### ISSUE TITLE
define object problem

### ISSUE THREAD

**Issue by fundon** [babel/babel#1006]
* defineProperties.js
* babel v4.7.8

The example `one` is failed when getting property.
The example `two` is working good.

Is it a issue? or I'm missing something.

```js
var context = {
  app: {
    context: {},
    logger: {}
  }
};

// exmaple_1
Object.defineProperties(context, {
  get config() {
    return this.app.config;
  },
  get logger() {
    return this.app.logger;
  }
});

// exmaple_2
Object.defineProperties(context, {
  config_2: {
    get() {
      return this.app.config;
    }
  },
  logger_2: {
    get() {
      return this.app.logger;
    }
  },
});

console.log(context.config);
console.log(context.config_2);
console.log(context.config === context.config_2);
```

`babel defineProperties.js`
```
"use strict";

var context = {
  app: {
    context: {},
    logger: {}
  }
};

// exmaple_1
Object.defineProperties(context, Object.defineProperties({}, {
  config: {
    get: function () {
      return this.app.config;
    },
    configurable: true,
    enumerable: true
  },
  logger: {
    get: function () {
      return this.app.logger;
    },
    configurable: true,
    enumerable: true
  }
}));

// exmaple_2
Object.defineProperties(context, {
  config_2: {
    get: function get() {
      return this.app.config;
    }
  },
  logger_2: {
    get: function get() {
      return this.app.logger;
    }
  } });

console.log(context.config);
console.log(context.config_2);
console.log(context.config === context.config_2);
```

`babel-node defineProperties`
```
/Users/fundon/dev/test/defineProperties.js:14
      return this.app.config;
                     ^
TypeError: Cannot read property 'config' of undefined
    at Object.defineProperties.Object.defineProperties.config.get [as config] (/Users/fundon/dev/test/defineProperties.js:11:20)
    at Function.defineProperties (native)
    at Object.<anonymous> (/Users/fundon/dev/test/defineProperties.js:9:8)
    at Module._compile (module.js:444:26)
    at normalLoader (/Users/fundon/.nvm/versions/io.js/v1.5.0/lib/node_modules/babel/lib/babel/api/register/node.js:119:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/fundon/.nvm/versions/io.js/v1.5.0/lib/node_modules/babel/lib/babel/api/register/node.js:132:7)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Function.Module.runMain (module.js:485:10)
    at Object.<anonymous> (/Users/fundon/.nvm/versions/io.js/v1.5.0/lib/node_modules/babel/bin/_babel-node:108:12)
```

**Comment by sebmck** [comment]
Yep that's expected behaviour. You're setting a getter on the define properties object which doesn't make any sense.

**Comment by zloirock** [comment]
@fundon emm... for such behavior, I suggest for you `mixin` / `Object.define` here https://github.com/babel/babel/issues/661#issuecomment-72431831

**Comment by fundon** [comment]
@zloirock Thanks
 But that must needs `babel-runtime`, I don't want to include this.
