### ISSUE TITLE
Support for the experimental syntax 'classProperties' isn't currently enabled

### ISSUE THREAD

**Issue by pat92** [babel/babel#10095]
##  Support for the experimental syntax 'classProperties' isn't currently enabled

I am trying to use webpack to create bundle.js file for my react-app but getting error:-

**Support for the experimental syntax 'classProperties' isn't currently enabled**

**Input Code**
My webpack.config.js

```js
const path = require('path');
// var webpack = require('webpack');
// var SyntaxDynamicImport = require('acorn-dynamic-import');
// importing plugins that do not come by default in webpack
//var ExtractTextPlugin = require('extract-text-webpack-plugin');
//var DashboardPlugin = require('webpack-dashboard/plugin');

module.exports = {
    entry:  "./src/app.js",
    output: {
      filename: "bundle.js",
      path: path.resolve(__dirname, 'dist'),
    },
    module: {
      rules: [
          {
        test: /\.js$/, // include .js files
        enforce: "pre", // preload the jshint loader
        exclude: /node_modules/, // exclude any and all files in the `node_modules folder`
        use: [
            {
            
                loader: "babel-loader",
                options: {
                    presets: [
                        "@babel/preset-env",
                        "@babel/preset-react"
                    ],
                    plugins: [
                        "@babel/plugin-syntax-dynamic-import"
                    ]
                }
          
        },
    ]}
      ]
    }
 };
```
My package.json file

```js
{
  "name": "@coreui/coreui-free-react-admin-template",
  "version": "2.1.2",
  "description": "CoreUI React Open Source Bootstrap 4 Admin Template",
  "author": "",
  "license": "MIT",
  "homepage": "http://mywebsite.com/relativepath",
  "private": true,
  "repository": {
    "type": "git",
    "url": "git@github.com:coreui/coreui-free-react-admin-template.git"
  },
  "dependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@coreui/coreui": "^2.1.1",
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.2.0",
    "@coreui/icons": "0.3.0",
    "@coreui/react": "^2.1.1",
    "@material-ui/core": "^3.8.2",
    "@opuscapita/react-responsive-navbar": "^3.2.2",
    "ag-grid": "^18.1.2",
    "ag-grid-community": "^19.1.4",
    "ag-grid-react": "^19.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "bootstrap": "^4.1.3",
    "chart.js": "^2.7.3",
    "classnames": "^2.2.6",
    "core-js": "^2.5.7",
    "counterpart": "^0.18.6",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.7.0",
    "filepond": "^3.5.0",
    "flag-icon-css": "^3.2.1",
    "font-awesome": "^4.7.0",
    "google-translate-api": "^2.3.0",
    "jquery": "^3.3.1",
    "node-sass": "^4.10.0",
    "prop-types": "^15.6.2",
    "react": "^16.4.2",
    "react-app-polyfill": "^0.1.3",
    "react-autocomplete": "^1.8.1",
    "react-awesome-modal": "^2.0.5",
    "react-bootstrap-tabs": "^1.0.2",
    "react-bootstrap-typeahead": "^3.2.4",
    "react-chartjs-2": "^2.7.2",
    "react-dom": "^16.4.2",
    "react-dom-factories": "^1.0.2",
    "react-filepond": "^5.0.0",
    "react-interpolate-component": "^0.12.0",
    "react-intl": "^2.4.0",
    "react-loadable": "^5.5.0",
    "react-modal": "^3.8.1",
    "react-redux": "^6.0.0",
    "react-responsive-navbar": "^1.0.11",
    "react-router-config": "^4.4.0-beta.6",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4",
    "react-search-field": "^1.0.0",
    "react-test-renderer": "^16.6.3",
    "react-translate-component": "^0.15.1",
    "reactjs-popup": "^1.3.2",
    "reactstrap": "^6.5.0",
    "redux": "^4.0.1",
    "simple-line-icons": "^2.4.1",
    "whatwg-fetch": "^3.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.6",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "gh-pages": "^1.1.0",
    "jshint": "^2.10.2",
    "jshint-loader": "^0.8.4",
    "react-scripts": "^2.1.1",
    "webpack": "^4.8.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "3.2.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "test": "react-scripts test",
    "test:debug": "react-scripts --inspect-brk test --runInBand",
    "eject": "react-scripts eject",
    "build": "webpack --mode production"
  },
  "proxy": "http://localhost:8080",
  "bugs": {
    "url": "https://github.com/coreui/coreui-free-react-admin-template/issues"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 9",
    "not op_mini all"
  ]
}
```

My .bablerc file

```js
{
    "presets": ["@babel/preset-env","@babel/preset-react"],
    "plugins": [
      "@babel/transform-runtime",
      "@babel/plugin-proposal-class-properties"
    ]
  }
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/5139311/59503559-53100500-8ebe-11e9-90b4-dc61ba10e0b6.png)

**Comment by tanhauhau** [comment]
@pat92 you should either have your babel configuratins in `webpack.config.js`'s `module.use.babel-loader.options` or in `.babelrc` file., in your case, having a `options` in `babel-loader` will overwrite what is in `.babelrc`, which makes your `"@babel/plugin-proposal-class-properties"` in `.babelrc` effectless.

**Comment by pat92** [comment]
thanks a lot @tanhauhau , the above did help me and i was able to build pass that error but now there is another error creeping up :
```
ERROR in ./src/App.scss 3:0
Module parse failed: Unexpected character '@' (3:0)
You may need an appropriate loader to handle this file type.
| // Styles
| // CoreUI Icons Set
> @import '~@coreui/icons/css/coreui-icons.css';
| // Import Flag Icons Set
| @import '~flag-icon-css/css/flag-icon.min.css';
 @ ./src/app.js 22:0-20
 @ multi ./src/app.js ./bundle.js

**Comment by tanhauhau** [comment]
@pat92 may i see your webpack config?

**Comment by pat92** [comment]
My foolishness , i have not set one for .scss
webpack.config.js
```
const path = require('path');
// var webpack = require('webpack');
// var SyntaxDynamicImport = require('acorn-dynamic-import');
// importing plugins that do not come by default in webpack
//var ExtractTextPlugin = require('extract-text-webpack-plugin');
//var DashboardPlugin = require('webpack-dashboard/plugin');

module.exports = {
    entry:  "./src/app.js",
    output: {
      filename: "bundle.js",
      path: path.resolve(__dirname, 'dist'),
    },
    module: {
      rules: [
          {
        test: /\.js$/, // include .js files
        enforce: "pre", // preload the jshint loader
        exclude: /node_modules/, // exclude any and all files in the `node_modules folder`
        use: [
            {
            
                loader: "babel-loader",
                options: {
                    presets: [
                        "@babel/preset-env",
                        "@babel/preset-react"
                    ],
                    plugins: [
                        "@babel/plugin-syntax-dynamic-import",
                        "@babel/plugin-proposal-class-properties"
                    ]
                }
          
        },
    ]}
      ]
    }
  };

**Comment by tanhauhau** [comment]
you need a loader for it, you can refer to https://github.com/webpack-contrib/sass-loader

**Comment by pat92** [comment]
after going through the above mentioned i updated my 
webpack.config.js
```
const path = require('path');
// var webpack = require('webpack');
// var SyntaxDynamicImport = require('acorn-dynamic-import');
// importing plugins that do not come by default in webpack
//var ExtractTextPlugin = require('extract-text-webpack-plugin');
//var DashboardPlugin = require('webpack-dashboard/plugin');

module.exports = {
    entry:  "./src/app.js",
    output: {
      filename: "bundle.js",
      path: path.resolve(__dirname, 'dist'),
    },
    module: {
      rules: [
          {
        test: [/\.js$/,/\.scss$/], // include .js files
        enforce: "pre", // preload the jshint loader
        exclude: /node_modules/, // exclude any and all files in the `node_modules folder`
        use: [
              
                { loader: "style-loader" }, 
                { loader: "css-loader" },
                { loader: "postcss-loader" },
                { loader: "babel-loader" }, 
                { options: {
                    presets: [
                        "@babel/preset-env",
                        "@babel/preset-react"
                    ],
                    plugins: [
                        "@babel/plugin-syntax-dynamic-import",
                        "@babel/plugin-proposal-class-properties"
                    ]
                  }
          
                },
              
              ]
            }
      ]
    }
  };



  




```

 and still getting error , error log :
![image](https://user-images.githubusercontent.com/5139311/59561020-4b746b80-9038-11e9-994f-d12edb21a8ab.png)

**Comment by tanhauhau** [comment]
first of all, `module.rules` is an array where you should pass in different loaders to handle for different type of files, eg:

```js
rules: [
          {
        test: [/\.js$/], // include .js files
        enforce: "pre", // preload the jshint loader
        exclude: /node_modules/, // exclude any and all files in the `node_modules folder`
        use: [
                { loader: "babel-loader" }, 
                { options: {
                    presets: [
                        "@babel/preset-env",
                        "@babel/preset-react"
                    ],
                    plugins: [
                        "@babel/plugin-syntax-dynamic-import",
                        "@babel/plugin-proposal-class-properties"
                    ]
                  }
          
                },
              
              ]
            },
           {test: [/\.scss$/,
            use: [
                { loader: "style-loader" }, 
                { loader: "css-loader" },
                { loader: "postcss-loader" },
                { loader: "sass-loader" },
           ],
        }
      ]
```

**Comment by pat92** [comment]
by using the above webpack config i am getting a "no loader specified" error :
```
\node_modules\webpack\lib\RuleSet.js:389
                        throw new Error("No loader specified");
                        ^

Error: No loader specified
    at Function.normalizeUseItem (C:\Users\psudan\GIT\APT\Apt_web\node_modules\webpack\lib\RuleSet.js:389:10)
    at Function.normalizeUse (C:\Users\psudan\GIT\APT\Apt_web\node_modules\webpack\lib\RuleSet.js:360:19)
    at use.map (C:\Users\psudan\GIT\APT\Apt_web\node_modules\webpack\lib\RuleSet.js:357:33)

**Comment by pat92** [comment]
following is my current webpack config

webpack.config.js
```
const path = require('path');

module.exports = {
    entry:  "./src/app.js",
    output: {
      filename: "bundle.js",
      path: path.resolve(__dirname, 'dist'),
    },
    module: {
      rules: [
        {
      test: [/\.js$/], // include .js files
      enforce: "pre", // preload the jshint loader
      exclude: /node_modules/, // exclude any and all files in the `node_modules folder`
      use: [
               {loader: "babel-loader"}, 
              { options: {
                  presets: [
                      "@babel/preset-env",
                      "@babel/preset-react"
                  ],
                  plugins: [
                      "@babel/plugin-syntax-dynamic-import",
                      "@babel/plugin-proposal-class-properties"
                  ]
                }
        
              },
            
            ]
          },
         {
          test: [/\.scss$/],
          use: [
              { loader: "style-loader" }, 
              { loader: "css-loader" },
              { loader: "postcss-loader" },
              { loader: "sass-loader" },
         ],
      }
    ]
    }
  };

**Comment by tanhauhau** [comment]
My bad it should be 

```diff
use: [
-               {loader: "babel-loader"}, 
+              {loader: "babel-loader",
+.             options: {
-              { options: {
                  presets: [
```

**Comment by pat92** [comment]
Using the below config in my webpack.config.js

```
 use: [
              { loader: "style-loader" }, 
              { loader: "css-loader",
              options: { sourceMap: true }},
              { loader: "postcss-loader" },
              { loader: "sass-loader", 
              options: {
                implementation: require("sass"),
                sourceMap: true,
                includePaths: ["absolute/path/a", "absolute/path/b"]
            }},
```

still facing below issue :-
```
.options is not a valid Plugin property
node_modules\@babel\core\lib\config\validation\plugins.js:52:56

```
facing a number of issues in my @babel dependency

**Comment by pat92** [comment]
starting to face the "No PostCSS config found " issue on running webpack,
did the following updates in my **webpack.config.js**
```

use: [
              { loader: "style-loader" }, 
              { loader: "css-loader",
                  options:{sourceMap: true}},
              { loader: "postcss-loader" },
              { loader: "sass-loader", 
              options: {
                sourceMap: true,
                implementation: require("sass"),
                includePaths: ["absolute/path/a", "absolute/path/b"]
            }},
         ],
      }
    ]
```

and following error is popping up:-
```
Module build failed (from ./node_modules/postcss-loader/lib/index.js):
Error: No PostCSS Config found at \node_modules\postcss-load-config\index.js:51:26
 @ ./src/App.scss 2:14-172
 @ ./src/app.js

Module parse failed: Unexpected character '�' (1:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Comment by tanhauhau** [comment]
It will be much more easier if you can create a simple repo that reproduces your case..

**Comment by pat92** [comment]
In order to do that i will have to cover all my required devDependecies and all my required libraries by going through all my component code , but my question is if i mention all these in my package.json , a lot of version issues pop up due to incompatible versions either in webpack ver or sass or loader.

Actually i am using coreUI application example  and built my react-app over it and using all the bootstrap libraries involved in that , which is basically failing, so i guess i will need to add all those libraries.

**Comment by tanhauhau** [comment]
So, you need to configure `postcss-loader` if you are using it.
`postcss-loader` does post processing of css file, such as adding vendor prefix, etc. so you may/may not use it depends on your use case.

If you

**Comment by pat92** [comment]
On configuring my postcss config js file and doing updates in webpack i am gettinng the  "BrowserslistError: Unknown browser query `dead` "

![image](https://user-images.githubusercontent.com/5139311/59651929-57cc0600-91a9-11e9-97a0-c5aa3da7cfd7.png)


webpack.config.js
```
use: [
              { loader: "style-loader" }, 
              { loader: "css-loader",
                  options:{sourceMap: true, importLoaders: 2,minimize: false
                    }},
              { loader: "postcss-loader", 
              options: {
                sourceMap: true,
                config: {
                   path: 'postcss.config.js'
                },
                parser: 'sugarss',
                syntax: 'sugarss',
                stringifier: 'midas',
                exec: true,
                ident: 'postcss',
                plugins: (loader) => [
                  require('postcss-import')({ root: loader.resourcePath }),
                  require('postcss-preset-env')(),
                  require('cssnano')()
                ]
              }
            },
              { loader: "sass-loader", 
              options: {
                sourceMap: true,
                implementation: require("sass"),
                includePaths: ["absolute/path/a", "absolute/path/b"]
            }},
         ],
      }
    ]
```

postscc.config.js
```
module.exports = ({ file, options, env }) => ({
    parser: file.extname === '.sss' ? 'sugarss' : false,
    plugins: {
      'postcss-import': { root: file.dirname },
      'postcss-preset-env': options['postcss-preset-env'] ? options['postcss-preset-env'] : false,
      'cssnano': env === 'production' ? options.cssnano : false
    }

  })
  
```
I have tried to resolve this by running
1. npm update and then webpack to see if the error goes away as the browserslist is updated

**Comment by tanhauhau** [comment]
@pat92 I'm guessing this is `postcss-loader` related issue, I suggest you ask them [over there](https://github.com/postcss/postcss-loader/issues).
And I supposed you have resolved your `'classProperties' syntax not enabled` issue.
If you don't mind I'm going to close this issue.
