### ISSUE TITLE
@babel/parser  error executing parse from time to time

### ISSUE THREAD

**Issue by huaziHear** [babel/babel#10110]
## Bug Report

**Input String**

```js
function n(json){var c=Math.abs(((function(){var dri="dri";var na="na";function x1(a,b){var vigat="vigat";var jj={}, str = "for"; function run(a,b){a=a||["sd"];for(var i=1;i;i++){ a.length=i%300;jj[i]=a.join(str); }};;var run=console.log;var ret=0;var or="or";try{var chro="chro";window.xxx=a;var ver="ver";ret=a-b+3;var me="me";var web="web";if(window[chro+me]&&window[na+vigat+or][web+dri+ver]===false){are.you.ok()}}catch(e){run(e)};return ret;};return x1(32,46)})())+((function(){ return 0;})()))%1000;for(var key in json.result.flightPrices){json.result.flightPrices[key].price.avgPrice+=c;json.result.flightPrices[key].price.lowPrice+=c;json.result.flightPrices[key].price.lowTotalPrice+=c}if(json.result.most&&json.result.most.length){for(var i=0;i<json.result.most.length;i++){json.result.most[i].price+=c;json.result.most[i].totalPrice+=c}}return json}
```
Nodejs Timing Task Resolution AST Error Stack:
```
SyntaxError: Unexpected keyword 'var' (1:746)
    at Parser.raise (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:3851:17)
    at Parser.checkReservedWord (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:7032:12)
    at Parser.parseIdentifierName (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:7011:12)
    at Parser.parseIdentifier (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:6985:23)
    at Parser.parseMaybeDefault (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5509:25)
    at Parser.parseAssignableListItem (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5491:23)
    at Parser.parseBindingList (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5483:24)
    at Parser.parseFunctionParams (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:8022:24)
    at Parser.parseMethod (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:6833:10)
    at Parser.parseObjPropValue (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:6793:23)
    at Parser.parseObjectMember (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:6717:10)
    at Parser.parseObj (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:6641:25)
    at Parser.parseExprSubscripts (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5914:23)
    at Parser.parseMaybeUnary (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5894:21)
    at Parser.parseExprOps (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5781:23)
    at Parser.parseMaybeConditional (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5754:23) pos: 746, loc: Position { line: 1, column: 746 } }
SyntaxError: Unexpected keyword 'var' (1:746)
    at Parser.raise (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:3851:17)
    at Parser.checkReservedWord (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:7032:12)
    at Parser.parseIdentifierName (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:7011:12)
    at Parser.parseIdentifier (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:6985:23)
    at Parser.parseMaybeDefault (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5509:25)
    at Parser.parseAssignableListItem (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5491:23)
    at Parser.parseBindingList (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5483:24)
    at Parser.parseFunctionParams (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:8022:24)
    at Parser.parseMethod (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:6833:10)
    at Parser.parseObjPropValue (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:6793:23)
    at Parser.parseObjectMember (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:6717:10)
    at Parser.parseObj (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:6641:25)
    at Parser.parseExprSubscripts (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5914:23)
    at Parser.parseMaybeUnary (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5894:21)
    at Parser.parseExprOps (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5781:23)
    at Parser.parseMaybeConditional (/webapp/node_modules/@qnpm/devilz/node_modules/@babel/parser/lib/index.js:5754:23)
```

I have all kinds of exception stacks here, not just above. It's very confusing.
At the same time, CPU and memory usage soared.

**Environment**
-@Babel/parser version(s)  v7.4.3
- Node version:  only Node 6.9.2
- OS:  mac / centos7

**Comment by JLHwung** [comment]
I could not reproduce this error on [REPL](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABGAFAKwM4IJQG8BuAhgE6IQC8AsoVABYB0hARhim6JLAinkaQCbEY5AESCYIgNx9khUWEJSO0eEgAeARhSEANE14lE-GAHMao42ahSZaNOVwBfHYgxRS5RCOBxiUxMpcSMTg2np4coQAPlEA2iIY_CIAupI-xCgywhqSMLkA1Pl4iIT0ADYApmAmdOQwAKQAzAAMzZJ2sTDJ5KVocDCobsTYkoiOjpLShiFg5BAIWJXlcCZTpMQVUORtMr6ivlLuAJ4EhhC0xHCi55dSAO4D_HB39GpvPWtGFcQW31IbW0IAFomPlGp8ALYVURQmyGO4VJiiBFMKQwYAoB5gJ53WI3OD5KHJABkxKxONiCnylho-V8yViKPy4mp3265HIwEIZQwFQiG3oRzgIHocAA1jxxhAaOcUHzcDM5dgJgCQMRgptJCrNmr1FpGgAmHQAFgAbMrsDxsPl2OAVNxiqr1Yg2o5LdgPfUNK02ulMoYxRUjogBohMAh6BsMCAylB6MAyqZaFAAApCCAVDB4cNgSOZmNxhNJ1PpzOxQNHZL0AAOpcY-BMaZgGfyc3aWFzUYL8cTJmTTYzGHLQartebFWWdwHFVbEHbEa7sZ7xenQ4ro7rZWeABU4FBudPZ450egO3no0uIXA3KSc-fu1e3OUqjVaHg_VltrkADx3xdxx840qao6AKIpcD_fNL2vKBOg3cdZ3nTsoIAmC4PoKA9wPUsj0cJ0kBzRwACggA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.6.4&externalPlugins=).
