### ISSUE TITLE
Unknown helper objectSpread2

### ISSUE THREAD

**Issue by slavafomin** [babel/babel#10169]
Hello!

Thank you for your hard work.

However, I'm getting the following error when trying to compile my package using Babel with Rollup:

```
ReferenceError: Unknown helper objectSpread2
  at loadHelper (~/project/node_modules/@babel/helpers/lib/index.js:238:27)
  at Object.getDependencies (~/project/node_modules/@babel/helpers/lib/index.js:279:21)
  at File.addHelper (~/project/node_modules/@babel/core/lib/transformation/file/file.js:204:33)
  at PluginPass.addHelper (~/project/node_modules/@babel/core/lib/transformation/plugin-pass.js:31:22)
  at PluginPass.ObjectExpression (~/project/tumbleweed/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js:379:25)
  at newFn (~/project/node_modules/@babel/traverse/lib/visitors.js:193:21)
  at NodePath._call (~/project/node_modules/@babel/traverse/lib/path/context.js:53:20)
  at NodePath.call (~/project/node_modules/@babel/traverse/lib/path/context.js:40:17)
  at NodePath.visit (~/project/node_modules/@babel/traverse/lib/path/context.js:88:12)
  at TraversalContext.visitQueue (~/project/node_modules/@babel/traverse/lib/context.js:118:16)

  code: 'PLUGIN_ERROR',
  helper: 'objectSpread2',
  pluginCode: 'BABEL_HELPER_UNKNOWN',
  plugin: 'babel',
  hook: 'transform',
  id: '~/project/file.ts'
```

I've tried to additionally install the `@babel/runtime`, but it didn't help.

Here's my config for `rollup-plugin-babel`:

```json
{
  "babelConfig": {
    "extensions": [
      ".js",
      ".jsx",
      ".ts",
      ".tsx"
    ],
    "root": "~/project",
    "babelrc": false,
    "runtimeHelpers": true,
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": "extends @acme/browserslist-config"
        }
      ]
    ],
    "plugins": [
      [
        "@babel/plugin-transform-runtime",
        {
          "corejs": 3
        }
      ]
    ],
    "exclude": [
      "**/node_modules/**"
    ]
  }
}
```

The file in question is just a regular TypeScript file, which uses spread operator to merge objects. I'm processing TypeScript code using `rollup-plugin-typescript2` before feeding it to Babel. The TypeScript compiler is configured to output ESNext code in ESM format.

Do you have any clues, what could be causing this? Any suggestions will be highly appreciated.

---

The dependencies are:

```
    "@babel/core": "^7.5.0",
    "@babel/plugin-transform-runtime": "^7.5.0",
    "@babel/preset-env": "^7.5.0",
    "@babel/runtime": "^7.5.0",
    "rollup": "^1.16.4",
    "rollup-plugin-babel": "^4.3.3",
    "rollup-plugin-commonjs": "^10.0.1",
    "rollup-plugin-typescript2": "^0.21.2",
    "typescript": "^3.5.2"
```

Thank you!

**Comment by grekko** [comment]
@slavafomin I just had the same issue and the error was due to different versions of `@babel/core` and `@babel/preset-env` in my package.json.

**Comment by danielmahon** [comment]
Having the same issue pop up all of a sudden, not sure why... I needed to force `babel-preset-react-app` to use `@babel/runtime@7.5.0` as `7.4.3` doesn't include `objectSpread2`.
```js
  "resolutions": {
    "**/@babel/runtime": "7.5.0"
  },
```
