### ISSUE TITLE
 Files that are converted by @babel/plugin-transform-modules-commonjs cannot be required to be imported

### ISSUE THREAD

**Issue by yinshipeng** [babel/babel#10160]
## Bug Report

**Current Behavior**
After converting the es6 specification module to the commonjs specification, it cannot be introduced by require

**Input Code**

```js
gulp.src('src/router/*.js')
        .pipe(babel({
            plugins: ['@babel/plugin-transform-modules-commonjs']
        }))
        .pipe(gulp.dest('temp'));
```
After the above code transformation:
```js
"use strict";

var _interopRequireDefault = require("/Users/wang/Documents/workspace/douban/douban-h5/node_modules/@babel/runtime-corejs2/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _toConsumableArray2 = _interopRequireDefault(require("/Users/wang/Documents/workspace/douban/douban-h5/node_modules/@babel/runtime-corejs2/helpers/esm/toConsumableArray"));

var _home = _interopRequireDefault(require("./home.router"));

var _rank = _interopRequireDefault(require("./rank.router"));

var routers = [].concat((0, _toConsumableArray2.default)(_home.default), (0, _toConsumableArray2.default)(_rank.default));
var _default = routers;
exports.default = _default;
```

Problems occur when using require to introduce transformed files:

```js
/Users//Documents/workspace/douban/douban-h5/node_modules/@babel/runtime-corejs2/helpers/esm/toConsumableArray.js:1
(function (exports, require, module, __filename, __dirname) { import arrayWithoutHoles from "./arrayWithoutHoles";
                                                                     ^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

After check found because/Users/wang/Documents/workspace/douban/douban-h5 / node_modules / @ Babel/runtime-corejs2 / helpers/esm/toConsumableArray js files use or es6 specification：

```js
import arrayWithoutHoles from "./arrayWithoutHoles";
import iterableToArray from "./iterableToArray";
import nonIterableSpread from "./nonIterableSpread";
export default function _toConsumableArray(arr) {
  return arrayWithoutHoles(arr) || iterableToArray(arr) || nonIterableSpread();
}
```

**package.json  devDependencies**

```js
"devDependencies": {
        "@babel/plugin-transform-modules-commonjs": "^7.4.4",
        "@vue/cli-plugin-babel": "^3.4.0",
        "@vue/cli-plugin-eslint": "^3.4.0",
        "@vue/cli-service": "^3.4.0",
        "@vue/eslint-config-standard": "^4.0.0",
        "babel-eslint": "^10.0.1",
        "babel-plugin-import": "^1.12.0",
        "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
        "eslint": "^5.8.0",
        "eslint-plugin-vue": "^5.0.0",
        "gulp": "^4.0.2",
        "gulp-babel": "^8.0.0",
        "html-webpack-plugin": "^3.2.0",
        "husky": "^1.3.1",
        "json-server": "^0.14.2",
        "less": "^3.9.0",
        "less-loader": "^5.0.0",
        "mockjs": "^1.0.1-beta3",
        "node-sass": "^4.9.0",
        "page-skeleton-webpack-plugin": "^0.10.12",
        "postcss-pxtorem": "^4.0.1",
        "sass-loader": "^7.1.0",
        "vue-template-compiler": "^2.5.21",
        "webp-loader": "^0.5.0"
    }
```

- Node/npm version: [v10.15.3/npm 6.4.1]
- OS: [e.g. OSX 10.13.4]

**Comment by nicolo-ribaudo** [comment]
What it your other Babel config? It doesn't injects those imports by default.

**Comment by yinshipeng** [comment]
I'm using the scaffolding of vue-cli3, and the Babel configuration is using the scaffolding by default, which is the address of the configuration file(https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/index.js).
Please check to see if there is any problem.

**Comment by nicolo-ribaudo** [comment]
That preset is configured to use es6-style helpers, since it should be used with webpack or rollup. If you want to disable that behavior, you can use the `VUE_CLI_BABEL_TRANSPILE_MODULES` env variable:

```
VUE_CLI_BABEL_TRANSPILE_MODULES=true gulp build
```

**Comment by yinshipeng** [comment]
Your method is correct. It has been solved. Thank you very much！
