### ISSUE TITLE
Require hook not working in projects that are installed globally

### ISSUE THREAD

**Issue by robrichard** [babel/babel#1018]
I installed babel into my project and ```require('babel/register')``` first thing in the entry. The project is written with es6 and it works fine when I run it locally. However after publishing it to our npm registry and installing it globally it does not work. Is this a known issue?

```
/usr/local/lib/node_modules/dibs-cutman/lib/versionHelpers.js:12
    validateVersion(version) {
                   ^
SyntaxError: Unexpected token (
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/dibs-cutman/node_modules/babel/lib/babel/api/register/node.js:130:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/dibs-cutman/index.js:9:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by AluisioASG** [comment]
Yes, the issue being the hook not compiling stuff under any `node_modules` by default.  You can either use a prepublish script to transpile your code ahead of publishing, use `require('babel/register')({ignore: false})` to transpile **all** files or pass a regex (like ``new RegExp(`^${escapeRE(__dirname)}(?!.node_modules)` ``) as `ignore` to transpile only matching files.

**Comment by sebmck** [comment]
Yep, what @AluisioASG is correct.
