### ISSUE TITLE
Error when using decorator in legacy mode

### ISSUE THREAD

**Issue by yeongjet** [babel/babel#10221]
I just asked the same question [here](https://github.com/nestjs/nest/issues/2576). Is babel's problem?

**Comment by amites** [comment]
Running into the same issue -- this seems specific to plugin `["@babel/plugin-proposal-decorators", { "legacy": true }]`

will update as I find a workaround

**Comment by Fortur** [comment]
@yeongjet Do you find the workaround?

**Comment by Fortur** [comment]
Hi, if found solution for this bug in nest.js: 

instead of this code
```js
@Post()
async create(@Body() createCatDto) {
  return console.log(createCatDto);
}
```

you need to use this
```js
@Post()
@Bind(Body())
async create(createCatDto) {
  return console.log(createCatDto);
}
```

**Comment by sbrudz** [comment]
`@Body` is being used as a parameter decorator, which requires ["babel-plugin-parameter-decorator"](https://www.npmjs.com/package/babel-plugin-parameter-decorator) in addition to "@babel/plugin-proposal-decorators" for it to work.

**Comment by starikcetin** [comment]
> `@Body` is being used as a parameter decorator, which requires ["babel-plugin-parameter-decorator"](https://www.npmjs.com/package/babel-plugin-parameter-decorator) in addition to "@babel/plugin-proposal-decorators" for it to work.

THANK YOU! I have been searching all over the internet for about 3 hours now. You should write an article about this or something.

For future reference, I was trying to get [`tsoa`](https://github.com/lukeautry/tsoa) to work with Babel 7, and this solution by @sbrudz solves `SyntaxError: Invalid or unexpected token` error for parameter decorators such as `@Query` and `@Path`.

**Comment by ZeeshanAhmadKhalil** [comment]
I already have `"@babel/plugin-proposal-decorators": "^7.18.6",` in my devDependencies but still getting the issue :(

**Comment by liuxingbaoyu** [comment]
@ZeeshanAhmadKhalil Can you provide a repository to reproduce?

**Comment by ZeeshanAhmadKhalil** [comment]
@liuxingbaoyu  just added `"babel-plugin-parameter-decorator": "^1.0.16",` and `@Body() body` is working in params.

But now I am getting the following errors when using `@nestjs/swagger`. it looks like I have to find what I am doing wrong in nestjs docs.

```
C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\services\parameter-metadata-accessor.js:14
            type: types[param.index],
                       ^

TypeError: Cannot read properties of undefined (reading '0')
    at C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\services\parameter-metadata-accessor.js:14:24
    at C:\Projects\CreditRepair\credit-repair-scraper\node_modules\lodash\lodash.js:13469:38
    at C:\Projects\CreditRepair\credit-repair-scraper\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\lodash\lodash.js:3032:24)
    at mapValues (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\lodash\lodash.js:13468:7)
    at ParameterMetadataAccessor.explore (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\services\parameter-metadata-accessor.js:13:59)
    at exploreApiParametersMetadata (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\explorers\api-parameters.explorer.js:18:58)
    at C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\swagger-explorer.js:72:45
    at Array.reduce (<anonymous>)
    at C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\swagger-explorer.js:71:104
    at C:\Projects\CreditRepair\credit-repair-scraper\node_modules\lodash\lodash.js:13469:38
    at C:\Projects\CreditRepair\credit-repair-scraper\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\lodash\lodash.js:3032:24)
    at mapValues (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\lodash\lodash.js:13468:7)
    at MapIterator.iteratee (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\swagger-explorer.js:71:59)
    at MapIterator.next (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\iterare\src\map.ts:9:39)
    at FilterIterator.next (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\iterare\src\filter.ts:11:34)
    at IteratorWithOperators.next (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\iterare\src\iterate.ts:19:28)
    at Function.from (<anonymous>)
    at IteratorWithOperators.toArray (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\iterare\src\iterate.ts:227:22)
    at MetadataScanner.scanFromPrototype (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\core\metadata-scanner.js:12:14)
    at SwaggerExplorer.generateDenormalizedDocument (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\swagger-explorer.js:63:56)
    at SwaggerExplorer.exploreController (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\swagger-explorer.js:49:21)   
    at C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\swagger-scanner.js:49:84
    at Array.map (<anonymous>)
    at SwaggerScanner.scanModuleRoutes (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\swagger-scanner.js:49:56)      
    at C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\swagger-scanner.js:39:41
    at Array.map (<anonymous>)
    at SwaggerScanner.scanApplication (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\swagger-scanner.js:27:43)       
    at Function.createDocument (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@nestjs\swagger\dist\swagger-module.js:14:41)
    at _callee$ (C:\Projects\CreditRepair\credit-repair-scraper\src\/main.js:17:34)
    at tryCatch (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Projects\CreditRepair\credit-repair-scraper\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[nodemon] app crashed - waiting for file changes before starting...


```

**Comment by ZeeshanAhmadKhalil** [comment]
just added `"babel-plugin-parameter-decorator": "^1.0.16",` and `@Body() body` is working in params.

But now I am getting the following errors when using `@nestjs/swagger`. it looks like I have to find what I am doing wrong in nestjs docs.

```
C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\services\parameter-metadata-accessor.js:14
            type: types[param.index],
                       ^

TypeError: Cannot read properties of undefined (reading '0')
    at C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\services\parameter-metadata-accessor.js:14:24
    at C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:13469:38
    at C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:3032:24)
    at mapValues (C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:13468:7)
    at ParameterMetadataAccessor.explore (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\services\parameter-metadata-accessor.js:13:59)
    at exploreApiParametersMetadata (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\explorers\api-parameters.explorer.js:18:58)
    at C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-explorer.js:72:45
    at Array.reduce (<anonymous>)
    at C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-explorer.js:71:104
    at C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:13469:38
    at C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:3032:24)
    at mapValues (C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:13468:7)
    at MapIterator.iteratee (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-explorer.js:71:59)
    at MapIterator.next (C:\Projects\<PROJECT_PATH>\node_modules\iterare\src\map.ts:9:39)
    at FilterIterator.next (C:\Projects\<PROJECT_PATH>\node_modules\iterare\src\filter.ts:11:34)
    at IteratorWithOperators.next (C:\Projects\<PROJECT_PATH>\node_modules\iterare\src\iterate.ts:19:28)
    at Function.from (<anonymous>)
    at IteratorWithOperators.toArray (C:\Projects\<PROJECT_PATH>\node_modules\iterare\src\iterate.ts:227:22)
    at MetadataScanner.scanFromPrototype (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\core\metadata-scanner.js:12:14)
    at SwaggerExplorer.generateDenormalizedDocument (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-explorer.js:63:56)
    at SwaggerExplorer.exploreController (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-explorer.js:49:21)   
    at C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-scanner.js:49:84
    at Array.map (<anonymous>)
    at SwaggerScanner.scanModuleRoutes (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-scanner.js:49:56)      
    at C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-scanner.js:39:41
    at Array.map (<anonymous>)
    at SwaggerScanner.scanApplication (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-scanner.js:27:43)       
    at Function.createDocument (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-module.js:14:41)
    at _callee$ (C:\Projects\<PROJECT_PATH>\src\/main.js:17:34)
    at tryCatch (C:\Projects\<PROJECT_PATH>\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Projects\<PROJECT_PATH>\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Projects\<PROJECT_PATH>\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Projects\<PROJECT_PATH>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Projects\<PROJECT_PATH>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[nodemon] app crashed - waiting for file changes before starting...


```

**Comment by Tyranwyn** [comment]
> just added `"babel-plugin-parameter-decorator": "^1.0.16",` and `@Body() body` is working in params.
> 
> But now I am getting the following errors when using `@nestjs/swagger`. it looks like I have to find what I am doing wrong in nestjs docs.
> 
> ```
> C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\services\parameter-metadata-accessor.js:14
>             type: types[param.index],
>                        ^
> 
> TypeError: Cannot read properties of undefined (reading '0')
>     at C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\services\parameter-metadata-accessor.js:14:24
>     at C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:13469:38
>     at C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:4967:15
>     at baseForOwn (C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:3032:24)
>     at mapValues (C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:13468:7)
>     at ParameterMetadataAccessor.explore (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\services\parameter-metadata-accessor.js:13:59)
>     at exploreApiParametersMetadata (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\explorers\api-parameters.explorer.js:18:58)
>     at C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-explorer.js:72:45
>     at Array.reduce (<anonymous>)
>     at C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-explorer.js:71:104
>     at C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:13469:38
>     at C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:4967:15
>     at baseForOwn (C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:3032:24)
>     at mapValues (C:\Projects\<PROJECT_PATH>\node_modules\lodash\lodash.js:13468:7)
>     at MapIterator.iteratee (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-explorer.js:71:59)
>     at MapIterator.next (C:\Projects\<PROJECT_PATH>\node_modules\iterare\src\map.ts:9:39)
>     at FilterIterator.next (C:\Projects\<PROJECT_PATH>\node_modules\iterare\src\filter.ts:11:34)
>     at IteratorWithOperators.next (C:\Projects\<PROJECT_PATH>\node_modules\iterare\src\iterate.ts:19:28)
>     at Function.from (<anonymous>)
>     at IteratorWithOperators.toArray (C:\Projects\<PROJECT_PATH>\node_modules\iterare\src\iterate.ts:227:22)
>     at MetadataScanner.scanFromPrototype (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\core\metadata-scanner.js:12:14)
>     at SwaggerExplorer.generateDenormalizedDocument (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-explorer.js:63:56)
>     at SwaggerExplorer.exploreController (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-explorer.js:49:21)   
>     at C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-scanner.js:49:84
>     at Array.map (<anonymous>)
>     at SwaggerScanner.scanModuleRoutes (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-scanner.js:49:56)      
>     at C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-scanner.js:39:41
>     at Array.map (<anonymous>)
>     at SwaggerScanner.scanApplication (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-scanner.js:27:43)       
>     at Function.createDocument (C:\Projects\<PROJECT_PATH>\node_modules\@nestjs\swagger\dist\swagger-module.js:14:41)
>     at _callee$ (C:\Projects\<PROJECT_PATH>\src\/main.js:17:34)
>     at tryCatch (C:\Projects\<PROJECT_PATH>\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
>     at Generator._invoke (C:\Projects\<PROJECT_PATH>\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
>     at Generator.next (C:\Projects\<PROJECT_PATH>\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
>     at asyncGeneratorStep (C:\Projects\<PROJECT_PATH>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
>     at _next (C:\Projects\<PROJECT_PATH>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> [nodemon] app crashed - waiting for file changes before starting...
> ```

Did you find a solution for this?
