### ISSUE TITLE
React Fragment Short Syntax Colon

### ISSUE THREAD

**Issue by juliusza** [babel/babel#10238]
## Bug Report

**Current Behavior**
`
TypeError: Cannot read property 'name' of undefined
      at name (src/node-helpers.js:9:8)
      at enter (src/parse.js:230:13)
      at NodePath._call (node_modules\@babel\traverse\lib\path\context.js:53:20)
      at NodePath.call (node_modules\@babel\traverse\lib\path\context.js:40:17)
      at NodePath.visit (node_modules\@babel\traverse\lib\path\context.js:88:12)
      at TraversalContext.visitQueue (node_modules\@babel\traverse\lib\context.js:118:16)
      at TraversalContext.visitMultiple (node_modules\@babel\traverse\lib\context.js:85:17)
      at TraversalContext.visit (node_modules\@babel\traverse\lib\context.js:144:19)
      at Function.traverse.node (node_modules\@babel\traverse\lib\index.js:94:17)
      at NodePath.visit (node_modules\@babel\traverse\lib\path\context.js:95:18)
      at TraversalContext.visitQueue (node_modules\@babel\traverse\lib\context.js:118:16)
      at TraversalContext.visitSingle (node_modules\@babel\traverse\lib\context.js:90:19)
      at TraversalContext.visit (node_modules\@babel\traverse\lib\context.js:146:19)
      at Function.traverse.node (node_modules\@babel\traverse\lib\index.js:94:17)
      at NodePath.visit (node_modules\@babel\traverse\lib\path\context.js:95:18)
      at TraversalContext.visitQueue (node_modules\@babel\traverse\lib\context.js:118:16)
      at TraversalContext.visitSingle (node_modules\@babel\traverse\lib\context.js:90:19)
      at TraversalContext.visit (node_modules\@babel\traverse\lib\context.js:146:19)
      at Function.traverse.node (node_modules\@babel\traverse\lib\index.js:94:17)
      at NodePath.visit (node_modules\@babel\traverse\lib\path\context.js:95:18)
      at TraversalContext.visitQueue (node_modules\@babel\traverse\lib\context.js:118:16)
      at TraversalContext.visitMultiple (node_modules\@babel\traverse\lib\context.js:85:17)
      at TraversalContext.visit (node_modules\@babel\traverse\lib\context.js:144:19)
      at Function.traverse.node (node_modules\@babel\traverse\lib\index.js:94:17)
      at NodePath.visit (node_modules\@babel\traverse\lib\path\context.js:95:18)
      at TraversalContext.visitQueue (node_modules\@babel\traverse\lib\context.js:118:16)
      at TraversalContext.visitMultiple (node_modules\@babel\traverse\lib\context.js:85:17)
      at TraversalContext.visit (node_modules\@babel\traverse\lib\context.js:144:19)
      at Function.traverse.node (node_modules\@babel\traverse\lib\index.js:94:17)
      at NodePath.visit (node_modules\@babel\traverse\lib\path\context.js:95:18)
      at TraversalContext.visitQueue (node_modules\@babel\traverse\lib\context.js:118:16)
      at TraversalContext.visitSingle (node_modules\@babel\traverse\lib\context.js:90:19)
      at TraversalContext.visit (node_modules\@babel\traverse\lib\context.js:146:19)
      at Function.traverse.node (node_modules\@babel\traverse\lib\index.js:94:17)
      at traverse (node_modules\@babel\traverse\lib\index.js:76:12)

`

**Input Code**
I'm parsing JSX fragment:

```jsx
<>
    { gettext('Fragment short syntax') }: {'foo'}
</>
```

this only happens when short fragment syntax is used in combination with colon character

**Environment**
- Babel version(s): 7.5.5

**Comment by juliusza** [comment]
nvm, just realized the error is not within babel code
