### ISSUE TITLE
Named capturing groups cause crashes on the unicode regexp transform

### ISSUE THREAD

**Issue by Jessidhia** [babel/babel#10367]
## Bug Report

**Current Behavior**
Adding the `u` flag to a regexp with a named capturing group causes babel to crash if any transform related to unicode regexps is also enabled. This happens even when the named capturing group transform is enabled in preset-env, likely due to plugin execution order.

**Input Code**
- [REPL link](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=true&loose=false&code_lz=PTAECcFMFsHsDcCWA7A5qALgC0QZ1AETyyIAmBoMiG-K8AhgDZmgDGspkAUMS8ABQAdXAEpgPEqVADhYgK4S-_APwAeXAAd6rSAD5Z4kKDnJ20aJGQYU6bHjb05uSPnqgt4Z5XDhY4LiC8UgJqmtp6BgpAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=Node-8.9&version=7.5.5&externalPlugins=)

```js
void /(?<test>foo)/u
```

**Expected behavior/code**
```js
void _wrapRegExp(/(foo)/, {
  test: 1
})
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "env"
  ]
}
```

**Environment**
- Babel version(s): 7.4.3
- Node/npm version: 12.6.0
- OS: macOS 10.14
- Monorepo: yes
- How you are using Babel: loader

**Possible Solution**
The named capturing group transform could run before the other transforms; or regexpu should get support for parsing and preserving named capturing groups

**Additional context/Screenshots**
While writing a reproduction to this I also [found an emit bug](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=true&loose=false&code_lz=PQQ2G4ChgCgfgDwBcCmBnJA-EBKYkg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=Node-8.9&version=7.5.5&externalPlugins=) when babel helpers are injected and the first statement is a regexp literal. Not related, just a coincidence.

**Comment by Jessidhia** [comment]
Even making the named capture plugin run first doesn't help here; there's something weird with the unicode parsing in `regexp-tree`.

This actual regexp breaks on it: `/(?<name>[^+]+?)(?:\..+)?$/u`

```
invalid Unicode escape \.
    at Object.lexRules (.../node_modules/regexp-tree/dist/parser/generated/regexp-tree.js:442:11)
    at Object.getNextToken (.../node_modules/regexp-tree/dist/parser/generated/regexp-tree.js:580:32)
    at Object.parse (.../node_modules/regexp-tree/dist/parser/generated/regexp-tree.js:809:27)
    at Object.regexpTreeParser.parse (.../node_modules/regexp-tree/dist/parser/index.js:22:10)
    at Object.transform (.../node_modules/regexp-tree/dist/transform/index.js:129:20)
    at .../node_modules/regexp-tree/dist/compat-transpiler/index.js:36:27
    at Array.forEach (<anonymous>)
    at Object.transform (.../node_modules/regexp-tree/dist/compat-transpiler/index.js:28:22)
    at Object.compatTranspile (.../node_modules/regexp-tree/dist/regexp-tree.js:148:29)
    at PluginPass.RegExpLiteral (.../node_modules/@babel/plugin-transform-named-capturing-groups-regex/lib/index.js:41:46)
```

Changing the `\..` to `\\..` or just `..` gets rid of the crash, but it's not the same regexp.
