### ISSUE TITLE
 Requires Babel "^7.0.0-0", but was loaded with "6.26.3".

### ISSUE THREAD

**Issue by xwb007** [babel/babel#10389]
**error：**
`Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure
you have a compatible version of @babel/core, it is likely that something in you
r build process is loading the wrong version. Inspect the stack trace of this er
ror to look for the first entry that doesn't mention "@babel/core" or "babel-cor
e" to see what is calling Babel.
    at throwVersionError (D:\DengWei\xwb-react-markdown\node_modules\@babel\help
er-plugin-utils\lib\index.js:65:11)
    at Object.assertVersion (D:\DengWei\xwb-react-markdown\node_modules\@babel\h
elper-plugin-utils\lib\index.js:13:11)
    at _default (D:\DengWei\xwb-react-markdown\node_modules\@babel\plugin-propos
al-class-properties\lib\index.js:29:7)
    at D:\DengWei\xwb-react-markdown\node_modules\@babel\helper-plugin-utils\lib
\index.js:19:12
    at Function.memoisePluginContainer (C:\Users\Administrator\AppData\Roaming\n
pm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\option
s\option-manager.js:113:13)
    at Function.normalisePlugin (C:\Users\Administrator\AppData\Roaming\npm\node
_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\optio
n-manager.js:146:32)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\node_mo
dules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\Administrator\AppData\Roaming\npm\nod
e_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\opti
on-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\Administrator\AppData\Roaming\npm\no
de_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\opt
ion-manager.js:234:36)
    at OptionManager.init (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-mana
ger.js:368:12)
    at File.initOptions (C:\Users\Administrator\AppData\Roaming\npm\node_modules
\babel-cli\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-c
li\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\babel-cli\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-
cli\lib\babel\util.js:50:22)
    at Object.compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\b
abel-cli\lib\babel\util.js:59:12)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\lib\bab
el\file.js:142:23
    at Array.forEach (<anonymous>)
    at walk (C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\l
ib\babel\file.js:133:16)
    at files (C:\Users\Administrator\AppData\Roaming\npm\node_modules\babel-cli\
lib\babel\file.js:156:7)
    at module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\b
abel-cli\lib\babel\file.js:184:5)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\babel-cli\lib\babel\index.js:129:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xwb-react-markdown@1.0.0 build: `babel src/Markdown/index.jsx --out-fil
e ./lib/markdown.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xwb-react-markdown@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-09-04T0
5_42_22_376Z-debug.log`

**config:**
`"devDependencies": {
		"@babel/core": "^7.5.5",
		"@babel/plugin-proposal-class-properties": "^7.5.5",
		"@babel/preset-env": "^7.5.5",
		"@babel/preset-react": "^7.0.0",
		"babel-loader": "^8.0.6",
                ...
	},`

**Comment by nicolo-ribaudo** [comment]
What does `npx nls why babel-core` print? How are you running Babel?

**Comment by nicolo-ribaudo** [comment]
You need to run it with `@babel/cli, not with `babel-cli`

**Comment by xwb007** [comment]
> You need to run it with `@babel/cli, not with `babel-cli`

thank you
