### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by joeyhub** [babel/babel#10387]
```
"plugins": [["transform-runtime", {"regenerator": true}]],
```

```
index.jsx: this.setDynamic is not a function
    at PluginPass.pre (nodules/babel-plugin-transform-runtime/lib/index.js:31:12)
    at transformFile (nodules/@babel/core/lib/transformation/index.js:78:27)
    at runSync (nodules/@babel/core/lib/transformation/index.js:45:3)
    at Object.transformSync (nodules/@babel/core/lib/transform.js:43:38)
    at babel7 (nodules/parcel-bundler/src/transforms/babel/babel7.js:31:17)
    at async babelTransform (nodules/parcel-bundler/src/transforms/babel/transform.js:13:5)
    at async JSAsset.pretransform (nodules/parcel-bundler/src/assets/JSAsset.js:83:5)
    at async JSAsset.process (nodules/parcel-bundler/src/Asset.js:213:7)
    at async Pipeline.processAsset (nodules/parcel-bundler/src/Pipeline.js:46:7)
    at async Pipeline.process (nodules/parcel-bundler/src/Pipeline.js:24:23)
```

```
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "babel-plugin-transform-runtime": "^6.23.0",
```

node v12.7.0

**Comment by joeyhub** [comment]
Wrong repo

**Comment by joeyhub** [comment]
Not the wrong repo!

**Comment by joeyhub** [comment]
Needs `@babel/plugin-transform-runtime` rather than `babel-plugin-transform-runtime` but lots of places all over the internet refer to the old and NPM can't handle version compatibility.

**Comment by joeyhub** [comment]
Still happening with `"@babel/plugin-transform-runtime": "^7.5.5",`

**Comment by joeyhub** [comment]
Is babel doing something evil?

If you have the old one in your rc then it seems to magically add it to devDependencies with the wrong prefix.

**Comment by JLHwung** [comment]
`babel-plugin-transform-runtime` is not supposed to work with Babel 7. We understand it would cause troubles when people are upgrading from 6 to 7 so we try our best to update babel's [official document](https://babeljs.io/docs/en/babel-plugin-transform-runtime).

I am afraid npm couldn't do much about that since essentially they are different packages.

> If you have the old one in your rc then it seems to magically add it to devDependencies with the wrong prefix.

I don't think so, could you offer a reproduction repo?
