### ISSUE TITLE
broken build after source-map was bumped to v0.6

### ISSUE THREAD

**Issue by andreineculau** [babel/babel#10533]
## Bug Report

**Current Behavior**

Getting the following when running babel CLI, after babel@7.6.3 was picked up (which includes a newer source-map https://github.com/babel/babel/pull/10446 ):
[Travis CI build](https://travis-ci.com/tobiipro/browser-coords/builds/131042030)

```
Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
393    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/travis/build/tobiipro/browser-coords/node_modules/@babel/cli/node_modules/source-map/lib/source-map-generator.js:276:15)
394    at SourceMapGenerator_addMapping [as addMapping] (/home/travis/build/tobiipro/browser-coords/node_modules/@babel/cli/node_modules/source-map/lib/source-map-generator.js:110:12)
395    at /home/travis/build/tobiipro/browser-coords/node_modules/@babel/cli/lib/babel/file.js:106:17
396    at Array.forEach (<anonymous>)
397    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/home/travis/build/tobiipro/browser-coords/node_modules/@babel/cli/node_modules/source-map/lib/source-map-consumer.js:157:14)
398    at buildResult (/home/travis/build/tobiipro/browser-coords/node_modules/@babel/cli/lib/babel/file.js:104:20)
399    at output (/home/travis/build/tobiipro/browser-coords/node_modules/@babel/cli/lib/babel/file.js:140:22)
400    at /home/travis/build/tobiipro/browser-coords/node_modules/@babel/cli/lib/babel/file.js:236:9
401    at Generator.next (<anonymous>)
402    at asyncGeneratorStep (/home/travis/build/tobiipro/browser-coords/node_modules/@babel/cli/lib/babel/file.js:76:103)
```

**Input Code**

https://github.com/tobiipro/browser-coords

**Expected behavior/code**

[A green build, like the previous one with babel@7.6.2 .](https://travis-ci.com/tobiipro/browser-coords/builds/130819745)

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  presets: [
    ['firecloud', {
      '@babel/preset-env': {
        targets: {
          browsers: [
            'last 2 Chrome versions'
          ]
        }
      }
    }]
  ],

  sourceMaps: true,

  retainLines: true
};
```

**Environment**
- Babel version(s): 7.6.3
- Node/npm version: Node 10+
- OS: any
- Monorepo: no
- How you are using Babel: `cli`

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by medikoo** [comment]
Same here, perfectly working build stopped working
