### ISSUE TITLE
Cant compile React / Redux project

### ISSUE THREAD

**Issue by JuanjoOrt** [babel/babel#10541]
Hey, im trying to compile my project, and im having this issues:

this is the error:

```
`ERROR in ./src/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\usuario\Documents\test\src\index.jsx: Unexpected token (8:8)

   6 | 
   7 | ReactDOM.render(
>  8 |         <div>test</div>
     |         ^
   9 |    ,
  10 |     document.getElementById('root')
  11 | );
    at Parser.raise (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:6420:17)
    at Parser.unexpected (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:7773:16)
    at Parser.parseExprAtom (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8996:20)
    at Parser.parseExprSubscripts (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8556:23)
    at Parser.parseMaybeUnary (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8536:21)
    at Parser.parseExprOps (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8402:23)
    at Parser.parseMaybeConditional (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8375:23)
    at Parser.parseMaybeAssign (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8325:21)
    at Parser.parseExprListItem (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:9659:18)
    at Parser.parseCallExpressionArguments (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8774:22)
    at Parser.parseSubscript (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8661:29)
    at Parser.parseSubscripts (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8577:19)
    at Parser.parseExprSubscripts (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8566:17)
    at Parser.parseMaybeUnary (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8536:21)
    at Parser.parseExprOps (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8402:23)
    at Parser.parseMaybeConditional (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8375:23)
    at Parser.parseMaybeAssign (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8325:21)
    at Parser.parseExpression (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:8275:23)
    at Parser.parseStatementContent (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:10138:23)
    at Parser.parseStatement (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:10009:17)
    at Parser.parseBlockOrModuleBlockBody (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:10585:25)
    at Parser.parseBlockBody (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:10572:10)
    at Parser.parseTopLevel (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:9940:10)
    at Parser.parse (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:11447:17)
    at parse (C:\Users\usuario\Documents\test\node_modules\@babel\parser\lib\index.js:11483:38)
    at parser (C:\Users\usuario\Documents\test\node_modules\@babel\core\lib\transformation\normalize-file.js:168:34)
    at normalizeFile (C:\Users\usuario\Documents\test\node_modules\@babel\core\lib\transformation\normalize-file.js:102:11)
    at runSync (C:\Users\usuario\Documents\test\node_modules\@babel\core\lib\transformation\index.js:44:43)
    at runAsync (C:\Users\usuario\Documents\test\node_modules\@babel\core\lib\transformation\index.js:35:14)
    at process.nextTick (C:\Users\usuario\Documents\test\node_modules\@babel\core\lib\transform.js:34:34)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! test@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usuario\AppData\Roaming\npm-cache\_logs\2019-10-11T20_49_18_198Z-debug.log
```

I have this package:

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack --mode production"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "redux": "^4.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/preset-env": "^7.6.3",
    "@babel/preset-react": "^7.6.3",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.6",
    "webpack": "^4.41.1",
    "webpack-cli": "^3.3.9"
  }
}
```

I read something about the version of babel, but cannot fix it. Created a Git repository of the project:

https://github.com/JuanjoOrt/ReactprojectTest
https://github.com/JuanjoOrt/ReactprojectTest

Feel free to clone it and PR if u can find the solution.

Thanks a lot

**Comment by JLHwung** [comment]
A [Babel configuration](https://github.com/babel/babel-loader#options) is in need to support React JSX syntax.

You can add configuration to `webpack.config.js`
```js
module: {
  rules: [
    {
      test: /\.m?js$/,
      exclude: /(node_modules|bower_components)/,
      use: {
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env', '@babel/preset-react'],
        }
      }
    }
  ]
}
```

**Comment by JuanjoOrt** [comment]
awwwww is for thaat.

Thanks a lot.

Close Issue
