### ISSUE TITLE
'export interface' of typescript not compiling correctly

### ISSUE THREAD

**Issue by regalskr2006** [babel/babel#10570]
## Bug Report

**Current Behavior**
Throw an error

```
ERROR in ./app/validator/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:\Projects\Sample\sample-admin\app\validator\index.js: Unexpected token (19:17)

  17 | };
  18 | 
> 19 | export interface Lengths{
     |        ^
  20 |   maxLength?: number;
  21 |   minLength?: number;

at Object.raise (J:\Projects\Poitore\poitore-admin\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3851:17)
    at Object.unexpected (D:\Projects\Sample\sample-admin\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5167:16)
    at Object.parseExportFrom (JD:\Projects\Sample\sample-admin\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8499:14)
    at Object.parseExport (D:\Projects\Sample\sample-admin\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8354:12)
    at Object.parseStatementContent (D:\Projects\Sample\sample-admin\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7395:27)
    at Object.parseStatement (D:\Projects\Sample\sample-admin\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7291:17)
    at Object.parseBlockOrModuleBlockBody (D:\Projects\Sample\sample-admin\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7868:25)
    at Object.parseBlockBody (J:\Projects\Poitore\poitore-admin\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7855:10)
    at Object.parseTopLevel (D:\Projects\Sample\sample-admin\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7220:10)
    at Object.parse (D:\Projects\Sample\sample-admin\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8863:17)
```

**Input Code**

```js
export interface Lengths {
  maxLength?: number;
  minLength?: number;
}
```

**Expected behavior/code**
Compiled correctly

**Babel Configuration (.babelrc, package.json, cli command)**

```js
presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
      },
    ],
    '@babel/preset-react',
  ],
  plugins: [
    'styled-components',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-proposal-export-default-from',
  ],
  env: {
    production: {
      only: ['app'],
      plugins: [
        'lodash',
        'transform-react-remove-prop-types',
        '@babel/plugin-transform-react-inline-elements',
        '@babel/plugin-transform-react-constant-elements',
      ],
    },
    test: {
      plugins: [
        '@babel/plugin-transform-modules-commonjs',
        'dynamic-import-node',
      ],
    },
  },
```

**Environment**

software | version(s)
-- | --
Babel | 7.4.3
node | 8.12.0
npm |  6.12.0
Operating System | windows 7

**Comment by JLHwung** [comment]
There are multiple issues on your example.

1) If you would like to parse TypeScript with babel, please add `@babel/preset-typescript` to the `presets` field in your configuration

2) The error is thrown from `\app\validator\index.js`. A `.js` file should not use TypeScript syntax, consider change it to `.ts`.

**Comment by nicolo-ribaudo** [comment]
This now works: https://babeljs.io/repl#?browsers=%0A&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBASwHY2FAZgQwMbDgGWCQHMYALAZzgG8AoOOAW0xEJPIH4AuOJAV0YAjNAG56TZG1JluvAcKhiAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Ctypescript&prettier=false&targets=&version=7.12.12&externalPlugins=
