### ISSUE TITLE
Conflicting behavior run with  babel-node and node, see my script in issue body.

### ISSUE THREAD

**Issue by shenxiang11** [babel/babel#10679]
## Bug Report

**Current Behavior**
babel-node returns ```undefined```
node throws an error ```ReferenceError: x is not defined```

**Input Code**

```javascript
var x = 1;

function foo(x = x) {
  console.log(x)
}

foo()
```

**Comment by qodesmith** [comment]
What's the expected result? I ran that in Chrome's console and it threw a different error:

```
Uncaught ReferenceError: Cannot access 'x' before initialization
```

**Comment by shenxiang11** [comment]
@qodesmith 
I'm not sure if babel-node and node should has same behavior.

**Comment by thiagoarrais** [comment]
@shenxiang11: this is the output I'm getting with `babel-node`:

```
$ npx babel-node -e "var x = 1;
> 
> function foo(x = x) {
>   console.log(x)
> }
> 
> foo()"
[eval]:3
function foo(x = x) {
                 ^

ReferenceError: Cannot access 'x' before initialization
    at foo ([eval]:3:18)
    at [eval]:7:1
    at Script.runInThisContext (vm.js:123:20)
    at Object.runInThisContext (vm.js:313:38)
    at _eval (/data/app/node_modules/@babel/node/lib/_babel-node.js:107:22)
    at Object.<anonymous> (/data/app/node_modules/@babel/node/lib/_babel-node.js:124:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
```
This is a vanilla installation. Are you using any plugins/presets?

**Comment by JLHwung** [comment]
@thiagoarrais The error can be [reproduced](https://babeljs.io/repl#?babili=false&browsers=ie%20%3C%2011&build=&builtIns=usage&spec=false&loose=false&code_lz=G4QwTgBAHhC8EEYDcAoFAzArgOwMYBcBLAe2wnWOIAoZ4oBKCAbxQgl1IGdiAbAUwB0PYgHMa9FAF80FavSA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.7.4&externalPlugins=%40babel%2Fplugin-transform-parameters%407.7.4) after applying `@babel/plugin-transform-parameters`. We should have thrown a TDZ name error.

**Comment by thiagoarrais** [comment]
> ## Bug Report
> **Current Behavior**
> babel-node returns `undefined`
> node throws an error `ReferenceError: x is not defined`
> 
> **Input Code**
> 
> ```js
> var x = 1;
> 
> function foo(x = x) {
>   console.log(x)
> }
> 
> foo()
> ```

**Comment by thiagoarrais** [comment]
Sorry! Fat fingered the close button...
