### ISSUE TITLE
Can't get latest version of Babel to install with npm

### ISSUE THREAD

**Issue by youradds** [babel/babel#10688]
I can't seem to get 7.7.2 to install on my Ubuntu 18.10 server. Please see:

https://serverfault.com/questions/991088/babel-6-26-3-keeps-getting-installed-instead-of-version-7-7

I've tried:

> npm install --save-dev @babel/core

Which just installs:

```
npm view babel-core version
6.26.3
```

Trying to force a later version, gives:

```
npm install babel-core@7.7.2
npm ERR! code ETARGET
npm ERR! notarget No matching version found for babel-core@7.7.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-09T14_44_16_094Z-debug.log
```

What am I doing wrong?  I'm on these versions:

```
root@east:~# node --version
v13.1.0
root@east:~# npm --version
6.13.0
```

**Comment by JLHwung** [comment]
@babel/core@7.7.2 is [published](https://www.npmjs.com/package/@babel/core) on npm. Could you attach the output?
```
curl --head -v `npm view @babel/core dist.tarball`
```
Check if you are behind a proxy or using a third party npm registry. There are situations when these cache need some time to update to the latest version. You could also find a solution in https://github.com/babel/babel/issues?q=is%3Aissue+sort%3Aupdated-desc+No+matching+version+found+for+is%3Aclosed

**Comment by youradds** [comment]
Hi,

Thanks for the quick reply :) For some reason I don't seem to be able to attach any files? Here is the output:

```
root@east:~# curl --head -v `npm view @babel/core dist.tarball`
*   Trying 2606:4700::6810:1123...
* TCP_NODELAY set
* Connected to registry.npmjs.org (2606:4700::6810:1123) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl8917                                                                  38.cloudflaressl.com
*  start date: Sep 10 00:00:00 2019 GMT
*  expire date: Mar 18 23:59:59 2020 GMT
*  subjectAltName: host "registry.npmjs.org" matched cert's "*.npmjs.org"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMOD                                                                  O ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x560b96876d00)
> HEAD /@babel/core/-/core-7.7.2.tgz HTTP/2
> Host: registry.npmjs.org
> User-Agent: curl/7.61.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200
HTTP/2 200
< date: Sat, 09 Nov 2019 15:32:40 GMT
date: Sat, 09 Nov 2019 15:32:40 GMT
< content-type: application/octet-stream
content-type: application/octet-stream
< content-length: 30724
content-length: 30724
< set-cookie: __cfduid=d17d9fbdd4ff8bc88683c61e5f7a460e31573313560; expires=Sun,                                                                   08-Nov-20 15:32:40 GMT; path=/; domain=.npmjs.org; HttpOnly
set-cookie: __cfduid=d17d9fbdd4ff8bc88683c61e5f7a460e31573313560; expires=Sun, 0                                                                  8-Nov-20 15:32:40 GMT; path=/; domain=.npmjs.org; HttpOnly
< cf-cache-status: HIT
cf-cache-status: HIT
< cache-control: public, max-age=300
cache-control: public, max-age=300
< cf-ray: 5330d7363d65e5f8-LHR
cf-ray: 5330d7363d65e5f8-LHR
< accept-ranges: bytes
accept-ranges: bytes
< age: 230689
age: 230689
< etag: "2aad6cd25d95068240c9e871b0dc68cb"
etag: "2aad6cd25d95068240c9e871b0dc68cb"
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-c                                                                  gi/beacon/expect-ct"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi                                                                  /beacon/expect-ct"
< last-modified: Wed, 06 Nov 2019 23:27:51 GMT
last-modified: Wed, 06 Nov 2019 23:27:51 GMT
< vary: Accept-Encoding
vary: Accept-Encoding
< server: cloudflare
server: cloudflare

<
* Connection #0 to host registry.npmjs.org left intact
root@east:~#

```

**Comment by youradds** [comment]
Interestingly - if I try and install @babel/core, I get:

```
npm install @babel/cli
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching bi                                                                                           naries from AWS, smaller package size
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN @babel/cli@7.7.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux"                                                                                           ,"arch":"x64"})

+ @babel/cli@7.7.0
added 150 packages from 108 contributors and audited 2172 packages in 6.651s

1 package is looking for funding.
Run "npm fund" to find out more.
```

Yet when I run --version I get the old version still:

```root@east:~# babel --version
6.26.0 (babel-core 6.26.3)```

**Comment by JLHwung** [comment]
Yeah, `babel-core` is babel v6, and you should uninstall `babel-core` and use `@babel/core` instead. Rule of thumb: from v6 to v7 we have renamed every official `babel-foo` package to `@babel/foo`. You can also check out this [migration guide](https://babeljs.io/docs/en/v7-migration) if you are upgrading to v7.

**Comment by youradds** [comment]
Ah right. Ok I tried removing it:

```
npm uninstall babel-core
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN @babel/cli@7.7.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 8643 packages in 2.746s

1 package is looking for funding.
Run "npm fund" to find out more.

```
Yet it still seems to think its installed at 6.26?:

> root@east:~# babel --version
> 6.26.0 (babel-core 6.26.3)

**Comment by JLHwung** [comment]
You should also remove the globally installed `babel-cli`.
```
npm -g uninstall babel-cli
```

**Comment by youradds** [comment]
Cool - well that got rid of that, but now I don't know how to invoke it haha =) 
```

root@east:~# babel --version
-bash: /usr/local/bin/babel: No such file or directory

root@east:~# whereis babel
babel:
```

Do I need to do another step to make it accessable from command line? (all my scripts to create the Babel versions run from CLI in a bash script)

**Comment by JLHwung** [comment]
You may install `@babel/cli` globally
```
npm -g install @babel/cli
```

But I would recommend install at your app locally and invoke by
```
$(npm bin)/babel --blablabla
```
which I think is easier to maintain.

**Comment by youradds** [comment]
WAHOO!!! Thanks you so much :) I installed @babel/cli with the -g flag, and then run:

> babel --version

I got:

```
babel --version
internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module '@babel/core'
Require stack:
- /usr/local/lib/node_modules/@babel/cli/lib/babel/options.js
- /usr/local/lib/node_modules/@babel/cli/lib/babel/index.js
- /usr/local/lib/node_modules/@babel/cli/bin/babel.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at _core (/usr/local/lib/node_modules/@babel/cli/lib/babel/options.js:29:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@babel/cli/lib/babel/options.js:134:76)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@babel/cli/lib/babel/options.js',
    '/usr/local/lib/node_modules/@babel/cli/lib/babel/index.js',
    '/usr/local/lib/node_modules/@babel/cli/bin/babel.js'
  ]
```

So I assumed its because @babel/core needed installing globally as well - so I did:

`npm -g install @babel/core`


...and now I get:

```
# babel --version
7.7.0 (@babel/core 7.7.2)
```

Thank you so much. I was going mad with this issue! 

If you want to add the answer on my SO post, I'd be happy to accept it (and hopefully someone else who is having the same issues will come across it as well)

https://serverfault.com/questions/991088/babel-6-26-3-keeps-getting-installed-instead-of-version-7-7

**Comment by JLHwung** [comment]
@youradds I am gonna close this issue now and I am glad your issue is solved. You may link to this thread on the SO post.
