### ISSUE TITLE
MODULE_NOT_FOUND in @babel/cli/bin/babel.js => node_modules/core-js-compat/helpers.js:3:14)

### ISSUE THREAD

**Issue by kopax** [babel/babel#10793]
## Bug Report

We are experience errors on all our projects since a few minutes, we are still investigating

**Current Behavior**

`core-js` or `babel` is having issue to run babel build, this happen on all our projects that use babel and we are still investigating

**Input Code**
- REPL or Repo link if applicable: https://github.com/bootstrap-styled/provider

```js
> BABEL_ENV=production babel --out-dir lib src --copy-files

Error: Cannot find module './src/data'
Require stack:
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/helpers.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/get-modules-list-for-target-version.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/preset-env/lib/index.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/config/files/plugins.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/config/files/index.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/index.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/lib/babel/options.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/lib/babel/index.js
- /home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/bin/babel.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:800:15)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/helpers.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/helpers.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/core-js-compat/get-modules-list-for-target-version.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/preset-env/lib/index.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/config/files/plugins.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/config/files/index.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/core/lib/index.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/lib/babel/options.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/lib/babel/index.js',
    '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/@babel/cli/bin/babel.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bootstrap-styled/provider@1.5.2 build:lib: `BABEL_ENV=production babel --out-dir lib src --copy-files`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @bootstrap-styled/provider@1.5.2 build:lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dka/.npm/_logs/2019-12-02T18_02_24_436Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bootstrap-styled/provider@1.5.2 build: `npm run build:lib && npm run build:dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @bootstrap-styled/provider@1.5.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dka/.npm/_logs/2019-12-02T18_02_24_446Z-debug.log

```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  only: [
    'src',
    'styleguide',
  ],
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
      },
    ],
    '@babel/preset-react',
  ],
  plugins: [
    'styled-components',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-syntax-import-meta',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-json-strings',
    [
      '@babel/plugin-proposal-decorators',
      {
        legacy: true
      }
    ],
  ],
  env: {
    production: {
      plugins: [
        'add-module-exports',
        '@babel/plugin-transform-modules-commonjs',
      ],
    },
    test: {
      plugins: [
        '@babel/plugin-transform-modules-commonjs',
        'dynamic-import-node',
      ],
    },
  },
};

```

**Environment**

```

```
- Babel version(s): 7.7.4
- Node/npm version: v13.0.1
- OS: Debian buster
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

Not yet

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nicolo-ribaudo** [comment]
https://github.com/zloirock/core-js/issues/711#issuecomment-560512445
