### ISSUE TITLE
Problem with download @babel/preset-env ?

### ISSUE THREAD

**Issue by golubvladimir** [babel/babel#10857]
I can not to load @babel/preset-env by npm.
```
7 http fetch GET 304 https://registry.npmjs.org/@babel%2fpreset-env 407ms (from cache)
8 silly fetchPackageMetaData error for @babel/preset-env@latest Unexpected end of JSON input while parsing near '...gin-syntax-object-res'
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 464ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...gin-syntax-object-res'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
11 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
12 verbose cwd C:\Users\v.golub\Documents\projects\angulardemo
13 verbose Windows_NT 10.0.18363
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@babel/preset-env"
15 verbose node v12.13.1
16 verbose npm  v6.12.1
17 error Unexpected end of JSON input while parsing near '...gin-syntax-object-res'
18 verbose exit [ 1, true ]
```

I try:
```
npm install @babel/preset-env
npm install @babel/preset-env@7.5.6
npm install @babel/preset-env@7.5.5
```
These commands doesn't work.

For exmaple:
npm install react - work
npm install @babel/core - work
npm install @babel/preset-react - work

**Comment by nicolo-ribaudo** [comment]
The version cached by npm had some problems during the download and it is corrupted. Try running `npm cache clean --force`, delete `node_modules` and re-running `npm install`.

**Comment by golubvladimir** [comment]
@nicolo-ribaudo Thank you)
