### ISSUE TITLE
transpile a core-js internal as [buggy] `var _parse-int =`

### ISSUE THREAD

**Issue by drzraf** [babel/babel#10931]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
When recompiling my project, I hit this error:
```
node_modules/core-js/internals/parse-int.js (17:10)
SyntaxError: /project/node_modules/core-js/internals/parse-int.js: Unexpected token, expected ";" (17:10)

  15 | // `parseInt` method
  16 | // https://tc39.github.io/ecma262/#sec-parseint-string-radix
> 17 | var _parse-int = FORCED ? function parseInt(string, radix) {
     |           ^
  18 |   var S = trim(String(string));
  19 |   return nativeParseInt(S, (radix >>> 0) || (hex.test(S) ? 16 : 10));
  20 | } : nativeParseInt;
    at Parser.raise (/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6975:17)
    at Parser.unexpected (/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8368:16)
    at Parser.semicolon (/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8350:40)
    at Parser.parseVarStatement (/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:11127:10)
    at Parser.parseStatementContent (/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:10723:21)
    at Parser.parseStatement (/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:10656:17)
    at Parser.parseBlockOrModuleBlockBody (/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:11232:25)
    at Parser.parseBlockBody (/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:11219:10)
    at Parser.parseTopLevel (/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:10587:10)
    at Parser.parse (/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12097:10)
```

It sounds like transpiling [this file](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/parse-int.js) resulted in an illegal variable name being generated.

**Which mechanism/options is in charge of creating that `var _parse-int` identifier?**

**Environment**
├── core-js@3.4.7
├─┬ @babel/core@7.7.4
(but keep getting the error after having updated all my dependencies)

```
- Babel version(s): 7.7.4
- Node/npm version: v10.18.0
- OS: linux
- How you are using Babel: from rollup

**Comment by nicolo-ribaudo** [comment]
Rollup and Babel configs?

**Comment by drzraf** [comment]
Actually a [bug in the rollup plugin](https://github.com/rollup/plugins/issues/114). Sorry for the noise.
