### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by joliss** [babel/babel#1100]
On the experimental branch (v5.0.0-beta2) on iojs v1.6.2, `make test` fails with the following error:

```
$ make test
node test/acorn/run.js
Normal parser: 1101 tests run in 272ms; all passed.
Total: 1101 tests run in 272ms; all passed.
node node_modules/mocha/bin/_mocha test/core
/home/ubuntu/src/babel/lib/babel/traversal/scope.js:96
    var cached = path.getData("scope");
                      ^
TypeError: undefined is not a function
    at new Scope (/home/ubuntu/src/babel/lib/babel/traversal/scope.js:96:23)
    at Function.getScope (/home/ubuntu/src/babel/lib/babel/traversal/path.js:58:18)
    at TraversalPath.setScope (/home/ubuntu/src/babel/lib/babel/traversal/path.js:77:32)
    at TraversalPath.setContext (/home/ubuntu/src/babel/lib/babel/traversal/path.js:90:10)
    at Function.get (/home/ubuntu/src/babel/lib/babel/traversal/path.js:48:10)
    at TraversalContext.create (/home/ubuntu/src/babel/lib/babel/traversal/context.js:26:26)
    at TraversalContext.visitSingle (/home/ubuntu/src/babel/lib/babel/traversal/context.js:63:17)
    at TraversalContext.visit (/home/ubuntu/src/babel/lib/babel/traversal/context.js:73:19)
    at Function.traverse.node (/home/ubuntu/src/babel/lib/babel/traversal/index.js:44:17)
    at TraversalPath.visit (/home/ubuntu/src/babel/lib/babel/traversal/path.js:159:18)
    at TraversalContext.visitMultiple (/home/ubuntu/src/babel/lib/babel/traversal/context.js:50:16)
    at TraversalContext.visit (/home/ubuntu/src/babel/lib/babel/traversal/context.js:71:19)
    at Function.traverse.node (/home/ubuntu/src/babel/lib/babel/traversal/index.js:44:17)
    at traverse (/home/ubuntu/src/babel/lib/babel/traversal/index.js:34:14)
    at Function.traverse.removeProperties (/home/ubuntu/src/babel/lib/babel/traversal/index.js:78:3)
    at parseTemplate (/home/ubuntu/src/babel/lib/babel/util.js:150:18)
    at /home/ubuntu/src/babel/lib/babel/util.js:169:22
    at arrayEach (/home/ubuntu/src/babel/node_modules/lodash/internal/arrayEach.js:15:9)
    at /home/ubuntu/src/babel/node_modules/lodash/internal/createForEach.js:15:9
    at loadTemplates (/home/ubuntu/src/babel/lib/babel/util.js:162:3)
    at Object.<anonymous> (/home/ubuntu/src/babel/lib/babel/util.js:179:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/home/ubuntu/src/babel/test/core/_helper.js:2:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at /home/ubuntu/src/babel/node_modules/mocha/lib/mocha.js:187:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/ubuntu/src/babel/node_modules/mocha/lib/mocha.js:184:14)
    at Mocha.run (/home/ubuntu/src/babel/node_modules/mocha/lib/mocha.js:405:31)
    at Object.<anonymous> (/home/ubuntu/src/babel/node_modules/mocha/bin/_mocha:405:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Function.Module.runMain (module.js:451:10)
    at startup (node.js:123:18)
    at node.js:868:3
make: *** [test] Error 1
```

**Comment by joliss** [comment]
Never mind, I had left-over files in `lib` it seems.
