### ISSUE TITLE
Error when Mixing Nested Async Functions and TypeScript Generics

### ISSUE THREAD

**Issue by liamfd** [babel/babel#11007]
## Bug Report

- [x] I would like to work on a fix!

I'm interested in helping, but I don't have much context! If someone else would like to take point on a fix, that is also fine with me.

**Current Behavior**
When mixing TypeScript generics and async/await in a certain way, I'm seeing an `Unexpected Token, expected ";"` error.

**Input Code**
- [REPL](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwgOwM7wGYQnAvHAQ1QE9kE4AKASjwD44BvAKDkIHcCBLeABSggC2nVMAB0UYKggAbAG7AKDAL5UA3ExaIU6OACMCUPIRJk4AHgAqtanTgByLBDvqlqoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.8.3&externalPlugins=)

This is the smallest reproducible example I could come up with:

```ts
export const foo = async () => {
  await Promise.resolve({});

  const bar = async <T>() => 'foo';
};
```

Looks like it fails if you have an `await` before an `async` function with a generic defined.

**Expected behavior/code**
As far as I can tell, this should transpile. Its individual components do.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
(Note that I was able to repro this on the REPL)

- Filename: `.babelrc`

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "8.10"
        },
        "useBuiltIns": "entry",
      }
    ],
    "@babel/preset-typescript"
  ],
  "plugins": [
    "lodash",
    [
      "babel-plugin-transform-builtin-extend",
      {
        "globals": ["Error"]
      }
    ]
  ]
}
```

**Environment**

```
  System:
    OS: macOS 10.15.1
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
  npmPackages:
    @babel/cli: 7.8.3 => 7.8.3 
    @babel/core: 7.8.3 => 7.8.3 
    @babel/node: 7.8.3 => 7.8.3 
    @babel/polyfill: 7.8.3 => 7.8.3 
    @babel/preset-env: 7.8.3 => 7.8.3 
    @babel/preset-typescript: 7.8.3 => 7.8.3 
    @babel/register: 7.8.3 => 7.8.3 
    babel-jest: 24.9.0 => 24.9.0 
    babel-loader: 8.0.5 => 8.0.5 
    babel-plugin-lodash: 3.3.4 => 3.3.4 
    babel-plugin-transform-builtin-extend: 1.1.2 => 1.1.2 
    eslint: 5.13.0 => 5.13.0 
    jest: 24.9.0 => 24.9.0 
    webpack: 4.29.3 => 4.29.3 
```

**Possible Solution**

**Additional context/Screenshots**

Raw output (from a `yarn babel-node` invocation):

```
/Users/liam/fabric/linen/node_modules/@babel/core/lib/parser/index.js:95
    throw err;
    ^

SyntaxError: /path/to/file.ts: Unexpected token, expected ";" (31:26)

  29 |   await Promise.resolve({});
  30 | 
> 31 |   const bar = async <T>() => 'foo';
     |                           ^
  32 | };
  33 | 
    at Object.raise (/Users/liam/fabric/linen/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7013:17)
    at Object.unexpected (/Users/liam/fabric/linen/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8384:16)
    at Object.semicolon (/Users/liam/fabric/linen/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8366:40)
    at Object.parseVarStatement (/Users/liam/fabric/linen/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:11129:10)
    at Object.parseStatementContent (/Users/liam/fabric/linen/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:10725:21)
    at Object.parseStatementContent (/Users/liam/fabric/linen/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5972:18)
    at Object.parseStatement (/Users/liam/fabric/linen/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:10658:17)
    at Object.parseBlockOrModuleBlockBody (/Users/liam/fabric/linen/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:11234:25)
    at Object.parseBlockBody (/Users/liam/fabric/linen/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:11221:10)
    at Object.parseBlock (/Users/liam/fabric/linen/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:11205:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I believe this is a regression - I'm in the middle of upgrading from `7.2.x` to `7.8.x`, so I haven't found the exact version that introduced it yet, but the code in question worked in `7.2.x`.

**Comment by JLHwung** [comment]
As a workaround, you can wrap the async function declaration into parenthesis.
```ts
export const foo = async () => {
  await Promise.resolve({});

  const bar = (async <T>() => 'foo');
};
```

**Comment by liamfd** [comment]
@JLHwung thank you for the detailed explanation! I'll give that solution a shot.
