### ISSUE TITLE
Error .options is not a valid Plugin property

### ISSUE THREAD

**Issue by calaquend1** [babel/babel#11045]
when i run 
```js
npm run build 
```
which is in package.json
```js 
scripts: {
    "build": "rollup -c"
}
````

I get an error
```js
[!] (plugin babel) Error: [BABEL] /Users/kodix/Documents/kodix/storybooknew/node_modules/date-fns/esm/locale/index.js: .options is not a valid Plugin property in object: {"name":"peer-deps-external"}
node_modules/date-fns/esm/locale/index.js
Error: [BABEL] /Users/kodix/Documents/kodix/storybooknew/node_modules/date-fns/esm/locale/index.js: .options is not a valid Plugin property in object: {"name":"peer-deps-external"}
    at Object.keys.forEach.key (/Users/kodix/Documents/kodix/storybooknew/node_modules/@babel/core/lib/config/validation/plugins.js:61:59)
    at Array.forEach (<anonymous>)
    at validatePluginObject (/Users/kodix/Documents/kodix/storybooknew/node_modules/@babel/core/lib/config/validation/plugins.js:54:20)
    at instantiatePlugin (/Users/kodix/Documents/kodix/storybooknew/node_modules/@babel/core/lib/config/full.js:210:55)
    at cachedFunction (/Users/kodix/Documents/kodix/storybooknew/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPluginDescriptor (/Users/kodix/Documents/kodix/storybooknew/node_modules/@babel/core/lib/config/full.js:201:10)
    at config.plugins.reduce (/Users/kodix/Documents/kodix/storybooknew/node_modules/@babel/core/lib/config/full.js:71:20)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/kodix/Documents/kodix/storybooknew/node_modules/@babel/core/lib/config/full.js:69:38)
    at loadFullConfig (/Users/kodix/Documents/kodix/storybooknew/node_modules/@babel/core/lib/config/full.js:109:6)
```

I've added this part of the error by myself
```js
in object: {"name":"peer-deps-external"}
```

in @babel/core/lib/config/validation/plugins.js
```js
function validatePluginObject(obj) {
  const rootPath = {
    type: "root",
    source: "plugin"
  };
  Object.keys(obj).forEach(key => {
    const validator = VALIDATORS[key];
    const optLoc = {
      type: "option",
      name: key,
      parent: rootPath
    };
    if (validator) validator(optLoc, obj[key]);else throw new Error(`.${key} is not a valid Plugin property in object: ${JSON.stringify(obj)}`);
  });
  return obj;
}
```
this happens cause of date-fns, obviously

rollup.config.js
```js
import typescript from 'rollup-plugin-typescript2';
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import external from 'rollup-plugin-peer-deps-external';
import resolve from 'rollup-plugin-node-resolve';
import svgr from '@svgr/rollup';
import url from 'rollup-plugin-url';
import { terser } from 'rollup-plugin-terser';

import pkg from './package.json';

const plugins = [
  typescript({
    rollupCommonJSResolveHack: true,
    clean: true,
    transpileOnly: true,
  }),
  babel({
    babelrc: false,
    presets: ['@babel/preset-react', '@babel/preset-env'],
    plugins: [
      external(),
      '@babel/plugin-syntax-dynamic-import',
      '@babel/plugin-proposal-class-properties',
      [
        'module-resolver',
        {
          root: ['/'],
          alias: {
            Components: './src/Components',
            Helpers: './src/helpers',
            Storybook: './.storybook',
          },
        },
      ],
    ],
  }),
  resolve(),
  commonjs({
    include: 'node_modules/**',
    namedExports: {
      'node_modules/react/index.js': [
        'Component',
        'PureComponent',
        'Fragment',
        'Children',
        'createElement',
      ],
    },
  }),
  url(),
  svgr(),
  terser({
    compress: {
      drop_console: true,
    },
  }),
];

const externals = ['react', 'swiper', 'react-yandex-maps'].concat(
  Object.keys(pkg.dependencies),
);

export default [
  {
    input: './index.ts',
    output: {
      file: pkg.main,
      format: 'umd',
      name: 'skstb',
    },
    plugins: [...plugins],
    external: externals,
  },
  {
    input: './src/styles/theme/skoda.ts',
    output: {
      file: './dist/theme.js',
      format: 'umd',
      name: 'theme',
    },
    plugins,
    external: externals,
  },
  {
    input: './src/helpers/index.ts',
    output: {
      file: './dist/helpers.js',
      format: 'umd',
      name: 'helpers',
    },
    plugins,
    external: externals,
  },
];

```

.babelrc
```js
{
  "presets": ["@babel/preset-react", "@babel/preset-env"],
  "exclude": "/node_modules/(?!(dom7|swiper|react-id-swiper)/).*/",
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    [
      "module-resolver",
      {
        "root": ["/"],
        "alias": {
          "Types": "./src/Types",
          "Components": "./src/Components",
          "Helpers": "./src/helpers",
          "Storybook": "./.storybook"
        }
      }
    ]
  ]
}

```

```
- Babel version(s): 
     "@babel/core": "^7.5.4",
     "babel-eslint": "^10.0.2",
     "babel-loader": "^8.0.6",
     "babel-plugin-module-resolver": "^3.2.0",
```

**Comment by nicolo-ribaudo** [comment]
`external()` is a `rollup` plugin, not a Babel plugin.

**Comment by JLHwung** [comment]
Closing this since the configuration is invalid.
