### ISSUE TITLE
No matching version found for @babel/compat-data@^7.8.4

### ISSUE THREAD

**Issue by drabelo** [babel/babel#11073]
Randomly today, my CICD pipeline broke during the npm install step. It's throwing 
```

npm ERR! code ETARGET
--
53 | npm ERR! notarget No matching version found for @babel/compat-data@^7.8.4
54 | npm ERR! notarget In most cases you or one of your dependencies are requesting
55 | npm ERR! notarget a package version that doesn't exist.
56 | npm ERR! notarget
57 | npm ERR! notarget It was specified as a dependency of '@babel/preset-env'
58 | npm ERR! notarget

```

I saw that compat-data was updated to 7.8.4, but for reason my environment is not able to find it? Does anyone have any insight?

**Comment by formichi3** [comment]
I am experiencing the same issue with @babel/parser and @babel/traverse
`Error: Couldn't find any versions for "@babel/parser" that matches "^7.8.4"
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50129:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:304:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:315:13
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
Error: Couldn't find any versions for "@babel/traverse" that matches "^7.8.4"
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50129:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:304:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:315:13
    at processTicksAndRejections (internal/process/task_queues.js:86:5)`

**Comment by existentialism** [comment]
It's definitely there:

https://www.npmjs.com/package/@babel/parser
https://unpkg.com/browse/@babel/parser@7.8.4/

Are you behind a proxy/registry cache?

Can you attach the output of:

```sh
curl --head -v `npm view @babel/parser dist.tarball`
```

**Comment by bgl-tand** [comment]
Having the same problem as of today

**Comment by drabelo** [comment]
It started working for me! It was something to do with the package not being found in our private registry, but it was there after 24hrs.
