### ISSUE TITLE
@babel/traverse noScope can't path.remove()

### ISSUE THREAD

**Issue by liuxingbaoyu** [babel/babel#11128]
When I upgraded from v7.7.7 to v7.8.4, I found that there was a problem with the noScope option of @babel/traverse.

Error message:
```
e:\mypath\babel\node_modules\@babel\traverse\lib\path\removal.js:39
  Object.keys(bindings).forEach(name => this.scope.removeBinding(name));
                                                   ^

TypeError: Cannot read property 'removeBinding' of null
    at e:\mypath\babel\node_modules\@babel\traverse\lib\path\removal.js:39:52
    at Array.forEach (<anonymous>)
    at NodePath._removeFromScope (e:\mypath\babel\node_modules\@babel\traverse\lib\path\removal.js:39:25)
    at NodePath.remove (e:\mypath\babel\node_modules\@babel\traverse\lib\path\removal.js:22:8)
    at AssignmentExpression (e:\mypath\babel\test.js:6:14)
    at NodePath._call (e:\mypath\babel\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (e:\mypath\babel\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (e:\mypath\babel\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (e:\mypath\babel\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitSingle (e:\mypath\babel\node_modules\@babel\traverse\lib\context.js:84:19)
```

Code to reproduce the problem:
```js
var traverse = require("@babel/traverse").default;
var parser = require("@babel/parser");

traverse(parser.parse("a=1"), {
    AssignmentExpression(path) {
        path.remove();
    },
    noScope: true,
});
```

**Comment by liuxingbaoyu** [comment]
I'm sorry, I'm such a fool. It should be that I have modified it before, this is not a regression error, it is just a common bug. Sorry!

**Comment by nicolo-ribaudo** [comment]
Ok, it's not a problem!

**Comment by JLHwung** [comment]
Closing it as the OP's issue is resolved.

**Comment by nicolo-ribaudo** [comment]
@JLHwung The issue was resolved by modifying our code :stuck_out_tongue: 

@liuxingbaoyu Do you want to open a PR?

**Comment by liuxingbaoyu** [comment]
@nicolo-ribaudo OK, let me try!
