### ISSUE TITLE
How to skip child nodes

### ISSUE THREAD

**Issue by liuxingbaoyu** [babel/babel#11147]
Code:
```js
var traverse = require("@babel/traverse").default;
var parser = require("@babel/parser");
var generate = require("@babel/generator").default;
var types = require("@babel/types");

var ast = parser.parse('{"abc";"123";}');
traverse(ast, {
  BlockStatement(path) {
    var p = path.get("body")[0];
    console.log("before", p.shouldSkip);
    p.skip();
    console.log("after", p.shouldSkip, path.get("body")[0].shouldSkip);
  },
  ExpressionStatement(path) {
    console.log(generate(path.node).code);
  }
});

return;
```
Output:
```
before false
after true false
"abc";
"123";
```

**Comment by nicolo-ribaudo** [comment]
This is definitely a bug. If you try to run this code in the monorepo:
```js
const load = n => require(`./packages/babel-${n}`);
const babel = load("core");
const parser = load("parser");
const traverse = load("traverse").default;
const generate = load("generator").default;

const ast = parser.parse('{"abc";"123";}');
traverse(ast, {
  BlockStatement(path) {
    const p = path.get("body")[0];
    console.log("before", p.shouldSkip, path.get("body")[0] === p);
    p.skip();

    console.log("after 1", p.shouldSkip);
    path.get("body");
    console.log("after 2", p.shouldSkip);
  },
  ExpressionStatement(path) {
    console.log(generate(path.node).code);
  },
});
```

It will log `after 1 true`, `after 1 false`, but `shouldSkip` shouldn't change from `after 1` to `after2`.

**Comment by liuxingbaoyu** [comment]
I don't know if this is a bug or not allowed, so I asked a question😛

**Comment by liuxingbaoyu** [comment]
Related to this, but I don't know how to fix it😭

[```this._traverseFlags = 0;```](https://github.com/babel/babel/blob/master/packages/babel-traverse/src/path/context.js#L134)
```
    at NodePath.setContext (e:\mypath\babel\node_modules\@babel\traverse\lib\path\context.js:141:3)
    at e:\mypath\babel\node_modules\@babel\traverse\lib\path\family.js:188:10
    at Array.map (<anonymous>)
    at NodePath._getKey (e:\mypath\babel\node_modules\@babel\traverse\lib\path\family.js:181:22)
    at NodePath.get (e:\mypath\babel\node_modules\@babel\traverse\lib\path\family.js:170:17)
    at BlockStatement (e:\mypath\babel\test.js:51:10)
    at NodePath._call (e:\mypath\babel\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (e:\mypath\babel\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (e:\mypath\babel\node_modules\@babel\traverse\lib\path\context.js:90:31)
```

**Comment by Domiii** [comment]
Skipping just does not work in general.

Any news? Not being able to skip node is pretty bad. I know there are workarounds, but this is just a pretty obvious bug that requires fixing, if not at least acknowledgement.

Flags still get wiped, even without calling `path.get` in between:

# Order of events

1. Before some `p` gets visited, I call `p.skip()`. That in turn sets `NodePath._traverseFlags`
2. Before `p` gets visited, `setContext` is called. Stacktrace looks like so:
   ```
   at NodePath.setContext (code\node_modules\@babel\traverse\lib\path\context.js:143:13)
   at NodePath.pushContext (code\node_modules\@babel\traverse\lib\path\context.js:219:8)
   at TraversalContext.visitQueue (code\node_modules\@babel\traverse\lib\context.js:89:14)
   at TraversalContext.visitSingle (code\node_modules\@babel\traverse\lib\context.js:73:19)
   at TraversalContext.visit (code\node_modules\@babel\traverse\lib\context.js:127:19)
  ...
   ```
3. [setContext](https://github.com/babel/babel/blob/875fc8e6935ef7d124a748331ee8a43d59f4539e/packages/babel-traverse/src/path/context.ts#L143) unconditionally unsets `_traverseFlags`
4. Skipped node still gets visited.

Thus `skip` will never work.
