### ISSUE TITLE
[@babel/types] - spreadOperator from an array seems to have a bug with 7.8.7

### ISSUE THREAD

**Issue by thib3113** [babel/babel#11212]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
When I try to build (with react-scripts 3.4.0), I got this error :
`Error: C:\Users\thib3113\app\myFile.js: Expected type "Expression" with option {}, but instead got "SpreadElement".
    at Array.map (<anonymous>)
`

**Input Code**
- REPL or Repo link if applicable:

```js
        let communeFound = CommuneService.cachedResults.get(insee) || null;
        if (!communeFound) {
            // spread operator copy the array
            communeFound = [...(await this.search({ insee }, 1))].pop();
        }
```
this.search return a promise, the promise return an array.

if I replace by 
`communeFound = (await this.search({ insee }, 1)).slice(0).pop();`
it's work

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).
with 7.8.6 it works .

- Babel version(s): 7.8.7
- Node/npm version: Node 13.8.0/npm 6.14.2
- OS: win 10 1909
- Monorepo: no
- How you are using Babel: react-scripts (loader I think)

Is that normal ? or a regression ?

**Comment by nicolo-ribaudo** [comment]
@thib3113 I can't reproduce this bug. Can you post your configuration, or (better) a repository which reproduces the issue?

**Comment by thib3113** [comment]
hum .... I'll dig more to find this :/ ... 

Recreating an empty react app, with the buggy file, doesn't seems to block the build ... 
The project is private so I can't share it directly, but no custom babel configuration (nothing in package.json, no .babelrc ... only config from react-scripts) ... 

Did you have any idea of things to do to debug this ?

The only things I see, is, changing this : 
`communeFound = [...(await this.search({ insee }, 1))].pop();`
to this : 
`communeFound = (await this.search({ insee }, 1)).slice(0).pop();`
resolve the problem ...

And I didn't understand the error, what is "Expression" ? 

I'll try to modify another little project .... to find more precise informations :/

**Comment by nicolo-ribaudo** [comment]
Can you start by sharing the full stack trace?

> And I didn't understand the error, what is "Expression" ?

It's an internal representation of some JavaScript constructs, used by Babel.

**Comment by thib3113** [comment]
I doesn't have more trace ...

So, I edit 
`node_modules/regenerator-transform/lib/emit.js`
to log the complete error, and it is : 
```
Error: Expected type "Expression" with option {}, but instead got "SpreadElement".
    at assert (C:\Users\thib3113\app\node_modules\@babel\types\lib\asserts\generated\index.js:295:11)
    at Object.assertExpression (C:\Users\thib3113\app\node_modules\@babel\types\lib\asserts\generated\index.js:1236:3)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:700:9)
    at explodeViaTempVar (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:747:23)
    at C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:840:16
    at Array.map (<anonymous>)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:839:60)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:773:45)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:799:28)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:905:108)
```

I update emit.js like that : 
```
  if (expr) {
    t.assertExpression(expr);
  } else {
    return expr;
  }
```
become (for line numbers) : 
```
  if (expr) {
    try{
      t.assertExpression(expr);
    } catch (e) {
      console.error(e);
      throw e;
    }
  } else {
    return expr;
  }
```

**Comment by nicolo-ribaudo** [comment]
Ok thanks, I'm able to reproduce it:
https://babeljs.io/repl/#?browsers=node%2010&build=&builtIns=false&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsLwBQEoYDeAUDDANoB0VwA7sKsjAAwC6RAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=env%2Cenv&prettier=true&targets=Node-13&version=7.8.7&externalPlugins=%40babel%2Fplugin-transform-regenerator%407.8.7

**Comment by nicolo-ribaudo** [comment]
Could you edit this file https://github.com/facebook/create-react-app/blob/master/packages/babel-preset-react-app/create.js (it should be in `node_modules/babel-preset-react-app/create.js`, and add `debug: true` [here](https://github.com/facebook/create-react-app/blob/3f699fd08044de9ab0ce1991a66b376d3e1956a8/packages/babel-preset-react-app/create.js#L72) and [here](https://github.com/facebook/create-react-app/blob/3f699fd08044de9ab0ce1991a66b376d3e1956a8/packages/babel-preset-react-app/create.js#L81)?

It would help to understand what caused this regression.

**Comment by thib3113** [comment]
here is the full output : 
```
C:\Users\thib3113\app>react-scripts build
Creating an optimized production build...
@babel/preset-env: `DEBUG` option

Using targets:
{
  "chrome": "49",
  "edge": "18",
  "firefox": "68",
  "ios": "11.3",
  "opera": "66",
  "safari": "12.1",
  "samsung": "9.2"
}

Using modules transform: false

Using plugins:
  proposal-nullish-coalescing-operator { "chrome":"49", "edge":"18", "firefox":"68", "ios":"11.3", "opera":"66", "safari":"12.1", "samsung":"9.2" }
  proposal-optional-chaining { "chrome":"49", "edge":"18", "firefox":"68", "ios":"11.3", "opera":"66", "safari":"12.1", "samsung":"9.2" }
  proposal-json-strings { "chrome":"49", "edge":"18", "ios":"11.3" }
  proposal-optional-catch-binding { "chrome":"49", "edge":"18" }
  proposal-async-generator-functions { "chrome":"49", "edge":"18", "ios":"11.3" }
  proposal-object-rest-spread { "chrome":"49", "edge":"18" }
  transform-dotall-regex { "chrome":"49", "edge":"18", "firefox":"68" }
  proposal-unicode-property-regex { "chrome":"49", "edge":"18", "firefox":"68" }
  transform-named-capturing-groups-regex { "chrome":"49", "edge":"18", "firefox":"68" }
  transform-async-to-generator { "chrome":"49" }
  transform-exponentiation-operator { "chrome":"49" }
  transform-template-literals { "ios":"11.3", "safari":"12.1" }
  transform-function-name { "chrome":"49", "edge":"18" }
  transform-for-of { "chrome":"49" }
  transform-unicode-regex { "chrome":"49", "ios":"11.3" }
  transform-destructuring { "chrome":"49" }
  transform-regenerator { "chrome":"49" }
  syntax-dynamic-import { "chrome":"49", "edge":"18", "firefox":"68", "ios":"11.3", "opera":"66", "safari":"12.1", "samsung":"9.2" }

Using polyfills with `entry` option:
Error: Expected type "Expression" with option {}, but instead got "SpreadElement".
    at assert (C:\Users\thib3113\app\node_modules\@babel\types\lib\asserts\generated\index.js:295:11)
    at Object.assertExpression (C:\Users\thib3113\app\node_modules\@babel\types\lib\asserts\generated\index.js:1236:3)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:700:9)
    at explodeViaTempVar (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:747:23)
    at C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:840:16
    at Array.map (<anonymous>)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:839:60)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:773:45)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:799:28)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:905:108)
Error: Expected type "Expression" with option {}, but instead got "SpreadElement".
    at assert (C:\Users\thib3113\app\node_modules\@babel\types\lib\asserts\generated\index.js:295:11)
    at Object.assertExpression (C:\Users\thib3113\app\node_modules\@babel\types\lib\asserts\generated\index.js:1236:3)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:700:9)
    at explodeViaTempVar (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:747:23)
    at C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:840:16
    at Array.map (<anonymous>)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:839:60)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:773:45)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:799:28)
    at Emitter.Ep.explodeExpression (C:\Users\thib3113\app\node_modules\regenerator-transform\lib\emit.js:905:108)
Failed to compile.

./myFile.js
Error: Expected type "Expression" with option {}, but instead got "SpreadElement".
    at Array.map (<anonymous>)
```
( the error is output two times, because I have two files with the same spread line )

**Comment by nicolo-ribaudo** [comment]
The problem is that `regenerator` doesn't support array spread. All your targets support array spread (so the transform isn't included), but Chrome 49 doesn't support it.

The change in your targets is probably caused by a `caniuse` update, used by `browserslist` to decide what browsers it should target.

By default, `create-react-app` uses [`>0.2%`](https://browsersl.ist/?q=%3E0.2%25) ad a query to decide which browsers it should target.

You can add this to your `package.json` to force it to include a browser that doesn't support array spread, so that it gets compiled:
```js
"browserslist": [
  ">0.2%",
  "chrome 45"
]
```

(This is still a bug, I will fix it in `regenerator`).

**Comment by nicolo-ribaudo** [comment]
Fixes by https://github.com/facebook/regenerator/pull/385
