### ISSUE TITLE
Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null

### ISSUE THREAD

**Issue by hparadiz** [babel/babel#11231]
## Bug Report
As of 7.8.7 I'm getting the error `Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null`

Our CI runs like so automatically on every commit:
```yaml
    - apt install -y nodejs npm
    - npm -g -D install webpack webpack-cli babel-loader @babel/core @babel/preset-env babel-polyfill
    - cd ./webapp/js/
    - webpack --config webpack.dist.js
```
Here's the stack trace coming out of webpack CLI
```
ERROR in ./apps/application/controllers/controllers.addactivity.js
Module build failed (from /usr/local/lib/node_modules/babel-loader/lib/index.js):
TypeError: /Users/henry/Documents/application/application-website/webapp/js/apps/application/controllers/controllers.addactivity.js: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null
    at Object.validate (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:131:11)
    at validateField (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at Object.validate (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/replacement.js:172:7)
    at NodePath._remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:55:10)
    at NodePath.remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:34:8)
    at hooks (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/lib/removal-hooks.js:11:12)
    at NodePath._callRemovalHooks (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:46:9)
    at NodePath.remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:26:12)
    at convertFunctionParams (/usr/local/lib/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-parameters/lib/params.js:88:30)
    at PluginPass.Function (/usr/local/lib/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-parameters/lib/index.js:30:53)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
 @ multi /usr/local/lib/node_modules/babel-polyfill/ ./application/ironhide.js ./application/utility.js ./apps/application/services/services.js ./apps/application/services/services.appsdevices.js ./apps/application/services/services.branding.js ./apps/application/services/services.ionic.webapp.js ./apps/application/services/services.geo.webapp.js ./apps/application/services/services.minicache.js ./apps/application/services/services.devicesync.webapp.js ./apps/application/services/services.unifyapi.webapp.js ./apps/application/services/services.webappmenu.webapp.js ./apps/application/services/services.localforage.webapp.js ./apps/application/services/services.benefitplanutilities.js ./apps/application/services/services.dateutilities.js ./apps/application/directives/directives.earningsrow.js ./apps/application/directives/directives.helptext.js ./apps/application/directives/directives.helpmodal.js ./apps/application/directives/directives.miniplanbuilder.js ./apps/application/directives/directives.progressbar.js ./apps/application/directives/directives.validation.js ./apps/application/directives/directives.cyberfilters.js ./apps/application/directives/directives.chart.js ./apps/application/directives/directives.surveypage.js ./apps/application/directives/directives.focus.js ./apps/application/directives/directives.selectemployeetags.js ./apps/application/directives/directives.selectcompanyid.js ./apps/application/data/applicationDataSource.js ./apps/application/components/applicationGrid.js ./apps/workstation/components/grid.js ./apps/application/controllers/controllers.js ./apps/application/controllers/controllers.auth.js ./apps/application/controllers/controllers.timeline.js ./apps/application/controllers/controllers.commprefs.js ./apps/application/controllers/controllers.account.js ./apps/application/controllers/controllers.addactivity.js ./apps/application/controllers/controllers.appsdevices.js ./apps/application/controllers/controllers.benefit.js ./apps/application/controllers/controllers.earnings.js ./apps/application/controllers/controllers.challenges.js ./apps/application/controllers/controllers.company.js ./apps/application/controllers/controllers.customer.js ./apps/application/controllers/controllers.rewardsmall.js ./apps/application/controllers/controllers.orgsettings.taxreporting.js ./apps/application/controllers/controllers.newrewardsettings.js ./apps/application/controllers/controllers.reports.individuals.js ./apps/application/controllers/controllers.reports.activities.js ./apps/application/controllers/controllers.reports.rewards.js ./apps/application/controllers/controllers.reports.disbursements.js ./apps/application/controllers/controllers.reports.surveys.js ./apps/application/controllers/controllers.reports.healthcard.js ./apps/application/controllers/controllers.communications.js ./apps/application/controllers/controllers.events.js ./apps/application/controllers/controllers.menu.js ./apps/application/controllers/controllers.surveys.js ./apps/application/controllers/controllers.manage_orgs.js ./apps/application/controllers/controllers.employeeaddress.js ./apps/application/webapp.js webapp[35]

ERROR in ./application/ironhide.js
Module build failed (from /usr/local/lib/node_modules/babel-loader/lib/index.js):
TypeError: /Users/henry/Documents/application/application-website/webapp/js/application/ironhide.js: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null
    at Object.validate (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:131:11)
    at validateField (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at Object.validate (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/replacement.js:172:7)
    at NodePath._remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:55:10)
    at NodePath.remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:34:8)
    at hooks (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/lib/removal-hooks.js:11:12)
    at NodePath._callRemovalHooks (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:46:9)
    at NodePath.remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:26:12)
    at convertFunctionParams (/usr/local/lib/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-parameters/lib/params.js:88:30)
    at PluginPass.Function (/usr/local/lib/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-parameters/lib/index.js:30:53)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
 @ multi /usr/local/lib/node_modules/babel-polyfill/ ./application/ironhide.js ./application/utility.js ./apps/application/services/services.js ./apps/application/services/services.appsdevices.js ./apps/application/services/services.branding.js ./apps/application/services/services.ionic.webapp.js ./apps/application/services/services.geo.webapp.js ./apps/application/services/services.minicache.js ./apps/application/services/services.devicesync.webapp.js ./apps/application/services/services.unifyapi.webapp.js ./apps/application/services/services.webappmenu.webapp.js ./apps/application/services/services.localforage.webapp.js ./apps/application/services/services.benefitplanutilities.js ./apps/application/services/services.dateutilities.js ./apps/application/directives/directives.earningsrow.js ./apps/application/directives/directives.helptext.js ./apps/application/directives/directives.helpmodal.js ./apps/application/directives/directives.miniplanbuilder.js ./apps/application/directives/directives.progressbar.js ./apps/application/directives/directives.validation.js ./apps/application/directives/directives.cyberfilters.js ./apps/application/directives/directives.chart.js ./apps/application/directives/directives.surveypage.js ./apps/application/directives/directives.focus.js ./apps/application/directives/directives.selectemployeetags.js ./apps/application/directives/directives.selectcompanyid.js ./apps/application/data/applicationDataSource.js ./apps/application/components/applicationGrid.js ./apps/workstation/components/grid.js ./apps/application/controllers/controllers.js ./apps/application/controllers/controllers.auth.js ./apps/application/controllers/controllers.timeline.js ./apps/application/controllers/controllers.commprefs.js ./apps/application/controllers/controllers.account.js ./apps/application/controllers/controllers.addactivity.js ./apps/application/controllers/controllers.appsdevices.js ./apps/application/controllers/controllers.benefit.js ./apps/application/controllers/controllers.earnings.js ./apps/application/controllers/controllers.challenges.js ./apps/application/controllers/controllers.company.js ./apps/application/controllers/controllers.customer.js ./apps/application/controllers/controllers.rewardsmall.js ./apps/application/controllers/controllers.orgsettings.taxreporting.js ./apps/application/controllers/controllers.newrewardsettings.js ./apps/application/controllers/controllers.reports.individuals.js ./apps/application/controllers/controllers.reports.activities.js ./apps/application/controllers/controllers.reports.rewards.js ./apps/application/controllers/controllers.reports.disbursements.js ./apps/application/controllers/controllers.reports.surveys.js ./apps/application/controllers/controllers.reports.healthcard.js ./apps/application/controllers/controllers.communications.js ./apps/application/controllers/controllers.events.js ./apps/application/controllers/controllers.menu.js ./apps/application/controllers/controllers.surveys.js ./apps/application/controllers/controllers.manage_orgs.js ./apps/application/controllers/controllers.employeeaddress.js ./apps/application/webapp.js webapp[1]
```

Our config is:
```js
use: {
    loader: 'babel-loader',
    query: {
        /* This makes babel use the node global install directory as the project root during compile so that presets installed globally load correctly  */
        cwd: path.resolve(nodeModulesPath),
        presets: [
            [
                '@babel/preset-env', {
                    targets: {
                        'ie': '11'
                    },
                    //'corejs': 2, // @see https://babeljs.io/docs/en/babel-preset-env#corejs
                    'useBuiltIns': false
                }
            ]
        ] // presets
    } // query
}
```

This has been mentioned here as well:
https://github.com/apexcharts/apexcharts.js/issues/1359

```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [Node v11.15.0/npm 6.14.2]
- OS: [OSX and Ubuntu]
- Monorepo: [no]
- How you are using Babel: [`loader` via Webpack CLI]
```
The problem started on March 5th when our CI webpacks started failing.

**Comment by nicolo-ribaudo** [comment]
Could you share the contents of `./apps/application/controllers/controllers.addactivity.js`?

**Comment by hparadiz** [comment]
I can't share the whole thing but I believe the issue stems from the presence of for ... in type statements using a `var` keyword to define in place like so:

```js
    for (var i in $scope.ipats) {
        var ipat = $scope.ipats[i];
        if (ipat.AllowDocUploadActivity) {
          /* .... */
        }
    }
```

**Comment by JLHwung** [comment]
Here is a minimal reproduction example
```js
i => { for (var i in {}); }
```
with `transform-parameters` only. [REPL](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYAgvAfCDeIGYHsBOIAUA3Ahi0wB2MAvgJQDcIhQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.8.7&externalPlugins=%40babel%2Fplugin-transform-parameters%407.8.7)

@hparadiz As a workaround, please use `let` declaration if `i` is only accessed inside the loop.
```js
for (let i in $scope.ipats) {
   // loop body
}
```

**Comment by hparadiz** [comment]
I've narrowed down the issue to this commit
https://github.com/babel/babel/commit/9015fda3c106abda6928cf348797a38f09d4b3e0#diff-296be6d02e0f5a9eb2cda2c37099166f

I have downgraded to `@babel/plugin-transform-parameters@7.4.4` and `@babel/preset-env@7.7.1` for now. We have hundreds of instances of (var i in thing) so I'm gonna wait till it's fixed to update the packages.

**Comment by nicolo-ribaudo** [comment]
Released!
