### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by Abdelwahab0** [babel/babel#11365]
### **Bug Report**
I came across this issue while trying to setup babel with webpack to compile back my JavaScript ES6+ modules back to ES5.

```
C:\Users\links\Desktop\JS\9>npm run dev

> forkify@1.0.0 dev C:\Users\links\Desktop\JS\9
> webpack --mode development

Hash: f3ce9beccf2f95d1a12b
Version: webpack 4.42.1
Time: 2192ms
Built at: 04/02/2020 5:18:07 AM
       Asset      Size  Chunks             Chunk Names
  index.html  17.7 KiB          [emitted]
js/bundle.js   481 KiB    main  [emitted]  main
Entrypoint main = js/bundle.js
[0] multi babel-polyfill ./src/js/index.js 40 bytes {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[./src/js/index.js] 1.67 KiB {main} [built] [failed] [1 error]
    + 331 hidden modules

ERROR in ./src/js/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: [BABEL] C:\Users\links\Desktop\JS\9\src\js\index.js: Unknown option: C:\Users\links\Desktop\JS\9\.babelrc.preset. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options.
    at Logger.error (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\options\option-manager.js:226:20)
    at OptionManager.init (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\links\Desktop\JS\9\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\links\Desktop\JS\9\node_modules\babel-loader\lib\index.js:173:20)
 @ multi babel-polyfill ./src/js/index.js main[1]
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 18.3 KiB {HtmlWebpackPlugin_0} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! forkify@1.0.0 dev: `webpack --mode development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the forkify@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\links\AppData\Roaming\npm-cache\_logs\2020-04-02T03_18_07_353Z-debug.log
```
**package.json**

```
{
  "name": "forkify",
  "version": "1.0.0",
  "description": "forkify project",
  "main": "index.js",
  "dependencies": {
    "babel-polyfill": "^6.26.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "html-webpack-plugin": "^4.0.4",
    "webpack": "^4.42.1",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  },
  "scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open"
  },
  "author": "Abdelwahab Ahmed",
  "license": "ISC"
}

```

**webpack-config.js**

```
const path = require ('path');
const HtmlWebpackPlugin = require ('html-webpack-plugin');

module.exports = {
	entry: ['babel-polyfill','./src/js/index.js'],
	output:{
		path:path.resolve(__dirname, 'dist'),
		filename:'js/bundle.js'
	},
	devServer:{
		contentBase:'./dist'
	},
	plugins: [
		new HtmlWebpackPlugin({
			filename:'index.html',
			template:'./src/index.html'
		})
	],
	module:{
		rules: [
			{
				test:/\.js$/,
				exclude:/node_modules/,
				use:{
					loader:	'babel-loader'
				}
			}
		]
	}
};

```
**.babelrc**

```
{
	"preset":[
		"env", {
			"target":{
				"browsers":[

					"last 5 versions",
					"ie >= 8"
				]
			}
		}
	]
}
```

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/59283912/78208028-9fefb700-74a3-11ea-8d13-6e92a2615672.png)

**Comment by existentialism** [comment]
@Abdelwahab0 couple things:

The [`presets` option](https://babeljs.io/docs/en/presets#preset-options) in the config is an array of strings or arrays:

```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": [ ... ]
      }
    }]
  ]
}
```

Also, it looks like you're mixing v6 (babel-core, babel-preset-env) and v7 dependencies (@babel/core, @babel/preset-env). Unless you have a good reason to stick with v6, we recommend using v7.

**Comment by Abdelwahab0** [comment]
> @Abdelwahab0 couple things:
> 
> The [`presets` option](https://babeljs.io/docs/en/presets#preset-options) in the config is an array of strings or arrays of `[plugin name, plugin options]`:
> 
> ```
> {
>   "presets": [
>     ["@babel/preset-env", {
>       "targets": {
>         "browsers": [ ... ]
>       }
>     }]
>   ]
> }
> ```
> 
> Also, it looks like you're mixing v6 (babel-core, babel-preset-env) and v7 dependencies (@babel/core, @babel/preset-env). Unless you have a good reason to stick with v6, we recommend using v7.

so I did that and I got this error in return
it says here I don't have babel-core 7 even tho it shows in the package.json file as a developer dependency
 "@babel/core": "^7.9.0",!
```
ERROR in ./src/js/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "C:\\Users\\links\\Desktop\\JS\\9\\node_modules\\@babel\\preset-env\\lib\\index.js")
    at throwVersionError (C:\Users\links\Desktop\JS\9\node_modules\@babel\helper-plugin-utils\lib\index.js:65:11)
    at Object.assertVersion (C:\Users\links\Desktop\JS\9\node_modules\@babel\helper-plugin-utils\lib\index.js:13:11)
    at C:\Users\links\Desktop\JS\9\node_modules\@babel\preset-env\lib\index.js:208:7
    at C:\Users\links\Desktop\JS\9\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
    at C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\options\option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\links\Desktop\JS\9\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\links\Desktop\JS\9\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\links\Desktop\JS\9\node_modules\babel-loader\lib\index.js:173:20)
 @ multi babel-polyfill ./src/js/index.js main[1]
```

**Comment by JLHwung** [comment]
Please make sure you are specifying the following combinations.
```json
{
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "babel-loader": "^8.0.0",
  }
}
```
I am gonna close this issue since it is due to incompatible versions.
