### ISSUE TITLE
Property name expected type of string but got null

### ISSUE THREAD

**Issue by tenjojeremy** [babel/babel#11411]
`error`
```
TypeError: C:\Dev\Personal_Projects\web-toolkit\src\ambient\particles\index.js: Property name expected type of string but got null
    at validate (C:\Dev\Personal_Projects\web-toolkit\node_modules\@babel\types\lib\definitions\utils.js:160:13)
    at Object.validate (C:\Dev\Personal_Projects\web-toolkit\node_modules\@babel\types\lib\definitions\utils.js:229:7)
    at validateField (C:\Dev\Personal_Projects\web-toolkit\node_modules\@babel\types\lib\validators\validate.js:24:9)
    at validate (C:\Dev\Personal_Projects\web-toolkit\node_modules\@babel\types\lib\validators\validate.js:17:3)
    at builder (C:\Dev\Personal_Projects\web-toolkit\node_modules\@babel\types\lib\builders\builder.js:38:27)
    at Object.Identifier (C:\Dev\Personal_Projects\web-toolkit\node_modules\@babel\types\lib\builders\generated\index.js:337:31)
    at C:\Dev\Personal_Projects\web-toolkit\node_modules\regenerator-transform\lib\hoist.js:32:29
    at Array.forEach (<anonymous>)
    at varDeclToExpr (C:\Dev\Personal_Projects\web-toolkit\node_modules\regenerator-transform\lib\hoist.js:29:23)
    at exit (C:\Dev\Personal_Projects\web-toolkit\node_modules\regenerator-transform\lib\hoist.js:51:20) {
  code: 'BABEL_TRANSFORM_ERROR'

```
`particles\index.js`

```js
const hello = async () => {
  const he = { ll: '2' }
  const { ll } = he
}
```
`babel config`

```js
module.exports = {
  presets: [
    [
      require('@babel/preset-env'),
      {
        targets: 'defaults, not ie <= 11, not edge > 0, not IE_Mob 11',
        modules: false
      }
    ],
    require('@babel/preset-react')
  ],
  plugins: [
    require('react-hot-loader/babel'),
    require('@babel/plugin-transform-regenerator'),
    require('@babel/plugin-syntax-dynamic-import'),
    require('@babel/plugin-syntax-throw-expressions'),
    require('@babel/plugin-transform-runtime'),
    require('babel-plugin-styled-components')
  ],
  env: {
    production: {
      plugins: [require('babel-plugin-transform-react-remove-prop-types')]
    }
  }
}
```

`package.json`

```json
  "dependencies": {
    "@babel/core": "^7.9.0",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-syntax-throw-expressions": "^7.8.3",
    "@babel/plugin-transform-regenerator": "^7.8.7",
    "@babel/plugin-transform-runtime": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "@babel/preset-react": "^7.9.4",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^25.1.0",
    "babel-loader": "^8.1.0",
    "babel-plugin-styled-components": "^1.10.7",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "react-hot-loader": "^4.12.20"
  },
```

`node` version `v12.13.1`

Thanks

**Comment by existentialism** [comment]
@tenjojeremy I believe this is related to https://github.com/babel/babel/issues/10808#issuecomment-611119555

**Comment by liuliangsir** [comment]
Same issue here

**Comment by nicolo-ribaudo** [comment]
@tenjojeremy / @liuliangsir All the browsers with destructuring support also support generators. What is the use case for regenerator when you are not transpiling destructuring?
