### ISSUE TITLE
Build failed Travis (Cannot find module)

### ISSUE THREAD

**Issue by nleborgne** [babel/babel#11439]
I use Travis CI to automate the deployment of my VueJS program. I have the following error when I deploy :

```
> vue-cli-service build
-  Building for production...
 ERROR  Failed to compile with 1 errors10:22:12 AM
 error  in ./src/main.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
[BABEL] /home/travis/build/nleborgne/nCov/src/main.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/travis/build/nleborgne/nCov/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/travis/build/nleborgne/nCov/node_modules/@babel/preset-env/lib/index.js
- /home/travis/build/nleborgne/nCov/node_modules/@vue/babel-preset-app/index.js
- /home/travis/build/nleborgne/nCov/node_modules/@vue/cli-plugin-babel/preset.js
- /home/travis/build/nleborgne/nCov/node_modules/@babel/core/lib/config/files/plugins.js
- /home/travis/build/nleborgne/nCov/node_modules/@babel/core/lib/config/files/index.js
- /home/travis/build/nleborgne/nCov/node_modules/@babel/core/lib/index.js
- /home/travis/build/nleborgne/nCov/node_modules/babel-loader/lib/index.js
- /home/travis/build/nleborgne/nCov/node_modules/loader-runner/lib/loadLoader.js
- /home/travis/build/nleborgne/nCov/node_modules/loader-runner/lib/LoaderRunner.js
- /home/travis/build/nleborgne/nCov/node_modules/thread-loader/dist/worker.js (While processing: "/home/travis/build/nleborgne/nCov/node_modules/@vue/cli-plugin-babel/preset.js")
    at PoolWorker.fromErrorObj (/home/travis/build/nleborgne/nCov/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /home/travis/build/nleborgne/nCov/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/travis/build/nleborgne/nCov/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
```

My devDependencies are :
```
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.2.0",
    "@vue/cli-plugin-eslint": "~4.2.0",
    "@vue/cli-service": "~4.2.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.1.2",
    "vue-template-compiler": "^2.6.11"
  },
```

Thank you

**Comment by JLHwung** [comment]
@nleborgne Thanks for the report.

Please update `@babel/preset-env` to 7.9.0, c.f. https://github.com/nodejs/node/issues/32852#issuecomment-613655150

**Comment by nleborgne** [comment]
@JLHwung the module is not included to my package. Should I add it?

**Comment by JLHwung** [comment]
@nleborgne You can run `npm update --depth 999 @babel/preset-env` to update nested dependencies.

**Comment by dennisdenk** [comment]
Works with npm on version 13 and 14. Yarn not working

**Comment by PLQin** [comment]
我也遇到了这个问题 ， 单单删除 node_modules 没有用， 还得删除 package-lock.json 文件才行
