### ISSUE TITLE
Issue with "ignore" field in .babelrc and babel 5.0.0

### ISSUE THREAD

**Issue by ALF-er** [babel/babel#1145]
Hello! I'm using now babel 5.0.0 with this .babelrc:
```
{
  "stage": 0,
  "optional": [
    "runtime"
  ],
  "ignore": [
    "d3.js"
  ]
}
```

and get this error
```
ERROR in ./src/app/entrypoints/main.jsx
Module build failed: TypeError: undefined is not a function
    at Object.list (C:\dev\projects\trill\node_modules\babel-core\lib\babel\util.js:100:20)
    at list (C:\dev\projects\trill\node_modules\babel-core\lib\babel\transformation\file\option-parsers.js:41:15)
    at File.normalizeOptions (C:\dev\projects\trill\node_modules\babel-core\lib\babel\transformation\file\index.js:126:3
1)
    at new File (C:\dev\projects\trill\node_modules\babel-core\lib\babel\transformation\file\index.js:86:22)
    at Object.transform (C:\dev\projects\trill\node_modules\babel-core\lib\babel\transformation\index.js:18:14)
    at transpile (C:\dev\projects\trill\node_modules\babel-loader\index.js:54:24)
    at Object.module.exports (C:\dev\projects\trill\node_modules\babel-loader\index.js:43:24)
 @ multi main
```

Issue in function
```
function list(val) {
  return val ? val.split(",") : [];
}
```
while it gets array `["d3.js"]` as param.

**Comment by sebmck** [comment]
Fixed via d34480b42ba3930844d4a6b8f6212db3d8e2e88d and released as of 5.0.5. I stuffed up the commit message... Thanks!
