### ISSUE TITLE
Cannot read property 'value' of undefined at new ConfigItem

### ISSUE THREAD

**Issue by lavor** [babel/babel#11465]
I have a problem to run `mocha` test in my application.

I tried to debug it and there is problem with calling `Object.defineProperty` in `ConfigItem.constructor`:
https://github.com/babel/babel/blob/1a2f67191cd4c990019a977735ef9cb185dc0851/packages/babel-core/src/config/item.js#L105-L108

Before calling `Object.defineProperty(this, "_descriptor", ` the property `this._descriptor` has correctly set value of assigned `descriptor`, but after that call the value is `undefined`. It happen once (probably in somspecific situation) after multiple calls of `ConfigItem.constructor`. Hence that result in error:
```
TypeError: Cannot read property 'value' of undefined
    at new ConfigItem (D:\++projects\++datlowe\ui\datlowe-document\node_modules\@babel\core\lib\config\item.js:58:35)
    at createItemFromDescriptor (D:\++projects\++datlowe\ui\datlowe-document\node_modules\@babel\core\lib\config\item.js:26:10)
    at options.plugins.configChain.plugins.map.descriptor (D:\++projects\++datlowe\ui\datlowe-document\node_modules\@babel\core\lib\config\partial.js:109:94)
    at Array.map (<anonymous>)
    at loadPrivatePartialConfig (D:\++projects\++datlowe\ui\datlowe-document\node_modules\@babel\core\lib\config\partial.js:109:41)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (D:\++projects\++datlowe\ui\datlowe-document\node_modules\@babel\core\lib\config\full.js:57:46)
    at loadFullConfig.next (<anonymous>)
    at Function.<anonymous> (D:\++projects\++datlowe\ui\datlowe-document\node_modules\@babel\core\lib\config\index.js:31:43)
    at Generator.next (<anonymous>)
...
```

When I pass value of `descriptor` to the call of `Object.defineProperty`, everything is ok (built code in node_module, not the source code):
```
Object.defineProperty(this, "_descriptor", {
      enumerable: false,
      value: descriptor
    });
```

**Comment by nicolo-ribaudo** [comment]
What node.js version are you using? `Object.defineProperty` doesn't delete the value :thinking:

```js
var a = { x: 1 };
Object.defineProperty(a, "x", { enumerable: false });
console.log(a.x); // 1
```

Can you also add a `console.log(Function.toString.call(Object.defineProperty))` after line 106? Maybe some buggy code is modifying it.

**Comment by lavor** [comment]
I am using node 8.12: 
$ node -v
v8.12.0

Yes, I know that it can be used also for modifying a property. As I wrote, it happen after some time, so the code on those works for some time and once it stop to work.

I added log, you were right, my dependency library `pdfjs-dist` is modyfing it. I am using version 1.10.100 of that library:
```
function objectDefineProperty(obj, name, def) {
      delete obj[name];
      if ('get' in def) {
        obj.__defineGetter__(name, def['get']);
      }
      if ('set' in def) {
        obj.__defineSetter__(name, def['set']);
      }
      if ('value' in def) {
        obj.__defineSetter__(name, function objectDefinePropertySetter(value) {
          this.__defineGetter__(name, function objectDefinePropertyGetter() {
            return value;
          });
          return value;
        });
        obj[name] = def.value;
      }
    }
```

Thanks
