### ISSUE TITLE
`@babel/core` `parseSync` does not handle `exclude` in config

### ISSUE THREAD

**Issue by SimenB** [babel/babel#11540]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo link if applicable: https://github.com/SimenB/babel-parse-exclude

**Input Code**

```js
```

**Expected behavior/code**
Passing an empty string to `parseSync` will throw if config file contains `exclude`.

`Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel`

This is sorta documented (https://babeljs.io/docs/en/options#filename) but I find it very confusing 😀 There aren't really any parse info inferred from filename (I think?), at least not when we pass `parserOpts`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {exclude: /react-native/};
```

**Environment**

```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  npmPackages:
    @babel/core: ^7.9.6 => 7.9.6

```
- Babel version(s):  7.9.6
- Node/npm version: v12
- OS:  osx
- Monorepo:  no
- How you are using Babel: `@babel/core`'s `parseSync`

**Possible Solution**

I would expect this error to be suppressed when we use `parse` API, same as when we use `@babel/parser` directly.

**Additional context/Screenshots**

**Comment by nicolo-ribaudo** [comment]
Consider this example:

```js
module.exports = {
  overrides: [{
    include: /\.tsx?$/,
    plugins: ["@babel/plugin-transform-typescript"]
  }, {
    exclude: /\.tsx?$/,
    plugins: ["@babel/plugin-transform-flow-strip-types"]
  }]
};
```

When you call `babel.parseSync`, it will parse `.ts` and `.tsx` files as TypeScript and everything else as Flow. This example can easily come up in React Native codebase since `node_modules` with React Native usually contain Flow code but the app might be written in TypeScript. So yes, parse info _can_ be inferred from the filename.

If you are using `parserOpts` you could directly using `@babel/parser`, but if you want to load the user config then the filename can be an important information.

In https://github.com/babel/babel/pull/11316 I'm adding support for `include`/`exclude` without a filename, using a function instead of a RegExp. If you think that it's needed, I could extract that piece from the PR and open it targeting Babel 7.

**Comment by SimenB** [comment]
This issue was a result of debugging why https://github.com/istanbuljs/istanbuljs/pull/555 broke.

It might just be that a better error is needed, describing why a filename would be needed and how to skip it. Solution in this case is https://github.com/istanbuljs/istanbuljs/pull/562

**Comment by SimenB** [comment]
@nicolo-ribaudo btw, without adding `Error.stackTranceLimit = 100` the error we ger is this:

```
Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel
    at matchPattern (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:431:11)
    at /Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:418:35
    at Array.some (<anonymous>)
    at matchesPatterns (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:418:19)
    at configFieldIsApplicable (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:400:10)
    at configIsApplicable (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:395:233)
    at /Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:245:9
    at Generator.next (<anonymous>)
    at buildRootChain (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:90:27)
    at buildRootChain.next (<anonymous>)
```

Doesn't even point back to the `parseSync` call, which might have had an impact in how confusing this was? Not sure, and also very much not sure if there's anything you can do 😀 Maybe some `callerError` you pass around and reuse stack from or some such?

**Comment by nicolo-ribaudo** [comment]
@loganfsmyth Do you think that it would be possible for `gensync` to restore the stack frames missed due to the generators usage?

**Comment by coreyfarrell** [comment]
@nicolo-ribaudo It's not that the stack frames are missed, it's just that there are so many they overload the default `Error.stackTraceLimit` of 10.  Here is the complete stack trace @SimenB shared with me, produced when `Error.stackTraceLimit = 100;` was set:

```
Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel
    at matchPattern (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:431:11)
    at /Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:418:35
    at Array.some (<anonymous>)
    at matchesPatterns (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:418:19)
    at configFieldIsApplicable (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:400:10)
    at configIsApplicable (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:395:233)
    at /Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:245:9
    at Generator.next (<anonymous>)
    at buildRootChain (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/config-chain.js:90:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/partial.js:95:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (/Users/simen/repos/jest/node_modules/@babel/core/lib/config/full.js:57:46)
    at loadFullConfig.next (<anonymous>)
    at parse (/Users/simen/repos/jest/node_modules/@babel/core/lib/parse.js:27:45)
    at parse.next (<anonymous>)
    at evaluateSync (/Users/simen/repos/jest/node_modules/gensync/index.js:244:28)
    at sync (/Users/simen/repos/jest/node_modules/gensync/index.js:84:14)
    at getAst (/Users/simen/repos/jest/node_modules/istanbul-lib-instrument/dist/read-coverage.js:25:30)
    at readInitialCoverage (/Users/simen/repos/jest/node_modules/istanbul-lib-instrument/dist/read-coverage.js:37:15)
    at Object.<anonymous> (/Users/simen/repos/jest/file.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

Everything above `loadFullConfig` from `@babel/core/lib/config/full.js` is not really helpful to users of babel IMO.  One way would be to have a try/catch in `loadFullConfig` rewrite the stack-trace of config validation errors:
```js
try {
   // call to loadPrivatePartialConfig
} catch (error) {
  if (isConfigValidationError(error) && Error.captureStackTrace) {
    Error.captureStackTrace(error);
  }

  throw error;
}
```

**Comment by nicolo-ribaudo** [comment]
I'm working on this:
```
Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel
    at /home/nicolo/Documenti/dev/babel-bugs/babel-parse-exclude/babel.config.js
    at iternal Babel functions (elided)
    at parseSync (/home/nicolo/Documenti/dev/babel/babel/packages/babel-core/lib/parse.js:51:51)
    at Object.<anonymous> (/home/nicolo/Documenti/dev/babel-bugs/babel-parse-exclude/file.js:5:1)
```

**Comment by SimenB** [comment]
woah 😀

**Comment by nicolo-ribaudo** [comment]
- The underlying issue was fixed a while ago by the fact that now `exclude`/`include` [can be functions](https://babeljs.io/docs/en/options#matchpattern) so that can receive an `undefined` filename.
- The problem about the unhelpful stack trace was just fixed :smile:
