### ISSUE TITLE
Flow documentation example out of date/invalid.

### ISSUE THREAD

**Issue by SomeoneWeird** [babel/babel#1156]
The flow example [here](https://babeljs.io/docs/usage/transformers/other/flow/) has an example of 
```js
function foo(one: any, two: number, ?three): string {}
```
which when run, gives you 
```
/usr/local/lib/node_modules/babel/lib/babel/helpers/parse.js:60
    throw err;
          ^
SyntaxError: a.js: Unexpected token (1:36)
> 1 | function foo(one: any, two: number, ?three): string {}
    |                                     ^
  2 |
    at raise (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:343:15)
    at unexpected (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2278:5)
    at parseBindingAtom (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2395:9)
    at parseMaybeDefault (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2436:20)
    at parseBindingList (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2412:20)
    at parseFunctionParams (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3572:19)
    at parseFunction (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3548:5)
    at parseFunctionStatement (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2749:12)
    at parseStatement (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2600:14)
    at parseTopLevel (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2567:18)
```
It works if you do `three: ?any` instead of `?three` though, so I'm wondering if it's a regression or invalid documentation.

**Comment by sebmck** [comment]
Should be:

```javascript
function foo(one: any, two: number, three?): string {}
```

Also as per the README:

> For documentation and website issues please visit the [babel.github.io](https://github.com/babel/babel.github.io) repo.

**Comment by SomeoneWeird** [comment]
Wasn't sure if it was documentation or regression, my bad.
