### ISSUE TITLE
Imports/requires return undefined

### ISSUE THREAD

**Issue by haltman-at** [babel/babel#11562]
## Bug Report

We've been using Babel v6, and I recently attempted to upgrade to Babel v7.  The project in question is the Truffle Debugger; the overall repo can be found [here](https://github.com/trufflesuite/truffle/tree/babel-up) and the particular package can be found [here](https://github.com/trufflesuite/truffle/tree/babel-up/packages/debugger).  Note that I'm linking to the branch where I attempted the Babel upgrade, not our current development branch `develop`.

Unfortunately, on upgrading Babel to v7, I found that project-internal imports no longer worked; they all returned `undefined`.  Obviously, this makes it impossible to use Babel v7.

Note that we are using Babel together with Webpack, via `babel-loader`.  I had initially assumed that the problem was due to the Webpack upgrade rather than the Babel upgrade, but we managed to successfully separately upgrade Webpack to v4, so it would appear to be a Babel problem.

We are also using `@babel/register` to get source maps.  I'm a little confused here, because your "Environment" template suggests that `@babel/register` is a separate thing and that they don't go together?  I'm a little confused.

**Current Behavior**

Imports/requires return `undefined`.  So, when we attempt to run our tests, for instance, we get the following message:

```
TypeError: Cannot read property 'transaction' of undefined
    at Module.call (/home/sniffnoy/truffle/truffle/packages/debugger/lib/solidity/selectors/index.js:133:94)
    at require (/home/sniffnoy/truffle/truffle/packages/debugger/dist/webpack/bootstrap:19:22)
    at Module.call (/home/sniffnoy/truffle/truffle/packages/debugger/lib/data/selectors/index.js:35:19)
    at require (/home/sniffnoy/truffle/truffle/packages/debugger/dist/webpack/bootstrap:19:22)
    at Module.call (/home/sniffnoy/truffle/truffle/packages/debugger/lib/session/index.js:38:18)
    at require (/home/sniffnoy/truffle/truffle/packages/debugger/dist/webpack/bootstrap:19:22)
    at Module.call (/home/sniffnoy/truffle/truffle/packages/debugger/lib/debugger.js:17:16)
    at e (/home/sniffnoy/truffle/truffle/packages/debugger/dist/webpack/bootstrap:19:22)
    at Module.call (/home/sniffnoy/truffle/truffle/packages/debugger/test/ast.js:9:1)
    at __webpack_require__ (/home/sniffnoy/truffle/truffle/packages/debugger/dist/webpack/bootstrap:19:22)
    at forEach (/home/sniffnoy/truffle/truffle/node_modules/mocha-webpack/lib/entry.js:3:20)
    at Array.forEach (<anonymous>)
    at Object.call (/home/sniffnoy/truffle/truffle/node_modules/mocha-webpack/lib/entry.js:10:24)
    at __webpack_require__ (/home/sniffnoy/truffle/truffle/packages/debugger/dist/webpack/bootstrap:19:22)
    at /home/sniffnoy/truffle/truffle/packages/debugger/dist/webpack/bootstrap:83:10
    at factory (/home/sniffnoy/truffle/truffle/packages/debugger/dist/debugger.js:1:1152)
    at /home/sniffnoy/truffle/truffle/packages/debugger/dist/webpack/universalModuleDefinition:3:20
    at Object.<anonymous> (/home/sniffnoy/truffle/truffle/packages/debugger/dist/webpack/universalModuleDefinition:1:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/home/sniffnoy/truffle/truffle/node_modules/mocha-webpack/lib/util/registerRequireHook.js:148:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /home/sniffnoy/truffle/truffle/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/sniffnoy/truffle/truffle/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/sniffnoy/truffle/truffle/node_modules/mocha/lib/mocha.js:576:10)
    at /home/sniffnoy/truffle/truffle/node_modules/mocha-webpack/lib/runner/TestRunner.js:191:27
    at /home/sniffnoy/truffle/truffle/node_modules/mocha-webpack/lib/webpack/compiler/registerReadyCallback.js:26:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sniffnoy/truffle/truffle/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sniffnoy/truffle/truffle/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:304:22)
    at Compiler.emitRecords (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:499:39)
    at emitAssets.err (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:298:10)
    at callback (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:485:14)
    at _err0 (eval at create (/home/sniffnoy/truffle/truffle/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at handleAfterEmit (/home/sniffnoy/truffle/truffle/node_modules/write-file-webpack-plugin/src/WriteFileWebpackPlugin.js:195:7)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sniffnoy/truffle/truffle/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sniffnoy/truffle/truffle/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:482:27)
    at /home/sniffnoy/truffle/truffle/node_modules/neo-async/async.js:2818:7
    at done (/home/sniffnoy/truffle/truffle/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sniffnoy/truffle/truffle/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:464:33)
    at MemoryFileSystem.writeFile (/home/sniffnoy/truffle/truffle/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:462:30)
    at asyncLib.forEachLimit (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:476:7)
    at arrayIterator (/home/sniffnoy/truffle/truffle/node_modules/neo-async/async.js:3467:9)
    at done (/home/sniffnoy/truffle/truffle/node_modules/neo-async/async.js:3527:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sniffnoy/truffle/truffle/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sniffnoy/truffle/truffle/node_modules/tapable/lib/Hook.js:154:20)
    at outputFileSystem.writeFile.err (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:464:33)
    at MemoryFileSystem.writeFile (/home/sniffnoy/truffle/truffle/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:462:30)
    at asyncLib.forEachLimit (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:476:7)
    at arrayIterator (/home/sniffnoy/truffle/truffle/node_modules/neo-async/async.js:3467:9)
    at timesSync (/home/sniffnoy/truffle/truffle/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/home/sniffnoy/truffle/truffle/node_modules/neo-async/async.js:3463:5)
    at emitFiles (/home/sniffnoy/truffle/truffle/node_modules/webpack/lib/Compiler.js:358:13)
    at Immediate._onImmediate (/home/sniffnoy/truffle/truffle/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

This is due to to the following import in [lib/solidity/selectors/index.js]() returning undefined:
```import evm from "lib/evm/selectors";```

Note that external imports seem to be fine, but this internal import results in `evm == undefined`.

**Input Code**

You can see our repo, and the particular file where we get the error, linked above.

It may also help to note here that `@babel/register` is invoked in [this file](https://github.com/trufflesuite/truffle/blob/babel-up/packages/debugger/debugger.js).

**Expected behavior/code**

It should compile like before!

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

As mentioned above, we're using Babel via Webpack and `babel-loader`.  You can see all our webpack configuration files in [this folder](https://github.com/trufflesuite/truffle/tree/babel-up/packages/debugger/webpack).  I'll paste below the contents of `webpack.config-common.js`, but it may be worth looking at the other ones, too (in particular `webpack.config-test.js`; as I first noticed this problem in tests).

- Filename: `webpack.config-common.js`

```js
const path = require("path");
const nodeExternals = require("webpack-node-externals");

module.exports = {
  entry: "./debugger",

  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "babel-loader",
        query: {
          presets: [["babel-preset-env", { targets: { node: "6.14" } }]],
          plugins: [
            "@babel/plugin-proposal-object-rest-spread",
            "@babel/plugin-transform-runtime"
          ],
          sourceType: "module"
        },
        include: [path.resolve(__dirname, "..", "lib")]
      }
    ]
  },

  target: "node",

  mode: "production",

  output: {
    library: "Debugger",
    libraryTarget: "umd",
    umdNamedDefine: true,

    filename: "debugger.js",
    path: path.join(__dirname, "..", "dist"),
    devtoolModuleFilenameTemplate: "[absolute-resource-path]",
    devtoolFallbackModuleFilenameTemplate: "[absolute-resource-path]?[hash]"
  },

  resolve: {
    modules: [path.resolve(__dirname, ".."), "node_modules"]
  },

  // in order to ignore all modules in node_modules folder
  externals: [
    nodeExternals({
      modulesFromFile: true,
      whitelist: ["node-interval-tree"]
    })
  ],

  devtool: "source-map"
};
```

**Environment**

- Babel version(s): 7.8.4
- Node/npm version: 10.15.3 / 6.14.5
- OS: Linux 4.15 Linux Mint 19.1 (Tessa)
- Monorepo: We do use a monorepo, managed using Yarn and Lerna.  Babel is used only in this package of it.
- How you are using Babel: We're using it via Webpack 4.43.0 and `babel-loader` 8.0.6.  We're also using `@babel/register` 7.8.6, but I'm confused as to the relevance of that?

More version info can of course be found in the [package.json](https://github.com/trufflesuite/truffle/blob/babel-up/packages/debugger/package.json).

**Comment by racerxdl** [comment]
:+1: 

I found out that happens when there is a `_interopRequireDefault` with a file inside the project which defers the resolving of modules.

**Comment by liuxingbaoyu** [comment]
Because this issue is out of date, I will close it.
