### ISSUE TITLE
Error: Cannot find module '../constants'

### ISSUE THREAD

**Issue by phil-warner** [babel/babel#11564]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
When running webpack I'm getting the following error on roughly half of the entry points that get picked up by babel-loader:

overlapping.get is not a function (While processing: "/Users/me/Documents/GitHub/my-project/node_modules/@babel/preset-env/lib/index.js"

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo link if applicable:
n/a
**Input Code**

```js
{
        test: /\.js$/,
        exclude: /node_modules\/(?![url-regex|normalize-url])|vendor/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
            cacheDirectory: true
          }
        }
      }
```

**Expected behavior/code**
Expecting webpack to bundle my files.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "browsers": [ ">0.5%", "last 2 versions", "not ie <= 11"]
      }
    }]
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-transform-for-of"
  ]
}

```

**Environment**

```
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v10.15.3/bin/npm
  npmPackages:
    @babel/core: ^7.9.6 => 7.9.6 
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.8.3 
    @babel/plugin-proposal-object-rest-spread: ^7.9.6 => 7.9.6 
    @babel/plugin-syntax-dynamic-import: ^7.8.3 => 7.8.3 
    @babel/plugin-transform-for-of: ^7.9.0 => 7.9.0 
    @babel/plugin-transform-spread: ^7.8.3 => 7.8.3 
    @babel/polyfill: ^7.8.7 => 7.8.7 
    @babel/preset-env: ^7.9.6 => 7.9.6 
    babel-cli: ^6.26.0 => 6.26.0 
    babel-eslint: ^10.1.0 => 10.1.0 
    babel-loader: ^8.1.0 => 8.1.0 
    babel-plugin-add-module-exports: ^0.2.1 => 0.2.1 
    babel-plugin-syntax-async-functions: ^6.13.0 => 6.13.0 
    babel-polyfill: ^6.26.0 => 6.26.0 
    babel-preset-env: ^1.7.0 => 1.7.0 
    babel-preset-stage-3: ^6.24.1 => 6.24.1 
    eslint: ^5.16.0 => 5.16.0 
    eslint-plugin-babel: ^5.3.0 => 5.3.0 
    webpack: ^4.43.0 => 4.43.0 
```
- How you are using Babel: loader

**Possible Solution**
Unknown

**Additional context/Screenshots**
n/a

**Comment by nicolo-ribaudo** [comment]
It seems like you are compiling Babel with itself. Try this `exclude`:

```js
        exclude: /node_modules\/(?!url-regex|normalize-url|@babel)|vendor/,
```

If it doesn't work, we need a reproducible example.

**Comment by phil-warner** [comment]
Hi Nicolo

Thanks. Maybe some progress. I'm now getting this:

```
Module build failed (from ../node_modules/babel-loader/lib/index.js):
Error: Cannot find module '../constants'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
```

**Comment by existentialism** [comment]
@phil-warner sidenote, you have both v6 and v7 babel deps in your package.json, might want to switch to v7 completely (babel-* -> @babel/*)

**Comment by phil-warner** [comment]
Thanks. Would you be able to offer a little more info on how I'd go about that?

**Comment by phil-warner** [comment]
@existentialism - thank you. I've replaced everything that was v6.

I also upgraded node to the lts version (12.16.3) on the off-chance that my installation was missing a core module, but I'm still getting the same issue. Here is the require stack:

```
Error: Cannot find module '../constants'
Require stack:
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/definitions/core.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/definitions/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/builders/builder.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/builders/generated/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/utils/react/cleanJSXElementLiteralChild.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/builders/react/buildChildren.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/helper-get-function-arity/lib/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/helper-function-name/lib/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/helper-wrap-function/lib/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/helper-remap-async-to-generator/lib/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/plugin-proposal-async-generator-functions/lib/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/preset-env/lib/available-plugins.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/preset-env/lib/plugins-compat-data.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/preset-env/lib/normalize-options.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/preset-env/lib/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/core/lib/config/files/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/@babel/core/lib/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/babel-loader/lib/index.js
- /Users/me/Documents/GitHub/my-project/node_modules/loader-runner/lib/loadLoader.js
- /Users/me/Documents/GitHub/my-project/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/me/Documents/GitHub/my-project/node_modules/webpack/lib/NormalModule.js
- /Users/me/Documents/GitHub/my-project/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/me/Documents/GitHub/my-project/node_modules/webpack/lib/Compiler.js
- /Users/me/Documents/GitHub/my-project/node_modules/webpack/lib/webpack.js
- /Users/me/Documents/GitHub/my-project/node_modules/webpack-cli/bin/utils/validate-options.js
- /Users/me/Documents/GitHub/my-project/node_modules/webpack-cli/bin/utils/convert-argv.js
- /Users/me/Documents/GitHub/my-project/node_modules/webpack-cli/bin/cli.js
- /Users/me/Documents/GitHub/my-project/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/definitions/core.js:14:18)
    at Module._compile (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/definitions/index.js:70:1)
    at Module._compile (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/builders/builder.js:10:20)
    at Module._compile (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/builders/generated/index.js:248:39)
    at Module._compile (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/utils/react/cleanJSXElementLiteralChild.js:8:18)
    at Module._compile (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/me/Documents/GitHub/my-project/node_modules/@babel/types/lib/builders/react/buildChildren.js:10:59)
    at Module._compile (/Users/me/Documents/GitHub/my-project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
```

**Comment by phil-warner** [comment]
This problem was fixed by adding "@babel/plugin-transform-for-of" to by Babel plugins.
