### ISSUE TITLE
Class fields not recognized by @babel/plugin-proposal-class-properties.

### ISSUE THREAD

**Issue by NagabhushanS** [babel/babel#11584]
I am trying to get around this issue for quite some time. I have added the plugin @babel/plugin-proposal-class-properties for es6+ class-fields which are an experimental feature. However, it still gives me a syntax error.
Here is my sample package.json
````
{
  "name": "setup",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon -L ./app.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-do-expressions": "^7.0.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-function-sent": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.0.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0",
    "@babel/plugin-proposal-pipeline-operator": "^7.0.0",
    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/register": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.4.2",
    "concurrently": "^3.5.1",
    "husky": "^1.0.0",
    "jest": "^25.0.0",
    "jest-cli": "^25.0.0",
    "jest-express": "^1.6.0",
    "lint-staged": "^7.3.0",
    "nodemon": "^1.17.5"
  }
}
````
.babelrc:

```
{
    "presets": [
      "@babel/preset-env"
    ],
    "plugins": [
      "@babel/transform-runtime",
      "@babel/plugin-syntax-dynamic-import",
      "@babel/plugin-syntax-import-meta",
      "@babel/plugin-proposal-class-properties",
      "@babel/plugin-proposal-json-strings",
      [
        "@babel/plugin-proposal-decorators",
        {
          "legacy": true
        }
      ],
      "@babel/plugin-proposal-function-sent",
      "@babel/plugin-proposal-export-namespace-from",
      "@babel/plugin-proposal-numeric-separator",
      "@babel/plugin-proposal-throw-expressions",
      "@babel/plugin-proposal-export-default-from",
      "@babel/plugin-proposal-logical-assignment-operators",
      "@babel/plugin-proposal-optional-chaining",
      [
        "@babel/plugin-proposal-pipeline-operator",
        {
          "proposal": "minimal"
        }
      ],
      "@babel/plugin-proposal-nullish-coalescing-operator",
      "@babel/plugin-proposal-do-expressions"
    ]
  }
```

Sample app.js:

```
class Sample {

    z = 2;

}
  
```

And here is the error:

```
C:\Users\nagab\OneDrive\Desktop\WEB\setup\app.js:5
    z = 2;
      ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by JLHwung** [comment]
Where is your `.babelrc` located? If it is not at the root of your project, babel will not apply `.babelrc` to `WEB\setup\app.js`.

If you don't have complex babel configuration, please rename it into `babel.config.json`.

**Comment by NagabhushanS** [comment]
Hi JLHwung, the .babelrc file is in the same folder as app.js and package.json (in other words root of the node project). I also tried removing babelrc and adding babel.config.json. It still doesn't work.

**Comment by NagabhushanS** [comment]
I have seen that some stackoverflow question which had issues with class fields handling in babel, but none of the solutions worked since most solutions were either telling you to properly config webpack or were related to react. I am using neither of them.

**Comment by nicolo-ribaudo** [comment]
Trying to isolate the problem: if you run your app without nodemon, does it work?

**Comment by JLHwung** [comment]
I assume you are invoking babel through `@babel/register`, where do you `require("@babel/register")`?

Note that `@babel/register` will only be applied on files _required_ later than the entry, which means if you mix class properties and `require("@babel/register")` in `setup\app.js`, they won't work
```
// the following doesn't work
require("@babel/register")
// these codes will not be compiled via babel because it is not in a separate required module
class A { a = 1 };
```

BTW can you attach the output of
```
DEBUG=babel:config:* npm start
```

**Comment by NagabhushanS** [comment]
Hi JLHWung, Thanks for pointing out about @babel/register, I actually have a separate bin folder where there is a module called app.js which require babel-register and the module app.js (which is at root of the project folder). I accidently was executing app.js instead of bin/app.js.
