### ISSUE TITLE
toStatement does not work with CallExpression

### ISSUE THREAD

**Issue by gamefreak** [babel/babel#1158]
While experimenting with the new plugin API, I found that trying to use `toStatement` to turn a `CallExpression` into an `ExpressionStatement` does not work, while it does work for `AssignmentExpression`

If there is a reason for not simply supporting all `*Expression` types then it would be useful to at least support these as well:

* `YieldExpression`
* `AwaitExpression`
* `UpdateExpression`
* `UnaryExpression` (because of the `delete` operator)

Example code to reproduce:

```javascript
import { Transformer, types as t } from 'babel-core';

const Example = new Transformer('example', {
  TemplateLiteral(node, parent, scope) {
    let consoleLog = t.memberExpression(t.identifier('console'), t.identifier('log'));
    let callExpr = t.callExpression(consoleLog, [t.literal('Example output')])
    return t.toStatement(callExpr);
  }
});

let output = require('babel').transform('`Example input`', {
  plugins: [Example]
});

console.log(output.code);
```

babel's output:

```
/THEPATH/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
Error: unknown: cannot turn CallExpression to a statement
    at Object.toStatement (/THEPATH/node_modules/babel-core/lib/babel/types/converters.js:224:13)
    at TraversalPath.TemplateLiteral (/THEPATH/example.es:7:14)
    at TraversalPath.call (/THEPATH/node_modules/babel-core/lib/babel/traversal/path/index.js:443:26)
    at TraversalPath.visit (/THEPATH/node_modules/babel-core/lib/babel/traversal/path/index.js:455:10)
    at TraversalContext.visitSingle (/THEPATH/node_modules/babel-core/lib/babel/traversal/context.js:63:41)
    at TraversalContext.visit (/THEPATH/node_modules/babel-core/lib/babel/traversal/context.js:73:19)
    at Function.traverse.node (/THEPATH/node_modules/babel-core/lib/babel/traversal/index.js:44:17)
    at TraversalPath.visit (/THEPATH/node_modules/babel-core/lib/babel/traversal/path/index.js:472:18)
    at TraversalContext.visitMultiple (/THEPATH/node_modules/babel-core/lib/babel/traversal/context.js:50:16)
    at TraversalContext.visit (/THEPATH/node_modules/babel-core/lib/babel/traversal/context.js:71:19)
```

**Comment by sebmck** [comment]
You aren't supposed to be using `t.toStatement` for that. Why do you want to turn a `TemplateLiteral` into a statement anyway?

**Comment by gamefreak** [comment]
The end goal is pre-compiling tagged template literals (imagine implementing the React transform as ``JSX`<tag/>` `` and still producing the `React.createElement` in the compiled output)

The template literal was just distilling it to a minimal example.

**Comment by sebmck** [comment]
Well you're replacing an expression with an expression so there's no need to turn it into a statement at all.
