### ISSUE TITLE
Transpilation error

### ISSUE THREAD

**Issue by mconnol6** [babel/babel#11609]
## Bug Report

**Current behavior**

Transpiler is converting page.fill (function from [playwright](https://github.com/microsoft/playwright)) to Array.fill.

I opened an [issue with playwright](https://github.com/microsoft/playwright/issues/2345), and they think that the issue is either with babel or babel-jest.

**Input Code**

```js
import playwright from 'playwright';

describe(`UI Tests with Playwright`, () => {

    test(`Should load page`, async () => {
        let browser = null;
        let page = null;    

        browser = await playwright.chromium.launch({headless:false});
        page = await browser.newPage();
        await page.goto('https://github.com/microsoft/playwright/tree/master/docs', {
            waitUntil: 'networkidle0',
        });
        await page.fill('input.header-search-input', 'search term');
        await browser.close();
    });
});
```

**Expected behavior**
When I run this code, I receive this error: 

Cannot find module 'core-js/modules/es.array.fill' from 'spec/test.ts'
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:308:11)
at Object. (spec/test.ts:5:1)

Expected behavior is for the code to be transpiled to use page.fill from the playwright library, not Array.fill. 

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Babel config:
```js
module.exports = function(api) {
    api.cache(true);

    return {
        presets: [
            [
                '@babel/preset-env',
                {
                    useBuiltIns: 'usage',
                    corejs: 3,
                    targets: {
                        browsers: ['> 0.1%', 'last 3 versions', 'ie 11'],
                    },
                },
            ],
            '@babel/react',
            '@babel/preset-typescript',
        ],
        plugins: [
            '@babel/transform-runtime',
            '@babel/plugin-transform-typescript',
            '@babel/plugin-proposal-class-properties',
        ],
    };
};
```

Jest config:
```js
module.exports = {
    verbose: true,
    resetMocks: true,
    resetModules: true,
    restoreMocks: true,
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
    setupFilesAfterEnv: [path.resolve(__dirname, './test/setupTests.ts')],
    reporters: ['default', ['jest-junit', { outputDirectory: 'coverage' }]],
    coverageReporters: ['json', 'lcov', 'text', 'clover', 'cobertura', 'html'],
    moduleNameMapper: {
        '.(scss|jpg|png)$': path.resolve(__dirname, './test/empty-module.ts'),
    },
    // tell babel to travel to the root for babel.config.js
    transform: { '^.+\\.[t|j]sx?$': [ 'babel-jest'] },
    roots: ['<rootDir>/spec/'],
    testTimeout: 60000,
};
```

**Environment**

```
System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.9.6 => 7.9.6
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.8.3
    @babel/plugin-transform-runtime: ^7.9.6 => 7.9.6
    @babel/plugin-transform-typescript: ^7.9.6 => 7.9.6
    @babel/preset-env: ^7.9.6 => 7.9.6
    @babel/preset-react: ^7.9.4 => 7.9.4
    @babel/preset-typescript: ^7.9.0 => 7.9.0
    babel-jest: ^26.0.1 => 26.0.1
    babel-polyfill: ^6.26.0 => 6.26.0
    jest: ^26.0.1 => 26.0.1
```

**Comment by existentialism** [comment]
To be clear, we aren't converting page.fill into Array.fill... but `usage` is going to add an import statement for Array.fill due to seeing `.fill()` being used (not a perfect detection mechanism).

Do you have `core-js` as a devDependency? I see `babel-polyfill` v6 listed above which isn't going to work.

**Comment by mconnol6** [comment]
Hello, I uninstalled `babel-polyfill` and installed `core-js@3` and this fixed the issue. Thanks for your help!
