### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by umer310** [babel/babel#11638]
Hash: 226316e2f827f75e552a
Version: webpack 4.43.0
Time: 859ms
Built at: 05/28/2020 6:11:32 PM
       Asset      Size  Chunks             Chunk Names
  index.html  17.7 KiB          [emitted]
js/bundle.js   483 KiB    main  [emitted]  main
Entrypoint main = js/bundle.js
[0] multi babel-polyfill ./src/js/index.js 40 bytes {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[./src/js/index.js] 3.51 KiB {main} [not cacheable] [built] [failed] [1 error]
    + 331 hidden modules

ERROR in ./src/js/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/core'
Require stack:
- D:\ofline\forkify\starter\node_modules\babel-loader\lib\index.js
- D:\ofline\forkify\starter\node_modules\loader-runner\lib\loadLoader.js
- D:\ofline\forkify\starter\node_modules\loader-runner\lib\LoaderRunner.js
- D:\ofline\forkify\starter\node_modules\webpack\lib\NormalModule.js
- D:\ofline\forkify\starter\node_modules\webpack\lib\NormalModuleFactory.js
- D:\ofline\forkify\starter\node_modules\webpack\lib\Compiler.js
- D:\ofline\forkify\starter\node_modules\webpack\lib\webpack.js
- D:\ofline\forkify\starter\node_modules\webpack-cli\bin\utils\validate-options.js
- D:\ofline\forkify\starter\node_modules\webpack-cli\bin\utils\convert-argv.js
- D:\ofline\forkify\starter\node_modules\webpack-cli\bin\cli.js
- D:\ofline\forkify\starter\node_modules\webpack\bin\webpack.js
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (D:\ofline\forkify\starter\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (D:\ofline\forkify\starter\node_modules\babel-loader\lib\index.js:10:11)
    at Module._compile (D:\ofline\forkify\starter\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (D:\ofline\forkify\starter\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at loadLoader (D:\ofline\forkify\starter\node_modules\loader-runner\lib\loadLoader.js:18:17)
    at iteratePitchingLoaders (D:\ofline\forkify\starter\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\ofline\forkify\starter\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\ofline\forkify\starter\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (D:\ofline\forkify\starter\node_modules\webpack\lib\NormalModule.js:446:15)
    at Compilation.buildModule (D:\ofline\forkify\starter\node_modules\webpack\lib\Compilation.js:739:10)
    at D:\ofline\forkify\starter\node_modules\webpack\lib\Compilation.js:981:14
    at D:\ofline\forkify\starter\node_modules\webpack\lib\NormalModuleFactory.js:409:6
    at D:\ofline\forkify\starter\node_modules\webpack\lib\NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (D:\ofline\forkify\starter\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (D:\ofline\forkify\starter\node_modules\tapable\lib\Hook.js:154:20)
    at D:\ofline\forkify\starter\node_modules\webpack\lib\NormalModuleFactory.js:138:29
    at D:\ofline\forkify\starter\node_modules\webpack\lib\NormalModuleFactory.js:346:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
 @ multi babel-polyfill ./src/js/index.js main[1]
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 18.3 KiB {HtmlWebpackPlugin_0} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! forkify@1.0.0 dev: `webpack --mode development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the forkify@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Umer\AppData\Roaming\npm-cache\_logs\2020-05-28T13_11_32_107Z-debug.log

{
  "name": "forkify",
  "version": "1.0.0",
  "description": "forkify project",
  "main": "index.js",
  "scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production"
  },
  "author": "umer",
  "license": "ISC",
  "devDependencies": {
    "babel": "^6.23.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.1.0",
    "babel-plugin-check-es2015-constants": "^6.22.0",
    "babel-plugin-transform-es2015-arrow-functions": "^6.22.0",
    "babel-plugin-transform-es2015-block-scoping": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "html-webpack-plugin": "^4.3.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "jquery": "^3.5.1"
  }
}

const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: ['babel-polyfill', './src/js/index.js'],
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'js/bundle.js'
    },
    devServer: {
        contentBase: './dist'
    },
    plugins: [
        new HtmlWebpackPlugin({
            filename: 'index.html',
            template: './src/index.html'
        })
    ], 
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader'
                }
            }
        ]
    }
};

**Comment by existentialism** [comment]
> babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.

😀
