### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by alexwasner** [babel/babel#11659]
## Bug Report

**Current behavior**
After upgrading to React Native `0.63.0-rc.1`, all my tests started failing with the error `Cannot convert undefined or null to object at assign`. I upgraded from `0.62.2` who's diff can be found [here](https://react-native-community.github.io/upgrade-helper/)

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

**Input Code**

```bash
 FAIL  __tests__/<testnamehere>.test.tsx
  ● Test suite failed to run

    TypeError: Cannot convert undefined or null to object
        at assign (<anonymous>)

      at _extends (node_modules/@babel/runtime/helpers/extends.js:16:19)
      at node_modules/@testing-library/react-native/dist/preset/mock-modules.js:41:25
      at Object.require (node_modules/react-native/Libraries/Image/Image.ios.js:15:21)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        8.534 s
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
"dependencies": {
    "@react-native-community/async-storage": "^1.6.3",
    "@react-native-community/netinfo": "^5.3.3",
    "@react-native-community/push-notification-ios": "^1.2.0",
    "@types/i18n-js": "^3.0.1",
    "react": "16.13.1",
    "react-native": "0.63.0-rc.1",
    "react-native-background-fetch": "^3.0.3",
    "react-native-device-info": "^5.5.4",
    "react-native-fast-image": "^7.0.2",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-inappbrowser-reborn": "^3.3.4",
    "react-native-rate": "^1.2.1",
    "react-native-permissions": "^2.1.5",
    "react-native-reanimated": "^1.7.0",
    "react-native-scalable-image": "^1.0.0",
    "react-native-screens": "^2.0.0-alpha.22",
    "react-native-share": "^3.0.0",
    "react-native-shared-element": "^0.5.3",
    "react-native-svg": "^12.1.0",
    "react-native-svg-icon": "^0.8.1",
    "react-native-version-number": "^0.3.6",
    "react-native-webview": "^9.0.1",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.8.2",
    "styled-components": "^4.4.1",
  },
  "devDependencies": {
    "@apollo/react-testing": "^3.0.1",
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "@testing-library/react-native": "^5.0.3",
    "@types/detox": "^14.5.2",
    "@types/jasmine": "^3.5.1",
    "@types/jest": "^25.2.3",
    "@types/react": "^16.9.35",
    "@types/react-native": "^0.62.12",
    "@types/react-test-renderer": "^16.9.1",
    "@types/styled-components": "^4.1.19",
    "@typescript-eslint/eslint-plugin": "^2.14.0",
    "@typescript-eslint/parser": "^2.0.0",
    "babel-jest": "^25.1.0",
    "detox": "^16.0.1",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.9.0",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.17.0",
    "jest": "^26.0.1",
    "jest-junit": "^10.0.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "prettier": "^1.19.1",
    "react-test-renderer": "16.13.1",
    "ts-jest": "^26.1.0",
    "typescript": "^3.7.4"
  },
}
```

**Environment**

```

```
- Babel version(s): 7.8.4
- Node/npm version: v12.0.0
- OS: OSX 10.13.4
- Monorepo: no
- How you are using Babel: cli

**Additional context**
I tried breaking it down to just 
```js
import React from 'react';
import { View } from 'react-native';

const Index: FC<NavigationProps> = ({ navigation }) => {
  return <View />;
};
export default Index;
``` 
and that still failed

**Comment by alexwasner** [comment]
Opened a ticket with [@testing-library](https://github.com/testing-library/native-testing-library/issues/126)
