### ISSUE TITLE
Colons in config causes Hugo/Babel build to fail

### ISSUE THREAD

**Issue by inwardmovement** [babel/babel#11717]
## Bug Report
**Current behavior**
I have to remove the `:` to make the Hugo/Babel build work.

```
babel.config.js:2
  "presets": [
           ^
SyntaxError: Unexpected token ':'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)  
    at loadCjsDefault (C:\Users\arkay\Documents\1_repos\algo-website\node_modules\@babel\core\lib\config\files\module-types.js:77:18)
    at loadCjsOrMjsDefault (C:\Users\arkay\Documents\1_repos\algo-website\node_modules\@babel\core\lib\config\files\module-types.js:49:16)
    at loadCjsOrMjsDefault.next (<anonymous>)
    at readConfigJS (C:\Users\arkay\Documents\1_repos\algo-website\node_modules\@babel\core\lib\config\files\configuration.js:192:47)
Built in 1997 ms
Error: Error building site: BABEL: failed to transform "scripts/misc.js" (application/javascript): exit status 
```

**Expected behavior**
Just copy/paste config examples from the docs and it works.

**Babel Configuration**
`babel.config.js`
```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": "> 0.25%, not dead"
      }
    ]
  ]
}
```

**Environment**
```
System:
    OS: Windows 10 10.0.18363
Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE    
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD       
npmPackages:
    @babel/cli: ^7.10.1 => 7.10.1
    @babel/core: ^7.10.2 => 7.10.2
    @babel/preset-env: ^7.10.2 => 7.10.2
```

- How you are using Babel: within [Hugo](https://gohugo.io/hugo-pipes/babel/)

**Comment by nicolo-ribaudo** [comment]
That is a JSON file, not a JavaScript file. Please rename it to `babel.config.json`!
