### ISSUE TITLE
Syntax Error "Missing class properties transform" after update to 7.10.4

### ISSUE THREAD

**Issue by alesak** [babel/babel#11775]
**Current behavior**
After recent update to version 7.10.4 babel complains with Syntax Error at **justTest = () => {** line in perfectly valid TSX file. 

```
[01:47:24] Starting 'build'...
[01:47:25] 'build' errored after 435 ms
[01:47:25] SyntaxError: {path}babel-bug/src/App.tsx: Missing class properties transform.
  10 |     }
  11 |     
> 12 |     justTest = () => {
     |     ^
  13 |         
  14 |     }
  15 |      while parsing file: {path}babel-bug/src/App.tsx
    at File.buildCodeFrameError ({path}babel-bug/node_modules/@babel/core/lib/transformation/file/file.js:248:12)
    at NodePath.buildCodeFrameError ({path}babel-bug/node_modules/@babel/traverse/lib/path/index.js:144:21)
    at pushBody ({path}babel-bug/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:161:20)
    at buildBody ({path}babel-bug/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:135:5)
    at classTransformer ({path}babel-bug/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:544:5)
    at transformClass ({path}babel-bug/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:580:10)
    at PluginPass.ClassExpression ({path}babel-bug/node_modules/@babel/plugin-transform-classes/lib/index.js:63:54)
    at newFn ({path}babel-bug/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call ({path}babel-bug/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call ({path}babel-bug/node_modules/@babel/traverse/lib/path/context.js:42:17)
```

**Input Code**

App.tsx

```ts
import * as React from 'react';
import {render as r} from 'react-dom';



class Test extends React.Component<{}> {
    constructor(props: {}) {
        super(props);
    }
    
    justTest = () => {
        
    }
    
    render() {
        return <div>test</div>
    }
}

r(<Test />, document.getElementById('app'));
```

**Expected behavior**
Clean compilation as before update. (version 7.10.1 at least was fine)

gulpfile.js
```js
var gulp = require('gulp');
var source = require('vinyl-source-stream');
var browserify = require('browserify');
var babelify = require('babelify');
var streamify = require('gulp-streamify');

function getJsonFile(path) {
    return JSON.parse(fs.readFileSync(path));
}


gulp.task('build', function () {
    var options = {
        extensions: [".tsx", ".ts", ".js", ".jsx"],
        ignoreMissing: true,
        paths: ["./src"],
        entries: ['./src/App.tsx'], // Entry point
        debug: false // add resource map at the end of the file or not
    };
    return browserify(options)
            .transform(babelify, {
                extensions: [".tsx", ".ts", ".js", ".jsx"],
                presets: [
                    ["@babel/preset-typescript", {allowNamespaces: true}],
                    "@babel/preset-react",
                    ["@babel/preset-env", {targets: "> 1% in AU and not dead"}]],
                sourceType: "module"})
            .exclude(['react', 'react-dom'])
            .bundle()
            .pipe(source('app.js'))
            .pipe(gulp.dest('./public'));
});
```
package.json
```json
{
    "name": "babel-bug",
    "version": "1.0.0",
    "keywords": [
        "util",
        "functional",
        "server",
        "client",
        "browser"
    ],
    "author": "",
    "contributors": [],
    "devDependencies": {
        "@babel/core": "7.10.4",
        "@babel/plugin-transform-typescript": "7.10.4",
        "@babel/preset-env": "7.10.4",
        "@babel/preset-react": "7.10.4",
        "@babel/preset-typescript": "7.10.4",
        "@types/node": "^14.0.14",
        "@types/react": "^16.9.41",
        "@types/react-dom": "^16.9.8",
        "gulp": "*",
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
        "typescript": "^3.9.5",
        "vinyl-source-stream": "^2.0.0",
        "babelify": "*",
        "gulp-streamify": "^1.0.2",
        "browserify": "^16.5.1"
    }
}
```
tcconfig.json
```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "jsx": "react",
        "esModuleInterop": true,
        "alwaysStrict": true,
        "module": "commonjs",
        "target": "es5",
        "declaration": true,
        "outDir": "./dist",
        "noImplicitAny": true,
        "removeComments": false,
        "preserveConstEnums": true,
        "sourceMap": true,
        "strictNullChecks": true
        },
    "include": [
      "src/**/*"
    ]
}
```

**Environment**

```
System:
    OS: Linux 5.6 openSUSE Tumbleweed 20200612
  Binaries:
    Node: 14.4.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  npmPackages:
    @babel/core: 7.10.4 => 7.10.4 
    @babel/plugin-transform-typescript: 7.10.4 => 7.10.4 
    @babel/preset-env: 7.10.4 => 7.10.4 
    @babel/preset-react: 7.10.4 => 7.10.4 
    @babel/preset-typescript: 7.10.4 => 7.10.4 
    babelify: * => 10.0.0 
```

**Comment by JLHwung** [comment]
class properties are still a stage-3 proposal so it is not enabled in `preset-env` by default. You can enable them via `shippedProposals: true` ([docs](https://babel.dev/docs/en/babel-preset-env#shippedproposals))

```
["@babel/preset-env", {targets: "> 1% in AU and not dead", shippedProposals: true }]]
```

**Comment by alesak** [comment]
Thanks for quick response, it compiles fine now. The error message could be probably better and point to the docs.
