### ISSUE TITLE
Inconsistency in "Duplicate declaration"

### ISSUE THREAD

**Issue by ramitos** [babel/babel#1177]
Source:
```
js
let [a, b] = [1, 2];
console.log(a, b);
let [a, b] = [3, 4];
console.log(a, b);
```

using Babel: 
```
TypeError: /Users/ramitos/dev/ycatch/test/test.js: Line 3: Duplicate declaration "a"
  1 | let [a, b] = [1, 2];
  2 | console.log(a, b);
> 3 | let [a, b] = [3, 4];
    |      ^
  4 | console.log(a, b);
    at File.errorWithNode (node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:439:15)
    at Scope.checkBlockScopedCollisions (node_modules/babel/node_modules/babel-core/lib/babel/traversal/scope.js:292:23)
    at Scope.registerBinding (node_modules/babel/node_modules/babel-core/lib/babel/traversal/scope.js:429:12)
    at Scope.registerDeclaration (node_modules/babel/node_modules/babel-core/lib/babel/traversal/scope.js:389:14)
    at TraversalPath.enter (node_modules/babel/node_modules/babel-core/lib/babel/traversal/scope.js:79:13)
    at TraversalPath.call (node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/index.js:443:26)
    at TraversalPath.visit (node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/index.js:455:10)
    at TraversalContext.visitMultiple (node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:50:16)
    at TraversalContext.visit (node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:71:19)
    at Function.traverse.node (node_modules/babel/node_modules/babel-core/lib/babel/traversal/index.js:44:17)
```

using Firefox:
![](http://f.cl.ly/items/2S1x0v2j2N1Q3j3N0m3b/Image%202015-04-07%20at%202.55.03%20AM.png)

**Comment by monsanto** [comment]
Firefox's behavior is incorrect. You cannot redeclare a block scoped variable in the same scope it was defined.

**Comment by loganfsmyth** [comment]
@ramitos Just so it's clear, the issue is that you have essentially done `let a;` twice, which is not allowed. You can simply leave off the second `let`

```
let [a, b] = [1, 2];
console.log(a, b);
[a, b] = [3, 4];
console.log(a, b);
```

since the first `let [a, b]` defines `a`.

**Comment by ramitos** [comment]
Thank you the replies.

I thought about trying the firefox REPL in another way that makes more sense:
![](http://f.cl.ly/items/0w140i1d1K3X0T040K0x/Image%202015-04-07%20at%203.52.49%20AM.png)

@loganfsmyth right. I just found odd that babel and ff had different behaviors (although they don't, I was wrong)
