### ISSUE TITLE
Issue with lint and curly strings introduced in @babel/core 7.10.5

### ISSUE THREAD

**Issue by jakeleventhal** [babel/babel#11844]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
A clear and concise description of the behavior.

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

**Input Code**

When I use eslint 7.4.0 and @babel/core 7.10.4, everything works. When upgrading to 7.10.5, I get the following error:
```
Oops! Something went wrong! :(

ESLint: 7.4.0

TypeError: Cannot read property 'value' of null
Occurred while linting /Users/jakeleventhal/ecominate/packages/landing/src/view/Components/LandingButton.jsx:34
    at checkSpacingBefore (/Users/jakeleventhal/ecominate/node_modules/eslint/lib/rules/template-curly-spacing.js:52:24)
    at TemplateElement (/Users/jakeleventhal/ecominate/node_modules/eslint/lib/rules/template-curly-spacing.js:136:17)
    at /Users/jakeleventhal/ecominate/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/jakeleventhal/ecominate/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/jakeleventhal/ecominate/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/jakeleventhal/ecominate/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/jakeleventhal/ecominate/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/jakeleventhal/ecominate/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:635:23)
    at /Users/jakeleventhal/ecominate/node_modules/eslint/lib/linter/linter.js:949:32
```

The line in question is this
```react
<Link className={classes.link} to={`/${href}`}>
```
If I comment out that code, it fails with the same error on the next line with a format string (using the curly braces).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Here is my eslintrc
```json
{
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": [
    "airbnb",
    "plugin:react/all"
  ],
  "parser": "babel-eslint",
  "plugins": [
    "react",
    "simple-import-sort"
  ],
  "rules": {
    "arrow-parens": [
      "error",
      "always"
    ],
    "camelcase": "error",
    "comma-dangle": [
      "error",
      "never"
    ],
    "curly": [
      "error",
      "all"
    ],
    "func-names": "error",
    "indent": [
      "error",
      2,
      {
        "SwitchCase": 1
      }
    ],
    "jsx-a11y/click-events-have-key-events": "off",
    "max-len": [
      "error",
      {
        "code": 120,
        "ignoreUrls": true,
        "tabWidth": 2
      }
    ],
    "no-console": "error",
    "no-plusplus": "off",
    "no-underscore-dangle": "off",
    "no-unused-vars": "error",
    "react/destructuring-assignment": "off",
    "react/function-component-definition": "off",
    "react/jsx-handler-names": "off",
    "react/jsx-indent": [
      "error",
      2
    ],
    "react/jsx-indent-props": [
      "error",
      2
    ],
    "react/jsx-max-depth": "off",
    "react/jsx-no-literals": "off",
    "react/jsx-one-expression-per-line": "off",
    "react/jsx-props-no-spreading": "off",
    "react/no-set-state": "off",
    "react/prop-types": "off",
    "simple-import-sort/sort": "error",
    "sort-keys": [
      "error",
      "asc",
      {
        "caseSensitive": false,
        "natural": true
      }
    ],
    "sort-vars": "error"
  }
}
```
And my babel config in my package.json
```json
  "babel": {
    "plugins": [
      "@babel/plugin-proposal-class-properties"
    ],
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ]
  }
```

**Environment**

```
  System:
    OS: macOS 10.16
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
```

**Comment by JLHwung** [comment]
I can not reproduce this issue on a fresh installed repo: https://github.com/JLHwung/babel-test-repo-11844

Can you draft an reproducing repo based on that?

**Comment by jakeleventhal** [comment]
for whatever reason, this works on 7.11.0

**Comment by geopamplona** [comment]
I have same error. Will try your code @JLHwung .
