### ISSUE TITLE
@babel/helper-validator-identifier can’t be required

### ISSUE THREAD

**Issue by proteriax** [babel/babel#11878]
## Bug Report

Fix is available below.

- [x] I would like to work on a fix!

**Current behavior**
```sh
mkdir test && cd test
yarn init --yes
yarn add @babel/helper-validator-identifier
node

Welcome to Node.js v14.6.0.
Type ".help" for more information.
> require('@babel/helper-validator-identifier')
Uncaught:
TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "/test/node_modules/@babel/helper-validator-identifier/lib/index.js" must not include encoded "/" or "\" characters imported from /test/node_modules/@babel/helper-validator-identifier/
    at resolveExportsTarget (internal/modules/cjs/loader.js:564:15)
    at applyExports (internal/modules/cjs/loader.js:469:14)
    at resolveExports (internal/modules/cjs/loader.js:522:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1052:27)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at repl:1:1
    at Script.runInThisContext (vm.js:132:18) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}
```

**Expected behavior**
It works.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
N/A

**Environment**
- Babel version(s): 7.10.4
- Node/npm version: v14.6.0
- OS: macOS Catalina
- Monorepo: no
- How you are using Babel: Node.js

**~~Possible~~ Solution**

Remove `exports` field from `package.json` and it will work.

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

=== Edits by @JLHwung ===
**Solution**
Update node to `v14.7.0`.

**Comment by JLHwung** [comment]
I believe it is a bug of node REPL, because the following example does not throw
```
node -e "require('@babel/helper-validator-identifier')"
```
