### ISSUE TITLE
mocha can't seem to find mocha.opts in `make test`

### ISSUE THREAD

**Issue by amasad** [babel/babel#1196]
On a fresh clone and following the steps in the [contributing guide](https://github.com/babel/babel/blob/master/CONTRIBUTING.md), running the tests using `make test` will result in:

```
node test/acorn/run.js
Normal parser: 1120 tests run in 316ms; all passed.
Total: 1120 tests run in 316ms; all passed.
node node_modules/mocha/bin/_mocha test/core
/Users/amasad/code/babel/test/core/api.js:6
suite("api", function () {
^
ReferenceError: suite is not defined
    at Object.<anonymous> (/Users/amasad/code/babel/test/core/api.js:6:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/amasad/code/babel/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/amasad/code/babel/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/Users/amasad/code/babel/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/Users/amasad/code/babel/node_modules/mocha/bin/_mocha:393:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
make: *** [test] Error 1
```

However, when running via `node node_modules/mocha/bin/_mocha --ui tdd test/core/` will work.

**Comment by sebmck** [comment]
Looks like mocha pushed out a faulty release.

**Comment by sebmck** [comment]
Looks like fixing the version fixes this, I've followed up on the `mocha` repo as it looks to be a regression.
