### ISSUE TITLE
babel-node does not use `ignore` and `only` options from the configuration file

### ISSUE THREAD

**Issue by Edmond-XavierCollot** [babel/babel#12038]
## Bug Report

**Current behavior**
When using `babel-node` without providing `ignore` and `only` options,  the values for this options are defaulted instead of using the ones specified in the config file.

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

**Input Code**

My `babel.config.json`:

```json
{
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-proposal-private-methods",
    "@babel/plugin-proposal-class-properties",
    [
      "babel-plugin-module-resolver",
      {
        "alias": {
          "@db": "./src/db",
          "@utils": "./src/utils",
          "@s3": "./src/s3",
          "@models": "./src/models",
          "@console": "./src/console"
        }
      }
    ]
  ],
  "only": ["./src", "./node_modules/my-library"]
}
```

When running the following
```shell
babel-node src/index.js
```

I get an error because my `/node_modules/my-library` has not been compiled
```
$ babel-node src/index.js
/Users/ddx/Projects/Cosmic/services/Medias/node_modules/my-libraryl/index.js:1
import Model from "./model";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Module._compile (/Users/ddx/Projects/Cosmic/services/Medias/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .js] (/Users/ddx/Projects/Cosmic/services/Medias/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/ddx/Projects/Cosmic/services/Medias/src/models/image.js:1:1)
```

**Expected behavior**
I'd expect that the `ignore` and `only` options should be taken from the `babel.config.js` when no values for this options has been provided to `babel-node`

**Environment**
```
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  npmPackages:
    @babel/cli: ^7.11.5 => 7.11.5 
    @babel/core: ^7.11.5 => 7.11.5 
    @babel/node: ^7.10.5 => 7.10.5 
    @babel/plugin-proposal-class-properties: ^7.10.4 => 7.10.4 
    @babel/plugin-proposal-private-methods: ^7.10.4 => 7.10.4 
    @babel/preset-env: ^7.11.5 => 7.11.5 
    babel-plugin-module-resolver: ^4.0.0 => 4.0.0 
```

**Possible Solution**
As it has only been mentionned in #11892 the issue comes from this line 
https://github.com/babel/babel/blob/main/packages/babel-register/src/node.js#L140

The problem is that the default options for `only` and `ignore` setted here, are overriding the config file.
When commenting this lines, the config file is taken into account as expected.
I am not familiar with the codebase so I don't know where this default values should be set.
But I am pretty sure they are currently set at the wrong moment.

**Comment by JLHwung** [comment]
The behaviour is expected, because by default `@babel/node` will pass `node_modules` as `ignore` and `process.cwd()` as `only` if none of them are not specified. When Babel merges options, programmatic options have higher priority than config files (`.babelrc` and `babel.config.json`).

As a workaround, please move `only` and `ignore` to `@babel/node`'s command line arguments. This may not be desired but removing those defaults certainly break users who does not use `only` in their configs because now `node_modules` are always transpiled.

Note that `@babel/node` is not for production use because of high memory usage. Consider switch to `@babel/cli` or other bundlers if you want to transpile some of node_modules.
