### ISSUE TITLE
Use # prefix on private class field with eslint-plugin-flowtype cause "Cannot read property 'type' of undefined"

### ISSUE THREAD

**Issue by tkbremnes** [babel/babel#12105]
## Bug Report

Clone of https://github.com/babel/babel-eslint/issues/688

As reported by @SebastienGllmt:

> This exact issue still persists for me even if I crank all eslint & bable dependencies to their latest version. What's more, this doesn't always fail. For example in my case
> 
> This fails
> ```javascript
>   #publicDeriverId: number;
>   #bip44Wallet: IBip44Wallet;
>   #derivationId: number;
>   #pathToPublic: Array<number>; // only this specific private field causes an error.
> ```
> 
> This passes
> ```javascript
>   #publicDeriverId: number;
>   #bip44Wallet: IBip44Wallet;
>   #derivationId: number;
>   #pathToPublic: string; // note: this changed
> ```
> 
> Adding this totally unrelated type makes it work
> ```javascript
> type TotallyUnrelatedType = Array<number>;
> export class Foo {
>   #publicDeriverId: number;
>   #bip44Wallet: IBip44Wallet;
>   #derivationId: number;
>   #pathToPublic: Array<number>;
> }
> ```

_Originally posted by @SebastienGllmt in https://github.com/babel/babel-eslint/issues/688#issuecomment-531608020_

**Comment by kaicataldo** [comment]
Hey, sorry for the delay here. Do you mind sharing the versions of all `@babel/core`, `eslint`, `@babel/eslint-parser`, and `eslint-plugin-flowtype` you're using as well as the actual output from ESLint for the various examples? It'll make it easier to understand what is going on.

**Comment by tkbremnes** [comment]
```
"@babel/core": "7.11.1",
"eslint": "7.9.0",
"@babel/eslint-parser": "7.12.1",
"eslint-plugin-flowtype": "5.2.0",
```

The error below is produced as I'm setting a react reference `#refUrlInput = Reference<AutocompleteInput> = React.createRef();` in the root of a class object.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/tk/.nvm/versions/node/v12.13.0/bin/node',
1 verbose cli   '/Users/tk/.nvm/versions/node/v12.13.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle gapp-browser-react@1.0.0~prelint: gapp-browser-react@1.0.0
6 info lifecycle gapp-browser-react@1.0.0~lint: gapp-browser-react@1.0.0
7 verbose lifecycle gapp-browser-react@1.0.0~lint: unsafe-perm in lifecycle true
8 verbose lifecycle gapp-browser-react@1.0.0~lint: PATH: /Users/tk/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Volumes/Dev/vivaldi/vivaldi.js/vivapp/node_modules/.bin:/Users/tk/.nvm/versions/node/v12.13.0/bin:/Users/tk/.nodenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle gapp-browser-react@1.0.0~lint: CWD: /Volumes/Dev/vivaldi/vivaldi.js/vivapp
10 silly lifecycle gapp-browser-react@1.0.0~lint: Args: [ '-c', 'node node_modules/eslint/bin/eslint.js --ext js,jsx src/' ]
11 silly lifecycle gapp-browser-react@1.0.0~lint: Returned: code: 2  signal: null
12 info lifecycle gapp-browser-react@1.0.0~lint: Failed to exec lint script
13 verbose stack Error: gapp-browser-react@1.0.0 lint: `node node_modules/eslint/bin/eslint.js --ext js,jsx src/`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/tk/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/Users/tk/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid gapp-browser-react@1.0.0
15 verbose cwd /Volumes/Dev/vivaldi/vivaldi.js/vivapp
16 verbose Darwin 17.7.0
17 verbose argv "/Users/tk/.nvm/versions/node/v12.13.0/bin/node" "/Users/tk/.nvm/versions/node/v12.13.0/bin/npm" "run" "lint"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 2
22 error gapp-browser-react@1.0.0 lint: `node node_modules/eslint/bin/eslint.js --ext js,jsx src/`
22 error Exit status 2
23 error Failed at the gapp-browser-react@1.0.0 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

A smaller test-case for this is:
```
// @flow

import React from "react";

export class TestCase extends React.PureComponent<Props, State> {
  #someArray: Array<number>;

  render() {
    return null;
  }
}
```

This produces:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/tk/.nvm/versions/node/v12.13.0/bin/node',
1 verbose cli   '/Users/tk/.nvm/versions/node/v12.13.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle gapp-browser-react@1.0.0~prelint: gapp-browser-react@1.0.0
6 info lifecycle gapp-browser-react@1.0.0~lint: gapp-browser-react@1.0.0
7 verbose lifecycle gapp-browser-react@1.0.0~lint: unsafe-perm in lifecycle true
8 verbose lifecycle gapp-browser-react@1.0.0~lint: PATH: /Users/tk/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Volumes/Dev/vivaldi/vivaldi.js/vivapp/node_modules/.bin:/Users/tk/.nvm/versions/node/v12.13.0/bin:/Users/tk/.nodenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle gapp-browser-react@1.0.0~lint: CWD: /Volumes/Dev/vivaldi/vivaldi.js/vivapp
10 silly lifecycle gapp-browser-react@1.0.0~lint: Args: [ '-c', 'node node_modules/eslint/bin/eslint.js --ext js,jsx src/' ]
11 silly lifecycle gapp-browser-react@1.0.0~lint: Returned: code: 2  signal: null
12 info lifecycle gapp-browser-react@1.0.0~lint: Failed to exec lint script
13 verbose stack Error: gapp-browser-react@1.0.0 lint: `node node_modules/eslint/bin/eslint.js --ext js,jsx src/`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/tk/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/Users/tk/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid gapp-browser-react@1.0.0
15 verbose cwd /Volumes/Dev/vivaldi/vivaldi.js/vivapp
16 verbose Darwin 17.7.0
17 verbose argv "/Users/tk/.nvm/versions/node/v12.13.0/bin/node" "/Users/tk/.nvm/versions/node/v12.13.0/bin/npm" "run" "lint"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 2
22 error gapp-browser-react@1.0.0 lint: `node node_modules/eslint/bin/eslint.js --ext js,jsx src/`
22 error Exit status 2
23 error Failed at the gapp-browser-react@1.0.0 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by tkbremnes** [comment]
```

**Comment by tkbremnes** [comment]
```
"@babel/core": "7.13.10",
"@babel/eslint-parser": "7.13.10",
"eslint": "7.22.0",
"eslint-plugin-flowtype": "5.4.0",
```

Still produces the same issue. Am I missing something?

**Comment by nicolo-ribaudo** [comment]
Whops sorry, we had to revert the fix because it caused too much breakage.

**Comment by JLHwung** [comment]
We can not enable the class features by default since it is a breaking change to ecosystem (but it is inevitable since Babel AST differs to ESTree). If you want to try on this feature

```js
module.exports = {
  parser: "@babel/eslint-parser",
  babelOptions: {
    parserOpts: {
      plugins: [
        ["estree", { classFeatures: true }],
        "classPrivateProperties",
        "classProperties",
      ],
    },
  },
};
```
