### ISSUE TITLE
Seems like is looking for a weird path?

### ISSUE THREAD

**Issue by tedchou12** [babel/babel#12132]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
A clear and concise description of the behavior.

```
server_13 % npx babel src -d dst                      
Error: Cannot find module 'babel-preset-preset-stage-3' from '/Applications/MAMP/htdocs/prosemirror_server/server_13'
- Did you mean "@babel/preset-stage-3"?
    at Function.resolveSync [as sync] (/Applications/MAMP/htdocs/prosemirror_server/server_13/node_modules/resolve/lib/sync.js:89:15)
    at resolveStandardizedName (/Applications/MAMP/htdocs/prosemirror_server/server_13/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/Applications/MAMP/htdocs/prosemirror_server/server_13/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/Applications/MAMP/htdocs/prosemirror_server/server_13/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/Applications/MAMP/htdocs/prosemirror_server/server_13/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /Applications/MAMP/htdocs/prosemirror_server/server_13/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Applications/MAMP/htdocs/prosemirror_server/server_13/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Applications/MAMP/htdocs/prosemirror_server/server_13/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Applications/MAMP/htdocs/prosemirror_server/server_13/node_modules/@babel/core/lib/config/config-descriptors.js:47:19) {
  code: 'MODULE_NOT_FOUND'
}

```

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

**Input Code**

```js
var your => (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "name": "prosemirror_server",
  "version": "0.0.1",
  "description": "Rich text editor built with React and ProseMirror",
  "main": "main.js",
  "bin": "main.js",
  "scripts": {
    "start": "npm start"
  },
  "devDependencies": {
    "@babel/cli": "^7.10.4",
    "@babel/core": "^7.11.6",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/plugin-proposal-decorators": "^7.10.4",
    "@babel/plugin-proposal-do-expressions": "^7.10.4",
    "@babel/plugin-proposal-export-default-from": "^7.10.4",
    "@babel/plugin-proposal-export-namespace-from": "^7.10.4",
    "@babel/plugin-proposal-function-sent": "^7.10.4",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.10.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.10.4",
    "@babel/plugin-proposal-pipeline-operator": "^7.10.4",
    "@babel/plugin-proposal-throw-expressions": "^7.10.4",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-syntax-import-meta": "^7.10.4",
    "@babel/plugin-transform-flow-strip-types": "^7.10.4",
    "@babel/plugin-transform-parameters": "^7.10.4",
    "@babel/plugin-transform-runtime": "^7.10.4",
    "@babel/preset-env": "^7.10.4",
    "@babel/preset-flow": "^7.10.4",
    "@babel/preset-react": "^7.10.4",
    "@babel/preset-stage-3": "^7.8.3",
    "babel-preset-preset-stage-3": "^7.8.3",
    "babel-eslint": "10.1.0",
    "babel-loader": "^8.0.0-beta.6",
    "babel-plugin-flow-react-proptypes": "26.0.0",
    "babel-plugin-transform-es2015-modules-umd": "^6.24.1",
    "babel-plugin-transform-react-remove-prop-types": "0.4.24",
    "babel-preset-es2015": "^6.24.1",
    "clean-webpack-plugin": "3.0.0",
    "copy-webpack-plugin": "6.0.3",
    "css-loader": "3.6.0",
    "eslint": "7.4.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "7.20.3",
    "file-loader": "^6.1.0",
    "flow-bin": "0.128.0",
    "flow-copy-source": "2.0.9",
    "flow-webpack-plugin": "1.2.0",
    "html-loader": "1.1.0",
    "html-webpack-inline-source-plugin": "1.0.0-beta.2",
    "html-webpack-plugin": "^4.3.0",
    "husky": "^4.2.5",
    "jest": "^26.4.2",
    "lint-staged": "^10.2.11",
    "mkdirp": "^1.0.4",
    "prettier": "^2.0.5",
    "stylelint": "^13.6.1",
    "terser-webpack-plugin": "^3.0.6",
    "webpack": "^4.44.2",
    "webpack-dev-server": "^3.11.0",
    "write-file-webpack-plugin": "4.5.1"
  },
  "dependencies": {
    "babel-jest": "^26.3.0",
    "browserkeymap": "2.0.2",
    "classnames": "2.2.6",
    "color": "3.1.2",
    "cors": "^2.8.5",
    "exports-loader": "1.1.0",
    "express": "^4.17.1",
    "flatted": "^3.0.4",
    "flow-typed": "^3.2.0",
    "formidable": "^1.2.2",
    "fs": "0.0.2",
    "invariant": "2.2.4",
    "jquery": "^3.5.1",
    "katex": "0.11.1",
    "mv": "^2.1.1",
    "node-mathquill": "0.10.2",
    "nullthrows": "1.1.1",
    "prosemirror-collab": "1.2.2",
    "prosemirror-commands": "1.1.4",
    "prosemirror-dev-tools": "3.0.2",
    "prosemirror-dropcursor": "1.3.2",
    "prosemirror-gapcursor": "1.1.5",
    "prosemirror-history": "1.1.3",
    "prosemirror-inputrules": "1.1.2",
    "prosemirror-keymap": "^1.1.4",
    "prosemirror-model": "^1.11.0",
    "prosemirror-schema-basic": "^1.1.2",
    "prosemirror-schema-list": "^1.1.4",
    "prosemirror-schema-table": "^0.22.0",
    "prosemirror-state": "^1.3.3",
    "prosemirror-tables": "github:ProseMirror/prosemirror-tables",
    "prosemirror-transform": "^1.2.7",
    "prosemirror-utils": "0.9.6",
    "prosemirror-view": "^1.15.2",
    "query-string": "6.13.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "regenerator-runtime": "^0.13.7",
    "resize-observer-polyfill": "1.5.1",
    "smooth-scroll-into-view-if-needed": "1.1.28",
    "stable": "0.1.8",
    "style-loader": "^1.2.1",
    "uuid": "8.2.0",
    "webfontloader": "1.6.28"
  },
  "jest": {
    "transform": {
      "^.+\\.jsx$": "babel-jest",
      "^.+\\.js$": "babel-jest"
    }
  }
}

```

I tried to look for this: `babel-preset-preset-stage-3`, but is nowhere in the package, I wonder why is looking for `babel-preset-preset-stage-3`?

**Environment**

```

```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34] 
server_13 % npx babel --version
7.11.6 (@babel/core 7.11.6)
- Node/npm version: [e.g. Node 8/npm 5]
server_13 % node --version
v14.11.0
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]
cli

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by tedchou12** [comment]
I found out, 
if you put 
`preset-stage-3`
```
"presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": true
        }
      }
    ],
    "@babel/preset-react",
    "@babel/preset-flow",
    "preset-stage-3",

  ],
```

It will automatically prepend `babel-preset` to your package and try to look for it, as of babel 7, you should use:
`@babel/preset-stage-3` instead.

Babel is nice, but I think much of the error handling and moving of directories when upgrading are a bit meaningless. The whole point is compatibility, if it cannot sort its own dependencies out, what are we here for?

**Comment by nicolo-ribaudo** [comment]
One reason for renaming `babel-*` to `@babel/*` was to disambiguate between community packages and official packages. Another one was to avoid people from using package names that we could need in the future.

Anyway, glad you sorted it out!
