### ISSUE TITLE
crash with simple for loop at top level with `system` module formatter

### ISSUE THREAD

**Issue by lygaret** [babel/babel#1217]
With this file `foo.js` (listed in it's entirety):

```javascript
for (let a = 0; a < 10; a++) {
}
```

I get the following output

```
## babel -V
5.0.12
## babel -m amd foo.js
define(["exports"], function (exports) {
  "use strict";

  for (var a = 0; a < 10; a++) {}
});

## babel -m system foo.js
/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
Error: foo.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at TraversalPath.insertAfter (/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/traversal/path/index.js:184:15)
    at TraversalPath.replaceWithMultiple (/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/traversal/path/index.js:322:10)
    at TraversalPath.replaceWith (/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/traversal/path/index.js:337:21)
    at TraversalPath.call (/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/traversal/path/index.js:444:27)
    at TraversalPath.visit (/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/traversal/path/index.js:455:10)
    at TraversalContext.visitSingle (/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/traversal/context.js:63:41)
    at TraversalContext.visit (/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/traversal/context.js:73:19)
    at Function.traverse.node (/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/traversal/index.js:44:17)
    at TraversalPath.visit (/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/traversal/path/index.js:472:18)
    at TraversalContext.visitMultiple (/home/jonathan/code/babel/packages/babel-cli/node_modules/babel-core/lib/babel/traversal/context.js:50:16)
```

I tried to do a bisect, but after spending 3 hours having to skip commits because things didn't built I gave up, sorry :/

I ran into this upgrading from 4 something to 5.0.12 today, and have been banging my head on it; a workaround is putting the offending for statement into some nested scope, like an IIFE.

**Comment by sebmck** [comment]
Sorry for the delay. Fixed as of 5.1.0, thanks!

**Comment by lygaret** [comment]
Thanks for the quick turnaround!

**Comment by eguneys** [comment]
I got this error with a `for(let name of something)` babel 5.3.3
