### ISSUE TITLE
this.optionalCall is not a function

### ISSUE THREAD

**Issue by alexkreidler** [babel/babel#12229]
```
ERROR in /home/alex/loqu/node_modules/@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysTarget.js
Module build failed (from /home/alex/loqu/node_modules/babel-loader/lib/index.js):
TypeError: /home/alex/loqu/node_modules/@blueprintjs/core/lib/esnext/components/hotkeys/hotkeysTarget.js: this.optionalCall is not a function
    at Object.handle (/home/alex/loqu/node_modules/@babel/helper-member-expression-to-functions/lib/index.js:317:35)
    at Object.Super (/home/alex/loqu/node_modules/@babel/helper-replace-supers/lib/index.js:69:11)
    at NodePath._call (/home/alex/loqu/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/alex/loqu/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/alex/loqu/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/home/alex/loqu/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitSingle (/home/alex/loqu/node_modules/@babel/traverse/lib/context.js:88:19)
    at TraversalContext.visit (/home/alex/loqu/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/alex/loqu/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/home/alex/loqu/node_modules/@babel/traverse/lib/path/context.js:99:18)
    at TraversalContext.visitQueue (/home/alex/loqu/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitSingle (/home/alex/loqu/node_modules/@babel/traverse/lib/context.js:88:19)
    at TraversalContext.visit (/home/alex/loqu/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/alex/loqu/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/home/alex/loqu/node_modules/@babel/traverse/lib/path/context.js:99:18)
    at TraversalContext.visitQueue (/home/alex/loqu/node_modules/@babel/traverse/lib/context.js:116:16)
```

The offending line appears to be:

https://github.com/babel/babel/blob/ddb7e05f07599e46d4d1605c3ae344ca0c44d7a5/packages/babel-helper-member-expression-to-functions/src/index.js#L385

The simplest way to reproduce is use this [Babel REPL link](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=PQKgUABCEMIPYAcCeAnAlgcwBYBcICYAGARgDYIAFAQwBsqA7HNFCAFQFMBjLeuGuDGnYBnADQQAkvU4A6CAEEaNCOmw5hKkexQA3dgBMZkcFAgAZNJ3b1hBiAFd6-7RBxZ2ChFW4eLVm-ziAGrawmhw9AQyhBAAFG4eAER-1raJAJQA3MYQSHD2EAC2VEgQvHj2tq5YaBoAZmg0HuwAHlYIeGiRnHCFCDRoDFYQAO5obtW-lqnsRqYAmvlFJRBwAEY4VF0QVBA9yKt1k-bTATs4xjkQ1xC4OAgAXMDAI68yVF4-MnAoGMAD_lswmAZgkMAAogA5ADK4IAtPhopdTABVehNYQaFDsACO9mYdjWpQ-_UsVDWTQgdBGqxYVAw2LsODgEG2I3QTHoGHEwjgdRwIyo2Jy-lqOHQa3sODsjmcLASJ0BHlqEFFwnFaEl0v0q0iDAgiXk0Mk0MSEAAQkaJNDRDkAOoSVgACQA8ijWBA7fIAEre-SQ1gScHGl3e2AuyEAEUdEgjIYAYgpIfMIABpCRR8TscbuFitBDYzG01l9AYGObQaHsDwKlJnOo_Y7CBBcNANThUhgYez0jwYOB6FD0LoYCAtlCFWphCIaBj6HIDSebJgzhxOFy1062CvAMBoPo_PDQKgab3sbx4OooXoG7EXxLZfcIQ8QADeEFdrFT4Pm0IA-l63qQn-kbgjAobyKwoZ_pC4LgpG_7euC8gwKwf7gmY4IALJQqw4ift-v4AT6wGgeBfpQd6MEun-OHOi6kYQAAvhAV43okMgyMAnHAD0hSFBEwDaNeKDCA-e4HigeDvhg7A4JGtT9CUkJUIUgSssI8aOJwK6RCxbGFAaPE8XxAn0MAUqNGJj6SdJH5wDgADW7BINC-zqU6DnOUgwjgnojAaPp16GRxwBYF5Lm-f56jifmL51Npun2U5kWsEKsk4LEdooCSBjwAe9DWDg6RvpANw6EKEB_lQ2Q3KyRyxAAhLUWnSLpWU5QgLb6Plz6FYwMgFg5DlIC2MjYuuKCeSlPnpCVr5lXV1w9DYfCzIKQ6xARP7_oBpFgRBlHUbR4L0ZGWSLcxl3Yjg9hDlVuwALx7HQRbTd5whpb8ckwK9GitNKTgaNluU9b0fVFaVS3Q3sM7ivYOk_LE82XTDS3CPY46xJx7y_PYakBRdaNo6A0AAAJdNKQ60FAu7EzDbi1DIGD8GstDvZFflFRoz2FTSHM-VzAVbRFrnuTIADiZgupaZhE_TS2kxAFOMNo9A0yAdMK3VjPCDI_CcOzotRdzEC8-w_PG0L6gizNbmILM0swPIcu1QrTGozDfEQ4wCn6Fh-SMMjUPazcbZxBj44yN7ERFX7AeOHgjW8_YSgo6HMOR9o0fg7HvtoP7geZfLGcexn1zPOcmzcBALPrDT3kQOw0VUmK1ihJ79P6HAnD40V7z6Po1sWOq7coLEiTed3Iz0Ik4i68zrNGzNJsBTIWBzk0qYuZGcAzyXofd73BM4APQ_RSPgPaBP3mY3P1RM3XbM0ALq_qOvm_sNvSAoggB9o2XBWMd-o4DtI0GgaIBKJ2DgtcuEAs4oBzgVIqYClCQKLgAfhkMjN2Gcj59wGtiASehh5t0KuPSeLlp6z3njUPWT9l4fWtnrDeTgt47z3vQf-Ct8En3GuwYh7BSGj3ITfFyd9aGPyXi_K20UWGf2_r_bh9MF4MJkSvZh0cmhChwZ3YmC8DaMM5nIrR55x7KKWoA-mE05QwL0WjFa6om5NBPmbeBmNs42OvhYtG4dYjsBcZDR6Kc04hzgRXYAOwaCCh8poW690AAGASBFFQSayboJ4PCGyUC4FUapOTdlqDULkEA1hyRGNWSICT6CpxoGkucEAEmynYA0Qq-gEn2IVjdO6kRkkn1waHKxoc_GNTPBeGQtQgi0ALuCQJQc-lFTmmE8Jji1oyA2vQLaLovw7WIkBECB0KLQVgvBRCyFULoUwjhAMPiulyR6c4lJjABnayGdrPxLVErhE2QvLxU1jZLNgeE5acNbjGzcb86wcpX66OBdcPxBie5GMFnI9OcKdZ0P1ki9RTCTG2BwDC8KK9BrXgQMIW59M3nlwRZitRr9mFovRdcVR0j6V4rkoS42JLEDkpeeXKlGcaVM0MTi4x3Mc7QJKgAPggIQRlTLHF4E2GsKQzgWhuKJR9blZKZDKtVa0M2wS1zOFaXYDBsqIAPDBcSoaOq9XrhaHy4Fiq3y6m_rvGeVrWhihHO6zh4gIiKMeE3FoPquRBuYm4hZA1bXCCdSs0FrD9DsKQB6-gIMuouGev4kqj0ZVAqZUtRF2S2XiqTSmtN_iZDqyYCQ6KFLwnevVL6jhM8sE5vjXApinby4uvLV_Fyv8M3jjcTms2-bOnAuLcit-8i2EDp_ggKtNa0B1sWT24FTaClBvbewBtryN2h26fdMZOktGx1mU8zK0acDiALYWm4gbW30Ctf2v1M9h3aFtA-paT7F2voUYOhAn6UDfp_Tce1aqwOFqYvumGAriYIbRse3pcycCHoQ0xaDS1qoyDVEpJAKk1JuISa_L6GVYgABJXwZQUs2OghHVLsA6qDXqediqwYSdhuq1Vsge2eAAYngfkFAVgsIkhHCib0ZhHqatSulOSMgABWetigICAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Creact&prettier=false&targets=&version=7.12.3&externalPlugins=). If you change the preset to `es2016`, it works perfectly fine.

The code in question uses optional chaining and null coalescing, which were recently added to `@babel/preset-env`.

See this issue for context about the code in question: https://github.com/palantir/blueprint/issues/4112

<details><summary>My environment</summary>

Using:
```
    "@babel/core": "7.9.6",
    "@babel/preset-env": "7.9.6",
    "@babel/preset-react": "7.9.4",
    "@babel/preset-typescript": "7.9.0",
```

browserslist:
```
last 1 Chrome version
last 1 Firefox version
last 2 Edge major versions
last 2 Safari major version
last 2 iOS major versions
Firefox ESR
not IE 9-11
```
</details>

**Comment by alexkreidler** [comment]
pinging via git blame @jridgewell @JLHwung @nicolo-ribaudo @ryzokuken
