### ISSUE TITLE
@babel/generator, TemplateElement ast-node, Cannot read property 'quasis' of undefined  happened

### ISSUE THREAD

**Issue by navegador5** [babel/babel#12236]
## Bug Report

**Current behavior**

```js
Uncaught TypeError: Cannot read property 'quasis' of undefined  happened  , when try to generate the code for 
TemplateElement node  using @babel/generator
```

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

**Input Code**

```js
const parse = require('@babel/parser').parse
const _gen = require('@babel/generator').default
var code_str = "`head-${x}-tail`"
var ast= parse(code_str,{sourceType:'module',ranges:false,plugins:['typescript','decorators-legacy',"jsx","classProperties"]})
var t = ast.program.body[0].expression
> t.type
'TemplateLiteral'              ----------for parent-type  TemplateLiteral, worked well
>
> _gen(t).code
'`head-${x}-tail`'
>
> var quasis = t.quasis[0]      ----------in my usage, i just want to generator the code of quasis TemplateElement
undefined
> quasis                      
Node {
  type: 'TemplateElement',
  start: 1,
  end: 6,
  loc: SourceLocation {
    start: Position { line: 1, column: 1 },
    end: Position { line: 1, column: 6 }
  },
  value: { raw: 'head-', cooked: 'head-' },
  tail: false
}
>
> _gen(quasis).code
Uncaught TypeError: Cannot read property 'quasis' of undefined  =======================> ERROR happened
    at Generator.TemplateElement (/mnt/sdb/NGMATERO_/ng-matero/node_modules/@babel/generator/lib/generators/template-literals.js:17:26)
    at /mnt/sdb/NGMATERO_/ng-matero/node_modules/@babel/generator/lib/printer.js:291:19
    at Buffer.withSource (/mnt/sdb/NGMATERO_/ng-matero/node_modules/@babel/generator/lib/buffer.js:172:28)
    at Generator.withSource (/mnt/sdb/NGMATERO_/ng-matero/node_modules/@babel/generator/lib/printer.js:157:15)
    at Generator.print (/mnt/sdb/NGMATERO_/ng-matero/node_modules/@babel/generator/lib/printer.js:290:10)
    at Generator.generate (/mnt/sdb/NGMATERO_/ng-matero/node_modules/@babel/generator/lib/printer.js:49:10)
    at Generator.generate (/mnt/sdb/NGMATERO_/ng-matero/node_modules/@babel/generator/lib/index.js:24:18)
    at _default (/mnt/sdb/NGMATERO_/ng-matero/node_modules/@babel/generator/lib/index.js:92:14)
>

```

**Environment**

- Babel version(s): [6.26.0 (babel-core 6.26.3)]
- Node/npm version: [v12.16.3/6.14.4]
- OS: [Linux server_name 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux]
- Monorepo: [maybe yes, i use @babel/generator ]
- How you are using Babel: [`code`]

**Possible Solution**

-I just do a UGLY  if-block in my usge:

```js
function gen(ast) {
    if(ast.type === "CommentLine"){
        return(ast.value)
    } else if(ast.type === "CommentBlock") {
        return(ast.value)
    } else if(ast.type === "TemplateElement") {   //==========================>
        return(ast.value.cooked)                             //==========================>
    }  else {
        return(_gen(ast,{comments:true}).code)
    }
}

```

**Additional context**

**Comment by existentialism** [comment]
@navegador5 the `TemplateElement` printer requires a parent to be passed (the code currently handles printing the ticks and braces): https://github.com/babel/babel/blob/main/packages/babel-generator/src/generators/template-literals.js#L7.

**Comment by navegador5** [comment]
thanks for explaining.   Instinctively， the "${" and "}"  should be along with  expression , such as  "${ex}".
