### ISSUE TITLE
Cannot find module 'xxx\xxx\node_modules\@babel\core\node_modules\gensync\index.js'.

### ISSUE THREAD

**Issue by zcrkey** [babel/babel#12300]
## my error
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'H:\zcrkey\React\react-web\node_modules\@babel\core\node_modules\gensync\index.js'. Please verify that the package.json has a valid "main" entry
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:682:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at _gensync (H:\zcrkey\React\react-web\node_modules\@babel\core\lib\gensync-utils\async.js:12:39)
    at Object.<anonymous> (H:\zcrkey\React\react-web\node_modules\@babel\core\lib\gensync-utils\async.js:25:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (H:\zcrkey\React\react-web\node_modules\@babel\core\lib\config\caching.js:22:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
```

## my package.json
"devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-transform-react-jsx": "^7.12.1",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@babel/runtime": "^7.12.1",
    "babel-loader": "^8.1.0"
}

**Comment by nicolo-ribaudo** [comment]
Does that `node_modules\@babel\core\node_modules\gensync\index.js` file exist on your PC?

**Comment by zcrkey** [comment]
I found that my NPM installation failed to cause this problem
