### ISSUE TITLE
Minor version of `plugin-proposal-numeric-separator` suddenly breaking our app

### ISSUE THREAD

**Issue by fraywing** [babel/babel#12310]
## Bug Report

**Current behavior**
Suddenly when building our app, an upstream change in `plugin-proposal-numeric-separator` seems to break puppeteer. 

```
ERROR in ./src/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/austin/Dev/RupieNetwork/src/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js: Cannot read property 'includes' of undefined
    at PluginPass.remover (/Users/austin/Dev/RupieNetwork/node_modules/@babel/plugin-proposal-numeric-separator/lib/index.js:21:26)
    at newFn (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/path/context.js:99:18)
    at TraversalContext.visitQueue (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/path/context.js:99:18)
    at TraversalContext.visitQueue (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/path/context.js:99:18)
    at TraversalContext.visitQueue (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/path/context.js:99:18)
    at TraversalContext.visitQueue (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/Users/austin/Dev/RupieNetwork/node_modules/@babel/traverse/lib/path/context.js:99:18)
 @ ./src/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js 61:26-56
 @ ./src/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./src/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./src/puppeteer/node_modules/puppeteer/cjs-entry.js
 @ ./src/puppeteer/controllers/saveToPdf.js
 @ ./src/puppeteer/routes/index.js
 @ ./src/puppeteer/index.js
 @ multi ./src/puppeteer/index.js
```

**Expected behavior**
Was working a day ago, now when we delete yarn.lock it appears that a minor version of package dependencies within `preset-env` are causing problems. 

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
  const presets = [['@babel/env']];
  const plugins = [
    'transform-class-properties', '@babel/plugin-proposal-nullish-coalescing-operator'
  ];
```

**Environment**
```
System:
    OS: macOS 10.15.6
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.0.3 - /usr/local/bin/npm
  npmPackages:
  "@babel/cli": "^7.12.0",
    "@babel/core": "^7.12.3",
    "@babel/node": "^7.10.5",
    "@babel/plugin-proposal-export-default-from": "^7.10.4",
    "@babel/plugin-syntax-export-default-from": "^7.10.4",
    "@babel/preset-env": "^7.12.0",
    "@babel/preset-react": "^7.10.4",
    "@babel/runtime": "^7.12.0",
    "babel-eslint": "10.1.0",
    "babel-jest": "^25.5.1",
    "babel-loader": "8.1.0",
    "babel-plugin-dynamic-import-node": "^2.3.3",
    "babel-plugin-import": "1.13.1",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-plugin-transform-async-to-generator": "^7.0.0-beta.3",
    "babel-plugin-transform-class-properties": "^7.0.0-beta.3",
    "babel-plugin-transform-object-rest-spread": "^7.0.0-beta.3",
    "babel-preset-react-app": "^9.1.2",

```

```
- Babel version(s): [e.g. v^7.12.3]
- Node/npm version: [e.g. Node 15]
- OS: macOS 10.15.6
- Monorepo: yes, yarn
- How you are using Babel: cli

**Comment by nicolo-ribaudo** [comment]
I don't understand why it happens, but the fix is easy: https://github.com/babel/babel/blob/12c6db6fae54ea7ffe6481ffe7e610b8cf4146ae/packages/babel-plugin-proposal-numeric-separator/src/index.js#L12 should be replaced with
```js
  if (extra?.raw?.includes("_")) {
```

Do you want to open a PR?

---

Probably not related, but you shouldn't use `7.0.0-beta.*` versions of Babel packages alongside with stable `7.x` packages.

**Comment by fraywing** [comment]
@nicolo-ribaudo done https://github.com/babel/babel/pull/12311

**Comment by existentialism** [comment]
Might be pushing our luck, but any chance for a repo that reproduces the problem? 😄

**Comment by fraywing** [comment]
haha, I wish I could provide. We're just using puppeteer in a webpack environment ¯\_(ツ)_/¯

**Comment by fraywing** [comment]
Can we get this released?

**Comment by nicolo-ribaudo** [comment]
I can release v7.12.7 tomorrow evening. Sorry we completely forgot to release a patch for this regression :sweat_smile:
