### ISSUE TITLE
7.12 BUG: Cannot read property 'hasOwnBinding' of null; class property; initializer; SystemJS

### ISSUE THREAD

**Issue by shrinktofit** [babel/babel#12329]
Repo: https://github.com/shrinktofit/babel-bug

## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

```
(node:2504) UnhandledPromiseRejectionWarning: TypeError: X:\Temp\babelbug\light.ts: Cannot read property 'hasOwnBinding' of null
    at Object.ReferencedIdentifier (X:\Temp\babelbug\node_modules\@babel\helper-create-class-features-plugin\lib\misc.js:35:20)
    at Object.newFn (X:\Temp\babelbug\node_modules\@babel\traverse\lib\visitors.js:216:17)
    at NodePath._call (X:\Temp\babelbug\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (X:\Temp\babelbug\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (X:\Temp\babelbug\node_modules\@babel\traverse\lib\path\context.js:92:31)
    at TraversalContext.visitQueue (X:\Temp\babelbug\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitSingle (X:\Temp\babelbug\node_modules\@babel\traverse\lib\context.js:84:19)
    at TraversalContext.visit (X:\Temp\babelbug\node_modules\@babel\traverse\lib\context.js:140:19)
    at Function.traverse.node (X:\Temp\babelbug\node_modules\@babel\traverse\lib\index.js:82:17)
    at NodePath.visit (X:\Temp\babelbug\node_modules\@babel\traverse\lib\path\context.js:99:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

**Input Code**

```ts
import { Vec3 } from '../../math';

export class Light {
    protected _color: Vec3 = new Vec3(1, 1, 1);
}

```

**Expected behavior**

No error.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const babel = require('@babel/core');
const presetEnv = require('@babel/preset-env');
const fs = require('fs-extra');
(async () => {
    const result = await babel.transformFileAsync(String.raw`light.ts`, {
        presets: [
            [presetEnv, {
                modules: 'systemjs',
            }],
            [require('@babel/preset-typescript')],
        ],
        plugins: [
            [require('@babel/plugin-proposal-class-properties')],
        ],
    });
    console.log(result.code);
})();

```

**Environment**

```
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 14.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: 7.12.3 => 7.12.3
    @babel/plugin-proposal-class-properties: 7.12.1 => 7.12.1
    @babel/preset-env: 7.12.1 => 7.12.1
    @babel/preset-typescript: 7.12.1 => 7.12.1
```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context**

**Comment by shrinktofit** [comment]
It's strange if I explictly specify the systemjs plugin:
```
presets: [
            [require('@babel/preset-typescript')],
            [presetEnv, {
                // modules: 'systemjs',
            }],
            [{
                plugins: [
                    require('@babel/plugin-transform-modules-systemjs'),
                ],
            }],
        ],
        plugins: [
            require('@babel/plugin-proposal-class-properties'),
        ],
```

**Comment by nicolo-ribaudo** [comment]
A smaller example:

```js
let Vec3;

export class Light {
    _color = Vec3;
}
`;

const out = babel.transformSync(input, {
  configFile: false,
  sourceType: "module",
  filename: "input.ts",
  plugins: [
    modulesSytemJS.default,
    proposalClassProperties.default,
  ]
});
```
