### ISSUE TITLE
Cannot find module '@babel/plugin-transform-runtime'

### ISSUE THREAD

**Issue by marcusjwhelan** [babel/babel#12445]
## Bug Report

**Current behavior**

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

Github repo
https://github.com/marcusjwhelan/dockerReact

**Input Code**

Startup without docker
```bash
npm run start
```
This works and all the development process continues with hot reload just fine.

However if I try to run the application in development mode only one package is not included in the node_modules and that is @babel/plugin-transform-runtime
```bash
docker-compose -f docker-compose-dev.yml build --no-cache
docker-compose -f docker-compose-dev.yml up
# or if first time
docker-compose -f docker-compose-dev.yml up --build
```
**Expected behavior**

The application should compile and run in docker like it did before having to add the transform runtime and @babel/runtime

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "corejs": 3,
        "targets": "> 0.25%, not dead"
      }
    ],
    "@babel/preset-typescript",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-async-generator-functions",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-proposal-optional-catch-binding",
    "@babel/plugin-proposal-unicode-property-regex",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-transform-member-expression-literals",
    "@babel/plugin-transform-property-literals",
    "@babel/plugin-transform-reserved-words",
    "@babel/plugin-transform-arrow-functions",
    "@babel/plugin-transform-block-scoped-functions",
    "@babel/plugin-transform-block-scoping",
    "@babel/plugin-transform-classes",
    "@babel/plugin-transform-computed-properties",
    "@babel/plugin-transform-destructuring",
    "@babel/plugin-transform-duplicate-keys",
    "@babel/plugin-transform-for-of",
    "@babel/plugin-transform-function-name",
    "@babel/plugin-transform-instanceof",
    "@babel/plugin-transform-literals",
    "@babel/plugin-transform-object-super",
    "@babel/plugin-transform-parameters",
    "@babel/plugin-transform-shorthand-properties",
    "@babel/plugin-transform-spread",
    "@babel/plugin-transform-sticky-regex",
    "@babel/plugin-transform-template-literals",
    "@babel/plugin-transform-typeof-symbol",
    "@babel/plugin-transform-unicode-escapes",
    "@babel/plugin-transform-unicode-regex",
    "@babel/plugin-transform-exponentiation-operator",
    "@babel/plugin-transform-async-to-generator",
    "@babel/plugin-transform-typescript"
  ]
}
```

**Environment**

```

```
- Babel version(s): ^7.12.9 => 7.12.9
- Node/npm version: 12.18.2 - C:\Program Files\nodejs\node.EXE
- OS:  Windows 10 10.0.18363
- Monorepo: no
- How you are using Babel: webpack cli

**Additional context**

webpack.config.dev.js
```js
const path = require('path')
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
const WebpackPwaManifest = require('webpack-pwa-manifest')
const PATH_SOURCE = path.join(__dirname, './src')
const PATH_PUBLIC = path.join(__dirname, './public')
module.exports = {
  mode: 'development',
  target: 'web',
  // webpack will take the files from ./src/index
  entry: [
    path.join(PATH_SOURCE, './index.tsx')
  ],

  devtool: 'source-map',
  // adding .ts and .tsx to resolve.extensions will help babel look for .ts and .tsx files to transpile
  resolve: {
    extensions: ['.wasm', '.ts', '.tsx', '.mjs', '.cjs', '.js', '.json', '.html']
  },
  stats: {
    // warnings: false // in dev only -> suppress warnings
  },
  watchOptions: {
    poll: true
  },
  module: {
    rules: [

      // we use babel-loader to load our jsx and tsx files
      {
        test: /\.(ts|js)x?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        },
      },

      // css-loader to bundle all the css files into one file and style-loader to add all the styles  inside the style tag of the document
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.json$/,
        loader: 'json-loader',
        type: 'javascript/auto'
      },
      {
        test: /\.html$/,
        exclude: /node_modules/,
        loader: 'html-loader'
      },
      {
        test: /\.(a?png|svg)$/,
        loader: 'url-loader',
        options: {
          limit: 8192,
        }
      },
      {
        test: /\.(jpe?g|gif|bmp|mp3|mp4|ogg|wav|eot|ttf|woff|woff2)$/,
        use: 'file-loader'
      },
      {
        test: /\.ico$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]'
        }
      }
    ]
  },

  // development server configuration
  devServer: {
    hot: true,
    port: 3000,
    open: true,
    // must be `true` for SPAs
    historyApiFallback: true
  },
  optimization: {
    splitChunks: {
      cacheGroups: {
        default: false,
        vendors: false,

        // vendor chunk
        vendor: {
          minChunks: 2,
          // name of the chunk
          name: 'vendor',

          // async + async chunks
          chunks: 'all',

          // import file path containing node_modules
          test: /node_modules/,

          // priority
          priority: 20
        },

        // common chunk
        common: {
          name: 'common',
          minChunks: 2,
          chunks: 'all',
          priority: 10,
          reuseExistingChunk: true,
          enforce: true
        }
      }
    }
  },
  plugins: [
    new HtmlWebpackPlugin({
      favicon: path.join(PATH_PUBLIC, './favicon.ico'),
      template: path.join(PATH_PUBLIC, './index.html')
    }),
    new BundleAnalyzerPlugin(),
    new WebpackPwaManifest({
      name: 'example',
      short_name: 'ex',
      display: 'standalone',
      theme_color: '#ffffff',
      description: 'desc',
      background_color: '#212121',
      crossorigin: null, // can be null, use-credentials or anonymous
      ios: {
        'apple-mobile-web-app-title': 'Example',
        'apple-mobile-web-app-status-bar-style': 'black'
      },
      icons: [
        {
          src: path.resolve('public/logo512.png'),
          size: '512x512' // you can also use the specifications pattern
        },
        {
          src: path.resolve('public/logo192.png'),
          size: '192x192',
          destination: path.join('icons', 'ios'),
          ios: true
        },
        {
          src: path.resolve('public/logo192.png'),
          size: '192x192',
          destination: path.join('icons', 'android')
        }
      ]
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('development')
      }
    })
  ]
}
```
package.json
```json
{
  "name": "hmv1",
  "version": "0.1.0",
  "description": "Example",
  "main": "index.js",
  "scripts": {
    "bundle": "webpack --mode=production --config=webpack.config.js",
    "start": "webpack serve --config=webpack.config.dev.js --mode=development --host 127.0.0.1",
    "start_docker": "webpack serve --config=webpack.config.dev.js --mode=development --host 0.0.0.0",
    "compose_start": "docker-compose -f docker-compose-dev.yml up --build",
    "docker_build_dev": "docker build -f Dockerfile.dev -t react-dev-tag .",
    "docker_start_dev": "docker run -v \"%cd%\":/var/www -v /var/www/node_modules -p 8080:8080 -ti --rm --name dev-react-name react-dev-tag",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Marcus Whelan",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-async-generator-functions": "^7.12.1",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-proposal-export-namespace-from": "^7.12.1",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.12.1",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.12.1",
    "@babel/plugin-proposal-numeric-separator": "^7.12.7",
    "@babel/plugin-proposal-object-rest-spread": "^7.12.1",
    "@babel/plugin-proposal-optional-catch-binding": "^7.12.1",
    "@babel/plugin-proposal-optional-chaining": "^7.12.7",
    "@babel/plugin-proposal-unicode-property-regex": "^7.12.1",
    "@babel/plugin-transform-arrow-functions": "^7.12.1",
    "@babel/plugin-transform-async-to-generator": "^7.12.1",
    "@babel/plugin-transform-block-scoped-functions": "^7.12.1",
    "@babel/plugin-transform-block-scoping": "^7.12.1",
    "@babel/plugin-transform-classes": "^7.12.1",
    "@babel/plugin-transform-computed-properties": "^7.12.1",
    "@babel/plugin-transform-destructuring": "^7.12.1",
    "@babel/plugin-transform-duplicate-keys": "^7.12.1",
    "@babel/plugin-transform-exponentiation-operator": "^7.12.1",
    "@babel/plugin-transform-for-of": "^7.12.1",
    "@babel/plugin-transform-function-name": "^7.12.1",
    "@babel/plugin-transform-instanceof": "^7.12.1",
    "@babel/plugin-transform-literals": "^7.12.1",
    "@babel/plugin-transform-member-expression-literals": "^7.12.1",
    "@babel/plugin-transform-object-super": "^7.12.1",
    "@babel/plugin-transform-parameters": "^7.12.1",
    "@babel/plugin-transform-property-literals": "^7.12.1",
    "@babel/plugin-transform-reserved-words": "^7.12.1",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/plugin-transform-shorthand-properties": "^7.12.1",
    "@babel/plugin-transform-spread": "^7.12.1",
    "@babel/plugin-transform-sticky-regex": "^7.12.7",
    "@babel/plugin-transform-template-literals": "^7.12.1",
    "@babel/plugin-transform-typeof-symbol": "^7.12.1",
    "@babel/plugin-transform-typescript": "^7.12.1",
    "@babel/plugin-transform-unicode-escapes": "^7.12.1",
    "@babel/plugin-transform-unicode-regex": "^7.12.1",
    "@types/crypto-js": "^4.0.1",
    "@types/jest": "^26.0.15",
    "@types/js-cookie": "^2.2.6",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-redux": "^7.1.11",
    "@types/react-router": "^5.1.8",
    "@types/react-router-dom": "^5.1.6",
    "@types/redux-logger": "^3.0.8",
    "@typescript-eslint/eslint-plugin": "^4.9.0",
    "@typescript-eslint/eslint-plugin-tslint": "^4.9.0",
    "@typescript-eslint/parser": "^4.9.0",
    "babel-loader": "^8.2.2",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^5.0.1",
    "eslint": "^7.14.0",
    "eslint-plugin-jsdoc": "^30.7.8",
    "eslint-plugin-no-null": "^1.0.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "fibers": "^5.0.0",
    "file-loader": "^6.2.0",
    "html-loader": "^1.3.2",
    "html-webpack-plugin": "^4.5.0",
    "identity-obj-proxy": "^3.0.0",
    "imports-loader": "^1.2.0",
    "json-loader": "^0.5.7",
    "redux-logger": "^3.0.6",
    "resolve-url-loader": "^3.1.2",
    "source-map-loader": "^1.1.2",
    "style-loader": "^2.0.0",
    "ts-loader": "^8.0.11",
    "typescript": "^4.1.2",
    "url-loader": "^4.1.1",
    "webpack": "^5.9.0",
    "webpack-bundle-analyzer": "^4.2.0",
    "webpack-cli": "^4.2.0",
    "webpack-dev-server": "^4.0.0-beta.0",
    "webpack-pwa-manifest": "^4.3.0"
  },
  "dependencies": {
    "@babel/preset-env": "^7.12.7",
    "@babel/preset-react": "^7.12.7",
    "@babel/preset-typescript": "^7.12.7",
    "@babel/runtime": "^7.12.5",
    "@babel/runtime-corejs3": "^7.12.5",
    "@material-ui/core": "^4.11.1",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "axios": "^0.21.0",
    "connected-react-router": "^6.8.0",
    "crypto-js": "^4.0.0",
    "history": "^5.0.0",
    "jquery": "^3.5.1",
    "js-cookie": "^2.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-redux": "^7.2.2",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-spring": "^8.0.27",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
  }
}

```

# The error
```bash
docker-compose -f docker-compose-dev.yml up
Recreating docker_react_dev_container ... done
Attaching to docker_react_dev_container
docker_react_dev_container |
docker_react_dev_container | > hmv1@0.1.0 start_docker /var/www
docker_react_dev_container | > webpack serve --config=webpack.config.dev.js --mode=development --host 0.0.0.0
docker_react_dev_container |
docker_react_dev_container | <i> [webpack-dev-server] Project is running at http://0.0.0.0:3000/
docker_react_dev_container | <i> [webpack-dev-server] Content not from webpack is served from /var/www
docker_react_dev_container | <i> [webpack-dev-server] 404s will fallback to /index.html
docker_react_dev_container | (node:23) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
docker_react_dev_container | BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
docker_react_dev_container |    Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
docker_react_dev_container |    Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
docker_react_dev_container | (Use `node --trace-deprecation ...` to show where the warning was created)
docker_react_dev_container | Error parsing bundle asset "/var/www/dist/main.js": no such file
docker_react_dev_container |
docker_react_dev_container | No bundles were parsed. Analyzer will show only original module sizes from stats file.
docker_react_dev_container |
docker_react_dev_container | Webpack Bundle Analyzer is started at http://127.0.0.1:8888
docker_react_dev_container | Use Ctrl+C to close it
docker_react_dev_container | <e> [webpack-dev-middleware] assets by path icons/ 46.3 KiB
docker_react_dev_container | <e>   asset icons/android/icon_192x192.4b84f1f7e81945d33680dacbfc230eaa.png 23.1 KiB [emitted]
docker_react_dev_container | <e>   asset icons/ios/icon_192x192.4b84f1f7e81945d33680dacbfc230eaa.png 23.1 KiB [emitted]
docker_react_dev_container | <e> asset main.js 250 KiB [emitted] (name: main) 1 related asset
docker_react_dev_container | <e> asset icon_512x512.27f2880700cd02fe09aa71289ac8b7f7.png 29.8 KiB [emitted]
docker_react_dev_container | <e> asset favicon.ico 3.78 KiB [emitted]
docker_react_dev_container | <e> asset index.html 1.03 KiB [emitted]
docker_react_dev_container | <e> asset manifest.de05c92f23f6c327d93c915bc9ebcc42.json 656 bytes [emitted]
docker_react_dev_container | <e> runtime modules 24.8 KiB 10 modules
docker_react_dev_container | <e> cacheable modules 193 KiB
docker_react_dev_container | <e>   modules by path ./node_modules/webpack-dev-server/client/ 71 KiB 12 modules
docker_react_dev_container | <e>   modules by path ./node_modules/webpack/hot/*.js 4.3 KiB 4 modules
docker_react_dev_container | <e>   modules by path ./node_modules/html-entities/lib/*.js 57.9 KiB 4 modules
docker_react_dev_container | <e>   modules by path ./node_modules/url/ 37.4 KiB 3 modules
docker_react_dev_container | <e>   modules by path ./node_modules/querystring/*.js 4.51 KiB
docker_react_dev_container | <e>     ./node_modules/querystring/index.js 127 bytes [built] [code generated]
docker_react_dev_container | <e>     ./node_modules/querystring/decode.js 2.34 KiB [built] [code generated]
docker_react_dev_container | <e>     ./node_modules/querystring/encode.js 2.04 KiB [built] [code generated]
docker_react_dev_container | <e>   ./src/index.tsx 39 bytes [built] [code generated] [1 error]
docker_react_dev_container | <e>   ./node_modules/ansi-html/index.js 4.16 KiB [built] [code generated]
docker_react_dev_container | <e>   ./node_modules/events/events.js 13.8 KiB [built] [code generated]
docker_react_dev_container | <e> ./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]
docker_react_dev_container | <e>
docker_react_dev_container | <e> ERROR in ./src/index.tsx
docker_react_dev_container | <e> Module build failed (from ./node_modules/babel-loader/lib/index.js):
docker_react_dev_container | <e> Error: Cannot find module '@babel/plugin-transform-runtime' from '/var/www'
docker_react_dev_container | <e>     at Function.resolveSync [as sync] (/var/www/node_modules/resolve/lib/sync.js:90:15)
docker_react_dev_container | <e>     at resolveStandardizedName (/var/www/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
docker_react_dev_container | <e>     at resolvePlugin (/var/www/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
docker_react_dev_container | <e>     at loadPlugin (/var/www/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
docker_react_dev_container | <e>     at createDescriptor (/var/www/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
docker_react_dev_container | <e>     at /var/www/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
docker_react_dev_container | <e>     at Array.map (<anonymous>)
docker_react_dev_container | <e>     at createDescriptors (/var/www/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
docker_react_dev_container | <e>     at createPluginDescriptors (/var/www/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
docker_react_dev_container | <e>     at plugins (/var/www/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
docker_react_dev_container | <e>
docker_react_dev_container | <e> webpack 5.9.0 compiled with 1 error in 5969 ms
docker_react_dev_container | <i> [webpack-dev-middleware] Failed to compile.

```

**Comment by marcusjwhelan** [comment]
Needed to delete the container and the associated volume. I guess the rebuild was not starting from scratch even with the `--no-cache` command.
