### ISSUE TITLE
@babel/preset-typescript   Error: Assert fail  @babel/parser/src/plugins/typescript/index.js:53:11

### ISSUE THREAD

**Issue by Topthinking** [babel/babel#12587]
### Input Code

```jsx
let a = 2

a == 3 ? (a = <h1>123</h1>) : (a = <h1>abc</h1>)
```

### error message
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Assert fail
    at assert (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:53:11)
    at Object.parseMaybeAssign (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:2504:9)
    at callback (/project/node_modules/@babel/core/node_modules/@babel/parser/src/parser/expression.js:224:12)
    at Object.allowInAnd (/project/node_modules/@babel/core/node_modules/@babel/parser/src/parser/expression.js:2561:12)
    at Object.parseMaybeAssignAllowIn (/project/node_modules/@babel/core/node_modules/@babel/parser/src/parser/expression.js:223:17)
    at Object.parseMaybeDefault (/project/node_modules/@babel/core/node_modules/@babel/parser/src/parser/lval.js:375:23)
    at Object.parseMaybeDefault (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:2676:26)
    at Object.parseAssignableListItem (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:1738:25)
    at Object.parseBindingList (/project/node_modules/@babel/core/node_modules/@babel/parser/src/parser/lval.js:336:24)
    at Object.tsParseBindingListForSignature (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:448:19)
    at Object.tsFillSignature (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:433:35)
    at Object.tsParseFunctionOrConstructorType (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:753:12)
    at Object.tsParseNonConditionalType (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:1170:21)
    at Object.tsParseType (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:1154:25)
    at cb (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:1145:33)
    at Object.tsInType (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:1281:16)
```

## babel-code

![image](https://user-images.githubusercontent.com/13382821/103642628-6564fe80-4f8e-11eb-9b91-77647c97b19d.png)

https://github.com/babel/babel/blob/0d6063f1b9c837838ddefc2c623ac9fd594fa7f0/packages/babel-parser/src/plugins/typescript/index.js#L2504

## babel gif【 try it out 】

![Jan-05-2021 19-04-53](https://user-images.githubusercontent.com/13382821/103639251-0d77c900-4f89-11eb-821a-5c459d2de324.gif)

## link 【 try it out 】

https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAhhC8ECYDcAoFNaYgZggfggAoMIAeACwEYA-BUgeiuoEoIAuIqWCha7bBuV7NUaevWhwsuAsThkmdRjVYc58SsyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.12&externalPlugins=

**Comment by Topthinking** [comment]
![Jan-05-2021 18-46-49](https://user-images.githubusercontent.com/13382821/103637707-d7394a00-4f86-11eb-915a-390fd64092ee.gif)

**Comment by Topthinking** [comment]
https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=C4JwrgpgBA_FAUBDKBeATARjQZi9qAlFAFwKLoEDcAUEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.12.12&externalPlugins=

**Comment by Topthinking** [comment]
@JLHwung   What happens now

**Comment by JLHwung** [comment]
@Topthinking It is indeed a parser bug but currently team members are prioritizing other tasks. Feel free to send a PR if you come up with a fix. Or reach out if you would like to work on this issue.
