### ISSUE TITLE
build by rollup with babel7 cannot support IE11

### ISSUE THREAD

**Issue by quicklearning123** [babel/babel#12614]
## Bug Report
I cannot make my code build with babel work on the IE11.
Could someone help me ?

**Current behavior**

- [REPL](https://babel.dev/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo may increase triaging priority!

**Input Code**

**Expected behavior**
can work on IE11

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

package.json
```
{
  "name": "@antv/x6",
  "version": "1.8.2",
  "description": "JavaScript diagramming library that uses SVG and HTML for rendering.",
  "main": "lib/index.js",
  "module": "es/index.js",
  "unpkg": "dist/x6.js",
  "jsdelivr": "dist/x6.js",
  "types": "lib/index.d.ts",
  "files": [
    "dist",
    "es",
    "lib"
  ],
  "keywords": [
    "graph",
    "diagram",
    "flowchart",
    "uml",
    "x6-editor",
    "editor",
    "svg",
    "x6",
    "antv"
  ],
  "scripts": {
    "clean:build": "rimraf dist es lib",
    "clean:coverage": "rimraf ./test/coverage",
    "clean": "run-p clean:build clean:coverage",
    "lint:es": "eslint --ext .js scripts --fix",
    "lint:ts": "tslint -c tslint.json -p tsconfig.json --fix",
    "lint:style": "stylelint 'src/**/*.less' --syntax less --fix",
    "lint": "run-s lint:ts lint:es lint:style",
    "build:esm": "tsc --module esnext --target es2015 --outDir ./es",
    "build:cjs": "tsc --module commonjs --target es5 --outDir ./lib",
    "build:umd": "rollup -c",
    "build:less": "node ./scripts/style",
    "build:readme": "node ./scripts/readme.js",
    "build:version": "node ./scripts/version.js",
    "build:csstype": "node ./scripts/csstype.js",
    "build:dev": "run-p build:csstype build:less build:cjs build:esm",
    "build:watch": "yarn build:esm --w",
    "build:watch:esm": "yarn build:esm --w",
    "build:watch:cjs": "yarn build:cjs --w",
    "build": "run-p build:readme build:version build:dev build:umd",
    "prebuild": "run-s lint clean",
    "test": "karma start",
    "coveralls": "cat ./test/coverage/lcov.info | coveralls",
    "pretest": "run-p clean:coverage",
    "prepare": "run-s build:version test build",
    "precommit": "lint-staged"
  },
  "lint-staged": {
    "src/**/*.less": [
      "stylelint --syntax less --fix"
    ],
    "*.js": [
      "eslint --fix"
    ],
    "src/**/*.ts": [
      "tslint -c tslint.json -p ./tsconfig.json --fix"
    ]
  },
  "dependencies": {
    "@babel/runtime": "^7.12.5",
    "@babel/runtime-corejs3": "^7.12.5",
    "core-js": "^3.8.2",
    "csstype": "^3.0.3",
    "jquery": "^3.5.1",
    "jquery-mousewheel": "^3.1.13",
    "lodash-es": "^4.17.15",
    "mousetrap": "^1.6.5",
    "regenerator-runtime": "^0.13.7",
    "utility-types": "^3.10.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-proposal-decorators": "^7.12.12",
    "@babel/plugin-transform-runtime": "^7.12.10",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-typescript": "^7.12.10",
    "@rollup/plugin-babel": "^5.2.2",
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-node-resolve": "^11.0.0",
    "@rollup/plugin-replace": "^2.3.4",
    "@rollup/plugin-typescript": "^8.1.0",
    "@types/jasmine": "^3.6.2",
    "@types/jquery": "^3.5.5",
    "@types/jquery-mousewheel": "^3.1.8",
    "@types/lodash-es": "^4.17.4",
    "@types/mousetrap": "^1.6.5",
    "@types/node": "^14.14.14",
    "@types/sinon": "^9.0.0",
    "coveralls": "^3.1.0",
    "eslint": "^7.16.0",
    "jasmine-core": "^3.6.0",
    "karma": "^5.2.3",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-jasmine": "^4.0.1",
    "karma-spec-reporter": "^0.0.32",
    "karma-typescript": "^5.2.0",
    "karma-typescript-es6-transform": "^5.1.0",
    "less": "^4.0.0",
    "lint-staged": "^10.5.3",
    "npm-run-all": "^4.1.5",
    "rimraf": "^3.0.0",
    "rollup": "^2.35.1",
    "rollup-plugin-filesize": "^9.1.0",
    "rollup-plugin-progress": "^1.1.2",
    "rollup-plugin-terser": "^7.0.2",
    "sinon": "^9.0.2",
    "stylelint": "^13.8.0",
    "ts-node": "^9.1.1",
    "tslint": "^6.1.3",
    "typescript": "^4.1.2"
  },
  "author": {
    "name": "bubkoo",
    "email": "bubkoo.wy@gmail.com"
  },
  "contributors": [],
  "license": "MIT",
  "homepage": "https://github.com/antvis/x6",
  "bugs": {
    "url": "https://github.com/antvis/x6/issues"
  },
  "repository": {
    "type": "git",
    "url": "ssh://git@github.com/antvis/x6.git",
    "directory": "packages/x6"
  },
  "publishConfig": {
    "access": "public",
    "registry": "https://registry.npmjs.org"
  }
}
rollup.config.js
```
import { terser } from 'rollup-plugin-terser'
import replace from '@rollup/plugin-replace'
import commonjs from '@rollup/plugin-commonjs'
import filesize from 'rollup-plugin-filesize'
import resolve from '@rollup/plugin-node-resolve'
import typescript from '@rollup/plugin-typescript'
// import progress from 'rollup-plugin-progress'

import babel from '@rollup/plugin-babel'

export default {
  input: './src/index.ts',
  output: [
    {
      name: 'X6',
      format: 'umd',
      file: 'dist/x6.js',
      sourcemap: true,
    },
  ],
  plugins: [
    typescript({ declaration: false }),
    resolve({
      browser: true
    }),
    commonjs(),
    replace({ 'process.env.NODE_ENV': JSON.stringify('production') }),
    // progress(),
    babel({
      // exclude: "node_modules/**", // only transpile our source code
      // babelHelpers: 'bundled'
      babelHelpers: 'runtime'
    }),
    // terser(),
    filesize(),
  ],
}

```

```
babel.config.json
```
{
  "presets": [
    [
      "@babel/preset-env", {
        "targets": {
          "edge": "17",
          "firefox": "60",
          "chrome": "67",
          "safari": "11.1",
          "ie": "11"
        },
        "debug":true,
        "shippedProposals":true,
      "modules": false,
      "loose": true,
      "useBuiltIns": "entry",
      "spec": true,
      "forceAllTransforms": true,
      "corejs": { "version":3 }
    }],
    ["@babel/preset-typeScript"],
    "@babel/preset-react"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators",{"decoratorsBeforeExport":true}],
    ["@babel/plugin-proposal-class-properties"],
    [
      "@babel/plugin-transform-runtime", 
      {
        "corejs": { "version":3 }
      }
    ]
  ]
}
```

**Environment**

```
npx: 1 安装成功，用时 0.866 秒

  System:
    OS: macOS 10.15.5
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.7.0/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.7.0/bin/npm
  npmPackages:
    @babel/core: ^7.12.10 => 7.12.10
    @babel/plugin-proposal-class-properties: ^7.12.1 => 7.12.1
    @babel/plugin-proposal-decorators: ^7.12.12 => 7.12.12
    @babel/plugin-transform-runtime: ^7.12.10 => 7.12.10
    @babel/preset-env: ^7.12.11 => 7.12.11
    @babel/runtime: ^7.12.5 => 7.12.5
    @babel/runtime-corejs3: ^7.12.5 => 7.12.5
```
- Babel version(s): [v7.12.10]
- Node/npm version: [e.g. Node 14 npm6]
- OS: [macOS 10.15.4, Windows 10]
- Monorepo: [e.g. Lerna]
- How you are using Babel: [`rollup`]

**Possible Solution**

**Additional context**

**Comment by JLHwung** [comment]
```
babel({
      // exclude: "node_modules/**", // only transpile our source code
      // babelHelpers: 'bundled'
      babelHelpers: 'runtime'
    }),
```
I think `babelHelpers: 'bundled'` serves your purpose: bundle `X6` into a library that can run on `X6test.html`. 

If you specify `runtime`, Rollup also suggests that you should mark `@babel/runtime` as an external dependency so `require("@babel/runtime")` will be in the build artifacts, which is apparently not what you want.

See https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers for more info.

Can you also attach the built `X6.js`?

**Comment by quicklearning123** [comment]
> ```
> babel({
>       // exclude: "node_modules/**", // only transpile our source code
>       // babelHelpers: 'bundled'
>       babelHelpers: 'runtime'
>     }),
> ```
> 
> I think `babelHelpers: 'bundled'` serves your purpose: bundle `X6` into a library that can run on `X6test.html`.
> 
> If you specify `runtime`, Rollup also suggests that you should mark `@babel/runtime` as an external dependency so `require("@babel/runtime")` will be in the build artifacts, which is apparently not what you want.
> 
> See https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers for more info.
> 
> Can you also attach the built `X6.js`?

When set babelHelpers to bundled, I got an error: 

```
[/Users/qingyang/dev/X6-master/node_modules/tslib/tslib.es6.js] Based on your code and targets, core-js polyfills were not added.
[!] (plugin babel) Error: You have declared using "bundled" babelHelpers, but transforming /Users/qingyang/dev/X6-master/node_modules/tslib/tslib.es6.js resulted in "runtime". Please check your configuration.
../../node_modules/tslib/tslib.es6.js
Error: You have declared using "bundled" babelHelpers, but transforming /Users/qingyang/dev/X6-master/node_modules/tslib/tslib.es6.js resulted in "runtime". Please check your configuration.
    at error (/Users/qingyang/dev/X6-master/node_modules/rollup/dist/shared/rollup.js:5265:30)
    at throwPluginError (/Users/qingyang/dev/X6-master/node_modules/rollup/dist/shared/rollup.js:17956:12)
    at Object.error (/Users/qingyang/dev/X6-master/node_modules/rollup/dist/shared/rollup.js:18563:24)
    at Object.error (/Users/qingyang/dev/X6-master/node_modules/rollup/dist/shared/rollup.js:18125:38)
    at preflightCheck (/Users/qingyang/dev/X6-master/packages/x6/node_modules/@rollup/plugin-babel/dist/index.js:204:9)
    at /Users/qingyang/dev/X6-master/packages/x6/node_modules/@rollup/plugin-babel/dist/index.js:433:13
    at transformCode (/Users/qingyang/dev/X6-master/packages/x6/node_modules/@rollup/plugin-babel/dist/index.js:245:24)
    at ModuleLoader.addModuleSource (/Users/qingyang/dev/X6-master/node_modules/rollup/dist/shared/rollup.js:18319:30)
    at ModuleLoader.fetchModule (/Users/qingyang/dev/X6-master/node_modules/rollup/dist/shared/rollup.js:18375:9)
    at async Promise.all (index 0)
    at ModuleLoader.fetchStaticDependencies (/Users/qingyang/dev/X6-master/node_modules/rollup/dist/shared/rollup.js:18400:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/Users/qingyang/dev/X6-master/node_modules/rollup/dist/shared/rollup.js:18377:9)
    at async Promise.all (index 12)
    at ModuleLoader.fetchStaticDependencies (/Users/qingyang/dev/X6-master/node_modules/rollup/dist/shared/rollup.js:18400:34)
    at async Promise.all (index 0)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @antv/x6@1.8.2 build:umd: `rollup -c`
npm ERR! Exit status 1

```

**Comment by quicklearning123** [comment]
@JLHwung  My x6.js is here. https://gitee.com/quicklearning123/X6/blob/master/packages/x6/dist_v1/x6.js

**Comment by quicklearning123** [comment]
still many  log when building even add exclude: "node_modules/**"

```
[/Users/qingyang/dev/myx6/X6/node_modules/core-js-pure/es/instance/trim-right.js] Import of core-js was not found.
Though the "loose" option was set to "true" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "false" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": false }]
to the "plugins" section of your Babel config.

[/Users/qingyang/dev/myx6/X6/node_modules/core-js-pure/es/string/virtual/trim-left.js] Import of core-js was not found.
Though the "loose" option was set to "true" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "false" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": false }]
to the "plugins" section of your Babel config.

[/Users/qingyang/dev/myx6/X6/node_modules/core-js-pure/es/string/virtual/trim-left.js] Import of core-js was not found.
Though the "loose" option was set to "true" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "false" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": false }]
to the "plugins" section of your Babel config.

[/Users/qingyang/dev/myx6/X6/node_modules/core-js-pure/es/string/virtual/trim-right.js] Import of core-js was not found.
Though the "loose" option was set to "true" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "false" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": false }]
to the "plugins" section of your Babel config.

[/Users/qingyang/dev/myx6/X6/node_modules/core-js-pure/es/string/virtual/trim-right.js] Import of core-js was not found.
┌──────────────────────────────┐
│                              │
│   Destination: dist/x6.js    │
│   Bundle Size:  2.62 MB      │
│   Minified Size:  1 MB       │
│   Gzipped Size:  284.73 KB   │
│                              │
└──────────────────────────────┘
(!) Circular dependencies
../../node_modules/@babel/runtime-corejs3/core-js/instance/slice.js -> ../../node_modules/core-js-pure/features/instance/slice.js -> ../../node_modules/core-js-pure/es/instance/slice.js -> ../../node_modules/@babel/runtime-corejs3/core-js/instance/slice.js
../../node_modules/@babel/runtime-corejs3/core-js/instance/slice.js -> ../../node_modules/core-js-pure/features/instance/slice.js -> ../../node_modules/core-js-pure/es/instance/slice.js -> ../../node_modules/core-js-pure/es/array/virtual/slice.js -> ../../node_modules/@babel/runtime-corejs3/core-js/instance/slice.js
../../node_modules/@babel/runtime-corejs3/core-js/instance/slice.js -> ../../node_modules/core-js-pure/features/instance/slice.js -> ../../node_modules/core-js-pure/es/instance/slice.js -> ../../node_modules/core-js-pure/es/array/virtual/slice.js -> ../../node_modules/core-js-pure/modules/es.array.slice.js -> ../../node_modules/@babel/runtime-corejs3/core-js/instance/slice.js
```

**Comment by quicklearning123** [comment]
now the v2 error is :
![image](https://user-images.githubusercontent.com/70048681/104492181-3e51a100-560e-11eb-858e-1913bdab882e.png)
![image](https://user-images.githubusercontent.com/70048681/104492268-56c1bb80-560e-11eb-824b-ecb1f7de09b2.png)

**Comment by quicklearning123** [comment]
```
![image](https://user-images.githubusercontent.com/70048681/104493053-773e4580-560f-11eb-8dba-8d4e56ce4c26.png)

```

**Comment by quicklearning123** [comment]
![image](https://user-images.githubusercontent.com/70048681/104493091-81f8da80-560f-11eb-9375-1b02e294fef6.png)

**Comment by JLHwung** [comment]
The error is thrown from lodash in your n_m:

https://github.com/lodash/lodash/blob/2f79053d7bc7c9c9561a30dda202b3dcd2b72b90/.internal/nodeTypes.js#L6-L7

where `typeof module` is replaced by `"object"` and thus it throws on IE 11. Since `lodash` is excluded in `rollup-babel` and `terser` is not enabled, please check if you have enabled some tools that evaluates `typeof module` to `"object"`.
