### ISSUE TITLE
transformSync in @babel/core does not handle overrides in babel.config.json

### ISSUE THREAD

**Issue by ayush000** [babel/babel#12627]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

<details>
<summary>If I try to run `babel.transformSync("code()")`, I get this error:</summary>
<p>

```
HookWebpackError: Configuration contains string/RegExp pattern, but no filename was passed to Babel
    at makeWebpackError (/Users/ayushsachdeva/repos/moby/node_modules/webpack/lib/HookWebpackError.js:49:9)
    at /Users/ayushsachdeva/repos/moby/node_modules/webpack/lib/Compilation.js:2107:11
    at eval (eval at create (/Users/ayushsachdeva/repos/moby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at /Users/ayushsachdeva/repos/moby/node_modules/webpack/lib/Compilation.js:363:26
    at /Users/ayushsachdeva/repos/moby/node_modules/webpack-merge-and-include-globally/index.node6-compatible.js:318:11
-- inner error --
Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel
    at matchPattern (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:544:11)
    at /Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:531:35
    at Array.some (<anonymous>)
    at matchesPatterns (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:531:19)
    at configFieldIsApplicable (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:497:10)
    at configIsApplicable (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:492:41)
    at /Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:331:13
    at Array.forEach (<anonymous>)
    at /Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:328:42
    at Generator.next (<anonymous>)
    at loadFileChain (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:228:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:97:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/partial.js:101:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/full.js:57:46)
    at loadFullConfig.next (<anonymous>)
    at Object.transform (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/transform.js:25:45)
    at transform.next (<anonymous>)
    at evaluateSync (/Users/ayushsachdeva/repos/moby/node_modules/gensync/index.js:251:28)
    at Object.sync (/Users/ayushsachdeva/repos/moby/node_modules/gensync/index.js:89:14)
    at Object.admin-yui-app.min.js (/Users/ayushsachdeva/repos/moby/webpack.config.js:344:36)
    at Object.fileTransform.dest (/Users/ayushsachdeva/repos/moby/node_modules/webpack-merge-and-include-globally/index.node6-compatible.js:180:133)
    at _callee3$ (/Users/ayushsachdeva/repos/moby/node_modules/webpack-merge-and-include-globally/index.node6-compatible.js:210:40)
    at tryCatch (/Users/ayushsachdeva/repos/moby/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/ayushsachdeva/repos/moby/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/Users/ayushsachdeva/repos/moby/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/ayushsachdeva/repos/moby/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/ayushsachdeva/repos/moby/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
caused by plugins in Compilation.hooks.processAssets
Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel
    at matchPattern (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:544:11)
    at /Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:531:35
    at Array.some (<anonymous>)
    at matchesPatterns (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:531:19)
    at configFieldIsApplicable (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:497:10)
    at configIsApplicable (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:492:41)
    at /Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:331:13
    at Array.forEach (<anonymous>)
    at /Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:328:42
    at Generator.next (<anonymous>)
    at loadFileChain (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:228:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/config-chain.js:97:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/partial.js:101:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/config/full.js:57:46)
    at loadFullConfig.next (<anonymous>)
    at Object.transform (/Users/ayushsachdeva/repos/moby/node_modules/@babel/core/lib/transform.js:25:45)
    at transform.next (<anonymous>)
    at evaluateSync (/Users/ayushsachdeva/repos/moby/node_modules/gensync/index.js:251:28)
    at Object.sync (/Users/ayushsachdeva/repos/moby/node_modules/gensync/index.js:89:14)
    at Object.admin-yui-app.min.js (/Users/ayushsachdeva/repos/moby/webpack.config.js:344:36)
    at Object.fileTransform.dest (/Users/ayushsachdeva/repos/moby/node_modules/webpack-merge-and-include-globally/index.node6-compatible.js:180:133)
    at _callee3$ (/Users/ayushsachdeva/repos/moby/node_modules/webpack-merge-and-include-globally/index.node6-compatible.js:210:40)
    at tryCatch (/Users/ayushsachdeva/repos/moby/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/ayushsachdeva/repos/moby/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/Users/ayushsachdeva/repos/moby/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/ayushsachdeva/repos/moby/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/ayushsachdeva/repos/moby/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

</p>
</details>

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.json`

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": 3.8
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ],
  "overrides": [
    {
      "test": "node_modules/path-to-node-module",
      "presets": [
        [
          "@babel/preset-env",
          {
            "useBuiltIns": false
          }
        ]
      ]
    }
  ],
  "env": {
    "test": {
      "plugins": [
        "transform-amd-to-commonjs"
      ]
    }
  }
}
```

**Environment**

```

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  npmPackages:
    @babel/core: 7.8.0 => 7.8.0 
    @babel/plugin-proposal-class-properties: ^7.12.1 => 7.12.1 
    @babel/preset-env: 7.8.0 => 7.8.0 
    @babel/preset-react: 7.8.0 => 7.8.0 
    @babel/register: 7.8.0 => 7.8.0 
    @babel/runtime-corejs3: ^7.12.5 => 7.12.5 
    babel-loader: ^8.2.2 => 8.2.2 
    babel-plugin-module-resolver: 4.0.0 => 4.0.0 
    babel-plugin-transform-amd-to-commonjs: 1.4.0 => 1.4.0 
    eslint: ^7.15.0 => 7.15.0 
    jest: 25.2.4 => 25.2.4 
    webpack: ^5.10.0 => 5.10.0 
```

**Possible Solution**

Without the overrides in `babel.config.json`, `babel.transformSync` works without any error. Upon analyzing error stack trace,  I found that inside `node_modules/@babel/core/lib/config/config-chain.js`, `matchToPattern` function receives `pathToTest` as `undefined`. For `babel.transformSync`, I believe it shouldn't reach the `matchPattern` function if filename is not passed to `transformAsync`. A hacky fix I made was to pass some filename to `transformSync` call. 

```js
babel.transformAsync("code()", {filename: "./babel.config.json"})
```

**Additional context**

Not 100% sure, but this issue might be related to https://github.com/babel/babel/issues/11540

**Comment by JLHwung** [comment]
> it shouldn't reach the matchPattern function if filename is not passed to transformAsync

`matchToPattern` is called because there is a `test` option in `overrides`

> "test": "node_modules/path-to-node-module",

Babel requires `filename` otherwise it can't tell whether `"code()"` is intended to be  `"node_modules/path-to-node-module"` .

**Comment by ayush000** [comment]
Thanks for clarification. I was looking to use `babel.transformSync` to transform output of `webpack-merge-and-include-globally` plugin. So have filed an issue over there asking if they can pass the filename too https://github.com/markshapiro/webpack-merge-and-include-globally/issues/58
