### ISSUE TITLE
Cannot read property 'slice' of undefined version in new project 

### ISSUE THREAD

**Issue by saeed-cs** [babel/babel#12657]
## Bug Report

**Current behavior**
I install a new react app by create-react-app  and config webpack config and trying to build with webpack but got this error.
note : according to [this link  ](https://webpack.js.org/guides/typescript/) 

> Note that if you're already using babel-loader to transpile your code, **_you can use @babel/preset-typescript and let Babel handle both your JavaScript and TypeScript files instead of using an additional loader_**. Keep in mind that, contrary to ts-loader, the underlying @babel/plugin-transform-typescript plugin does not perform any type checking.

I used @babel/preset-typescript as loader because if I use babel-loader webpack have problem in parse some thing like :
``` import {somthing} from sth ``` or define type of variable like ``` let variabel:string ='nothing' ```

But in below Error code you can see the problem with undefined !
How can I fix this issue?

**Error Code**
$ ./node_modules/webpack/bin/webpack.js serve
```js
ERROR in ./src/index.js
Module build failed (from ./node_modules/@babel/preset-typescript/lib/index.js):
TypeError: Cannot read property 'slice' of undefined
    at throwVersionError (node_modules/@babel/helper-plugin-utils/lib/index.js:62:15)
    at Object.assertVersion (node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at node_modules/@babel/preset-typescript/lib/index.js:19:7
    at Object.<anonymous> (node_modules/@babel/helper-plugin-utils/lib/index.js:19:12)

webpack 5.15.0 compiled with 1 error and 1 warning in 795 ms
ℹ ｢wdm｣: Failed to compile.


```

**webpack config**

```js
const HtmlWebPackPlugin = require( 'html-webpack-plugin' );
const path = require( 'path' );
const babelLoaderOptions = {
    presets: [
        '@babel/preset-typescript',
        [
            '@babel/preset-env',
            {
                loose: true,
                // debug: true,
                modules: 'auto',
                spec: true,
                useBuiltIns: 'usage',
                corejs: 3,
                targets: {
                    browsers: ['last 2 versions'],
                    // esmodules: true,
                },
            },
        ],
        ["@babel/preset-react", {
            "runtime": "automatic"
        }],
    ],
    plugins: [
        ['@babel/plugin-transform-runtime', {
            corejs: 3,
            helpers: true,
            regenerator: false,
            absoluteRuntime: false,
            useESModules: true,
        }],
        '@babel/plugin-proposal-export-default-from',
        '@babel/plugin-proposal-export-namespace-from',
        '@babel/plugin-syntax-dynamic-import',
        // "babel-plugin-dynamic-import-webpack",
        'lodash',
        '@babel/plugin-proposal-class-properties',
        '@babel/plugin-transform-arrow-functions',
    ],
};
module.exports = {
    context: __dirname,
    entry: './src/index.js',
    output: {
        path: path.resolve( __dirname, 'dist' ),
        filename: 'main.js',
        publicPath: '/',
    },
    devServer: {
        port: 9898,
        historyApiFallback: true
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules(?!(\/|\\)vast-client)/,
                loader: '@babel/preset-typescript',
                // loader: 'babel-loader',
                options: babelLoaderOptions,
            },
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader'],
            },
            {
                test: /\.(png|j?g|svg|gif)?$/,
                use: 'file-loader'
            }
        ]
    },
    plugins: [
        new HtmlWebPackPlugin({
            template: path.resolve( __dirname, 'public/index.html' ),
            filename: 'index.html'
        })
    ]
};

```

**packages**
```
$ cat package.json 
{
  "name": "webpack_new_react",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/plugin-proposal-export-default-from": "^7.12.1",
    "@babel/plugin-transform-runtime": "^7.12.10",
    "@babel/preset-react": "^7.12.10",
    "@babel/preset-typescript": "^7.12.7",
    "babel-loader": "^8.2.2",
    "babel-plugin-lodash": "^3.3.4",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^7.0.0",
    "css-loader": "^5.0.1",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^4.5.1",
    "node-sass": "^5.0.0",
    "node-sass-utils": "^1.1.3",
    "react-svg-loader": "^3.0.3",
    "style-loader": "^2.0.0",
    "webpack": "^5.15.0",
    "webpack-cli": "^4.3.1",
    "webpack-dev-server": "^3.11.2"
  }
}

```
**Env**
```
$ npx envinfo --preset babel

  System:
    OS: Linux 5.9 Fedora 32 (KDE Plasma) 32 (KDE Plasma)
  Binaries:
    Node: 12.20.1 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  npmPackages:
    @babel/plugin-proposal-export-default-from: ^7.12.1 => 7.12.1 
    @babel/plugin-transform-runtime: ^7.12.10 => 7.12.10 
    @babel/preset-react: ^7.12.10 => 7.12.10 
    @babel/preset-typescript: ^7.12.7 => 7.12.7 
    babel-loader: ^8.2.2 => 8.2.2 
    babel-plugin-lodash: ^3.3.4 => 3.3.4 
    webpack: ^5.15.0 => 5.15.0 


```

**Comment by JLHwung** [comment]
```diff
--- loader: '@babel/preset-typescript',
+++ loader: 'babel-loader'
```

The `loader` should be `babel-loader`, `@bable/preset-typescript` is Babel preset, not a Webpack loader.
