### ISSUE TITLE
Throw on duplicate declaration when errorRecovery enabled

### ISSUE THREAD

**Issue by coderaiser** [babel/babel#12950]
## Bug Report

- [ ] I would like to work on a fix!

Can be related to #8262

**Current behavior**

- [REPL](https://babel.dev/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo may increase triaging priority!

**Input Code**

```js
const { parse} = require("@babel/parser");
const traverse = require('@babel/traverse').default

const ast = parse("let a;let a", {
    errorRecovery: true
});

traverse(ast, {});
```

throws:

```js
/Users/coderaiser/putout/node_modules/@babel/traverse/lib/scope/index.js:427
      throw this.hub.buildError(id, `Duplicate declaration "${name}"`, TypeError);
                     ^

TypeError: Cannot read property 'buildError' of undefined
    at Scope.checkBlockScopedCollisions (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/scope/index.js:427:22)
    at Scope.registerBinding (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/scope/index.js:587:16)
    at Scope.registerDeclaration (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/scope/index.js:529:14)
    at Object.BlockScoped (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/scope/index.js:246:12)
    at Object.newFn (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/visitors.js:216:17)
    at NodePath._call (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/path/context.js:38:14)
    at NodePath.visit (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitMultiple (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/context.js:80:17)
```

**Expected behavior**

Expected to see exception with text: `Duplicate declaration "a"`

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): [e.g. v7.12.0]
- Node/npm version: [e.g. Node 12/npm 7]
- OS: [e.g. macOS 10.15.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `webpack`, `rollup`, `parcel`, `babel-register`]

**Possible Solution**

**Additional context**

**Comment by coderaiser** [comment]
The thing is I need `scope` to get information about declared variables. When I change code according to https://github.com/babel/babel/issues/11350#issuecomment-644118606

```js
const {File} = require('@babel/core');
const {parse} = require("@babel/parser");
const traverse = require('@babel/traverse').default

const code = "let a; let a";
const ast = parse(code, {
    errorRecovery: true
});
const file = new File({filename: '__putout.js'}, {code, ast});
traverse(file, {});
```
It throws `Duplicate declaration "a"`.

But when I change code:

```diff
-const code = "let a; let a";
+const code = "let a;";
```

I get:

```js
   throw new Error("You must pass a scope and parentPath unless traversing a Program/File. " + `Instead of that you tried to traverse a ${parent.type} node without ` + "passing scope and parentPath.");
      ^

Error: You must pass a scope and parentPath unless traversing a Program/File. Instead of that you tried to traverse a undefined node without passing scope and parentPath.
    at traverse (/Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:53:13)
    at Object.<anonymous> (/Users/coderaiser/putout/packages/engine-parser/1.js:10:1)
```

Could you please tell me how could I get `scope` to pass it?

I got an idea to add auto-fix to [putout](https://github.com/coderaiser/putout): functions without `async` which uses `await`;

```diff
-const fn = () => await f();
+const fn = async () => await f();
```

And I see that it's parsed good with `errorRecovery: true`. Would be amazing to have ability to `traverse` such code with a scope. I can't find information about it in:
- https://babeljs.io/docs/en/babel-traverse
- [babel-handbook](https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#toc-babel-traverse).

**Comment by nicolo-ribaudo** [comment]
`@babel/traverse` expects to be called directly with an AST node. If you have a `File` intance, you can grab a reference to the `NodePath` containing the wrapped AST:
```js
const code = "let a";
const ast = parser.parse(code, {
  errorRecovery: true,
});
const file = new babel.File({ filename: "__putout.js" }, { code, ast });
file.path.traverse({
  Identifier(path) {
    console.log(path.toString());
  },
});
```

However, it seems like this won't work with `let a; let a` because `new File` constructs the scope information (I'm sorry we don't have much docs about this, I often have to try or read the source code to understand how things exactly work).

**Comment by coderaiser** [comment]
@nicolo-ribaudo could you please tell me where can I get `babel.File` from:

```js
const file = new babel.File({ filename: "__putout.js" }, { code, ast });
```

**Comment by nicolo-ribaudo** [comment]
It should be exported by `@babel/core`.
