### ISSUE TITLE
Import Typescript interface through path mapping cause error

### ISSUE THREAD

**Issue by zshlomyz** [babel/babel#13105]
Babel versions:
"@babel/core": "7.9.6",
 "@babel/plugin-proposal-class-properties": "7.7.4",
 "@babel/plugin-proposal-object-rest-spread": "7.9.0",
 "@babel/plugin-proposal-optional-chaining": "7.9.0",
 "@babel/plugin-transform-runtime": "7.9.0",
 "@babel/preset-env": "7.7.6",
 "@babel/preset-react": "7.7.4",
 "@babel/preset-typescript": "7.9.0",
 "@babel/runtime": "7.9.6",
 "babel-loader": "8.0.6",

compile using Webpack version 5.4.0

.babelrc:
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "corejs": 3
      }
    ],
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-transform-runtime"
  ]
}
```

The tsconfig contain path mapping configuration:
```
"compilerOptions": {
    "allowJs": true,
    "outDir": "./dist/",
    "module": "CommonJS",
    "target": "ES5",
    "sourceMap": false,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "jsx": "react",
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@generated/*": ["../../generated/*"]
    }
  },
  "exclude": [
    "node_modules",
    "dist",
    "webpack.config.js"
  ],
  "include": ["src/**/*", "./declarations.d.ts"]
}
```
The Webpack configuration also contain the same path mapping.

The imported file:
```
export interface Iinterface1 {
   x: string
}
```

At some React component I imported the interface like this:
```
import { Iinterface1 } from "@generated/Iinterface1";
   const y:Iinterface1 = { x: 'aaa' }
```

The error:
```

Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: <path_to_generated_code>\Iinterface1.ts: Support for the experimental syntax 'flow' isn't currently enabled (22:8):

> 1  | export interface Iinterface1  {
     |        ^
  2  |     x: string
  3  |     }

Add @babel/preset-flow (https://git.io/JfeDn) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://git.io/vb4yb) to the 'plugins' section to enable parsing.
    at Parser._raise (<path_to_repo>\node_modules\@babel\parser\lib\index.js:748:17)
    at Parser.raiseWithData (<path_to_repo>\node_modules\@babel\parser\lib\index.js:741:17)
    at Parser.expectOnePlugin (<path_to_repo>\node_modules\@babel\parser\lib\index.js:9112:18)
    at Parser.isExportDefaultSpecifier (<path_to_repo>\node_modules\@babel\parser\lib\index.js:12884:16)
    at Parser.maybeParseExportDefaultSpecifier (<path_to_repo>\node_modules\@babel\parser\lib\index.js:12785:14)
    at Parser.parseExport (<path_to_repo>\node_modules\@babel\parser\lib\index.js:12738:29)
    at Parser.parseStatementContent (<path_to_repo>\node_modules\@babel\parser\lib\index.js:11756:27)
    at Parser.parseStatement (<path_to_repo>\node_modules\@babel\parser\lib\index.js:11650:17)
    at Parser.parseBlockOrModuleBlockBody (<path_to_repo>\node_modules\@babel\parser\lib\index.js:12232:25)
    at Parser.parseBlockBody (<path_to_repo>\node_modules\@babel\parser\lib\index.js:12218:10)
 @ ./src/components/MyComp.tsx 32:0-104 34:22-72 316:15-65 357:15-65 410:17-67 530:19-69
 @ ./src/components/MyComp.tsx 14:0-56 54:90-109
 @ container entry ./MyComp[0]

webpack 5.9.0 compiled with 1 error in 7681 ms
i ｢wdm｣: Failed to compile.

```

Note - replacing the .babelrc file by putting the babel configuration inside the Webpack configuration file solve the issue.
Is it a bug?

Thanks

**Comment by JLHwung** [comment]
This is expected, `.babelrc` is _not_ applied to node_modules. If in doubt, we recommend using `babel.config.json`.

https://babeljs.io/docs/en/configuration#whats-your-use-case

**Comment by zshlomyz** [comment]
Hi,
But I don't want to compile the node modules (as mention at the link that you attached).
Just using it.
So why can't I use the `.babelrc` file?
Thanks

**Comment by JLHwung** [comment]
> You have a configuration that only applies to a single part of your project?

Besied node_modules, `.babelrc` is not applied to files outside of your project, in your cases, `../../generated/*`. Since it works if "putting the babel configuration inside the Webpack configuration", `babel.config.json` should work for you too.

You can also output the effective Babel config using `BABEL_SHOW_CONFIG_FOR`:

https://babeljs.io/docs/en/configuration#print-effective-configs

**Comment by zshlomyz** [comment]
Thanks!
