### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by gsklee** [babel/babel#1315]
```
TypeError: /home/kaylee/Projects/GitHub/gsklee/estraits/estraits.js: Cannot read property 'start' of undefined
    at Parser.pp.toAssignable (/home/kaylee/Projects/GitHub/gsklee/estraits/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/lval.js:29:56)
    at Parser.pp.toAssignableList (/home/kaylee/Projects/GitHub/gsklee/estraits/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/lval.js:75:19)
    at Parser.pp.parseArrowExpression (/home/kaylee/Projects/GitHub/gsklee/estraits/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:652:22)
    at Parser.pp.parseParenArrowList (/home/kaylee/Projects/GitHub/gsklee/estraits/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:462:15)
    at Parser.parseParenArrowList (/home/kaylee/Projects/GitHub/gsklee/estraits/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/plugins/flow.js:710:20)
    at Parser.pp.parseParenAndDistinguishExpression (/home/kaylee/Projects/GitHub/gsklee/estraits/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:427:19)
    at Parser.pp.parseExprAtom (/home/kaylee/Projects/GitHub/gsklee/estraits/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:338:19)
    at Parser.parseExprAtom (/home/kaylee/Projects/GitHub/gsklee/estraits/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:593:162)
    at Parser.pp.parseExprSubscripts (/home/kaylee/Projects/GitHub/gsklee/estraits/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
    at Parser.pp.parseMaybeUnary (/home/kaylee/Projects/GitHub/gsklee/estraits/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:199:19)
```

[Bugged Demo](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20f(...args)%20%7B%0A%20%20return%20args.forEach((%7Bconfig%2C%20...methods%7D)%20%3D%3E%20console.log(config%2C%20methods))%3B%0A%7D%0A%0Af(%7B%0A%20%20config()%20%7B%0A%20%20%20%20return%20'config'%3B%0A%20%20%7D%2C%0A%20%20%0A%20%20x()%20%7B%0A%20%20%20%20return%20'x'%3B%0A%20%20%7D%2C%0A%20%20%0A%20%20y()%20%7B%0A%20%20%20%20return%20'y'%3B%0A%20%20%7D%0A%7D%2C%20%7B%0A%20%20config()%20%7B%0A%20%20%20%20return%20'config'%3B%0A%20%20%7D%2C%0A%20%20%0A%20%20a()%20%7B%0A%20%20%20%20return%20'a'%3B%0A%20%20%7D%2C%0A%20%20%0A%20%20b()%20%7B%0A%20%20%20%20return%20'b'%3B%0A%20%20%7D%0A%7D)%3B)

It seems that the object rest/spread part is the cause of this problem ([Working Demo](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20f(...args)%20%7B%0A%20%20return%20args.forEach((%7Bconfig%2C%20x%7D)%20%3D%3E%20console.log(config%2C%20x))%3B%0A%7D%0A%0Af(%7B%0A%20%20config()%20%7B%0A%20%20%20%20return%20'config'%3B%0A%20%20%7D%2C%0A%20%20%0A%20%20x()%20%7B%0A%20%20%20%20return%20'x'%3B%0A%20%20%7D%2C%0A%20%20%0A%20%20y()%20%7B%0A%20%20%20%20return%20'y'%3B%0A%20%20%7D%0A%7D%2C%20%7B%0A%20%20config()%20%7B%0A%20%20%20%20return%20'config'%3B%0A%20%20%7D%2C%0A%20%20%0A%20%20a()%20%7B%0A%20%20%20%20return%20'a'%3B%0A%20%20%7D%2C%0A%20%20%0A%20%20b()%20%7B%0A%20%20%20%20return%20'b'%3B%0A%20%20%7D%0A%7D)%3B))

The bugged syntax used to work in v4.7.16 so I could only assume this to be a bug.

**Comment by sebmck** [comment]
Fixed as of 5.1.12, thanks!

**Comment by gsklee** [comment]
@sebmck :+1:

**Comment by geekyme** [comment]
this issue cropped up again for me 

```
Cannot read property 'start' of undefined
    at NodePath.errorWithNode (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/path/index.js:119:28)
    at NodePath.Scope (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/transformation/transformers/es6/constants.js:23:23)
    at NodePath.<anonymous> (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/visitors.js:190:17)
    at NodePath.call (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/path/context.js:122:26)
    at NodePath.visit (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/path/context.js:146:8)
    at TraversalContext.visitSingle (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/context.js:105:12)
    at TraversalContext.visit (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/context.js:117:19)
    at Function.traverse.node (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/index.js:67:17)
    at traverse (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/traversal/index.js:50:14)
    at TransformerPass.transform (/Users/shawnlim/Documents/react/Boa/node_modules/babel-core/lib/babel/transformation/transformer-pass.js:39:32)
```

**Comment by sebmck** [comment]
You probably aren't on latest. Upgrade and verify that it's still an issue please. That error is impossible to be thrown now as you can see [here](https://github.com/babel/babel/blob/master/src/babel/transformation/file/index.js#L403-409).

**Comment by geekyme** [comment]
i am using the latest versions. 

```
├─┬ babel@5.5.6
│ └── babel-core@5.5.6
└── babel-core@5.5.6
```

some other libraries peerDependencies problem?

**Comment by Rodeoclash** [comment]
I'm seeing this as well, I'm not convinced that it's a babel-js problem but rather another library that depends on it. Can you post your package.json?

**Comment by geekyme** [comment]
```
  "dependencies": {
    "autoprefixer-loader": "2.0.0",
    "axis": "0.4.0",
    "babel": "5.5.6",
    "babel-core": "5.5.6",
    "babel-loader": "5.1.4",
    "bluebird": "^2.9.25",
    "body-parser": "^1.12.2",
    "bootstrap-styl": "^4.0.4",
    "classnames": "2.1.2",
    "compression": "^1.4.3",
    "cookie-parser": "^1.3.4",
    "css-loader": "0.14.4",
    "csurf": "^1.7.0",
    "debug": "^2.1.3",
    "expose-loader": "0.7.0",
    "express": "4.12.4",
    "extract-text-webpack-plugin": "0.8.1",
    "fastclick": "^1.0.6",
    "favicon": "0.0.2",
    "file-loader": "0.8.4",
    "fluxible": "0.4.10",
    "fluxible-action-utils": "^0.2.1",
    "fluxible-plugin-fetchr": "0.3.1",
    "fluxible-router": "0.1.7",
    "font-awesome-stylus": "^4.3.0",
    "gulp": "^3.8.11",
    "gulp-awspublish": "0.0.23",
    "gulp-cloudfront": "0.0.14",
    "gulp-load-plugins": "^0.7.1",
    "i18n-abide": "0.0.22",
    "immutable": "3.7.3",
    "intl": "^0.1.4",
    "jsxgettext": "^0.7.0",
    "locale": "0.0.20",
    "lodash": "3.9.3",
    "morgan": "^1.5.2",
    "newrelic": "1.20.0",
    "node-libs-browser": "^0.5.0",
    "qs": "3.1.0",
    "raven": "0.7.3",
    "react": "0.13.3",
    "react-bootstrap": "0.23.2",
    "react-doc-meta": "^0.2.0",
    "react-document-title": "^1.0.2",
    "react-intl": "^1.2.0",
    "require-dir": "^0.3.0",
    "serialize-javascript": "^1.0.0",
    "serve-favicon": "^2.2.0",
    "strip-loader": "^0.1.0",
    "style-loader": "0.12.3",
    "stylus-loader": "1.2.0",
    "superagent": "^1.2.0",
    "url-loader": "^0.5.5",
    "webpack": "1.9.10",
    "webpack-dev-server": "1.9.0"
  },
  "devDependencies": {
    "babel-eslint": "3.1.9",
    "babel-plugin-rewire": "0.1.3",
    "eslint": "^0.21.2",
    "eslint-plugin-react": "^2.3.0",
    "esprima-fb": "^15001.1.0-dev-harmony-fb",
    "heapdump": "^0.3.5",
    "jasmine-core": "^2.2.0",
    "jscs": "^1.13.1",
    "karma": "^0.12.31",
    "karma-chrome-launcher": "^0.1.8",
    "karma-cli": "0.0.4",
    "karma-commonjs": "0.0.13",
    "karma-firefox-launcher": "^0.1.4",
    "karma-jasmine": "^0.3.5",
    "karma-jasmine-html-reporter": "^0.1.8",
    "karma-safari-launcher": "^0.1.1",
    "karma-sourcemap-loader": "^0.3.4",
    "karma-webpack": "^1.5.0",
    "react-hot-loader": "1.2.7",
    "react-tools": "^0.13.2",
    "rewire": "^2.3.1",
    "rewire-webpack": "^1.0.0",
    "stylint": "^0.9.9",
    "webpack-dev-server": "^1.8.0"
  }
```

**Comment by damassi** [comment]
This is now happening to me as well, and I just upgraded to the latest:
```
ERROR in ./src/entry.js
Module build failed: TypeError: /Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/src/entry.js: Cannot read property 'start' of undefined
    at NodePath.errorWithNode (/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/node_modules/babel-core/lib/babel/traversal/path/index.js:119:28)
    at NodePath.Scope (/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/node_modules/babel-core/lib/babel/transformation/transformers/es6/constants.js:23:23)
    at NodePath.<anonymous> (/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/node_modules/babel-core/lib/babel/traversal/visitors.js:190:17)
    at NodePath.call (/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/node_modules/babel-core/lib/babel/traversal/path/context.js:122:26)
    at NodePath.visit (/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/node_modules/babel-core/lib/babel/traversal/path/context.js:146:8)
    at TraversalContext.visitSingle (/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/node_modules/babel-core/lib/babel/traversal/context.js:105:12)
    at TraversalContext.visit (/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/node_modules/babel-core/lib/babel/traversal/context.js:117:19)
    at Function.traverse.node (/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/node_modules/babel-core/lib/babel/traversal/index.js:67:17)
    at traverse (/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/node_modules/babel-core/lib/babel/traversal/index.js:50:14)
    at TransformerPass.transform (/Users/damassi/Sites/Kindling/kindlingdev/development/kindlingapp/frontend/node_modules/babel-core/lib/babel/transformation/transformer-pass.js:39:32)  
```

**Comment by sebmck** [comment]
I cannot reproduce anything without the source code for the file it's erroring on.

**Comment by damassi** [comment]
This is one of those "where to begin" type of things?  There's no pointers in the source to the problem, but if this helps:

```javascript
import "babel/polyfill";

import 'underscore-wrapper';
import 'jquery-wrapper';
import 'underscore-wrapper';
import 'backbone-wrapper';
import 'datepicker-wrapper';
import 'moment-wrapper';
import 'handlebars-wrapper';

// IE8 matchMedia polyfill
import 'matchMedia';
import 'matchMedia.addListener';

// Set up custom helpers and modules incompatable with module systems
import 'utils/polyfills';
import 'script!vendor/scripts/highcharts/adapters/standalone-framework.src.js';
import 'script!vendor/scripts/highcharts/highcharts.src.js';

// Kick off the application
import $ from 'jquery';
import ie8Icons from 'utils/ie8-icons';
import UserModel from 'models/user';

const user = UserModel.getCurrent();
const moduleName = user && user.inState('activated') ? 'inside' : 'outside';

// Main app entryPoint
if (moduleName === 'inside') {
  require.ensure([], function() {
    require('inside')();
  });
}

// Login or register entryPoint
else if (moduleName === 'outside') {
  require.ensure([], function() {
    require('outside')();
  });
}

$(() => ie8Icons.fix());
```

**Comment by sebmck** [comment]
Is that the source to `./src/entry.js`? (That's the file it's erroring on) Because if so, that compiles fine for me.

**Comment by damassi** [comment]
It is.  That's what I mean, it doesn't *seem* to be a babel problem, but literally this morning the exact error appeared that @geekyme spoke about above.  Somewhat at a loss.

**Comment by damassi** [comment]
@geekyme - did you ever figure out the issue?

**Comment by geekyme** [comment]
no. basically my app is running perfectly fine. But when I run my unit tests it failed with all the above errors. I'm using this babel plugin to do mocking https://github.com/speedskater/babel-plugin-rewire

**Comment by damassi** [comment]
Oh man, that must be it; i'm using that too

**Comment by geekyme** [comment]
its dependencies are : 

```
  "devDependencies": {
    "expect.js": "^0.3.1",
    "mocha": "^2.2.4"
  },
  "peerDependencies": {
    "babel-core": ">=5.2.0"
  },

```

**Comment by damassi** [comment]
For anyone arriving at this issue, it was indeed `babel-plugin-rewire`.  Once I commented it out everything built as it should.  What a game of cat and mouse Rewire has been the past few months!

**Comment by speedskater** [comment]
It seems to depend on babel-core version 5.5.6. The babel-plugin-rewire unit tests fail in this version as well. With previous versions (e.g. 5.3.1) these unit tests passed. I start to investigate this problem. @sebmck do you have any hint?

**Comment by sebmck** [comment]
Not off the top of my head. Also FYI [this](https://github.com/speedskater/babel-plugin-rewire/blob/master/src/babel-plugin-rewire.js#L17-19) is incredibly dangerous as nodes are mutated and this will cause severe memory leaks.

**Comment by speedskater** [comment]
@sebmck thanks for the hint regarding this concern. What would be the safe way of doing this?

**Comment by sebmck** [comment]
Creating it each time.

**Comment by speedskater** [comment]
@sebmck Thanks for the hint. Removed the global identifiers.
Furthermore fixed the original issue (https://github.com/speedskater/babel-plugin-rewire/issues/10) resulting in "Cannot read property 'start' of undefined". The failure was that I was renaming variables without using the appropriate api on the scope.

**Comment by speedskater** [comment]
I tracked the issue down to the situation when using a plugin to replace constants or module declarations with variables and accompanying functions mutating them. Although it is possible to replace the constant or module declaration with a single variable declaration. 

The problem can be reproduced with the following sample plugin

```js
var Transformer = require("babel-core").Transformer;
var t           = require("babel-core").types;

module.exports = new Transformer("import-to-variable", {
	ImportDeclaration: function(node, parent, scope, file) {
		var variableDeclarations = [];
		var mutators = [];

		node.specifiers.forEach(function(specifier) {
			var importedSpecifierName = (specifier.imported && specifier.imported.name) || null;
			var localVariable = specifier.local;
			var localVariableName = localVariable.name;
			
			variableDeclarations.push(t.variableDeclaration('let', [ t.variableDeclarator(t.identifier(localVariableName), t.literal(localVariableName))]));

			mutators.push(t.functionDeclaration(
					t.identifier('mutatingFunction'),
					[t.identifier("value")],
					t.blockStatement([
					t.expressionStatement(t.assignmentExpression("=", t.identifier(localVariableName), t.identifier("value")))
				])
			));
		});

		return variableDeclarations.concat(mutators);
	}
});
```

When trying to transform the following snippet:

```js
import a from 'b';
```

the "Module build failed: TypeError: 'Cannot read property 'start' of undefined" occurs.

@sebmck Is this a babel issue or is it the wrong way to write such a plugin?

**Comment by sebmck** [comment]
You're reassigning a constant (eg. an import).

**Comment by speedskater** [comment]
Thats true, but after the transformation there is no constant anymore. Therefore imho I should be able to reassign the value.
