### ISSUE TITLE
[Bug]: Edge-case exception while printing single-parameter arrow function

### ISSUE THREAD

**Issue by Zalathar** [babel/babel#13198]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const { parse } = require("@babel/parser");
const t = require("@babel/types");
const { default: generate } = require("@babel/generator");

// Create an identifier with a location and a leading comment.
const param = parse("(/*x*/ a)").program.body[0].expression;

// Create an async arrow function without a location.
const ast = t.arrowFunctionExpression(
    [param],
    t.identifier("a"),
    /* async */ true,
);

// TypeError: Cannot read property 'start' of undefined
generate(ast);
```

### Current and expected behavior

Expected: Babel generates valid output source for the AST.

Actual:
```
$ yarn node repro.js 
/Users/user/babel/packages/babel-generator/lib/generators/methods.js:137
      if (firstParam.loc && firstParam.loc.start.line > node.loc.start.line) {
                                                                 ^

TypeError: Cannot read property 'start' of undefined
    at Generator.ArrowFunctionExpression (/Users/user/babel/packages/babel-generator/lib/generators/methods.js:137:66)
    at /Users/user/babel/packages/babel-generator/lib/printer.js:287:19
    at Buffer.withSource (/Users/user/babel/packages/babel-generator/lib/buffer.js:188:28)
    at Generator.withSource (/Users/user/babel/packages/babel-generator/lib/printer.js:153:15)
    at Generator.print (/Users/user/babel/packages/babel-generator/lib/printer.js:286:10)
    at Generator.generate (/Users/user/babel/packages/babel-generator/lib/printer.js:45:10)
    at Generator.generate (/Users/user/babel/packages/babel-generator/lib/index.js:26:18)
    at generate (/Users/user/babel/packages/babel-generator/lib/index.js:100:14)
    at Object.<anonymous> (/Users/user/babel/repro.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
```

### Environment

- Current Babel main (fb908fd87e1bf8a5ebe2c881c0baab1488c917e7)

### Possible solution

Originally I was planning to PR an additional null check, but on closer inspection (and in light of #13136) I think it makes more sense to get rid of all this special-case code and just delegate to the regular param-printing code.

**Comment by nicolo-ribaudo** [comment]
Yeah let's just remove that code at this point
