### ISSUE TITLE
[Bug]: Unexpected error thrown

### ISSUE THREAD

**Issue by fisker** [babel/babel#13322]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
require("@babel/parser").parse('<div propA={[ key: value ]} propsB={(a: b)} />', {sourceType: 'module', errorRecovery:true, plugins: ['jsx', 'typescript'], tokens: true})
Uncaught TypeError: Cannot read property 'type' of undefined
    at babel7CompatTokens (<CWD>\node_modules\@babel\parser\lib\index.js:12432:17)
    at Object.parseTopLevel (<CWD>\node_modules\@babel\parser\lib\index.js:12466:44)
    at Object.parse (<CWD>\node_modules\@babel\parser\lib\index.js:14186:10)
    at Object.parse (<CWD>\node_modules\@babel\parser\lib\index.js:7925:18)
    at Object.parse (<CWD>\node_modules\@babel\parser\lib\index.js:14238:38)
```

### Current and expected behavior

Should throw `SyntaxError`

### Environment

Babel version: 7.14.2

### Additional context

Prettier PR https://github.com/prettier/prettier/pull/10898

**Comment by fisker** [comment]
This code was added in https://github.com/babel/babel/pull/12221/files, but didn't test on `errorRecovery:true` mode.

**Comment by fedeci** [comment]
On [astexplorer](https://astexplorer.net/#/gist/955d01f8823a54291bdeb034448090c0/119e336bd650b6a425291d2bd1e43f74bfbdf49e) which is using `v7.13.9` it works correctly, so the regression may have not been introduced in #12221
