### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PDOG099** [babel/babel#13441]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

at first it said could not find 'babel-register'. I then added a coma somewhere it had been left out thinking it would fix my problem. I then encountered this and can not find answers online.

private/var/root/blockchain-project1/truffle-config.js:22
  compilers: {
  ^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Object.require (internal/modules/cjs/helpers.js:25:18)
    at Function.load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:161:1)
    at Function.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:150:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/compile.js:68:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/cli.js:51:1)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:89:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
Truffle v5.1.39 (core: 5.1.39)

### Configuration file name

.babelrc

### Current and expected behavior

it should create a contract and an ABI file in sublime - instead it says 'syntax error - unexpected identifier'

### Environment

node - 10.16.3
npm - 6.9.0
truffle - 5.1.39

**Comment by nicolo-ribaudo** [comment]
Can you share the contents of `private/var/root/blockchain-project1/truffle-config.js`?
