### ISSUE TITLE
Babel 5 no longer accepts HTML comments in JSX blocks

### ISSUE THREAD

**Issue by brianhawthorne** [babel/babel#1346]
```
% echo '<div><!-- comment --></div>' | babel

/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
SyntaxError: unknown: Unexpected token (1:6)
> 1 | <div><!-- comment --></div>
    |       ^
  2 | 
    at Parser.pp.raise (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:68:13)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.jsx_parseIdentifier (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:427:124)
    at Parser.pp.jsx_parseNamespacedName (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:436:19)
    at Parser.pp.jsx_parseElementName (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:449:19)
    at Parser.pp.jsx_parseOpeningElementAt (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:523:20)
    at Parser.pp.jsx_parseElementAt (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:545:29)
    at Parser.pp.jsx_parseElementAt (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:558:30)
    at Parser.pp.jsx_parseElement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:587:15)
    at Parser.parseExprAtom (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/jsx.js:593:125)
```

**Comment by sebmck** [comment]
Has it ever?

**Comment by brianhawthorne** [comment]
Hmm - looks like I was under the mistaken impression that babel 4.0.1 was successfully compiling an html comment in a jsx block, and only began to fail when I upgraded to v5.  My mistake - sorry for the noise!
