### ISSUE TITLE
[Bug]: Cannot read property 'slice' of undefined, only when @babel/plugin-proposal-nullish-coalescing-operator babel plugin used

### ISSUE THREAD

**Issue by dennisat** [babel/babel#13494]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

This is an imported dependency, `node_modules/@react-leaflet/core/cjs/path.js`.

```
"use strict";

exports.__esModule = true;
exports.usePathOptions = usePathOptions;
exports.createPathHook = createPathHook;

var _react = require("react");

var _context = require("./context");

var _events = require("./events");

var _layer = require("./layer");

var _pane = require("./pane");

function usePathOptions(element, props) {
  const optionsRef = (0, _react.useRef)();
  (0, _react.useEffect)(function updatePathOptions() {
    if (props.pathOptions !== optionsRef.current) {
      const options = props.pathOptions ?? {};     // <-- BABEL's plugin is called to replace this nullish coalescing operator
      element.instance.setStyle(options);
      optionsRef.current = options;
    }
  }, [element, props]);
}

function createPathHook(useElement) {
  return function usePath(props) {
    const context = (0, _context.useLeafletContext)();
    const elementRef = useElement((0, _pane.withPane)(props, context), context);
    (0, _events.useEventHandlers)(elementRef.current, props.eventHandlers);
    (0, _layer.useLayerLifecycle)(elementRef.current, context);
    usePathOptions(elementRef.current, props);
    return elementRef;
  };
}
```

### Webpack configuration

The problem occurs when I add the `@babel/plugin-proposal-nullish-coalescing-operator` in the webpakc config.

```
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          "@babel/plugin-proposal-nullish-coalescing-operator", 
          'babel-loader',
        ],
      },
...
```

### Current and expected behavior

# Current
On `webpack` we get this error

```
...
[./src/index.tsx] 23.2 KiB {main} [built]
    + 295 hidden modules

ERROR in /Users/user/dev/my-company/my-project/node_modules/react/index.js
Module build failed (from /Users/user/dev/my-company/my-project/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js):
TypeError: Cannot read property 'slice' of undefined
    at throwVersionError (/Users/user/dev/my-company/my-project/node_modules/@babel/helper-plugin-utils/lib/index.js:75:15)
    at Object.assertVersion (/Users/user/dev/my-company/my-project/node_modules/@babel/helper-plugin-utils/lib/index.js:28:5)
    at /Users/user/dev/my-company/my-project/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js:19:7
    at Object.<anonymous> (/Users/user/dev/my-company/my-project/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12)
 @ ./src/Accordion/Accordion.tsx 10:12-28 12:14-30
 @ ./src/index.tsx
 @ multi ./src/index.tsx

... // And many errors like this 
```

# Expected
No error

## System info
  System:
    OS: macOS 11.4
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.19.0/bin/yarn
    npm: 7.12.0 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.10

## Babel related packages versions
    "@babel/cli": "^7.13.16",
    "@babel/core": "^7.14.6",
    "@babel/plugin-syntax-nullish-coalescing-operator": "^7.8.3",
    "@babel/preset-env": "^7.14.5",
    "@babel/preset-react": "^7.14.5",
    "babel-jest": "^27.0.2",
    "babel-loader": "^8.2.2",
    "babel-preset-minify": "^0.5.1",
    "babel-preset-react-app": "^10.0.0",

### Additional context

Investigation
===
Digging I found that this error occurred in `node_modules/@babel/helper-plugin-utils/lib/index.js` in this function:

```
function throwVersionError(range, version) {
  if (typeof range === "number") {
    if (!Number.isInteger(range)) {
      throw new Error("Expected string or integer value.");
    }

    range = `^${range}.0.0-0`;
  }

  if (typeof range !== "string") {
    throw new Error("Expected string or integer value.");
  }

  const limit = Error.stackTraceLimit;

  if (typeof limit === "number" && limit < 25) {
    Error.stackTraceLimit = 25;
  }

  let err;

  if (version.slice(0, 2) === "7.") { // <-- AND AT THIS LINE, the `version` is undefined!

    err = new Error(`Requires Babel "^7.0.0-beta.41", but was loaded with "${version}". ` + `You'll need to update your @babel/core version.`);
  } else {
    err = new Error(`Requires Babel "${range}", but was loaded with "${version}". ` + `If you are sure you have a compatible version of @babel/core, ` + `it is likely that something in your build process is loading the ` + `wrong version. Inspect the stack trace of this error to look for ` + `the first entry that doesn't mention "@babel/core" or "babel-core" ` + `to see what is calling Babel.`);
  }

  if (typeof limit === "number") {
    Error.stackTraceLimit = limit;
  }

  throw Object.assign(err, {
    code: "BABEL_VERSION_UNSUPPORTED",
    version,
    range
  });
}
```

**Comment by nicolo-ribaudo** [comment]
`@babel/plugin-proposal-nullish-coalescing-operator` is not a webpack plugin, it's a Babel plugin. You need to move it from your webpack config to your Babel config, or to the Babel options inside the Webpack config as in https://github.com/babel/babel-loader#usage.
