### ISSUE TITLE
Cannot find module 'babel-core' after make bootstrap

### ISSUE THREAD

**Issue by natew** [babel/babel#1357]
Attempting to contribute and running the setup "make bootstrap" (really sudo make bootstrap for my machine). It runs fine but when I try to run babel I get:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nw/projects/flint/babel/packages/babel-cli/bin/babel/index.js:4:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

It seems the symlink in packages/babel-cli isn't noticed. I tried running with a few different node versions with the same errors. Tried uninstalling globally and reinstalling as well.

Running:
```
npm list --global --depth 1 babel
/usr/local/lib
├─┬ babel@5.1.13  -> /Users/nw/projects/github/babel/packages/babel-cli
│ └── babel-core@5.1.13  (babel) invalid extraneous
├─┬ babel-core@5.1.13 -> /Users/nw/projects/github/babel
│ └── babel@4.7.13 
```

**Comment by sebmck** [comment]
Try running `$ npm link` in the root then `cd`ing into `packages/babel-cli` and running `$ npm link babel-core`.

**Comment by natew** [comment]
Ran link again and then:

``` 
➜  babel git:(master) ✗ cd packages/babel-cli 
➜  babel-cli git:(master) ✗ sudo npm link babel-core
unbuild babel-core@5.1.13
/Users/nw/projects/flint/babel/packages/babel-cli/node_modules/babel-core -> /usr/local/lib/node_modules/babel-core -> /Users/nw/projects/flint/babel
➜  babel-cli git:(master) ✗ babel
module.js:338
    throw err;
          ^
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nw/projects/flint/babel/packages/babel-cli/bin/babel/index.js:4:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
➜  babel-cli git:(master) ✗ npm list --global --depth 1 babel 
/usr/local/lib
├─┬ babel@5.1.13  -> /Users/nw/projects/flint/babel/packages/babel-cli
│ └── babel-core@5.1.13  (babel) invalid extraneous
├─┬ babel-core@5.1.13 -> /Users/nw/projects/flint/babel
│ └── babel@4.7.13 
├─┬ reapp-component@1.0.2 -> /Users/nw/projects/reapp/reapp-component
│ └── babel@4.7.16 
├─┬ reapp-kit@1.2.13 -> /Users/nw/projects/reapp/reapp-kit
│ └── babel@5.0.7 
├─┬ reapp-pack@1.3.24 -> /Users/nw/projects/reapp/reapp-pack
│ └── babel@5.0.2 
├─┬ reapp-routes@0.10.10 -> /Users/nw/projects/reapp/reapp-routes
│ └── babel@5.0.7 
└─┬ reapp-ui@0.12.51 -> /Users/nw/projects/reapp/reapp-ui/build
  └── babel@5.0.12 

npm ERR! extraneous: babel-core@5.1.13 /usr/local/lib/node_modules/babel/node_modules/babel
npm ERR! invalid: babel-core@5.1.13 /usr/local/lib/node_modules/babel/node_modules/babel
```

**Comment by monsanto** [comment]
I think the issue is that you need to build the package after linking. Just do `make`

**Comment by natew** [comment]
In babel root?

```
➜  babel git:(master) ✗ make
node node_modules/babel/bin/babel src --out-dir lib --copy-files
module.js:338
    throw err;
          ^
Error: Cannot find module '../internal/assignWith'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nw/projects/flint/babel/node_modules/lodash/object/assign.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
make: *** [build-core] Error 1
```

**Comment by sebmck** [comment]
There's something wrong with your setup. `lodash` shouldn't be throwing an error under any circumstance.

**Comment by natew** [comment]
Hm. Have all sorts of stuff working without problem. I did just try and switch node versions because this wasn't working originally so maybe I added to the problem. Going to blow it away and retry.

**Comment by sebmck** [comment]
I mean, just the `node_modules` might be bad.

**Comment by monsanto** [comment]
I can confirm on a fresh repo, running babel after `make bootstrap` will result in the original error you posted, and `make` afterwards will make it work.

We should probably have `make bootstrap` run build-core after linking

**Comment by natew** [comment]
Apologies, I thought I had run watch-core in another window but I had copied in the `$` so it didn't run. Wups.

Thanks guys.
