### ISSUE TITLE
[Bug]: Babel doesn't process module react-native-vector-icons on latest version, doesn't apply configuration

### ISSUE THREAD

**Issue by Phazoning** [babel/babel#13757]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

This is the module that is crashing, [react-native-vector-icons][1]

[1]: https://github.com/oblador/react-native-vector-icons

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset', '@babel/preset-react'],
  plugins: ['react-native-config-node/transform']
};
```

### Current and expected behavior

# Expected 

Babel processes the module

# What it's doing

Babel raises the following error when doing the webpack (see additional context for full details)

```
C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\react-native-vector-icons\lib\create-icon-set.js: Support
for the experimental syntax 'jsx' isn't currently enabled (92:9):

  90 |
  91 |       return (
>92 |         <Text {...props}>
     |         ^
  93 |           {glyph}
  94 |           {children}
  95 |         </Text>

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable
parsing.

```

### Environment

System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.9.6 => 7.12.16
    @babel/preset-env: ^7.15.4 => 7.15.4
    @babel/preset-react: ^7.14.5 => 7.14.5
    @babel/runtime: ^7.9.6 => 7.12.13
    babel-jest: ^26.0.1 => 26.6.3
    babel-preset-react: ^6.24.1 => 6.24.1
    eslint: ^6.8.0 => 6.8.0
    jest: ^26.0.1 => 26.6.3
    metro-react-native-babel-preset: ^0.59.0 => 0.59.0
    react-native: ^0.63.4 => 0.63.4

### Additional context

+ I'm running Babel as part of Docz, which uses Gatsby
+ The error arises on doing the webpack (yarn docz build)
+ The error arises **only** when importing a component into a .md/x file
+ The faulty module doesn't have a .babelrc file of its own, yet doesn't seem to use the global config
+ Another module, react-native-gesture-handler raised the same error, yet it was corrected upon updating it

**Comment by JLHwung** [comment]
Can you attach the [effective config](https://babeljs.io/docs/en/configuration#print-effective-configs)?
```
BABEL_SHOW_CONFIG_FOR C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\react-native-vector-icons\lib\create-icon-set.js your build command
```

**Comment by Phazoning** [comment]
I cannot manage to do it. Excuse if it seems too simple, but I haven't been with this for long. With build command you mean the node command as in the tutorial (which end up becoming on my case "react-native start", or the command to build the docz site?

**Comment by nicolo-ribaudo** [comment]
It should be the command you run in order to get the error you posted.

Btw, depending on the shell you are using you need a different syntax to set the enable the `BABEL_SHOW_CONFIG_FOR` variable: https://babeljs.io/docs/en/configuration#print-effective-configs

**Comment by Phazoning** [comment]
So, doing that on powershell, I get the following error:


> $env:BABEL_SHOW_CONFIG_FOR="./node_modules/react-native-vector-icons/lib/create-icon-set.js"; npm run docs-build 
```
> build
> gatsby build "--prefix-paths"


 ERROR

Error while initializing babel in docz:  Error: ENOENT: no such file or directory, stat
'C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\.docz\node_modules\react-native-vector-icons\lib\create-icon-set.js'
    at Object.statSync (fs.js:1086:3)
    at Object.sync (C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\gensync\index.js:182:19)
    at Object.stat (C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\gensync\index.js:210:24)
    at Generator.next (<anonymous>)
    at resolveShowConfigPath (C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\react-docgen\node_modules\@ba
bel\core\lib\config\files\configuration.js:310:29)
    at resolveShowConfigPath.next (<anonymous>)
    at loadPrivatePartialConfig (C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\react-docgen\node_modules\
@babel\core\lib\config\partial.js:94:66)
    at loadPrivatePartialConfig.next (<anonymous>)
    at Function.<anonymous> (C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\react-docgen\node_modules\@bab
el\core\lib\config\partial.js:149:25)
    at Generator.next (<anonymous>)
    at evaluateSync (C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\gensync\index.js:251:28)
    at Function.sync (C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\gensync\index.js:89:14)
    at Object.<anonymous> (C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\react-docgen\node_modules\@babel
\core\lib\config\index.js:46:61)
    at buildOptions
(C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\react-docgen\dist\babelParser.js:44:31)
    at buildParse (C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\react-docgen\dist\babelParser.js:62:22)
    at Object.<anonymous> (C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\docz-core\dist\index.js:1576:13)
 {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\Users\\AlonsoMorenasDiaz\\Desktop\\ctica\\smitom\\.docz\\node_modules\\react-native-vector-icons\\lib\\crea
te-icon-set.js'
}


 ERROR #10123  CONFIG

We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.



  Error: Error: ENOENT: no such file or directory, stat 'C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\.docz\node_modu
  les\react-native-vector-icons\lib\create-icon-set.js'

  - index.js:1582 Object.<anonymous>
    [smitom]/[docz-core]/dist/index.js:1582:9

  - v8-compile-cache.js:192 Module._compile
    [smitom]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - loader.js:1092 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1092:10

  - loader.js:928 Module.load
    internal/modules/cjs/loader.js:928:32

  - loader.js:769 Function.Module._load
    internal/modules/cjs/loader.js:769:14

  - loader.js:952 Module.require
    internal/modules/cjs/loader.js:952:19

  - v8-compile-cache.js:159 require
    [smitom]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - parseConfig.js:1 Object.<anonymous>
    [smitom]/[gatsby-theme-docz]/lib/utils/parseConfig.js:1:111

  - v8-compile-cache.js:192 Module._compile
    [smitom]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - loader.js:1092 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1092:10

  - loader.js:928 Module.load
    internal/modules/cjs/loader.js:928:32

  - loader.js:769 Function.Module._load
    internal/modules/cjs/loader.js:769:14

  - loader.js:952 Module.require
    internal/modules/cjs/loader.js:952:19

  - v8-compile-cache.js:159 require
    [smitom]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - gatsby-config.js:2 Object.<anonymous>
    [smitom]/[gatsby-theme-docz]/gatsby-config.js:2:27

  - v8-compile-cache.js:192 Module._compile
    [smitom]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30


not finished open and validate gatsby-configs - 1.122s
```

I've manually checked and the file exists in the path and the path leads you correctly to the file. Also, it raises the same error when using the other backlash

**Comment by nicolo-ribaudo** [comment]
Can you try with the absolute path?
```
$env:BABEL_SHOW_CONFIG_FOR="C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\react-native-vector-icons\lib\create-icon-set.js"; npm run docs-build
```

**Comment by Phazoning** [comment]
When I do that the output is this:

```
Babel configs on
"C:\Users\AlonsoMorenasDiaz\Desktop\ctica\smitom\node_modules\react-native-vector-icons\lib\create-icon-set.js"
(ascending priority):
programmatic options from babel-loader
{
  "babelrc": false,
  "configFile": false,
  "compact": false,
  "presets": [
    [
      "C:\\Users\\AlonsoMorenasDiaz\\Desktop\\ctica\\smitom\\node_modules\\gatsby\\node_modules\\babel-preset-gatsby\\de
pendencies.js",
      {
        "stage": "build-javascript"
      }
    ]
  ],
  "sourceMaps": false,
  "filename": "C:\\Users\\AlonsoMorenasDiaz\\Desktop\\ctica\\smitom\\node_modules\\react-native-vector-icons\\lib\\creat
e-icon-set.js",
  "sourceFileName": "C:\\Users\\AlonsoMorenasDiaz\\Deskto
```

**Comment by nicolo-ribaudo** [comment]
It looks like you are using Webpack with `babel-loader`, and passing `configFile: false` to `babel-loader` which prevents it from loading `babel.config.js`

Or is there more output with more configs? (The one you posted is cropped)

**Comment by Phazoning** [comment]
You're right, I didn't notice. I've edited the comment with a full output. Also, no other config araises, but a shortened version of that one

```
{
  "babelrc": false,
  "configFile": false,
  "compact": false,
  "presets": [
    [
      "C:\\Users\\AlonsoMorenasDiaz\\Desktop\\ctica\\smitom\\node_modules\\gatsby\\node_modules\\babel-preset-gatsby\\dependencies.js",
      {
        "stage": "build-javascript"
      }
    ]
  ],
  "sourceMaps": false,
  "filename": "C:\\Users\\AlonsoMorenasDiaz\\Desktop\\ctica\\smitom\\node_modules\\react-native-vector-icons\\lib\\create-icon-set.js",
  "sourceFileName": "C:\\Users\\AlonsoMorenasDiaz\\Desktop\\ctica\\smitom\\node_modules\\react-native-vector-icons\\lib\\create-icon-set.js",
  "caller": {
    "name": "babel-loader",
    "target": "web",
    "supportsStaticESM": true,
    "supportsDynamicImport": true,
    "supportsTopLevelAwait": true
  }
}
```

**Comment by liuxingbaoyu** [comment]
Since this issue is outdated, I will close it.
