### ISSUE TITLE
[Bug]: Error: Cannot find module 'node_modules\babel-loader\lib\index.js'

### ISSUE THREAD

**Issue by JeySamir** [babel/babel#13787]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

src/index.js
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import App from './components/App';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

serviceWorker.unregister();
```

### Configuration

package.json
```
"scripts": {
    "build": "webpack --config ./config/webpack.build.conf.js",
}
"devDependencies": {
    "@babel/core": "^7.7.4",
    "@babel/preset-env": "^7.7.4",
    "@babel/preset-react": "^7.14.5",
    "babel-loader": "^8.2.2",
    "webpack": "^5.53.0",
    "webpack-dev-server": "^4.2.1",
    "webpack-merge": "^5.8.0"
}
```

webpack.base.conf.js
```
module.exports = {
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: "babel-loader",
                    }
                ]
            },
...
```

.babelrc.json
```
module.exports = {
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ],
...
}
```

### Current and expected behavior

I'm trying to build my old working project, but it started throwing errors when building.
I tried to fix it by delete package-lock.json and node_modules. Also i removed all the Babel mentions in package.json.
After that, I execute:
```powershell
npm install -D babel-loader @babel/core @babel/preset-env webpack
npm install
```
But I still get an error when building.
```powershell
PS D:\projects\web\HSapp> npm run-script build

> HSapp@1.0.0 build D:\projects\web\HSapp
> webpack --config ./config/webpack.build.conf.js

ERROR in ../../../projects/web/HSapp/src/index.js
Module build failed (from ../../../projects/web/HSapp/node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'D:\projects\web\HSapp\node_modules\babel-loader\lib\index.js'
Require stack:
- D:\projects\web\HSapp\node_modules\loader-runner\lib\loadLoader.js
- D:\projects\web\HSapp\node_modules\loader-runner\lib\LoaderRunner.js
- D:\projects\web\HSapp\node_modules\webpack\lib\NormalModuleFactory.js
- D:\projects\web\HSapp\node_modules\webpack\lib\Compiler.js
- D:\projects\web\HSapp\node_modules\webpack\lib\webpack.js
- D:\projects\web\HSapp\node_modules\webpack\lib\index.js
- D:\projects\web\HSapp\node_modules\webpack-cli\lib\webpack-cli.js
- D:\projects\web\HSapp\node_modules\webpack-cli\lib\bootstrap.js
- D:\projects\web\HSapp\node_modules\webpack-cli\bin\cli.js
- D:\projects\web\HSapp\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (D:\projects\web\HSapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (D:\projects\web\HSapp\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (D:\projects\web\HSapp\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (D:\projects\web\HSapp\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule.doBuild (D:\projects\web\HSapp\node_modules\webpack\lib\NormalModule.js:781:3)
    at NormalModule.build (D:\projects\web\HSapp\node_modules\webpack\lib\NormalModule.js:928:15)
    at D:\projects\web\HSapp\node_modules\webpack\lib\Compilation.js:1322:12
```

I check file `D:\projects\web\HSapp\node_modules\babel-loader\lib\index.js`. It exist.
```powershell
...
Error: Cannot find module 'D:\projects\web\HSapp\node_modules\babel-loader\lib\index.js'
...
```

What could be the problem?
How to fix it?
The build output seems absolutely unrecognized.

### Environment

System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.6 - D:\nodejs\node.EXE
    npm: 6.14.15 - D:\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.7.4 => 7.15.5
    @babel/preset-env: ^7.7.4 => 7.15.6
    @babel/preset-react: ^7.14.5 => 7.14.5
    babel-loader: ^8.2.2 => 8.2.2
    babel-plugin-react-css-modules: ^5.2.6 => 5.2.6
    babel-runtime: ^6.26.0 => 6.26.0
    webpack: ^5.53.0 => 5.53.0

**Comment by JLHwung** [comment]
Can you share the whole webpack build configuration? For example, the contents of "webpack.build.conf.js".

**Comment by liuxingbaoyu** [comment]
I'll close it now due to inactivity for a long time, feel free to open a new issue if there are still problems.
