### ISSUE TITLE
[Bug]: babel crashes when destructuring, after using `for await` inside of async IIFE

### ISSUE THREAD

**Issue by danieltroger** [babel/babel#13801]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Code that reproduces the crash (only happens when targeting older engines like `IE 11`:

```
main();

async function main() {
  let is_done = false;
  const async_iterable = {
    [Symbol.asyncIterator]: () => ({
      next: () => {
        const promise = Promise.resolve({ value: "luv u", done: is_done });
        is_done = true;
        return promise;
      },
    }),
  };


  (async () => { // IIFE: required for babel to crash
    for await (const string of async_iterable) { // for await: required for babel to crash
      console.log(string);
    }
  })();

  const [one] = [1]; // array destructuring: required for babel to crash
}
```

[REPL link that also crashes](https://babeljs.io/repl/#?browsers=IE%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=LYQwlgdgFAlA3AKASAzgTwgYwAQDMCuWALmAPYTaiSzYDeC22ANgKZHZgoD6AJuS9gC8eEExQtEjTORTtUGTFzBEWAJxAAjVkLoNG2ANoBlNMA2kmAOnlYAkivVFSqgLoAubDUEA-T_X36ECwAHkQeXr7-AfrSELLYAA6qpMCcAsIACsmp4paqLCgWAG4sULTYRaL4LB4AREz4Rdj4tQA02HxBHpy8_NgAvvB60RzcnenYRKrVkiPY-UT4qhRJKWmzAf2twwMw24z9iEiMUDY4EXTYAPRX2La2AGIAoh75AI74YPk8eM7YGpoWExJqRsJh1CgABY7XB_EAAd3A7CgsXislUkAA5thSLhsGclA5NKwYJcbr9VPjEcpXiwPl8WD9YZSARogSCwRDoSNURYWJYmKRMVB0Vihps9INYEcpDJ2AZ-C4dAYAIwuODXW4gVTqNAdApTfCYRYYiCY2n074U_6A4FOTmoaH9BBAA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.15.7&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.js

### Configuration

Not relevant IMO since it also crashes in REPL. Target has to be set to `IE 11`.

### Current and expected behavior

Current behavior: `Property name expected type of string but got null`

Expected behavior: Code that prints `luv u` to the console when ran.

### Environment

- Babel: 7.15.7 (@babel/core 7.15.5)
- Node v16.9.1
- Yarn 3.0.2
- OS: macOS 10.15.7 (19H1323)

### Possible solution

Transpile the code correctly instead of crashing

### Additional context

I wrote code which was the reproduction code but with many more steps. Wanted to push it to a customer as a quick fix before my next calendar event. Babel crashed. Suck. Deployed only for modern browsers. Bored, offline on a flight I removed code bit for bit for bit for bit until I came up with the reproduction snippet. This is a very weird bug.

**Comment by JLHwung** [comment]
Duplicate of https://github.com/facebook/regenerator/issues/391

See also https://github.com/babel/babel/issues/11411 https://github.com/babel/babel/issues/10808.

I can not reproduce this issue on our fixture runner. I am investigating the REPL error.

**Comment by danieltroger** [comment]
> Duplicate of facebook/regenerator#391

I strongly disagree.
They're having set up issues with their config. For me, destructuring and everything is transpiled absolutely fine. I haven't changed my configuration in multiple months and transpiled hundreds of instances of destructuring. It's just this specific combination of destructuring, for await and an IIFE that triggers something. If I lift out the `for await` out of the IIFE there is no issue - showing that it's not (solely) the destructuring that triggers it.

Even if it was a duplicate of your mentioned issue, adding `@babel/plugin-transform-destructuring` would fix it, which it doesn't.

Both https://github.com/babel/babel/issues/11411 and https://github.com/babel/babel/issues/10808 transpile fine in my environment as well as in the REPL link that I provided.

Please investigate and I will eagerly await the results of your investigation.

**Comment by JLHwung** [comment]
The root cause is identical: In https://github.com/facebook/regenerator/blob/dbbddd9bd8c099ed1cdfcecdd077b8b4e7f43042/packages/transform/src/hoist.js#L29 the regenerator transform does not support any destructuring patterns.

It seems to me we have plugin ordering issues in babel-standalone, for unknown reasons the array pattern is seen here even though it should have been transformed since the hoisting is executed in `Function:exit` step.

> adding @babel/plugin-transform-destructuring would fix it, which it doesn't.

Are you using `preset-env`? Can you share a reproduction repo? I can reproduce on `babel-standalone` but not in `preset-env`.

**Comment by danieltroger** [comment]
> Are you using preset-env?

Yeah, but parcels. Pinging @mischnic for pro knowledge on that - I'm using babel within parcel.

> Can you share a reproduction repo?

Sure, try this: https://drive.google.com/file/d/1jjx7Fw8QJCeJfEJc5eDDU7tD74bB4vvC/view?usp=sharing

You will have to execute `yarn build` and have yarn installed as it uses yarn berry. I bundled everything for extra reproductionness (which is why the file is so big).

**Comment by mischnic** [comment]
It fails for me with

```json
{
  "presets": ["@babel/preset-env"]
}
```
and 
```json
{
  "dependencies": {
    "@babel/cli": "7.15.7",
    "@babel/core": "7.15.5",
    "@babel/preset-env": "7.15.6"
  }
}
```

when running babel via `yarn babel index.js` on 
```js
main();

async function main() {
  (async () => {
    // IIFE: required for babel to crash
    for await (const string of async_iterable) {
      // for await: required for babel to crash
      console.log(string);
    }
  })();

  const [one] = [1]; // array destructuring: required for babel to crash
}
```

```
$ node_modules/.bin/babel main.js
TypeError: main.js: Property name expected type of string but got null
    at validate (node_modules/@babel/types/lib/definitions/utils.js:158:13)
    at Object.validate (node_modules/@babel/types/lib/definitions/utils.js:227:7)
    at validateField (node_modules/@babel/types/lib/validators/validate.js:24:9)
    at validate (node_modules/@babel/types/lib/validators/validate.js:17:3)
    at builder (node_modules/@babel/types/lib/builders/builder.js:38:27)
    at Object.identifier (node_modules/@babel/types/lib/builders/generated/index.js:344:31)
    at node_modules/regenerator-transform/lib/hoist.js:32:29
    at Array.forEach (<anonymous>)
    at varDeclToExpr (node_modules/regenerator-transform/lib/hoist.js:29:23)
    at exit (node_modules/regenerator-transform/lib/hoist.js:51:20) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

**Comment by JLHwung** [comment]
Thanks. I can reproduce the error with these plugins now:
```jsonc
{
  "plugins": [
    "transform-destructuring",
    "transform-regenerator",
    "proposal-async-generator-functions" // pass when it is removed
  ],
  "externalHelpers": false // pass when plugin-external-helpers is removed. we enable external helpers in our own test suites by default
}
```

**Comment by JLHwung** [comment]
I think I have figured it out what's going wrong here.

The `proposal-async-generator-functions` plugin initiates a [sub-traversal from the Program node](https://github.com/babel/babel/blob/89cab4311ce6dea0090d5819a721a1269765d6ec/packages/babel-plugin-proposal-async-generator-functions/src/index.js#L95) in order to run before `async-to-generators`. In this traversal context, it does not have access to visitors defined by other plugins. It [visits the Function node `async function main() {}`](https://github.com/babel/babel/blob/89cab4311ce6dea0090d5819a721a1269765d6ec/packages/babel-plugin-proposal-async-generator-functions/src/index.js#L67) and [add `asyncIterators` helper for the for-await statements](https://github.com/babel/babel/blob/89cab4311ce6dea0090d5819a721a1269765d6ec/packages/babel-plugin-proposal-async-generator-functions/src/index.js#L35).

The `addHelper` utility does not respect the sub-traversal context, instead it [uses the Program node's context](https://github.com/babel/babel/blob/89cab4311ce6dea0090d5819a721a1269765d6ec/packages/babel-core/src/transformation/file/file.ts#L78), which is the top level context with visitors defined by all plugins. When `asyncIterators` helper is inserted before `async function main() {}`, the async function's traversal context is [changed to the Program's context](https://github.com/babel/babel/blob/89cab4311ce6dea0090d5819a721a1269765d6ec/packages/babel-traverse/src/path/modification.ts#L262) by `unshiftContainer`.

Now the net effect is: After the async function is visited by `traverse.node`,

https://github.com/babel/babel/blob/89cab4311ce6dea0090d5819a721a1269765d6ec/packages/babel-traverse/src/path/context.ts#L88-L97

its context is changed to the Program's context, in which the `regenerator-transform` registered [a `Function:exit` listener](https://github.com/facebook/regenerator/blob/055b4030219f7cc0af5999ef4431c991697d7ee5/packages/transform/src/visit.js#L47) to [turn all variable declarations to var-statements](https://github.com/facebook/regenerator/blob/055b4030219f7cc0af5999ef4431c991697d7ee5/packages/transform/src/visit.js#L105). The listener is immediately invoked by `this.call("exit")` which eventually brings out the error since at this time, the `transform-destructring` is never run (expected), but neither should `regenerator-transform` if only `addHelper` could respect the sub-traversal context.

In my local tests, we have similar issue within `this.call("enter")` and `traverse.node`, too. The traversal context could be changed by the `"enter"` listeners, too and they are in current test suites.

A conservative fix will be to manually restore context after `this.call("enter")` and `traverse.node`, but it surely impacts performance because most listeners do not change traversal context: except calling `unshiftContainer` / `pushContainer` on ancestry path in a sub-traversal. And it may break some plugins if they intend to change the path context in the visitor.

I will see if it can be fixed in `addHelper` utility, otherwise we may have to trade off performance for correctness here.

**Comment by Jessidhia** [comment]
This is a regression from (at least) 7.13. The REPL doesn't seem to have 7.14 so I couldn't check that.

Smaller reproduction (the empty push is to skip static array optimization):

```js
async function f() {
  for await (const { foo } of [].push()) {}
}
```

Relevant annotated output in 7.13.17:

```js
        case 4:
          _context.next = 6;
          // await iterator.next()
          return regeneratorRuntime.awrap(_iterator.next());

        case 6:
          _step = _context.sent;
          // store whether iterator is complete but don't check yet
          _iteratorNormalCompletion = _step.done;
          _context.next = 10;
          // await step.value (what was yielded from iterator.next())
          return regeneratorRuntime.awrap(_step.value);

        case 10:
          // read the result of await step.value
          _value = _context.sent;

          // check now for iterator completion
          if (_iteratorNormalCompletion) {
            _context.next = 16;
            break;
          }

          // read foo from the awaited iterator.value
          _value2 = _value, foo = _value2.foo;
```

Relevant annotated output in 7.15.7:

```js
        case 4:
          _context.next = 6;
          // await iterator.next()
          return regeneratorRuntime.awrap(_iterator.next());

        case 6:
          // directly check if iterator is done before awaiting for value
          if (!(_iteratorAbruptCompletion = !(_step = _context.sent).done)) {
            _context.next = 11;
            break;
          }

          // directly attempt to read step.value, which is a Promise
          // the "for await" was effectively transformed like a regenerator version of a regular "for of"
          foo = _step.value.foo;
```

**Comment by danieltroger** [comment]
Yo @JLHwung just curious, why does the REPL link still crash?

**Comment by nicolo-ribaudo** [comment]
The repl link in the issue original issue used Babel 7.15.7. It doesn't crash with 7.16.2: https://babeljs.io/repl/#?browsers=IE%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=LYQwlgdgFAlA3AKASAzgTwgYwAQDMCuWALmAPYTaiSzYDeC22ANgKZHZgoD6AJuS9gC8eEExQtEjTORTtUGTFzBEWAJxAAjVkLoNG2ANoBlNMA2kmAOnlYAkivVFSqgLoAubDUEA-T_X36ECwAHkQeXr7-AfrSELLYAA6qpMCcAsIACsmp4paqLCgWAG4sULTYRaL4LB4AREz4Rdj4tQA02HxBHpy8_NgAvvB60RzcnenYRKrVkiPY-UT4qhRJKWmzAf2twwMw24z9iEiMUDY4EXTYAPRX2La2AGIAoh75AI74YPk8eM7YGpoWExJqRsJh1CgABY7XB_EAAd3A7CgsXislUkAA5thSLhsGclA5NKwYJcbr9VPjEcpXiwPl8WD9YZSARogSCwRDoSNURYWJYmKRMVB0Vihps9INYEcpDJ2AZ-C4dAYAIwuODXW4gVTqNAdApTfCYRYYiCY2n074U_6A4FOTmoaH9BBAA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.16.2&externalPlugins=&assumptions=%7B%7D

**Comment by danieltroger** [comment]
Oh, I didn't know the version was in the link. Alright, amazing!
