### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'constantViolations')

### ISSUE THREAD

**Issue by pustovalov** [babel/babel#13907]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
//root.jsx

import { observer, inject } from 'mobx-react'
import { AccountRootStore } from 'stores/account/account_root_store'

const AccountsEdit = inject(({ accountRootStore }) => ({
  accountRootStore,
  accountStore: accountRootStore.accountStore,
  currentUser: accountRootStore.currentUser,
  onSubmit: accountRootStore.accountSettingsFormStore.onSubmit,
}))(
  observer(
    class AccountsEdit extends React.PureComponent {
      render() {
        return (
          <div>
          </div>
        )
      }
    },
  ),
)
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = function (api) {
  let validEnv = ['development', 'test', 'production']
  let currentEnv = api.env()
  let isDevelopmentEnv = api.env('development')
  let isProductionEnv = api.env('production')
  let isTestEnv = api.env('test')

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      'Please specify a valid `NODE_ENV` or ' +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        '.',
    )
  }

  return {
    presets: [
      isTestEnv && [
        '@babel/preset-env',
        {
          loose: true,
          targets: {
            node: 'current',
          },
        },
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        '@babel/preset-env',
        {
          useBuiltIns: 'entry',
          modules: 'auto',
          bugfixes: true,
          loose: true,
          corejs: '3.19',
          configPath: __dirname + '/package.json',
        },
      ],
      [
        '@babel/preset-react',
        {
          development: isDevelopmentEnv || isTestEnv,
          useBuiltIns: true,
        },
      ],
      ['@babel/preset-typescript', { allExtensions: true, isTSX: true }],
    ].filter(Boolean),
    plugins: [
      process.env.WEBPACK_DEV_SERVER && 'react-refresh/babel',
      '@loadable/babel-plugin',
      'babel-plugin-macros',
      [
        '@babel/plugin-proposal-class-properties',
        {
          loose: true,
        },
      ],
      [
        '@babel/plugin-transform-classes',
        {
          loose: true,
        },
      ],
      isTestEnv && [
        '@babel/plugin-transform-spread',
        {
          loose: true,
        },
      ],
      [
        '@babel/plugin-transform-runtime',
        {
          helpers: false,
        },
      ],
      [
        'babel-plugin-styled-components',
        {
          displayName: !isTestEnv,
          ssr: false,
        },
      ],
      isProductionEnv && [
        'babel-plugin-transform-react-remove-prop-types',
        {
          removeImport: true,
        },
      ],
    ].filter(Boolean),
  }
}

```

### Current and expected behavior

Before update:
```
  System:
    OS: macOS 11.6
  Binaries:
    Node: 17.0.1 - /usr/local/opt/node/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.15.8 => 7.15.8
    @babel/eslint-parser: ^7.15.8 => 7.15.8
    @babel/plugin-proposal-class-properties: ^7.14.5 => 7.14.5
    @babel/plugin-transform-classes: ^7.15.4 => 7.15.4
    @babel/plugin-transform-runtime: ^7.15.8 => 7.15.8
    @babel/plugin-transform-spread: ^7.15.8 => 7.15.8
    @babel/preset-env: ^7.15.8 => 7.15.8
    @babel/preset-react: ^7.14.5 => 7.14.5
    @babel/preset-typescript: ^7.15.0 => 7.15.0
    @babel/runtime: ^7.15.4 => 7.15.4
    babel-jest: ^27.3.1 => 27.3.1
    babel-plugin-styled-components: ^1.13.3 => 1.13.3
    babel-plugin-transform-react-remove-prop-types: ^0.4.24 => 0.4.24
    eslint: ^7.32.0 => 7.32.0
    jest: ^27.3.1 => 27.3.1
    webpack: ^4.44.2 => 4.46.0
```

All works fine

Behavior after update:
```
ERROR in ./app/javascript/components/accounts/edit/root.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/pavel/t/main/app/javascript/components/accounts/edit/root.jsx: Cannot read properties of undefined (reading 'constantViolations')
    at shouldTransform (/Users/pavel/t/main/node_modules/@babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression/lib/index.js:15:47)
    at PluginPass.FunctionExpression (/Users/pavel/t/main/node_modules/@babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression/lib/index.js:40:22)
    at newFn (/Users/pavel/t/main/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/pavel/t/main/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/pavel/t/main/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/pavel/t/main/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/Users/pavel/t/main/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitSingle (/Users/pavel/t/main/node_modules/@babel/traverse/lib/context.js:77:19)
    at TraversalContext.visit (/Users/pavel/t/main/node_modules/@babel/traverse/lib/context.js:131:19)
    at Function.traverse.node (/Users/pavel/t/main/node_modules/@babel/traverse/lib/index.js:82:17)
```

### Environment
```
  System:
    OS: macOS 11.6
  Binaries:
    Node: 17.0.1 - /usr/local/opt/node/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.16.0 => 7.16.0
    @babel/eslint-parser: ^7.16.0 => 7.16.0
    @babel/plugin-proposal-class-properties: ^7.16.0 => 7.16.0
    @babel/plugin-transform-classes: ^7.16.0 => 7.16.0
    @babel/plugin-transform-runtime: ^7.16.0 => 7.16.0
    @babel/plugin-transform-spread: ^7.16.0 => 7.16.0
    @babel/preset-env: ^7.16.0 => 7.16.0
    @babel/preset-react: ^7.16.0 => 7.16.0
    @babel/preset-typescript: ^7.16.0 => 7.16.0
    @babel/runtime: ^7.16.0 => 7.16.0
    babel-jest: ^27.3.1 => 27.3.1
    babel-plugin-styled-components: ^1.13.3 => 1.13.3
    babel-plugin-transform-react-remove-prop-types: ^0.4.24 => 0.4.24
    eslint: ^7.32.0 => 7.32.0
    jest: ^27.3.1 => 27.3.1
    webpack: ^4.44.2 => 4.46.0
```

**Comment by nicolo-ribaudo** [comment]
Until this is fixed, the only package you need to downgrade is `@babel/preset-env`
