### ISSUE TITLE
Transpilation choking on syntax error in 5.2.0, but not in 5.1.13

### ISSUE THREAD

**Issue by nackjicholson** [babel/babel#1399]
I get no error using `5.1.13`, but `5.2.0` does this:

```
[16:33:15] SyntaxError: /Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/gulp-mocha/node_modules/gulp-util/node_modules/beeper/index.js: 'return' outside of function (9:1)
   7 |  process.argv.indexOf('--beep=false') !== -1) {
   8 |  module.exports = function () {};
>  9 |  return;
     |  ^
  10 | }
  11 | 
  12 | function beep() {
    at Parser.pp.raise (/Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.parseReturnStatement (/Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:247:74)
    at Parser.pp.parseStatement (/Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:77:19)
    at Parser.parseStatement (/Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
    at Parser.pp.parseBlock (/Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:387:21)
    at Parser.pp.parseStatement (/Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:93:19)
    at Parser.parseStatement (/Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
    at Parser.pp.parseIfStatement (/Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:241:26)
    at Parser.pp.parseStatement (/Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:75:19)
    at Parser.parseStatement (/Users/nackjicholson/repos/dynamoDb-marshaler/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)

```

**Comment by sebmck** [comment]
See #1398. Update to 5.2.1.

**Comment by nackjicholson** [comment]
Thanks.
