### ISSUE TITLE
Type aliases are broken

### ISSUE THREAD

**Issue by monsanto** [babel/babel#1401]
Type aliases are broken as of 8ae460117730e1116356280be796a1e6e52bcd1e. Reverting the change to strict.js fixes it.

```
monsanto@box:~/source/babel$ echo 'type X = Int' | babel                                                                                     
/home/monsanto/source/babel/lib/babel/helpers/parse.js:80
    throw err;
          ^
Error: unknown: No clue what to do with this node type.
    at TraversalPath.insertBefore (/home/monsanto/source/babel/lib/babel/traversal/path/index.js:168:13)
    at TraversalPath.unshiftContainer (/home/monsanto/source/babel/lib/babel/traversal/path/index.js:472:17)
```

**Comment by sebmck** [comment]
Fixed as of 5.2.3, thanks!
