### ISSUE TITLE
[Bug]: Cannot read properties of null failing with optional chaining?

### ISSUE THREAD

**Issue by jrj2211** [babel/babel#14043]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

```
err.errors?.forEach((message, name) => {
          const input = this.querySelector(`input[name=${name}]`);
          const label = input.closest('label');
          label.setAttribute('error', `• ${message}`);
});
```

### Configuration

I don't have a babelrc file but I do have an eslintrc file:

```
{
    "env": {
        "browser": true,
        "es2021": true,
        "node": true
    },
    "extends": [
        "airbnb-base"
    ],
    "parserOptions": {
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "parser": "babel-eslint",
    "rules": {
      "max-len": 0,
      "no-unused-vars": [2, { "args": "none" }],
      "func-names": [2, "never"],
      "import/no-unresolved": 0,
      "import/extensions": 0,
      "no-underscore-dangle": 0,
      "no-param-reassign": [2, { "props": false }],
      "lines-between-class-members": [2, "always", { "exceptAfterSingleLine": true }],
      "no-restricted-syntax": ["error", "ForInStatement", "LabeledStatement", "WithStatement"],
      "class-methods-use-this": 0,
      "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }],
      "default-case": 0
    }
}

```

### Current and expected behavior

Current behavior is that I'm getting the error:

```
TypeError: Cannot read properties of null (reading 'value')
Occurred while linting C:\Users\Joe\projects\test\app\views\index.js:243
    at checkSpacingBefore (C:\Users\Joe\projects\test\node_modules\eslint\lib\rules\template-curly-spacing.js:52:24)
    at TemplateElement (C:\Users\Joe\projects\test\node_modules\eslint\lib\rules\template-curly-spacing.js:136:17)
    at C:\Users\Joe\projects\test\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\Joe\projects\test\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\Joe\projects\test\node_modules\eslint\lib\linter\node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (C:\Users\Joe\projects\test\node_modules\eslint\lib\linter\node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (C:\Users\Joe\projects\test\node_modules\eslint\lib\linter\node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (C:\Users\Joe\projects\test\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:711:23)
    at C:\Users\Joe\projects\test\node_modules\eslint\lib\linter\linter.js:960:32
```

I read on an old issue from babel-eslint that this has to do with variables inside `${variable}`. Changing my code to use 'input[name=' + name + ']' does then work but I'm not a fan of that.

Alternatively, removing the optional changing works as well:

```
(err.errors || []).forEach((message, name) => {
// OR
if(err.errors) err.errors.forEach((message, name) => {
```

### Environment

 System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.16.0 => 7.16.0
    @babel/eslint-parser: ^7.16.3 => 7.16.3
    babel-eslint: ^10.1.0 => 10.1.0
    babel-loader: ^8.2.2 => 8.2.2
    eslint: ^7.32.0 => 7.32.0
    webpack: ^5.36.2 => 5.53.0

**Comment by jrj2211** [comment]
Nevermind, I just noticed that I have both babel-eslint and @babel/eslint-parser installed and was using the wrong one. Switching to the new package now works.
