### ISSUE TITLE
[Bug]: Filename does not appear in SyntaxErrors when using Node < 16.9.0

### ISSUE THREAD

**Issue by codebling** [babel/babel#14128]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

https://github.com/codebling/babel-issue-example contains a minimal reproducible example, along with instructions and expected and actual results. Key points of the README are copied here:

```
git clone https://github.com/codebling/babel-issue-example.git
cd babel-issue-example
nvm use 16.8    # or any version between 12 and 16.8, possibly even earlier versions
npm i
npm start       # or: ./node_modules/.bin/babel-node index.js
```

### Configuration file name

package.json

## Expected Result

Using Node 16.9.0 or later, the problematic file name and lines are logged.
```
SyntaxError: /tmp/babel-issue-example/index.js: Legacy octal literals are not allowed in strict mode. (1:4)

> 1 | a = 01;
    |     ^
  2 |
    at Parser._raise (/tmp/babel-issue-example/node_modules/@babel/parser/lib/index.js:569:17
```

## Actual Result

Using Node 16.8 or earlier, we don't see the file name (though the line numbers still appear).
```
SyntaxError: Legacy octal literals are not allowed in strict mode. (1:4)
    at Parser._raise (/tmp/babel-issue-example/node_modules/@babel/parser/lib/index.js:569:17)
```

### Environment

- Babel version: ^7.16
- Node version: <= 16.8 (works in >= 16.9.0)
- OS: linux or Mac

**Comment by JLHwung** [comment]
This issue only affects `@babel/node`. I can't reproduce on `@babel/cli`.

**Comment by codebling** [comment]
Sounds right, sorry about that. I've updated the issue description (`@babel/node` wasn't in the template and I didn't think to change it afterwards)

**Comment by r3x5ur** [comment]
**Babel is forced to open strict mode, is there a way to close it**

![image](https://user-images.githubusercontent.com/64947085/230759414-e9041f71-a491-4ae5-ac32-6b20971aaa1e.png)
`package.json`
```json
  "dependencies": {
    "@babel/core": "^7.21.3",
}
```

**Comment by codebling** [comment]
@r3x5ur how is that related

**Comment by JLHwung** [comment]
@r3x5ur You can set `sourceType` to `script` ([docs link](https://babel.dev/docs/options#sourcetype)). If you have further questions, please open a new issue instead of hijacking current thread.

**Comment by r3x5ur** [comment]
Solved, thank you
