### ISSUE TITLE
[Bug]: Syntax Error:support for 'jsx' is not enabled only when electron application has been packaged.

### ISSUE THREAD

**Issue by athinimafu** [babel/babel#14155]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```
const babel = require("@babel/core");

function transform(sourceCode) {
    return babel.transformAsync(sourceCode,{});
}
```

### Configuration file name

babel.config.json

### Configuration

```{
    "presets":[
        [
            "@babel/preset-env",
            {
                "targets":"defaults"
            }
        ],
        "@babel/preset-react"
    ],
    "targets":{
        "electron":"16.0.6"
    }
}
```

### Current and expected behavior

When i run my application through the terminal the application runs correctly however once i run a build version of the application the following error occurs once 
```
SyntaxError: unknown: Support for the experimental syntax 'jsx' isn't currently enabled (91:13):

  89 |     render() {
  90 |         return (
> 91 |             <div className="col-md-12 calculator" >
     |             ^
  92 |                 <div className="display col-md-12">
  93 |                     <h2 className='alternate-equation'> { this.state.equation } </h2>
  94 |                     <p className='answer'> { this.state.value } </p>

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
```
 I'm trying to parse the above code that is throwing the error using the babel programmatic api.

### Environment

System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/core: ^7.16.7 => 7.16.7
    @babel/plugin-transform-classes: ^7.16.7 => 7.16.7
    @babel/preset-env: ^7.16.8 => 7.16.8
    @babel/preset-react: ^7.16.7 => 7.16.7
    @babel/preset-stage-0: ^7.8.3 => 7.8.3
    babel-loader: ^8.2.3 => 8.2.3
    grunt-babel: ^8.0.0 => 8.0.0
    webpack: ^5.65.0 => 5.66.0

### Additional context

I'm not sure if this is a problem created by babel or by electron-builder which is what i used to build the application, but i thought since it was babel producing the error i should ask here. Here is my package.json file.
```
  {
  "name": "planck_app",
  "productName": "planck_app",
  "version": "1.0.0",
  "description": "My Electron application description",
  "main": "main.js",
  "index": "index-bundled.js",
  "indexHtml": "index.html",
  "scripts": {
    "start": "electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder",
    "lint": "echo \"No linting configured\"",
    "postinstall": "electron-builder install-app-deps",
    "unpack":"npx asar extract 'C:\\Users\\uncle-shaggy\\programs\\planck_app\\planck-app\\dist\\win-unpacked\\resources\\app.asar' './dist/unpacked'"
  },
  "keywords": [],
  "author": {
    "name": "uncle-shaggy",
    "email": "zanoxstoner@gmail.com"
  },
  "license": "MIT",
  "build": {
    "appId": "planck.web.dev.text.editor.app",
    "linux": {
      "target": "deb",
      "category": "Development"
    },
    "win": {
      "target": "squirrel"
    }
  },
  "dependencies": {
    "@babel/core": "^7.16.7",
    "@babel/plugin-transform-classes": "^7.16.7",
    "@babel/preset-env": "^7.16.8",
    "@babel/preset-react": "^7.16.7",
    "electron-builder-squirrel-windows": "^22.14.12",
    "electron-log": "^4.4.4",
    "electron-squirrel-startup": "^1.0.0",
    "electron-unhandled": "^3.0.2",
    "grunt-cli": "^1.4.3",
    "json5": "^2.2.0",
    "localforage": "^1.10.0",
    "prettier": "^2.5.1",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@babel/preset-stage-0": "^7.8.3",
    "babel-loader": "^8.2.3",
    "electron": "^16.0.6",
    "electron-builder": "^22.14.5",
    "grunt": "^1.4.1",
    "grunt-babel": "^8.0.0",
    "load-grunt-tasks": "^5.1.0",
    "webpack": "^5.65.0",
    "webpack-cli": "^4.9.1"
  }
}
```

**Comment by JLHwung** [comment]
Can you provide a reproduciton repo?

**Comment by JLHwung** [comment]
Yes, without a reproduction repo we can't prioritize the issue.

**Comment by athinimafu** [comment]
[https://github.com/athinimafu/reprod.git](url) is the repo where i reproduced the same error. it's a small electron application where you write code and it is transpiled for you using babel it works fine for jsx when run through the terminal but again the packaged application displays the same syntax error.

**Comment by JLHwung** [comment]
You need to pass a filename for `preset-react` to work
```js
return (await babel.transformAsync(code,{ filename: "example.jsx" })).code;
```
the filename is automatically determined by `@babel/cli`, but if you are calling `@babel/core` programmatically, you have to provide the `filename` option.

**Comment by athinimafu** [comment]
@JLHwung  i did as you suggested and exact error still persists

**Comment by nicolo-ribaudo** [comment]
> https://github.com/athinimafu/reprod.git 

How do I use it? `npm run pack` works without errors, and `npm run dist` gives this error:
```
reprod@1.0.0 dist
> electron-builder

  • electron-builder  version=22.14.5 os=5.13.0-1010-gcp
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=16.0.7 appOutDir=dist/linux-unpacked
  • building        target=deb arch=x64 file=dist/reprod_1.0.0_amd64.deb
  ⨯ Please specify author 'email' in the application package.json

See https://docs.npmjs.com/files/package.json#people-fields-author-contributors

It is required to set Linux .deb package maintainer. Or you can set maintainer in the custom linux options.
(see https://www.electron.build/configuration/linux).
  failedTask=build stackTrace=Error: Please specify author 'email' in the application package.json
                                                                                                                                                                                                                                                                                                                          See https://docs.npmjs.com/files/package.json#people-fields-author-contributors
                                                                                                                                                                                                                                                                                                                          It is required to set Linux .deb package maintainer. Or you can set maintainer in the custom linux options.
(see https://www.electron.build/configuration/linux).
                                                                                                                                                                                                                                                                                                                              at FpmTarget.computeFpmMetaInfoOptions (/workspace/reprod/node_modules/app-builder-lib/src/targets/fpm.ts:86:13)
    at FpmTarget.build (/workspace/reprod/node_modules/app-builder-lib/src/targets/fpm.ts:144:25)
    at /workspace/reprod/node_modules/app-builder-lib/src/platformPackager.ts:154:11
    at async Promise.all (index 0)
    at AsyncTaskManager.awaitTasks (/workspace/reprod/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at Packager.doBuild (/workspace/reprod/node_modules/app-builder-lib/src/packager.ts:453:5)
    at Object.executeFinally (/workspace/reprod/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/workspace/reprod/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/workspace/reprod/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/workspace/reprod/node_modules/builder-util/src/promise.ts:12:14)
```

**Comment by athinimafu** [comment]
sorry the squirrel.windows installer configuration for electron-builder requires an email field.

**Comment by nicolo-ribaudo** [comment]
Btw, I cannot know for sure since I cannot reproduce the problem using your repository, but you could try specifying `configFile: __dirname + "/babel.config.json"` in the `babel-loader` options in `webpack.config.js`

**Comment by athinimafu** [comment]
The webpack bundle is only responsible for bundling renderer process so i can't see how that would effect the code
` await babel.transformAsync(code,{ filename:"example.jsx", })).code; ` which i execute in the main process but i did as you suggested anyway and the error still persists . When you say you cannot reproduce the error does that mean you can successfully transpile jsx using the build application.
