### ISSUE TITLE
[Bug]: Release 7.17.0 breaks downstream plugins

### ISSUE THREAD

**Issue by l0gicgate** [babel/babel#14233]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
import { SomeComponent } from '~/some/aliased/path`;
```

### Current and expected behavior

Not to break downstream plugins

### Environment

- Babel 7.17.0
- Node 

### Additional context

This is the error that started occurring after updating from `@babel/core: 7.16.12` to `7.17.0`

```
[eslint-import-resolver-babel-module] TypeError: [BABEL] C:\Redacted\src\components\ui\Nav\AccountMenu\AccountMenu.js: Cannot add property 1, object is not extensible
    at Array.push (<anonymous>)
    at C:\Redacted\node_modules\@babel\core\lib\config\full.js:314:26
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\Redacted\node_modules\@babel\core\lib\gensync-utils\async.js:25:3)
    at Generator.next (<anonymous>)
    at evaluateSync (C:\Redacted\node_modules\gensync\index.js:251:28)
    at Function.sync (C:\Redacted\node_modules\gensync\index.js:89:14)
    at sync (C:\Redacted\node_modules\@babel\core\lib\gensync-utils\async.js:68:25)
    at sync (C:\Redacted\node_modules\gensync\index.js:182:19)
    at onFirstPause (C:\Redacted\node_modules\gensync\index.js:210:24)
    at Generator.next (<anonymous>)
    at cachedFunction (C:\Redacted\node_modules\@babel\core\lib\config\caching.js:66:46)
    at cachedFunction.next (<anonymous>)
    at loadPluginDescriptor (C:\Redacted\node_modules\@babel\core\lib\config\full.js:282:17)
    at loadPluginDescriptor.next (<anonymous>)
    at loadPluginDescriptors (C:\Redacted\node_modules\@babel\core\lib\config\full.js:170:33)

```

**Comment by nicolo-ribaudo** [comment]
We need your config, or even better an example that shows the crash.

**Comment by JLHwung** [comment]
Is this issue reproduced in `@babel/traverse@7.16.8`? 7.16.8 comes with a bug fix of wrong behaviour which some plugins may depend on.
Can you provide a reproduction repo?

**Comment by nicolo-ribaudo** [comment]
This is related to the `extendedDependencies` tracking. When loading a plugin, we usually:
1. create an `externalDependencies` array for the plugin
2. if the plugin inherits from another plugin:
   1. load the inherited plugin
   2. push the `externalDependencies` of the inherited plugin into the `externalDependencies` of the plugin we are loading
3. freeze `externalDependencies` of the plugin we are loading

However, for some reason `externalDependencies` of the plugin we are loading is already frozen at step 2.2: I don't understand why it's possible, so we need to know which plugin is causing this.

**Comment by l0gicgate** [comment]
@nicolo-ribaudo here's my babel config:
```json
{
  "env": {
    "development": {
      "plugins": [
        "@babel/plugin-proposal-class-properties",
        [
          "@babel/plugin-transform-runtime",
          {
            "absoluteRuntime": false,
            "corejs": false,
            "version": "^7.7.4"
          }
        ],
        [
          "module-resolver",
          {
            "root": ["./src"],
            "alias": {
              "~": "./src"
            }
          }
        ]
      ],
      "presets": [
        "airbnb",
        "@babel/preset-env",
        "@babel/preset-react"
      ]
    },
    "production": {
      "plugins": [
        "@babel/plugin-proposal-class-properties",
        [
          "@babel/plugin-transform-runtime",
          {
            "absoluteRuntime": false,
            "corejs": false,
            "version": "^7.7.4"
          }
        ],
        [
          "module-resolver",
          {
            "root": ["./src"],
            "alias": {
              "~": "./src"
            }
          }
        ],
        ["transform-react-remove-prop-types", {
          "mode": "remove",
          "ignoreFilenames": ["node_modules"],
          "removeImport": true
        }]
      ],
      "presets": [
        "airbnb",
        "@babel/preset-env",
        "@babel/preset-react"
      ]
    },
    "staging": {
      "plugins": [
        "@babel/plugin-proposal-class-properties",
        [
          "@babel/plugin-transform-runtime",
          {
            "absoluteRuntime": false,
            "corejs": false,
            "version": "^7.7.4"
          }
        ],
        [
          "module-resolver",
          {
            "root": ["./src"],
            "alias": {
              "~": "./src"
            }
          }
        ],
        ["transform-react-remove-prop-types", {
          "mode": "remove",
          "ignoreFilenames": ["node_modules"],
          "removeImport": true
        }]
      ],
      "presets": [
        "airbnb",
        "@babel/preset-env",
        "@babel/preset-react"
      ]
    }
  }
}
```

**Comment by nicolo-ribaudo** [comment]
Are you running with `NODE_ENV` (or `BABEL_ENV`) set to `development`, `production` or `staging`? (you have different configs for different envs)

**Comment by l0gicgate** [comment]
`NODE_ENV` set to `development` @nicolo-ribaudo

**Comment by jaggaer-epiccini** [comment]
**Hello starting from today I've this issue:**

`**Uncaught Error: Cannot create styled-component for component: undefined.**
    at j (vendors~main.iframe.bundle.js:386453:4940)
    at e (vendors~main.iframe.bundle.js:386453:21638)
    at He (vendors~main.iframe.bundle.js:386453:21875)
    at Object../node_modules/@/ui/build/Slider/Slider.js (vendors~main.iframe.bundle.js:81207:50)
    at __webpack_require__ (runtime~main.iframe.bundle.js:857:31)
    at fn (runtime~main.iframe.bundle.js:151:20)
    at Object../node_modules/@/ui/build/Slider/index.js (vendors~main.iframe.bundle.js:81343:15)
    at __webpack_require__ (runtime~main.iframe.bundle.js:857:31)
    at fn (runtime~main.iframe.bundle.js:151:20)
    at Object../node_modules/@/ui/build/index.js (vendors~main.iframe.bundle.js:84540:15)`


**it is used by:**
![image](https://user-images.githubusercontent.com/78030279/152420051-88ba1f4c-8872-4693-a963-02599733cdb7.png)

**this is babel config:**

`

module.exports = function (api) {
    api.cache(true);
    const presets = [ "@babel/preset-env", "@babel/preset-react" ];
    const plugins = [ "macros" ];

    return {
        presets,
        plugins
    };
}
`

**Comment by nicolo-ribaudo** [comment]
That looks unrelated, please create a new issue with instructions to reproduce the bug

**Comment by jaggaer-epiccini** [comment]
Until yesterday it worked perfectly, today the unique dependency not synched in our private nexus was your dependency ...I think @babel/preset-env in my package.json has downloaded too updated dependency that create this issue.

In out CRA project also I've this issue:

Uncaught ReferenceError: process is not defined

**Comment by nicolo-ribaudo** [comment]
It might be caused by this babel update, but it's a different error. Please open a new repository with some steps to reproduce the problem, and the full stack trace of that CRA error.

**Comment by nicolo-ribaudo** [comment]
@l0gicgate I tried reproducing the error at https://github.com/nicolo-ribaudo/babel-bug-1423, but it compiles succesfully (using `npm run build`) :sweat_smile: 

Could you try creating a small repo I can use to see the error?

**Comment by l0gicgate** [comment]
@nicolo-ribaudo I stripped everything down as best as I could with minimal dependencies to reproduce the issue. Here's the repository:
https://github.com/l0gicgate/babel-core-issue-14233

Let me know if you need anything else

**Comment by Haroenv** [comment]
I think I'm having the same issue here: https://app.circleci.com/pipelines/github/algolia/vue-instantsearch/1473/workflows/f4cd9381-e860-4e10-bbc2-587036c5ac68/jobs/4470

**Comment by jaggaer-epiccini** [comment]
> It might be caused by this babel update, but it's a different error. Please open a new repository with some steps to reproduce the problem, and the full stack trace of that CRA error.

[test.zip](https://github.com/babel/babel/files/8002880/test.zip)
This is the smal project:
npm install + npm run start
and you should see process env issue

Thank you

**Comment by nicolo-ribaudo** [comment]
Thanks @l0gicgate; I was able to trim your repository down even more (first removing webpack, and then some ESLint stuff), and I managed to create a reproduction that only uses Babel (https://github.com/babel/babel/pull/14241).

However, I will not be available much this weekend and next week, so it might take a while before I fix it. In the meantime, please pin `@babel/core` to the last working version (e.g. `~7.16.0`).

**Comment by l0gicgate** [comment]
@nicolo-ribaudo thank you for promptly addressing this. I will pin to 7.16 until #14241 gets merged! Have a good weekend!
