### ISSUE TITLE
ReferenceError: Unknown transformer es6.unicodeRegex specified in whitelist

### ISSUE THREAD

**Issue by mzgol** [babel/babel#1425]
babel 5.2.6, io.js 1.8.1:
```
$ babel --whitelist es6.unicodeRegex src/app.js
/Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:121
        throw new ReferenceError("Unknown transformer " + key + " specified in
              ^
ReferenceError: Unknown transformer es6.unicodeRegex specified in whitelist
    at TransformerPipeline._ensureTransformerNames (/Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:121:15)
    at transformerList (/Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/option-parsers.js:23:19)
    at File.normalizeOptions (/Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:187:31)
    at new File (/Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:148:22)
    at TransformerPipeline.transform (/Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:86:16)
    at Object.exports.transform (/Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/bin/babel/util.js:33:22)
    at Object.exports.compile (/Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/bin/babel/util.js:41:18)
    at /Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/bin/babel/file.js:112:25
    at arrayEach (/Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/node_modules/lodash/index.js:1361:13)
    at Function.<anonymous> (/Users/mgol/.nvm/versions/io.js/v1.8.1/lib/node_modules/babel/node_modules/lodash/index.js:3405:13)
```

This transformer is documented under https://babeljs.io/docs/usage/transformers/

**Comment by sebmck** [comment]
Docs were out of date. In the future please, as the README says, report these issues on the [babel.github.io repo](https://github.com/babel/babel.github.io):

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

Thanks!

**Comment by mzgol** [comment]
Ah, sorry, I'll remember next time.

**Comment by sebmck** [comment]
All good!
