### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by gsklee** [babel/babel#1432]
I ran my gulpfile through the require hook (`require('babel-core/register')`) and encountered the following error:

```
/srv/home/kaylee/projects/projectX/node_modules/babel-core/lib/babel/helpers/code-frame.js:66
  return text.replace(_jsTokens2["default"], function () {
              ^
TypeError: undefined is not a function
    at highlight (/srv/home/kaylee/projects/projectX/node_modules/babel-core/lib/babel/helpers/code-frame.js:66:15)
    at Object.exports.default (/srv/home/kaylee/projects/projectX/node_modules/babel-core/lib/babel/helpers/code-frame.js:89:13)
    at File.wrap (/srv/home/kaylee/projects/projectX/node_modules/babel-core/lib/babel/transformation/file/index.js:590:47)
    at TransformerPipeline.transform (/srv/home/kaylee/projects/projectX/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:87:17)
    at Object.transformFileSync (/srv/home/kaylee/projects/projectX/node_modules/babel-core/lib/babel/api/node.js:108:32)
    at compile (/srv/home/kaylee/projects/projectX/node_modules/babel-core/lib/babel/api/register/node.js:98:20)
    at normalLoader (/srv/home/kaylee/projects/projectX/node_modules/babel-core/lib/babel/api/register/node.js:147:14)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/home/kaylee/projects/projectX/node_modules/babel-core/lib/babel/api/register/node.js:160:7)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

After some debugging, it appeared that the error was caused by attempting to reassign a new value to a `const`; however it'd be great if the error message could be clearer.

**Comment by sebmck** [comment]
The error message is shit because it's a bug in Babel not because it was a deliberate decision.
