### ISSUE TITLE
[Bug]: SyntaxError - Unexpected token, expected "," Typescript

### ISSUE THREAD

**Issue by fzn0x** [babel/babel#14516]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
describe("my test suite", () => {
    it.fetch("https://stackoverflow.com/questions/70063451/cant-import-node-fetch-into-typescript", {}, (a: string) => {
        console.log(a);
        expect(0).toStrictEqual(0)
    })
});
```

### Configuration

```json
export default {
    // Other configuration above...

    // Add the next three options if using TypeScript
    moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json"],
    preset: "ts-jest",
    transform: {
        "^.+\\.[t|j]sx?$": "babel-jest"
    },

    // Run these files after jest has been
    // installed in the environment
    setupFilesAfterEnv: ["<rootDir>/build/jest.setup.js"], // use .js if you prefer JavaScript
    testEnvironment: "node",
};
```

### Current and expected behavior

Current behavior:

```
 FAIL  tests/test.spec.ts
  ● The test suite failed to run

    SyntaxError: D:\Projects\Javascript\jessica\tests\test.spec.ts: Unexpected token, expected "," (2:106)

      1 | describe("my test suite", () => {
    > 2 |     it.fetch("https://stackoverflow.com/questions/70063451/cant-import-node-fetch-into-typescript", {}, (a: string) => {
        |                                                                                                           ^
      3 |         console.log(a);
      4 |         expect(0).toStrictEqual(0)
      5 |     })

      at instantiate (node_modules/@babel/parser/src/parse-error/credentials.js:61:22)
      at toParseError (node_modules/@babel/parser/src/parse-error.js:58:12)
      at Parser.raise (node_modules/@babel/parser/src/tokenizer/index.js:1736:19)
      at Parser.unexpected (node_modules/@babel/parser/src/tokenizer/index.js:1781:16)
      at Parser.expect (node_modules/@babel/parser/src/parser/util.js:153:28)
      at Parser.parseParenAndDistinguishExpression (node_modules/@babel/parser/src/parser/expression.js:1698:14)
      at Parser.parseExprAtom (node_modules/@babel/parser/src/parser/expression.js:1123:21)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/src/parser/expression.js:683:23)
      at Parser.parseUpdate (node_modules/@babel/parser/src/parser/expression.js:662:21)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/src/parser/expression.js:631:23)
```

Expected behavior:

Tests run successfully.

### Environment

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/preset-env: ^7.17.10 => 7.17.10
    jest: ^27.5.1 => 27.5.1

**Comment by nicolo-ribaudo** [comment]
It looks like Babel's typescript plugin is not enabled; I suggest asking in the Jest repository how to configure Jest to support TS files.

**Comment by fzn0x** [comment]
> It looks like Babel's typescript plugin is not enabled; I suggest asking in the Jest repository how to configure Jest to support TS files.

Thanks
