### ISSUE TITLE
Proposal: Babel-Standalone Minimal Build supporting only JSX

### ISSUE THREAD

**Issue by curran** [babel/babel#14567]
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

I am working on a browser-based code editor. I want this editor to support JSX. The editor currently uses [buble-jsx-only](https://github.com/vizhub-core/buble-jsx-only) to transpile JSX in the browser, but that unfortunately suffers from [lack of support for optional chaining](https://github.com/bublejs/buble/issues/267). I'm looking for a solution that transpiles JSX in the browser, and babel-standalone is such a solution, however it suffers from a [large bundle size](https://bundlephobia.com/package/@babel/standalone@7.18.0). This proposal aims to solve the bundle size issue by introducing an alternative build of Babel-standalone that does _not_ import and include in its bundle any extraneous transforms except those required to support JSX.

### Describe the solution you'd like

I'd like an alternative build of Babel-standalone that does _not_ import and include in its bundle any extraneous transforms except those required to support JSX.

### Describe alternatives you've considered

I've considered using [buble-jsx-only](https://github.com/vizhub-core/buble-jsx-only) to transpile JSX in the browser, but that unfortunately suffers from [lack of support for optional chaining](https://github.com/bublejs/buble/issues/267). 

### Documentation, Adoption, Migration Strategy

There could be a new entry point for the Babel-standalone build, and a new built file that can be documented. Alternative we can do a hard fork of the `babel-standalone` package, introducing a new sibling package `babel-standalone-jsx-only` (similar to the relationship between `buble` and `buble-jsx-only`.

**Comment by nicolo-ribaudo** [comment]
You can import `@babel/core` and `@babel/plugin-transform-react-jsx` in your app, and the bundle it with webpack or rollup.

**Comment by curran** [comment]
Thank you @nicolo-ribaudo for your suggestion! I tried it. Here is what I experienced:

After setting up a minimal Rollup build that imports things from `@babel/core` and `@babel/plugin-transform-react-jsx`, with the following Rollup config:

```
// Inspired by https://github.com/babel/babel/blob/main/Gulpfile.mjs
import { nodeResolve } from '@rollup/plugin-node-resolve';

export default {
  input: 'src/index.js',
  output: {
    dir: 'build/',
    format: 'umd',
    name: 'BabelStandaloneJSXOnly',
    sourcemap: true,
  },
  plugins: [nodeResolve()],
};
```

I observed the following error when attempting to build:

```
src/index.js → build/...
[!] Error: 'transform' is not exported by node_modules/@babel/core/lib/index.js, imported by src/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/index.js (2:9)
1: // Inspired by https://github.com/babel/babel/blob/main/packages/babel-standalone/src/index.ts
2: import { transform as babelTransform } from '@babel/core';
            ^
3: import pluginTransformReactJSX from '@babel/plugin-transform-react-jsx';
4: export const transform = (jsx) => babelTransform(jsx, pluginTransformReactJSX);
Error: 'transform' is not exported by node_modules/@babel/core/lib/index.js, imported by src/index.js
    at error (/home/curran/repos/babel-standalone-jsx-only-prototype/node_modules/rollup/dist/shared/rollup.js:198:30)
    ...
```

Next, having studied the [Babel Rollup config in Gulpfile.mjs](https://github.com/babel/babel/blob/main/Gulpfile.mjs), I noticed that `@rollup/plugin-commonjs` is used there, which may solve the named import issue. So I tried the following Rollup config:

```js
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

export default {
  input: 'src/index.js',
  output: {
    dir: 'build/',
    format: 'umd',
    name: 'BabelStandaloneJSXOnly',
    sourcemap: true,
  },
  plugins: [commonjs(), nodeResolve()],
};
```

which then resulted in the following error:

```
src/index.js → build/...
[!] (plugin commonjs--resolver) Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
node_modules/globals/globals.json (2:10)
1: {
2:   "builtin": {
              ^
3:     "Array": false,
4:     "ArrayBuffer": false,
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (/home/curran/repos/babel-standalone-jsx-only-prototype/node_modules/rollup/dist/shared/rollup.js:198:30)
```

Next, having studied the [Babel Rollup config in Gulpfile.mjs](https://github.com/babel/babel/blob/main/Gulpfile.mjs), I noticed that `@rollup/plugin-json` is used there, which may solve the json import issue. So I tried the following Rollup config:

```js
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';

export default {
  input: 'src/index.js',
  output: {
    dir: 'build/',
    format: 'umd',
    name: 'BabelStandaloneJSXOnly',
    sourcemap: true,
  },
  plugins: [commonjs(), nodeResolve(), json()],
};
```

which then resulted in the following error:

```
src/index.js → build/...
(!) Missing shims for Node.js built-ins
Creating a browser bundle that depends on "tty", "util", "os", "assert", "path", "url" and "buffer". You might need to include https://github.com/snowpackjs/rollup-plugin-polyfill-node
(!) Circular dependencies
node_modules/@babel/types/lib/definitions/index.js -> node_modules/@babel/types/lib/definitions/core.js -> node_modules/@babel/types/lib/validators/is.js -> node_modules/@babel/types/lib/validators/isType.js -> node_modules/@babel/types/lib/definitions/index.js
node_modules/@babel/types/lib/definitions/index.js -> node_modules/@babel/types/lib/definitions/core.js -> node_modules/@babel/types/lib/validators/is.js -> node_modules/@babel/types/lib/validators/isPlaceholderType.js -> node_modules/@babel/types/lib/definitions/index.js
node_modules/@babel/types/lib/definitions/index.js -> node_modules/@babel/types/lib/definitions/core.js -> node_modules/@babel/types/lib/validators/is.js -> node_modules/@babel/types/lib/definitions/index.js
...and 16 more
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
tty (guessing 'require$$0$6')
util (guessing 'require$$1')
os (guessing 'require$$0$5')
assert (guessing 'require$$0$7')
path (guessing 'require$$0$8')
fs (guessing 'require$$0$9')
url (guessing 'require$$2$1')
module (guessing 'require$$11')
buffer (guessing 'require$$0$a')
v8 (guessing 'require$$0$b')
```

Next, having studied the [Babel Rollup config in Gulpfile.mjs](https://github.com/babel/babel/blob/main/Gulpfile.mjs), I noticed that `rollup-plugin-polyfill-node` is used there, which may solve the Node built-ins issue. However, `rollup-plugin-polyfill-node` is So I tried the following Rollup config:

```js
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import nodePolyfills from 'rollup-plugin-polyfill-node';

export default {
  input: 'src/index.js',
  output: {
    dir: 'build/',
    format: 'umd',
    name: 'BabelStandaloneJSXOnly',
    sourcemap: true,
  },
  plugins: [commonjs(), nodeResolve(), json(), nodePolyfills()],
};
```

which then resulted in the following error:

```
src/index.js → build/...
(!) Missing shims for Node.js built-ins
Creating a browser bundle that depends on "tty", "util", "os", "assert", "path", "url" and "buffer". You might need to include https://github.com/snowpackjs/rollup-plugin-polyfill-node
(!) Circular dependencies
node_modules/@babel/types/lib/definitions/index.js -> node_modules/@babel/types/lib/definitions/core.js -> node_modules/@babel/types/lib/validators/is.js -> node_modules/@babel/types/lib/validators/isType.js -> node_modules/@babel/types/lib/definitions/index.js
node_modules/@babel/types/lib/definitions/index.js -> node_modules/@babel/types/lib/definitions/core.js -> node_modules/@babel/types/lib/validators/is.js -> node_modules/@babel/types/lib/validators/isPlaceholderType.js -> node_modules/@babel/types/lib/definitions/index.js
node_modules/@babel/types/lib/definitions/index.js -> node_modules/@babel/types/lib/definitions/core.js -> node_modules/@babel/types/lib/validators/is.js -> node_modules/@babel/types/lib/definitions/index.js
...and 16 more
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
tty (guessing 'require$$0$6')
util (guessing 'require$$1')
os (guessing 'require$$0$5')
assert (guessing 'require$$0$7')
path (guessing 'require$$0$8')
fs (guessing 'require$$0$9')
url (guessing 'require$$2$1')
module (guessing 'require$$11')
buffer (guessing 'require$$0$a')
v8 (guessing 'require$$0$b')
created build/ in 5.4s
```

FWIW I also tried `nodePolyfills({include: "**/*.{js,cjs,ts}"})`, but the same error appeared.

At this point I'm feeling a bit stuck. I'm uncertain as to which specific additional parts of the [Babel Rollup config in Gulpfile.mjs](https://github.com/babel/babel/blob/main/Gulpfile.mjs) I need to add to my Rollup config, be it configuration options to the plugins I have alread added, or more plugins. Any input here would be _greatly_ appreciated.

Here's a [minimal reproduction repository (at the commit with the last Rollup config mentioned here)](https://github.com/curran/babel-standalone-jsx-only-prototype/tree/1468083bb30e8826f8aab50c45788a33806ea5f3).

Thanks in advance!

**Comment by JLHwung** [comment]
Alternatively, you can also fork the Babel repo, leave only

https://github.com/babel/babel/blob/ee4576f6c0d25bd0c64a7a891c34e28fc016b974/packages/babel-standalone/src/index.ts#L186

and then run `yarn gulp build-babel-standalone`, which will use our own rollup config and generate a smaller `@babel/standalone` build.

**Comment by nicolo-ribaudo** [comment]
@curran You need to properly configure the `nodeResolve` plugin:
```js
    nodeResolve({
      // by default @babel/core expects to run in Node.js (to load/resolve the config files and presets from the filesystem),
      // but it internally includes support for running in the browser.
      // You can tell rollup to only bundle the files needed to run in the browser, so that it doesn't need to load the
      // fs-related Node.js modules
      browser: true,
      exportConditions: ['browser'],
      // This is needed to use rollup-plugin-polyfill-node
      preferBuiltins: false,
    }),
```

**Comment by nicolo-ribaudo** [comment]
You can test that it works with this `index.js` file:
```js
// Inspired by https://github.com/babel/babel/blob/main/packages/babel-standalone/src/index.ts
import { transform as babelTransform } from '@babel/core';
import pluginTransformReactJSX from '@babel/plugin-transform-react-jsx';
export const transform = (jsx) => babelTransform(jsx, {
    plugins: [pluginTransformReactJSX]
});

console.log(transform("<div>a</div>").code);
```

**Comment by curran** [comment]
@nicolo-ribaudo Thank you so much! I was able to get it to work ([changes here](https://github.com/curran/babel-standalone-jsx-only-prototype/commit/444797fc70c0a1ce8f75f2add7e780656f72fbd4)).

Interestingly, the minified build ends up at 1.08 MB (I tried Uglify and Terser both), whereas [babel-standalone on UNPKG (v7.0.0-beta.3)](https://unpkg.com/browse/babel-standalone@7.0.0-beta.3/babel.min.js)  weighs about the same at 1.05 MB. Any idea why? Is there some chance that unnecessary parsing logic relating to unused plugins is also getting included?

**Comment by ConradSollitt** [comment]
Hi @curran 

I've created something similar that you might be interested in - it's less than 7 kB and only handles JSX. For legacy browsers (IE and older mobile Safari) it will download Babel Standalone and still works.

Docs are here (it contains links to many examples):

https://github.com/dataformsjs/dataformsjs/blob/master/docs/jsx-loader.md
