### ISSUE TITLE
Destructuring issue while nesting them into function parameters

### ISSUE THREAD

**Issue by nfroidure** [babel/babel#1462]
Not sure if it is the desired behavior.

```
function f ({ name: {n}, val: v }) {
    console.log(n, v)
}
f()
```
Gives:
/home/nfroidure/projects/whook/test.js:4
      var n = _ref.name.n;
                  ^
TypeError: Cannot read property 'name' of undefined
    at f (/home/nfroidure/projects/whook/test.js:1:23)
    at Object.<anonymous> (/home/nfroidure/projects/whook/test.js:4:1)
    at Module._compile (module.js:460:26)
    at normalLoader (/home/nfroidure/projects/whook/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:147:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/nfroidure/projects/whook/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/home/nfroidure/projects/whook/node_modules/babel/bin/_babel-node:111:12)
    at Module._compile (module.js:460:26)

```
node node_modules/babel/bin/babel-node --version
5.2.15
```

**Comment by sebmck** [comment]
Expected behaviour. You need to assign a default.

```javascript
function f ({ name: {n}, val: v } = {}) {
    console.log(n, v)
}
f()
```

**Comment by nfroidure** [comment]
Thanks!

**Comment by nfroidure** [comment]
Doing so still lead to an issue:

/home/nfroidure/projects/whook/test.js:6
      var n = _ref.name.n;
                       ^
TypeError: Cannot read property 'n' of undefined
    at f (/home/nfroidure/projects/whook/test.js:1:19)
    at Object.<anonymous> (/home/nfroidure/projects/whook/test.js:4:1)
    at Module._compile (module.js:460:26)
    at normalLoader (/home/nfroidure/projects/whook/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:147:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/nfroidure/projects/whook/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/home/nfroidure/projects/whook/node_modules/babel/bin/_babel-node:111:12)
    at Module._compile (module.js:460:26)

**Comment by sebmck** [comment]
You need to specify defaults for those too then:

```javascript
function f ({ name: {n} = {}, val: v } = {}) {
    console.log(n, v)
}
f()
```

**Comment by nfroidure** [comment]
Had to do this:
```
function f ({ name: {n} = {}, val: v } = {n:{}}) {
      console.log(n, v)
}
f()
f({})
```
That's pretty verbose. Will ES6 engines implement the same behavior?

**Comment by sebmck** [comment]
Yep.

**Comment by nfroidure** [comment]
Too bad :(

**Comment by nfroidure** [comment]
Thanks anyway for your help. Have a nice day.
