### ISSUE TITLE
[Bug]: `@babel/plugin-transform-reserved-words` not working

### ISSUE THREAD

**Issue by jackprogramsjp** [babel/babel#14690]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
const static = require("node-static");
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "node": "10.11.0"
        }
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-proposal-logical-assignment-operators",
    "@babel/plugin-transform-reserved-words"
  ]
}
```

### Current and expected behavior

```bash
> babel wrapper -d wrapper-build --copy-files --ignore wrapper/node_modules

SyntaxError: /Users/jackprograms/Wrapper-Offline-Electron/wrapper/server.js: Unexpected reserved word 'static'. (8:6)

   6 | const url = require("url");
   7 | const formidable = require("formidable");
>  8 | const static = require("node-static");
     |       ^
   9 |
  10 | /**
  11 |  * routes
    at instantiate (/Users/jackprograms/Wrapper-Offline-Electron/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/Users/jackprograms/Wrapper-Offline-Electron/node_modules/@babel/parser/lib/index.js:358:12)
    at Parser.raise (/Users/jackprograms/Wrapper-Offline-Electron/node_modules/@babel/parser/lib/index.js:3341:19)
    at Parser.checkReservedWord (/Users/jackprograms/Wrapper-Offline-Electron/node_modules/@babel/parser/lib/index.js:14151:12)
    at Parser.parseIdentifierName (/Users/jackprograms/Wrapper-Offline-Electron/node_modules/@babel/parser/lib/index.js:14090:12)
    at Parser.parseIdentifier (/Users/jackprograms/Wrapper-Offline-Electron/node_modules/@babel/parser/lib/index.js:14060:23)
    at Parser.parseBindingAtom (/Users/jackprograms/Wrapper-Offline-Electron/node_modules/@babel/parser/lib/index.js:11929:17)
    at Parser.parseVarId (/Users/jackprograms/Wrapper-Offline-Electron/node_modules/@babel/parser/lib/index.js:15393:20)
    at Parser.parseVar (/Users/jackprograms/Wrapper-Offline-Electron/node_modules/@babel/parser/lib/index.js:15368:12)
    at Parser.parseVarStatement (/Users/jackprograms/Wrapper-Offline-Electron/node_modules/@babel/parser/lib/index.js:15171:10) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'UnexpectedReservedWord',
  loc: Position { line: 8, column: 6, index: 160 },
  pos: [Getter/Setter]
}
```
There is a "Unexpected reserved word 'static'." syntax error, which `@babel/plugin-transform-reserved-words` is supposed to detect that `static` is a reserved word, so they would suppose to change it to `_static` instead to not have this error.

### Environment

```
  System:
    OS: macOS 12.4
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
  npmPackages:
    @babel/cli: ^7.17.10 => 7.17.10 
    @babel/core: ^7.18.5 => 7.18.5 
    @babel/plugin-proposal-logical-assignment-operators: ^7.17.12 => 7.17.12 
    @babel/plugin-proposal-optional-chaining: ^7.17.12 => 7.17.12 
    @babel/plugin-transform-reserved-words: ^7.17.12 => 7.17.12 
    @babel/preset-env: ^7.18.2 => 7.18.2 
```

**Comment by JLHwung** [comment]
Per [spec](https://tc39.es/ecma262/#sec-keywords-and-reserved-words), `static` is reserved word in strict mode. By default `@babel/core` assumes that your input source is `"module"`. You can set `sourceType` to `"script"`: See also https://babeljs.io/docs/en/options#sourcetype

```json
{
  "sourceType": "script",
  "presets": []
}
```
