### ISSUE TITLE
[Bug]: Build failure "RangeError: Invalid array length"

### ISSUE THREAD

**Issue by bryceharrington** [babel/babel#14715]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Re-building of node-babel7 7.18.7+~cs214.249.185-1 in Debian and Ubuntu is failing with the error listed below.

### Current and expected behavior

[17:01:19] 'build-babel' errored after 1.15 s
[17:01:19] RangeError: Invalid array length
    at new BaseWorkerPool (/usr/share/nodejs/jest-worker/build/base/BaseWorkerPool.js:44:21)
    at new WorkerPool (/usr/share/nodejs/jest-worker/build/WorkerPool.js:18:1)
    at new Worker (/usr/share/nodejs/jest-worker/build/index.js:135:26)
    at createWorker (file:///build/1st/node-babel7-7.18.6+~cs214.249.185/Gulpfile.mjs:229:18)
    at buildBabel (file:///build/1st/node-babel7-7.18.6+~cs214.249.185/Gulpfile.mjs:239:18)
    at file:///build/1st/node-babel7-7.18.6+~cs214.249.185/Gulpfile.mjs:544:32
    at taskWrapper (/usr/share/nodejs/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
    at asyncRunner (/usr/share/nodejs/async-done/index.js:55:18)
[17:01:19] 'build' errored after 11 s

### Environment

This is against babel 7.18.7+~cs214.249.185-1.
Prior (successful) version in Ubuntu was 7.12.12+~cs150.141.84-8.  Debian appears to have had success with 7.18.5+~cs214.249.185-1, so this may be a recent regression?

**Comment by nicolo-ribaudo** [comment]
We never saw this error before and we build the monorepo a lot of times, so unfortunately you will have to debug it yourself :sweat_smile: 

What code do you see at line 44 of `/usr/share/nodejs/jest-worker/build/base/BaseWorkerPool.js`, where the error is thrown? In my local clone I have
```js
function _interopRequireWildcard(obj, nodeInterop) {
  if (!nodeInterop && obj && obj.__esModule) { // <--- Line 44
    return obj;
  }
```
which is very unlikely to throw that error.

**Comment by JLHwung** [comment]
const numWorkers = require("os").cpus().length / 2 - 1;

I think our build scripts can't handle single core cpu, in this case the numWorkers is negative.
