### ISSUE TITLE
Error "export default" in the files that use the regenerator

### ISSUE THREAD

**Issue by Smert** [babel/babel#1471]
```
var q = {};

function * a(){
  yield 1;
  return 2;
}

export default q;
```

**Comment by sebmck** [comment]
Do you have the stack trace? What version are you on? [I can't replicate this in the REPL.](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=var%20q%20%3D%20%7B%7D%3B%0A%0Afunction%20*%20a()%7B%0A%20%20yield%201%3B%0A%20%20return%202%3B%0A%7D%0A%0Aexport%20default%20q%3B)

**Comment by Smert** [comment]
```
AssertionError: /home/dmitry/WebstormProjects/adserving/src/test.js: did not recognize object of type "ExportDefaultDeclaration"
    at Object.getFieldNames (/home/dmitry/WebstormProjects/adserving/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:595:16)
    at visitChildren (/home/dmitry/WebstormProjects/adserving/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:203:32)
    at Visitor.PVp.visitWithoutReset (/home/dmitry/WebstormProjects/adserving/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at NodePath.each (/home/dmitry/WebstormProjects/adserving/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:96:22)
    at visitChildren (/home/dmitry/WebstormProjects/adserving/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:199:14)
    at Visitor.PVp.visitWithoutReset (/home/dmitry/WebstormProjects/adserving/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/home/dmitry/WebstormProjects/adserving/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/home/dmitry/WebstormProjects/adserving/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at Visitor.PVp.visit (/home/dmitry/WebstormProjects/adserving/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:124:25)
    at Function.transform (/home/dmitry/WebstormProjects/adserving/node_modules/regenerator/lib/visit.js:29:11)
```

**Comment by sebmck** [comment]
Uninstall `regenerator` and install `babel` again. `babel` needs to have it's own version of `regenerator` installed so it can patch `ast-types` with some definitions. Currently waiting on benjamn/ast-types#112 when this crappy monkey patching can be removed.

**Comment by ai** [comment]
Maybe there is a some hack to have `regenerator` locally and in `babel`?

**Comment by donaldpipowitch** [comment]
I have the same problem, because I have `recast` installed on the same level as `babel`. It seems `regenerator` uses `recast`.

**Comment by donaldpipowitch** [comment]
> babel needs to have it's own version of regenerator installed so it can patch ast-types with some definitions.

I _think_ I have problems of this again and it is super hard to debug. Maybe Babel should handle this differently. Can't you fork Regenerator and treat it as a "different" module, so others can install and require Regenerator and don't affect Babel...?

Somewhere in my install process I get this stack trace with the first two lines repeated infinitely:
````
    at Visitor.PVp.visitWithoutReset (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at Visitor.PVp.visit (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:124:25)
    at Function.transform (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/node_modules/regenerator/lib/visit.js:30:11)
    at NodePath.exit (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformers/other/regenerator.js:41:34)
    at NodePath.call (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/context.js:61:28)
    at NodePath.visit (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/context.js:112:12)
    at TraversalContext.visitMultiple (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:92:16)
    at TraversalContext.visit (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:122:19)
    at Function.traverse.node (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/traversal/index.js:72:17)
    at NodePath.visit (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/context.js:111:26)
    at TraversalContext.visitSingle (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:112:12)
    at TraversalContext.visit (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:124:19)
    at Function.traverse.node (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/traversal/index.js:72:17)
    at Object.traverse [as default] (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/traversal/index.js:55:14)
    at PluginPass.transform (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/transformation/plugin-pass.js:44:27)
    at File.transform (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:596:12)
    at /Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/transformation/pipeline.js:131:19
    at File.wrap (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:610:16)
    at Pipeline.transform (/Users/foo/Workspace/ws/node_modules/babel/node_modules/babel-core/lib/babel/transformation/pipeline.js:128:17)
    at Object.exports.transform (/Users/foo/Workspace/ws/node_modules/babel/bin/babel/util.js:34:22)
    at Object.exports.compile (/Users/foo/Workspace/ws/node_modules/babel/bin/babel/util.js:43:20)
    at write (/Users/foo/Workspace/ws/node_modules/babel/bin/babel/dir.js:17:21)
    at handleFile (/Users/foo/Workspace/ws/node_modules/babel/bin/babel/dir.js:38:7)
    at /Users/foo/Workspace/ws/node_modules/babel/bin/babel/dir.js:54:9
    at arrayEach (/Users/foo/Workspace/ws/node_modules/babel/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/foo/Workspace/ws/node_modules/babel/node_modules/lodash/index.js:3345:13)
    at handle (/Users/foo/Workspace/ws/node_modules/babel/bin/babel/dir.js:52:9)
    at arrayEach (/Users/foo/Workspace/ws/node_modules/babel/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/foo/Workspace/ws/node_modules/babel/node_modules/lodash/index.js:3345:13)
    at module.exports (/Users/foo/Workspace/ws/node_modules/babel/bin/babel/dir.js:61:5)
    at Object.<anonymous> (/Users/foo/Workspace/ws/node_modules/babel/bin/babel/index.js:145:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
````

**Comment by sebmck** [comment]
> Can't you fork Regenerator and treat it as a "different" module

Nah, last time I did that I got yelled at. See #313.

**Comment by donaldpipowitch** [comment]
I see :(
