### ISSUE TITLE
[Bug]: Invalid "Missing initializer in const declaration" error reported in .d.ts files

### ISSUE THREAD

**Issue by michaldudak** [babel/babel#14871]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import * as babel from "@babel/core";

const source = `
export const foo: string;
`;

babel.parse(source, {
  configFile: false,
  filename: "source.d.ts",
  plugins: ["@babel/plugin-syntax-typescript"],
});

```

### Current and expected behavior

After updating @babel/parser from 7.17.3 to 7.17.7, parsing .d.ts files, as shown above, fails with the following error:
```
SyntaxError: C:\Users\Michal\Desktop\babel-repro\source.d.ts: Missing initializer in const declaration. (2:24)

  1 |
> 2 | export const foo: string;
    |                         ^
  3 |
    at instantiate (C:\Users\Michal\Desktop\babel-repro\node_modules\@babel\parser\lib\index.js:72:32)
    at constructor (C:\Users\Michal\Desktop\babel-repro\node_modules\@babel\parser\lib\index.js:358:12)
    at Object.raise (C:\Users\Michal\Desktop\babel-repro\node_modules\@babel\parser\lib\index.js:3334:19)
    at Object.parseVar (C:\Users\Michal\Desktop\babel-repro\node_modules\@babel\parser\lib\index.js:15292:16)
    at Object.parseVarStatement (C:\Users\Michal\Desktop\babel-repro\node_modules\@babel\parser\lib\index.js:15085:10)
    at Object.parseVarStatement (C:\Users\Michal\Desktop\babel-repro\node_modules\@babel\parser\lib\index.js:10243:31)
    at Object.parseStatementContent (C:\Users\Michal\Desktop\babel-repro\node_modules\@babel\parser\lib\index.js:14631:21)
    at Object.parseStatementContent (C:\Users\Michal\Desktop\babel-repro\node_modules\@babel\parser\lib\index.js:10284:18)
    at Object.parseStatement (C:\Users\Michal\Desktop\babel-repro\node_modules\@babel\parser\lib\index.js:14556:17)
    at Object.parseExportDeclaration (C:\Users\Michal\Desktop\babel-repro\node_modules\@babel\parser\lib\index.js:15932:17) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'DeclarationMissingInitializer',
  loc: Position { line: 2, column: 24, index: 25 },
  pos: [Getter/Setter]
}
```

The official TypeScript compiler does not complain about this sample code.

### Environment

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - ~\node_modules\.bin\npm.CMD
  npmPackages:
    @babel/core: ^7.18.13 => 7.18.13
    @babel/plugin-syntax-typescript: 7.16.7 => 7.16.7

**Comment by nicolo-ribaudo** [comment]
We should expose the `dts` option of the `typescript` plugin of `@babel/parser` to `@babel/plugin-syntax-typescript`.

**Comment by nicolo-ribaudo** [comment]
@AnmolBansalDEV I saw in other issues that you are looking for a good first issue: this could be it!

`@babel/plugin-syntax-typescript` currently accepts a `disallowAmbiguousJSXLike` option, and "forwards" it to the parser: https://github.com/babel/babel/blob/ab5b91ddf63a98d1eb8737ea34cc9502c44244b6/packages/babel-plugin-syntax-typescript/src/index.ts#L41

We should do something similar for [the `dts` option](https://babeljs.io/docs/en/babel-parser#plugins-options). You can add a test in https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-typescript/test/fixtures, adding a folder `dts/enabled` with the input code as in the above issue description and this config:
```json
{
  "plugins": [["syntax-typescript", { "dts": true }]]
}
```

**Comment by AnmolBansalDEV** [comment]
Thank you @nicolo-ribaudo for suggesting! Right now, I'm traveling, I'll start working on this issue next week. Thank you for your cooperation!

**Comment by nicolo-ribaudo** [comment]
Awesome! I'm assigning this to you :)

**Comment by oceandrama** [comment]
@nicolo-ribaudo I could help with this issue, if @AnmolBansalDEV doesn't mind

**Comment by sanyamgandhak** [comment]
Hi there ,
Please assign to me

**Comment by liuxingbaoyu** [comment]
https://github.com/babel/babel/pull/14923
Hi, this issue has been fixed, just waiting for the minor release,
