### ISSUE TITLE
[Bug]: replacing a ClassDeclaration with another of the same name causes duplicate declaration error

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel#14881]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const { parse } = require('@babel/parser')
const traverse = require('@babel/traverse').default
const template = require('@babel/template')

const ast = parse('class Foo { }')

traverse(ast, {
  ClassDeclaration(path) {
    path.replaceWith(template.statement('class Foo { foo() { } }')())
  },
})

```

### Configuration file name

package.json

### Configuration

N/A

### Current and expected behavior

Replacing `class Foo` with a different `class Foo` should work just fine (there's only one `Foo` in scope when all is said and done).  Instead the old `class Foo` binding doesn't get removed from the scope and it throws this error when registering the new `class Foo`:

```
/Users/andy/github/codemodsquad/astx/node_modules/.pnpm/@babel+traverse@7.18.13/node_modules/@babel/traverse/lib/scope/index.js:481
      throw this.hub.buildError(id, `Duplicate declaration "${name}"`, TypeError);
                     ^

TypeError: Cannot read properties of undefined (reading 'buildError')
    at Scope.checkBlockScopedCollisions (/Users/andy/github/codemodsquad/astx/node_modules/.pnpm/@babel+traverse@7.18.13/node_modules/@babel/traverse/lib/scope/index.js:481:22)
    at Scope.registerBinding (/Users/andy/github/codemodsquad/astx/node_modules/.pnpm/@babel+traverse@7.18.13/node_modules/@babel/traverse/lib/scope/index.js:642:16)
    at Scope.registerDeclaration (/Users/andy/github/codemodsquad/astx/node_modules/.pnpm/@babel+traverse@7.18.13/node_modules/@babel/traverse/lib/scope/index.js:587:12)
    at BlockScoped (/Users/andy/github/codemodsquad/astx/node_modules/.pnpm/@babel+traverse@7.18.13/node_modules/@babel/traverse/lib/scope/index.js:300:12)
    at newFn (/Users/andy/github/codemodsquad/astx/node_modules/.pnpm/@babel+traverse@7.18.13/node_modules/@babel/traverse/lib/visitors.js:222:17)
    at Scope.crawl (/Users/andy/github/codemodsquad/astx/node_modules/.pnpm/@babel+traverse@7.18.13/node_modules/@babel/traverse/lib/scope/index.js:815:9)
    at Scope.init (/Users/andy/github/codemodsquad/astx/node_modules/.pnpm/@babel+traverse@7.18.13/node_modules/@babel/traverse/lib/scope/index.js:793:12)
    at NodePath.setScope (/Users/andy/github/codemodsquad/astx/node_modules/.pnpm/@babel+traverse@7.18.13/node_modules/@babel/traverse/lib/path/context.js:146:30)
    at NodePath.replaceWith (/Users/andy/github/codemodsquad/astx/node_modules/.pnpm/@babel+traverse@7.18.13/node_modules/@babel/traverse/lib/path/replacement.js:154:8)
    at ClassDeclaration (/Users/andy/github/codemodsquad/astx/temp.js:15:10)
```

### Environment

  System:
    OS: macOS 12.5
  Binaries:
    Node: 16.15.1 - ~/Library/pnpm/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/Library/pnpm/npm
  npmPackages:
    @babel/cli: ^7.12.10 => 7.18.10 
    @babel/code-frame: ^7.18.6 => 7.18.6 
    @babel/core: ^7.18.13 => 7.18.13 
    @babel/generator: ^7.18.13 => 7.18.13 
    @babel/node: ^7.13.13 => 7.18.10 
    @babel/parser: ^7.18.13 => 7.18.13 
    @babel/plugin-transform-runtime: ^7.12.10 => 7.18.10 
    @babel/preset-env: ^7.18.10 => 7.18.10 
    @babel/preset-typescript: ^7.18.6 => 7.18.6 
    @babel/register: ^7.12.10 => 7.18.9 
    @babel/runtime: ^7.18.9 => 7.18.9 
    @babel/template: ^7.18.10 => 7.18.10 
    @babel/traverse: ^7.18.13 => 7.18.13 
    @babel/types: ^7.18.13 => 7.18.13 
    babel-eslint: ^10.1.0 => 10.1.0 
    babel-parse-wild-code: ^1.2.0 => 1.2.0 
    babel-plugin-istanbul: ^6.0.0 => 6.1.1 
    eslint: ^7.18.0 => 7.32.0 

### Possible solution

In `NodePath.replaceWith`, I don't see any code path intended to remove bindings of the nodes that got replaced.  Shouldn't it be doing that, before registering bindings for the new nodes?

### Additional context

I'm developing [`astx`](https://github.com/codemodsquad/astx/tree/beta-babel), a structural search-and-replace code refactoring tool.  Users could possibly find and replace a `ClassDeclaration`, and they might leave its name the same.  One such testcase in `astx` triggered this error.

**Comment by jedwards1211** [comment]
Maybe I misunderstand what `replaceWith` is intended for?

Here's a workaround:

```js
traverse(ast, {
  ClassDeclaration(path) {
    const next = path.getNextSibling()
    if (next) {
      path.remove()
      next.insertBefore(template.statement('class Foo { foo() { } }')())
    }
  },
})
```

**Comment by jedwards1211** [comment]
More evidence of the problem: if I replace `class Foo` with `class Bar`, the `Foo` binding is still present...but now it refers to `class Bar`:

```js
const { parse } = require('@babel/parser')
const traverse = require('@babel/traverse').default
const template = require('@babel/template')
const generate = require('@babel/generator').default

const ast = parse('class Foo { }')

traverse(ast, {
  ClassDeclaration(path) {
    const [replacement] = path.replaceWith(
      template.statement('class Bar { foo() { } }')()
    )
    replacement.skip()
    console.log(path.scope.getBinding('Foo').path.node)
  },
})
```

Output:
```
{
  type: 'ClassDeclaration',
  id: { type: 'Identifier', name: 'Bar', loc: undefined },
  body: { type: 'ClassBody', body: [ [Object] ], loc: undefined },
  superClass: null,
  loc: undefined,
  trailingComments: [],
  leadingComments: [],
  innerComments: []
}
```

**Comment by jedwards1211** [comment]
@liuxingbaoyu the fix isn't going to be released for babel 7?

**Comment by liuxingbaoyu** [comment]
Not necessarily, I added it to the BABEL8 milestone because a fundamental fix is likely to bring breaking changes.

**Comment by benjie** [comment]
Thanks to @jedwards1211's solution here's a monkey-patch that may or may not solve the issue for others:

```ts
import { NodePath } from "@babel/traverse";

const $$patched = Symbol("babel-14881-hack");
/** @see {@link https://github.com/babel/babel/issues/14881} */
function patch(scope: any) {
  if (!scope[$$patched]) {
    scope[$$patched] = true;
    const original = scope._replaceWith;
    scope._replaceWith = function (...args: any[]) {
      if (!this.opts?.noScope) {
        this._removeFromScope();
      }
      return original.apply(this, args);
    };
  }
}
patch(NodePath.prototype);
```
