### ISSUE TITLE
Error when running lab with coverage on babel compiled code

### ISSUE THREAD

**Issue by corbinu** [babel/babel#1505]
So I have a bit of code compiled with babel and not sure if this is a lab or babel issue so will cross link issues. Lab runs fine with out coverage but get this error with coverage enabled:
```
./dist/test/couchbase/doc.js',5);continue _function;
                                                                    ^^^^^^^^^
SyntaxError: Undefined label '_function'
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.require.extensions.(anonymous function) [as .js] (./node_modules/lab/lib/coverage.js:29:36)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at ./node_modules/lab/lib/cli.js:105:23
    at Array.forEach (native)
    at Object.internals.traverse (./node_modules/lab/lib/cli.js:101:19)
    at Object.exports.run (./node_modules/lab/lib/cli.js:50:29)
    at Object.<anonymous> (./node_modules/lab/bin/lab:3:23)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:472:10)
    at startup (node.js:124:18)
    at node.js:959:3
```
Here is the compiled source
```
var _get = function get(_x2, _x3, _x4) { var _again = true; _function: while (_again) { desc = parent = getter = undefined; _again = false; var object = _x2,
    property = _x3,
    receiver = _x4; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x2 = parent; _x3 = property; _x4 = receiver; _again = true; continue _function; } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };
```

**Comment by corbinu** [comment]
https://github.com/babel/babel/issues/1505

**Comment by corbinu** [comment]
https://github.com/hapijs/lab/issues/355

**Comment by sebmck** [comment]
What's the original and compiled source? The compiled source that you provided definently isn't all of it.

**Comment by corbinu** [comment]
Original:
```
import {install as installSourceMaps} from "source-map-support";
installSourceMaps();

import Lab from "lab";

import {data} from "../helpers";

import connection from "./connection";

import {Model} from "../../mrstore";
import {StoreCouchbase as Store} from "../../mrstore";

let lab = exports.lab = Lab.script();

lab.experiment("Couchbase Doc", function () {
	class User extends Model {
		constructor(data={}) {
			super(data);
		}
	}

	let user;

	lab.before(function (done) {
		connection((err, conn) => {
			if (err) return done(err);

			let store = new Store(conn);

			User.setup("User", data.schema.user).setStore(store);

			User.install().then(() => {
				done();
			}, done).catch(done);
		});
	});

	lab.test("save new", function (done) {
		user = new User(data.users[0]);

		user.save().then(() => {
			data.verify.blues1(user);

			return User.get(user.id);
		}, done).then((doc) => {

			data.verify.blues1(doc);

			done();
		}, done).catch(done);
	});

	lab.test("save updated", function (done) {

		user.name = {};
		user.username = "replaced";
		user.password = "replaced";
		user.address = {};
		user.roles = [];

		delete user.email;

		user.save().then(() => {
			data.verify.replaced(user);

			return User.get(user.id);
		}, done).then((doc) => {

			data.verify.replaced(doc);

			done();
		}, done).catch(done);
	});
});
```

compiled
```
"use strict";

var _get = function get(_x2, _x3, _x4) { var _again = true; _function: while (_again) { desc = parent = getter = undefined; _again = false; var object = _x2,
    property = _x3,
    receiver = _x4; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x2 = parent; _x3 = property; _x4 = receiver; _again = true; continue _function; } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) subClass.__proto__ = superClass; }

var _sourceMapSupport = require("source-map-support");

var _lab = require("lab");

var _lab2 = _interopRequireDefault(_lab);

var _helpers = require("../helpers");

var _connection = require("./connection");

var _connection2 = _interopRequireDefault(_connection);

var _mrstore = require("../../mrstore");

_sourceMapSupport.install();

var lab = exports.lab = _lab2["default"].script();

lab.experiment("Couchbase Doc", function () {
	var User = (function (_Model) {
		function User() {
			var data = arguments[0] === undefined ? {} : arguments[0];

			_classCallCheck(this, User);

			_get(Object.getPrototypeOf(User.prototype), "constructor", this).call(this, data);
		}

		_inherits(User, _Model);

		return User;
	})(_mrstore.Model);

	var user = undefined;

	lab.before(function (done) {
		_connection2["default"](function (err, conn) {
			if (err) return done(err);

			var store = new _mrstore.StoreCouchbase(conn);

			User.setup("User", _helpers.data.schema.user).setStore(store);

			User.install().then(function () {
				done();
			}, done)["catch"](done);
		});
	});

	lab.test("save new", function (done) {
		user = new User(_helpers.data.users[0]);

		user.save().then(function () {
			_helpers.data.verify.blues1(user);

			return User.get(user.id);
		}, done).then(function (doc) {

			_helpers.data.verify.blues1(doc);

			done();
		}, done)["catch"](done);
	});

	lab.test("save updated", function (done) {

		user.name = {};
		user.username = "replaced";
		user.password = "replaced";
		user.address = {};
		user.roles = [];

		delete user.email;

		user.save().then(function () {
			_helpers.data.verify.replaced(user);

			return User.get(user.id);
		}, done).then(function (doc) {

			_helpers.data.verify.replaced(doc);

			done();
		}, done)["catch"](done);
	});
});
```

**Comment by sebmck** [comment]
This would be a bug with hapi.js. Doesn't look like they support loop labels.

You can "fix" this (you'll get worse performance though) by disabling the `es6.tailCall` transformer:

**.babelrc**

```javascript
{
  "blacklist": ["es6.tailCall"]
}
```

or

```sh
$ babel --blacklist es6.tailCall script.js
```

or

```javascript
require("babel-core").transform("code", { blacklist: ["es6.tailCall"] });
```

**Note** that you may also experience issues with block scoping as it also using loop labels.

**Comment by corbinu** [comment]
Thanks!
