### ISSUE TITLE
[Bug]: Wrong error name

### ISSUE THREAD

**Issue by p51lee** [babel/babel#15105]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
"use strict";
let { 0 : x } = { get 0 ( ) { return super [ 0 ] = 0 ; } } ;
```

### Current and expected behavior

Running the `input.js` code should throw `TypeError`:
```js
// input.js
"use strict";
let { 0 : x } = { get 0 ( ) { return super [ 0 ] = 0 ; } } ;
```
```console
❯ node input.js
input.js:2
let { 0 : x } = { get 0 ( ) { return super [ 0 ] = 0 ; } } ;
                                                 ^

TypeError: Cannot redefine property: 0
    at get 0 [as 0] (/Users/p51lee/dev/esmeta-plrg/.test.js:2:50)
    at Object.<anonymous> (/Users/p51lee/dev/esmeta-plrg/.test.js:2:11)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

However, transpilation result throws `Error`:
```js
// output.js
...
throw new Error("failed to set property");
...
```
```console
❯ node output.js
output.js:38
    throw new Error("failed to set property");
    ^

Error: failed to set property
    at _set (/Users/p51lee/dev/esmeta-plrg/.test2.js:38:11)
    at get 0 [as 0] (/Users/p51lee/dev/esmeta-plrg/.test2.js:72:14)
    at Object.<anonymous> (/Users/p51lee/dev/esmeta-plrg/.test2.js:75:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

### Environment

[Reproduction on Babel's own REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=EQVwzgpgBGAuBOBLAxrYBuAUAGwrKA3lAAxQBcUAHlAL5QC8hUA5niVABRQCUT8eIeADsYIAA4R4UANrsAug3bpaK9EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.20.0&externalPlugins=&assumptions=%7B%7D)

### Possible solution

Possibly it will be solved by changing the function `_set` that throws `Error("failed to set property")` to throw `TypeError` instead.

**Comment by SuperSodaSea** [comment]
Another helper with incorrect error type:

https://github.com/babel/babel/blob/859daa3c185d18901106d8e6c39898ba1ce8e8f4/packages/babel-helpers/src/helpers.ts#L651-L655

Should throw `ReferenceError` instead of `Error` in my opinion. (Example in [REPL](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEAa0G9oG1YF1oF5oEZoF8BuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=&version=7.20.6&externalPlugins=&assumptions=%7B%7D))
