### ISSUE TITLE
[Bug]: Assigning `new.target` as a default parameter with same name throws `TypeError`

### ISSUE THREAD

**Issue by p51lee** [babel/babel#15139]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
var f = function x ( ... { x = new . target } ) { }
class C extends f { } 
new C ( ) ;
```

### Current and expected behavior

`input.js` is expected to be terminated normally:
```console
$ node input.js # no error
```
However, `output.js` results in `TypeError`:
```console
$ node output.js
output.js:17
    x = _ref$x === void 0 ? this instanceof x ? this.constructor : void 0 : _ref$x;
                                 ^

TypeError: Right-hand side of 'instanceof' is not an object
    at new x (output.js:17:34)
    at C._createSuperInternal output.js:7:283)
    at new C (output.js:26:19)
    at Object.<anonymous> (output.js:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Environment

[Reproduction on babel's own REPL](https://babeljs.io/repl#?browsers=since%202015&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=G4QwTgBAZhC80FcB2BjALgSwPZIgDwgAoIA6MiAb3zgiQFMB3UiNcAczrQgF8IBKSjwBQKADYgAzhIgBhCHTxo6SACbSYVYfSZziAgNxCgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.20.1&externalPlugins=&assumptions=%7B%7D)

**Comment by SuperSodaSea** [comment]
Seems that this is similar to #14406, but it was not completely fixed.

This one is correctly unshadowed:

```js
function x() { let x = new.target; }
// --->
function x() {
  var _x = this instanceof x ? this.constructor : void 0;
}
```

However, this one is incorrect:

```js
let f = function x() { let x = new.target; }
// --->
var f = function x() {
  var x = this instanceof x ? this.constructor : void 0;
};
```
