### ISSUE TITLE
[Bug]: Babel Unable to Transpile React Native Components in a Monorepo

### ISSUE THREAD

**Issue by mikecfisher** [babel/babel#15166]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

*Test Code*
```ts
import React from 'react'
import { render } from '@testing-library/react-native'
import { Button } from 'ui'

describe('<App />', () => {
  it('exists', () => {
    const { container } = render(<Button />)

    expect(container).toBeTruthy()
  })
})
```

*ui code*
```ts
import * as React from 'react'
import { Text } from 'react-native'
export const Button = () => {
  return <Text>Boop</Text>
}

```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = function (api) {
  api.cache(true)
  return {
    plugins: ['nativewind/babel'],
    presets: ['babel-preset-expo'],
  }
}
```

### Current and expected behavior

I'm trying to use babel to transpile a test in React Native App in a pnpm managed monorepo.

I have an apps/mobile folder and a packages/ui folder.

I have a very simple unit test that looks like the code above

If I try to import a React Native component from ui into apps/mobile and test it with Jest I get an error.

```
● <App /> › exists

    Invariant Violation: __fbBatchedBridgeConfig is not set, cannot invoke native modules

      2 | import { Text } from 'react-native'
      3 | export const Button = () => {
    > 4 |   return <Text>Boop</Text>
        |           ^
      5 | }
      6 |

      at invariant (../../node_modules/invariant/invariant.js:40:15)
      at Object.invariant (../../node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:181:3)
      at Object.require (../../node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:11:23)
      at Object.<anonymous> (../../node_modules/react-native/Libraries/Utilities/NativePlatformConstantsIOS.js:12:1)
      at Object.<anonymous> (../../node_modules/react-native/Libraries/Utilities/Platform.ios.js:11:1)
      at Object.<anonymous> (../../node_modules/react-native/Libraries/NativeComponent/ViewConfigIgnore.js:11:1)
      at Object.<anonymous> (../../node_modules/react-native/Libraries/NativeComponent/StaticViewConfigValidator.js:12:1)
      at Object.<anonymous> (../../node_modules/react-native/Libraries/NativeComponent/NativeComponentRegistry.js:11:1)
      at Object.<anonymous> (../../node_modules/react-native/Libraries/Components/View/ViewNativeComponent.js:11:1)
      at Object.<anonymous> (../../node_modules/react-native/Libraries/Components/View/View.js:13:1)
      at Object.<anonymous> (../../node_modules/react-native/Libraries/Pressability/PressabilityDebug.js:15:1)
      at Object.<anonymous> (../../node_modules/react-native/Libraries/Text/Text.js:11:1)
      at Object.require [as Text] (../../node_modules/react-native/index.js:211:12)
      at Button (../../packages/ui/Button.tsx:4:11)
      at renderWithHooks (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6097:18)
      at mountIndeterminateComponent (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10432:13)
      at beginWork (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11661:16)
      at performUnitOfWork (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15265:12)
      at workLoopSync (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15201:5)
      at renderRootSync (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15173:7)
      at performSyncWorkOnRoot (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14880:20)
      at flushSyncCallbacks (../../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2533:22)
      at flushActQueue (../../node_modules/react/cjs/react.development.js:2665:24)
      at act (../../node_modules/react/cjs/react.development.js:2519:11)
      at actImplementation (node_modules/@testing-library/react-native/src/act.ts:34:25)
      at renderWithAct (node_modules/@testing-library/react-native/src/render.tsx:118:3)
      at renderWithAct (node_modules/@testing-library/react-native/src/render.tsx:47:20)
      at Object.<anonymous> (src/app.test.tsx:8:33)
```

Generally if I see a `__fbBatchedBridgeConfig is not set, cannot invoke native modules` error that makes me think there is a native module being imported into a test. However I'm just testing the most basic React Native component. 

Because of this I believe this is happening because babel is incorrectly transpiling the React Native component from the `packages/ui` folder. 

### Environment

 System:
    OS: macOS 12.5
  Binaries:
    Node: 18.11.0 - ~/.nodenv/versions/18.11.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nodenv/versions/18.11.0/bin/npm
  npmPackages:
    react-native: 0.69.6 => 0.69.6

**Comment by liuxingbaoyu** [comment]
The plugins and presets you're using appear to be third party, we don't know about this.
If you want to filter certain files, you can refer to this https://babeljs.io/docs/en/options#overrides
