### ISSUE TITLE
Syntax errors in bluebird coroutine results in vague error

### ISSUE THREAD

**Issue by MadaraUchiha** [babel/babel#1517]
Consider the following code:
```javascript
Promise.coroutine(function *main() {
    yield syntax error;
})
```
That snippet gives me the following error when run

```
> $ /usr/bin/iojs --version
v1.8.1

> $ /usr/bin/iojs run.js
/home/dor/Projects/diff-normalize/node_modules/babel/node_modules/babel-core/lib/babel/helpers/code-frame.js:92
  lines = lines.split(NEWLINE);
                ^
TypeError: undefined is not a function
    at Object.exports.default (/home/dor/Projects/diff-normalize/node_modules/babel/node_modules/babel-core/lib/babel/helpers/code-frame.js:92:17)
    at File.wrap (/home/dor/Projects/diff-normalize/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:590:47)
    at TransformerPipeline.transform (/home/dor/Projects/diff-normalize/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:87:17)
    at Object.transformFileSync (/home/dor/Projects/diff-normalize/node_modules/babel/node_modules/babel-core/lib/babel/api/node.js:108:32)
    at compile (/home/dor/Projects/diff-normalize/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:98:20)
    at normalLoader (/home/dor/Projects/diff-normalize/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:147:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dor/Projects/diff-normalize/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:7)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
```

I'm currently trying to isolate the issue on a new project, but so far have been unsuccessful.

**Comment by sebmck** [comment]
What Babel version are you on and what are you using to build it? It's nigh impossible to debug without a reproducible test case.

**Comment by MadaraUchiha** [comment]
Probably something that was fixed. I couldn't reproduce but updating babel to the latest version solved it. (from 5.2.9 to 5.3.1).
