### ISSUE TITLE
minification.deadCodeElimination fails for ImportDeclaration

### ISSUE THREAD

**Issue by Naddiseo** [babel/babel#1522]
$ babel --version
5.3.2

$ cat test.jsx 
```javascript
import x from 'y';

x.foo = function foo(err) {};
```
$ babel --optional minification.deadCodeElimination test.jsx 
~/node_modules/babel-core/lib/babel/transformation/file/index.js:591
      throw err;
            ^
Error: test.jsx: cannot turn ImportDeclaration to an expression
    at Object.toExpression (~/node_modules/babel-core/lib/babel/types/converters.js:265:11)
    at TraversalPath.ReferencedIdentifier (~/node_modules/babel-core/lib/babel/transformation/transformers/minification/dead-code-elimination.js:50:5)
    at TraversalPath.<anonymous> (~/node_modules/babel-core/lib/babel/traversal/visitors.js:183:17)
    at TraversalPath.call (~/node_modules/babel-core/lib/babel/traversal/path/index.js:833:28)
    at TraversalPath.visit (~/node_modules/babel-core/lib/babel/traversal/path/index.js:866:10)
    at TraversalContext.visitSingle (~/node_modules/babel-core/lib/babel/traversal/context.js:78:43)
    at TraversalContext.visit (~/node_modules/babel-core/lib/babel/traversal/context.js:89:19)
    at Function.traverse.node (~/node_modules/babel-core/lib/babel/traversal/index.js:64:17)
    at TraversalPath.visit (~/node_modules/babel-core/lib/babel/traversal/path/index.js:883:28)
    at TraversalContext.visitSingle (~/node_modules/babel-core/lib/babel/traversal/context.js:78:43)

**Comment by sebmck** [comment]
Closed via 330665f15063b03c8362a60b9f55a64d2a711b1f.
