### ISSUE TITLE
[Bug]: Cannot read property 'file' of undefined at Scope.toArray 

### ISSUE THREAD

**Issue by Graicaa** [babel/babel#15244]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code
```
let zmq = require('zeromq') // zeromq:"^6.0.0-beta.14"
async function run () {
    const sock1 = new zmq.Subscriber()
    sock1.connect('tcp://127.0.0.1:5561')
    sock1.subscribe('kitty cats')
    console.log('Subscriber connected to port 3000')
    for await (const [topic, msg] of sock1) {   // when this loop was commented out, the mistake was disappeared.
         console.log('received a message related to:', topic, 'containing message:', msg)
      }
}
```

### Configuration
```
{
  "comments": false,
  "env": {
    "test": {
      "presets": [
        ["env", {
          "targets": { "node": 7 }
        }],
        "stage-0"
      ],
      "plugins": ["istanbul"]
    },
    "main": {
      "presets": [
        ["env", {
          "targets": { "node": 7 }
        }],
        "stage-0"
      ]
    },
    "renderer": {
      "presets": [
        ["env", {
          "modules": false
        }],
        "stage-0"
      ]
    },
    "web": {
      "presets": [
        ["env", {
          "modules": false
        }],
        "stage-0"
      ]
    }
  },
  "plugins": ["transform-runtime"]
}
```

### Current and expected behavior

I add zeromq 6.0 to my project, but it build falied . I expect build electron project successful.

### Environment

Babel:"babel-core": "6.26.3",
Node: 14.17.0
Yarn version: 1.22.19
OS: [Windows 10.0.19044.2251]

**Comment by Graicaa** [comment]
Stack:
```
ERROR in ./src/utils/subber.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  TypeError: C:/Users/euler/Documents/work/chibi-face/src/utils/subber.js: Cannot read property 'file' of undefined
      at Scope.toArray (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\scope\index.js:437:25)
      at DestructuringTransformer.toArray (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-plugin-transform-es2015-destructuring\lib\index.js:122:27)
      at DestructuringTransformer.pushArrayPattern (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-plugin-transform-es2015-destructuring\lib\index.js:277:26)
      at DestructuringTransformer.push (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-plugin-transform-es2015-destructuring\lib\index.js:110:14)
      at DestructuringTransformer.init (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-plugin-transform-es2015-destructuring\lib\index.js:317:12)
      at PluginPass.VariableDeclaration (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-plugin-transform-es2015-destructuring\lib\index.js:468:27)
      at newFn (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\visitors.js:276:21)
      at NodePath._call (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\path\context.js:76:18)
      at NodePath.call (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\path\context.js:48:17)
      at NodePath.visit (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\path\context.js:105:12)
      at TraversalContext.visitQueue (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\context.js:150:16)
      at TraversalContext.visitMultiple (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\context.js:103:17)
      at TraversalContext.visit (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\context.js:190:19)
      at Function.traverse.node (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\index.js:114:17)
      at NodePath.visit (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\path\context.js:115:19)
      at TraversalContext.visitQueue (C:\Users\euler\Documents\work\chibi-face\node_modules\babel-traverse\lib\context.js:150:16)
   @ ./src/renderer/containers/LandingPage.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/containers/LandingPage.vue?vue&type=scr
ipt&lang=js&) 34:13-42
   @ ./src/renderer/containers/LandingPage.vue?vue&type=script&lang=js&
   @ ./src/renderer/containers/LandingPage.vue
   @ ./src/renderer/router/index.js
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js
```

**Comment by liuxingbaoyu** [comment]
Can you update to babel7 to try? babel6 has been out of date for many years.

**Comment by Graicaa** [comment]
> 

Thanks for your suggestion : ) ,The problem has been solved.

**Comment by Graicaa** [comment]
> Can you update to babel7 to try? babel6 has been out of date for many years.



> Can you update to babel7 to try? babel6 has been out of date for many years.

Thanks for your suggestion : ) ,The problem has been solved.
