### ISSUE TITLE
minification.deadCodeElimination fails for spread of nested for-of in generator

### ISSUE THREAD

**Issue by Naddiseo** [babel/babel#1524]
Another one for you @sebmck, apparently my codebase is good for testing this particular transformer.
$ babel --version
5.3.3
$ cat test.jsx 
```javascript
function* foo(s) {
	for (let a of []) {
		for (let b of a) {
			yield 1;
		}
	}
}

function bar() {
	return [...foo()];
}
```
$ babel --optional minification.deadCodeElimination test.jsx 
~/node_modules/babel-core/lib/babel/transformation/file/index.js:591
      throw err;
            ^
Error: test.jsx: cannot turn VariableDeclaration to an expression
    at Object.toExpression (~/node_modules/babel-core/lib/babel/types/converters.js:265:11)
    at TraversalPath.ReferencedIdentifier (~/node_modules/babel-core/lib/babel/transformation/transformers/minification/dead-code-elimination.js:50:5)
    at TraversalPath.<anonymous> (~/node_modules/babel-core/lib/babel/traversal/visitors.js:183:17)
    at TraversalPath.call (~/node_modules/babel-core/lib/babel/traversal/path/index.js:833:28)
    at TraversalPath.visit (~/node_modules/babel-core/lib/babel/traversal/path/index.js:866:10)
    at TraversalContext.visitSingle (~/node_modules/babel-core/lib/babel/traversal/context.js:78:43)
    at TraversalContext.visit (~/node_modules/babel-core/lib/babel/traversal/context.js:89:19)
    at Function.traverse.node (~/node_modules/babel-core/lib/babel/traversal/index.js:64:17)
    at TraversalPath.visit (~/node_modules/babel-core/lib/babel/traversal/path/index.js:883:28)
    at TraversalContext.visitMultiple (~/node_modules/babel-core/lib/babel/traversal/context.js:67:16)

**Comment by sebmck** [comment]
Fixed as of 5.4.0, thanks!
