### ISSUE TITLE
[Bug]: `Cannot set properties of undefined (setting 'identifier')` error when using `plugin-proposal-decorators` legacy with `plugin-transform-block-scoping`

### ISSUE THREAD

**Issue by charlessuh** [babel/babel#15295]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
try {
    class C {
        @Dummy foo() {
            throw new Error();
        }
    }

    let c = new C();
    c.foo();
} catch (e) {
    console.error(e);
}
```

### Configuration file name

.babelrc

### Configuration

```js
{
  //"presets": [
  //  ["@babel/preset-env", {"targets": "firefox 50"}]
  //],
  "plugins": [
    ["@babel/plugin-proposal-decorators", {"legacy": true}],
    ["@babel/transform-block-scoping"]
  ]	
}
```
### Current and expected behavior

Current:
```
TypeError: /Users/chsuh/decorators-bug/index.js: Cannot set properties of undefined (setting 'identifier')
    at PluginPass.ClassDeclaration (/Users/chsuh/decorators-bug/node_modules/@babel/plugin-proposal-decorators/lib/transformer-legacy.js:148:26)
    at newFn (/Users/chsuh/decorators-bug/node_modules/@babel/traverse/lib/visitors.js:159:21)
    at NodePath._call (/Users/chsuh/decorators-bug/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/chsuh/decorators-bug/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/chsuh/decorators-bug/node_modules/@babel/traverse/lib/path/context.js:84:31)
    at TraversalContext.visitQueue (/Users/chsuh/decorators-bug/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitMultiple (/Users/chsuh/decorators-bug/node_modules/@babel/traverse/lib/context.js:67:17)
    at TraversalContext.visit (/Users/chsuh/decorators-bug/node_modules/@babel/traverse/lib/context.js:119:19)
    at traverseNode (/Users/chsuh/decorators-bug/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/chsuh/decorators-bug/node_modules/@babel/traverse/lib/path/context.js:90:52) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

### Environment

  System:
    OS: macOS 13.1
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  npmPackages:
    @babel/cli: ^7.19.3 => 7.19.3 
    @babel/plugin-proposal-decorators: ^7.20.5 => 7.20.5 
    @babel/plugin-transform-block-scoping: ^7.20.5 => 7.20.5

**Comment by charlessuh** [comment]
This line appears to be throwing the error: https://github.com/babel/babel/pull/8566/files#diff-fb3ce34c7f7df7457153d3f43ef3fe7f02074361968b11b045932930db4e44fdR334

**Comment by liuxingbaoyu** [comment]
I can reproduce it with the latest release, but not in the main branch, not sure if it's because of https://github.com/babel/babel/pull/15200.

**Comment by nicolo-ribaudo** [comment]
Lets try releasing and see if it fixes the bug then :)

**Comment by liuxingbaoyu** [comment]
After the update the problem disappeared.😂

**Comment by nicolo-ribaudo** [comment]
@charlessuh Can you confirm that updating all your Babel dependencies fixed this for you?

**Comment by cjones26** [comment]
It may not be fully related, but we are seeing something similar here: https://github.com/storybookjs/storybook/issues/20382.

We were able to resolve by reverting to an older version of `@babel/plugin-transform-block-scoping`.

**Comment by liuxingbaoyu** [comment]
@cjones26 https://github.com/babel/babel/issues/15299 Can you try v7.20.8?

**Comment by cjones26** [comment]
@liuxingbaoyu I just tried v7.20.8 with no luck, but v7.20.5 does in fact work properly.

**Comment by liuxingbaoyu** [comment]
@cjones26 v7.20.9 has been released, has the problem been solved?

**Comment by necatisarhanli** [comment]
@liuxingbaoyu I don't see the new release (v7.20.9) on npm , where can we find it?

**Comment by liuxingbaoyu** [comment]
@necatisarhanli https://www.npmjs.com/package/@babel/plugin-transform-block-scoping

**Comment by eductech** [comment]
Hello. We use 3rd party bundling tool that has depth `"@babel/preset-env": "^7.11.5"`. Now it installs `@babel/plugin-transform-block-scoping@7.20.7` which seems to be corrupted by the issue raised and build fails. How we can resolve this?

**Comment by nicolo-ribaudo** [comment]
Delete `@babel/plugin-transform-block-scoping` from your lockfile and reinstall your dependencies
