### ISSUE TITLE
[Bug]: Internal Babel error: path is not in loop. Please report this as a bug. @babel/plugin-transform-block-scoping@7.20.11

### ISSUE THREAD

**Issue by jane-rose** [babel/babel#15342]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code
```js
 useEffect(() => {
    for (const key in state) {
        if (Object.prototype.hasOwnProperty.call(state, key)) {
            let value = state[key];
            if (typeof value === 'string') {
                if (/len|hchk|sof|chk|ctrl|ver/.test(key)) {
                    continue;
                }
                const info = formList.find((item) => item.key === key);
                if (state.is16t) {
                    if (info) {
                        state[key] = int2Hex(value, info.byteLen * 2, false);
                    }
                } else {
                    if (info) {
                        value = fillByte(value, info.byteLen * 2, true);
                        state[key] = parseInt(value, 16).toString();
                    }
                }
            }
        }
    }
    setState({
        ...state,
    });
}, [state.is16t]);
```

### Configuration

```js
 {
    extends: [require.resolve('@umijs/fabric/dist/eslint')],
    globals: {
        ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION: true,
        page: true,
        REACT_APP_ENV: true,
    },
    parser: '@babel/eslint-parser',
    parserOptions: {
        requireConfigFile: false,
        // babelOptions: {
        // 	presets: ['@babel/preset-react'],
        // },
        project: ['./tsconfig.json'],
    },
    env: {
        browser: true,
        node: true,
    },
    settings: {
        'import/resolver': {
            webpack: {
                config: {
                    resolve: {
                        modules: [path.resolve(__dirname, 'src')],
                        extensions: ['.js', '.jsx', '.ts', '.tsx'],
                    },
                },
            },
        },
    },
    plugins: ['react-hooks'],
    rules: {
        'no-use-before-define': 'off',
        '@typescript-eslint/no-var-requires': 'off',
        '@typescript-eslint/no-use-before-define': ['error'],
        'react/jsx-filename-extension': [
            2,
            {
                extensions: ['.js', '.jsx', '.ts', '.tsx'],
            },
        ],
        'react-hooks/rules-of-hooks': 'error', // Checks rules of Hooks
        'react-hooks/exhaustive-deps': 'warn', // Checks effect dependencies
        'react/jsx-no-bind': [
            1,
            {
                allowArrowFunctions: true,
            },
        ],
        'jsx-a11y/control-has-associated-label': 0,
        'react/state-in-constructor': 0,
        'react/sort-comp': 0,
        'react/static-property-placement': 0,
        'react/prefer-stateless-function': 0,
        'react/no-access-state-in-setstate': 0,
        'react/jsx-props-no-spreading': 0,
        'react/jsx-indent': 0,
        'react/no-deprecated': 'warn',
        // 'react/jsx-fragments': 0,
        // 'import/extensions': [
        // 	'error',
        // 	'never',
        // 	{
        // 		styl: 'always',
        // 		json: 'always',
        // 	},
        // ],
        'no-self-assign': 0,
        'prefer-object-spread': 0,
        'no-async-promise-executor': 0,
        'comma-dangle': 0,
        'no-multiple-empty-lines': 0,
        'no-var': 'error',
        'no-await-in-loop': 0,
        'no-loop-func': 0,
        "@typescript-eslint/no-loop-func": "warn",
        indent: [
            2,
            4,
            {
                SwitchCase: 1,
                ignoredNodes: ['ConditionalExpression'],
            },
        ],
        'no-constant-condition': [
            2,
            {
                checkLoops: false,
            },
        ],
        'spaced-comment': [1, 'always'],
        'no-multi-str': 0,
        'no-lonely-if': 0,
        'no-bitwise': 0,
        'max-classes-per-file': 0,
        'lines-between-class-members': [
            2,
            'always',
            {
                exceptAfterSingleLine: true, // skip checking empty lines after single-line class members
            },
        ],
        semi: [2, 'always'],
    // 'jsx-a11y/label-has-associated-control': [
    // 	'error',
    // 	{
    // 		required: {
    // 			some: ['nesting', 'id'],
    // 		},
    // 	},
    // ],
    },
    ignorePatterns: ['*.d.ts'],
    overrides: [
        {
            files: ['*.ts', '*.tsx'],
            extends: [
                'plugin:@typescript-eslint/eslint-recommended',
                'plugin:@typescript-eslint/recommended',
            ],
            parser: '@typescript-eslint/parser',
            // plugins: ['react', '@typescript-eslint'],
            rules: {
                '@typescript-eslint/ban-types': 'off',
                'no-use-before-define': 'off',
                '@typescript-eslint/no-use-before-define': ['error'],
                'react/prop-types': 'off',
                'no-shadow': 'off',
                '@typescript-eslint/no-shadow': ['error'],
                'no-empty-function': 'off',
                '@typescript-eslint/no-empty-function': ['error'],
                'no-extra-semi': 'off',
                '@typescript-eslint/no-extra-semi': ['error'],
                'no-unused-vars': 'off',
                // Note: you must disable the base rule as it can report incorrect errors
                "no-unused-expressions": "off",
                '@typescript-eslint/no-unused-vars': ['error'],
                '@typescript-eslint/promise-function-async': 'error',
            },
        },
    ],
};
```

### Current and expected behavior
```
curren error: Internal Babel error: path is not in loop. Please report this as a bug.

Module build failed (from ./node_modules/@umijs/deps/compiled/babel-loader/index.js):
Error: /Users/ross/Documents/tl300-emweb/src/pages/Controller/components/DataManager/components/SinglePointSender/BaseInput.tsx: Internal Babel error: path is not in loop. Please report this as a bug.
    at relativeLoopLocation (/Users/ross/Documents/tl300-emweb/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-block-scoping/src/loop.ts:86:9)
    at fn (/Users/ross/Documents/tl300-emweb/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-block-scoping/src/loop.ts:59:35)
    at filterMap (/Users/ross/Documents/tl300-emweb/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-block-scoping/src/loop.ts:328:20)
    at getUsageInBody (/Users/ross/Documents/tl300-emweb/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-block-scoping/src/loop.ts:56:22)
    at PluginPass.Loop (/Users/ross/Documents/tl300-emweb/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-block-scoping/src/index.ts:85:31)
    at newFn (/Users/ross/Documents/tl300-emweb/node_modules/@umijs/deps/compiled/babel/bundle.js:66732:21)
    at NodePath._call (/Users/ross/Documents/tl300-emweb/node_modules/@umijs/deps/compiled/babel/bundle.js:61110:20)
```
expect: no error

### Environment

Babel version: 7.18.6
Node: Node 16.13.2
yarn version: 1.22.19
OS: macOS 13.1

### Additional context

It's work fine in @babel/plugin-transform-block-scoping@7.20.5, but broken in version 7.20.11.

**Comment by liuxingbaoyu** [comment]
The configuration seems complicated, can you provide a repo that can reproduce it?

**Comment by njmulsqb** [comment]
Deleting node modules and package lock file and reinstalling fixed the issue for me

**Comment by nicolo-ribaudo** [comment]
Closing ad there is no reproducible example.
