### ISSUE TITLE
[Bug]:  After Upgrading to babel core pacakage , getting below module declaration issue

### ISSUE THREAD

**Issue by mahendrushivam** [babel/babel#15450]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

Trace: `isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`.
    at isModuleDeclaration (/Users/shivam.mahendru/Documents/Cyware/ctix-frontend-v2/node_modules/@babel/types/lib/validators/generated/index.js:3939:11)

### Current and expected behavior

Trace: `isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`.
    at isModuleDeclaration (/<<project-path>>/node_modules/@babel/types/lib/validators/generated/index.js:3939:11)

### Environment

Node : 16.15.1

**Comment by JLHwung** [comment]
This is an intended behaviour, see https://github.com/babel/babel/pull/15266#issue-1492649843 for the migration guide.
