### ISSUE TITLE
Cannot find module 'babel-core' when running `make build`

### ISSUE THREAD

**Issue by camsong** [babel/babel#1553]
I cloned the master branch, and try to build babel myself.
After `npm install` and `make build`, I got the following error:
```shell
node node_modules/uglify-js/bin/uglifyjs dist/babel.js >dist/babel.min.js
node packages/babel-cli/bin/babel-external-helpers >dist/external-helpers.js
module.js:339
    throw err;
          ^
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/cam/jsapp/babel/packages/babel-cli/bin/babel-external-helpers:4:17)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:472:10)
make: *** [build] Error 1
```

**Comment by sebmck** [comment]
Follow the setup process in [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md#setup). Looks like you forgot to `$ make bootstrap`.
