### ISSUE TITLE
@babel/plugin-transform-runtime插件报错 bundle.js:43127 Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by AliSnowaroma** [babel/babel#15573]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
presets: [
      '@babel/preset-env',
      '@babel/preset-react',
      ['@babel/preset-typescript', {
        isTSX: true,
        jsxPragma: 'React',
        allExtensions: true,
        allowNamespaces: true,
      }],
    ],
    plugins: [
      ['@babel/plugin-proposal-decorators', {
        legacy: true,
      }],
      '@babel/plugin-proposal-nullish-coalescing-operator', // 可选链 ?.
      '@babel/plugin-proposal-optional-chaining', // A ?? B
      [
        '@babel/plugin-transform-runtime',
        {
          absoluteRuntime: false,
          corejs: 3,
          helpers: true, // 使用到@babel/runtime
          regenerator: true, // 使用到@babel/runtime
        },
      ],
      ['@babel/plugin-transform-modules-commonjs'],
    ],
  }
```

### Current and expected behavior

bundle.js:43127 Uncaught ReferenceError: require is not defined
    at eval (typeof.js:4:30)
    at ./node_modules/@babel/runtime-corejs3/helpers/esm/typeof.js (bundle.js:40081:1)
    at __webpack_require__ (bundle.js:43124:33)
    at fn (bundle.js:43341:21)
    at eval (index.js?protocol=ws%3A&hostname=127.0.0.1&port=9999&pathname=%2Fws&logging=info&reconnect=10:5:39)
    at ./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=127.0.0.1&port=9999&pathname=%2Fws&logging=info&reconnect=10 (bundle.js:34855:1)
    at __webpack_require__ (bundle.js:43124:33)
    at bundle.js:44202:11
    at bundle.js:44206:12

### Environment

"@babel/core": "^7.18.0",
windows
node：16.16.0

**Comment by AliSnowaroma** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，谢谢

**Comment by AliSnowaroma** [comment]
@babel/plugin-transform-runtime版本7.21.4报错bundle.js:43127 Uncaught ReferenceError: require is not defined

修改@babel/plugin-transform-runtime版本为7.19.6
再次执行报错改为bundle.js:40982 Uncaught TypeError: $ is not a function

**Comment by AliSnowaroma** [comment]
问题已解决

使用@babel/plugin-transform-runtime插件，如果babel配置文件时babel.config.js，则此时babel会读取babel.config.js作为全局配置，这时会影响到插件，进而报错Uncaught TypeError: $ is not a function

将babel.config.js改为.babelrc格式，此时.babelrc文件 不会被当作全局配置，再次打包正常，目前已经用这种方式解决该问题
