### ISSUE TITLE
[Bug]: Property declarations expected type of array but got object in objectPattern 

### ISSUE THREAD

**Issue by yooouuri** [babel/babel#15589]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
t.variableDeclaration(
  'const',
  t.variableDeclarator(
    t.objectPattern([
      t.objectProperty(
        t.identifier('app'),
        t.identifier('app'),
        false,
        true
      ),
      t.objectProperty(
        t.identifier('router'),
        t.identifier('router'),
        false,
        true
      )
    ])
    // t.expressionStatement(
    //   t.callExpression(
    //     t.identifier('xxx'),
    //     path.node.declaration.arguments
    //   )
    // )
  )
)
```

Im trying to create the following:

```js
const { app, router } = xxx(App, { routes })
```

```
TypeError: Property declarations expected type of array but got object
    at validate (/Users/youri/dev/ast-test/node_modules/.pnpm/@babel+types@7.21.4/node_modules/@babel/types/lib/definitions/utils.js:134:13)
    at Object.validate (/Users/youri/dev/ast-test/node_modules/.pnpm/@babel+types@7.21.4/node_modules/@babel/types/lib/definitions/utils.js:188:7)
    at validateField (/Users/youri/dev/ast-test/node_modules/.pnpm/@babel+types@7.21.4/node_modules/@babel/types/lib/validators/validate.js:21:9)
    at validate (/Users/youri/dev/ast-test/node_modules/.pnpm/@babel+types@7.21.4/node_modules/@babel/types/lib/validators/validate.js:15:3)
    at validateNode (/Users/youri/dev/ast-test/node_modules/.pnpm/@babel+types@7.21.4/node_modules/@babel/types/lib/builders/validateNode.js:12:27)
    at Object.variableDeclaration (/Users/youri/dev/ast-test/node_modules/.pnpm/@babel+types@7.21.4/node_modules/@babel/types/lib/builders/generated/index.js:597:36)
    at ExportDefaultDeclaration (file:///Users/youri/dev/ast-test/index.js:55:9)
    at NodePath._call (/Users/youri/dev/ast-test/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/path/context.js:45:20)
    at NodePath.call (/Users/youri/dev/ast-test/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/path/context.js:35:17)
    at NodePath.visit (/Users/youri/dev/ast-test/node_modules/.pnpm/@babel+traverse@7.21.4/node_modules/@babel/traverse/lib/path/context.js:80:31)
```

### Current and expected behavior

It should not error because im giving an array...

### Environment

  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  npmPackages:
    @babel/generator: ^7.21.4 => 7.21.4
    @babel/parser: ^7.21.4 => 7.21.4
    @babel/template: ^7.20.7 => 7.20.7
    @babel/traverse: ^7.21.4 => 7.21.4
    @babel/types: ^7.21.4 => 7.21.4

**Comment by JLHwung** [comment]
`declarations` must be an array. For example, think about `const { a } = foo, { b } = bar`. In your case, the valid usage should be

```js
t.variableDeclaration(
  'const',
  [
    t.variableDeclarator(t.objectPattern(), t.callExpression())
  ]
)
```

When in doubt, always check the [ASTExplorer](https://astexplorer.net/#/gist/efa02f816762fcb36c600b1b483fde67/268f4d6344ff0616bfa030897595e0b1b57bf48c) for the exact shape before creating the AST nodes.

**Comment by yooouuri** [comment]
@JLHwung yea when I was creating this issue, I noticed myself. Sorry...
