### ISSUE TITLE
[Bug]: Unable to transform arrow inside class property

### ISSUE THREAD

**Issue by adminy** [babel/babel#15613]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Vite is

### Input code

```
vite v4.3.5 building for production...
✓ 277 modules transformed.
[vite:bytecode] unknown file: Unable to transform arrow inside class property
  12144 |     }
  12145 |     // conditionally set private methods related to TTL
> 12146 |     #updateItemAge = () => { };
        |                      ^^^^^^^^^
  12147 |     #statusTTL = () => { };
  12148 |     #setItemTTL = () => { };
  12149 |     /* c8 ignore stop */
✓ 0 bundles compiled into bytecode.
✓ built in 1.80s
error during build:
SyntaxError: unknown file: Unable to transform arrow inside class property
  12144 |     }
  12145 |     // conditionally set private methods related to TTL
> 12146 |     #updateItemAge = () => { };
        |                      ^^^^^^^^^
  12147 |     #statusTTL = () => { };
  12148 |     #setItemTTL = () => { };
  12149 |     /* c8 ignore stop */
    at File.buildCodeFrameError (/Users/adminy/project/node_modules/@babel/core/lib/transformation/file/file.js:205:12)
    at NodePath.buildCodeFrameError (/Users/adminy/project/node_modules/@babel/traverse/lib/path/index.js:105:21)
    at hoistFunctionEnvironment (/Users/adminy/project/node_modules/@babel/traverse/lib/path/conversion.js:171:20)
    at NodePath.arrowFunctionToExpression (/Users/adminy/project/node_modules/@babel/traverse/lib/path/conversion.js:121:7)
    at PluginPass.ArrowFunctionExpression (/Users/adminy/project/node_modules/@babel/plugin-transform-arrow-functions/lib/index.js:18:16)
    at newFn (/Users/adminy/project/node_modules/@babel/traverse/lib/visitors.js:149:21)
    at NodePath._call (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:45:20)
    at NodePath.call (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:35:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:81:31)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse (/Users/adminy/project/node_modules/@babel/traverse/lib/index.js:49:34)
    at transformFile (/Users/adminy/project/node_modules/@babel/core/lib/transformation/index.js:81:29)
    at transformFile.next (<anonymous>)
    at run (/Users/adminy/project/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (/Users/adminy/project/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
```

### Configuration file name

vite.config.mjs

### Configuration

```javascript
import { svelte } from '@sveltejs/vite-plugin-svelte'
export default {
    plugins: [svelte()],
}
```

### Current and expected behavior

Not to fail

### Environment

- Babel Version: 7.21.0
- Node: 19.8.1
- Npm: 9.5.1
- OS: macos-13.0.1
- Monorepo: yes

### Possible solution

Works fine when I run `vite dev` but fails with this when I run `vite build` so its somehow mis-using it.

### Additional context

The code it fails on seems to be at:
```bash
./node_modules/path-scurry/node_modules/lru-cache/dist/mjs/index.js
```

**Comment by nicolo-ribaudo** [comment]
It's not possible to compile arrow function in class fields without also compiling class fields. This is a bug in whatever code is configuring Babel for you, since there is no reason to compile arrow functions if your targets support class fields.

Can you try running this command, to show your Babel config?
```
BABEL_SHOW_CONFIG_FOR=./node_modules/path-scurry/node_modules/lru-cache/dist/mjs/index.js vite build
```

**Comment by adminy** [comment]
Same logs, I think it fails before its able to show the config somehow.

**Comment by alex8088** [comment]
> It's not possible to compile arrow function in class fields without also compiling class fields. This is a bug in whatever code is configuring Babel for you, since there is no reason to compile arrow functions if your targets support class fields.
> 
> Can you try running this command, to show your Babel config?
> 
> ```
> BABEL_SHOW_CONFIG_FOR=./node_modules/path-scurry/node_modules/lru-cache/dist/mjs/index.js vite build
> ```


```ts
import * as babel from '@babel/core'
//...
babel.transform(code, {
   plugins: ['@babel/plugin-transform-arrow-functions']
})
```

**Comment by liuxingbaoyu** [comment]
This issue looks out of date, if anyone encounters it again please open a new issue.
