### ISSUE TITLE
[Bug]: Cannot assign to read only property 'stackTraceLimit'

### ISSUE THREAD

**Issue by loynoir** [babel/babel#15625]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import { parse } from "@babel/core";
console.log(parse("").type);
```

### Current and expected behavior

```sh
$ node reproduce.mjs
File
```

```
$  node --frozen-intrinsics reproduce.mjs 
(node:602173) ExperimentalWarning: The --frozen-intrinsics flag is experimental
(Use `node --trace-warnings ...` to show where the warning was created)
/path/to/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:65
  Error.stackTraceLimit && (Error.stackTraceLimit = Math.max(Error.stackTraceLimit, MIN_STACK_TRACE_LIMIT));
                                                  ^

TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot assign to read only property 'stackTraceLimit' of function 'function Error() { [native code] }'
    at setupPrepareStackTrace (/path/to/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:65:51)
    at stopHiding - secret - don't use this - v1 (/path/to/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:45:5)
    at parse (/path/to/node_modules/@babel/core/lib/parse.js:34:76)
    at file:///path/to/reproduce.mjs:2:13
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.15.0
```

### Environment

"@babel/core": "^7.21.8"

node v18.15.0

### Possible solution

```patch
diff --git a/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js b/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js
index 9b6ce01..0757ad6 100644
--- a/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js
+++ b/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js
@@ -62,6 +62,7 @@ function setupPrepareStackTrace() {
     prepareStackTrace = defaultPrepareStackTrace
   } = Error;
   const MIN_STACK_TRACE_LIMIT = 50;
+  try {
   Error.stackTraceLimit && (Error.stackTraceLimit = Math.max(Error.stackTraceLimit, MIN_STACK_TRACE_LIMIT));
   Error.prepareStackTrace = function stackTraceRewriter(err, trace) {
     let newTrace = [];
@@ -87,6 +88,7 @@ function setupPrepareStackTrace() {
     }
     return prepareStackTrace(err, newTrace);
   };
+  } catch {}
 }
 function defaultPrepareStackTrace(err, trace) {
   if (trace.length === 0) return ErrorToString(err);
```

```sh
$ node --frozen-intrinsics reproduce.mjs
(node:604212) ExperimentalWarning: The --frozen-intrinsics flag is experimental
(Use `node --trace-warnings ...` to show where the warning was created)
File
```

**Comment by liuxingbaoyu** [comment]
![image](https://github.com/babel/babel/assets/30521560/c3585acc-8bd0-48b0-8646-7e19dc208192)
I opened a PR https://github.com/babel/babel/pull/15626.
This problem seems to only exist in some versions.

**Comment by loynoir** [comment]
REPL is different from script. Try a script.

**Comment by liuxingbaoyu** [comment]
![image](https://github.com/babel/babel/assets/30521560/b5787113-ceca-498a-afdb-28f653eed10e)
Maybe nodejs changed behavior in newer versions?

**Comment by loynoir** [comment]
I'm on v18.15.0. What version are you using?

**Comment by liuxingbaoyu** [comment]
v19.8.1
Don't worry, even though I can't reproduce it, I still think the problem exists.
Because there is a related PR https://github.com/nodejs/node/pull/38215 in nodejs.

**Comment by loynoir** [comment]
@liuxingbaoyu

🤔 Are you using nodejs wrapper that does not accept CLI flags?

---

```sh
$ img=docker.io/library/node:19.8.1@sha256:1fab548e95c779df229e4b50d8d20e222597bda15aeece508098c5ba7723302e                                          
$ docker run --rm -it -v "$PWD":/app -w /app "$img" node --frozen-intrinsics ./reproduce.mjs               
(node:1) ExperimentalWarning: The --frozen-intrinsics flag is experimental
(Use `node --trace-warnings ...` to show where the warning was created)
/app/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:65
  Error.stackTraceLimit && (Error.stackTraceLimit = Math.max(Error.stackTraceLimit, MIN_STACK_TRACE_LIMIT));
                                                  ^

TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot assign to read only property 'stackTraceLimit' of function 'function Error() { [native code] }'
    at setupPrepareStackTrace (/app/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:65:51)
    at stopHiding - secret - don't use this - v1 (/app/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:45:5)
    at parse (/app/node_modules/@babel/core/lib/parse.js:34:76)
    at file:///app/reproduce.mjs:2:13
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.8.1
```

---

```sh
$ img=docker.io/library/node:20@sha256:0efc3ef3fea2822c9d16da084c40181ed7f74b6f45141100580f9887ccc8e9a
$ docker run --rm -it -v "$PWD":/app -w /app "$img" node --frozen-intrinsics ./reproduce.mjs           
(node:1) ExperimentalWarning: The --frozen-intrinsics flag is experimental
(Use `node --trace-warnings ...` to show where the warning was created)
/app/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:65
  Error.stackTraceLimit && (Error.stackTraceLimit = Math.max(Error.stackTraceLimit, MIN_STACK_TRACE_LIMIT));
                                                  ^

TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot assign to read only property 'stackTraceLimit' of function 'function Error() { [native code] }'
    at setupPrepareStackTrace (/app/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:65:51)
    at stopHiding - secret - don't use this - v1 (/app/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:45:5)
    at parse (/app/node_modules/@babel/core/lib/parse.js:34:76)
    at file:///app/reproduce.mjs:2:13
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)

Node.js v20.1.0
```

**Comment by liuxingbaoyu** [comment]
![image](https://github.com/babel/babel/assets/30521560/cd9f27ae-2efb-4d19-9d71-a7d8b417c6bc)
It seems not.
Obviously the flag is working.

**Comment by liuxingbaoyu** [comment]
Strangely, when I test inside babel, it throws this error.😕

**Comment by nicolo-ribaudo** [comment]
It only throws in strict mode :)
