### ISSUE TITLE
[Bug]: Cannot find package '@babel/plugin-proposal-optional-chaining' imported from

### ISSUE THREAD

**Issue by suraj-sundariya** [babel/babel#15669]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

My package.json look like below 

```json
    "@babel/cli": "^7.10.1",
    "@babel/core": "^7.10.1",
    "@babel/plugin-proposal-class-properties": "^7.10.1",
    "@babel/plugin-proposal-decorators": "^7.10.1",
    "@babel/plugin-proposal-export-default-from": "^7.10.1",
    "@babel/plugin-proposal-function-bind": "^7.10.1",
    "@babel/plugin-proposal-object-rest-spread": "^7.10.1",
    "@babel/plugin-transform-react-display-name": "^7.10.1",
    "@babel/plugin-transform-react-jsx-source": "^7.10.1",
    "@babel/plugin-transform-runtime": "^7.10.1",
    "@babel/preset-env": "^7.10.1",
    "@babel/preset-react": "^7.10.1",
    "@babel/runtime": "^7.10.1",
    "@hot-loader/react-dom": "^17.0.1",
    "@sentry/webpack-plugin": "^1.6.2",
    "@storybook/addon-actions": "^5.3.19",
    "@storybook/addon-knobs": "^5.3.19",
    "@storybook/addon-links": "^5.3.19",
    "@storybook/addons": "^5.3.19",
    "@storybook/react": "^5.3.19",
    "@testing-library/react": "^11.2.3",
    "@types/jest": "^26.0.20",
    "@types/node": "^14.14.20",
    "@welldone-software/why-did-you-render": "^3.6.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-add-module-exports": "^1.0.0",
    "babel-plugin-array-includes": "^2.0.3",
    "babel-plugin-emotion": "^9.2.11",
    "babel-plugin-transform-promise-to-bluebird": "^2.0.0",
    "babel-register": "^6.26.0",
```

### Current and expected behavior

Error while bundling 

### Environment

Babel - ^7.10.1
Node - 14.17.6
OS- Mac

**Comment by barlima** [comment]
facing the same issue, showed up today

**Comment by nicolo-ribaudo** [comment]
Can you provide the full error?

**Comment by clintgeek** [comment]
**Error: Cannot find package '@babel/plugin-proposal-optional-chaining' imported from /opt/atlassian/pipelines/agent/build/guides/branch-business/babel-virtual-resolve-base.js**
    at __node_internal_ (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:233:9)
    at new NodeError (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:203:5)
    at packageResolve (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:873:9)
    at moduleResolve (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:902:20)
    at defaultResolve (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:985:15)
    at resolve (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:999:12)
    at resolve (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:13:10)
    at tryImportMetaResolve (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/files/plugins.js:123:45)
    at resolveStandardizedNameForImport (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/files/plugins.js:145:19)
    at resolveStandardizedName (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/files/plugins.js:154:12)
    at loadPlugin (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/files/plugins.js:47:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/config-descriptors.js:139:16)
    at createDescriptor.next (<anonymous>)
    at step (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:291:5)
    at /opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:43:15)
    at Function.all (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/config-descriptors.js:101:41)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/config-descriptors.js:98:17)
    at createPluginDescriptors.next (<anonymous>)
    at /opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/config-descriptors.js:64:32
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
    at Generator.next (<anonymous>)
    at step (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:269:25)
    at evaluateAsync (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:291:5)
    at Function.errback (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:113:7)
    at errback (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/gensync-utils/async.js:66:18)
    at async (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:188:31)
    at onFirstPause (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at cachedFunction (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/caching.js:52:46)
    at cachedFunction.next (<anonymous>)
    at mergeChainOpts (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/config-chain.js:349:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/config-chain.js:316:14)
    at chainWalker.next (<anonymous>)
    at buildRootChain (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/config-chain.js:57:36)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/partial.js:79:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at /opt/atlassian/pipelines/agent/build/guides/node_modules/@babel/core/lib/config/partial.js:122:25
    at Generator.next (<anonymous>)
    at step (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:269:25)
    at evaluateAsync (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:291:5)
    at /opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:93:9
    at new Promise (<anonymous>)
    at async (/opt/atlassian/pipelines/agent/build/guides/node_modules/gensync/index.js:92:14)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/guides/node_modules/babel-loader/lib/index.js:126:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/opt/atlassian/pipelines/agent/build/guides/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/opt/atlassian/pipelines/agent/build/guides/node_modules/babel-loader/lib/index.js:4:194)
    at /opt/atlassian/pipelines/agent/build/guides/node_modules/babel-loader/lib/index.js:4:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/guides/node_modules/babel-loader/lib/index.js:4:97)
    at Object._loader (/opt/atlassian/pipelines/agent/build/guides/node_modules/babel-loader/lib/index.js:210:18)
    at Object.loader (/opt/atlassian/pipelines/agent/build/guides/node_modules/babel-loader/lib/index.js:48:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/guides/node_modules/babel-loader/lib/index.js:44:12)
 @ multi @ignitesales/neuro-application/src/neuro-guide/utils/logger.mjs react-app-polyfill/ie11 react-app-polyfill/stable custom-event-polyfill ./src/main/js/index.mjs ./src/main/scss/main.scss guide[4]

**Comment by clintgeek** [comment]
The only configuration I can find surrounding Babel is in our webpack config. It isn't very specific surrounding versions but it is during the webpack stage that we're seeing the above errors.

**Comment by nicolo-ribaudo** [comment]
There is _somewhere_ a config that enables all those Babel presets and plugins, maybe you could try searching for `@babel/` in your whole project?

This is what I suspect is happening:
- that configuration is enabling `@babel/plugin-proposal-optional-chaining`
- `@babel/plugin-proposal-optional-chaining` is not in your dependencies
- for some reason `@babel/plugin-proposal-optional-chaining` was in your `node_modules`, probably as a transitive dependencies of one of your dependencies
- your `node_modules` layout changed due to updates in your dependencies, and that plugin which was "implicitly installed" is not there anymore.

**Comment by ZeeshanTamboli** [comment]
We encountered a similar issue at Material UI while attempting to update from `^7.21.0 to ^7.21.5` - see the GitHub pull request at https://github.com/mui/material-ui/pull/37422. The error specifically relates to `@babel/plugin-proposal-private-methods`. We wonder why the plugin proposals [were removed from `@babel/preset-env`](https://github.com/mui/material-ui/pull/37422/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL1065) and whether this should be considered a breaking change.

**Comment by nicolo-ribaudo** [comment]
> I wonder why the plugin proposals [were removed from @babel/preset-env](https://github.com/mui/material-ui/pull/37422/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL1065) and whether this should be considered a breaking change.

They were removed because those are not proposals anymore but standard features, so we are now using the `-transform-` plugins as we are doing for every other standard feature. The functionality of `@babel/preset-env` is not changed, and the list of internal dependencies of a package has never been consider as part of the public API in the npm ecosystem.

**Comment by webraptor** [comment]
> > I wonder why the plugin proposals [were removed from @babel/preset-env](https://github.com/mui/material-ui/pull/37422/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL1065) and whether this should be considered a breaking change.
> 
> They were removed because those are not proposals anymore but standard features, so we are now using the `-transform-` plugins as we are doing for every other standard feature. The functionality of `@babel/preset-env` is not changed, and the list of internal dependencies of a package has never been consider as part of the public API in the npm ecosystem.
> 
> The problem is that some packages rely on dependencies without listing them in their package.json, and _sometimes_ they are lucky that the dependency is installed for other reasons, sometimes they aren't.

That's nice but it looks like some dependencies haven't been properly updated as running yarn install will still try to use the proposal as a dependency, rather than the transform version.

**Comment by webraptor** [comment]
> Can you check which one hasn't been properly updated, and report an issue on their GitHub?

it's react navigation suite of projects :(

**Comment by nicolo-ribaudo** [comment]
Could you open an issue there and link it here?
