### ISSUE TITLE
[Bug]: not working after upgrade to 7.22.5

### ISSUE THREAD

**Issue by kukjevov** [babel/babel#15712]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

After upgrading Angular from 16.0.4 to 16.1.1 (which increased version of babel from 7.21.4 to 7.22.5) application will not compile anymore.

Minimal reproduction for non working version
`git clone https://github.com/kukjevov/ng-universal-demo`
`cd ng-universal-demo`
`git checkout 2.0`
`npm install --legacy-peer-deps`
`npm run build`

Minimal reproduction for working version
`git clone https://github.com/kukjevov/ng-universal-demo`
`cd ng-universal-demo`
`git checkout 1.0`
`npm install --legacy-peer-deps`
`npm run build`

### Current and expected behavior

Error received
ERROR in ./node_modules/@anglr/notifications/es2020/src/components/notificationMessage/notificationMessage.component.js
Error: D:\git\universal-demo\node_modules\@anglr\notifications\es2020\src\components\notificationMessage\notificationMessage.component.js: `column` must be greater than or equal to 0 (columns start at column 0)
    at exports.originalPositionFor (D:\git\universal-demo\node_modules\@jridgewell\trace-mapping\dist\trace-mapping.umd.js:402:23)
    at SourceMap.mark (D:\git\universal-demo\node_modules\@babel\generator\lib\source-map.js:57:65)
    at Buffer._mark (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:191:60)
    at Buffer._appendChar (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:135:12)
    at Buffer.appendChar (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:104:10)
    at Generator._appendChar (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:205:15)
    at Generator.tokenChar (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:126:10)
    at Generator.rightParens (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:81:10)
    at Generator.CallExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:196:8)
    at Buffer.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:249:5)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ExpressionStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:227:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printSequence (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:476:10)
    at Generator.BlockStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\base.js:51:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printAndIndentOnComments (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:423:10)
    at Generator.IfStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\statements.js:52:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printSequence (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:476:10)
    at Generator.BlockStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\base.js:51:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.FunctionExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\methods.js:109:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ObjectProperty (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\types.js:82:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printList (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:482:10)
    at Generator.ObjectExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\types.js:49:10)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printList (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:482:10)
    at Generator.CallExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:195:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.AssignmentExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:252:8)
    at Buffer.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:249:5)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ExpressionStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:227:8)
 @ ./node_modules/@anglr/notifications/es2020/src/index.js 4:0-79 4:0-79
 @ ./app/boot/app.component.ts 27:0-43 179:90-121
 @ ./app/boot/browser-app.module.ts 6:0-47 16:14-26
 @ ./app/main.browser.bootstrap.ts 11:0-61 16:45-61
 @ ./app/main.browser.ts 11:10-44

### Environment

- Babel: 7.22.5
- Node: v16.15.0
- npm: 8.19.4
- Windows: 10.0.19045

**Comment by liuxingbaoyu** [comment]
Thanks for the repro repo. Unfortunately I didn't find the `2.0` branch, can you confirm that?

**Comment by kukjevov** [comment]
I apologize for that, i pushed it after i created issue. Its there, you can try again. :)

**Comment by kukjevov** [comment]
@nicolo-ribaudo @liuxingbaoyu  thx for fix :). I have one more question what is estimated date when this will get release?

Thank you very much anyway.

**Comment by nicolo-ribaudo** [comment]
I can release now :)

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/actions/runs/5473502050, it will be done in ~10 minutes

**Comment by kukjevov** [comment]
Tested and it is working, thank you very much for fix :), love it.
