### ISSUE TITLE
[Bug]:  Cannot find package 'babel-plugin-macros'

### ISSUE THREAD

**Issue by AtomicCow87** [babel/babel#15760]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```
rake webpacker:clobber webpacker:compile
or
rails s
```

### Configuration file name

babel.config.js

### Configuration

babel.config.js
```
module.exports = function(api) {
  var validEnv = ['development', 'test', 'production']
  var currentEnv = api.env()
  var isDevelopmentEnv = api.env('development')
  var isProductionEnv = api.env('production')
  var isTestEnv = api.env('test')

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      'Please specify a valid `NODE_ENV` or ' +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        '.'
    )
  }

  return {
    presets: [
      isTestEnv && [
        '@babel/preset-env',
        {
          targets: {
            node: 'current'
          }
        }
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        '@babel/preset-env',
        {
          forceAllTransforms: true,
          useBuiltIns: 'entry',
          corejs: 3,
          modules: false,
          exclude: ['transform-typeof-symbol']
        }
      ]
    ].filter(Boolean),
    plugins: [
      'babel-plugin-macros',
      '@babel/plugin-syntax-dynamic-import',
      isTestEnv && 'babel-plugin-dynamic-import-node',
      '@babel/plugin-transform-destructuring',
      [
        '@babel/plugin-proposal-class-properties',
        {
          loose: true
        }
      ],
      [
        '@babel/plugin-proposal-object-rest-spread',
        {
          useBuiltIns: true
        }
      ],
      [
        '@babel/plugin-transform-private-methods',
        {
          loose: true
        }
      ],
      [
        '@babel/plugin-transform-private-property-in-object',
        {
          loose: true
        }
      ],
      [
        '@babel/plugin-transform-runtime',
        {
          helpers: false
        }
      ],
      [
        '@babel/plugin-transform-regenerator',
        {
          async: false
        }
      ]
    ].filter(Boolean)
  }
}

```

### Current and expected behavior

Error that show up when I run either webpacker:compile or rails s and open localhost:3000
```
Started GET "/" for 127.0.0.1 at 2023-07-06 12:05:05 -0400
   (13.6ms)  SELECT sqlite_version(*)
   (2.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by StaticPagesController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering static_pages/index.html.erb within layouts/application
  Rendered static_pages/index.html.erb within layouts/application (Duration: 11.8ms | Allocations: 281)
[Webpacker] Compiling...
[Webpacker] Compilation failed:
Hash: 4d6a0453e4a0cd86319c
Version: webpack 4.46.0
Time: 6755ms
Built at: 07/06/2023 12:05:20 PM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-f685c72999449b4e73a4.js   24.4 KiB  application  [emitted] [immutable]  application
js/application-f685c72999449b4e73a4.js.map   13.2 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]
Entrypoint application = js/application-f685c72999449b4e73a4.js js/application-f685c72999449b4e73a4.js.map
[0] multi ./app/javascript/packs/application.js ./app/javascript/packs/application.scss 40 bytes {application} [built]
[./.yarn/__virtual__/css-loader-virtual-68a818fad2/0/cache/css-loader-npm-3.6.0-3394f37d07-a45d7ee810.zip/node_modules/css-loader/dist/cjs.js?!./.yarn/cache/postcss-loader-npm-3.0.0-f4ab99b685-a6a922cbcc.zip/node_modules/postcss-loader/src/index.js?!./.yarn/__virtual__/sass-loader-virtual-b963274632/0/cache/sass-loader-npm-10.1.1-5a25ed7b45-dbd4ba06e2.zip/node_modules/sass-loader/dist/cjs.js?!./app/javascript/packs/application.scss] ./.yarn/__virtual__/css-loader-virtual-68a818fad2/0/cache/css-loader-npm-3.6.0-3394f37d07-a45d7ee810.zip/node_modules/css-loader/dist/cjs.js??ref--6-1!./.yarn/cache/postcss-loader-npm-3.0.0-f4ab99b685-a6a922cbcc.zip/node_modules/postcss-loader/src??ref--6-2!./.yarn/__virtual__/sass-loader-virtual-b963274632/0/cache/sass-loader-npm-10.1.1-5a25ed7b45-dbd4ba06e2.zip/node_modules/sass-loader/dist/cjs.js??ref--6-3!./app/javascript/packs/application.scss 5.34 KiB {application} [built] [failed] [1 error]
[./app/javascript/packs/application.js] 3.15 KiB {application} [built] [failed] [1 error]
[./app/javascript/packs/application.scss] 1.02 KiB {application} [built]
    + 1 hidden module

ERROR in ./app/javascript/packs/application.js
Module build failed (from ./.yarn/__virtual__/babel-loader-virtual-5e1e3f47a6/0/cache/babel-loader-npm-8.2.3-855681b984-78e1e1a919.zip/node_modules/babel-loader/lib/index.js):
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'babel-plugin-macros' imported from /mnt/d/Documents/Fullstack_Projects/fswd-todolist/babel-virtual-resolve-base.js
    at new NodeError (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:2552:5)
    at packageResolve (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3208:9)
    at moduleResolve (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3242:18)
    at defaultResolve (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3281:13)
    at /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3304:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:63:103)
    at _next (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:65:194)
    at /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:65:364
    at new Promise (<anonymous>)
    at /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:65:97
    at _resolve (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3311:19)
    at resolve (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:3294:19)
    at /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:38:38
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:20:103)
    at _next (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/@babel-core-npm-7.17.7-eda5ef1b9d-467838313f.zip/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:22:194)
 @ multi ./app/javascript/packs/application.js ./app/javascript/packs/application.scss application[0]

ERROR in ./app/javascript/packs/application.scss (./.yarn/__virtual__/css-loader-virtual-68a818fad2/0/cache/css-loader-npm-3.6.0-3394f37d07-a45d7ee810.zip/node_modules/css-loader/dist/cjs.js??ref--6-1!./.yarn/cache/postcss-loader-npm-3.0.0-f4ab99b685-a6a922cbcc.zip/node_modules/postcss-loader/src??ref--6-2!./.yarn/__virtual__/sass-loader-virtual-b963274632/0/cache/sass-loader-npm-10.1.1-5a25ed7b45-dbd4ba06e2.zip/node_modules/sass-loader/dist/cjs.js??ref--6-3!./app/javascript/packs/application.scss)
Module build failed (from ./.yarn/cache/postcss-loader-npm-3.0.0-f4ab99b685-a6a922cbcc.zip/node_modules/postcss-loader/src/index.js):
Error: Your application tried to access postcss-import, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: postcss-import
Required by: /mnt/d/Documents/Fullstack_Projects/fswd-todolist/

Require stack:
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/postcss.config.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/import-fresh-npm-2.0.0-8b4e6073aa-610255f975.zip/node_modules/import-fresh/index.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/cosmiconfig-npm-5.2.1-4a84462a41-8b6f1d3c8a.zip/node_modules/cosmiconfig/dist/loaders.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/cosmiconfig-npm-5.2.1-4a84462a41-8b6f1d3c8a.zip/node_modules/cosmiconfig/dist/createExplorer.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/cosmiconfig-npm-5.2.1-4a84462a41-8b6f1d3c8a.zip/node_modules/cosmiconfig/dist/index.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/postcss-load-config-npm-2.1.2-5372164a56-2e6d3a4995.zip/node_modules/postcss-load-config/src/index.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/postcss-loader-npm-3.0.0-f4ab99b685-a6a922cbcc.zip/node_modules/postcss-loader/src/index.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/loader-runner-npm-2.4.0-c414104c2f-e27eebbca5.zip/node_modules/loader-runner/lib/loadLoader.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/loader-runner-npm-2.4.0-c414104c2f-e27eebbca5.zip/node_modules/loader-runner/lib/LoaderRunner.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/__virtual__/webpack-virtual-762e04698a/0/cache/webpack-npm-4.46.0-a8158cfa7f-013fa24c00.zip/node_modules/webpack/lib/NormalModule.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/__virtual__/webpack-virtual-762e04698a/0/cache/webpack-npm-4.46.0-a8158cfa7f-013fa24c00.zip/node_modules/webpack/lib/NormalModuleFactory.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/__virtual__/webpack-virtual-762e04698a/0/cache/webpack-npm-4.46.0-a8158cfa7f-013fa24c00.zip/node_modules/webpack/lib/Compiler.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/__virtual__/webpack-virtual-762e04698a/0/cache/webpack-npm-4.46.0-a8158cfa7f-013fa24c00.zip/node_modules/webpack/lib/webpack.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/__virtual__/webpack-cli-virtual-5739b890ba/0/cache/webpack-cli-npm-3.3.12-3f0b130bc7-3097084e7b.zip/node_modules/webpack-cli/bin/utils/validate-options.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/__virtual__/webpack-cli-virtual-5739b890ba/0/cache/webpack-cli-npm-3.3.12-3f0b130bc7-3097084e7b.zip/node_modules/webpack-cli/bin/utils/convert-argv.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/__virtual__/webpack-cli-virtual-5739b890ba/0/cache/webpack-cli-npm-3.3.12-3f0b130bc7-3097084e7b.zip/node_modules/webpack-cli/bin/cli.js
- /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/__virtual__/webpack-virtual-762e04698a/0/cache/webpack-npm-4.46.0-a8158cfa7f-013fa24c00.zip/node_modules/webpack/bin/webpack.js
    at Function.require$$0.Module._resolveFilename (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.pnp.cjs:21091:13)
    at Function.require$$0.Module._load (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.pnp.cjs:20941:42)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/v8-compile-cache-npm-2.3.0-961375f150-adb0a271ea.zip/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/postcss.config.js:3:5)
    at Module._compile (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/v8-compile-cache-npm-2.3.0-961375f150-adb0a271ea.zip/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Object.require$$0.Module._extensions..js (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.pnp.cjs:21135:33)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.require$$0.Module._load (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.pnp.cjs:20972:14)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/v8-compile-cache-npm-2.3.0-961375f150-adb0a271ea.zip/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/import-fresh-npm-2.0.0-8b4e6073aa-610255f975.zip/node_modules/import-fresh/index.js:28:9)
    at loadJs (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/cosmiconfig-npm-5.2.1-4a84462a41-8b6f1d3c8a.zip/node_modules/cosmiconfig/dist/loaders.js:9:18)
    at Explorer.loadFileContent (/mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/cosmiconfig-npm-5.2.1-4a84462a41-8b6f1d3c8a.zip/node_modules/cosmiconfig/dist/createExplorer.js:230:12)
    at /mnt/d/Documents/Fullstack_Projects/fswd-todolist/.yarn/cache/cosmiconfig-npm-5.2.1-4a84462a41-8b6f1d3c8a.zip/node_modules/cosmiconfig/dist/createExplorer.js:252:21
 @ ./app/javascript/packs/application.scss 2:26-500
 @ multi ./app/javascript/packs/application.js ./app/javascript/packs/application.scss


Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Rendered layout layouts/application.html.erb (Duration: 14995.3ms | Allocations: 21047)
Completed 200 OK in 15087ms (Views: 15030.4ms | ActiveRecord: 0.0ms | Allocations: 24023)


^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2023-07-06 12:05:26 -0400 ===
- Goodbye!
Exiting
```

### Environment

-Node: v16.17.1
-Yarn: 1.22.19
-OS: Windows 10, WSL 2 Ubuntu 22.04

package.json
```
{
  "name": "fswd-todolist",
  "private": true,
  "engines": {
    "node": "^16.17"
  },
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "5.4.3",
    "bootstrap": "5.1.3",
    "jquery": "^3.7.0",
    "turbolinks": "^5.2.0",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3"
  },
  "packageManager": "yarn@1.22.19"
}
```

### Additional context

Apologies ahead of time. I'm in the midst of a bootcamp and I'm running into this issue. I can't continue the lesson until this is resolved and my teacher and I went through a ton of different things, none of which worked.

Here is my [current project](https://github.com/AtomicCow87/fswd-todolist). The biggest issue is that when my teacher downloads my files it runs perfectly fine. Just on my computer it doesn't work. 

This all started because bootstrap wasn't working and then I saw an error in the inspect element so I check terminal and I got that long list.

I just want to do my homework.

**Comment by nicolo-ribaudo** [comment]
Oh I see that you upgraded to Yarn 3. Then you _have to_ add all the Babel plugins to your package.json, because Yarn 2/3 only allows you to use dependencies that have been explicitly declared.

I think it's working on your teacher's machine either because they are not using yarn, or because they are using an old Yarn 1 version that does not detect the presence of Yarn 3 in your repository.

As a workaround, you could also add `nodeLinker: "node-modules"` to your `.yarnrc.yml` file, so that it installs dependencies "the old way" and they should be visible to Babel even if not explicitly listed in your package.json.

**Comment by AtomicCow87** [comment]
I could kiss you @nicolo-ribaudo.

I added the `nodeLinker: "node-modules"` to my `.yarnc.yml`. It failed but I noticed it pointed to `@babel/plugin-transform-private-property-in-object` as the reason. Well that was a fix I attempted to use previously so I changed it back to `@babel/plugin-proposal-private-methods` and it worked instantly.

[Here](https://github.com/AtomicCow87/fswd-todolist/commit/2d7783b916c0e1acd031ea2e1e2f6093187bf522) is the commit I did for the changes I made. I changed the two files, save and committed then did the following steps:

```
rm -rf node_modules
rails assets:clean
rails assets:clobber
yarn install
rake webpacker:clobber webpacker:compile <--finally worked!
rails s <-- also works and bootstrap not works as well!
```

Now I can complete this section. Again thank you do much!
