### ISSUE TITLE
async functions: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vially** [babel/babel#1580]
$ babel --version
5.4.4
$ regenerator --version
0.8.25
$ cat async.js

```js
async function bar() {}
```

$ babel --optional es7.asyncFunctions async.js
```
~/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:600
      throw err;
            ^
RangeError: async.js: Maximum call stack size exceeded
    at String.toString (native)
    at Type.Object.defineProperty.value (~/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:92:29)
    at Type.Object.defineProperties.check.value (~/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:34:36)
    at Field.Fp.getValue (~/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:232:22)
    at Object.getFieldValue (~/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:613:26)
    at NodePath.NPp.getValueProperty (~/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/node-path.js:116:18)
    at getChildPath (~/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:47:33)
    at NodePath.get (~/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:71:16)
    at visitChildren (~/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:222:34)
    at Visitor.PVp.visitWithoutReset (~/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
```

**Comment by sebmck** [comment]
[I can't reproduce this.](http://localhost:4000/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=async%20function%20bar()%20%7B%7D) Do you have a reproducible example on the REPL?

**Comment by vially** [comment]
Removing `node_modules` and reinstalling all the dependencies seems to have fixed the issue. Sorry for the noise.

**Comment by matgessel** [comment]
I encountered this error after changing babel from `5.4.7` to `5.5.5` and running `npm update`. Like @vially, `rm -rf node_modules; npm install` fixed it for me :)

**Comment by parties** [comment]
I tried removing `node_modules` and reinstalling, but I'm still having this problem with a file as simple as:

```js
class Service {
  async read(params) {}
}
```

Using
* `babel@5.6.17`
* `regenerator@0.8.34`

Any help?
