### ISSUE TITLE
[Bug]: SyntaxError: unknown: Unexpected token

### ISSUE THREAD

**Issue by tenadolanter** [babel/babel#15819]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code
```
const parser = require('@babel/core');
const code = `
export default {
  methods: {
    getYearArr() {
      for (let i = 0; i <= 100; i++) {
        // some thing ...
      }
    }
  }
};
`

const options = {
  // ...
};
const ast = parser.parse(code, options);
console.log("success...");
```

### Current and expected behavior

```
SyntaxError: unknown: Unexpected token (11:0)

|   }
  10 | };
> 11 | </script>
     | ^
  12 |
    at instantiate (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:63:32)
    at constructor (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:358:12)
    at Parser.raise (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:3255:19)
    at Parser.unexpected (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:3285:16)
    at Parser.parseExprAtom (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:11247:18)
    at Parser.parseExprSubscripts (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:10890:23)
    at Parser.parseUpdate (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:10873:21)
    at Parser.parseMaybeUnary (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:10849:23)
    at Parser.parseMaybeUnaryOrPrivate (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:10687:61)
    at Parser.parseExprOps (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:10692:23)
    at Parser.parseMaybeConditional (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:10669:23)
    at Parser.parseMaybeAssign (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:10630:21)
    at Parser.parseExpressionBase (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:10584:23)
    at /Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:10580:39
    at Parser.allowInAnd (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:12275:16)
    at Parser.parseExpression (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:10580:17)
    at Parser.parseStatementContent (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:12733:23)
    at Parser.parseStatementLike (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:12584:17)
    at Parser.parseModuleItem (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:12561:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:13185:36)
    at Parser.parseBlockBody (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:13178:10)
    at Parser.parseProgram (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:12460:10)
    at Parser.parseTopLevel (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:12450:25)
    at Parser.parse (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:14347:10)
    at parse (/Users/tenado/github/i18n-cli/node_modules/@babel/parser/lib/index.js:14388:38)
    at parser (/Users/tenado/github/i18n-cli/node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at parse (/Users/tenado/github/i18n-cli/node_modules/@babel/core/lib/parse.js:25:37)
    at parse.next (<anonymous>)
    at evaluateSync (/Users/tenado/github/i18n-cli/node_modules/gensync/index.js:251:28)
    at sync (/Users/tenado/github/i18n-cli/node_modules/gensync/index.js:89:14)
    at stopHiding - secret - don't use this - v1 (/Users/tenado/github/i18n-cli/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:46:12)
```

### Environment

- Babel version(s): v7.22.5
- Node: v18.6.0
- npm/Yarn version:  npm 8.10.0/Yarn 1.22.10
- OS: macOS 10.15.7

### Possible solution

`<=` causing the error， change `<=` to `<`,it works !

**Comment by nilerudra** [comment]
please give me the path of this code file.
