### ISSUE TITLE
[Bug]: TypeError: this.getOptions is not a function + SPFx

### ISSUE THREAD

**Issue by vchauhan1994** [babel/babel#15844]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

I am using Docx npm module in SharePoint Framework(React)

import { Document, Packer, Paragraph, TextRun } from "docx";

For that I want to use babel-loader.

### Configuration

{
        test: /\.(?:js|mjs|cjs)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              ['@babel/preset-env', { targets: "defaults" }]
            ]
          }
        }
      }

### Current and expected behavior

There should be no error while after using gulp bundle command but currently facing below error:

Error - [webpack] 'dist':
./lib/webparts/docxWebpart/DocxWebpartWebPart.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: this.getOptions is not a function
    at Object.loader (D:/Practice/DocxCreatorPOC/DocxReactPOC/node_modules/babel-loader/lib/index.js:44:28)
    at Object.<anonymous> (D:/Practice/DocxCreatorPOC/DocxReactPOC/node_modules/babel-loader/lib/index.js:39:12)

### Environment

babel-loader-9.1
Node: 16.20.1
NPM: 9.8.1
OS: Windows 10

**Comment by nicolo-ribaudo** [comment]
What is your webpack version?

**Comment by vchauhan1994** [comment]
> 

 "webpack": "^5.88.2"

**Comment by JLHwung** [comment]
Can you attach the output of `npm ls webpack`? And what is the build command of your app? Do you run `webpack` directly? Or do you run some devtools which invoke `webpack`?
