### ISSUE TITLE
[Node.js 20.6 bug] `@babel/core` does not work in node v20.6

### ISSUE THREAD

**Issue by liuxingbaoyu** [babel/babel#15927]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

/

### Current and expected behavior

![image](https://github.com/babel/babel/assets/30521560/8626766d-3f63-4c6a-97d1-9295d37bf947)

### Environment

node v20.6

### Additional context

https://github.com/babel/babel/actions/runs/6069179792/job/16493426064?pr=15922

**Comment by liuxingbaoyu** [comment]
https://github.com/nodejs/node/issues/49497

This is an upstream problem, and we may be difficult to solve.🤦‍♂️

**Comment by demurgos** [comment]
Error message in text form to help with search (the screenshot in the original post is not properly indexed, please avoid screenshots).

```text
/home/demurgos/.yarn/berry/cache/@babel-core-npm-7.22.5-d75e931080-10.zip/node_modules/@babel/core/lib/index.js:7
Object.defineProperty(exports, "File", {
       ^

TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/home/demurgos/.yarn/berry/cache/@babel-core-npm-7.22.5-d75e931080-10.zip/node_modules/@babel/core/lib/index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at require$$0.Module._extensions..js (/data/projects/eternaltwin/etwin/.pnp.cjs:22683:33)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at require$$0.Module._load (/data/projects/eternaltwin/etwin/.pnp.cjs:22531:31)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)

Node.js v20.6.0
```

**Comment by vedas-dixit** [comment]
Facing the same problem! any solutions?
*I've updated Node Version from 20.6 -> 20.9
![Uploading Screenshot 2023-11-08 170437.png…]()

**Comment by vedas-dixit** [comment]
Facing the same problem:

[plugin:vite:react-babel] Cannot redefine property: File
C:/Users/vedas dixit/Desktop/コード/Opensource/nom/idurar-erp-crm/frontend/src/main.jsx
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (C:\Users\vedas dixit\Desktop\コード\Opensource\nom\idurar-erp-crm\frontend\node_modules\@babel\core\lib\index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (C:\Users\vedas dixit\Desktop\コード\Opensource\nom\idurar-erp-crm\frontend\node_modules\@babel\core\lib\config\helpers\config-api.js:16:14)
    at Module._compile (node:internal/modules/cjs/loader:1241:14

**Comment by nicolo-ribaudo** [comment]
Update Node.js, they fixed the bug.

**Comment by MaxiCattaneoCvetic** [comment]
Hello, I have the same issue. I´m using Node 20.11.0 

[vite] Internal server error: Cannot redefine property: File
Plugin: vite:react-babel

**Comment by Codex-** [comment]
@MaxiCattaneoCvetic check your lock file, likely having an old version of babel
