### ISSUE TITLE
[Bug]: v7.22.11 broke something in my project

### ISSUE THREAD

**Issue by birdofpreyru** [babel/babel#15938]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Hey guys, I have my personal toolkit for React (https://github.com/birdofpreyru/react-utils), which uses Babel in a bunch of ways, and it all worked good up to Babel v7.22.10, but once upgraded to v7.22.11 some of my Jest tests start to fail with errors like below, although other tests (seemingly using the Babel in a similar way, with a similar config) work fine. And I very doubt that the primary error message **Plugin/Preset files are not allowed to export objects, only functions.** is correct, as doing so presumably wouldn't work with previous Babel v7.22.10.

And, yeah, I've seen a recent issue #15934 &mdash; not sure if it is related or not with my problem.

And if you wanna give it a try with my repo:
- Clone https://github.com/birdofpreyru/react-utils, checkout the latest commit (092b25efca99a67dfb4d2e1fa8a064ed25462f2d).
- `npm install && npm run build && npm run jest:1` &mdash; it works because Babel v7.22.10
- `npm install @babel/core@7.22.11 && npm run build && npm run jest:1` &mdash; it will fail now.

```
[BABEL]: Plugin/Preset files are not allowed to export objects, only functions. In /home/birdofprey/Documents/dr.pogodin.studio/react-utils/config/babel/node-ssr.js (While processing: /home/birdofprey/Documents/dr.pogodin.studio/react-utils/config/babel/node-ssr.js)

      at createDescriptor (node_modules/@babel/core/src/config/config-descriptors.ts:353:11)
          at createDescriptor.next (<anonymous>)
      at evaluateSync (node_modules/gensync/index.js:251:28)
      at node_modules/gensync/index.js:31:34
          at Array.map (<anonymous>)
      at Function.sync (node_modules/gensync/index.js:31:22)
      at Function.all (node_modules/gensync/index.js:210:24)
      at all (node_modules/@babel/core/src/config/config-descriptors.ts:264:38)
          at createDescriptors.next (<anonymous>)
      at createDescriptors (node_modules/@babel/core/src/config/config-descriptors.ts:240:17)
          at createPresetDescriptors.next (<anonymous>)
      at fn (node_modules/@babel/core/src/gensync-utils/functional.ts:10:54)
      at presets (node_modules/@babel/core/src/config/config-chain.ts:725:34)
          at mergeChainOpts.next (<anonymous>)
      at mergeChainOpts (node_modules/@babel/core/src/config/config-chain.ts:661:14)
          at chainWalker.next (<anonymous>)
      at loadFileChainWalker (node_modules/@babel/core/src/config/config-chain.ts:398:24)
          at loadFileChain.next (<anonymous>)
      at loadFileChain (node_modules/@babel/core/src/config/config-chain.ts:186:27)
          at buildRootChain.next (<anonymous>)
      at loadPrivatePartialConfig (node_modules/@babel/core/src/config/partial.ts:109:44)
          at loadPrivatePartialConfig.next (<anonymous>)
      at loadPrivatePartialConfig (node_modules/@babel/core/src/config/partial.ts:172:12)
          at loadPartialConfig.next (<anonymous>)
      at evaluateSync (node_modules/gensync/index.js:251:28)
      at sync (node_modules/gensync/index.js:89:14)
      at fn (node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:99:14)
      at loadPartialConfigSync (node_modules/@babel/core/src/config/index.ts:49:60)
      at loadPartialConfigSync (node_modules/@babel/core/src/config/index.ts:68:14)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:228:41)
      at ScriptTransformer._getFileCachePath (node_modules/@jest/transform/build/ScriptTransformer.js:289:27)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:525:32)
      at revertHook.exts (node_modules/@jest/transform/build/ScriptTransformer.js:776:18)
      at Module._compile (node_modules/pirates/lib/index.js:113:29)
      at newLoader (node_modules/pirates/lib/index.js:121:7)
      at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:121:7)
      at fn (node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:113:14)
      at loadCjsDefault (node_modules/@babel/core/src/config/files/module-types.ts:140:45)
      at loadCjsDefault (node_modules/@babel/core/src/config/files/module-types.ts:53:18)
          at loadCodeDefault.next (<anonymous>)
      at requireModule (node_modules/@babel/core/src/config/files/plugins.ts:238:36)
          at requireModule.next (<anonymous>)
      at requireModule (node_modules/@babel/core/src/config/files/plugins.ts:51:24)
          at loadPreset.next (<anonymous>)
      at resolver (node_modules/@babel/core/src/config/config-descriptors.ts:323:35)
          at createDescriptor.next (<anonymous>)
      at evaluateSync (node_modules/gensync/index.js:251:28)
      at node_modules/gensync/index.js:31:34
          at Array.map (<anonymous>)
      at Function.sync (node_modules/gensync/index.js:31:22)
      at Function.all (node_modules/gensync/index.js:210:24)
      at all (node_modules/@babel/core/src/config/config-descriptors.ts:264:38)
          at createDescriptors.next (<anonymous>)
      at createDescriptors (node_modules/@babel/core/src/config/config-descriptors.ts:240:17)
          at createPresetDescriptors.next (<anonymous>)
      at fn (node_modules/@babel/core/src/gensync-utils/functional.ts:10:54)
      at presets (node_modules/@babel/core/src/config/config-chain.ts:725:34)
          at mergeChainOpts.next (<anonymous>)
      at mergeChainOpts (node_modules/@babel/core/src/config/config-chain.ts:661:14)
          at chainWalker.next (<anonymous>)
      at loadFileChainWalker (node_modules/@babel/core/src/config/config-chain.ts:398:24)
          at loadFileChain.next (<anonymous>)
      at loadFileChain (node_modules/@babel/core/src/config/config-chain.ts:186:27)
          at buildRootChain.next (<anonymous>)
      at loadPrivatePartialConfig (node_modules/@babel/core/src/config/partial.ts:109:44)
          at loadPrivatePartialConfig.next (<anonymous>)
      at loadFullConfig (node_modules/@babel/core/src/config/full.ts:58:49)
          at loadFullConfig.next (<anonymous>)
      at loadOptionsImpl (node_modules/@babel/core/src/config/index.ts:74:39)
          at loadOptionsImpl.next (<anonymous>)
      at evaluateSync (node_modules/gensync/index.js:251:28)
      at sync (node_modules/gensync/index.js:89:14)
      at fn (node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:99:14)
      at loadOptionsSync (node_modules/@babel/core/src/config/index.ts:87:54)
      at OptionManager.init (node_modules/@babel/core/src/index.ts:100:31)
      at init (node_modules/@babel/register/src/worker/transform.js:81:44)
      at Function.transformSync (node_modules/@babel/register/src/worker/handle-message.js:15:16)
      at LocalClient.call (node_modules/@babel/register/src/worker-client.js:103:27)
      at LocalClient.call [as transform] (node_modules/@babel/register/src/worker-client.js:40:16)
      at transform (node_modules/@babel/register/src/hook.js:57:25)
      at compile (node_modules/@babel/register/src/hook.js:48:14)
      at Module._compile (node_modules/pirates/lib/index.js:113:29)
      at Module._compile (node_modules/pirates/lib/index.js:117:24)
      at newLoader (node_modules/pirates/lib/index.js:121:7)
      at Object.newLoader [as .jsx] (node_modules/pirates/lib/index.js:121:7)

(node:11298) Warning: Accessing non-existent property 'then' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11298) Warning: Accessing non-existent property 'browserslistConfigFile' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'include' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'exclude' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'env' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'overrides' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'ignore' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'only' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'extends' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'plugins' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'presets' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'passPerPreset' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'babelrc' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'babelrcRoots' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'then' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'include' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'exclude' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'overrides' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'ignore' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'only' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'extends' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'babelrc' of module exports inside circular dependency
(node:11298) Warning: Accessing non-existent property 'babelrcRoots' of module exports inside circular dependency
```

### Current and expected behavior

Not expecting from a patch release v7.22.11 to break anything in existing projects.

### Environment

  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  npmPackages:
    @babel/cli: ^7.22.10 => 7.22.10 
    @babel/core: ^7.22.11 => 7.22.11 
    @babel/eslint-parser: ^7.22.10 => 7.22.10 
    @babel/eslint-plugin: ^7.22.10 => 7.22.10 
    @babel/node: ^7.22.10 => 7.22.10 
    @babel/plugin-transform-runtime: ^7.22.10 => 7.22.10 
    @babel/preset-env: ^7.22.10 => 7.22.10 
    @babel/preset-react: ^7.22.5 => 7.22.5 
    @babel/register: ^7.22.5 => 7.22.5 
    @babel/runtime: ^7.22.11 => 7.22.11 
    babel-jest: ^29.6.4 => 29.6.4 
    babel-loader: ^9.1.3 => 9.1.3 
    babel-plugin-module-resolver: ^5.0.0 => 5.0.0 
    eslint: ^8.48.0 => 8.48.0 
    eslint-import-resolver-babel-module: ^5.3.2 => 5.3.2 
    jest: ^29.6.4 => 29.6.4 
    webpack: ^5.88.2 => 5.88.2

**Comment by JLHwung** [comment]
It seems to be related to #15916

Can you upgrade to `@babel/core@7.22.15` and see if this error persists?

**Comment by nicolo-ribaudo** [comment]
@birdofpreyru Could you push a branch with the upgrade, so that we can try your project exactly with all the packages versions that you are using?

**Comment by birdofpreyru** [comment]
@nicolo-ribaudo I guess, you removed your message, but anyway, here is the upgraded branch: https://github.com/birdofpreyru/react-utils/tree/babel-15938

So, `npm install && npm run build && npm run jest:1` and it fails me 3 test out of 20.

**Comment by nicolo-ribaudo** [comment]
Thank you! (yeah I removed my message because I can indeed reproduce the error with your instructions)

**Comment by nicolo-ribaudo** [comment]
The root cause of the problem is that there is a circular dependencies _somewhere_ including `config/babel/node-ssr.js` in the `require()` cycle, so its `module.exports` is not initialized yet when Babel tries to read it (and thus it finds the default empty exports object).

**Comment by nicolo-ribaudo** [comment]
As a workaround, use `@babel/register/experimental-worker` instead of `@babel/register` in `E2eSsrEnv.js`.

**Comment by nicolo-ribaudo** [comment]
Ok I know _why_ the different behavior, but I do not think that this is a Babel bug.

If I modify [this function](https://github.com/babel/babel/blob/159491e99f2770ded1578e0c593738729e7e4390/packages/babel-core/src/config/files/module-types.ts#L143) to manually cache `require()`'s result, the tests stop failing:
```diff
  const LOADING_CJS_FILES = new Set();
+ const REQUIRE_CACHE = new Map();
  function loadCjsDefault(filepath) {
+   if (REQUIRE_CACHE.has(filepath)) return REQUIRE_CACHE.get(filepath);
    if (LOADING_CJS_FILES.has(filepath)) {
      debug("Auto-ignoring usage of config %o.", filepath);
      return {};
    }
    let module;
    try {
      LOADING_CJS_FILES.add(filepath);
      module = (0, _rewriteStackTrace.endHiddenCallStack)(require)(filepath);
+     REQUIRE_CACHE.set(filepath, module);
    } finally {
      LOADING_CJS_FILES.delete(filepath);
    }
    {
      var _module;
      return (_module = module) != null && _module.__esModule ? module.default || (arguments[1] ? module : undefined) : module;
    }
  }
```

However, this should not be needed. `require()` already performs _exactly_ that caching, using `require.cache`. In Babel 7.22.10 we were caching before calling `require()`, while in Babel 7.22.11 we have cache after calling `require()` (using `require()`'s result as the cache key) because of https://github.com/babel/babel/pull/15850.

**Why is it important that `require()` is cached in this case?**

Your `node-ssr` preset is being used to compile a copy of itself, because there are multiple layers of compilation (one done by Jest itself, and one done by your usage of `@babel/register` inside your custom Jest env).  If `node-ssr` is already in `require()`'s cache (the `require` used by Babel, outside of Jest's virtualized environment) this is not a problem. I am being a little bit vague here because the Jest system is particularly complex and I didn't figure out exactly why this caching difference affects whether `node-ssr` is succesfully loaded or not.

However, given that by forcefully re-implementing Node.js's cache this problem does not happen, I'm inclined to not consider this a Babel bug.

**Possible solutions on your side**

1. Instead of `@babel/register`, use `@babel/register/experimental-worker`. This runs Babel in a `Worker`, with its own clean environment, and thus without re-entrancy risks.
2. Tell Jest to not compile `/config/babel/*`, by adding `'/(?!__tests__)[^/]+/config/babel/'` to `transformIgnorePatterns` in your Jest config. This still causes some warnings about circular `require()`s, but makes the problem disappear. If you want to also get rid of those warnings (caused by the config being used to compile itself -- it doesn't throw as for the preset because config files _can_ be objects), you can also add `'babel.config.js'` to `transformIgnorePatterns`.

**Comment by birdofpreyru** [comment]
Hey @nicolo-ribaudo , many thanks for help and detailed explanations! I'll give a try to `@babel/register/experimental-worker` &mdash; as you describe it, it is exactly what I need there, as the intention with that Jest testing environment is to test how results of server-side Babel compilation interplay with the results of client-side compilation with Webpack & Babel, so clean environment sounds very-very good.
