### ISSUE TITLE
[Bug]: module expression scope handling

### ISSUE THREAD

**Issue by DMartens** [babel/babel#16037]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

Code:
```js
const mod = module {}
```

Programmatic access:
```js
import { parseForESLint } from '@babel/eslint-parser'
parseForESLint(code, { plugins: ["@babel/proposal-syntax-module-blocks" })
```

### Configuration file name

babel.config.js

### Configuration

```json
{
	"plugins": ["@babel/proposal-syntax-module-blocks"]
}
```

### Current and expected behavior

Currently parsing any code module expression and analyzing the scope will lead to an error:
```txt
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(this.__currentScope === null)

    at ScopeManager.__nestScope (project/node_modules/.pnpm/eslint-scope@5.1.1/node_modules/eslint-scope/lib/scope-manager.js:193:13)
    at ScopeManager.__nestGlobalScope (project/node_modules/.pnpm/eslint-scope@5.1.1/node_modules/eslint-scope/lib/scope-manager.js:201:21)
    at Referencer.Program (project/node_modules/.pnpm/eslint-scope@5.1.1/node_modules/eslint-scope/lib/referencer.js:412:27)
    at Referencer.Visitor.visit (project/node_modules/.pnpm/esrecurse@4.3.0/node_modules/esrecurse/esrecurse.js:104:34)
    at Referencer.Visitor.visitChildren (project/node_modules/.pnpm/esrecurse@4.3.0/node_modules/esrecurse/esrecurse.js:88:26)
    at Referencer.Visitor.visit (project/node_modules/.pnpm/esrecurse@4.3.0/node_modules/esrecurse/esrecurse.js:107:14)
    at Referencer.VariableDeclaration (project/node_modules/.pnpm/eslint-scope@5.1.1/node_modules/eslint-scope/lib/referencer.js:536:22)
    at Referencer.Visitor.visit (project/node_modules/.pnpm/esrecurse@4.3.0/node_modules/esrecurse/esrecurse.js:104:34)
    at Referencer.Visitor.visitChildren (project/node_modules/.pnpm/esrecurse@4.3.0/node_modules/esrecurse/esrecurse.js:83:38)
    at Referencer.Program (project/node_modules/.pnpm/eslint-scope@5.1.1/node_modules/eslint-scope/lib/referencer.js:429:14)
```
This is triggered [here in eslint-scope](https://github.com/eslint/eslint-scope/blob/115ded3cb6f768a37f0dcb17bb16e2299849e16f/lib/scope-manager.js#L193)

The expectation is that no error is thrown.

### Environment

- Babel: 7.23.0
- Node: 20.8.0
- npm: 10.2.0
- OS: Linux
- Monorepo: no

### Possible solution

The problem is that for module expressions `Program` nodes are generated which are already handled in `eslint-scope` .
The default visitor creates a global scope and expects no other scope to have been created.
As such the node must be handled explicitly in the [referencer](https://github.com/eslint/eslint-scope/blob/115ded3cb6f768a37f0dcb17bb16e2299849e16f/lib/referencer.js#L112).
Either:
- keep using a `Program` node but not adding a global scope for module expressions in the referencer
- use a `ModuleBlock` node according to [ESTree](https://github.com/estree/estree/blob/master/experimental/module-expressions.md) and add a visitor to the referencer

### Additional context

I saw PR #15240 but this change also keeps creating `Program` nodes.
If this bug report is approved would you prefer creating a `ModuleScope` or a new kind of scope for module expressions?

**Comment by DMartens** [comment]
Is there anything unclear with the bug report?
To summarize, the parser creates `Program` nodes for the bodies of the `ModuleExpression` which `eslint-scope` only expects once.
I successfully tried locally updating the `Program` visitor for `eslint-scope` by using a flag to check whether there was already a program node and if there was, nest an `ModuleScope` instead. 
So no code changes are required for the parser if this is a concern.

**Comment by JLHwung** [comment]
Note that the `eslint-scope` only supports stage-4 proposals. So it will throw on module expressions.

In `@babel/eslint-parser` we patch the `eslint-scope` for the Babel AST: https://github.com/babel/babel/blob/main/eslint/babel-eslint-parser/src/analyze-scope.cjs

feel free to do the same for module expressions.

As for the AST design, the `@babel/eslint-parser`'s policy is to follow ESTree after eslint has implemented it, otherwise use Babel AST instead. So the `analyze-scope.cjs` should handle the nested `Program` node. We can create a `ModuleScope` like you said.
