### ISSUE TITLE
document is undefined

### ISSUE THREAD

**Issue by gsklee** [babel/babel#1603]
I was using v5.4.5 yesterday and everything was fine; updated to v5.4.7 just now and things are breaking.

What I encountered (totally fine without error before today's npm update):

```
/srv/home/kaylee/project-x/source/scripts/misc/constants.js:10
  GRID_WIDTH: (document.documentElement.clientWidth - 2 * 2 * 16) / 12,
               ^
ReferenceError: document is not defined
    at Object.<anonymous> (/srv/home/kaylee/project-x/source/scripts/misc/constants.js:4:16)
    at Module._compile (module.js:431:26)
    at normalLoader (/srv/home/kaylee/project-x/node_modules/babel-core/lib/babel/api/register/node.js:150:5)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/home/kaylee/project-x/node_modules/babel-core/lib/babel/api/register/node.js:163:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/srv/home/kaylee/project-x/source/scripts/misc/helpers.js:1:24)
    at Module._compile (module.js:431:26)
```

Code in question:

```javascript
export default {
  GRID_WIDTH: (document.documentElement.clientWidth - 2 * 2 * 16) / 12
};
```

Thoughts?

**Comment by gsklee** [comment]
This cannot be circumvented by using `window.document` BTW so I'm totally stuck at here now:

```
/srv/home/kaylee/project-x/source/scripts/misc/constants.js:10
  GRID_WIDTH: (window.document.documentElement.clientWidth - 2 * 2 * 16) / 12,
               ^
ReferenceError: window is not defined
```

**Comment by monsanto** [comment]
Why do you expect this to work? You are running it in node.js, which does not declare those variables.

**Comment by gsklee** [comment]
@monsanto This is being bundled by webpack into client-side JavaScript and has been working on my production environment for months.

**Comment by monsanto** [comment]
Do you have a self-contained reproducible example? Your traceback is exactly what you get if you run that sample in `babel-node` which is why I assumed that you were running this under node.

**Comment by gsklee** [comment]
@monsanto Actually - you're right. I accidentally included a file which contains `constants.js` high up in the require chain. Sorry for the false alarm.
