### ISSUE TITLE
Investigate Node.js 6 CI failure

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#16035]
Somehow CI started failing since https://github.com/babel/babel/commit/cd28f070310be0f2419924ce8aa526827746795f.

It's not a regression, since it seems to be specific to our own stack traces:
```
  ● @babel/core errors › error inside config function

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `@babel/core errors error inside config function 1`

    - Snapshot
    + Received

      Error: Error inside config!
          at myConfig (<CWD>/packages/babel-core/test/fixtures/errors/error-config-function/babel.config.js:_:_)
    -     at Module.parseSync (<CWD>/packages/babel-core/src/parse.ts:_:_)
    +     at undefined.parseSync (<CWD>/packages/babel-core/src/parse.ts:_:_)
          at <CWD>/packages/babel-core/test/errors-stacks.js:_:_
          at expectError (<CWD>/packages/babel-core/test/errors-stacks.js:_:_)
          at <CWD>/packages/babel-core/test/errors-stacks.js:_:_
          at ... internal jest frames ...

```

**Comment by liuxingbaoyu** [comment]
```
  ● transformScriptTags › should transform script element with type 'text/babel'

    ReferenceError: URL is not defined

       9 |   beforeAll(async () => {
      10 |     standaloneSource = fs.readFileSync(
    > 11 |       new URL("../babel.js", import.meta.url),
         |           ^
      12 |       "utf8",
      13 |     );
      14 |     JSDOM = require("jsdom").JSDOM;

      at Object.<anonymous> (packages/babel-standalone/test/transform-script-tags.test.js:11:11)
      at asyncGeneratorStep (packages/babel-standalone/test/transform-script-tags.test.js:3:43)
      at _next (packages/babel-standalone/test/transform-script-tags.test.js:3:43)
      at packages/babel-standalone/test/transform-script-tags.test.js:3:43
      at Object.<anonymous> (packages/babel-standalone/test/transform-script-tags.test.js:3:43)
```

This seems like a very strange problem.
