### ISSUE TITLE
"Cannot call method '_containerInsertBefore' of undefined"

### ISSUE THREAD

**Issue by atombender** [babel/babel#1614]
Getting this:

```
# babel <<EOT
'use strict';
function f(args) {
  switch (name) {
    case 'get':
      this.store.get(...args);
  }
}
EOT

TypeError: unknown: Cannot call method '_containerInsertBefore' of undefined
    at Scope.push (/tmp/test/node_modules/babel/node_modules/babel-core/lib/babel/traversal/scope/index.js:745:68)
    at Scope.maybeGenerateMemoised (/tmp/test/node_modules/babel/node_modules/babel-core/lib/babel/traversal/scope/index.js:362:27)
    at TraversalPath.CallExpression (/tmp/test/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformers/es6/spread.js:103:22)
    at TraversalPath.call (/tmp/test/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/index.js:928:28)
    at TraversalPath.visit (/tmp/test/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/index.js:960:10)
    at TraversalContext.visitSingle (/tmp/test/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:90:12)
    at TraversalContext.visit (/tmp/test/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:102:19)
    at Function.traverse.node (/tmp/test/node_modules/babel/node_modules/babel-core/lib/babel/traversal/index.js:64:17)
    at TraversalPath.visit (/tmp/test/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/index.js:977:28)
    at TraversalContext.visitMultiple (/tmp/test/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:70:16)
```

This is Babel 5.4.7.

**Comment by atombender** [comment]
Thank you!
