### ISSUE TITLE
[Bug]: @babel/helper-compilation-targets: 'opera_mobile' is not a valid target when upgrading babel/core to 7.23.6

### ISSUE THREAD

**Issue by zuyetawarmatik** [babel/babel#16171]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

The problem happens when only upgrading @babel/core from 7.23.5 to 7.23.6. I'm using babel-loader for react

```
@babel/helper-compilation-targets: 'opera_mobile' is not a valid target

Did you mean 'opera'? (While processing: "/Users/dbui/git/ui/node_modules/babel-preset-react-app/dependencies.js$0$43")
    at validateTargetNames (/Users/dbui/git/ui/node_modules/@babel/helper-define-polyfill-provider/node_modules/@babel/helper-compilation-targets/lib/index.js:60:13)
    at getTargets (/Users/dbui/git/ui/node_modules/@babel/helper-define-polyfill-provider/node_modules/@babel/helper-compilation-targets/lib/index.js:167:17)
    at resolveOptions (/Users/dbui/git/ui/node_modules/@babel/helper-define-polyfill-provider/lib/index.js:87:15)
    at instantiateProvider (/Users/dbui/git/ui/node_modules/@babel/helper-define-polyfill-provider/lib/index.js:115:7)
    at /Users/dbui/git/ui/node_modules/@babel/helper-define-polyfill-provider/lib/index.js:235:9
    at /Users/dbui/git/ui/node_modules/@babel/helper-define-polyfill-provider/node_modules/@babel/helper-plugin-utils/lib/index.js:31:12
    at async (/Users/dbui/git/ui/node_modules/@babel/core/lib/gensync-utils/async.js:35:33)
    at async (/Users/dbui/git/ui/node_modules/gensync/index.js:186:15)
    at /Users/dbui/git/ui/node_modules/gensync/index.js:216:13
    at Generator.next (<anonymous>)
    at /Users/dbui/git/ui/node_modules/@babel/core/lib/config/full.js:180:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/dbui/git/ui/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
    at Generator.next (<anonymous>)
    at step (/Users/dbui/git/ui/node_modules/gensync/index.js:269:25)
    at evaluateAsync (/Users/dbui/git/ui/node_modules/gensync/index.js:291:5)
    at Function.errback (/Users/dbui/git/ui/node_modules/gensync/index.js:113:7)
    at errback (/Users/dbui/git/ui/node_modules/@babel/core/lib/gensync-utils/async.js:65:18)
    at async (/Users/dbui/git/ui/node_modules/gensync/index.js:188:17)
    at onFirstPause (/Users/dbui/git/ui/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at cachedFunction (/Users/dbui/git/ui/node_modules/@babel/core/lib/config/caching.js:52:46)
    at cachedFunction.next (<anonymous>)
    at loadPluginDescriptor (/Users/dbui/git/ui/node_modules/@babel/core/lib/config/full.js:259:42)
    at loadPluginDescriptor.next (<anonymous>)
    at loadPluginDescriptors (/Users/dbui/git/ui/node_modules/@babel/core/lib/config/full.js:129:33)
    at loadPluginDescriptors.next (<anonymous>)
    at /Users/dbui/git/ui/node_modules/@babel/core/lib/config/full.js:156:21
    at Generator.next (<anonymous>)
    at loadFullConfig (/Users/dbui/git/ui/node_modules/@babel/core/lib/config/full.js:141:5)
    at loadFullConfig.next (<anonymous>)
    at transform (/Users/dbui/git/ui/node_modules/@babel/core/lib/transform.js:20:44)
    at transform.next (<anonymous>)
    at step (/Users/dbui/git/ui/node_modules/gensync/index.js:269:25)
    at /Users/dbui/git/ui/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/dbui/git/ui/node_modules/gensync/index.js:223:11)
    at /Users/dbui/git/ui/node_modules/gensync/index.js:189:28
    at /Users/dbui/git/ui/node_modules/@babel/core/lib/gensync-utils/async.js:67:7
    at /Users/dbui/git/ui/node_modules/gensync/index.js:113:33
    at step (/Users/dbui/git/ui/node_modules/gensync/index.js:287:14)
    at /Users/dbui/git/ui/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/dbui/git/ui/node_modules/gensync/index.js:223:11)
```

### Current and expected behavior

Should not break the build

### Environment

"@babel/cli": "^7.23.4",
    "@babel/core": "^7.23.6",
    "@babel/eslint-parser": "^7.23.3",
    "@babel/plugin-transform-react-constant-elements": "^7.23.3",
    "@babel/plugin-transform-runtime": "^7.23.6",
    "@babel/preset-env": "^7.23.6",
    "@babel/preset-react": "^7.23.3",

"babel-jest": "^29.7.0",
    "babel-loader": "^9.1.3",
    "babel-plugin-dynamic-import-node": "^2.3.3",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-preset-react-app": "^10.0.1",
    
"webpack": "^5.89.0",

node: 20.10.0

**Comment by liuxingbaoyu** [comment]
If you delete your `node_modules` and `package-lock.json` and re-run `npm i` will it work?

**Comment by sumanbh** [comment]
You might have multiple versions of helper-compilation-targets in your project. 

An alternative to deleting lockfile would be to dedupe (or override) your dependency tree so it all points to `7.23.6`:
```sh
yarn dedupe
# or
pnpm dedupe
```

**Comment by zuyetawarmatik** [comment]
> You might have multiple versions of helper-compilation-targets in your project.
> 
> An alternative to deleting lockfile would be to dedupe (or override) your dependency tree so it all points to `7.23.6`:
> 
> ```shell
> yarn dedupe
> # or
> pnpm dedupe
> ```

`yarn install` will do dedupe automatically, and this is not working.
Putting into resolutions like this isn't working too.
```
resolutions: {
  @babel/helper-compilation-targets: 7.2.6
}
```

**Comment by zuyetawarmatik** [comment]
> If you delete your `node_modules` and `package-lock.json` and re-run `npm i` will it work?

I use yarn and yarn cache clean, and it's not working

**Comment by liuxingbaoyu** [comment]
> yarn install will do dedupe automatically, and this is not working.

I remember not dedupe automatically, but resolutions should work.
Can you provide a repository to reproduce?

**Comment by KlavierCat** [comment]
Do you happen to have a `browserslist` config somewhere? If you do, what happens if you delete this or make its value empty?

**Comment by zuyetawarmatik** [comment]
> Do you happen to have a `browserslist` config somewhere? If you do, what happens if you delete this or make its value empty?

our browserlist is:
```
  "browserslist": [
    ">0.2%",
    "not dead",
    "not android > 0",
    "not op_mini all"
  ]
```

**Comment by zuyetawarmatik** [comment]
OK I figured out the culprit: This is due to some library is using an old version of `@babel/helper-compilation-targets`:
- @babel/helper-compilation-targets (old version, targets don't contain opera_mobile => crash)
=> @babel/helper-define-polyfill-provider (yarn resolves to 0.3.3, but not 0.4.4)
=> babel-plugin-polyfill-corejs3/babel-plugin-polyfill-corejs2 (old versions)
=> @babel/plugin-transform-runtime (old ver 7.16.4)
=> babel-preset-react-app 10.0.1 (very old, not maintained by FB since 2021) (But I can't get rid of it in near future).

**Comment by zuyetawarmatik** [comment]
I will close this issue

**Comment by jasrhoyt** [comment]
Anyone who finds themselves here looking for a solution, ignoring operah_mobile in your browserslist config solved my problem:
` "browserslist": [
    ">0.2%",
    "not dead",
    "not android > 0",
    "not op_mini all",
    "not op_mob >=1"
  ]`
