### ISSUE TITLE
[Bug]: Cannot find package '@babel/plugin-preset-typescript' when using @babel/preset-typescript

### ISSUE THREAD

**Issue by MrDiamondDog** [babel/babel#16244]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

index.tsx
```tsx
function Component() {
    const [state, setState] = useState(0);
    return <button onClick={() => setState(state + 1)}>{state}</button>;
}
```

Command used to run
`npx babel index.tsx`

### Configuration file name

babel.config.json, .babelrc

### Configuration

```json
{
    "plugins": ["@babel/preset-typescript"]
}
```

### Current and expected behavior

It keeps throwing this error for no reason, I have no clue why, and I can't find any issues relating to this anywhere.

Full Error:

```
Error: Cannot find package '@babel/plugin-preset-typescript' imported from /home/mrdiamond/Documents/Workspace/custom-jsx/babel-virtual-resolve-base.js
    at new NodeError (/home/mrdiamond/Documents/Workspace/custom-jsx/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:194:5)
    at packageResolve (/home/mrdiamond/Documents/Workspace/custom-jsx/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:908:9)
    at moduleResolve (/home/mrdiamond/Documents/Workspace/custom-jsx/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:937:20)
    at defaultResolve (/home/mrdiamond/Documents/Workspace/custom-jsx/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1007:15)
    at resolve (/home/mrdiamond/Documents/Workspace/custom-jsx/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1020:12)
    at tryImportMetaResolve (/home/mrdiamond/Documents/Workspace/custom-jsx/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/config/files/plugins.js:142:45)
    at resolveStandardizedNameForImport (/home/mrdiamond/Documents/Workspace/custom-jsx/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/config/files/plugins.js:164:19)
    at resolveStandardizedName (/home/mrdiamond/Documents/Workspace/custom-jsx/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/config/files/plugins.js:173:22)
    at loadPlugin (/home/mrdiamond/Documents/Workspace/custom-jsx/node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/config/files/plugins.js:52:20)
    at loadPlugin.next (<anonymous>) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Environment

- Babel CLI: 7.23.9
- Babel TS Preset: 7.23.3
- OS: Ubuntu
- Node: 18.18.2
- pnpm: 8.11.0

**Comment by MrDiamondDog** [comment]
Oops, simple fix:

```
{
    "plugins": ["@babel/preset-typescript"]
}
```

Should be 

```
{
    "presets": ["@babel/preset-typescript"]
}
```
