### ISSUE TITLE
Requiring es6 module from node_modules/ results in "'import' and 'export' may appear only with 'sourceType: module'"

### ISSUE THREAD

**Issue by sunjay** [babel/babel#1625]
I published some of my project's code to a public scoped npm package here: https://www.npmjs.com/package/@anyware/streaming-client

Then I required it in an es6 module (using require instead of the import syntax):

    const StreamingClient = require('@anyware/streaming-client');

I now get this error whenever I run babelify and browserify:

    'import' and 'export' may appear only with 'sourceType: module'

It seems to not like that I use `export` in the [src/streaming-client.js](https://github.com/anyWareSculpture/streaming-client/blob/master/src/streaming-client.js#L65) file (which is an ES6 module too).

**Comment by sebmck** [comment]
Stack trace please.

**Comment by sunjay** [comment]
Probably not the most useful stacktrace since you'll need my gulpfile and a whole bunch of other stuff to understand it:

	/sculpture-emulator-client/gulpfile.js:56
		throw new Error(err);
		      ^
	Error: Error: Parsing file /sculpture-emulator-client/node_modules/@anyware/streaming-client/src/streaming-client.js: 'import' and 'export' may appear only with 'sourceType: module' (65:0)
	    at Readable.<anonymous> (/sculpture-emulator-client/gulpfile.js:56:15)
	    at Readable.emit (events.js:107:17)
	    at Labeled.<anonymous> (/sculpture-emulator-client/node_modules/browserify/node_modules/read-only-stream/index.js:27:44)
	    at Labeled.emit (events.js:107:17)
	    at Labeled.<anonymous> (/sculpture-emulator-client/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:132:18)
	    at Labeled.emit (events.js:129:20)
	    at Deps.<anonymous> (/sculpture-emulator-client/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:132:18)
	    at Deps.emit (events.js:107:17)
	    at Deps.parseDeps (/sculpture-emulator-client/node_modules/browserify/node_modules/module-deps/index.js:436:14)
	    at fromSource (/sculpture-emulator-client/node_modules/browserify/node_modules/module-deps/index.js:375:44)

**Comment by sebmck** [comment]
Change `throw new Error(err);` to `throw err;` you're destroying the original stack trace. Would be easier to debug this with steps to reproduce?

**Comment by sunjay** [comment]
Unfortunately that's not me, that's gulp and Babelify.

**Comment by sebmck** [comment]
Nope, it is you. See [sculpture-emulator-client/gulpfile.js](https://github.com/anyWareSculpture/sculpture-emulator-client/blob/master/gulpfile.js#L56).

**Comment by sunjay** [comment]
Hmmm sorry about that. I took that out and now this:

sculpture-emulator-client/gulpfile.js:56
        throw err;
              ^
Error: Parsing file sculpture-emulator-client/node_modules/@anyware/streaming-client/src/streaming-client.js: 'import' and 'export' may appear only with 'sourceType: module' (65:0)
    at Deps.parseDeps (sculpture-emulator-client/node_modules/browserify/node_modules/module-deps/index.js:436:28)
    at fromSource (sculpture-emulator-client/node_modules/browserify/node_modules/module-deps/index.js:375:44)
    at sculpture-emulator-client/node_modules/browserify/node_modules/module-deps/index.js:369:17
    at ConcatStream.<anonymous> (sculpture-emulator-client/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:129:20)
    at finishMaybe (sculpture-emulator-client/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (sculpture-emulator-client/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (sculpture-emulator-client/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (sculpture-emulator-client/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:199:16)

**Comment by sebmck** [comment]
Grrr, the original source is still being hidden. I highly doubt it's a Babel issue and is most likely related to your config since I've seen that issue come up and it's a result of another transform using `acorn` and running **before** `babelify` is. Can't really go any further without steps to reproduce as it extremely limits my debug capabilities.

**Comment by loganfsmyth** [comment]
@sunjay Are you transpiling `streaming-client` before publishing it? Your sculpture-emulator-client gulpfile `browserify` setup only runs babelify on `sculpture-emulator-client/src/**/*.js` and `streaming-client/package.json` has `main` pointing at the ES6 source, not at transpiled ES5.

Normally I'd expect the module `main` to point and prepublish transpiled ES5 code, or for the main to point at ES6, with `babelify` specified as a module-level transform.

**Comment by sunjay** [comment]
That's probably the issue. I assumed that Babel would transpile the
required files too. (Though that probably doesn't make sense now that I
think about it)

That explains it. I'll transpile my file.

Thanks!

**Comment by sunjay** [comment]
I should note that I was requiring that dependency as a local file before and it was all working so that means that local files that are required do get transpiled but node modules do not

**Comment by loganfsmyth** [comment]
Babel only runs on a per-file basis, it is browserify that decides which files to run it on.

    .transform(babelify)

tells Browserify to run `babelify` on any file within the current module. That does not include dependencies. With your current setup, it should be as simple as adding

    "browserify": { "transform": [ "babelify" ] }

as a into the `package.json` of `streaming-client`. That tells browserify that any time it requires a file inside that module that it needs to run it through that transform when packaging it.

**Comment by loganfsmyth** [comment]
If you have any other support questions, feel free to ask in Babel's support channel: https://gitter.im/babel/babel

**Comment by sunjay** [comment]
@loganfsmyth Wow! It worked! Thank you! That's really awesome. I just added that line to my `package.json` and it worked seamlessly.

**Comment by josezy** [comment]
@loganfsmyth How can I make it include dependencies?

**Comment by qiulang** [comment]
Except for adding ` "browserify": { "transform": [ "babelify" ] }` to package.json I find I still need to set `.babelrc` with appropriate presets otherwise I still get the import error.

But why was this? I had thought I only needed to `.babelrc` at the place which uses my module.
