### ISSUE TITLE
Unknown transformer 7 specified in optional

### ISSUE THREAD

**Issue by mjackson** [babel/babel#1636]
I'm having trouble using the `es7.exportExtensions` transformer. It's listed in my `.babelrc` under the `options` field, but Babel can't find it.

```
michael:~/Projects/react-router$ cat .babelrc
{
  "optional": [ "es7.classProperties", "es7.exportExtensions" ],
  "plugins": [ "object-assign" ]
}
michael:~/Projects/react-router$ cat package.json | grep babel
    "babel": "^5.4.7",
    "babel-core": "^5.4.7",
    "babel-plugin-object-assign": "^1.1.0",
michael:~/Projects/react-router$ npm run build

...

ReferenceError: Unknown transformer 7 specified in optional
    at TransformerPipeline._ensureTransformerNames (/Users/michael/Projects/react-router/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:125:15)
    at transformerList (/Users/michael/Projects/react-router/node_modules/babel-core/lib/babel/transformation/file/option-parsers.js:23:19)
    at File.normalizeOptions (/Users/michael/Projects/react-router/node_modules/babel-core/lib/babel/transformation/file/index.js:187:31)
    at new File (/Users/michael/Projects/react-router/node_modules/babel-core/lib/babel/transformation/file/index.js:145:22)
    at TransformerPipeline.transform (/Users/michael/Projects/react-router/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:87:16)
    at Object.exports.transform (/Users/michael/Projects/react-router/node_modules/babel/bin/babel/util.js:33:22)
    at Object.exports.compile (/Users/michael/Projects/react-router/node_modules/babel/bin/babel/util.js:41:18)
    at write (/Users/michael/Projects/react-router/node_modules/babel/bin/babel/dir.js:16:21)
    at handleFile (/Users/michael/Projects/react-router/node_modules/babel/bin/babel/dir.js:37:7)
    at /Users/michael/Projects/react-router/node_modules/babel/bin/babel/dir.js:53:9
```

Any ideas what I'm doing wrong?

**Comment by sebmck** [comment]
Do you have parent `.babelrc`s?

**Comment by sebmck** [comment]
Ping @mjackson

**Comment by Mark-Simulacrum** [comment]
I was hit by what appears to be a similar bug:
```
rawKeys [ 'es6.tailCall', 's', '6', '.', 'c', 'l', 'a', 's', 's', 'e', 's' ]
lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:127
        throw new ReferenceError("Unknown transformer " + key + " specified in
              ^
ReferenceError: Unknown transformer s specified in blacklist
    at TransformerPipeline._ensureTransformerNames (lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:127:15)
    at transformerList (lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/option-parsers.js:23:19)
    at File.normalizeOptions (lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:187:31)
    at new File (lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:145:22)
    at TransformerPipeline.transform (lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:87:16)
    at Object.exports.transform (lib/node_modules/babel/bin/babel/util.js:33:22)
    at Object.exports.compile (lib/node_modules/babel/bin/babel/util.js:41:18)
    at lib/node_modules/babel/bin/babel/file.js:120:23
    at arrayEach (lib/node_modules/babel/node_modules/lodash/index.js:1314:13)
    at Function.<anonymous> (lib/node_modules/babel/node_modules/lodash/index.js:3355:13)
```

The "rawKeys" line at the very top is debugging I added to `TransformerPipeline._ensureTransformerNames`, at the very top of the method:
```js
console.log("rawKeys", rawKeys);
```

From my testing, it seems to only happen with a relative path (not `~/dir` or `/dir`).

Environment:
  - babel v5.4.7
  - command: `babel --blacklist "es6.classes" ./src/babel/messages.js`
    - while run in babel's master branch (if it is important, but I doubt that it is).

Please tell me if it would be helpful to have more information.

**Comment by sebmck** [comment]
Ah. I think it's because the configs are being merged without being normalised to their proper data types.
