### ISSUE TITLE
[Bug]: When a ES Module defines a class named `Object`, babel's transpilation makes an unusable file

### ISSUE THREAD

**Issue by julienw** [babel/babel#16601]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

I created this project to show this issue:

https://github.com/julienw/babel-object-issue

You can also reproduce [in this REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwDYEMDOa4HkBGArYBeAbwF8AoIA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.24.7&externalPlugins=&assumptions=%7B%7D).

### Configuration file name

babel.config.json

### Configuration

```json
{
  "targets": ["last 2 chrome versions", "last 2 firefox versions"],
  "presets": [
    ["@babel/preset-env", { "useBuiltIns": false }]
  ]
}
```

### Current and expected behavior

Current behavior: there's an error when running the file with `babel-node`:
```
Object.defineProperty(exports, "__esModule", {
    ^

    ReferenceError: Cannot access 'Object' before initialization
    at Object.<anonymous> (/home/julien/travail/git/babel-object-issue/Object.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._compile (/home/julien/travail/git/babel-object-issue/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Object.newLoader [as .js] (/home/julien/travail/git/babel-object-issue/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.runMain (node:internal/modules/run_main:128:12)
    at Object.<anonymous> (/home/julien/travail/git/babel-object-issue/node_modules/@babel/node/src/_babel-node.ts:228:12)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49
```

The problem is that Babel adds this preample to the file:
```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
```
And of course the `Object` here doesn't refer to the right one anymore.

Expected: Babel can transpile this file to a working file.

### Environment

 ```
  System:
    OS: Linux 6.7 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    bun: 1.0.29 - ~/.bun/bin/bun
  npmPackages:
    @babel/cli: ^7.24.7 => 7.24.7 
    @babel/node: ^7.24.7 => 7.24.7 
    @babel/preset-env: ^7.24.7 => 7.24.7 
```

### Possible solution

TBH I'm not so sure.
Maybe rename the Object class to something else to avoid the name collision?

Or detect if a collision might happen, and use something such as `({}).prototype.defineProperty` in that case?

### Additional context

I've seen this issue in the wild, in the `taskcluster-client-web` library. I'm gonna report the issue there too. (Update: reported in https://github.com/taskcluster/taskcluster/issues/7110)

**Comment by JLHwung** [comment]
https://babel.dev/docs/caveats#built-ins

Babel assumes that the builtins are not modified. If they were modified, Babel expects it is sufficiently well polyfilled. In your case, the `Object` has been shadowed and replaced by a custom class, so Babel can not guarantee the output is correct. Like you said, a workaround will be to avoid shadowing the builtins.
