### ISSUE TITLE
[Bug]: TypeError: unknown file: _getAssignmentIdentifiers is not a function

### ISSUE THREAD

**Issue by mcguyvor** [babel/babel#16716]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

TypeError: unknown file: _getAssignmentIdentifiers is not a function

### Configuration file name

package.json

### Configuration

 "@babel/preset-env": "7.22.20",
    "@babel/runtime": "7.23.1",
    "@babel/runtime-corejs3": "7.23.1",
    "@babel/types": "7.23.0",
"@babel/core": "^7.22.20",
    "@babel/cli": "^7.22.20",
    "@babel/plugin-transform-runtime": "^7.22.20",
    "@babel/preset-react": "^7.22.15"

### Current and expected behavior

Getting TypeError: unknown file: _getAssignmentIdentifiers is not a function during react build time

### Environment

-Babel core 7.22.20

**Comment by liuxingbaoyu** [comment]
Will removing `node_modules` and re-running `npm install/yarn` help?

**Comment by mcguyvor** [comment]
@liuxingbaoyu not really
I try adding these in devdependency it it solve the issue
"@babel/core": "^7.22.20",
    "@babel/cli": "^7.22.20",
    "@babel/plugin-transform-runtime": "^7.22.20",
    "@babel/preset-react": "^7.22.15"

**Comment by nickgieschen** [comment]
Just started to get this error as well. The above didn't fix.

**Comment by nicolo-ribaudo** [comment]
Do you have a better stack trace? Could you try adding `console.log(_getAssignmentIdentifiers)` before the line that throws?

**Comment by Webbrother** [comment]
```
ERROR: _getAssignmentIdentifiers is not a function
STACK: TypeError: _getAssignmentIdentifiers is not a function
    at NodePath.getAssignmentIdentifiers (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/traverse/lib/path/family.js:280:10)
    at Scope.crawl (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/traverse/lib/scope/index.js:707:24)
    at Scope.init (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/traverse/lib/scope/index.js:675:12)
    at NodePath.setScope (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/traverse/lib/path/context.js:123:53)
    at NodePath.setContext (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/traverse/lib/path/context.js:135:8)
    at new File (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/core/lib/transformation/file/file.js:90:8)
    at normalizeFile (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/core/lib/transformation/normalize-file.js:98:10)
    at normalizeFile.next (<anonymous>)
    at run (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/core/lib/transformation/index.js:21:50)
    at run.next (<anonymous>)
    at transform (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at evaluateSync (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/gensync/index.js:251:28)
    at sync (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/gensync/index.js:89:14)
    at stopHiding - secret - don't use this - v1 (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
    at transformSync (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@babel/core/lib/transform.js:42:76)
    at ScriptTransformer._instrumentFile (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@jest/transform/build/ScriptTransformer.js:389:46)
    at ScriptTransformer._buildTransformResult (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@jest/transform/build/ScriptTransformer.js:491:33)
    at ScriptTransformer.transformSourceAsync (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@jest/transform/build/ScriptTransformer.js:608:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async generateEmptyCoverage (/Users/vega/projects/sber-track-fe/business/mfe-configuration/node_modules/@jest/reporters/build/generateEmptyCoverage.js:127:20)
```

**Comment by wjx25zj** [comment]
try to update "@babel/types" version

**Comment by tzimmermann** [comment]
I am also getting this error, using these versions:

```
    "@babel/core": "7.26.0",
    "@babel/eslint-parser": "7.25.9",
    "@babel/plugin-proposal-export-default-from": "7.25.9",
    "@babel/plugin-transform-modules-commonjs": "7.26.3",
    "@babel/plugin-transform-runtime": "7.25.9",
    "@babel/preset-env": "7.26.0",
    "@babel/preset-react": "7.26.3",
```

Different stack trace than above though:
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: _getAssignmentIdentifiers is not a function
    at NodePath.getAssignmentIdentifiers (/home/circleci/repo/node_modules/@babel/traverse/lib/path/family.js:280:10)
    at Scope.crawl (/home/circleci/repo/node_modules/@babel/traverse/lib/scope/index.js:663:24)
    at Scope.init (/home/circleci/repo/node_modules/@babel/traverse/lib/scope/index.js:625:12)
    at NodePath.setScope (/home/circleci/repo/node_modules/@babel/traverse/lib/path/context.js:126:53)
    at NodePath.setContext (/home/circleci/repo/node_modules/@babel/traverse/lib/path/context.js:138:12)
    at new File (/home/circleci/repo/node_modules/@babel/core/lib/transformation/file/file.js:90:8)
    at normalizeFile (/home/circleci/repo/node_modules/@babel/core/lib/transformation/normalize-file.js:98:10)
    at normalizeFile.next (<anonymous>)
    at run (/home/circleci/repo/node_modules/@babel/core/lib/transformation/index.js:22:50)
    at run.next (<anonymous>)
    at transform (/home/circleci/repo/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/home/circleci/repo/node_modules/gensync/index.js:261:32)
    at /home/circleci/repo/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/circleci/repo/node_modules/gensync/index.js:223:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 @ ./src/index.js 116:0-21

```

Deleting node_modules fixed it locally, but not on CircleCI (although I did purge the shared node_modules cache there as well). Is there any transitive babel-dependency missing that I should be adding?

**Comment by nicolo-ribaudo** [comment]
Wow @philipwhiuk that's surprising and... bad 😅

If you are on Yarn 1 I highly recommend trying to upgrade to Yarn 4 -- the 1->4 changes are are much easier to deal with than what 1->2 originally was.

If you are already on the latest Yarn version... please report a bug at https://github.com/yarnpkg/berry/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen :)
