### ISSUE TITLE
[Bug]: Cannot combine importAssertions and importAttributes plugins.

### ISSUE THREAD

**Issue by jwld** [babel/babel#16798]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Same issue as detailed in #16754. Also using a monorepo with react, next and jest.

Hoped it was fixed by #16781, so I installed the following at the monorepo root:
```
"@babel/plugin-syntax-import-assertions": "^7.25.6",
"@babel/plugin-syntax-import-attributes": "^7.25.6"
```

But I'm still seeing the same error:
```
Cannot combine importAssertions and importAttributes plugins.

      at validatePlugins (../../node_modules/@babel/parser/src/plugin-utils.ts:130:11)
      at validatePlugins (../../node_modules/@babel/parser/src/index.ts:106:5)
      at getParser (../../node_modules/@babel/parser/src/index.ts:32:22)
      at parser (../../node_modules/@babel/core/src/parser/index.ts:28:19)
          at parser.next (<anonymous>)
      at normalizeFile (../../node_modules/@babel/core/src/transformation/normalize-file.ts:50:24)
          at normalizeFile.next (<anonymous>)
      at run (../../node_modules/@babel/core/src/transformation/index.ts:39:36)
          at run.next (<anonymous>)
      at transform (../../node_modules/@babel/core/src/transform.ts:29:20)
          at transform.next (<anonymous>)
      at evaluateSync (../../node_modules/gensync/index.js:251:28)
      at sync (../../node_modules/gensync/index.js:89:14)
      at fn (../../node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:99:14)
      at transformSync (../../node_modules/@babel/core/src/transform.ts:66:52)
      at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:545:31)
      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:674:40)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:726:19)
```

Strange that this issue appeared without any files being changed - one day it was fine, the next not. Also seems random which team members have the issue, despite us all using the same node version.

### Configuration

Jest config file

```
const paths = require('./paths')

module.exports = {
  displayName: 'admin',
  modulePaths: paths,
  testPathIgnorePatterns: ['dump', 'node_modules'],
  transform: { '^.+\\.(js|jsx)$': ['babel-jest', { presets: ['next/babel'] }] }
}
```

### Current and expected behavior

No errors.

### Environment

  System:
    OS: macOS 14.6.1
  Binaries:
    Node: 22.7.0 - /opt/homebrew/bin/node
    Yarn: 4.4.1 - ~/projectpath/node_modules/.bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
  Monorepos:
    Yarn Workspaces: 4.4.1
  npmPackages:
    eslint: 8.57.0 => 8.57.0
    jest: ^29.7.0 => 29.7.0

### Possible solution

[People are suggesting](https://x.com/alexanderkondov/status/1826612490509418561) updating next to a canary version or rolling node back, but neither of these are viable solutions for us at the moment.

### Additional context

I was asked to submit my lock file also, but it's too long so linking it [here](https://jmp.sh/tPvzuOjB).

**Comment by nicolo-ribaudo** [comment]
Oh I see, you are using Next.js. Unfortunately Next.js bundles Babel packages, so the `next/babel` preset loads an old bundled version of the import assertions plugin, and not the one you installed.

One day we'll probably add some sort of anti-Next.js-bundling mode to let users update their dependencies, since their bundling approach is one of the most common causes of user problems with Babel. For now, you can remove `next/babel` from your Jest config and manually include the individual pieces: https://github.com/vercel/next.js/blob/canary/packages/next/src/build/babel/preset.ts

```js
['babel-jest', {
  sourceType: 'unambiguous',
  targets: { node: process.versions.node },
  presets: [
    '@babel/preset-env',
    // or runtime: 'classic', depending on which one you are using
    ['@babel/preset-react', { development: true, runtime: 'automatic' }]
  ]
}]
```
