### ISSUE TITLE
[Bug]: getting error while running npm run build : Cannot read properties of undefined (reading 'getCode')

### ISSUE THREAD

**Issue by nitinsharma-materialplus** [babel/babel#16961]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

npm run build

### Configuration file name

babel.config.js

### Configuration

node version : 16.20.2
npm : 8.19.4
running on : macOS 15.0.1  M2

package.json:-
{
  "name": "emulsify-wordpress-theme",
  "version": "1.0.0-alpha.5",
  "description": "Emulsify is a Design System that works with WordPress, Drupal, React, and more.",
  "author": "Dean Oest <randy@fourkitchens.com>",
  "license": "GPL-2.0-only",
  "dependencies": {
    "@babel/core": "^7.13.10",
    "@babel/preset-env": "^7.13.10",
    "@storybook/addon-a11y": "6.1.21",
    "@storybook/addon-actions": "6.1.21",
    "@storybook/addon-links": "6.1.21",
    "@storybook/addon-viewport": "^6.1.21",
    "@storybook/addons": "6.1.21",
    "@storybook/react": "6.1.21",
    "@storybook/storybook-deployer": "^2.8.7",
    "add-attributes-twig-extension": "^0.1.0",
    "autoprefixer": "^10.2.5",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.2.2",
    "babel-preset-minify": "^0.5.0",
    "bem-twig-extension": "^0.1.1",
    "breakpoint-sass": "^2.7.1",
    "clean-webpack-plugin": "^3.0.0",
    "concurrently": "^6.0.0",
    "css-loader": "^5.1.3",
    "eslint": "^7.22.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.22.0",
    "file-loader": "^6.2.0",
    "fs": "^0.0.1-security",
    "glob": "^7.1.4",
    "imagemin-webpack-plugin": "^2.4.2",
    "js-yaml-loader": "^1.2.2",
    "mini-css-extract-plugin": "^1.3.9",
    "node-sass": "^9.0.0",
    "node-sass-glob-importer": "^5.3.2",
    "normalize.css": "^8.0.1",
    "postcss": "^8.2.8",
    "postcss-custom-properties": "^10.0.0",
    "postcss-loader": "^4.1.0",
    "ramda": "^0.27.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "sass-loader": "^10.1.0",
    "style-loader": "^2.0.0",
    "stylelint": "^13.12.0",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^21.0.0",
    "stylelint-webpack-plugin": "^2.1.1",
    "svg-sprite-loader": "^6.0.0",
    "twig": "~1.15.4",
    "twig-loader": "https://github.com/AmazeeLabs/twig-loader",
    "webpack": "4.44.2",
    "webpack-cli": "^4.5.0",
    "webpack-merge": "^5.7.3"
  },
  "scripts": {
    "a11y": "npm run build-storybook && ./scripts/a11y.js -r",
    "setup": "composer install && yarn",
    "lint": "eslint ./components",
    "storybook": "start-storybook --ci -s ./dist,./images -p 6006",
    "build-storybook": "npm run build && build-storybook -s ./dist,./images -o .out",
    "deploy-storybook": "storybook-to-ghpages -o .out",
    "webpack": "webpack --watch --config ./webpack/webpack.dev.js",
    "build": "webpack --config ./webpack/webpack.prod.js",
    "develop": "concurrently --raw \"npm run webpack\" \"npm run storybook\""
  },
  "devDependencies": {
    "core-js": "3.9.1",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "open-cli": "^6.0.1",
    "pa11y": "^5.3.0",
    "prettier": "2.2.1"
  }
}

### Current and expected behavior

facing below shown error for all the js files

ERROR in ./webpack/svgSprite.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/webpack/svgSprite.js: Cannot read properties of undefined (reading 'getCode')
    at NodePath.getSource (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/traverse/lib/path/introspection.js:137:27)
    at PluginPass.Program (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/babel-plugin-minify-simplify/lib/index.js:490:41)
    at newFn (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/traverse/lib/visitors.js:172:14)
    at NodePath._call (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/traverse/lib/path/context.js:49:20)
    at NodePath.call (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/traverse/lib/path/context.js:39:18)
    at NodePath.visit (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/traverse/lib/path/context.js:88:31)
    at TraversalContext.visitQueue (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/traverse/lib/context.js:90:16)
    at TraversalContext.visitSingle (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/traverse/lib/context.js:66:19)
    at TraversalContext.visit (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/traverse/lib/context.js:113:19)
    at traverseNode (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/traverse/lib/index.js:53:34)
    at transformFile (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/core/lib/transformation/index.js:80:31)
    at transformFile.next (<anonymous>)
    at run (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/core/lib/transformation/index.js:25:12)
    at run.next (<anonymous>)
    at transform (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/gensync/index.js:261:32)
    at /Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/nitin.sharma/Projects/Material-website/wp-content/themes/materialplus/node_modules/gensync/index.js:223:11)
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--4-1!node_modules/postcss-loader/dist/cjs.js??ref--4-2!node_modules/sass-loader

Expected behaviour:
The npm run build command should complete without any error(s).

### Environment

node version : 16.20.2
npm : 8.19.4
running on : macOS 15.0.1  M2

package.json:-
{
  "name": "emulsify-wordpress-theme",
  "version": "1.0.0-alpha.5",
  "description": "Emulsify is a Design System that works with WordPress, Drupal, React, and more.",
  "author": "Dean Oest <randy@fourkitchens.com>",
  "license": "GPL-2.0-only",
  "dependencies": {
    "@babel/core": "^7.13.10",
    "@babel/preset-env": "^7.13.10",
    "@storybook/addon-a11y": "6.1.21",
    "@storybook/addon-actions": "6.1.21",
    "@storybook/addon-links": "6.1.21",
    "@storybook/addon-viewport": "^6.1.21",
    "@storybook/addons": "6.1.21",
    "@storybook/react": "6.1.21",
    "@storybook/storybook-deployer": "^2.8.7",
    "add-attributes-twig-extension": "^0.1.0",
    "autoprefixer": "^10.2.5",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.2.2",
    "babel-preset-minify": "^0.5.0",
    "bem-twig-extension": "^0.1.1",
    "breakpoint-sass": "^2.7.1",
    "clean-webpack-plugin": "^3.0.0",
    "concurrently": "^6.0.0",
    "css-loader": "^5.1.3",
    "eslint": "^7.22.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.22.0",
    "file-loader": "^6.2.0",
    "fs": "^0.0.1-security",
    "glob": "^7.1.4",
    "imagemin-webpack-plugin": "^2.4.2",
    "js-yaml-loader": "^1.2.2",
    "mini-css-extract-plugin": "^1.3.9",
    "node-sass": "^9.0.0",
    "node-sass-glob-importer": "^5.3.2",
    "normalize.css": "^8.0.1",
    "postcss": "^8.2.8",
    "postcss-custom-properties": "^10.0.0",
    "postcss-loader": "^4.1.0",
    "ramda": "^0.27.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "sass-loader": "^10.1.0",
    "style-loader": "^2.0.0",
    "stylelint": "^13.12.0",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^21.0.0",
    "stylelint-webpack-plugin": "^2.1.1",
    "svg-sprite-loader": "^6.0.0",
    "twig": "~1.15.4",
    "twig-loader": "https://github.com/AmazeeLabs/twig-loader",
    "webpack": "4.44.2",
    "webpack-cli": "^4.5.0",
    "webpack-merge": "^5.7.3"
  },
  "scripts": {
    "a11y": "npm run build-storybook && ./scripts/a11y.js -r",
    "setup": "composer install && yarn",
    "lint": "eslint ./components",
    "storybook": "start-storybook --ci -s ./dist,./images -p 6006",
    "build-storybook": "npm run build && build-storybook -s ./dist,./images -o .out",
    "deploy-storybook": "storybook-to-ghpages -o .out",
    "webpack": "webpack --watch --config ./webpack/webpack.dev.js",
    "build": "webpack --config ./webpack/webpack.prod.js",
    "develop": "concurrently --raw \"npm run webpack\" \"npm run storybook\""
  },
  "devDependencies": {
    "core-js": "3.9.1",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "open-cli": "^6.0.1",
    "pa11y": "^5.3.0",
    "prettier": "2.2.1"
  }
}

**Comment by liuxingbaoyu** [comment]
Please try removing babel-plugin-minify-simplify from your config, it is currently unmaintained.

**Comment by nitinsharma-materialplus** [comment]
I don't see "babel-plugin-minify-simplify" in the package.json. Should I just do "npm uninstall babel-plugin-minify-simplify"?

Here's how my babel.config.js looks like:-
module.exports = (api) => {
  api.cache(true);

  const presets = [
    '@babel/preset-react',
    [
      '@babel/preset-env',
      {
        corejs: '3',
        useBuiltIns: 'usage',
      },
    ],
    'minify',
  ];

  const comments = false;

  return { presets, comments };
};

**Comment by liuxingbaoyu** [comment]
It may be caused by the `minify` plugin, maybe you need to remove it and use another compressor instead.
