### ISSUE TITLE
Issue parsing `!yield`

### ISSUE THREAD

**Issue by julien-f** [babel/babel#1699]
```javascript
// Compiles correctly.
function *foo () {
  return yield
}
function *bar () {
  return !(yield)
}

// Does not compile.
function *baz () {
  return !yield
}
```

Error:

```
node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:597
      throw err;
            ^
SyntaxError: plop.js: Unexpected token (10:10)
   8 | // Does not compile.
   9 | function *baz () {
> 10 |   return !yield
     |           ^
  11 | }
  12 | 
    at Parser.pp.raise (node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.unexpected (node_modules/babel/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseExprAtom (node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:278:34)
    at Parser.parseExprAtom (node_modules/babel/node_modules/babel-core/node_modules/acorn-jsx/inject.js:624:24)
    at Parser.pp.parseExprSubscripts (node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
    at Parser.pp.parseMaybeUnary (node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:199:19)
    at Parser.pp.parseMaybeUnary (node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:193:26)
    at Parser.pp.parseExprOps (node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:155:19)
    at Parser.pp.parseMaybeConditional (node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:138:19)
    at Parser.pp.parseMaybeAssign (node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:106:19)
```

**Comment by sebmck** [comment]
Expected behaviour. The behaviour of yield parsing isn't so intuitive, see marijnh/acorn#219 for related discussion.

**Comment by julien-f** [comment]
Indeed that's weird :/

Thank you anyway :)
