### ISSUE TITLE
`metadataUsedHelpers` deprecate check is too early

### ISSUE THREAD

**Issue by haruair** [babel/babel#1704]
In `File` class, deprecate check is [too early](https://github.com/babel/babel/blob/master/src/babel/transformation/file/index.js#L133) so that Logger can't use `this.file.opts.suppressDeprecationMessages` at [that moment](https://github.com/babel/babel/blob/master/src/babel/transformation/file/logger.js#L28). When you turn on the option `metadataUsedHelpers`, you can reproduce the error.

    err  TypeError: Cannot read property 'suppressDeprecationMessages' of undefined
             at Logger.deprecate (helloworld/jspm_packages/npm/babel-core@5.5.4/browser.js:8889:24)
             at File.normalizeOptions (helloworld/jspm_packages/npm/babel-core@5.5.4/browser.js:8271:18)
             at new File (helloworld/jspm_packages/npm/babel-core@5.5.4/browser.js:8237:22)
             at TransformerPipeline.transform (helloworld/jspm_packages/npm/babel-core@5.5.4/browser.js:12107:16)
             at /usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/compilers/esm.js:143:31
             at runMicrotasksCallback (node.js:337:7)
             at process._tickCallback (node.js:355:11)

**Comment by sebmck** [comment]
[Nope](https://github.com/babel/babel/blob/master/src/babel/transformation/file/index.js#L104). I just haven't gotten around to pushing a new version yet.

**Comment by haruair** [comment]
@sebmck Oh, I got it. I miss that. I'm sorry :smile:

**Comment by sebmck** [comment]
All good :smile: Just released 5.5.5, let me know if that does the trick, thanks!

**Comment by haruair** [comment]
@sebmck It is working perfectly now. Thank you so much!
