### ISSUE TITLE
Fails to parse Flow-annotated polymorphic methods named "delete"

### ISSUE THREAD

**Issue by AgentME** [babel/babel#1737]
I started using Flow recently, and was delighted to see that Babel (which I was already using) supported stripping Flow types by default already! I just found a funny issue though:

```
/* @flow */

class Foo {
  delete<T>(item: T): T {
    return item;
  }
}

var foo = new Foo();
console.log( foo.delete('aaa') );
```

```
[chris ~/Coding/flow-test]$ flow check

Found 0 errors
[chris ~/Coding/flow-test]$ babel-node foo.js 

SyntaxError: /Users/chris/Coding/flow-test/foo.js: Unexpected token (4:8)
  2 | 
  3 | class Foo {
> 4 |   delete<T>(item: T): T {
    |         ^
  5 |     return item;
  6 |   }
  7 | }
    at Parser.pp.raise (/usr/local/lib/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.expect (/usr/local/lib/node_modules/babel-core/lib/acorn/src/parseutil.js:81:26)
    at Parser.pp.parseMethod (/usr/local/lib/node_modules/babel-core/lib/acorn/src/expression.js:664:8)
    at Parser.parseClassMethod (/usr/local/lib/node_modules/babel-core/lib/acorn/plugins/flow.js:742:27)
    at Parser.pp.parseClass (/usr/local/lib/node_modules/babel-core/lib/acorn/src/statement.js:528:10)
    at Parser.pp.parseStatement (/usr/local/lib/node_modules/babel-core/lib/acorn/src/statement.js:72:19)
    at Parser.parseStatement (/usr/local/lib/node_modules/babel-core/lib/acorn/plugins/flow.js:639:22)
    at Parser.pp.parseTopLevel (/usr/local/lib/node_modules/babel-core/lib/acorn/src/statement.js:22:21)
    at Object.parse (/usr/local/lib/node_modules/babel-core/lib/acorn/src/index.js:106:12)
[chris ~/Coding/flow-test]$ flow --version
Flow, a static type checker for JavaScript, version 0.12.0
[chris ~/Coding/flow-test]$ babel-node --version
5.5.6
```

Renaming the "delete" method to anything else causes babel to work fine with it.

**Comment by sebmck** [comment]
It's being parsed as a JSX tag for some reason.

**Comment by sebmck** [comment]
Figured it out `exprAllowed` is being set to true on `delete` tokens so the `<` is being interpreted as the start of a JSX starting tag expression.
