### ISSUE TITLE
Super calls in ES5 subclasses should fail

### ISSUE THREAD

**Issue by joliss** [babel/babel#1738]
The following snippet works in Babel, but fails in V8:

```js
'use strict'

class A {
  constructor() {
    console.log('A::constructor', this)
  }
}

B.prototype = Object.create(A.prototype)
B.prototype.constructor = B
function B() {
  A.call(this)
}

new B
```

With Babel 5.5.6, it prints

```
A::constructor {}
```

but with Node 2.2.1, it prints

```
/home/ubuntu/tmp/test.js:4
    constructor() {
               ^
TypeError: Class constructors cannot be invoked without 'new'
    at B.A (/home/ubuntu/tmp/test.js:4:16)
    at new B (/home/ubuntu/tmp/test.js:12:7)
    at Object.<anonymous> (/home/ubuntu/tmp/test.js:15:3)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:117:18)
    at node.js:946:3
```

At first glance, the V8 behavior seems to be correct here. I'm not sure if it's really worth trying to catch this in Babel, but figured I'd report it so you can decide.

**Comment by sebmck** [comment]
The error is because you're calling a class as a function. The current `_classCallCheck` is just about as much as you can do to get that with ES5 semantics:

```javascript
function _classCallCheck(instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");
  }
}

var Foo = function Foo() {
  _classCallCheck(this, Foo);
};
```

I wish there was more that could be done but unfortunately it's impossible to get it any better :cry:
