### ISSUE TITLE
Error when function name and parameter name are the same

### ISSUE THREAD

**Issue by asakusuma** [babel/babel#1763]
When and only when you pass in `ignore` for the `modules` option, throws an error when transforming if there exists a function with an argument with the same name as the function.

```JavaScript
let obj = {
  foo(foo) {}
};
```

Condensed the reproducible error into this little repo: https://github.com/asakusuma/babel-bug

```
/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/transformation/file/index.js:628
      throw err;
            ^
TypeError: unknown: Cannot read property 'foo' of undefined
    at Scope._renameFromMap (/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/traversal/scope/index.js:423:12)
    at Scope.rename (/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/traversal/scope/index.js:417:12)
    at wrap (/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/transformation/helpers/name-method.js:54:13)
    at NodePath.bare (/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/transformation/helpers/name-method.js:173:10)
    at NodePath.call (/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/traversal/path/context.js:122:26)
    at NodePath.visit (/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/traversal/path/context.js:164:12)
    at TraversalContext.visitSingle (/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/traversal/context.js:105:12)
    at TraversalContext.visit (/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/traversal/context.js:117:19)
    at Function.traverse.node (/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/traversal/index.js:67:17)
    at NodePath.visit (/Users/akusuma/workspace/opensource/babel-bug/node_modules/babel-core/lib/babel/traversal/path/context.js:163:26)
```

**Comment by sebmck** [comment]
I can't reproduce this on the site [REPL](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=true&code=let%20obj%20%3D%20%7B%0A%20%20foo(foo)%20%7B%7D%0A%7D%3B&playground=false). Are you sure you're on the latest?

**Comment by asakusuma** [comment]
Yes. If you use the REPL, you'll notice it renames the parameter `foo` to `_foo`.

Also, this only happens when modules = ignore. Is that how the REPL is setup?

**Comment by sebmck** [comment]
Nevermind, I missed when you said it only happens when `modules` is set to `ignore`.

**Comment by asakusuma** [comment]
Did some digging and found a parameter that, anecdotally, seems to be `undefined` when `modules = ignore`, but is otherwise `{}`. I just made the default value `{}` and it seems to have fixed things.

Fixed in this PR: https://github.com/babel/babel/pull/1771
