### ISSUE TITLE
Can't replace callExpression with a string literal

### ISSUE THREAD

**Issue by DmitrySoshnikov** [babel/babel#1764]
This is another regression we noticed at switching `v5.5.8`.

With a child visitor, we'd like to replace nested calls with strings:

```javascript
foo(bar('x'));
```

To:

```javascript
foo('{x}');
```

With a (simplified here) transform:

```javascript
module.exports = new Transformer('foo', {
  CallExpression: function(node, parent, scope) {
    scope.traverse(node, childCallVisitor, {});
  }
});

var childCallVisitor = {
  CallExpression: {
    enter: function(node) {
      return t.literal('{' + node['arguments'][0].value + '}');
    }
  }
};
```

The stack-trace:

```
TypeError: /Users/dmitrys/test.js: Cannot set property '0' of null
    at NodePath.replaceWith (.../babel/node_modules/babel-core/lib/babel/traversal/path/replacement.js:170:40)
    at NodePath.call (.../babel/node_modules/babel-core/lib/babel/traversal/path/context.js:125:12)
    at NodePath.visit (.../babel/node_modules/babel-core/lib/babel/traversal/path/context.js:146:8)
    at TraversalContext.visitMultiple (.../babel/node_modules/babel-core/lib/babel/traversal/context.js:85:16)
    at TraversalContext.visit (.../babel/node_modules/babel-core/lib/babel/traversal/context.js:115:19)
    at Function.traverse.node (.../babel/node_modules/babel-core/lib/babel/traversal/index.js:67:17)
    at traverse (.../babel/node_modules/babel-core/lib/babel/traversal/index.js:50:14)
    at Scope.traverse (.../babel/node_modules/babel-core/lib/babel/traversal/scope/index.js:219:28)
    at NodePath.module.exports.Transformer.CallExpression (...fb-transforms/babel-plugin-fbt/index.js:12:11)
    at NodePath.call (.../babel/node_modules/babel-core/lib/babel/traversal/path/context.js:122:26)
```

If we have more complex expression, it works:

```javascript
foo(bar('x') + ' y');
```

Normally transforms to:

```javascript
foo('{x}' + 'y');
```

**Comment by sebmck** [comment]
The main visitor is traversing into the `bar` call (after transforming `foo` and replacing `bar('x')`) and then trying to replace it again but it's been removed.

**Comment by sebmck** [comment]
It's the use of `scope.traverse` that's throwing it off. The path instances were changed to be stored on their parent rather than their container so it's attempting to traverse into a removed child. There are two different node paths for `bar` being stored/used. One that's being stored on `foo` and another on `Program`. The second path on `Program` is being stored because that's the `parent` that `scope.traverse` is providing and it's (rightfully) assuming that it's a direct child.

Using `this.traverse` fixes it:

```javascript
module.exports = new Transformer('foo', {
  CallExpression: function(node, parent, scope) {
    this.traverse(childCallVisitor, {});
  }
});

var childCallVisitor = {
  CallExpression: {
    enter: function(node) {
      return t.literal('{' + node['arguments'][0].value + '}');
    }
  }
};
```

**Comment by DmitrySoshnikov** [comment]
@sebmck, OK, thanks for clarification, and seems it's fixed. Yeah, there are several traversing mechanism used through the code base (`scope.traverse`, `path.traverse`). It'd be great to have a small doc with examples which type of traversing is to use better in a specific use case.

**Comment by sebmck** [comment]
@DmitrySoshnikov Yeah, I've been in the process of removing a lot of duplicated methods as I've been writing plugin API docs (with deprecation messages). Using `path.traverse` is basically the only reliable way to "subtraverse" a node as otherwise internal path state gets messed.

**Comment by DmitrySoshnikov** [comment]
OK, sounds great, thanks again!
