### ISSUE TITLE
`babel-core/browser.js` doesn't work with Browersify

### ISSUE THREAD

**Issue by Minwe** [babel/babel#1780]
I want to use `babel-core/browser.js` to transform code in browser, I write code like below, then bundle with browserify, but it not works.

```js
'use strict';

var babel = require('babel-core/browser');

// do something with babel browser

```

Error message:

```
Error: Cannot find module './plugins/flow' from '/Users/my/Dev/AmazeUI/amazeui-react/node_modules/babel-core'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:42:25
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:43)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:66:22
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:21:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

also:

```
Error: Cannot find module 'readable-stream/transform.js' 
Error: Cannot find module 'readable-stream/passthrough.js' 
...
```

**Comment by sebmck** [comment]
It's not meant to. Use `require("babel-core");`.
