### ISSUE TITLE
ANSI color codes in cmd console (windows)

### ISSUE THREAD

**Issue by laggingreflex** [babel/babel#1784]
Related to [this issue][837] I'm getting similar output on error in my windows cmd.exe console

    SyntaxError: index.js: Unexpected token (6:17)
      4 | ←[36mvar←[39m fs ←[1m=←[22m require←[94m←[1m(←[22m←[39m←[31m'fs'←[39m←[94m←[1m)←[22m←[39m←[1m;←[22m
      5 |
    > 6 | ←[36mvar←[39m text ←[1m=←[22m await fs←[1m.←[22mreadFile←[94m←[1m(←[22m←[39m←[31m'./index.js'←[39m←[94m←[1m)←[22m←[39m←[1m;←[22m
        |                  ^
      7 | console←[1m.←[22mlog←[94m←[1m(←[22m←[39mtext←[94m←[1m)←[22m←[39m←[1m;←[22m
      8 |
      9 |
        at Parser.pp.raise (C:\…\node_modules\babel\node_modules\babel-core\lib\acorn\src\location.js:73:13)
        at Parser.pp.unexpected (C:\…\node_modules\babel\node_modules\babel-core\lib\acorn\src\parseutil.js:87:8)
        at Parser.pp.semicolon (C:\…\node_modules\babel\node_modules\babel-core\lib\acorn\src\parseutil.js:66:73)
        at Parser.pp.parseVarStatement (C:\…\node_modules\babel\node_modules\babel-core\lib\acorn\src\statement.js:330:8)
        at Parser.pp.parseStatement (C:\…\node_modules\babel\node_modules\babel-core\lib\acorn\src\statement.js:87:19)
        at Parser.parseStatement (C:\…\node_modules\babel\node_modules\babel-core\lib\acorn\plugins\flow.js:639:22)
        at Parser.pp.parseTopLevel (C:\…\node_modules\babel\node_modules\babel-core\lib\acorn\src\statement.js:22:21)
        at Object.parse (C:\…\node_modules\babel\node_modules\babel-core\lib\acorn\src\index.js:106:12)
        at exports.default (C:\…\node_modules\babel\node_modules\babel-core\lib\babel\helpers\parse.js:66:19)
        at File.parse (C:\…\node_modules\babel\node_modules\babel-core\lib\babel\transformation\file\index.js:555:46)

Using latest babel@5.5.8 

Also, `--color=never` argument does nothing; the above output is the same using or without using it.  

[837]: https://github.com/babel/babel/issues/837

**Comment by sebmck** [comment]
```sh
$ babel --no-highlight-errors script.js
```

**Comment by laggingreflex** [comment]
error: unknown option `--no-highlight-errors'

**Comment by sebmck** [comment]
Oh right it's `--no-highlight-code`.
