### ISSUE TITLE
"SyntaxError: Unexpected token *" when used with bluebirdCoroutines transformer

### ISSUE THREAD

**Issue by yaru22** [babel/babel#1801]
`.babelrc`:
```
{
  "optional": [
    "bluebirdCoroutines",
    "es7.asyncFunctions"
  ]
}
```

`test.js`:
```js
import Promise from 'bluebird';

function bar() {
  return Promise.resolve(3);
}

async function foo() {
  let g = await bar();
  console.log(g);
}

foo();
```

When I run `test.js` with `babel-node`, I get the following error:
```
var foo = _bluebird.coroutine(function* () {
                                      ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:160:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/bin/_babel-node:112:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

What am I doing wrong here? If it's a bug, what is the workaround?

Thanks!

**Comment by sebmck** [comment]
You're using `bluebirdCoroutines` which compiles async functions to generators and the environment you're running it in doesn't support generators. Remove the `bluebirdCoroutines` transformer.

Also, in the future, please see the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">slack channel</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks!
