### ISSUE TITLE
Don't hotlink internal Babel files.

### ISSUE THREAD

**Issue by nackjicholson** [babel/babel#1840]
I'm running a gulp build based very much on this: https://github.com/babel/babel-library-boilerplate

And now running my gulp commands I get...

```
/Users/nackjicholson/repos/jobs-service/node_modules/isparta/node_modules/babel-core/lib/babel/tools/protect.js:15
    throw new Error("Don't hotlink internal Babel files.");
          ^
Error: Don't hotlink internal Babel files.
    at Object.exports.default (/Users/nackjicholson/repos/jobs-service/node_modules/isparta/node_modules/babel-core/lib/babel/tools/protect.js:15:11)
    at Object.<anonymous> (/Users/nackjicholson/repos/jobs-service/node_modules/isparta/node_modules/babel-core/lib/babel/api/node.js:42:28)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/nackjicholson/repos/jobs-service/node_modules/isparta/lib/instrumenter.js:25:23)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/nackjicholson/repos/jobs-service/node_modules/isparta/lib/isparta.js:19:21)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/nackjicholson/repos/jobs-service/gulp/test.js:4:15)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at requireDir (/Users/nackjicholson/repos/jobs-service/node_modules/require-dir/index.js:116:33)
    at Object.<anonymous> (/Users/nackjicholson/repos/jobs-service/gulpfile.js:2:23)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/Users/nackjicholson/.nvm/versions/io.js/v2.2.1/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/nackjicholson/.nvm/versions/io.js/v2.2.1/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/Users/nackjicholson/.nvm/versions/io.js/v2.2.1/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/nackjicholson/.nvm/versions/io.js/v2.2.1/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /Users/nackjicholson/.nvm/versions/io.js/v2.2.1/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
    at /Users/nackjicholson/.nvm/versions/io.js/v2.2.1/lib/node_modules/gulp/node_modules/v8flags/index.js:79:12
    at /Users/nackjicholson/.nvm/versions/io.js/v2.2.1/lib/node_modules/gulp/node_modules/v8flags/index.js:35:7
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:117:18)
    at node.js:946:3
```

Was working earlier today. And I see that in the last half hour there have been commits related to babel protect.

Thanks for any help.

**Comment by sebmck** [comment]
See #1839. Reinstall and update.
