### ISSUE TITLE
Problem reading json file

### ISSUE THREAD

**Issue by lfilho** [babel/babel#1864]
This is the same error described [here](https://github.com/babel/babelify/issues/71) but since I'm using Babel alone (not babelify), I'm posting it here.

I have the following json on disk:

```
{
    "repo1": "myChannel1",
    "repo2": "myChannel2",
    "docflow": "myChannel1"
}
```

When I try to read it, this is the error given:
`[SyntaxError: /Users/path/to/file: Unexpected token (2:11)]`

Tested under Babel ^5.4.2 and 5.6.14

This happend while running test using mocha: `mocha test --recursive --compilers js:babel/register`

Any clues?

**Comment by sebmck** [comment]
What's the entire stack trace and what's the filename of the JSON file?

**Comment by sebmck** [comment]
Also FWIW, `babel/register` does not touch `.json` files.

**Comment by lfilho** [comment]
Thanks for quick reply.

The filename is `repoChannelMapping.json.example`.

Here it goes:

``` 
{ [SyntaxError: /Users/.../repoChannelMapping.json.example: Unexpected token (2:11)]
  pos: 13,
  loc: { line: 2, column: 11 },
  raisedAt: 14,
  _babel: true,
  codeFrame: '  1 | \u001b[32m{\u001b[39m\n> 2 |     \u001b[31m"repo1"\u001b[39m\u001b[1m:\u001b[22m \u001b[31m"myChannel1"\u001b[39m\u001b[1m,\u001b[22m\n    |            ^\n  3 |     \u001b[31m"repo2"\u001b[39m\u001b[1m:\u001b[22m \u001b[31m"myChannel2"\u001b[39m\u001b[1m,\u001b[22m\n  4 |     \u001b[31m"docflow"\u001b[39m\u001b[1m:\u001b[22m \u001b[31m"myChannel1"\u001b[39m\n  5 | \u001b[32m}\u001b[39m' }
```

**Comment by sebmck** [comment]
So it doesn't have the `.json` file extension?

**Comment by lfilho** [comment]
No it does not. It's an example file for private data. So I'm running the unit tests against the .example suffix file...

I'm using `require(file)` for reading + parsing the json file. You think that might be the issue?

**Comment by sebmck** [comment]
It is. You need to have the `.json` file extension at the end or else it's being loaded as JavaScript. There's no way for it to infer that it's JSON.

**Comment by lfilho** [comment]
Oh shoot. Should have seen that coming. Thanks for you great software and great support!!

**Comment by tjwebb** [comment]
I have the same problem, except my file does have a `.json` extension.

```
SyntaxError: /home/tjwebb/workspace/sails-auth/config/locales/en.json: Unexpected token (2:35)
  1 | {
> 2 |   "Error.Passport.Password.Invalid": "Invalid passport",
    |                                    ^
  3 |   "Error.Passport.Password.Wrong": "Incorrect password",
  4 |   "Error.Passport.Password.NotSet": "Password not set",
  5 |   "Error.Passport.Username.NotFound": "Username not found",
    at Parser.pp.raise (/home/tjwebb/workspace/sails-auth/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/home/tjwebb/workspace/sails-auth/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.semicolon (/home/tjwebb/workspace/sails-auth/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:69:81)
    at Parser.pp.parseExpressionStatement (/home/tjwebb/workspace/sails-auth/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:427:8)
    at Parser.parseExpressionStatement (/home/tjwebb/workspace/sails-auth/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:642:20)
    at Parser.pp.parseStatement (/home/tjwebb/workspace/sails-auth/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:142:21)
    at Parser.parseStatement (/home/tjwebb/workspace/sails-auth/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:621:22)
    at Parser.pp.parseBlock (/home/tjwebb/workspace/sails-auth/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseStatement (/home/tjwebb/workspace/sails-auth/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:105:19)
    at Parser.parseStatement (/home/tjwebb/workspace/sails-auth/node_modules/gulp-babel/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:621:22)
```

**Comment by jmm** [comment]
Hi @tjwebb. I suggest that you ask about that on stackoverflow or the `babel` slack, or perhaps on the [`gulp-babel`](https://github.com/babel/gulp-babel) issue tracker. Apparently the JSON file is being fed to `babel`, which shouldn't happen.
