### ISSUE TITLE
Require hook fails for packages installed with -g

### ISSUE THREAD

**Issue by shyiko** [babel/babel#1889]
Say you have a CLI package which is intended to be `npm -g install`ed. Unless `require("babel/register")({ignore: false})` or `require("babel/register")({only: [regexp_matching_source_directory]})` is called, hook will not work (because of [src/babel/api/register/node.js:shouldIgnore](https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L91)) (global modules stored in my case in `~/.nvm/v0.10.26/lib/node_modules/...`). One way to fix this would be to add an option (e.g. `cwd`) which users could fix to (let's say) __dirname (default value is process.cwd()). There is probably a better way but... well, I though you should know.

**Comment by resistdesign** [comment]
@sebmck Is it possible to have a mode that ignores a file if it fails compilation and lets the native functionality handle it?

**Comment by sebmck** [comment]
@resistdesign Not sure what benefit that would be?

**Comment by resistdesign** [comment]
Compiling everything you can and nothing you can't so that you don't need some crazy regex to use npm packages that may or may not be ES6/7/etc.

**Comment by sebmck** [comment]
Babel can compile anything the native environment can though?

**Comment by resistdesign** [comment]
It's failing to compile prompt for me

**Comment by sebmck** [comment]
I don't know what that means, can you elaborate?

**Comment by resistdesign** [comment]
So if I set `ignore: false` it tries to compile everything right, so packages in my `node_modules` folder are being compiled, and I get an error when it tries to compile the `prompt` package:
```
TypeError: Cannot set property inflect of [object Object] which has only a getter
    at Object.get (/Users/ryan.graff/wrk/rev/node_modules/prompt/node_modules/utile/lib/index.js:41:27)
    at Object.<anonymous> (/Users/ryan.graff/wrk/rev/node_modules/prompt/node_modules/utile/lib/index.js:281:25)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/ryan.graff/wrk/rev/node_modules/babel-core/lib/babel/api/register/node.js:166:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ryan.graff/wrk/rev/node_modules/babel-core/lib/babel/api/register/node.js:179:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ryan.graff/wrk/rev/node_modules/prompt/lib/prompt.js:10:13)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/ryan.graff/wrk/rev/node_modules/babel-core/lib/babel/api/register/node.js:166:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ryan.graff/wrk/rev/node_modules/babel-core/lib/babel/api/register/node.js:179:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ryan.graff/wrk/rev/lib/commands/init/index.js:5:36)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/ryan.graff/wrk/rev/node_modules/babel-core/lib/babel/api/register/node.js:166:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ryan.graff/wrk/rev/node_modules/babel-core/lib/babel/api/register/node.js:179:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at getCommandClass (/Users/ryan.graff/wrk/rev/lib/command-router.js:50:20)
    at runNextCommand (/Users/ryan.graff/wrk/rev/lib/command-router.js:63:20)
    at Object.<anonymous> (/Users/ryan.graff/wrk/rev/lib/command-router.js:85:1)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/ryan.graff/wrk/rev/node_modules/babel-core/lib/babel/api/register/node.js:166:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ryan.graff/wrk/rev/node_modules/babel-core/lib/babel/api/register/node.js:179:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ryan.graff/wrk/rev/index.js:28:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by sebmck** [comment]
It'd be because of strict mode. You shouldn't be passing in arbitrary code to Babel. Is there a reason you can't just use the `only` option?

```javascript
require("babel/register")({
  only: ["your_folder_name_or_whatever"]
});
```

**Comment by resistdesign** [comment]
I want to modularize my commands and keep them in other packages, and also, I want to compile code in the CWD where the CLI is run as well, so that get complicated right? Or am I missing something?

**Comment by resistdesign** [comment]
And don't get me wrong, I totally understand the challenges involved here :)

**Comment by resistdesign** [comment]
@sebmck It might be nice to be able to `require('ES5_thingy`);` and `import ES6Thingy from `es6_thingy;` to differentiate, is something like that possible?

**Comment by resistdesign** [comment]
@sebmck Sorry if these requests seem crazy, I'm just trying to formulate a nice clean, easy way to add this kind of flexibility :)

**Comment by benjamingr** [comment]
> @sebmck It might be nice to be able to require('ES5_thingy'); and import ES6Thingy from 'es6_thingy'; to differentiate, is something like that possible?

This was discussed at length and rejected at io.js as it would really confuse people.

**Comment by geddski** [comment]
I ran into this issue as well, and used the `only` config workaround.

**Comment by resistdesign** [comment]
Using the `only` config option proves very difficult to manage in large projects when you are trying to use Babel in a custom CLI tool that doesn't require project level configuration for each of all of your hundreds of packages. Open sourcing that CLI tools makes the `only` option make even less sense because you can't use some sort of a hardcoded project name prefix like `myco-`. I have considered several possible fixes, but I think the best one might be to just be able to add some sort of comment to an incompatible ES5 import such as `// @no-babel` or something to that effect.

**Comment by sebmck** [comment]
@resistdesign Just precompile your code, it saves a lot of hassle and improves performance. The [docs](https://babeljs.io/docs/usage/cli/#babel-node) discourage production use.

**Comment by resistdesign** [comment]
The overhead isn't a problem and I need the runtime processing for target packages. Also, how would precompiling avoid compiling incompatible ES5 packages?

**Comment by resistdesign** [comment]
I'm sorry, I think I have something confused because I'm trying to solve this issue for 2 scenarios:
1. I'm using the webpack loader in the CLI to process the target package. (This is where the prefix is an issue but that's a different issue)
2. I'm using Babel require hook in the CLI itself and to run target package tests. (It think `only` solves my problem for that)

**Comment by resistdesign** [comment]
I think you can mark this closed.

**Comment by shyiko** [comment]
@resistdesign the problem is inconsistent (read "unexpected") behavior when module using "babel/register" is **globally** installed (obviously it works fine when installed without -g). I see no reason to close this ticket.

**Comment by resistdesign** [comment]
I'm sorry, I was remembering this as my ticket and it's not! And now I know why I couldn't close it! Sorry, I have programming brain right now :P

**Comment by thejameskyle** [comment]
I'm assuming all that needs to be changed is [`process.cwd()` to `__dirname`](https://github.com/babel/babel/blob/master/packages/babel/src/api/register/node.js#L56) for global installs to work?

**Comment by KyleAMathews** [comment]
This is unexpected. Didn't realize this was happening until got a bug report.

**Comment by bnolan** [comment]
Is this a bug in `src/babel/api/register/node.js:shouldIgnore`? Is the goal of shouldIgnore that you don't run babel on files that are dependencies of dependencies? So you want to test for the presence of `node_modules` twice in the path name? Or maybe have some knowledge of how npm global packages are installed?

**Comment by hzoo** [comment]
Going to be closing some issues for inactivity (also since this was from babel 5). We don't currently recommend installing babel globally atm and if anything https://github.com/babel/babel/issues/5091
