### ISSUE TITLE
Cannot read property '_paths' of null in traversal/path/index.js

### ISSUE THREAD

**Issue by koistya** [babel/babel#1933]
```
"C:\Program Files (x86)\JetBrains\WebStorm 10.0.4\bin\runnerw.exe" "C:\Program Files\iojs\babel-node.cmd" --debug-brk=2498 --nolazy --debug test\Spec.js
```

io.js 2.3.1, babel 5.6.14, Windows 8.1 (x64)

```
C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\transformation\file\index.js:634
      throw err;
            ^
TypeError: c:/Projects/Test/Test.js: Cannot read property '_paths' of null
    at Function.get (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\index.js:82:39)
    at NodePath.getSibling (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\family.js:97:29)
    at NodePath.shareCommentsWithSiblings (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\comments.js:28:19)
    at NodePath.dangerouslyRemove (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\removal.js:49:8)
    at NodePath.ForOfStatement (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\transformation\transformers\es6\for-of.js:58:12)
    at NodePath.call (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:61:28)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:94:8)
    at TraversalContext.visitSingle (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:112:12)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:124:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitMultiple (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:92:16)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:122:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitSingle (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:112:12)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:124:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitSingle (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:112:12)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:124:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitMultiple (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:92:16)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:122:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitMultiple (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:92:16)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:122:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitMultiple (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:92:16)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:122:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitSingle (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:112:12)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:124:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitMultiple (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:92:16)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:122:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitSingle (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:112:12)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:124:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitSingle (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:112:12)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:124:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitSingle (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:112:12)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:124:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitMultiple (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:92:16)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:122:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitMultiple (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:92:16)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:122:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at NodePath.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\path\context.js:111:26)
    at TraversalContext.visitSingle (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:112:12)
    at TraversalContext.visit (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\context.js:124:19)
    at Function.traverse.node (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:72:17)
    at Object.traverse [as default] (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\traversal\index.js:55:14)
    at PluginPass.transform (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\transformation\plugin-pass.js:44:27)
    at File.transform (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\transformation\file\index.js:596:12)
    at C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\transformation\pipeline.js:131:19
    at File.wrap (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\transformation\file\index.js:610:16)
    at Pipeline.transform (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\transformation\pipeline.js:128:17)
    at Object.transformFileSync (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\api\node.js:118:37)
    at compile (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\api\register\node.js:115:20)
    at normalLoader (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\api\register\node.js:166:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\api\register\node.js:179:7)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (c:/Projects/Test/Test.js:2:33)
    at Module._compile (module.js:428:26)
    at normalLoader (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\api\register\node.js:166:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Program Files\iojs\node_modules\babel\node_modules\babel-core\lib\babel\api\register\node.js:179:7)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Function.Module.runMain (module.js:469:10)
    at Object.<anonymous> (C:\Program Files\iojs\node_modules\babel\bin\_babel-node:112:12)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at [object Object].Module.runMain [as _onTimeout] (module.js:469:10)
    at Timer.listOnTimeout (timers.js:89:15)
```

**Comment by sebmck** [comment]
Provide the code of the file you're trying to compile please.

**Comment by koistya** [comment]
It breaks in places like `import react from 'react/addons';`, perhaps it doesn't ignore files from node_modules by default? I'm trying to add it via `--ignore node_modules` flag, but this seems doesn't make any difference.

**Comment by sebmck** [comment]
I can't reproduce this without the exact source code and options. You'll need to gist the entire `c:/Projects/Test/Test.js` file.

**Comment by koistya** [comment]
I will close, it for now, not able to reproduce it if the contents of Test.js is reduced to bare minimum.
