### ISSUE TITLE
Flow type hint in assignment after default export of class or function causes parse error

### ISSUE THREAD

**Issue by AgentME** [babel/babel#1941]
```javascript
export default function bar() {}
(Foo: any).a = 123;
```

```
[chris /tmp]$ babel --version
5.6.14
[chris /tmp]$ babel a.js 

/usr/local/lib/node_modules/babel/bin/babel/util.js:49
      throw err;
            ^
SyntaxError: a.js: Unexpected token (2:4)
  1 | export default function bar() {}
> 2 | (Foo: any).a = 123;
    |     ^
  3 | 
    at Parser.pp.raise (/usr/local/lib/node_modules/babel-core/lib/acorn/src/location.js:80:13)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/babel-core/lib/acorn/src/parseutil.js:95:8)
    at Parser.pp.expect (/usr/local/lib/node_modules/babel-core/lib/acorn/src/parseutil.js:89:26)
    at Parser.pp.parseExprList (/usr/local/lib/node_modules/babel-core/lib/acorn/src/expression.js:762:12)
    at Parser.pp.parseSubscripts (/usr/local/lib/node_modules/babel-core/lib/acorn/src/expression.js:259:27)
    at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/babel-core/lib/acorn/src/expression.js:234:15)
    at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/babel-core/lib/acorn/src/expression.js:214:19)
    at Parser.pp.parseExprOps (/usr/local/lib/node_modules/babel-core/lib/acorn/src/expression.js:170:19)
    at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/babel-core/lib/acorn/src/expression.js:153:19)
    at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/babel-core/lib/acorn/src/expression.js:121:19)
    at Parser.pp.parseExport (/usr/local/lib/node_modules/babel-core/lib/acorn/src/statement.js:628:21)
    at Parser.pp.parseStatement (/usr/local/lib/node_modules/babel-core/lib/acorn/src/statement.js:110:85)
    at Parser.parseStatement (/usr/local/lib/node_modules/babel-core/lib/acorn/plugins/flow.js:627:22)
    at Parser.pp.parseTopLevel (/usr/local/lib/node_modules/babel-core/lib/acorn/src/statement.js:30:21)
    at Object.parse (/usr/local/lib/node_modules/babel-core/lib/acorn/src/index.js:101:12)
    at Object.exports.default (/usr/local/lib/node_modules/babel-core/lib/babel/helpers/parse.js:72:19)
    at File.parse (/usr/local/lib/node_modules/babel-core/lib/babel/transformation/file/index.js:561:41)
    at File.parseCode (/usr/local/lib/node_modules/babel-core/lib/babel/transformation/file/index.js:646:22)
    at /usr/local/lib/node_modules/babel-core/lib/babel/transformation/pipeline.js:130:12
    at File.wrap (/usr/local/lib/node_modules/babel-core/lib/babel/transformation/file/index.js:610:16)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-core/lib/babel/transformation/pipeline.js:128:17)
    at Object.exports.transform (/usr/local/lib/node_modules/babel/bin/babel/util.js:34:22)
    at Object.exports.compile (/usr/local/lib/node_modules/babel/bin/babel/util.js:43:20)
    at /usr/local/lib/node_modules/babel/bin/babel/file.js:121:23
    at arrayEach (/usr/local/lib/node_modules/babel/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/babel/node_modules/lodash/index.js:3345:13)
    at walk (/usr/local/lib/node_modules/babel/bin/babel/file.js:118:7)
    at files (/usr/local/lib/node_modules/babel/bin/babel/file.js:130:5)
    at module.exports (/usr/local/lib/node_modules/babel/bin/babel/file.js:150:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/bin/babel/index.js:145:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

Removing "export default", changing it to export a value besides a function or class, or putting anything between the default export and the typed expression makes it work.

**Comment by sebmck** [comment]
It's because there's syntax ambiguity.

One of the productions of a `ExportDeclaration` is:

> export default [lookahead ∉ {function, class}] AssignmentExpression[In] ;

So it's actually being parsed as:

```javascript
export default (function bar() {})(Foo: any).a = 123;
```

Thus the type cast expression is being interpreted as the arguments list of a call.
