### ISSUE TITLE
No-op decorator on object property accessor throws

### ISSUE THREAD

**Issue by yuchi** [babel/babel#1949]
*test.js*:

```js
function deco() {
    return (target, name, descriptor) => (descriptor);
}

({
    @deco()
    get answer() { return 42 }
});
```

```
$ node --version
v0.12.4
$ babel --version
5.4.3
$ babel-node test.js
/path/to/test.js:3
 { descriptor.value = descriptor.initializer.call(target); } Object.defineProp
                                                                    ^
TypeError: Invalid property.  A property cannot both have accessors and be writable or have a value, [object Object]
    at Function.defineProperty (native)
    at _createDecoratedObject (/Users/pier/Development/decorators-toolbox/t.js:3:776)
    at Object.<anonymous> (/Users/pier/Development/decorators-toolbox/t.js:5:1)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:150:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:163:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/bin/_babel-node:111:12)
```

**Comment by yuchi** [comment]
Works with:

```js
function deco() {
    return (target, name, { writable, ...descriptor }) => (descriptor);
}

({
    @deco()
    get answer() { return 42 }
});
```

**Comment by yuchi** [comment]
:zap:
