### ISSUE TITLE
Call stack exceeded with async/await after update

### ISSUE THREAD

**Issue by grabbou** [babel/babel#1960]
Actually looks like mine stack trace is slightly different from #1958...

```
/usr/local/lib/node_modules/babel/bin/babel/util.js:49
      throw err;
            ^
RangeError: src/client/handlers/champagneHandler.js: Maximum call stack size exceeded
    at String.toString (native)
    at Type.<anonymous> (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:92:25)
    at Type.Object.defineProperties.check.value (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:34:36)
    at Field.Fp.getValue (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:245:22)
    at Object.getFieldValue (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:644:26)
    at NodePath.NPp.getValueProperty (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/node-path.js:116:18)
    at getChildPath (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:47:33)
    at NodePath.get (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:71:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:222:34)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at NodePath.each (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:96:22)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:199:14)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at NodePath.each (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:96:22)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:199:14)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at NodePath.each (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:96:22)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:199:14)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at NodePath.each (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:96:22)
    ...
    ...
    ...
    ...
    at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at Visitor.PVp.visit (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:124:25)
    at Function.transform (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/regenerator/lib/visit.js:30:11)
    at NodePath.exit (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformers/other/regenerator.js:41:34)
    at NodePath.call (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/context.js:61:28)
    at NodePath.visit (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/context.js:112:12)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:92:16)
    at TraversalContext.visit (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:122:19)
    at Function.traverse.node (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/index.js:72:17)
    at NodePath.visit (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/path/context.js:111:26)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:112:12)
    at TraversalContext.visit (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/context.js:124:19)
    at Function.traverse.node (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/index.js:72:17)
    at Object.traverse [as default] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/traversal/index.js:55:14)
    at PluginPass.transform (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/plugin-pass.js:44:27)
    at File.transform (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:596:12)
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/pipeline.js:131:19
    at File.wrap (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:610:16)
    at Pipeline.transform (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/pipeline.js:128:17)
    at Object.exports.transform (/usr/local/lib/node_modules/babel/bin/babel/util.js:34:22)
    at Object.exports.compile (/usr/local/lib/node_modules/babel/bin/babel/util.js:43:20)
    at /usr/local/lib/node_modules/babel/bin/babel/file.js:121:23
    at arrayEach (/usr/local/lib/node_modules/babel/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/babel/node_modules/lodash/index.js:3345:13)
    at walk (/usr/local/lib/node_modules/babel/bin/babel/file.js:118:7)
    at files (/usr/local/lib/node_modules/babel/bin/babel/file.js:130:5)
    at module.exports (/usr/local/lib/node_modules/babel/bin/babel/file.js:150:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/bin/babel/index.js:145:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Actually seems to fail on this https://gist.github.com/grabbou/52709cff517dfb1f43d7 which is rather weird as ~50 other similar (even bigger) handlers do not fail.

**Comment by sebmck** [comment]
Have you updated to Babel 5.6.16?

**Comment by grabbou** [comment]
Yes, used direct Github version as npm wasn't yet published:
```json
{
   "babel": "babel/babel#v5.6.16"
}
```

**Comment by sebmck** [comment]
That wont work unless you're manually building it. No compiled source it checked in.

**Comment by grabbou** [comment]
Yeah, was just going to say that, babel still pointing to previous version. Closing then, probably false alert.
