### ISSUE TITLE
Noisy Errors

### ISSUE THREAD

**Issue by tarwich** [babel/babel#1971]
The error messages in babel include a stack trace, which is really noisy. I'd like an option for `--no-stack` or something that would output this:

```
SyntaxError: test.js: Unexpected token (3:6)
  1 | 
  2 | class Foo {
> 3 |   bar {}
    |       ^
  4 | }
  5 | 
```

instead of this:
```
/usr/local/lib/node_modules/babel/bin/babel/util.js:49
      throw err;
            ^
SyntaxError: test.js: Unexpected token (3:6)
  1 | 
  2 | class Foo {
> 3 |   bar {}
    |       ^
  4 | }
  5 | 
    at Parser.pp.raise (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:80:13)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/parseutil.js:95:8)
    at Parser.pp.expect (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/parseutil.js:89:26)
    at Parser.pp.parseMethod (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/expression.js:696:8)
    at Parser.parseClassMethod (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:742:27)
    at Parser.pp.parseClass (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:549:10)
    at Parser.pp.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:80:19)
    at Parser.parseStatement (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/plugins/flow.js:627:22)
    at Parser.pp.parseTopLevel (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:30:21)
    at Object.parse (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/acorn/src/index.js:101:12)
    at Object.exports.default (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/helpers/parse.js:72:19)
    at File.parse (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:561:41)
    at File.parseCode (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:646:22)
    at /usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/pipeline.js:130:12
    at File.wrap (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:610:16)
    at Pipeline.transform (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/pipeline.js:128:17)
    at Object.exports.transform (/usr/local/lib/node_modules/babel/bin/babel/util.js:34:22)
    at Object.exports.compile (/usr/local/lib/node_modules/babel/bin/babel/util.js:43:20)
    at /usr/local/lib/node_modules/babel/bin/babel/file.js:121:23
    at arrayEach (/usr/local/lib/node_modules/babel/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/babel/node_modules/lodash/index.js:3345:13)
    at walk (/usr/local/lib/node_modules/babel/bin/babel/file.js:118:7)
    at files (/usr/local/lib/node_modules/babel/bin/babel/file.js:130:5)
    at module.exports (/usr/local/lib/node_modules/babel/bin/babel/file.js:150:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/bin/babel/index.js:145:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

> Please forgive me if this has been mentioned. I searched, but couldn't find it.

I looked at the source, and it seems like we're using fail-fast, so at first glance it looks hard to implement, but on second thought, I wonder if we could just wrap things in a `try` if some command-line argument is set.

If the powers that be see this as an option, then I'd be happy to contribute to a solution. I just wanted to post an issue first to see if there's an option or setting that I'm missing.

**Comment by impinball** [comment]
+1 for the CLI. -1 for the API (although an added property would be nice).

**Comment by tarwich** [comment]
Good point. I hadn't thought about the API side of it.

**Comment by tarwich** [comment]
:heart: Can't wait to try it out. Thanks @sebmck
