### ISSUE TITLE
Does not work with Flow `import type` statements

### ISSUE THREAD

**Issue by tengyifei** [babel/babel#1996]
```js
import type { Foo } from './Foo'
```
Triggers error
```
Bar.js: Cannot read property 'toLowerCase' of undefined
TypeError: file:///.../Bar.js.js: Cannot read property 'toLowerCase' of undefined
    at check (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:22283:21)
    at NodePath.ModuleDeclaration (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:22312:5)
    at NodePath.call (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:23019:28)
    at NodePath.visit (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:23052:8)
    at TraversalContext.visitMultiple (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:22424:16)
    at TraversalContext.visit (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:22462:19)
    at Function.traverse.node (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:22579:17)
    at NodePath.visit (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:23069:26)
    at TraversalContext.visitSingle (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:22448:12)
    at TraversalContext.visit (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:22464:19)
    at Function.traverse.node (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:22579:17)
    at Object.traverse [as default] (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:22558:14)
    at PluginPass.transform (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:15170:27)
    at File.transform (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:10155:12)
    at file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:15061:19
    at File.wrap (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:10173:16)
    at Pipeline.transform (file:///.../browser/jspm_packages/npm/babel-core@5.6.20/browser.js:15058:17)
    at /.../node_modules/systemjs-builder/compilers/esm.js:143:31
    at run (/.../node_modules/gulp-flowtype/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /.../node_modules/gulp-flowtype/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at process._tickCallback (node.js:355:11)e_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /...node_modules/gulp-flowtype/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at process._tickCallback (node.js:355:11)
```

**Comment by sebmck** [comment]
[I can't reproduce this](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=import%20type%20%7B%20Foo%20%7D%20from%20'.%2FFoo'&playground=false).

**Comment by tengyifei** [comment]
Hmmm. It doesn't happen at run time. Only happens when Babel is used to transpile files during the jspm bundling process. Perhaps some weird interaction between systemjs-builder and babel?

**Comment by sebmck** [comment]
This could be caused by `resolveModuleSource` returning `undefined` rather than a string. cc @guybedford

**Comment by guybedford** [comment]
The only reason I can think `resolveModuleSource` would return undefined in SystemJS builder would be if the dependencies weren't written in as the dependencies in the System.register transform:

```javascript
System.register([], function() {
  // ...
});
```

instead of:

```javascript
System.register(['./Foo'], function() {
  // ...
});
```

Is it possible that is happening here?

**Comment by sebmck** [comment]
No idea, not entirely familiar with the jspm/systemjs workflow. I'll add an assertion to confirm whether or not this is the cause.

**Comment by sebmck** [comment]
Actually, FWIW flow type imports are stripped from the compiled output which may be influencing that?

**Comment by guybedford** [comment]
Thanks seeing if there's something I can do this side.

**Comment by tengyifei** [comment]
Fixed. Thank you guys so much!
