### ISSUE TITLE
Error when installing older versions of babel

### ISSUE THREAD

**Issue by jonricaurte** [babel/babel#2011]
When I run: 
sudo npm install -g babel@5.6.14

I get the following error when i just run: babel
module.js:340
    throw err;
          ^
Error: Cannot find module 'babel-core/lib/babel/transformation/modules'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/home/u1260/src/repo/beauty/node_modules/babel/bin/babel/index.js:5:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

This used to work but stopped working in the last couple days.

**Comment by sebmck** [comment]
You need to update your version of `babel`. It's trying to use a newer `babel-core` version when it's only compatible with versions of the same range as it.

**Comment by jonricaurte** [comment]
When I install a specific version of babel, it should know what the dependency versions should be. What happens if the latest version of babel as an issue, and I deploy it to a website and the issue happens on deploy and breaks the website? This is why I want to use a specific version, so I do not have to worry about issues like this happening.

**Comment by sebmck** [comment]
Babel can't control your other dependency versions. This is a problem that needs to be solved with your module installer. I'd recommend taking a look at [npm shinkwrap](https://docs.npmjs.com/cli/shrinkwrap) if you want a way to provide consistent versions through the entire dependency graph.

**Comment by jonricaurte** [comment]
Doesn't babel use a package.json that says what its dependencies versions are? Couldn't babel specify its dependencies so when you install babel, you do not have to manage babel's dependencies. In this case babel relies on babel-core, I do not rely on babel-core.

**Comment by sebmck** [comment]
It does rely on `babel-core` internally. This is a module installer issue where it's resolving `babel-core` to be compatible with the `babel` package when it's not, the `babel` package specifies exactly what ranges it's compatible with. This could be likely due to npm 3 flattening the dependency tree so `babel-core` is top level and it's inferring it to be compatible when it's not.

**Comment by jmm** [comment]
@sebmck This seems like a legitimate issue to me.

> the babel package specifies exactly what ranges it's compatible with

`babel@5.6.14` depends on `babel-core@^5.6.14`, which currently installs `babel-core@5.7.2` and leads to this error. It seems that those versions (for example) are not compatible, but the semver matching is correct unless I'm misunderstanding something.

```sh
$ npm i babel@5.6.14 && node_modules/.bin/babel --help

module.js:340
    throw err;
          ^
Error: Cannot find module 'babel-core/lib/babel/transformation/modules'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/somedir/node_modules/babel/bin/babel/index.js:5:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

$ npm ls --depth=1

+-- babel@5.6.14
  +-- babel-core@5.7.2
```
