### ISSUE TITLE
transformFileSync is undefined in compiled code

### ISSUE THREAD

**Issue by Globegitter** [babel/babel#2017]
I am on node.js (v0.10.25) / io.js (v2.3.4) and have code as follows:

```js
import babel from 'babel';

let {code} = babel.transformFileSync(filename, {
  'stage'   : 0,
  'loose'   : true,
  'optional': 'runtime',
  'modules' : 'common'
});
```

Then I compile this code using `babel src --out-dir lib` and the same babel settings as above.

This yields roughly to following code:

```js
var _interopRequireDefault = require('babel-runtime/helpers/interop-require-default')['default'];

var _babel = require('babel');

var _babel2 = _interopRequireDefault(_babel);

var _babel$transformFileSync = _babel2['default'].transformFileSync(filename, {
      'stage': 0,
      'loose': true,
      'optional': 'runtime',
      'modules': 'common'
    });

    var code = _babel$transformFileSync.code;
```
When I then set filename to something and run the code it throws the following error:
```js
/home/mpadourek/Projects/experiments/Nord.js/lib/Server.js:84
    var _babel$transformFileSync = _babel2['default'].transformFileSync(filena
                                                      ^
TypeError: Cannot call method 'transformFileSync' of undefined
    at NordServer.transformAppCode (/Projects/experiments/Nord.js/lib/Server.js:84:55)
    at Object.<anonymous> (/Projects/experiments/Nord.js/lib/Server.js:120:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

There seem to be two simple fixes which make the above code work. Either change `_babel2['default']` to just `_babel2`, in the compiled code, or change the `babel-runtime/helpers/interop-require-default` file to following:

```js
"use strict";

exports["default"] = function (obj) {
  return {
    "default": obj
  };
};

exports.__esModule = true;
```

Not sure if either of these are proper solutions but there we go. Let me know if you need any other information.

**Comment by sebmck** [comment]
You aren't using ES6 imports correctly, you need to use a wildcard import:

```javascript
import * as babel from 'babel';
```

or reference the named import directly:

```javascript
import { transformFileSync } from 'babel';
```

**Comment by Globegitter** [comment]
Ah that would explain that. Cheers for the quick clarification.
