### ISSUE TITLE
no templates directory - this is most likely the result of a broken `npm publish`

### ISSUE THREAD

**Issue by vvs-code** [babel/babel#2044]
```
Building...
no templates directory - this is most likely the result of a broken `npm publish`. Please report to https://github.com/babel/babel/issues
ReferenceError: no templates directory - this is most likely the result of a broken `npm publish`. Please report to https://github.com/babel/babel/issues
    at loadTemplates (/Users/vvs/repo/apollo/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/util.js:337:11)
    at Object.<anonymous> (/Users/vvs/repo/apollo/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/util.js:360:23)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/vvs/repo/apollo/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/lib/transformation/modules/_default.js:32:13)
    at Module._compile (module.js:426:26)
```

**Comment by sebmck** [comment]
Being tracked at #2043.
