### ISSUE TITLE
ReferenceError: no templates directory ("babelify": "^6.1.3")

### ISSUE THREAD

**Issue by AlexBen** [babel/babel#2045]
$project$\node_modules\babelify\node_modules\babel-core\lib\util.js:337
    throw new ReferenceError(messages.get("missingTemplatesDirectory"));
          ^
ReferenceError: no templates directory - this is most likely the result of a broken `npm publish`. Please report to https://github.com/babel/babel/issues
    at loadTemplates ($project$\node_modules\babelify\node_modules\babel-core\lib\util.js:337:11)
    at Object.<anonymous> ($project$\node_modules\babelify\node_modules\babel-core\lib\util.js:360:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ($project$\node_modules\babelify\node_modules\babel-core\lib\transformation\modules\_default.js:32:13)
    at Module._compile (module.js:460:26)

**Comment by sebmck** [comment]
Upgrade to 5.8.3. Also see #2044 and #2043, please search next time. Thank you!

**Comment by AlexBen** [comment]
Sorry, didn't update for 10 minutes before report.
