### ISSUE TITLE
Crash for arrow function inside other function with empty whitelist

### ISSUE THREAD

**Issue by andy-hanson** [babel/babel#2152]
This code:

	var babel = require("babel-core")

	var code = "function a() { return () => this }"
	babel.transform(code, { whitelist: [ ] })

Causes this error:

	TypeError: unknown: Cannot read property 'this' of undefined
		at NodePath.inShadow (/node_modules/babel-core/lib/traversal/path/ancestry.js:231:27)
		at remap (/node_modules/babel-core/lib/transformation/transformers/internal/shadow-functions.js:31:25)
		at NodePath.ThisExpression (/node_modules/babel-core/lib/transformation/transformers/internal/shadow-functions.js:82:12)
		at NodePath.call (/node_modules/babel-core/lib/traversal/path/context.js:56:28)
		at NodePath.visit (/node_modules/babel-core/lib/traversal/path/context.js:89:8)
		at TraversalContext.visitSingle (/node_modules/babel-core/lib/traversal/context.js:132:12)
		at TraversalContext.visit (/node_modules/babel-core/lib/traversal/context.js:148:19)
		at Function.traverse.node (/node_modules/babel-core/lib/traversal/index.js:76:17)
		at NodePath.visit (/node_modules/babel-core/lib/traversal/path/context.js:106:26)
		at TraversalContext.visitSingle (/node_modules/babel-core/lib/traversal/context.js:132:12)

Broken in babel-core 5.8.20, works in 5.8.19.

**Comment by loganfsmyth** [comment]
Looks like a regression from https://github.com/babel/babel/commit/ea31229d, due to changes from the original PR https://github.com/babel/babel/pull/1692, we're no longer verifying that `shadow` is set before checking it.
