### ISSUE TITLE
Extending Set

### ISSUE THREAD

**Issue by devchakraborty** [babel/babel#2159]
Not sure if I'm doing something wrong here, but I'm having trouble extending Set. (babel 5.8.20)

Here's a simple test:

```
class Test extends Set {

}

let test = new Test()
```

Compiles to:

```
"use strict";

var _get = function get(_x, _x2, _x3) { var _again = true; _function: while (_again) { var object = _x, property = _x2, receiver = _x3; desc = parent = getter = undefined; _again = false; if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x = parent; _x2 = property; _x3 = receiver; _again = true; continue _function; } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var Test = (function (_Set) {
  _inherits(Test, _Set);

  function Test() {
    _classCallCheck(this, Test);

    _get(Object.getPrototypeOf(Test.prototype), "constructor", this).apply(this, arguments);
  }

  return Test;
})(Set);

var test = new Test();
```

At runtime:

```
/Users/dev/Development/test/src/example.js:15
   _get(Object.getPrototypeOf(Test.prototype), "constructor", this).apply(this
                                                                    ^
TypeError: Constructor Set requires 'new'
    at Test.Set (native)
    at new Test (/Users/dev/Development/test/src/example.js:15:70)
    at Object.<anonymous> (/Users/dev/Development/test/src/example.js:21:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by zloirock** [comment]
Extending built-in constructors not supported, [see caveats](https://babeljs.io/docs/advanced/caveats/#classes).
