### ISSUE TITLE
Exception when transforming simple test case

### ISSUE THREAD

**Issue by mattbasta** [babel/babel#2174]
The following code is the minimum test case that I could produce that exhibits the behavior:

```js
if (true) {
    function foo() {}
    function bar() {return foo;}
    for (var x in {}) {}
}
```

Running `babel test.js` (where `test.js` contains only the code above) produces the following exception:

```
TypeError: test.js: Cannot read property 'length' of undefined
    at BlockScoping.pushDeclar (/opt/btype/node_modules/babel/node_modules/babel-core/lib/transformation/transformers/es6/block-scoping.js:726:42)
    at NodePath.enter (/opt/btype/node_modules/babel/node_modules/babel-core/lib/transformation/transformers/es6/block-scoping.js:271:14)
    at NodePath.call (/opt/btype/node_modules/babel/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/opt/btype/node_modules/babel/node_modules/babel-core/lib/traversal/path/context.js:89:8)
    at TraversalContext.visitMultiple (/opt/btype/node_modules/babel/node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (/opt/btype/node_modules/babel/node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (/opt/btype/node_modules/babel/node_modules/babel-core/lib/traversal/index.js:76:17)
    at Object.traverse [as default] (/opt/btype/node_modules/babel/node_modules/babel-core/lib/traversal/index.js:55:14)
    at NodePath.traverse (/opt/btype/node_modules/babel/node_modules/babel-core/lib/traversal/path/index.js:163:23)
    at BlockScoping.hoistVarDeclarations (/opt/btype/node_modules/babel/node_modules/babel-core/lib/transformation/transformers/es6/block-scoping.js:707:20)

```

**Comment by mattbasta** [comment]
I should also mention that when I run `babel --version` I see `5.8.21 (babel-core 5.8.21)`

**Comment by mattbasta** [comment]
Thanks @sebmck!
