### ISSUE TITLE
minification.deadCodeElimination TypeError: test.js: Cannot read property '_paths' of null

### ISSUE THREAD

**Issue by achicu** [babel/babel#2221]
$ babel --version

    5.8.21 (babel-core 5.8.22)

$ cat test.js

    export function aFunction() {
        return 12345;
    }

$ babel --optional minification.deadCodeElimination test.js

    [BABEL] test.js: THE TRANSFORMER minification.deadCodeElimination HAS BEEN MARKED AS EXPERIMENTAL AND IS WIP. USE AT YOUR OWN RISK. THIS WILL HIGHLY LIKELY BREAK YOUR CODE SO USE WITH **EXTREME** CAUTION. ENABLE THE `experimental` OPTION TO IGNORE THIS WARNING.
    TypeError: test.js: Cannot read property '_paths' of null
        at Function.get (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/traversal/path/index.js:94:39)
        at NodePath.getSibling (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/traversal/path/family.js:98:29)
        at NodePath.shareCommentsWithSiblings (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/traversal/path/comments.js:20:19)
        at NodePath.dangerouslyRemove (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/traversal/path/removal.js:43:8)
        at NodePath.ReferencedIdentifier (/usr/local/lib/node_modules/babel/node_modules/babel-core/node_modules/babel-plugin-dead-code-elimination/lib/index.js:58:20)
        at NodePath.<anonymous> (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/traversal/visitors.js:219:17)
        at NodePath.call (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/traversal/path/context.js:56:28)
        at NodePath.visit (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/traversal/path/context.js:89:8)
        at TraversalContext.visitSingle (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/traversal/context.js:132:12)
        at TraversalContext.visit (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/traversal/context.js:148:19)

**Comment by sebmck** [comment]
Please report this on the [/babel-plugin-dead-code-elimination](https://github.com/babel-plugins/babel-plugin-dead-code-elimination) repo.

**Comment by achicu** [comment]
Sorry, didn't know. Seems like the issue was added before:
https://github.com/babel-plugins/babel-plugin-dead-code-elimination/issues/4
