### ISSUE TITLE
Cannot use super in a constructor (Assigning to rvalue)

### ISSUE THREAD

**Issue by MoOx** [babel/babel#226]
This raise an error

``` js
class MyError extends Error {
  constructor() {
    this = new super(...arguments)
  }
}
```

stack

```
  at raise (/test/node_modules/6to5/node_modules/acorn-6to5/acorn.js:340:15)
  at checkLVal (/test/node_modules/6to5/node_modules/acorn-6to5/acorn.js:1912:7)
  at parseMaybeAssign (/test/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2353:7)
  at parseExpression (/test/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2333:16)
  at parseStatement (/test/node_modules/6to5/node_modules/acorn-6to5/acorn.js:1985:38)
  at parseBlock (/test/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2261:18)
  at parseFunctionBody (/test/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2871:17)
  at parseMethod (/test/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2785:5)
  at parseClass (/test/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2924:22)
  at parseStatement (/test/node_modules/6to5/node_modules/acorn-6to5/acorn.js:1965:25)
```

This should works this way right ?
Calling just `super(...arguments)` don't do anything.

**Comment by petersandor** [comment]
I'm facing the same issue as @MoOx 

@thejameskyle  Can you please paste a snippet of what you have done in order to avoid this issue? The file you linked doesn't exist anymore.

**Comment by thejameskyle** [comment]
@petersandor https://github.com/marionettejs/backbone-metal/blob/master/src/error.js
