### ISSUE TITLE
`export default from` is not working

### ISSUE THREAD

**Issue by iamstarkov** [babel/babel#2265]
it [works online](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=export%20default%20from%20%27.%2Fbox-sticker.jsx%27%3B%0A)
```js
export default from './box-sticker.jsx';
```

but not with tool:

```js
ERROR in ./src/components/box-sticker/index.js
Module build failed: SyntaxError: /Users/iamstarkov/projects/test/src/components/box-sticker/index.js: Unexpected token (1:20)
> 1 | export default from './box-sticker.jsx';
    |                     ^
  2 |
    at Parser.pp.raise (/Users/iamstarkov/projects/test/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/iamstarkov/projects/test/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.semicolon (/Users/iamstarkov/projects/test/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:69:81)
    at Parser.pp.parseExport (/Users/iamstarkov/projects/test/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:691:25)
    at Parser.parseExport (/Users/iamstarkov/projects/test/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:679:20)
    at Parser.pp.parseStatement (/Users/iamstarkov/projects/test/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:115:90)
    at Parser.parseStatement (/Users/iamstarkov/projects/test/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:621:22)
    at Parser.pp.parseTopLevel (/Users/iamstarkov/projects/test/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/Users/iamstarkov/projects/test/node_modules/babel-core/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/Users/iamstarkov/projects/test/node_modules/babel-core/node_modules/babylon/lib/index.js:45:50)
```

am i doing it wrong or did I miss something?

**Comment by jmm** [comment]
Hello @iamstarkov, welcome to the Babel community! You don't show anything about how you configure or invoke Babel, but you need to [enable stage 1](http://babeljs.io/docs/usage/experimental/) for that (`es7.exportExtensions`) currently, as the `experimental` setting in your REPL link does.

For future reference please note that this issue tracker isn't used for this kind of issue, per the README:

>  For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

**Comment by iamstarkov** [comment]
@jmm thank you for response. I wasnt sure about question status support or bug report

**Comment by jmm** [comment]
@iamstarkov You're welcome. Yeah, unless you can be confident that something is a bug it's a good idea to bring it up in one of the other venues first.
