### ISSUE TITLE
Treating strings as sequence of characters produces a miscompile

### ISSUE THREAD

**Issue by pilif** [babel/babel#2267]
When applying the spread operator to strings, Babel produces output that throws a TypeError "undefined is not a function".

Test code

    $ echo 'console.log([..."💩"].length)' | babel | node

I would expect the ouput `1`.

I get

```
[stdin]:3
r.length; i++) arr2[i] = arr[i]; return arr2; } else { return Array.from(arr);
                                                                    ^
TypeError: undefined is not a function
    at _toConsumableArray ([stdin]:3:178)
    at [stdin]:5:23
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at Socket.<anonymous> (node.js:164:11)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

IMHO it's ok to not support treating strings as character sequences, but then I think babel should properly blow up and not produce code that doesn't run.

**Comment by pilif** [comment]
never mind. The compile just requires the polyfill. Closing this.
