### ISSUE TITLE
traverse can throws error when used directly

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2270]
Noticed this the other night when I was working on a processing script.

```
var ast = {
  "body": [
    {
      "id": {
        "name": "Example",
        "type": "Identifier"
      },
      "superClass": null,
      "body": {
        "body": [],
        "type": "ClassBody"
      },
      "type": "ClassDeclaration"
    }
  ],
  "sourceType": "module",
  "type": "Program"
};

babel.traverse(ast, {});
```

throws the following error

```
Error: We couldn't find a Function or Program...
    at Scope.getProgramParent (/private/tmp/omg/node_modules/babel-core/lib/traversal/scope/index.js:938:11)
    at Scope.crawl (/private/tmp/omg/node_modules/babel-core/lib/traversal/scope/index.js:874:23)
    at Scope.init (/private/tmp/omg/node_modules/babel-core/lib/traversal/scope/index.js:798:32)
    at NodePath.setScope (/private/tmp/omg/node_modules/babel-core/lib/traversal/path/context.js:148:30)
    at NodePath.setContext (/private/tmp/omg/node_modules/babel-core/lib/traversal/path/context.js:167:8)
    at NodePath.unshiftContext (/private/tmp/omg/node_modules/babel-core/lib/traversal/path/context.js:272:8)
    at TraversalContext.create (/private/tmp/omg/node_modules/babel-core/lib/traversal/context.js:74:10)
    at TraversalContext.visitMultiple (/private/tmp/omg/node_modules/babel-core/lib/traversal/context.js:95:25)
    at TraversalContext.visit (/private/tmp/omg/node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (/private/tmp/omg/node_modules/babel-core/lib/traversal/index.js:76:17)
```

Tried it going back and it seems this will throw some error or another back to `v5.4.3`. It appears to work as expected in `v5.4.2`.

On version `>= v5.4.3 < 5.5.0`, this error is thrown instead:

```
TypeError: Cannot read property 'bindings' of undefined
    at Scope.crawl (/private/tmp/omg/node_modules/babel-core/lib/babel/traversal/scope/index.js:663:40)
    at new Scope (/private/tmp/omg/node_modules/babel-core/lib/babel/traversal/scope/index.js:203:10)
    at Function.getScope (/private/tmp/omg/node_modules/babel-core/lib/babel/traversal/path/index.js:147:18)
    at TraversalPath.setScope (/private/tmp/omg/node_modules/babel-core/lib/babel/traversal/path/index.js:422:32)
    at TraversalPath.setContext (/private/tmp/omg/node_modules/babel-core/lib/babel/traversal/path/index.js:442:10)
    at TraversalPath.unshiftContext (/private/tmp/omg/node_modules/babel-core/lib/babel/traversal/path/index.js:490:10)
    at TraversalContext.create (/private/tmp/omg/node_modules/babel-core/lib/babel/traversal/context.js:40:10)
    at TraversalContext.visitMultiple (/private/tmp/omg/node_modules/babel-core/lib/babel/traversal/context.js:57:25)
    at TraversalContext.visit (/private/tmp/omg/node_modules/babel-core/lib/babel/traversal/context.js:100:19)
    at Function.traverse.node (/private/tmp/omg/node_modules/babel-core/lib/babel/traversal/index.js:64:17)
```

I don't however get an error when transforming that same AST via `babel.transform.fromAst(ast)`. I'm assuming there is something scope-related that is being initialized for the transformers that isn't for standard traversal.

**Comment by sebmck** [comment]
You're moreorless using a private API so it's not really supported. You need to wrap your `Program` in a `File` node, eg:

```javascript
var ast = {
  "type": "File", 
  "program": {
    "body": [
      {
        "id": {
          "name": "Example",
          "type": "Identifier"
        },
        "superClass": null,
        "body": {
          "body": [],
          "type": "ClassBody"
        },
        "type": "ClassDeclaration"
      }
    ],
    "sourceType": "module",
    "type": "Program"
  }
};

babel.traverse(ast, {});

```

**Comment by loganfsmyth** [comment]
Oh huh, okay. It was exposed, so I assumed it was supposed to work as a pair with `parse`, and it did work in 4.x and early 5.x. That error is also very misleading then, since I did have a `Program`.

**Comment by loganfsmyth** [comment]
@sebmck Should this be changed if `Program` nodes aren't allowed then? That explicit check is what made me assume `Program` nodes were supported.
https://github.com/babel/babel/blob/69232e525d7f03681361ac82f4e962184f2bd068/packages/babel/src/traversal/index.js#L16

**Comment by joshblack** [comment]
Is there a reason why the test case for `traverse` has an ast that isn't wrapped in a `File` node? See: https://github.com/babel/babel/blob/master/packages/babel/test/traverse.js#L79-L83

**Comment by sebmck** [comment]
You can still traverse it, it'll just error when it does scope tracking which it doesn't have to do for those test cases.

**Comment by loganfsmyth** [comment]
But you have no way of knowing ahead of time if something will need scope tracking, right? It doesn't seem like having `traverse` fail _some_ of the time for Program nodes is helpful. If they don't work 100% of the time, shouldn't they be disallowed entirely?

**Comment by joshblack** [comment]
@sebmck Awesome, sounds good. Thanks for responding! Is there anywhere that I can go to research/learn scope tracking or other topics related to the babel project? This stuff is amazingly cool.
