### ISSUE TITLE
Browserify+babelify+ngAnnotate error

### ISSUE THREAD

**Issue by baelter** [babel/babel#2297]
Not 100% sure babel is to blame, but error occurs in babel code and this is my best guess.

So there is a bug in browserify compiles which use both babelify and browserify-ngannotate programmatically. Using them via package.json works fine.

## The error

    TypeError: /home/anders/Projects/babel-npe/ngannotate-babel/index.js: Cannot read property 'match' of undefined
        at urlParse (/home/anders/Projects/babel-npe/ngannotate-babel/node_modules/babelify/node_modules/babel-core/node_modules/source-map/lib/source-map/util.js:37:21)
        at normalize (/home/anders/Projects/babel-npe/ngannotate-babel/node_modules/babelify/node_modules/babel-core/node_modules/source-map/lib/source-map/util.js:86:15)
        at Array.map (native)
        at SourceMapConsumer.BasicSourceMapConsumer (/home/anders/Projects/babel-npe/ngannotate-babel/node_modules/babelify/node_modules/babel-core/node_modules/source-map/lib/source-map/source-map-consumer.js:311:23)
        at new SourceMapConsumer (/home/anders/Projects/babel-npe/ngannotate-babel/node_modules/babelify/node_modules/babel-core/node_modules/source-map/lib/source-map/source-map-consumer.js:26:9)
        at File.mergeSourceMap (/home/anders/Projects/babel-npe/ngannotate-babel/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:511:31)
        at File.generate (/home/anders/Projects/babel-npe/ngannotate-babel/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:808:25)
        at File.transform (/home/anders/Projects/babel-npe/ngannotate-babel/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:625:17)
        at /home/anders/Projects/babel-npe/ngannotate-babel/node_modules/babelify/node_modules/babel-core/lib/transformation/pipeline.js:168:19
        at File.wrap (/home/anders/Projects/babel-npe/ngannotate-babel/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:639:16)

## Causes?
```inputMap.file``` is not set and https://github.com/babel/babel/blob/master/packages/babel/src/transformation/file/index.js#L463 later causes to error above...

I made a barebone repo to showcase the bug. Please look at: 
https://github.com/baelter/ngannotate-babel

I have no clue how all that source maps stuff is supposed to work so i'm not getting any further in my digging. Hopefully someone with more knowledge about this can take a look.

**Comment by sebmck** [comment]
Something else that's not Babel is generating an invalid source map that's causing the `source-map` module to barf.

**Comment by baelter** [comment]
Awsm feedback!

**Comment by baelter** [comment]
And from what I understand the ```file``` property of the source map is optional.

**Comment by thejameskyle** [comment]
Seems like this is actually an issue with `sources` not `file` (https://github.com/mozilla/source-map/blob/master/lib/source-map-consumer.js#L304-L308).

**Comment by thejameskyle** [comment]
Oh I'm sorry, I see what you are saying. Babel is [mapping file to sources](https://github.com/babel/babel/blob/31a01cc4d257e8d9237b02c5469c2cd7ce2d2abb/packages/babel/src/transformation/file/index.js#L464). @sebmck can you explain why?

**Comment by sebmck** [comment]
Closing due to inactivity and lack of information. Feel free to reopen if this is still an issue.
