### ISSUE TITLE
Set/Map cannot be subclassed without blacklisting the es6.classes transformer

### ISSUE THREAD

**Issue by Morfent** [babel/babel#2334]
When I pipe the following code through Babel, then io.js:
```javascript
class MySet extends Set {
    constructor(...args) {
        super(args);
    }
}

const mySet = new MySet(1, 2, 3);
mySet.add(4);
```
I get the following error:
```
[stdin]:19
    _get(Object.getPrototypeOf(MySet.prototype), "constructor", this).call(this, args);

TypeError: Constructor Set requires 'new'
    at MySet.Set (native)
    at new MySet ([stdin]:19:71)
    at [stdin]:25:13
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:430:26)
    at node.js:566:27
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```
The transpiled code is:
```javascript
"use strict";

var _get = function get(_x, _x2, _x3) { var _again = true; _function: while (_again) { var object = _x, property = _x2, receiver = _x3; desc = parent = getter = undefined; _again = false; if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x = parent; _x2 = property; _x3 = receiver; _again = true; continue _function; } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var MySet = (function (_Set) {
  _inherits(MySet, _Set);

  function MySet() {
    _classCallCheck(this, MySet);

    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    _get(Object.getPrototypeOf(MySet.prototype), "constructor", this).call(this, args);
  }

  return MySet;
})(Set);

var mySet = new MySet(1, 2, 3);mySet.add(4);
```
When I blacklist the es6.classes transformer, the code runs as expected, but I noticed that if I accessed `MySet.prototype` directly (like when adding `console.log(MySet.prototype);` to the original code), I'd get the following error:
```javascript
util.js:295
    empty = value.size === 0;
                 ^

TypeError: Method Set.prototype.size called on incompatible receiver #<MySet>
    at MySet.get size (native)
    at formatValue (util.js:295:18)
    at inspect (util.js:105:10)
    at Console.exports.format (util.js:13:20)
    at Console.log (console.js:36:34)
    at [stdin]:11:54
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:430:26)
    at node.js:566:27
```
...which is also the same type of error thrown when I run the original code through babel-node without blacklisting es6.classes. I'm running Babel v5.8.23 and io.js v3.3.0.

**Comment by zloirock** [comment]
Built-in constructors can't be subclassed in babel with current `es6.classes` transformer, see [caveats](https://babeljs.io/docs/advanced/caveats/#classes).
