### ISSUE TITLE
Destructuring to get second argument

### ISSUE THREAD

**Issue by roadhump** [babel/babel#2346]
I've tried this expression, which seems valid by specification
```
const x = (...[,b]) => console.log(b);
```

and got
```
TypeError: /Users/roadhump/Projects/Targetprocess/Mashups/ListColumnsResizer/src/index.js: Cannot read property 'typeAnnotation' of null
    at CodeGenerator.VariableDeclarator (/Users/roadhump/Projects/babel/packages/babel/lib/generation/generators/statements.js:331:22)
    at CodeGenerator.print (/Users/roadhump/Projects/babel/packages/babel/lib/generation/index.js:289:20)
    at NodePrinter.plain (/Users/roadhump/Projects/babel/packages/babel/lib/generation/node/printer.js:37:27)
    at CodeGenerator.printJoin (/Users/roadhump/Projects/babel/packages/babel/lib/generation/index.js:336:13)
    at NodePrinter.join (/Users/roadhump/Projects/babel/packages/babel/lib/generation/node/printer.js:56:27)
    at NodePrinter.list (/Users/roadhump/Projects/babel/packages/babel/lib/generation/node/printer.js:71:17)
    at CodeGenerator.VariableDeclaration (/Users/roadhump/Projects/babel/packages/babel/lib/generation/generators/statements.js:315:9)
    at CodeGenerator.print (/Users/roadhump/Projects/babel/packages/babel/lib/generation/index.js:289:20)
    at NodePrinter.plain (/Users/roadhump/Projects/babel/packages/babel/lib/generation/node/printer.js:37:27)
    at CodeGenerator.printJoin (/Users/roadhump/Projects/babel/packages/babel/lib/generation/index.js:336:13)
```

**Comment by loganfsmyth** [comment]
That's invalid syntax. The spec defines:

    FunctionRestParameter : BindingRestElement

    BindingRestElement : ... BindingIdentifier

so rest params in a function can only be identifiers, not other patterns. Seems easiest to use the argument list normally in this case.

That said, it looks like that error message isn't right since it is coming from the code generator, so there may still be a bug here with the parser.

**Comment by sebmck** [comment]
Yeah @loganfsmyth is correct. FWIW you should never have to do that and it's far clearer to do:

```javascript
const x = (a, b) => console.log(b);
```

**Comment by roadhump** [comment]
I just tried to find the shortest way to skip some arguments of function. 

Also `const x = (...[a,b]) => console.log(b);` is working now.

**Comment by sebmck** [comment]
As @loganfsmyth said, that's not valid syntax and it will be removed in the next major so I'd recommend not using it. Just use normal parameters, there's literally no advantage to using a rest parameter if you're going to array destructure it.
