### ISSUE TITLE
Static evaluation of instanceof and in statements causing errors

### ISSUE THREAD

**Issue by novacrazy** [babel/babel#2355]
I have a couple functions that look like this:
```javascript
function tryJSON( value ) {
    try {
        return JSON.parse( value );

    } catch( err ) {
        if( err instanceof SyntaxError ) {
            return value;

        } else {
            throw err;
        }
    }
}
```

Where Babel is throwing the error: 
```
TypeError: lib/server/normalize-query.js: Expecting a function in instanceof check, but got undefined
    at evaluate (node_modules/babel-core/lib/traversal/path/evaluation.js:213:34)
    at NodePath.evaluate (node_modules/babel-core/lib/traversal/path/evaluation.js:51:15)
    at NodePath.IfStatement (node_modules/babel-core/node_modules/babel-plugin-constant-folding/lib/index.js:34:42)
    at NodePath.call (node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitMultiple (node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitSingle (node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitSingle (node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitMultiple (node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitSingle (node_modules/babel-core/lib/traversal/context.js:132:12)
```

**Comment by novacrazy** [comment]
It also does this for `assert.AssertionError` and any other instanceof check. For `Error` based values I can just use `err.name === 'AssertionError'`, but that's not entirely reliable for errors provided by third-party libraries.

**Comment by novacrazy** [comment]
There also seem to be issues statically evaluating `in` statements. For example [Here](https://github.com/olado/doT/blob/ef4e74b2c0d98109e552b3a37cb1ca67124f3146/doT.js#L59) Babel tries to statically evaluate that `in` statement. I ran into this via the require-hook on a local copy of that module.

**Comment by sebmck** [comment]
Regression due to some changes made in #2300. cc @hzoo. `in` and `instanceof` should probably be removed.

**Comment by novacrazy** [comment]
Out of curiosity, why would Babel consider the `err` in `catch(err)` a static value that could be evaluated anyway? Or a function argument like with the `in` example I gave?

**Comment by sebmck** [comment]
The constant folding transformer literally tries to fold every single expression it can, it delegates to whatever the evaluation logic supports. `err` isn't evaluated by itself, what makes you think it is?

**Comment by novacrazy** [comment]
Ah, that makes sense. I figured there might have been a system for tracing back to the declaration of variables to determine if they are constants or not, and if they weren't then excluding them from the constant folding transformer. In retrospect, it's probably a lot easier to try evaluating it anyway, and it just happens that `in` and `instanceof` don't like undefined values.

**Comment by hzoo** [comment]
Was goina say we could check for undefined from `let left = evaluate(path.get("left"));`, but I don't think anyone will normally use `in` and `instanceof` as constants so should probably just remove for now like you suggested. Or maybe the other evaluate expressions should check for undefined as well (as long as `path.get("left")` itself wasn't undefined?

**Comment by sebmck** [comment]
@hzoo The `get` is never `undefined`, the result of `evaluate()` can be though. Probably safest to remove it as the scenarios it's used in will be way too dynamic.

**Comment by hzoo** [comment]
Yeah I meant checking `evaluate(path.get("left"))` for undefined as long as `node.left` itself wasn't undefined. I'l make a change now though
