### ISSUE TITLE
Document how to disable .babelrc inheritance

### ISSUE THREAD

**Issue by gajus** [babel/babel#2366]
How do I force babel NOT to look at the parent directory for babelrc?

I have two `.babelrc` files: `./a/.babelrc` and `./a/b/.babelrc`.

I am running `babel` in `./a/b` path.

`./a/.babelrc` defines a plugin “lodash".

I do not want to use this plugin when executing babel in `./a/b`

I have tried setting `./a/b/.babelrc` to:

```js
{
    "stage": 0,
    "plugins": []
}
```

However, running `babel` in `./a/b/` path still uses "lodash" plugin.

**Comment by gajus** [comment]
More info:

```sh
curiosity:examples gajus$ pwd
/Users/gajus/Documents/dev/gajus/youtube-player/examples
curiosity:examples gajus$ cat ./.babelrc
{
    "stage": 0,
    "plugins": []
}
curiosity:examples gajus$ cat ./../.babelrc
{
    "stage": 0,
    "plugins": [
        "lodash"
    ]
}
curiosity:examples gajus$ babel ./src/
Error: ENOENT: no such file or directory, scandir '/Users/gajus/Documents/dev/gajus/youtube-player/node_modules/babel-plugin-lodash/node_modules/lodash'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at getDirectories (/Users/gajus/Documents/dev/gajus/youtube-player/node_modules/babel-plugin-lodash/lib/lodash-modules.js:24:26)
    at Object.<anonymous> (/Users/gajus/Documents/dev/gajus/youtube-player/node_modules/babel-plugin-lodash/lib/lodash-modules.js:34:42)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
curiosity:examples gajus$ babel --babelrc ./.babelrc ./src/
Error: ENOENT: no such file or directory, scandir '/Users/gajus/Documents/dev/gajus/youtube-player/node_modules/babel-plugin-lodash/node_modules/lodash'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at getDirectories (/Users/gajus/Documents/dev/gajus/youtube-player/node_modules/babel-plugin-lodash/lib/lodash-modules.js:24:26)
    at Object.<anonymous> (/Users/gajus/Documents/dev/gajus/youtube-player/node_modules/babel-plugin-lodash/lib/lodash-modules.js:34:42)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by ustccjw** [comment]
@gajus https://github.com/gajus/react-css-modules/pull/20 this PR can you check it ?

**Comment by sebmck** [comment]
Please see the README:

> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by gajus** [comment]
That is a request for documentation. Since it is to the best of my 15 minutes search results, does not exist.

**Comment by sebmck** [comment]
> For documentation and website issues please visit the <a href="https://github.com/babel/babel.github.io">babel.github.io</a> repo.

**Comment by gajus** [comment]
Sorry, misread your reply.

**Comment by jmm** [comment]
@gajus `babel.github.io` repo is the place for documentation issues. Thanks!

**Comment by ustccjw** [comment]
@gajus I'm sorry to trouble everyone，can you check this PR https://github.com/gajus/react-css-modules/pull/20. I call you many times.
