### ISSUE TITLE
es6.parameters without es6.arrowFunctions fails on some edge cases

### ISSUE THREAD

**Issue by BenoitZugmeyer** [babel/babel#2373]
Now that nodejs supports arrow functions, I try to remove the `es6.arrowFunctions` transformer but it seems to be required for some edge case with the `es6.parameters` transformer.

To reproduce, try to compile this code with either `babel -b es6.arrowFunctions` or `babel -l es6.parameters`:
``` javascript
let a = (...args) => () => b(...args);
```
It breaks with the exception:
```
TypeError: unknown: undefined is not a function
    at NodePath.Function (/.../babel-core/lib/transformation/transformers/es6/parameters/rest.js:246:22)
    at NodePath.call (/.../babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/.../babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitSingle (/.../babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/.../babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/.../babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/.../babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitMultiple (/.../babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (/.../babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (/.../babel-core/lib/traversal/index.js:76:17)
```

Babel version: 5.8.23 (babel-core 5.8.24)

**Comment by thejameskyle** [comment]
[`node.body.body`](https://github.com/babel/babel/blob/master/packages/babel/src/transformation/transformers/es6/parameters/rest.js#L234) is a `CallExpression` and it needs to be turned into a `BlockStatement`.
