### ISSUE TITLE
Error with inline script in JSX

### ISSUE THREAD

**Issue by OliverJAsh** [babel/babel#2408]
``` js
export default () => (
    <script>
        var foo = function () { return 'bar'; };
    </script>
);
```

Leads to:

```
SyntaxError: /Users/OliverJAsh/Development/simple-offline-blog/views/shell.js: Unexpected token (6:32)
  4 | export default () => (
  5 |     <script>
> 6 |         var foo = function () { return 'bar'; };
    |                                 ^
  7 |     </script>
  8 | );
  9 |
    at Parser.pp.raise (/Users/OliverJAsh/Development/simple-offline-blog/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/OliverJAsh/Development/simple-offline-blog/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseExprAtom (/Users/OliverJAsh/Development/simple-offline-blog/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:425:12)
    at Parser.parseExprAtom (/Users/OliverJAsh/Development/simple-offline-blog/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/Users/OliverJAsh/Development/simple-offline-blog/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/Users/OliverJAsh/Development/simple-offline-blog/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Users/OliverJAsh/Development/simple-offline-blog/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Users/OliverJAsh/Development/simple-offline-blog/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Users/OliverJAsh/Development/simple-offline-blog/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExpression (/Users/OliverJAsh/Development/simple-offline-blog/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:79:19)
```

**Comment by sebmck** [comment]
This is expected behaviour. Can you explain what you're trying to do and why you're expecting this to work? The inside of a JSX tag is just text and `{}` is used for interpolation of an expression.

**Comment by OliverJAsh** [comment]
I want to have an inline script. I guess the right way would be to set
innerHTML

**Comment by sebmck** [comment]
Why? You can already execute whatever JavaScript you want so putting it in an inline script is unnecessary. Regardless, this is expected behaviour as it's inline with the syntax. If you have any further questions or need assistance feel free to use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by OliverJAsh** [comment]
I'm rendering JSX on the server, but I want the inline script to execute on
the client.
