### ISSUE TITLE
Can't use class expression inside object literal where key matches superclass name

### ISSUE THREAD

**Issue by AgentME** [babel/babel#2494]
```javascript
var x = {Foo: class extends Foo {}};
```

```
TypeError: unknown: Cannot read property 'length' of undefined
    at Object.exports.default (/usr/local/lib/node_modules/babel-core/lib/transformation/helpers/get-function-arity.js:18:34)
    at wrap (/usr/local/lib/node_modules/babel-core/lib/transformation/helpers/name-method.js:90:58)
    at Object.bare (/usr/local/lib/node_modules/babel-core/lib/transformation/helpers/name-method.js:218:10)
    at NodePath.ClassExpression (/usr/local/lib/node_modules/babel-core/lib/transformation/transformers/es6/classes/index.js:45:39)
    at NodePath.call (/usr/local/lib/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/usr/local/lib/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/usr/local/lib/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/usr/local/lib/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/usr/local/lib/node_modules/babel-core/lib/traversal/path/context.js:107:26)
```

It works fine if the object key and the superclass name don't match:

```javascript
var x = {Foo: class extends Foo2 {}};
```

**Comment by thejameskyle** [comment]
Still in 6.0, here's an updated stack trace:

```
TypeError: index.js: Cannot read property 'length' of undefined
    at Object.exports.default (/Users/thejameskyle/Projects/Tests/__babel-bug-2494/node_modules/babel-helper-get-function-arity/lib/index.js:15:29)
    at wrap (/Users/thejameskyle/Projects/Tests/__babel-bug-2494/node_modules/babel-helper-function-name/lib/index.js:61:69)
    at Object.exports.default (/Users/thejameskyle/Projects/Tests/__babel-bug-2494/node_modules/babel-helper-function-name/lib/index.js:160:10)
    at PluginPass.ClassExpression (/Users/thejameskyle/Projects/Tests/__babel-bug-2494/node_modules/babel-plugin-transform-es2015-classes/lib/index.js:37:60)
    at newFn (/Users/thejameskyle/Projects/Tests/__babel-bug-2494/node_modules/babel-traverse/lib/visitors.js:233:27)
    at NodePath._call (/Users/thejameskyle/Projects/Tests/__babel-bug-2494/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/thejameskyle/Projects/Tests/__babel-bug-2494/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/thejameskyle/Projects/Tests/__babel-bug-2494/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/Users/thejameskyle/Projects/Tests/__babel-bug-2494/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/thejameskyle/Projects/Tests/__babel-bug-2494/node_modules/babel-traverse/lib/context.js:111:19)
```

Test repo: https://github.com/thejameskyle/__babel-bug-2494
