### ISSUE TITLE
Error using runtime with ES7 async/await

### ISSUE THREAD

**Issue by felixfbecker** [babel/babel#2503]
**transpiling the code with `babel src --out-dir build` works without error**, but when I try to test using mocha and the babel runtime I get an exception:
```
λ mocha src --bail --compilers js:babel/register
C:\Users\felix\git\api\src\mensa\router.js:86
router.param('datum', async function (next) {
                      ^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at normalLoader (C:\Users\felix\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\api\register\node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\felix\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\api\register\node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:/Users/felix/git/api/src/server.js:3:32)
    at Module._compile (module.js:434:26)
    at normalLoader (C:\Users\felix\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\api\register\node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\felix\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\api\register\node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\felix\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\felix\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:213:14)
    at Mocha.run (C:\Users\felix\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:453:10)
    at Object.<anonymous> (C:\Users\felix\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:393:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```
The code snippet:
```js
router.param('datum', async function (next) {
  let datum = moment(this.params.datum)
  if (!datum.isValid()) {
    throw new HttpError(400, datum.parsingFlags())
  }
  await next
})
```

**Comment by sebmck** [comment]
Babel is not being ran over those files. That's a syntax error from V8.

**Comment by felixfbecker** [comment]
But.... where? I mean V8 shouldn't even "see" the async keyword right?!

**Comment by felixfbecker** [comment]
I also eslint without error.

**Comment by felixfbecker** [comment]
Fixed it, I accidently blacklisted regenerator in a .babelrc because I'm using Node 4 and didn't want it to transpile generators. Apparently, blacklisting regenerator also breaks async/await support.

**Comment by kishore-dataisys** [comment]
Now I'm getting the same error you've mentioned in the first line.
And I didn't understand how how did you fix. Could you please elaborate or show the change in your .babelrc?

**Comment by hzoo** [comment]
Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests. This is an old issue so it's hard to say if you have the same problem or not - either a typo in the config, or didn't install the relevant plugin/preset, or it's not picking up the config file.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
