### ISSUE TITLE
discrepancy between uppercase vs lowercase component names in jsx

### ISSUE THREAD

**Issue by romeovs** [babel/babel#2586]
When I run `babel-node` on this file:
```js
import React from 'react';
console.log(<component/>);
```
I get following the output (which is strange since i never define `component`):
```js
{ '$$typeof': Symbol(react.element),
  type: 'component',
  key: null,
  ref: null,
  props: {},
  _owner: null,
  _store: {} }
```

However, when I run it on this one:
```js
import React from 'react';
console.log(<Component/>);
```
i righteously get an error:
```
/Users/romeovs/example.js:9
console.log(_react2['default'].createElement(Component, null));
                                             ^
ReferenceError: Component is not defined
    at Object.<anonymous> (/Users/romeovs/example.js:2:14)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/lib/_babel-node.js:144:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Is there a reason for this discrepancy? I know lowercase react components are deprecated but here it just seems to ignore the component completely.

**Comment by sebmck** [comment]
Lowercase React JSX tag names refer to HTML tags. You can see reasoning for this [here](https://gist.github.com/sebmarkbage/f1f4ba40816e7d7848ad). There's nothing actionable here so I'm closing this. Thanks! :blush:
