### ISSUE TITLE
Cannot assign to read only property '.js' of #<Object> - require hook

### ISSUE THREAD

**Issue by MadLittleMods** [babel/babel#2590]
When using the require hook in an Atom package, I am running into this error: `Cannot assign to read only property '.js' of #<Object>`

```js
require('babel/register');
module.exports = require('./lib/something');
```

```
Cannot assign to read only property '.js' of #<Object>
TypeError: Cannot assign to read only property '.js' of #<Object>
    at registerExtension (C:\github\some-atom-package\node_modules\babel\node_modules\babel-core\lib\api\register\node.js:212:27)
    at C:\github\some-atom-package\node_modules\babel\node_modules\babel-core\lib\api\register\node.js:238:5
    at arrayEach (C:\github\some-atom-package\node_modules\babel\node_modules\lodash\internal\arrayEach.js:15:9)
    at Object.module.exports [as default] (C:\github\some-atom-package\node_modules\babel\node_modules\lodash\internal\createForEach.js:15:9)
    at hookExtensions (C:\github\some-atom-package\node_modules\babel\node_modules\babel-core\lib\api\register\node.js:236:36)
    at Object.<anonymous> (C:\github\some-atom-package\node_modules\babel\node_modules\babel-core\lib\api\register\node.js:246:1)
    at Module._compile (module.js:428:26)
    at Object.keys.forEach.Object.defineProperty.value [as .js] (C:\Users\madli_000\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

**Comment by sebmck** [comment]
I don't know enough about how Atom works. I assume this is a limitation of their module system. `babel/register` is only supported in Node and not Electron. Atom already has built-in support for Babel anyway, you can read more about that [here](http://blog.atom.io/2015/02/04/built-in-6to5.html). If you need any further assistance please don't hesitate to use one of the resources located in the README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

Thanks! :blush:

**Comment by MadLittleMods** [comment]
Thanks @sebmck, the problem with the `'use babel;` directive is that it only applies to the file it is declared in. I would really like to just declare it in the top-level module. [I asked in the Atom room](https://atomio.slack.com/archives/atom/p1445819177002164), so hopefully there are some solutions/ideas proposed there.

**Comment by AsaAyers** [comment]
> directive is that it only applies to the file it is declared in. I would really like to just declare it in the top-level module

This is a bad approach because you would be modifying the global environment shared by all Atom modules. By using `'use babel'`at the top of all of your modules you can opt into the new features without the risk of breaking other people's plugins.
