### ISSUE TITLE
Async functions throw assertion error

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2643]
Enabling `syntax-async-functions` causes Babel to throw an assertion error when transpiling:

```
AssertionError: tmp.js: false == true
    at exports.hoist (/Users/thesmyth/tmp/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/hoist.js:21:10)
    at PluginPass.exports.visitor.Function.exit (/Users/thesmyth/tmp/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/visit.js:85:18)
    at newFn (/Users/thesmyth/tmp/node_modules/babel-traverse/lib/visitors.js:233:27)
    at NodePath._call (/Users/thesmyth/tmp/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/thesmyth/tmp/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/thesmyth/tmp/node_modules/babel-traverse/lib/path/context.js:108:8)
    at TraversalContext.visitQueue (/Users/thesmyth/tmp/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/thesmyth/tmp/node_modules/babel-traverse/lib/context.js:111:19)
    at TraversalContext.visit (/Users/thesmyth/tmp/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/thesmyth/tmp/node_modules/babel-traverse/lib/index.js:139:17)
```

with

```
{
    "presets": [
        "es2015"
    ],
    "plugins": [
        "syntax-async-functions"
    ]
}
```

**Comment by loganfsmyth** [comment]
Another trace from @samwgoldman: https://gist.github.com/samwgoldman/aa42280c8f0215319b1b

```
AssertionError: index.js: false == true
    at getRuntimeMarkDecl (/Users/sam/Developer/OSS/observable/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/visit.js:180:10)
    at getOuterFnExpr (/Users/sam/Developer/OSS/observable/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/visit.js:159:20)
    at PluginPass.exports.visitor.Function.exit (/Users/sam/Developer/OSS/observable/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/visit.js:74:25)
    at newFn (/opt/homebrew/lib/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:233:27)
    at NodePath._call (/opt/homebrew/lib/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/opt/homebrew/lib/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/opt/homebrew/lib/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:108:8)
    at TraversalContext.visitQueue (/opt/homebrew/lib/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitMultiple (/opt/homebrew/lib/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:106:17)
    at TraversalContext.visit (/opt/homebrew/lib/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:193:19)
```

I see there's some work on `master` to remove these, not sure if the code still works though?

**Comment by loganfsmyth** [comment]
This is working now that the assertions have been removed, so I'm going to close it.

For anyone hitting this, ensure you have `babel-plugin-transform-regenerator@^6.0.12`

**Comment by kyrylkov** [comment]
@loganfsmyth is https://github.com/babel/babel/issues/2744 related?

**Comment by thelinuxlich** [comment]
is it related to #2761?
