### ISSUE TITLE
es2015-modules-umd fails when function property shares name of an import

### ISSUE THREAD

**Issue by andy-hanson** [babel/babel#2650]
Here's my code:

	import {foo} from 'foo'
	const x = {
		foo() {}
	}

Here's my package.json:

	{
		"scripts": {
			"build": "babel src --out-dir dist"
		},
		"devDependencies": {
			"babel-cli": "6.0.2",
			"babel-plugin-transform-es2015-modules-umd": "6.0.2"
		},
		"babel": {
			"plugins": ["transform-es2015-modules-umd"]
		}
	}

Running `npm run build` gives this error:

	TypeError: src/foo.js: Property key of ObjectMethod expected node to be of a type ["Identifier","Literal"] but instead got "MemberExpression"
		at validate (/home/andy/babel-bug/node_modules/babel-types/lib/definitions/index.js:97:13)
		at Object.validate (/home/andy/babel-bug/node_modules/babel-types/lib/definitions/core.js:467:63)
		at Object.validate (/home/andy/babel-bug/node_modules/babel-types/lib/index.js:267:9)
		at NodePath._replaceWith (/home/andy/babel-bug/node_modules/babel-traverse/lib/path/replacement.js:203:7)
		at NodePath.replaceWith (/home/andy/babel-bug/node_modules/babel-traverse/lib/path/replacement.js:181:8)
		at Object.ReferencedIdentifier (/home/andy/babel-bug/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:56:14)
		at Object.newFn (/home/andy/babel-bug/node_modules/babel-traverse/lib/visitors.js:279:17)
		at NodePath._call (/home/andy/babel-bug/node_modules/babel-traverse/lib/path/context.js:72:18)
		at NodePath.call (/home/andy/babel-bug/node_modules/babel-traverse/lib/path/context.js:44:17)
		at NodePath.visit (/home/andy/babel-bug/node_modules/babel-traverse/lib/path/context.js:102:12)

I suspect that es2015-modules-umd is turning the second `foo` identifier into a property of the imported module, when it should really just be left alone as a name.

**Comment by sebmck** [comment]
Fixed as of 6.0.13, thanks!
