### ISSUE TITLE
6.0 Running mocha tests with compiler doesn't work

### ISSUE THREAD

**Issue by tleunen** [babel/babel#2652]
Updated to Babel 6 and running this command doesn't use Babel as a compiler
```
mocha --compilers js:babel-core/register
```

get this error:
```
import assert from 'assert';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at loader (xxxxx/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (xxxxx/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at xxxxx/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (xxxxx/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (xxxxx/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (xxxxx/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by thejameskyle** [comment]
You need to use [`babel-preset-es2015`](https://github.com/babel/babel/tree/master/packages/babel-preset-es2015) and [`babel-plugin-transform-es2015-modules-commonjs`](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-commonjs).

Also, from the README:

> For questions and support please visit the [Slack community](https://babel-slack.herokuapp.com/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
> The Babel issue tracker is **exclusively** for bug reports and feature requests.

**Comment by tleunen** [comment]
Rah of course I forgot that. Thanks!

Feels weird nothing is included by default now :/
Hopefully soon we'll get this https://github.com/babel/babel/issues/2626
