### ISSUE TITLE
Identifiers can't be named $

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2664]
Using `babel-plugin-transform-es2015-modules-amd` and naming an Identifier errors out with:

```
TypeError: index.js: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got undefined
    at Object.validate (/Users/thejameskyle/Projects/Tests/__babel-setup-cagdas/node_modules/babel-types/lib/definitions/index.js:97:13)
    at Object.validate (/Users/thejameskyle/Projects/Tests/__babel-setup-cagdas/node_modules/babel-types/lib/index.js:267:9)
    at NodePath._replaceWith (/Users/thejameskyle/Projects/Tests/__babel-setup-cagdas/node_modules/babel-traverse/lib/path/replacement.js:203:7)
    at NodePath.replaceWith (/Users/thejameskyle/Projects/Tests/__babel-setup-cagdas/node_modules/babel-traverse/lib/path/replacement.js:181:8)
    at NodePath.replaceInline (/Users/thejameskyle/Projects/Tests/__babel-setup-cagdas/node_modules/babel-traverse/lib/path/replacement.js:291:17)
    at Array.enter (/Users/thejameskyle/Projects/Tests/__babel-setup-cagdas/node_modules/babel-template/lib/index.js:117:12)
    at NodePath._call (/Users/thejameskyle/Projects/Tests/__babel-setup-cagdas/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/thejameskyle/Projects/Tests/__babel-setup-cagdas/node_modules/babel-traverse/lib/path/context.js:40:14)
    at NodePath.visit (/Users/thejameskyle/Projects/Tests/__babel-setup-cagdas/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/Users/thejameskyle/Projects/Tests/__babel-setup-cagdas/node_modules/babel-traverse/lib/context.js:151:16)
```

See: https://github.com/thejameskyle/__babel-bug-dollar-amd

I'm pretty sure it comes down to babel-template on [this line](https://github.com/babel/babel/blob/master/packages/babel-template/src/index.js#L75) but I haven't taken the time to check it out any further.

/cc @ctulek

**Comment by zowers** [comment]
having it too,
`this.$("tr")` leads to the error, so most `Backbone.View`s will fail to transpile

**Comment by zowers** [comment]
I would like to stress this out the issue is showstopper
