### ISSUE TITLE
Errors for repos that depend on this repo or that are switching to this repo

### ISSUE THREAD

**Issue by paladox** [babel/babel#2669]
When switching dependacys to this repo we are getting this error.

148npm ERR! Failed to parse json

149npm ERR! Unexpected token }

150npm ERR! File: /home/travis/build/moment/moment/node_modules/Babel/package.json

151npm ERR! Failed to parse package.json data.

152npm ERR! package.json must be actual JSON, not just JavaScript.

153npm ERR! 

154npm ERR! This is not a bug in npm.

155npm ERR! Tell the package author to fix their package.json file. JSON.parse

156

157npm ERR! System Linux 3.13.0-40-generic

158npm ERR! command "/home/travis/.nvm/v0.10.40/bin/node" "/home/travis/.nvm/v0.10.40/bin/npm" "install"

159npm ERR! cwd /home/travis/build/moment/moment

160npm ERR! node -v v0.10.40

161npm ERR! npm -v 1.4.28

162npm ERR! file /home/travis/build/moment/moment/node_modules/Babel/package.json

163npm ERR! code EJSONPARSE

164npm ERR! not ok code 0

165

Please fix it

https://travis-ci.org/moment/moment/builds/88309154#L150

**Comment by paladox** [comment]
Also get this error

1067make[1]: Leaving directory `/home/travis/build/babel/babel'

1068cd packages/babel-runtime; \

1069	node scripts/build-dist.js

1070module.js:338

1071    throw err;

1072    ^

1073

1074Error: Cannot find module 'babel-runtime/core-js/symbol'

1075    at Function.Module._resolveFilename (module.js:336:15)

1076    at Function.Module._load (module.js:286:25)

1077    at Module.require (module.js:365:17)

1078    at require (module.js:384:17)

1079    at Object.<anonymous> (/home/travis/build/babel/babel/packages/babel-template/lib/index.js:5:15)

1080    at Module._compile (module.js:434:26)

1081    at Object.Module._extensions..js (module.js:452:10)

1082    at Module.load (module.js:355:32)

1083    at Function.Module._load (module.js:310:12)

1084    at Module.require (module.js:365:17)

1085make: *** [bootstrap] Error 1

1086

1087The command "make test-travis" exited with 2.

**Comment by paladox** [comment]
https://travis-ci.org/babel/babel/jobs/88313228

**Comment by paladox** [comment]
Please fix all errors since there seems to be a lot of errors in travis-ci.
