### ISSUE TITLE
variable declared in method with the same name causes error

### ISSUE THREAD

**Issue by venil7** [babel/babel#2684]
**Input:**

```
class Hello {
  some() {
    let some = () => console.log(123);
    return some();
  }
}
```

**Error:**
```js
TypeError: index.js: Duplicate declaration "some"
  1 | class Hello {
  2 |   some() {
> 3 |     let some = () => console.log(123);
    |         ^
  4 |     return some();
  5 |   }
  6 | }
    at File.buildCodeFrameError (/Users/thejameskyle/Projects/Tests/__babel-bug-2684/node_modules/babel-core/lib/transformation/file/index.js:409:15)
    at Scope.checkBlockScopedCollisions (/Users/thejameskyle/Projects/Tests/__babel-bug-2684/node_modules/babel-traverse/lib/scope/index.js:488:27)
    at Scope.<anonymous> (/Users/thejameskyle/Projects/Tests/__babel-bug-2684/node_modules/babel-traverse/lib/scope/index.js:673:18)
    at Scope.registerBinding (/Users/thejameskyle/Projects/Tests/__babel-bug-2684/node_modules/babel-traverse/lib/scope/index.js:687:8)
    at Scope.registerDeclaration (/Users/thejameskyle/Projects/Tests/__babel-bug-2684/node_modules/babel-traverse/lib/scope/index.js:575:14)
    at Object.BlockScoped (/Users/thejameskyle/Projects/Tests/__babel-bug-2684/node_modules/babel-traverse/lib/scope/index.js:226:28)
    at Object.newFn (/Users/thejameskyle/Projects/Tests/__babel-bug-2684/node_modules/babel-traverse/lib/visitors.js:311:17)
    at NodePath._call (/Users/thejameskyle/Projects/Tests/__babel-bug-2684/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/thejameskyle/Projects/Tests/__babel-bug-2684/node_modules/babel-traverse/lib/path/context.js:40:14)
    at NodePath.visit (/Users/thejameskyle/Projects/Tests/__babel-bug-2684/node_modules/babel-traverse/lib/path/context.js:102:12)
```

Example repo: https://github.com/thejameskyle/__babel-bug-2684

**Comment by ritz078** [comment]
same problem here.

**Comment by vmakhaev** [comment]
confirm problem

**Comment by sebmck** [comment]
I can't reproduce this. What options are you using?

**Comment by ritz078** [comment]
Settings
```javascript
{
    "presets":["es2015","stage-2"]
}
```
code
```javascript
class Spotify extends Base{
	constructor(input, options, embeds) {
		super(input, options, embeds);
		this.regex = /spotify.com\/track\/[a-zA-Z0-9_]+/gi;
	}

	template(match){
		let template =
		`<div class="ejs-embed">
		<iframe src="https://embed.spotify.com/?uri=spotify:track:${match.split('/')[2]}" height="80"></iframe>
		</div>`;
		return template;
	}
}
```
Error
```shell
ERROR in ./src/js/modules/audio/spotify.es6
Module build failed: TypeError: /Users/ritz078/projects/embed.js/src/js/modules/audio/spotify.es6: Duplicate declaration "template"
   8 |
   9 | 	template(match){
> 10 | 		let template =
     |       ^
  11 | 		`<div class="ejs-embed">
  12 | 		<iframe src="https://embed.spotify.com/?uri=spotify:track:${match.split('/')[2]}" height="80"></iframe>
  13 | 		</div>`;
    at File.buildCodeFrameError (/Users/ritz078/projects/embed.js/node_modules/babel-core/lib/transformation/file/index.js:409:15)
    at Scope.checkBlockScopedCollisions (/Users/ritz078/projects/embed.js/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:428:27)
    at Scope.<anonymous> (/Users/ritz078/projects/embed.js/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:613:18)
    at Scope.registerBinding (/Users/ritz078/projects/embed.js/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:627:8)
    at Scope.registerDeclaration (/Users/ritz078/projects/embed.js/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:515:14)
    at Object.BlockScoped (/Users/ritz078/projects/embed.js/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:165:28)
    at Object.newFn (/Users/ritz078/projects/embed.js/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:300:17)
    at NodePath._call (/Users/ritz078/projects/embed.js/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/ritz078/projects/embed.js/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:40:14)
    at NodePath.visit (/Users/ritz078/projects/embed.js/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/Users/ritz078/projects/embed.js/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:151:16)
 @ ./src/js/modules/audio/audio.es6 10:33-57
```

**Comment by venil7** [comment]
to replicate, create file containing my example above as `example.js`
then run `babel example.js --presets es2015`

**Comment by hzoo** [comment]
So far: 

I think `if (local.identifier === id) continue;` should be run but the objects are different (`local.identifer` doesn't have start/end/loc maybe?

https://github.com/babel/babel/blob/5508f4de567ec59b2bc85f371deddd912be138ef/packages/babel-traverse/src/scope/index.js#L464

```asdf
{ type: 'Identifier', name: 'a' }
asdf
{ type: 'Identifier',
  start: 30,
  end: 31,
  loc: { start: { line: 3, column: 8 }, end: { line: 3, column: 9 } },
  name: 'a' }
TypeError: a.js: Duplicate declaration "a"
  1 | class Hello {
  2 |   a() {
> 3 |     let a = 1;
    |         ^
  4 |   }
  5 | }
  6 |
    at File.buildCodeFrameError (/Users/hzhu/dev/test-jscs/_babel-bug-export-default-class-extends/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:409:15)
    at Scope.checkBlockScopedCollisions (/Users/hzhu/dev/test-jscs/_babel-bug-export-default-class-extends/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:428:27)
```
