### ISSUE TITLE
Problem: Instructions on mocha testing integration no longer correct with babel 6

### ISSUE THREAD

**Issue by trevorbernard** [babel/babel#2685]
register was removed in babel 6 but no replacement or work around was provided.

https://babeljs.io/docs/setup/#mocha

```javascript
{
  "scripts": {
    "test": "mocha --compilers js:babel/register"
  }
}
```

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /node_modules/mocha/bin/_mocha:296:3
    at Array.forEach (native)
    at Object.<anonymous> (/node_modules/mocha/bin/_mocha:290:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by safareli** [comment]
`babel/register` is now `babel-core/register` so try `mocha --compilers js:babel-core/register` instead

**Comment by jmm** [comment]
Thanks @safareli! Thanks for the report @trevorbernard. I opened https://github.com/babel/babel.github.io/issues/496 to get that documentation

**Comment by trevorbernard** [comment]
Awesome, thank you

**Comment by agudulin** [comment]
It doesn't work properly for me after updating to babel 6.0.12 and switching to `babel-core/register`
Check out this gist: https://gist.github.com/agudulin/136fe60d6b9ab41893a6

Seems that babel don't want transpile recursively.

**Comment by hzoo** [comment]
@agudulin not the same issue anymore and probably the same as https://github.com/babel/babel/issues/2676 (you need to add the right presets/packages like `npm i babel-preset-es2015`). Check out the slack room for more help

**Comment by agudulin** [comment]
@hzoo thank you for the quick reply, fixed.
