### ISSUE TITLE
`modules` option causes error

### ISSUE THREAD

**Issue by justinfagnani** [babel/babel#2693]
When I try to use `modules` (via gulp-babel) I get this error:

```
ReferenceError: [BABEL] /my/project/project.js: Unknown option: base.modules
    at Logger.error (/my/project/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/my/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:18)
    at OptionManager.init (/my/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:10)
    at File.initOptions (/my/project/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/my/project/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/my/project/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at DestroyableTransform._transform (/my/project/node_modules/gulp-babel/index.js:30:20)
    at DestroyableTransform.Transform._read (/my/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/my/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/my/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
```

**Comment by loganfsmyth** [comment]
`modules` is not an option. Can I ask where you saw that it was?

**Comment by loganfsmyth** [comment]
Also, please see our README:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by justinfagnani** [comment]
https://babeljs.io/docs/usage/options/

**Comment by justinfagnani** [comment]
I see the README says to report documentation issues to the babel.github.io repo. Since this appears to be a documentation issue, I presume you'll file it. I'll close this one.

**Comment by MrHalfman** [comment]
Hi, what is the good option for setting module formatter type?

I have the same error but I don't find any solution and the documentation still says that `modules` is a valid option.

**Comment by hzoo** [comment]
We need to update the docs then - Now it's through a transform plugin http://babeljs.io/docs/plugins/#modules

**Comment by MrHalfman** [comment]
Ok, I see. Thanks for the answer.
