### ISSUE TITLE
npm-running a babel-node script doesn’t work

### ISSUE THREAD

**Issue by rauschma** [babel/babel#2703]
File `my_repo/foo.js`:

```js
#!/usr/bin/env babel-node

import * as fs from 'fs';
...
```

File `my_repo/package.json`:

```js
...
"bin": {
  "foo": "./foo.js"
},
...
```

`./foo.js` works nicely, but if I do `npm run foo`, I get:

```
/Users/rauschma/my_repo/foo.js:3
import * as fs from 'fs';
^^^^^^

SyntaxError: Unexpected reserved word
```

Any ideas on how to fix this? Thanks!

**Comment by hzoo** [comment]
What is your `.babelrc` like? Did you add the es2015 preset?

**Comment by rauschma** [comment]
That’s what I suspected, too. But I didn’t understand why the direct invocation worked. The answer is simple: it called a globally installed v5 babel-node. Adding the following entry to `package.json` solved the problem:

```js
  "babel": {
    "presets": [
      "es2015"
    ]
  }
```

Does `.babelrc` have to be directly in the home directory or can it be in a nested directory, too (e.g. next to the file you want to execute via `babel-node`?

**Comment by gcollazo** [comment]
Somewhat related.

I'm trying to replicate the v5 babel-node functionality using v6. I created a .babelrc file on y home directory with `{ "presets": ["es2015"] }` and installed babel-cli and babel-preset-es2015 globally.

Now when I try to `babel-node script.js` I get the following error:

`Error: Couldn't find preset`

Is there a way to get `babel-node` to work globally with es2015?

**Comment by Mark-Simulacrum** [comment]
@gcollazo Depending on where your installation of `npm` installs global modules, `node` might not load them by default. You can set the `NODE_PATH` environment variable to the location of your globally installed `node_modules` directory.

For `nvm` users, it seems that `"$(npm config get prefix)/lib/node_modules"` is the path to the current globally installed modules directory. (May not work for all configurations).

The global installation (and use) of presets is possible (at least from my testing) when using `NODE_PATH` to tell node where to find modules.

**Comment by lijunle** [comment]
Same here...

I am using `stage-2` as preset in `.babelrc` file. The command `babel --optional runtime src/ -d dist/` work fine.

However, `babel-node` not works. Call stack:

```
-> % ./node_modules/.bin/babel-node ./build/component.js > ./dist/component.json                                                                               
/path/to/build/component.js:6
import fs from 'fs';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at loader (/path/to/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at /path/to/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/path/to/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:425:26)
```

**Comment by loganfsmyth** [comment]
@lijunle Have you installed and enabled `babel-preset-es2015` like the other comments in here suggest?

**Comment by lijunle** [comment]
I am using `stage-2` preset. I think the preset is working, otherwise `babel` should not work.

**Comment by loganfsmyth** [comment]
@lijunle `stage-2` does not include `es2015`.

**Comment by lijunle** [comment]
@loganfsmyth Great, it is working now!

IMO, anybody on stage-2 is using es2015. Nobody use stage-2 without es2015 feathers. Right?

Anyway, thank you very much! :+1:

**Comment by gcollazo** [comment]
@lijunle are you using it globally or just inside a particular project?

**Comment by loganfsmyth** [comment]
@lijunle Not everyone needs `es2015`  because people may for instance be using Node 4/5. The `stage` presets just enable experimental behavior.

**Comment by GGAlanSmithee** [comment]
@lijunle see #2713 for some discussion on this.

**Comment by iamstarkov** [comment]
same issue, babel-node cannot find preset in local scope
```bash
➜  generator-rise git:(fix/babel-v6) ✗ git diff --cached | cat
diff --git a/.babelrc b/.babelrc
new file mode 100644
index 0000000..3c078e9
--- /dev/null
+++ b/.babelrc
@@ -0,0 +1,5 @@
+{
+  "presets": [
+    "es2015"
+  ]
+}
diff --git a/package.json b/package.json
index b71ecdd..4b341e5 100644
--- a/package.json
+++ b/package.json
@@ -10,8 +10,13 @@
     "email": "jbucaran@me.com",
     "url": "https://github.com/bucaran"
   },
+  "babel": {
+    "presets": [
+      "es2015"
+    ]
+  },
   "scripts": {
-    "test": "babel-node test/index.js | tspec",
+    "test": "./node_modules/.bin/babel-node test/index.js | tspec",
     "coverage": "babel-node node_modules/isparta/bin/isparta cover --report text test/index.js",
     "coveralls": "npm run coverage && coveralls < coverage/lcov.info && rimraf ./coverage",
     "deploy": "git pull -q --rebase origin master && git push -q origin master"
@@ -59,11 +64,13 @@
     "yosay": "*"
   },
   "devDependencies": {
-    "tape": "*",
-    "babel": "*",
+    "babel-cli": "^6.1.1",
+    "babel-core": "^6.0.20",
+    "babel-preset-es2015": "^6.0.15",
     "coveralls": "*",
     "isparta": "*",
     "rimraf": "*",
-    "tap-spec": "*"
+    "tap-spec": "*",
+    "tape": "*"
   }
 }
➜  generator-rise git:(fix/babel-v6) ✗ ll node_modules | grep babel-cli
drwxr-xr-x  10 vlasta  staff   340B Nov  5 12:46 babel-cli
➜  generator-rise git:(fix/babel-v6) ✗ ll node_modules | grep babel-core
drwxr-xr-x   8 vlasta  staff   272B Nov  5 12:53 babel-core
➜  generator-rise git:(fix/babel-v6) ✗ ll node_modules | grep babel-preset
drwxr-xr-x   6 vlasta  staff   204B Nov  5 12:51 babel-preset-es2015
➜  generator-rise git:(fix/babel-v6) ✗ npm test

> generator-rise@1.7.0 test /Users/vlasta/projects/generator-rise
> babel-node test/index.js | tspec

/Users/vlasta/projects/generator-rise/node_modules/babel-core/lib/transformation/file/options/option-manager.js:310
          throw new Error("Couldn't find preset " + JSON.stringify(val));
          ^

Error: Couldn't find preset "es2015"
    at OptionManager.mergePresets (/Users/vlasta/projects/generator-rise/node_modules/babel-core/lib/transformation/file/options/option-manager.js:310:17)
    at OptionManager.mergeOptions (/Users/vlasta/projects/generator-rise/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:12)
    at OptionManager.addConfig (/Users/vlasta/projects/generator-rise/node_modules/babel-core/lib/transformation/file/options/option-manager.js:206:10)
    at OptionManager.findConfigs (/Users/vlasta/projects/generator-rise/node_modules/babel-core/lib/transformation/file/options/option-manager.js:347:16)
    at OptionManager.init (/Users/vlasta/projects/generator-rise/node_modules/babel-core/lib/transformation/file/options/option-manager.js:392:12)
    at compile (/Users/vlasta/projects/generator-rise/node_modules/babel-core/lib/api/register/node.js:96:22)
    at loader (/Users/vlasta/projects/generator-rise/node_modules/babel-core/lib/api/register/node.js:136:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/vlasta/projects/generator-rise/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)


  ✖ No tests found
➜  generator-rise git:(fix/babel-v6) ✗ babel-node -V
zsh: command not found: babel-node
➜  generator-rise git:(fix/babel-v6) ✗ ./node_modules/.bin/babel-node -V
6.1.2
```

**Comment by iamstarkov** [comment]
It’s pretty annoying bug which make testing with tape impossible? is there any ETA or smth?

@sebmck, do you need help with this bug?

**Comment by iamstarkov** [comment]
for some reason babel-node looking for presets twice
```
    presetLoc /Users/vlasta/projects/generator-rise/node_modules/babel-preset-es2015/index.js
    presetLoc null
/Users/vlasta/projects/generator-rise/node_modules/babel-core/lib/transformation/file/options/option-manager.js:312
          throw new Error("Couldn't find preset " + JSON.stringify(val));
```

the code is:
```js
if (typeof val === "string") {
  var presetLoc = _helpersResolve2["default"]("babel-preset-" + val, dirname) || _helpersResolve2["default"](val, dirname);
  console.log('presetLoc', presetLoc);
  if (presetLoc) {
    var presetOpts = require(presetLoc);
    this.mergeOptions(presetOpts, presetLoc, presetLoc, _path2["default"].dirname(presetLoc));
  } else {
    throw new Error("Couldn't find preset " + JSON.stringify(val));
  }
```

**Comment by iamstarkov** [comment]
mb i have a solution

**Comment by iamstarkov** [comment]
@rauschma @sebmck pls take a look at my pr #2875
