### ISSUE TITLE
using decorators with preset-stage-1 throws cryptic error message

### ISSUE THREAD

**Issue by marionebl** [babel/babel#2711]
Given I use the following babel config ...

```json
{
  "presets":
  [
    "stage-0",
    "stage-1",
    "stage-2",
    "stage-3",
    "es2015-without-regenerator"
  ],
  "plugins":
  [
    "transform-strict-mode",
    "transform-runtime",
    "transform-es2015-modules-commonjs"
  ],
  "sourceMaps": "inline"
}
```

... and use decorators on class methods like this ...

```js
class PatternManifestError extends Error {
	@readonly;
	@stat('PatternManifestError');
	name() {}

	@readonly
	@namespace
	get message() {}

	@readonly
	@namespace
	get meta() {}
}

function patternManifestErrorFactory(...args) {
	return new PatternManifestError(...args);
}

export default patternManifestErrorFactory;
export {PatternManifestError};

```

... the following Error is thrown ...
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: ~source/library/manifest/error.js: Cannot read property 'body' of undefined
    at NodePath._getKey (~node_modules/babel-core/node_modules/babel-traverse/lib/path/family.js:113:23)
    at NodePath.get (~node_modules/babel-core/node_modules/babel-traverse/lib/path/family.js:100:17)
    at NodePath._getPattern (~node_modules/babel-core/node_modules/babel-traverse/lib/path/family.js:158:21)
    at NodePath.get (~node_modules/babel-core/node_modules/babel-traverse/lib/path/family.js:103:17)
    at transformClass (~node_modules/babel-preset-stage-1/node_modules/babel-plugin-transform-decorators/lib/index.js:63:32)
    at PluginPass.ClassExpression (~node_modules/babel-preset-stage-1/node_modules/babel-plugin-transform-decorators/lib/index.js:155:30)
    at newFn (~node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:233:27)
    at NodePath._call (~node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (~node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (~node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (~node_modules/babel-core/node_modules/babel-traverse/lib/context.js:151:16)
```

**Comment by hzoo** [comment]
Just want to point out that the stage-0 preset includes stage-1 (and that includes stage-2), etc so you won't need to specify all of them.

**Comment by j-walker23** [comment]
@hzoo any idea why they locked the comments on the ticket you referenced above? What is a support query?

**Comment by sebmck** [comment]
Referenced the wrong issue in the commit message.

**Comment by marionebl** [comment]
@hzoo: Thanks for the heads-up concerning the official presets. People should be aware of precedence issues when relying on it, most notably with ES7 property initializers in stage-1. See: https://github.com/babel/babel/issues/2729
