### ISSUE TITLE
Boolean(await f()) fails

### ISSUE THREAD

**Issue by adrianp** [babel/babel#2743]
The following code:

```
var foo = async function() {
	var bar = Boolean(await baz());
};
```

fails with the following error:

```
AssertionError: test.js: false == true
    at explodeViaTempVar ([...]/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/emit.js:926:12)
    at [...]/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/emit.js:1042:20
    at Array.forEach (native)
    at Emitter.Ep.explodeExpression ([...]/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/emit.js:1041:14)
    at Emitter.Ep.explodeExpression ([...]/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/emit.js:1156:12)
    at Emitter.Ep.explodeStatement ([...]/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/emit.js:403:10)
    at [...]/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/emit.js:386:12
    at Array.forEach (native)
    at Emitter.Ep.explodeStatement ([...]/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/emit.js:385:22)
    at Emitter.Ep.explode ([...]/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/emit.js:333:17)
```

One way to fix it is:

```
var foo = async function() {
	var bar = await baz();
	baz = Boolean(baz);
};
```

```
$ babel --version
6.0.15 (babel-core 6.0.16)
```

**Comment by loganfsmyth** [comment]
You you make sure your `node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator` is fully up-to-date?

**Comment by adrianp** [comment]
@loganfsmyth It's `6.0.14`, the latest according the the [project homepage](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-regenerator/package.json).

**Comment by loganfsmyth** [comment]
Weird. This is the same assertion that was posted about here. https://github.com/babel/babel/pull/2723

Would you be up for trying to make a repo to reproduce this? I'm having trouble doing it locally.

**Comment by adrianp** [comment]
@loganfsmyth sure: https://github.com/adrianp/babel2743

Let me know if I can provide more details.

**Comment by loganfsmyth** [comment]
That assertion has been removed, and I can't reproduce locally. Care to give it another shot?

**Comment by adrianp** [comment]
Yep, seems to work now in `6.0.15 (babel-core 6.0.20)`, thanks!
