### ISSUE TITLE
"babel script.js" returns identical output, "babel-node script.js" gives me "Unexpected token import"

### ISSUE THREAD

**Issue by 01AutoMonkey** [babel/babel#2750]
New to babel-cli, I'm attempting to use it for ES6-7 server side code that plain Node doesn't support.

Running `babel server.js -o plain_server.js` gives me an identical file and `babel-node server.js` returns `Unexpected token import`.

Isn't babel-cli suppose to make things such as `import` work with Node by adding an additional compiling step?

I'm guessing the compile step isn't actually executing for some reason.

Also I'm using [n](https://github.com/tj/n) if that's relevant.

`$ babel --version: 6.0.15 (babel-core 6.0.16)`
`$ node --version: v5.0.0`
`$ babel-node --version: 6.0.15`
`$ uname -a: Linux HAL 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux `

Server Code:
```JS
import koa from 'koa'

const app = koa();
const port = 3000

app.listen(port);
```

`babel-node server.js` error:
```
/home/magus/dev/current/webapp-init/server.js:1
(function (exports, require, module, __filename, __dirname) { import koa from 'koa';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at loader (/home/magus/.npm-packages/lib/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/magus/.npm-packages/lib/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at /home/magus/.npm-packages/lib/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/home/magus/.npm-packages/lib/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:425:26)
```

**Comment by hzoo** [comment]
Did you add the `es2015` preset? http://babeljs.io/blog/2015/10/29/6.0.0/

**Comment by 01AutoMonkey** [comment]
That solved it! :)

`babel --presets babel-preset-es2015 server.js`
`babel-node --presets babel-preset-es2015 server.js`
