### ISSUE TITLE
NumberLiteral renamed

### ISSUE THREAD

**Issue by mfrye-intuit** [babel/babel#2764]
Just pulled the latest code and everything broke. I'm running the latest babel, react (with JSX), broswerify. Seems like it might be the use of the jsx {number} pattern.

```
Trace: Visitor defined for NumberLiteral but it has been renamed to NumericLiteral
  at Function.explode (/Users/mfrye2/code/d3-mobile/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:145:15)
  at Plugin.normalize (/Users/mfrye2/code/d3-mobile/node_modules/babel-core/lib/transformation/plugin.js:129:32)
  at new Plugin (/Users/mfrye2/code/d3-mobile/node_modules/babel-core/lib/transformation/plugin.js:55:25)
```

**Comment by sebmck** [comment]
Update everything. That's a deprecation message. It just echos a trace, it's not a thrown error.

**Comment by timqian** [comment]
Having this error too, 
node version: `5.0.0`
npm version: `3.3.10`
after `npm install babel -g` and `npm install babel-cli -g`
while doing `babel-node script.js`, these errors show up: 

```
Trace: Visitor defined for NumberLiteral but it has been renamed to NumericLiteral
    at Function.explode (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:145:15)
    at Plugin.normaliseVisitor (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:150:32)
    at new Plugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:57:25)
    at Function.memoisePluginContainer (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:123:21)
    at Function.normalisePlugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:151:32)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:185:30
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:163:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:36)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:313:16)
Trace: Visitor defined for RegexLiteral but it has been renamed to RegExpLiteral
    at Function.explode (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:145:15)
    at Plugin.normaliseVisitor (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:150:32)
    at new Plugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:57:25)
    at Function.memoisePluginContainer (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:123:21)
    at Function.normalisePlugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:151:32)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:185:30
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:163:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:36)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:313:16)
Trace: Visitor defined for RegexLiteral but it has been renamed to RegExpLiteral
    at Function.explode (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:145:15)
    at Plugin.normaliseVisitor (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:150:32)
    at new Plugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:57:25)
    at Function.memoisePluginContainer (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:123:21)
    at Function.normalisePlugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:151:32)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:185:30
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:163:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:36)
... 
```

**Comment by sebmck** [comment]
It's a deprecation message not an error.

On Fri, Nov 13, 2015 at 5:57 AM, 钱利江 <notifications@github.com> wrote:

> Having this error too,
> node version: 5.0.0
> npm version: 3.3.10
> after npm install babel -g and npm install babel-cli -g
> while doing babel-node script.js, these errors show up:
>
> Trace: Visitor defined for NumberLiteral but it has been renamed to NumericLiteral
>     at Function.explode (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:145:15)
>     at Plugin.normaliseVisitor (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:150:32)
>     at new Plugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:57:25)
>     at Function.memoisePluginContainer (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:123:21)
>     at Function.normalisePlugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:151:32)
>     at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:185:30
>     at Array.map (native)
>     at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:163:20)
>     at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:36)
>     at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:313:16)
> Trace: Visitor defined for RegexLiteral but it has been renamed to RegExpLiteral
>     at Function.explode (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:145:15)
>     at Plugin.normaliseVisitor (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:150:32)
>     at new Plugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:57:25)
>     at Function.memoisePluginContainer (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:123:21)
>     at Function.normalisePlugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:151:32)
>     at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:185:30
>     at Array.map (native)
>     at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:163:20)
>     at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:36)
>     at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:313:16)
> Trace: Visitor defined for RegexLiteral but it has been renamed to RegExpLiteral
>     at Function.explode (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:145:15)
>     at Plugin.normaliseVisitor (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:150:32)
>     at new Plugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:57:25)
>     at Function.memoisePluginContainer (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:123:21)
>     at Function.normalisePlugin (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:151:32)
>     at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:185:30
>     at Array.map (native)
>     at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:163:20)
>     at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:36)
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2764#issuecomment-156436592>.
>



-- 
Sebastian McKenzie

**Comment by timqian** [comment]
Thanks for reply @sebmck , but babel-node doesn't work, how can I make it work?
