### ISSUE TITLE
Error: You gave us a visitor for the node type "NumericLiteral" but it's not a valid type

### ISSUE THREAD

**Issue by cameronjroe** [babel/babel#2770]
Getting this error when trying to transpile a class written in ES2015.

`Error: You gave us a visitor for the node type "NumericLiteral" but it's not a valid type`

- installed `babel-cli` globally v6.0.15
- using .babelrc
`{
  "presets": ["es2015","stage-0"]
}`
- running `$ babel lib -d dist`

**Comment by thejameskyle** [comment]
Can you try reinstalling all your Babel `node_modules`?

**Comment by thejameskyle** [comment]
Also, please include a stack trace. Messages aren't that useful on their own

**Comment by cameronjroe** [comment]
```
$ babel lib -d dist
Error: You gave us a visitor for the node type "NumericLiteral" but it's not a valid type
    at verify (/Users/cameronjroe/.nvm/versions/node/v4.0.0/lib/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:190:13)
    at Function.explode (/Users/cameronjroe/.nvm/versions/node/v4.0.0/lib/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:67:3)
    at Plugin.normalize (/Users/cameronjroe/.nvm/versions/node/v4.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:129:32)
    at new Plugin (/Users/cameronjroe/.nvm/versions/node/v4.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/plugin.js:55:25)
    at Function.memoisePluginContainer (/Users/cameronjroe/.nvm/versions/node/v4.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:123:21)
    at Function.normalisePlugin (/Users/cameronjroe/.nvm/versions/node/v4.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:149:32)
    at /Users/cameronjroe/.nvm/versions/node/v4.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/cameronjroe/.nvm/versions/node/v4.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:20)
    at OptionManager.mergeOptions (/Users/cameronjroe/.nvm/versions/node/v4.0.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:254:36)
```

**Comment by thejameskyle** [comment]
What version of `babel-cli` are you running globally?

**Comment by cameronjroe** [comment]
Ran the following:
```
$ npm uninstall -g babel-cli
unbuild babel-cli@6.0.15
```
```
$ npm uninstall babel-preset-es2015 babel-preset-stage-0 --save
unbuild babel-preset-es2015@6.0.15
unbuild babel-preset-stage-0@6.0.15
```
```
$ npm cache clean
```
```
$ npm i -g babel-cli; npm i babel-preset-es2015 babel-preset-stage-0 --save
```

Fixed.

**Comment by thejameskyle** [comment]
Sweet, I think it was just an issue of mismatching versions after the name change from `NumberLiteral` to `NumericLiteral`
