### ISSUE TITLE
"'super.*' is not allowed before super()" when trying to compile class without a constructor

### ISSUE THREAD

**Issue by vbarbarosh** [babel/babel#2775]
Babel6 produces an error when trying to compile class without a constructor.

```sh
$ babel --version
6.0.15 (babel-core 6.0.20)
$ babel --presets react,es2015,stage-1 Hello.jsx
SyntaxError: Hello.jsx: 'super.*' is not allowed before super() (This is an error on an internal node. Probably an internal error)
undefined
```

**Hello.jsx**
```jsx
var _ = require('underscore'),
    React = require('react');

class Hello extends React.Component
{
    state = {
        hello: 1
    };

/*
    constructor() {
        super();
    }
*/

    render() {
        var props = _.omit(this.props, 'children');
        return (
            <p className="1" {... props}>Hello</p>
        );
    }
    
    foo(param = 1) {
        this.param = param;
    }
}

module.exports = Hello;
```

After uncommenting the constructor it compiles:
```sh
$ babel --presets react,es2015,stage-1 Hello.jsx
'use strict';

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

var _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var _ = require('underscore'),
    React = require('react');

var Hello = (function (_React$Component) {
    _inherits(Hello, _React$Component);

    function Hello() {
        _classCallCheck(this, Hello);

        var _this = _possibleConstructorReturn(this, Object.getPrototypeOf(Hello).call(this));

        _this.state = {
            hello: 1
        };
        return _this;
    }

    _createClass(Hello, [{
        key: 'render',
        value: function render() {
            var props = _.omit(this.props, 'children');
            return React.createElement(
                'p',
                _extends({ className: '1' }, props),
                'Hello'
            );
        }
    }, {
        key: 'foo',
        value: function foo() {
            var param = arguments.length <= 0 || arguments[0] === undefined ? 1 : arguments[0];

            this.param = param;
        }
    }]);

    return Hello;
})(React.Component);

module.exports = Hello;
```

**Comment by mattstyles** [comment]
Is this still a problem with 6.0.20? There are a [few issues](https://github.com/babel/babel/issues/2688) along a similar vein.

**Comment by vbarbarosh** [comment]
I've updated to the latest `babel-cli` and `babel-core`. The problem still exists:
```
$ babel --version
6.1.1 (babel-core 6.0.20)
$ babel --presets react,es2015,stage-1 Hello.jsx
SyntaxError: Hello.jsx: 'super.*' is not allowed before super() (This is an error on an internal node. Probably an internal error)
undefined
```

**Comment by SteveEdson** [comment]
Also experiencing this issue. Greenkeeper has been testing all newer versions and my tests are still failing.

My file is at https://github.com/SteveEdson/generate-assets/blob/master/src/image-assets.js

and my failed tests are at https://travis-ci.org/SteveEdson/generate-assets

With Babel 5, using a class with static methods worked without any issues.

Thanks.

**Comment by phyllisstein** [comment]
I'm seeing the same thing in 6.0.20, so far only when using class properties as @vbarbarosh did. This code works:

```js
class ShardsDirective {
  scope = true;

  constructor() {
    console.log('constructing');
  }

  link($scope, $element) {
    $($element).shards();
  }

  static factory() {
    ShardsDirective.instance = new ShardsDirective;
    return ShardsDirective.instance;
  }
}
```

...but if I remove the constructor, I get an error:

```
TypeError: src/camp/home/cpShardsDirective.es6: Cannot read property 'shadow' of undefined
    at NodePath.has (/Users/phyllisstein/Repos/Personal/shannon.camp/node_modules/babel-traverse/lib/path/introspection.js:104:22)
    at /Users/phyllisstein/Repos/Personal/shannon.camp/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:134:24
    at NodePath.findParent (/Users/phyllisstein/Repos/Personal/shannon.camp/node_modules/babel-traverse/lib/path/ancestry.js:40:9)
    at PluginPass.ThisExpression (/Users/phyllisstein/Repos/Personal/shannon.camp/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:133:19)
    at /Users/phyllisstein/Repos/Personal/shannon.camp/node_modules/babel-traverse/lib/visitors.js:271:19
    at NodePath._call (/Users/phyllisstein/Repos/Personal/shannon.camp/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/phyllisstein/Repos/Personal/shannon.camp/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/phyllisstein/Repos/Personal/shannon.camp/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/Users/phyllisstein/Repos/Personal/shannon.camp/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/phyllisstein/Repos/Personal/shannon.camp/node_modules/babel-traverse/lib/context.js:111:19)
```

It also transpiles successfully if I remove _both_ the constructor _and_ the class property. I'd be happy to provide any more details I can, if that'd help with troubleshooting. Thanks so much for your work on Babel!

**Comment by danderu** [comment]
Hi! I'm having the same issue. More light about this:

This doesn't work:

```javascript
import React, {Component} from 'react';

export default class RandomComponent extends Component {
  constructor(){
    super();
  }

  render() {
    return (
      <div className='sui-RandomComponent'>
        <h2>Hi there!</h2>
      </div>
    );
  }
}
````
But this, does the trick:
```javascript
import React, {Component} from 'react';

class RandomComponent extends Component {
  constructor(){
    super();
  }

  render() {
    return (
      <div className='sui-RandomComponent'>
        <h2>Hi there!</h2>
      </div>
    );
  }
}

export default RandomComponent;
```

**Comment by sebmck** [comment]
I can't reproduce this. Can you verify that this is still an issue?

**Comment by danderu** [comment]
@sebmck @thejameskyle I'm using babel v6.0.15 on top of node v5.0.0. This is what my .babelrc looks like:

```
{
  "presets": ["react", "es2015", "stage-1"]
}
```

I've seen there are released other versions in github, until v6.1.3, but it's not published in npm. May this version fix the issue? When are you planning to publish it?

**Comment by kirbysayshi** [comment]
Not sure what issue @danderu is reporting.

The original issue, that of a property initializer causing the `super.* is not...` error when no constructor calls `super()` is still an issue using babel-core@6.1.4.

**Comment by sebmck** [comment]
babel-core has nothing to do with it. There are other packages involved.
Please ensure that they're all on latest too.

On Wed, Nov 11, 2015 at 1:34 PM, Andrew Petersen <notifications@github.com>
wrote:

> Not sure what issue @danderu <https://github.com/danderu> is reporting.
>
> The original issue, that of a property initializer causing the super.* is
> not... error when no constructor calls super() is still an issue using
> babel-core@6.1.4.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2775#issuecomment-155916871>.
>



-- 
Sebastian McKenzie

**Comment by kirbysayshi** [comment]
@sebmck which packages are relevant? I just removed my node_modules, and did a clean install using the latest babel-core. I have the latest presents for react, es2015, and stage0. I understand that those are meta packages, but there are 97 packages in my node_modules that have 'babel' in the name; it's pretty hard to know which packages could possibly be related to this problem. `npm outdated` does not list anything babel related.

**Comment by sebmck** [comment]
@kirbysayshi Yeah that should do it yet. Do you have any code and options that reproduces this? I need those in order to reproduce and fix this.

**Comment by sebmck** [comment]
Managed to reproduce. Release will be out ASAP, my laptop is playing up.

**Comment by Surreal9** [comment]
I am seeing the same issue; I see this issue is closed is there a resolution?
