### ISSUE TITLE
export class with statics

### ISSUE THREAD

**Issue by mattstyles** [babel/babel#2779]
I have another test case for the `export default` and `class extends` suites, sounds like these are just about smashed out with `6.0.20`

```
export default class Foo {
  constructor() {
    this.foo = 'foo'
  }
  static bar = 'bar'
}
```

```
{
  "presets": [ "es2015" ]
}
```

---

[This fix](https://github.com/babel/babel/commit/c1cceef1286f33adf6de64be16cc197648d096a5) would seem to be about there to fixing this one too.

[ref](https://github.com/babel/babel/issues/2700)

**Comment by mattstyles** [comment]
I updated the issue title, `export` or `export default` makes no difference. I tried `loose` mode too on classes and/or modules.

**Comment by heydenberk** [comment]
I'm encountering this issue as well, and it's an obstacle to using I believe this to be a complete test case which reproduces this issue, and shows that it works if you export after declaring the class or if you omit the statics:

https://gist.github.com/heydenberk/56b654e05b38c88ca472

Look at build.sh for the commands to fully reproduce the environment and the resulting issues.

**Comment by alexbeletsky** [comment]
Having that issue as well,

```js
export default class SignUp extends Component {
  static contextTypes = {
    store: PropTypes.any,
    history: PropTypes.object.isRequired
  }
  // ...
```

Produces error,

```bash
ERROR in ./source/containers/SignUp/index.js
Module build failed: Error: /Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/source/containers/SignUp/index.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (/Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/node_modules/babel-traverse/lib/path/modification.js:181:13)
    at PluginPass.Class (/Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/node_modules/babel-plugin-transform-class-properties/lib/index.js:146:14)
    at /Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/node_modules/babel-traverse/lib/visitors.js:271:19
    at NodePath._call (/Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/node_modules/babel-traverse/lib/context.js:111:19)
    at TraversalContext.visit (/Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/alexanderbeletsky/Development/Projects/blogfoster/front-stack/node_modules/babel-traverse/lib/index.js:139:17)
 @ ./source/containers/index.js 14:15-34
```

But that code works fine,

```js
class SignUp extends Component {
  static contextTypes = {
    store: PropTypes.any,
    history: PropTypes.object.isRequired
  }
  // ...
}

export default SignUp;
```

package.json

```
    "babel-core": "^6.1.2",
    "babel-loader": "^6.0.1",
    "babel-plugin-react-transform": "^1.1.1",
    "babel-preset-es2015": "^6.1.2",
    "babel-preset-react": "^6.1.2",
    "babel-preset-stage-0": "^6.1.2",
```

.babelrc

```
{
  "presets": ["es2015", "stage-0", "react"]
}
```

**Comment by billychan** [comment]
I met almost same issue as @alexbeletsky except it's on `function` and I figured out another variation that works.

#### This won't work
Using `export default` directly
```
export default function(Model, App, Backbone, ...) {
   ...
}
```
The error is `Module build failed: TypeError: some_model.js: Cannot read property '_generated' of undefined`

#### This works by defining a variable
```
let Models = function(Model, App, Backbone, ...) {
   ...
}
export default Models
```

#### This also works if having some import

```
import SomeController from '../controller';
export default function(Model, App, Backbone, ...) {
   ...
}
```
The above `import` is actually something not needed here. But after adding such declaration the compiling works.

#### Environments
```
   // package.json
    "babel-core": "^6.1.2",
    "babel-loader": "^6.1.0",
    "babel-preset-es2015": "^6.1.2",

   //webpack.config.js
    module: {
      loaders: [
        {
          test: /\.js$/,
          exclude: /(node_modules|bower_components)/,
          loader: 'babel',
          query: {
            cacheDirectory: true,
            presets: ['es2015']
          }
        }
      ]
    },
```
