### ISSUE TITLE
babel-doctor 6.1.1 throws if project uses @scoped npm deps

### ISSUE THREAD

**Issue by jokeyrhyme** [babel/babel#2788]
I just tried out [babel-doctor](http://babeljs.io/blog/2015/11/03/babel-doctor/), very neat. :)

> $ babel --version
> 6.1.1 (babel-core 6.0.20)

I ran it across a few of my projects, and it seems it has a problem when the project depends on [npm @ scoped packages](https://docs.npmjs.com/getting-started/scoped-packages).

> Babel Doctor
> Running sanity checks on your system. This may take a few minutes...
>
> module.js:339
>     throw err;
>     ^
>
> Error: Cannot find module '/path/to/project/node_modules/@scope/package.json'
>     at Function.Module._resolveFilename (module.js:337:15)
>     at Function.Module._load (module.js:287:25)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at Object.<anonymous> (/home/ron/.npm-packages/lib/node_modules/babel-cli/lib/babel-doctor/index.js:86:16)
>     at Module._compile (module.js:425:26)
>     at Object.Module._extensions..js (module.js:432:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:311:12)
>     at Module.require (module.js:366:17)

It seems babel-doctor expects every sub-directory beneath node_modules/ to contain a package.json, which won't be true for scoped packages.

**Comment by jokeyrhyme** [comment]
Just forked and bootstrapped to try to fix this. I don't get this bug anymore in master. `babel-doctor` works as expected.

However, `babel --version` and pretty much any use of the `babel` command results in:

>Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
>    at Function.Module._resolveFilename (module.js:337:15)
>    at Function.Module._load (module.js:287:25)
>    at Module.require (module.js:366:17)
>    at require (module.js:385:17)
>    at Object.<anonymous> (/home/ron/GitHub/babel/packages/babel-traverse/lib/index.js:7:30)
>    at Module._compile (module.js:425:26)
>    at Object.Module._extensions..js (module.js:432:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:311:12)
>    at Module.require (module.js:366:17)

The original purpose of this Issue seems like it has been addressed, so I'll close it now.
