### ISSUE TITLE
babel-doctor chokes on namespaced modules

### ISSUE THREAD

**Issue by qrohlf** [babel/babel#2791]
babel-doctor tries to load a package.json for namespace directories when run in a project with namespaced (private) node modules:

```
Babel Doctor
Running sanity checks on your system. This may take a few minutes...

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/qrohlf/Code/mymodule/node_modules/@mynamespace/package.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/qrohlf/.nvm/versions/node/v4.2.1/lib/node_modules/babel-cli/lib/babel-doctor/index.js:86:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by sebmck** [comment]
Fixed in `master`.
