### ISSUE TITLE
Using class properties gives "TypeError: script.js: Cannot read property 'shadow' of undefined"

### ISSUE THREAD

**Issue by psyrendust** [babel/babel#2800]
## Issue

When trying to transpile a simple class that uses class properties I get the error:

```
TypeError: script.js: Cannot read property 'shadow' of undefined
```

### Full Stack Trace

```shell
larrygordon in ~/dev/westfield/babelBug
○ → npm run start

> babelBug@ start /Users/larrygordon/dev/westfield/babelBug
> babel script.js

TypeError: script.js: Cannot read property 'shadow' of undefined
    at NodePath.has (/Users/larrygordon/dev/westfield/babelBug/node_modules/babel-traverse/lib/path/introspection.js:104:22)
    at /Users/larrygordon/dev/westfield/babelBug/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:134:24
    at NodePath.findParent (/Users/larrygordon/dev/westfield/babelBug/node_modules/babel-traverse/lib/path/ancestry.js:40:9)
    at PluginPass.ThisExpression (/Users/larrygordon/dev/westfield/babelBug/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:133:19)
    at /Users/larrygordon/dev/westfield/babelBug/node_modules/babel-traverse/lib/visitors.js:271:19
    at NodePath._call (/Users/larrygordon/dev/westfield/babelBug/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/larrygordon/dev/westfield/babelBug/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/larrygordon/dev/westfield/babelBug/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/Users/larrygordon/dev/westfield/babelBug/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/larrygordon/dev/westfield/babelBug/node_modules/babel-traverse/lib/context.js:111:19)
```

### Specs:

```
node v4.2.2
npm v3.3.10
```

## Steps to reproduce:

- Copy the 3 files below to your local system
- `npm install`
- `npm run start`

##### Folder Structure

```
.
├── .babelrc
├── node_modules
├── package.json
└── script.js
```

#### package.json

```json
{
  "name": "babelBug",
  "scripts": {
    "start": "babel script.js"
  },
  "dependencies": {
    "babel-cli": "^6.1.1",
    "babel-plugin-transform-class-properties": "^6.0.14",
    "babel-preset-es2015": "^6.0.15",
    "babel-preset-stage-0": "^6.0.15"
  }
}
```

#### .babelrc

```
{
  "presets": [
    "es2015",
    "stage-0"
  ],
  "plugins": [
    "transform-class-properties"
  ]
}
```

#### script.js

```js
class Foo {
  bar = 'bar';
  constructor() {
  }
}
```

**Comment by psyrendust** [comment]
I can get it to build correctly if I change the .babelrc file to this:

```
{
  "presets": [
  ],
  "plugins": [
    "transform-class-properties"
  ]
}
```
