### ISSUE TITLE
async/await functions don't work

### ISSUE THREAD

**Issue by leebenson** [babel/babel#2814]
* node v4.2.1
* babel 6.1.1 (babel-core 6.0.20)

**.babelrc**

```
{
  "presets": [
    "es2015",
    "stage-0"
  ]
}
```

**index.js**

```
async function createPromise() {
  return true;
}

async function doSomething() {
  await createPromise();
  console.log('it worked');
}

doSomething();
```

`babel-node index.js` throws this error:

```
/usr/local/lib/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/regenerator/runtime.js:111
      Object.setPrototypeOf(genFun, GeneratorFunctionPrototype);
             ^
TypeError: Object.setPrototypeOf called on null or undefined
    at Function.setPrototypeOf (native)
    at runtime.mark (/usr/local/lib/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/regenerator/runtime.js:111:14)
    at Array.map (native)
    at index.js:1:29
    at Object.<anonymous> (index.js:3:2)
    at Module._compile (module.js:435:26)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

**Comment by hzoo** [comment]
This looks like https://github.com/babel/babel/issues/2744? Can reopen if you think otherwise

**Comment by leebenson** [comment]
@hzoo sorry, yes - dupe.
