### ISSUE TITLE
Calling function on template string : Converting circular structure to JSON

### ISSUE THREAD

**Issue by roblabla** [babel/babel#2821]
Using babel6, the following file :

```js
`remote add origin`.split(" ")
```

causes the following error : 

```
TypeError: /home/roblabla/Dropbox/dev/src/js/norminette_online/src/test.js: Converting circular structure to JSON
    at Object.stringify (native)
    at CodeGenerator._stringLiteral (/home/roblabla/Dropbox/dev/src/js/norminette_online/node_modules/babel-generator/lib/generators/types.js:138:14)
    at CodeGenerator.MemberExpression (/home/roblabla/Dropbox/dev/src/js/norminette_online/node_modules/babel-generator/lib/generators/expressions.js:245:58)
    at CodeGenerator._print (/home/roblabla/Dropbox/dev/src/js/norminette_online/node_modules/babel-generator/lib/printer.js:140:19)
    at CodeGenerator.print (/home/roblabla/Dropbox/dev/src/js/norminette_online/node_modules/babel-generator/lib/printer.js:88:10)
    at CodeGenerator.CallExpression (/home/roblabla/Dropbox/dev/src/js/norminette_online/node_modules/babel-generator/lib/generators/expressions.js:125:8)
    at CodeGenerator._print (/home/roblabla/Dropbox/dev/src/js/norminette_online/node_modules/babel-generator/lib/printer.js:140:19)
    at CodeGenerator.print (/home/roblabla/Dropbox/dev/src/js/norminette_online/node_modules/babel-generator/lib/printer.js:88:10)
    at CodeGenerator.ExpressionStatement (/home/roblabla/Dropbox/dev/src/js/norminette_online/node_modules/babel-generator/lib/generators/expressions.js:176:8)
    at CodeGenerator._print (/home/roblabla/Dropbox/dev/src/js/norminette_online/node_modules/babel-generator/lib/printer.js:140:19)
```

Presets used : `presets: ["stage-0", "async-to-bluebird", "es2015-node5"]`

**Comment by sebmck** [comment]
I can't reproduce this:

```
$ echo '`remote add origin`.split(" ")' | babel --presets es2015,stage-0
"use strict";

"remote add origin".split(" ");
```

**Comment by roblabla** [comment]
Minimally reproduced by doing

```
npm i --save-dev babel-cli
echo '`remote add origin`.split(" ")' | babel
````

No need for any preset, it seems. I'm running nodejs5, babel-cli 6.1.2.

**Comment by hzoo** [comment]
If you don't have any plugins/presets it wont to transform anything (since it's all opt-in) - but yeah can reproduce with that
