### ISSUE TITLE
SyntaxError when using arrow function inside expression

### ISSUE THREAD

**Issue by jminuscula** [babel/babel#2823]
`(false || () => undefined)` is a valid expression in Babel 5.x, but fails with 6.x with the es2015 preset.

    > var babel = require('babel-core');
    > babel.transform('(false || () => undefined)', {presets: ['es2015']});

    SyntaxError: unknown: Unexpected token (1:11)
    > 1 | (false || () => undefined)
        |            ^
        at Parser.pp.raise (.../node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
        at Parser.pp.unexpected (.../node_modules/babel-core/node_modules/babylon/lib/parser/util.js:91:8)
        at Parser.pp.parseParenAndDistinguishExpression (.../node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:579:12)
        at Parser.pp.parseExprAtom (.../node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:464:19)
        at Parser.pp.parseExprSubscripts (.../node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:260:19)
        at Parser.pp.parseMaybeUnary (.../node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:240:19)
        at Parser.pp.parseExprOp (.../node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:202:42)
        at Parser.pp.parseExprOps (.../node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:175:17)
        at Parser.pp.parseMaybeConditional (.../node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:153:19)
        at Parser.pp.parseMaybeAssign (.../node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:120:19)

Versions: 

    babel@6.0.15
    babel-core@6.0.20
    babel-preset-es2015@6.0.15

**Comment by jminuscula** [comment]
Traceur raises [the same SyntaxError](https://google.github.io/traceur-compiler/demo/repl.html#(false%20%7C%7C%20()%3D%3Eundefiend))

The issue is fixed if the arrow function is wrapped inside parenthesis:

    (false || (() => undefined))

**Comment by nicolo-ribaudo** [comment]
`(false || () => undefined)` isn't a valid JavaScript expression.
On the right side of `||` there can only be a `LogicalANDExpression` (which includes literals, function/class expressions, parenthesized expressions, unary operators and binary operators, except for assignment ones), but an arrow function is an `AssignmentExpression`.

**Comment by jminuscula** [comment]
@nicolo-ribaudo thanks. I must disagree with the spec here though, since `(false || function(){})` is a perfectly valid expression.

I'm leaving the issue open in case the team wants to address the regression for 5.x

**Comment by loganfsmyth** [comment]
You'll see a similar error if you try to run that in Chrome's console. I don't disagree with you that it's unexpected, but Babel's issue queue isn't the right place to bring this up. We have no control over the spec.

**Comment by jmm** [comment]
@nicolo-ribaudo Thanks!

Hello @jminuscula, welcome to the Babel community! @nicolo-ribaudo is correct.

> I must disagree with the spec here though, since `(false || function(){})` is a perfectly valid expression.

`FunctionExpression` is a different syntactic construct than `ArrowFunction` -- they're not interchangeable. Babel follows the standards. You're welcome to take issue with it in the spec, although I think it would be fruitless.

> I'm leaving the issue open in case the team wants to address the regression for 5.x

If it worked in v5 it's a bug fix, not a regression. There were a number of issues with parsing arrow functions in v5.
