### ISSUE TITLE
Error message: 'this' is not allowed before super on babel6

### ISSUE THREAD

**Issue by Ahn1** [babel/babel#2832]
Hello, i get the following error message for my es6/react code:

```
ERROR in ./src/app/components/Mapselector.jsx
Module build failed: SyntaxError: C:/dev/apcdef/src/app/components/Mapselector.jsx: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (C:\dev\georesource\node_modules\babel-core\lib\transformation\file\index.js:409:15)
    at NodePath.buildCodeFrameError (C:\dev\georesource\node_modules\babel-core\node_modules\babel-traverse\lib\path\index.js:143:26)
    at ThisExpression (C:\dev\georesource\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-classes\lib\vanilla.js:73:20)
    at NodePath._call (C:\dev\georesource\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:72:18)
    at NodePath.call (C:\dev\georesource\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:44:17)
    at NodePath.visit (C:\dev\georesource\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:102:12)
    at TraversalContext.visitQueue (C:\dev\georesource\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:151:16)
    at TraversalContext.visitMultiple (C:\dev\georesource\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:106:17)
    at TraversalContext.visit (C:\dev\georesource\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:193:19)
    at Function.traverse.node (C:\dev\georesource\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:139:17)
 @ ./src/app/app.js 7:19-54
```

My problem is... .. i dont use "this" in the class the message says...
The Code of "Mapselector.jsx" looks like:

```
import React from 'react';

export default class Mapselector extends React.Component {
  render () {
    return (
      <div></div>
    )
  }
}
```
It shouldn`t even have other component dependencies.

My app sais:
```
import React from 'react';
import Mapselector from './components/Mapselector';
import ReactDOM from 'react-dom';

main();

function main() {
    ReactDOM.render(<Mapselector />, document.getElementById('app'));
}
```

There shouldn't be anything wrong about that, or am i wrong?

I am using grunt with webpack and:
* babel-core 6.0.20 
* babel-loader 6..0.1)
* babel-preset-react: 6.0.15
* babel-preset-es2015: 6.0.15

And the grunt/webpack config:
```
webpack: {
      default: {
        entry: "./src/app/app.js",
        output: {
          path: './dist',
          filename: 'bundle.js'
        },

        stats: {
          colors: true,
          reasons: true
        },
        progress: true,
        watch: true,
        keepalive: true,
        devtool: 'inline-source-map',
        resolve: {
          extensions: ["", ".webpack.js", ".web.js", ".js", ".es6", ".tag", ".styl", ".jsx"]
        },
        module: {
          loaders: [{
            test: /\.jsx?$/, // A regexp to test the require path. accepts either js or jsx
            loader: 'babel',
            query: {
              presets: ["react", "es2015"]
            }
          }]
        }

      }
    }
```

Does anyone have an idea? I worked with babel5

**Comment by mattstyles** [comment]
if you whack in a constructor and a `super` call (maybe) then it'll probably work. it might be related to the empty (missing) constructor.

There are about 4-5 other issues along a very similar track, I suspect 1 or 2 fixes will close off all of them.

**Comment by Ahn1** [comment]
Oh. Yes you're right..

#2774 and #2809 and #2775 ...
