### ISSUE TITLE
Unknown problems with babel 6

### ISSUE THREAD

**Issue by dangreen** [babel/babel#2835]
The message is absolutely uninformative. I don't know what wrong with code. 

```
/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:520
      throw err;
            ^
Error: /Users/dangreen/github/jam-editor/jam-server/api/services/mail.js: Expected type "Identifier" with option {}
    at Object.t.(anonymous function) [as assertIdentifier] (/Users/dangreen/github/jam-editor/jam-server/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/babel-types/lib/index.js:80:13)
    at PluginPass.exports.visitor.Function.exit (/Users/dangreen/github/jam-editor/jam-server/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/visit.js:78:9)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:271:19
    at NodePath._call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:108:8)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:106:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:193:19)
    at Function.traverse.node (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:106:22)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:111:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:106:22)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:151:16)
```

mail.js
```js
/**
* mail.js
* 
* Business logic for mailing.
* 
*/

export * from './infostruct/mail';

/**
 * Sending actiation link.
 * 
 * @param  {Object} request 
 * @param  {String} to      
 * @param  {String} token 
 * @return {Promise} 
 */
export async function SendActivationLink(request, to, token) {

	var html = await this.renderView("mail/main", {
		title: request.__('Thank you for the registration!'),
		paragraph: request.__('Please activate your account by visiting next page:'),
		link: request.__('Activate account'),
		link_url: `${sails.getBaseurl()}/activate/${encodeURIComponent(token)}`
	});

	return this.sendGridMailer.send({ 
		to, 
		subject: request.__("Account activation"), 
		html: html 
	});
}

/**
 * Sending restore password link.
 * 
 * @param  {Object} request 
 * @param  {String} to      
 * @param  {String} token 
 * @return {Promise} 
 */
export async function SendRestorePasswordLink(request, to, token) {

	var html = await this.renderView("mail/main", {
		title: request.__('We can restore your account!'),
		paragraph: request.__('Please follow the link to restore your account:'),
		link: request.__('Restore account'),
		link_url: `${sails.getBaseurl()}/restore-password/${encodeURIComponent(token)}`
	});

	return this.sendGridMailer.send({ 
		to, 
		subject: request.__("Restore account"), 
		html: html 
	});
}

/**
 * Sending subscription notification.
 * 
 * @param  {Object} request 
 * @param  {String} to      
 * @param  {String} token 
 * @return {Promise} 
 */
export async function SendSubscriptionNotification(request, to) {

	var html = await this.renderView("mail/main", {
		title: request.__('Your subscription is successfully changed!'),
		paragraph: request.__('Please follow the link to view your account:'),
		link: request.__('Open dashboard'),
		link_url: `${sails.getBaseurl()}/dashboard/subscriptions`
	});

	return this.sendGridMailer.send({ 
		to, 
		subject: request.__("Subscription changes"), 
		html: html 
	});
}
```

**Comment by hzoo** [comment]
With 

```
{
    "presets": ["es2015"],
    "plugins": ["transform-async-to-generator"]
}
```

```js
async function hello() {
    await 1;
}
```

```js
var hello = (function () {
    var _marked = [_callee].map(regeneratorRuntime.mark);

    var ref = _asyncToGenerator(function _callee() {
        return regeneratorRuntime.wrap(function _callee$(_context) {
            while (1) switch (_context.prev = _context.next) {
                case 0:
                    _context.next = 2;
                    return 1;

                case 2:
                case "end":
                    return _context.stop();
            }
        }, _marked[0], this);
    });

    return function hello() {
        return ref.apply(this, arguments);
    };
})();

// function _asyncToGenerator(fn) {...}
```

Some folks reported `ReferenceError: Can't find variable: _callee`. I guess it's because _callee is wrapped in _asyncToGenerator so maybe it has to be in that function, not sure?

**Comment by ppascher** [comment]
Not sure if this is related but I had the following problem using async/await with babel 6 and this config:
```
"babel": {
  "presets": [
    "es2015-node5",
    "stage-0"
  ]
}
```
This was working fine by itself:
```javascript
export async function test() {
  await 1;
}
```
It stopped working as soon as I had an import in the same file:
```javascript
import a from 'b';

export async function test() {
  await 1;
}
```
I had to assign the function to a const to get it to work again:
```javascript
import a from 'b';

const test = async function() {
  await 1;
};

export test;
```

**Comment by hzoo** [comment]
Should be fixed by https://github.com/babel/babel/pull/2908
