### ISSUE TITLE
babylon: parse error for arrow-block-IIFE

### ISSUE THREAD

**Issue by benmosher** [babel/babel#2847]
```js
// node 4.2.2 repl
b = require('babylon') // 6.1.2
b.parse('(() => {return foo}())')
SyntaxError: Unexpected token (1:19)
    at Parser.pp.raise (/Users/ben/git/eslint-plugin-import/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/ben/git/eslint-plugin-import/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.expect (/Users/ben/git/eslint-plugin-import/node_modules/babylon/lib/parser/util.js:85:33)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/ben/git/eslint-plugin-import/node_modules/babylon/lib/parser/expression.js:552:12)
    at Parser.pp.parseExprAtom (/Users/ben/git/eslint-plugin-import/node_modules/babylon/lib/parser/expression.js:471:19)
    at Parser.pp.parseExprSubscripts (/Users/ben/git/eslint-plugin-import/node_modules/babylon/lib/parser/expression.js:267:19)
    at Parser.pp.parseMaybeUnary (/Users/ben/git/eslint-plugin-import/node_modules/babylon/lib/parser/expression.js:247:19)
    at Parser.pp.parseExprOps (/Users/ben/git/eslint-plugin-import/node_modules/babylon/lib/parser/expression.js:178:19)
    at Parser.pp.parseMaybeConditional (/Users/ben/git/eslint-plugin-import/node_modules/babylon/lib/parser/expression.js:160:19)
    at Parser.pp.parseMaybeAssign (/Users/ben/git/eslint-plugin-import/node_modules/babylon/lib/parser/expression.js:123:19)
```
but with Babel (5.x):
```
$echo "(() => {return foo}())" | $(npm bin)/babel
"use strict";

(function () {
  return foo;
})();
```

Both `(() => foo)()` and `(() => { return foo })()` parse fine.

Is `(() => { return foo }())` invalid syntax? Seems to be analogous to `(function () { return foo }())` which also parses fine.

**Comment by jmm** [comment]
Yes, it's invalid. It was a bug in v5. See https://github.com/babel/babel/issues/2118. `FunctionExpression` and `ArrowFunction` are not interchangeable, even if analagous.

**Comment by benmosher** [comment]
Ah, got it. Thanks!
