### ISSUE TITLE
The plugin "syntax-async-functions" didn't export a Plugin instance

### ISSUE THREAD

**Issue by reggi** [babel/babel#2856]
Trying to use `babel-plugin-syntax-async-functions` and I'm getting a strange error:

Here's the versions

* "babel-cli": "^6.1.2",
* "babel-plugin-syntax-async-functions": "^6.0.14"

```
thomas@workstation:esnext-bootstrap$ npm run babel-node-watch

> @ babel-node-watch /Users/thomas/Desktop/esnext-bootstrap
> babel ./src --out-dir ./lib --watch

TypeError: The plugin "syntax-async-functions" didn't export a Plugin instance
    at PluginManager.validate (/Users/thomas/.nvm/versions/node/v4.2.1/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/thomas/.nvm/versions/node/v4.2.1/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/thomas/.nvm/versions/node/v4.2.1/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/thomas/.nvm/versions/node/v4.2.1/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/thomas/.nvm/versions/node/v4.2.1/lib/node_modules/babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.exports.transform (/Users/thomas/.nvm/versions/node/v4.2.1/lib/node_modules/babel/lib/babel/util.js:40:22)
    at Object.exports.compile (/Users/thomas/.nvm/versions/node/v4.2.1/lib/node_modules/babel/lib/babel/util.js:49:20)
    at write (/Users/thomas/.nvm/versions/node/v4.2.1/lib/node_modules/babel/lib/babel/dir.js:19:21)
    at handleFile (/Users/thomas/.nvm/versions/node/v4.2.1/lib/node_modules/babel/lib/babel/dir.js:40:7)
    at /Users/thomas/.nvm/versions/node/v4.2.1/lib/node_modules/babel/lib/babel/dir.js:56:9
```

**Comment by hzoo** [comment]
It looks like babel is being caled from `babel` not `babel-cli` `.nvm/versions/node/v4.2.1/lib/node_modules/babel/node_modules/babel-core` so it's probably babel 5?

**Comment by reggi** [comment]
I updated the global as well as the local solved this problem. Still can't get the `await` keyword to work tho.

**Comment by hzoo** [comment]
If you need to transform async/await then you need to include the transform plugin (I will update the docs) - the syntax plugin only parses async/await (also the transform plugin includes the syntax plugin). You probably need regenerator or the other transform http://babeljs.io/docs/plugins/ depending on what you want.

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.
