### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by reggi** [babel/babel#2857]
Trying to get async / await to work, ran into this issue:

Error

```
ReferenceError: regeneratorRuntime is not defined
    at helloWorld (/Users/thomas/Desktop/esnext-bootstrap/lib/shux.js:21:10)
    at Object.<anonymous> (/Users/thomas/Desktop/esnext-bootstrap/lib/shux.js:39:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

.babelrc

```
{
  "plugins": ["transform-regenerator", "syntax-async-functions"],
  "presets": ["es2015"]
}
```

src:

```
import csv from 'csv'
import Promise from 'bluebird'
Promise.promisifyAll(csv)

let input = [{
  'name': 'thomas'
}]

async function helloWorld () {
  let value = await csv.stringifyAsync(input)
  console.log(value)
}

helloWorld()
```

bundle:

```js
'use strict';

var _csv = require('csv');

var _csv2 = _interopRequireDefault(_csv);

var _bluebird = require('bluebird');

var _bluebird2 = _interopRequireDefault(_bluebird);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

_bluebird2.default.promisifyAll(_csv2.default);

var input = [{
  'name': 'thomas'
}];

function helloWorld() {
  var value;
  return regeneratorRuntime.async(function helloWorld$(_context) {
    while (1) switch (_context.prev = _context.next) {
      case 0:
        _context.next = 2;
        return regeneratorRuntime.awrap(_csv2.default.stringifyAsync(input));

      case 2:
        value = _context.sent;

        console.log(value);

      case 4:
      case 'end':
        return _context.stop();
    }
  }, null, this);
}

helloWorld();
```

**Comment by reggi** [comment]
Is there a reason `regeneratorRuntime` isn't defined by some boilerplate?

**Comment by hzoo** [comment]
Looks like the same as https://github.com/babel/babel/issues/2825 so going to close

**Comment by reggi** [comment]
Thanks for pointing me in that direction @hzoo
