### ISSUE TITLE
Babel6: SourceMap generation problem

### ISSUE THREAD

**Issue by KnisterPeter** [babel/babel#2864]
Hi,

I cannot run babel 6 with source-map support. The following error is thrown:

```
Error: temp/cli.js: Invalid mapping: {"generated":{"line":null,"column":null,"lastColumn":null},"source":"cli.js","original":{"line":3,"column":7},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/node_modules/source-map/lib/source-map/source-map-generator.js:275:15)
    at SourceMapGenerator_addMapping [as addMapping] (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/node_modules/source-map/lib/source-map/source-map-generator.js:105:14)
    at /home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:442:27
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/node_modules/source-map/lib/source-map/source-map-consumer.js:159:16)
    at /home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:441:26
    at File.mergeSourceMap (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:463:9)
    at File.generate (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:661:25)
    at File.transform (/home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:504:17)
    at /home/markusw/source/ankara/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:46:19
```

**Comment by johnnyreilly** [comment]
I've just experienced what looks to be the same problem.

I've a project which uses both ts-loader and babel-loader with Webpack.  Code is written in ES6 TypeScript and uses Babel to do transpilation to ES-old.  This worked beautifully with Babel 5 but seems to have died a death now I've ported to Babel 6.

I get this error:

```
ERROR in ./src/main.tsx
Module build failed: Error: E:/source/TypeScript-ES6-Babel-React-Flux-Karma/node_modules/ts-loader/index.js!E:/source/TypeScript-ES6-Babel-React-Flux-Karma/src/main.tsx: Invalid mapping: {"generated":{"line":null,"column":null,"lastColumn":null},"source":"E:\\source\\TypeScript-ES6-Babel-React-Flux-Karma\\src\\main.tsx","original":{"line":1,"column":7},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\node_modules\source-map\lib\source-map\source-map-generator.js:275:15)
    at SourceMapGenerator_addMapping [as addMapping] (E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\node_modules\source-map\lib\source-map\source-map-generator.js:105:14)
    at E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\lib\transformation\file\index.js:442:27
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\node_modules\source-map\lib\source-map\source-map-consumer.js:159:16)
    at E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\lib\transformation\file\index.js:441:26
    at File.mergeSourceMap (E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\lib\transformation\file\index.js:463:9)
    at File.generate (E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\lib\transformation\file\index.js:661:25)
    at File.transform (E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\lib\transformation\file\index.js:504:17)
    at E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\lib\transformation\pipeline.js:46:19
    at File.wrap (E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\lib\transformation\file\index.js:514:16)
    at Pipeline.transform (E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-core\lib\transformation\pipeline.js:43:17)
    at transpile (E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-loader\index.js:12:22)
    at Object.module.exports (E:\source\TypeScript-ES6-Babel-React-Flux-Karma\node_modules\babel-loader\index.js:69:12)
```

You can reproduce the problem by taking a look at this repo: https://github.com/johnnyreilly/TypeScript-ES6-Babel-React-Flux-Karma

Follow the instructions in the README.md to get up and running (pretty simple to do)

**Comment by KnisterPeter** [comment]
I use the same setup but with the cli versions of tsc and babel (no webpack).

**Comment by loganfsmyth** [comment]
@zertosh Could this be an issue from the source-map upgrade?

**Comment by zertosh** [comment]
@loganfsmyth maybe? The only substantive change from 0.4.x to 0.5.x was the removal of the AMD wrapper helper. However, it seems that in 0.5.1 a bug fix might've introduced this problem (https://github.com/mozilla/source-map/compare/09b95c1...3d8b134). I'm trying to repro with @johnnyreilly's repo.

**Comment by zertosh** [comment]
I tried source-map@0.4.4 and source-map@0.5.0 with @johnnyreilly's repo and both versions throw the same error. Unless there's something caching going on in his repro case, the source-map update can be ruled out.

@johnnyreilly, if you can come up with a simpler test case, I can try to dig into it further. Hopefully something that uses babel-core and the typescript compiler directly.

**Comment by KnisterPeter** [comment]
You could use https://github.com/KnisterPeter/ankara/tree/babel6 for testing this. It may not be simpler, but it uses tsc and babel directly.
Unfortunately I did not managed to compile a single file from the cli with tsc and inline-sourcemaps. There is no option for it, but the project contains a tsconfig.json file which defines the inlining of sourcemaps. The tsc step did succeed and places all outputs in the temp folder of the project. Then babel will fail when compiling e.g. the temp/cli.js file with sourcemaps.

As simple case use `npm test`. This will fail and running a plain `./node_modules/.bin/babel --source-maps=inline --out-dir dist temp/cli.js` on a file will also fail. This might be a good hint into the problem.

**Comment by zertosh** [comment]
@KnisterPeter, thanks for that. I tried yours too with source-map@0.4.4 and source-map@0.5.0, and it's still breaking. Maybe the problem is with TS?

**Comment by KnisterPeter** [comment]
@zertosh, thats possible, but with babel5 it did work well. Maybe babel6 is more strict with source-maps?

**Comment by johnnyreilly** [comment]
In case it helps you can see an example of the (working) Babel 5 version: 

https://github.com/Microsoft/TypeScriptSamples/tree/master/es6-babel-react-flux-karma

Also, @jbrantly do you have any insights on this?

**Comment by johnnyreilly** [comment]
By the way, the difference between the 2 repos (the TypeScriptSamples one and the Babel 6 one) is marginal. The Babel 6 one is just the TypeScriptSamples repo upgraded to use Babel 6.

**Comment by johnnyreilly** [comment]
@zertosh I've created a more cutdown version of the problem - it's without react in the frame and down to a single file of source code (`main.ts`): 

https://github.com/johnnyreilly/TypeScript-Babel-6-Problems

I'm afraid it's still a webpack example as that's my workflow.  Perhaps @KnisterPeter could provide an simple example of his setup if that would help (it sounds like his approach is more bare bones)

**Comment by jbrantly** [comment]
I don't have a lot to add other than sourcemaps were recently tweaked based on #2522. No idea if it's related.

**Comment by johnnyreilly** [comment]
Thanks @jbrantly

**Comment by zertosh** [comment]
Here is a minimal repro case: https://gist.github.com/zertosh/3234ea9fd2c6f269fc46.

It's not a TS issue, but rather with merging source maps when the original file begins with a comment. The repro case shows this with TS and shows it with a generated source map.

I'm afraid though, that I can't look into this more this weekend.

**Comment by KnisterPeter** [comment]
In that case its not only a comment but could also be a shebang (this is the fact in my case).

**Comment by johnnyreilly** [comment]
Thanks for identifying the issue @zertosh

**Comment by dfahlander** [comment]
Getting same problem when inputing a sourceMap generated by rollup.
