### ISSUE TITLE
Plugins cannot be found via CLI's --plugin option.

### ISSUE THREAD

**Issue by yuri-kilochek** [babel/babel#2903]
I've got

    > npm list -g --depth=0
    /usr/lib
    ├── babel-cli@6.1.2
    ├── babel-core@6.1.2
    ├── babel-plugin-transform-strict-mode@6.1.2
    └── npm@3.3.4

and when I attempt to

   > echo "let x = 1;" | babel --plugins transform-strict-mode

i get

    ReferenceError: Unknown plugin "transform-strict-mode" specified in "base" at 0
       at /usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
       at Array.map (native)
       at Function.normalisePlugins (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:20)
       at OptionManager.mergeOptions (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:254:36)
       at OptionManager.init (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:10)
       at File.initOptions (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:191:75)
       at new File (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:122:22)
       at Pipeline.transform (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
       at Object.transform (/usr/lib/node_modules/babel-cli/lib/babel/util.js:53:22)
       at Socket.<anonymous> (/usr/lib/node_modules/babel-cli/lib/babel/file.js:101:25)

This happens for all plugins I tried, for different naming schemes (e.g. without "transform-" prefix, or with "babel-plugin-" prefix, or both).

**Comment by hzoo** [comment]
It's probably because you are using the plugins globally `-g` - it should work if you do it in our local node_modules

**Comment by sebmck** [comment]
Basically what @hzoo said. This isn't a problem we can fix in Babel core as we just use nodes `require`. Feel free to use one of the resources in the [README](https://github.com/babel/babel#looking-for-support) if you need any further assistance and support.
