### ISSUE TITLE
Visitor with exit method errors

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2906]
The following plugin:

```js
export default function({ types: t }) {
  return {
    visitor: {
      exit() {}
    }
  };
};
```

Will throw this error: 

```js
TypeError: index.js: [object Object] is not iterable!
    at TypeError (native)
    at module.exports.require.getIterator (/Users/thejameskyle/Projects/Tests/__babel-bug-exit/node_modules/core-js/library/modules/core.get-iterator.js:5:40)
    at NodePath._call (/Users/thejameskyle/Projects/Tests/__babel-bug-exit/node_modules/babel-traverse/lib/path/context.js:53:109)
    at NodePath.call (/Users/thejameskyle/Projects/Tests/__babel-bug-exit/node_modules/babel-traverse/lib/path/context.js:40:14)
    at NodePath.visit (/Users/thejameskyle/Projects/Tests/__babel-bug-exit/node_modules/babel-traverse/lib/path/context.js:108:8)
    at TraversalContext.visitQueue (/Users/thejameskyle/Projects/Tests/__babel-bug-exit/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/thejameskyle/Projects/Tests/__babel-bug-exit/node_modules/babel-traverse/lib/context.js:111:19)
    at TraversalContext.visit (/Users/thejameskyle/Projects/Tests/__babel-bug-exit/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/thejameskyle/Projects/Tests/__babel-bug-exit/node_modules/babel-traverse/lib/index.js:139:17)
    at NodePath.visit (/Users/thejameskyle/Projects/Tests/__babel-bug-exit/node_modules/babel-traverse/lib/path/context.js:106:22)
```

Example repo: https://github.com/thejameskyle/__babel-bug-exit

**Comment by amasad** [comment]
What's expected here?

**Comment by thejameskyle** [comment]
`exit()` is an alias to `Node: { exit() {} }` which visits all nodes on exit.

**Comment by sebmck** [comment]
This happens when you have an `enter` visitor method too. I'm going to make this illegal since when you have an `enter` or `exit` visitor we can't do optimisations on nodes with no children. We have a specific optimisation that doesn't construct/retrieve a node path for those types of nodes since they'll never be used but with a global `enter`/`exit` we can't do that.

**Comment by thejameskyle** [comment]
Can we add that to the 6.0 changelog? Because this was one of the things that came up when trying to upgrade a plugin to 6.0

**Comment by sebmck** [comment]
done

On Sun, Nov 8, 2015 at 3:02 PM, James Kyle <notifications@github.com> wrote:

> Can we add that to the 6.0 changelog? Because this was one of the things
> that came up when trying to upgrade a plugin to 6.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/2906#issuecomment-154884348>.
>



-- 
Sebastian McKenzie
