### ISSUE TITLE
`transform-es2015-block-scoping` prints `We found a path that isn't a NodePath instance`

### ISSUE THREAD

**Issue by tellnes** [babel/babel#2913]
script.js
```js
while (true) {
  let foo = 'foo'
  fn(() => foo)
}
```

Command:
```shell
$ babel --plugins transform-es2015-block-scoping script.js
```

Output:
```
Error: script.js: We found a path that isn't a NodePath instance
    at Function.get (node_modules/babel-traverse/lib/path/index.js:103:13)
    at TraversalContext.create (node_modules/babel-traverse/lib/context.js:73:30)
    at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:102:25)
    at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:193:19)
    at Function.traverse.node (node_modules/babel-traverse/lib/index.js:139:17)
    at traverse (node_modules/babel-traverse/lib/index.js:61:12)
    at Function.traverse.hasType (node_modules/babel-traverse/lib/index.js:188:3)
    at BlockScoping.wrapClosure (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:491:47)
    at BlockScoping.run (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:383:12)
    at PluginPass.Loop (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:89:36)
```

Additional:
```shell
$ babel --version
6.0.14 (babel-core 6.0.14)

$ cat node_modules/babel-plugin-transform-es2015-block-scoping/package.json | jq .version
"6.0.14"
```

**Comment by hzoo** [comment]
Looks similar to https://github.com/babel/babel/issues/2644.

If you aren't using npm 3, can you try using that? (I can't reproduce with npm 3)

**Comment by tellnes** [comment]
Yes, It seems like an reinstall with npm 3 fixed it.

**Comment by tellnes** [comment]
But I'm having some other problems with npm 3, which keeps me on npm 2 for now.

Are you saying that you don't support npm 2?

**Comment by hzoo** [comment]
It should still work with npm 2 - I mentioned above that the https://github.com/babel/babel/commit/24f5ef50b041a8659c904f0e8bdf88d5d0d77448 fix was for a version higher than what you were using (6.0.14)

**Comment by tellnes** [comment]
Ah, thanks. I did read your post a little bit to fast.
