### ISSUE TITLE
make test Error: Cannot find module 'babel-runtime/helpers/interop-require-default'

### ISSUE THREAD

**Issue by SystemParadox** [babel/babel#2916]
Hi. I am currently unable to run the tests. `make test` produces the following:

```
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/simon/babel/packages/babylon/lib/index.js:5:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/simon/babel/packages/babylon/test/index.js:2:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/simon/babel/node_modules/mocha/lib/mocha.js:187:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/simon/babel/node_modules/mocha/lib/mocha.js:184:14)
    at Mocha.run (/home/simon/babel/node_modules/mocha/lib/mocha.js:405:31)
    at Object.<anonymous> (/home/simon/babel/node_modules/mocha/bin/_mocha:405:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

I suspect I am missing a step somewhere.

I note that there is an empty file `doc/api/node-path.md`. Do I need to add the `packages` directory to my `NODE_PATH`? I have tried this but strangely it hasn't changed anything. Maybe I should be using `npm link` instead?

Thanks.

**Comment by SystemParadox** [comment]
It seems that `babel-runtime/helpers/interop-require-default` does not exist. Are the test scripts out of date or something?

**Comment by sebmck** [comment]
See the [README](https://github.com/babel/babel#looking-for-support) and [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md). You probably forgot to run `make bootstrap`.

**Comment by SystemParadox** [comment]
Ah that's it. I did find that file, but didn't see the bootstrap part. Thanks.
