### ISSUE TITLE
require(...) is not a function in babel-plugin-transform-react-jsx

### ISSUE THREAD

**Issue by elierotenberg** [babel/babel#2917]
I get the following error when attempting to use `babel-plugin-transform-react-jsx`:

```
var visitor = require("babel-helper-builder-react-jsx")({
                                                         ^
TypeError: require(...) is not a function
    at exports.default (h:\gh\lib-starterkit\node_modules\babel-plugin-transform-react-jsx\lib\index.js:12:58)
    at Function.memoisePluginContainer (h:\gh\lib-starterkit\node_modules\babel-core\lib\transformation\file\options\option-manager.js:117:13)
    at Function.normalisePlugin (h:\gh\lib-starterkit\node_modules\babel-core\lib\transformation\file\options\option-manager.js:149:32)
    at h:\gh\lib-starterkit\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (h:\gh\lib-starterkit\node_modules\babel-core\lib\transformation\file\options\option-manager.js:161:20)
    at OptionManager.mergeOptions (h:\gh\lib-starterkit\node_modules\babel-core\lib\transformation\file\options\option-manager.js:254:36)
    at OptionManager.mergePresets (h:\gh\lib-starterkit\node_modules\babel-core\lib\transformation\file\options\option-manager.js:308:16)
    at OptionManager.mergeOptions (h:\gh\lib-starterkit\node_modules\babel-core\lib\transformation\file\options\option-manager.js:270:12)
    at compile (h:\gh\lib-starterkit\node_modules\babel-core\lib\api\register\node.js:95:15)
```

For the record, I'm using the require hook in:
- Windows 10
- `node` v5.0.0 64bits
- `npm` v3.3.6
- `babel-core` v 6.1.2
- `babel-plugin-transform-react-jsx` v6.0.18

**Comment by elierotenberg** [comment]
This appears to be related with the `only` option, whenener `only` is present (whatever its value other than `null`), this error is thrown.

**Comment by sebmck** [comment]
It's caused by a circular dependency where you've got `babel-register` enabled and it's trying to transform the plugin with itself. Make your `only` option more strict so it doesn't include any Babel core files. If you need any further help or assistance please don't hesitate to use one of the resources located in the [README](https://github.com/babel/babel#looking-for-support). Thanks!
