### ISSUE TITLE
export default function w/ typeof x === 'function' errors

### ISSUE THREAD

**Issue by cjohansen** [babel/babel#2928]
**Input:**

```js
export default function() {
  typeof foo === 'function';
}
```

**Stack trace:**

```sh
TypeError: index.js: Cannot read property '_generated' of undefined
    at /Users/thejameskyle/Projects/Tests/__babel-bug-2928/node_modules/babel-plugin-transform-es2015-typeof-symbol/lib/index.js:20:29
    at NodePath.find (/Users/thejameskyle/Projects/Tests/__babel-bug-2928/node_modules/babel-traverse/lib/path/ancestry.js:52:9)
    at PluginPass.UnaryExpression (/Users/thejameskyle/Projects/Tests/__babel-bug-2928/node_modules/babel-plugin-transform-es2015-typeof-symbol/lib/index.js:19:18)
    at /Users/thejameskyle/Projects/Tests/__babel-bug-2928/node_modules/babel-traverse/lib/visitors.js:271:19
    at NodePath._call (/Users/thejameskyle/Projects/Tests/__babel-bug-2928/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/thejameskyle/Projects/Tests/__babel-bug-2928/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/thejameskyle/Projects/Tests/__babel-bug-2928/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/Users/thejameskyle/Projects/Tests/__babel-bug-2928/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/thejameskyle/Projects/Tests/__babel-bug-2928/node_modules/babel-traverse/lib/context.js:111:19)
    at TraversalContext.visit (/Users/thejameskyle/Projects/Tests/__babel-bug-2928/node_modules/babel-traverse/lib/context.js:195:19)
```

~~If I remove the import, it does not crash. However, it does not matter what the import is, it crashes anyway. Also, adding the statement `typeof doit;` inside the function before the comparison causes it not to crash. Adding another statement, like `console.log('Hah')` causes it to crash.~~

Note from @thejameskyle: You don't need the import for it to crash, but you do need the `export default` and `typeof x === "string"`.

**Comment by thejameskyle** [comment]
Example repo: https://github.com/thejameskyle/__babel-bug-2928

Updated to full stack trace above

**Comment by hzoo** [comment]
This looks like the same as https://github.com/babel/babel/issues/2865 which I fixed in master

**Comment by sebmck** [comment]
Yup.
