### ISSUE TITLE
export default anonymous class

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel#2941]
**Input:**

```js
export default class {}
```

**Stack Trace:**

```js
TypeError: index.js: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got null
    at Object.validate (/.../node_modules/babel-types/lib/definitions/index.js:99:13)
    at validate (/.../node_modules/babel-types/lib/index.js:295:9)
    at Object.builder (/.../node_modules/babel-types/lib/index.js:248:7)
    at PluginPass.ClassDeclaration (/.../node_modules/babel-plugin-transform-es2015-classes/lib/index.js:33:58)
    at /.../node_modules/babel-traverse/lib/visitors.js:271:19
    at NodePath._call (/.../node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/.../node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/.../node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/.../node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/.../node_modules/babel-traverse/lib/context.js:111:19)
```

Example repo: https://github.com/thejameskyle/__babel-bug-export-default-anonymous-class

**Comment by sebmck** [comment]
Already fixed in `master`, I think by @hzoo. I've added a regression test anyway.
