### ISSUE TITLE
Is there any way to try async/await feature? I get  Expected type "Identifier" with option {}

### ISSUE THREAD

**Issue by carlosdubus** [babel/babel#2946]
.babelrc
```
{
  "presets": ["es2015","stage-0"],
  "plugins": []
}
```

src/test.js
```
function request(){
	return new Promise(function(resolve, reject){
		resolve("yo!");
	});
}
async function test() {
    var r = await request();
    console.log(r);
}

test();
```

```
$ babel src -d build
Error: src/test.js: Expected type "Identifier" with option {}
    at Object.t.(anonymous function) [as assertIdentifier] (/home/carlos/work/babel/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/babel-types/lib/index.js:80:13)
    at PluginPass.exports.visitor.Function.exit (/home/carlos/work/babel/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/visit.js:78:9)
    at /home/carlos/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:271:19
    at NodePath._call (/home/carlos/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/home/carlos/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/home/carlos/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:108:8)
    at TraversalContext.visitQueue (/home/carlos/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitMultiple (/home/carlos/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:106:17)
    at TraversalContext.visit (/home/carlos/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/context.js:193:19)
    at Function.traverse.node (/home/carlos/.nvm/versions/node/v5.0.0/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/index.js:139:17)
```

```
$ babel --version
6.1.2 (babel-core 6.1.2)
$ node --version
v5.0.0
```

Thanks!

**Comment by hzoo** [comment]
I think this is the same as https://github.com/babel/babel/issues/2835, https://github.com/babel/babel/issues/2896

**Comment by carlosdubus** [comment]
Can you help me to build babel from master? I pulled master and then run make. How do I run the cli? Thanks

**Comment by jmm** [comment]
@carlosdubus Have you looked at CONTRIBUTING? You should be able to `make bootstrap`, then `npm link babel-cli` where you want to run it.

**Comment by rightaway** [comment]
The referenced issues are closed, does it mean it will be fixed in the upcoming release?

**Comment by hzoo** [comment]
Yes and the closed issues should link to the pr that fixes the issue

**Comment by carlosdubus** [comment]
@jmm make bootstrap throws 'Cannot find module '/home/carlos/work/babel/babel/packages/babel-plugin-transform-runtime'

Do I need to npm install it?

**Comment by thejameskyle** [comment]
@carlosdubus Please get help in the Slack: http://slack.babeljs.io/
