### ISSUE TITLE
Unknown option: presets

### ISSUE THREAD

**Issue by legomind** [babel/babel#2949]
This .babelrc

```json
{
  "presets": ["es2015"]
}

```

Produces this error:
```
ReferenceError: [BABEL] src/server/index.js: Unknown option: /Users/coryt/projects/my-project/src/server/.babelrc.presets
```

With these packages

```json
{
  "babel-core": "^6.1.2",
  "babel-preset-es2015": "^6.1.2",
  "..."

}
```

**Comment by hzoo** [comment]
If you are running `babel` then maybe its using the global babel which is still on 5.x

**Comment by sebmck** [comment]
There's not enough information here. What integration are you using? What commands and complete config are you using?

This is probably just you using 5.x with a 6.x config.

**Comment by jdhiro** [comment]
I'm in the same boat. I'm using babel@6 with babel-loader (webpack) I've updated all my dependencies to @6 versions, both in the project and globally. In webpack I'm using a config like this:

```
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel',
        query: {
          'presets': ['es2015']
        }
      }
    ]
  }
```

But I get an error about presets being an unknown option:

```
ERROR in ../js-pimaps/src/pi-map.js
Module build failed: ReferenceError: [BABEL] /Users/jason/dev/pi/js-pimaps/src/pi-map.js: Unknown option: direct.presets
    at Logger.error (/Users/jason/dev/pi/js-pimaps/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/jason/dev/pi/js-pimaps/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.init (/Users/jason/dev/pi/js-pimaps/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:10)
    at File.initOptions (/Users/jason/dev/pi/js-pimaps/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/jason/dev/pi/js-pimaps/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/jason/dev/pi/js-pimaps/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/jason/dev/pi/js-pimaps/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/jason/dev/pi/js-pimaps/node_modules/babel-loader/index.js:69:12)
 @ ../js-pimaps/src/index.js 8:13-32
```

**Comment by legomind** [comment]
@hzoo @sebmck Indeed, it appears that the latest babel-cli is still using v5

```
npm install babel-cli@latest -g
/Users/coryt/.nodenv/versions/4.2.1/bin/babel-node -> /Users/coryt/.nodenv/versions/4.2.1/lib/node_modules/babel-cli/bin/babel-node.js
/Users/coryt/.nodenv/versions/4.2.1/bin/babel -> /Users/coryt/.nodenv/versions/4.2.1/lib/node_modules/babel-cli/bin/babel.js
/Users/coryt/.nodenv/versions/4.2.1/bin/babel-external-helpers -> /Users/coryt/.nodenv/versions/4.2.1/lib/node_modules/babel-cli/bin/babel-external-helpers.js
/Users/coryt/.nodenv/versions/4.2.1/bin/babel-doctor -> /Users/coryt/.nodenv/versions/4.2.1/lib/node_modules/babel-cli/bin/babel-doctor.js
/Users/coryt/.nodenv/versions/4.2.1/lib
└─┬ babel-cli@6.1.2
  ├─┬ babel-polyfill@6.0.16
  │ └── core-js@1.2.6
  └─┬ chokidar@1.2.0
    └─┬ anymatch@1.3.0
      └─┬ micromatch@2.3.1
        ├── normalize-path@2.0.0
        └─┬ object.omit@2.0.0
          └── is-extendable@0.1.1

babel -V                                                                                                 
>> 5.8.23 (babel-core 5.8.25)
```

Is there no way to run the compiler from the command line yet?

**Comment by jdhiro** [comment]
@legomind you can just do an `npm -g install babel-cli@6` (I still get the error though)

**Comment by sebmck** [comment]
Your npm installs are messed up. I can tell by the stack trace that it's 5.x. You've probably installed `babel` globally and it's using that. Try running `npm uninstall -g babel`.

I'm locking this since it isn't a bug, feel free to use one of the resources in the README if you need support:

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>. The Babel issue tracker is <strong>exclusively</strong> for bug reports and feature requests.

Thanks! :blush:
