### ISSUE TITLE
Failed to import `babel-preset-es2015` when installed as an `npm` nested dependency

### ISSUE THREAD

**Issue by n-riesco** [babel/babel#2974]
Below are the steps to reproduce the issue on Ubuntu:

```
$ mkdir test
$ cd test
$ echo {} > package.json 
$ npm install babel-core babel-preset-es2015
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
babel-core@6.1.2 node_modules/babel-core
├── slash@1.0.0
├── shebang-regex@1.0.0
├── path-exists@1.0.0
├── path-is-absolute@1.0.0
├── babel-messages@6.0.15
├── babel-template@6.0.16
├── babel-helpers@6.1.2
├── private@0.1.6
├── esutils@2.0.2
├── convert-source-map@1.1.1
├── home-or-tmp@1.0.0 (os-tmpdir@1.0.1, user-home@1.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── babel-types@6.1.2 (to-fast-properties@1.0.1)
├── babylon@6.1.2
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── source-map@0.4.4 (amdefine@1.0.0)
├── babel-code-frame@6.0.15 (js-tokens@1.0.2, line-numbers@0.2.0, repeating@1.1.3, chalk@1.1.1)
├── babel-generator@6.1.2 (trim-right@1.0.1, repeating@1.1.3, detect-indent@3.0.1, is-integer@1.0.6)
├── babel-traverse@6.1.2 (globals@8.11.0, repeating@1.1.3, invariant@2.1.2)
├── source-map-support@0.2.10 (source-map@0.1.32)
├── json5@0.4.0
├── lodash@3.10.1
├── babel-runtime@5.8.29 (core-js@1.2.6)
└── regenerator@0.8.35 (through@2.3.8, recast@0.10.24, esprima-fb@15001.1.0-dev-harmony-fb, commoner@0.10.4, defs@1.1.1)

babel-preset-es2015@6.1.2 node_modules/babel-preset-es2015
├── babel-plugin-transform-es2015-literals@6.0.18 (babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-block-scoping@6.0.18 (babel-template@6.0.16, babel-types@6.1.2, lodash@3.10.1, babel-traverse@6.1.2, babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-object-super@6.0.14 (babel-runtime@5.8.29, babel-helper-replace-supers@6.0.18)
├── babel-plugin-transform-es2015-function-name@6.0.14 (babel-runtime@5.8.29, babel-types@6.1.2, babel-helper-function-name@6.0.15)
├── babel-plugin-transform-es2015-computed-properties@6.0.14 (babel-template@6.0.16, babel-runtime@5.8.29, babel-helper-define-map@6.0.15)
├── babel-plugin-transform-es2015-unicode-regex@6.0.18 (regexpu@1.3.0, babel-helper-regex@6.0.18, babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-modules-commonjs@6.1.3 (babel-plugin-transform-strict-mode@6.1.2, babel-template@6.0.16, babel-types@6.1.2, babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-parameters@6.0.18 (babel-helper-get-function-arity@6.0.15, babel-helper-call-delegate@6.0.15, babel-types@6.1.2, babel-runtime@5.8.29, babel-template@6.0.16, babel-traverse@6.1.2)
├── babel-plugin-transform-es2015-destructuring@6.0.18 (babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-classes@6.1.2 (babel-helper-optimise-call-expression@6.0.15, babel-messages@6.0.15, babel-helper-replace-supers@6.0.18, babel-helper-function-name@6.0.15, babel-template@6.0.16, babel-types@6.1.2, babel-runtime@5.8.29, babel-helper-define-map@6.0.15, babel-traverse@6.1.2)
├── babel-plugin-transform-es2015-sticky-regex@6.0.18 (babel-helper-regex@6.0.18, babel-types@6.1.2, babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-constants@6.0.15 (babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-for-of@6.0.14 (babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-spread@6.0.14 (babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-shorthand-properties@6.0.14 (babel-types@6.1.2, babel-runtime@5.8.29)
├── babel-plugin-transform-regenerator@6.0.18 (through@2.3.8, private@0.1.6, commoner@0.10.4, babel-traverse@6.1.2, babel-types@6.1.2, babel-plugin-syntax-async-functions@6.0.14, babylon@6.1.2)
├── babel-plugin-transform-es2015-typeof-symbol@6.1.2 (babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-block-scoped-functions@6.0.14 (babel-runtime@5.8.29)
├── babel-plugin-transform-es2015-template-literals@6.0.14 (babel-runtime@5.8.29)
└── babel-plugin-transform-es2015-arrow-functions@6.0.14 (babel-runtime@5.8.29)
$ node
> process.chdir("..");
undefined
> var transform = require("babel-core").transform;
undefined
> transform("'Hi!'", {presets: ["es2015"]}).code;
Error: Couldn't find preset "es2015"
    at OptionManager.mergePresets (/home/user/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:310:17)
    at OptionManager.mergeOptions (/home/user/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:12)
    at OptionManager.init (/home/user/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:10)
    at File.initOptions (/home/user/test/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/home/user/test/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/home/user/test/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at repl:1:1
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
> 

```

Issue #2703 may be related.

**Comment by sebmck** [comment]
This is expected behaviour. You haven't specified a `filename` so it has no idea where to resolve presets and plugins from so it just uses the cwd.

**Comment by n-riesco** [comment]
It also happens when I transform a file. See below:

```
$ echo "'Hi';" > test.js
$ mkdir test
$ cd test
$ echo {} > package.json
$ npm install babel-core babel-preset-es2015

[...]

$ node
> process.chdir("..");
undefined
> require("babel-core").transformFileSync("test.js", {presets: ["es2015"]}).code;
Error: Couldn't find preset "es2015"
    at OptionManager.mergePresets (/home/user/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:315:17)
    at OptionManager.mergeOptions (/home/user/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:12)
    at OptionManager.init (/home/user/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:400:10)
    at File.initOptions (/home/user/test/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/home/user/test/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/home/user/test/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Object.transformFileSync (/home/user/test/node_modules/babel-core/lib/api/node.js:118:10)
    at repl:1:23
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
> 

```

By the way, my use-case doesn't transform files. I'm using `babel-core` to provide a Babel shell, where each execution request is transpiled so that it can be run on a `Node.js` shell.

**Comment by sebmck** [comment]
As I said, the presets/plugins are being resolved relative to the file you're transforming.

**Comment by n-riesco** [comment]
Unfortunately, the fact the `babel-core` doesn't use `Node.js`'s module resolution breaks the installation of my package.

Out of curiosity, would it be difficult to change `babel-core` so that it uses `Node.js`'s module resolution to load `babel-preset-2005`?

Just for completeness, here's an updated test case that shows the issue even when the transformed file is located in the same folder as the package:

It also happens when I transform a file. See below:

```
$ mkdir test
$ cd test
$ echo {} > package.json
$ npm install babel-core babel-preset-es2015

[...]

$ echo "'Hi';" > test.js
$ node
> process.chdir("..");
undefined
> require("babel-core").transformFileSync("test/test.js", {presets: ["es2015"]}).code;
Error: Couldn't find preset "es2015"
    at OptionManager.mergePresets (/home/user/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:315:17)
    at OptionManager.mergeOptions (/home/user/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:12)
    at OptionManager.init (/home/user/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:400:10)
    at File.initOptions (/home/user/test/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/home/user/test/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/home/user/test/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Object.transformFileSync (/home/user/test/node_modules/babel-core/lib/api/node.js:118:10)
    at repl:1:23
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
> 

```
