### ISSUE TITLE
Static class properties still not working properly

### ISSUE THREAD

**Issue by phantom10111** [babel/babel#2983]
__.babelrc__
```JSON
{
  "plugins": ["transform-class-properties"]
}
```
__test.js__
```JavaScript
export default class {
  static test = true
}
```
__result:__
```
TypeError: test.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/home/phantom/babel-test/node_modules/babel-types/lib/definitions/index.js:99:13)
    at validate (/home/phantom/babel-test/node_modules/babel-types/lib/index.js:268:9)
    at Object.builder (/home/phantom/babel-test/node_modules/babel-types/lib/index.js:221:7)
    at PluginPass.Class (/home/phantom/babel-test/node_modules/babel-plugin-transform-class-properties/lib/index.js:83:76)
    at newFn (/home/phantom/babel-test/node_modules/babel-traverse/lib/visitors.js:278:19)
    at NodePath._call (/home/phantom/babel-test/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/home/phantom/babel-test/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/home/phantom/babel-test/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/home/phantom/babel-test/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/home/phantom/babel-test/node_modules/babel-traverse/lib/context.js:111:19)
```
__test2.js__
```JavaScript
call(class {
	static test = true
});
```
__result:__
```
var _temp;

call((_temp = class {}, _undefined.test = true, _undefined, _temp));
```
__expected something like:__
```
var _temp;

call((_temp = class {}, _temp.test = true, _temp));
```
Babel version 6.1.4

**Comment by electerious** [comment]
Getting the same error as shown above (Babel 6.1.4).

**Comment by hzoo** [comment]
We have in https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-class-properties/src/index.js#L44-L48

```js
let ref;
        if (path.isClassExpression()) {
          ref = path.scope.generateUidIdentifier();
        } else { // path.isClassDeclaration()
          ref = path.node.id;
        }
```

ref is null in an export so it causes the `Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null`.

`transform-class-properties` is run before classes so we just need to be able to link the two in order to use the same ref?

**Comment by alexpalombaro** [comment]
Temp workaround is to provide a class name

```javascript
// fails
export default class {
  static test = true
}

// works (babel seems to default to a classname of _class anyway so output should be the same)
export default class _class {
  static test = true
}
```
