### ISSUE TITLE
Missing regeneratorRuntime

### ISSUE THREAD

**Issue by tomkis1** [babel/babel#2984]
I might have missed something but running the bundle throws me this exception:

```
/Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:906
	    var ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(comm
	                                ^
ReferenceError: regeneratorRuntime is not defined
    at /Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:906:34
    at Object.defineProperty.value (/Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:925:6)
    at __webpack_require__ (/Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:20:30)
    at Object.<anonymous> (/Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:748:32)
    at __webpack_require__ (/Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:20:30)
    at Object.<anonymous> (/Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:696:24)
    at __webpack_require__ (/Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:20:30)
    at Object.<anonymous> (/Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:67:19)
    at __webpack_require__ (/Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:20:30)
    at /Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:40:18
    at Object.<anonymous> (/Users/tomasweiss/dev/habanero/timesheet/dist/timesheet.server.min.js:43:10)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:953:3
```
I have required `babel-polyfill` in the main file. My `.eslintrc` looks as follows:
```
{
  "presets": ["es2015", "stage-0", "react"]
}
```
and I have these deps installed:

```
    "babel-core": "^6.1.4",
    "babel-loader": "^6.1.0",
    "babel-polyfill": "^6.1.4",
    "babel-preset-es2015": "^6.1.4",
    "babel-preset-react": "^6.1.4",
    "babel-preset-stage-0": "^6.1.2",
    "babel-runtime": "^6.1.4",
```

Also, when using `"plugins": ["transform-runtime"]` with installed `babel-runtime` it throws error when compiling:

```
ERROR in ./src/server/query/queryMappingHelper.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in /Users/tomasweiss/dev/habanero/timesheet/src/server/query
 @ ./src/server/query/queryMappingHelper.js 8:16-56

ERROR in ./~/babel-runtime/regenerator/runtime.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/typeof' in /Users/tomasweiss/dev/habanero/timesheet/node_modules/babel-runtime/regenerator
 @ ./~/babel-runtime/regenerator/runtime.js 15:15-54
```

**Comment by hzoo** [comment]
Ok closing in favor of https://github.com/babel/babel/issues/2986
