### ISSUE TITLE
Mocha breaks with Babel 6 when using babel-plugin-transform-es2015-modules-amd

### ISSUE THREAD

**Issue by Robert-W** [babel/babel#2992]
Im trying to setup a simple test using babel and mocha,  I have to use babel-plugin-transform-es2015-modules-amd because most of our projects leverage an api built on dojo.  If I remove this plugin from my ```.babelrc``` everything works fine, but including it throws a big error when trying to run mocha.

I am using the following command:
```mocha --compilers js:babel-core/register```
with the following ```.babelrc```
```
{
  "plugins": ["transform-es2015-modules-amd"],
  "presets": ["react", "es2015", "stage-0"],
  "sourceMaps": false,
  "ignore": [
    "build",
    "node_modules"
  ]
}
``` 
and using it on a very simple test at the moment:
```
/*eslint-disable no-unused-expressions */
let expect = require('chai').expect;

describe('Testing test framework', () => {

  it('should pass a simple test', () => {
    expect(1 === 1).to.be.ok;
  });

});
```
but this throws a huge error:
```
/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/lib/transformation/file/index.js:542
      throw err;
      ^

TypeError: /Users/Robert/Desktop/mocha-es6/test/testSpec.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-types/lib/definitions/index.js:99:13)
    at Object.validate (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-types/lib/index.js:268:9)
    at NodePath._replaceWith (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/replacement.js:203:7)
    at NodePath._remove (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/removal.js:57:10)
    at NodePath.remove (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/removal.js:29:8)
    at PluginPass.CallExpression (/Users/Robert/Desktop/mocha-es6/node_modules/babel-plugin-transform-es2015-modules-amd/lib/index.js:49:12)
    at NodePath._call (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:102:12)
    at TraversalContext.visitQueue (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:111:19)
    at TraversalContext.visit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:141:17)
    at NodePath.visit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:106:22)
    at TraversalContext.visitQueue (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:111:19)
    at TraversalContext.visit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:141:17)
    at NodePath.visit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:106:22)
    at TraversalContext.visitQueue (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitMultiple (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:106:17)
    at TraversalContext.visit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:193:19)
    at Function.traverse.node (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:141:17)
    at NodePath.visit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:106:22)
    at TraversalContext.visitQueue (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitMultiple (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:106:17)
    at TraversalContext.visit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:193:19)
    at Function.traverse.node (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:141:17)
    at Object.traverse [as default] (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:63:12)
    at NodePath.traverse (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:147:23)
    at PluginPass.exit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-plugin-transform-es2015-modules-amd/lib/index.js:92:16)
    at newFn (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:278:19)
    at NodePath._call (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:44:17)
    at NodePath.visit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:108:8)
    at TraversalContext.visitQueue (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:151:16)
    at TraversalContext.visitSingle (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:111:19)
    at TraversalContext.visit (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:141:17)
    at Object.traverse [as default] (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:63:12)
    at File.transform (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/lib/transformation/file/index.js:501:31)
    at /Users/Robert/Desktop/mocha-es6/node_modules/babel-core/lib/transformation/pipeline.js:46:19
    at File.wrap (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/lib/transformation/file/index.js:514:16)
    at Pipeline.transform (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/lib/transformation/pipeline.js:43:17)
    at Object.transformFileSync (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/lib/api/node.js:118:10)
    at compile (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-register/lib/node.js:103:20)
    at loader (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Robert/Desktop/mocha-es6/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/Robert/Desktop/mocha-es6/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/Robert/Desktop/mocha-es6/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/Users/Robert/Desktop/mocha-es6/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/Users/Robert/Desktop/mocha-es6/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

I have all the plugins and presets installed plus babel-core, babel-cli, and babel-polyfill.  Any ideas as to how I can configure this to ignore the plugin when running a test via npm test and only use it when compiling for use in the browser?

**Comment by Robert-W** [comment]
Hmm, very strange, I no longer seem to be getting this error anymore, now I am getting a define is not defined.  So I guess the question would be better phrased as Is there a good way to configure no plugin for testing but use it for everything else?

**Comment by Robert-W** [comment]
Ok closing this now as I figured it out, seems like when I can't figure something out I just post a ticket and things start working.  Updated my ```.babelrc``` to use the following and it worked fine.
```
{
  "env": {
    "test": {
      "plugins": []
    },
    "development": {
      "plugins": ["transform-es2015-modules-amd"]
    }
  },
  "presets": ["react", "es2015", "stage-0"],
  "sourceMaps": false,
  "ignore": [
    "build",
    "node_modules"
  ]
}
```
