### ISSUE TITLE
ReferenceError: this hasn't been initialised - super() hasn't been called

### ISSUE THREAD

**Issue by phantom10111** [babel/babel#2997]
Using Babel version 6.1.4

__.babelrc__:
```JSON
{
  "plugins": ["transform-es2015-classes"]
}
```
__test.js__:
```JavaScript
"use strict";
class A {}
class B extends A {
  constructor() {
    var a;
    return a = super(), a;
  }
}
new B();
```
Generates the following error at runtime:
```
ReferenceError: this hasn't been initialised - super() hasn't been called
    at _possibleConstructorReturn ([stdin]:3:70)
    at new B ([stdin]:22:12)
    at [stdin]:28:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:425:26)
    at node.js:587:27
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```
At the same time, __test2.js__, which should be equivalent, works fine:
```JavaScript
"use strict";
class A {}
class B extends A {
  constructor() {
    var a = super();
    return a;
  }
}
new B();
```

**Comment by thejameskyle** [comment]
Example repo: https://github.com/thejameskyle/__babel-bug-2997

**Comment by thejameskyle** [comment]
@phantom10111 found an even smaller example:

```js
constructor() {
  return super();
}
```
