### ISSUE TITLE
SyntaxError: Duplicate data property in object literal not allowed in strict mode: __source

### ISSUE THREAD

**Issue by sapegin** [babel/babel#3005]
Not sure where to put this issue. 

I use Babel 6 with Mocha and have a strange problem. Code to reproduce [is here](https://github.com/sapegin/babel-double-source). 

```
> babel-source@1.0.0 test /Users/tema/babel-double-source
> mocha --compilers js:babel-core/register test.js

/Users/tema/babel-double-source/test.js:36
                    __source: {
                    ^^^^^^^^
SyntaxError: Duplicate data property in object literal not allowed in strict mode
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at loader (/Users/tema/babel-double-source/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tema/babel-double-source/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/tema/babel-double-source/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/tema/babel-double-source/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/Users/tema/babel-double-source/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/Users/tema/babel-double-source/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

Everything is fine with 6.1.2 but not with 6.1.4. What I could debug is that babel-plugin-transform-react-jsx-source runs twice for some reason so I have two `__source` keys.

I cannot reproduce this without Mocha but I’m not sure that babel-plugin-transform-react-jsx-source should add  `__source` key if it’s already exists. 6.1.2 didn’t have this plugin.

**Comment by thejameskyle** [comment]
`babel-plugin-transform-react-jsx-source` has been disabled from the `react` preset. Update `babel-preset-react` and it should work.

**Comment by jmm** [comment]
@thejameskyle That change doesn't appear to be in the latest release `babel-preset-react@6.1.4`.

**Comment by hzoo** [comment]
Should be fixed in https://github.com/babel/babel/pull/3504
