### ISSUE TITLE
babel-doctor throws

### ISSUE THREAD

**Issue by oriSomething** [babel/babel#3006]
```
Babel Doctor
Running sanity checks on your system. This may take a few minutes...

Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TLSWrap.onread (net.js:544:26)
```

OS X Yosemite
Node v4.2.1
NPM 3.3.12

**Comment by thejameskyle** [comment]
http://stackoverflow.com/questions/17245881/node-js-econnreset
