### ISSUE TITLE
Unknown option: .../package.json.presets

### ISSUE THREAD

**Issue by brickyang** [babel/babel#3015]
**UPDATE**

I create `.babelrc` file and add 

```
{
  "presets": [
    "es2015",
    "react"
  ]
}
```

in it (removed the `babel` property from `package.json`). I can run `babel src -d lib` manually but still cannot run it via `package.json`. It will throw error:

```
ERROR in ./src/client/entry.js
Module build failed: ReferenceError: [BABEL] /Users/brick/Dropbox/learncoding/node.js/isomorphic/src/client/entry.js: Unknown option: /Users/brick/Dropbox/learncoding/node.js/isomorphic/.babelrc.presets
    at Logger.error (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-loader/index.js:69:12)
 @ multi main
```

I can just ignore this error because the app can runs. But I don't know why this error appears and what it affects.

The `entry.js` mentioned in the error message is:

```
import React from "react";
import Router from "react-router";
import ReactDOM from "react-dom";
import routes from "./routes";
import DataWrapper from './DataWrapper';
import createBrowserHistory from 'history/lib/createBrowserHistory';

let history = createBrowserHistory();
var data = JSON.parse(document.querySelector('#data').innerHTML);
ReactDOM.render(<DataWrapper data={data}><Router history = {history}>{routes}</Router></DataWrapper>, document.querySelector('#app'));

```
-------------------------------------------------

I just update to babel6. I have already install `babel-preset-es2015` and `babel-preset-react`. My `package.json` is 
```
"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1",
		"clean": "rm -rf lib",
		"build": "npm run clean && /usr/local/bin/babel src -d lib --experimental",
		"server": "nodemon lib/server/server",
		"dev-server": "node lib/server/webpack",
                "watch-js": "/usr/local/bin/babel src -d lib --experimental -w",
		"start": "npm run watch-js & npm run dev-server & npm run server"
	},
	"babel": {
		"presets": ["es2015","react"]
	},
```

the shell just throw an error about `Unknown option: .../package.json.presets`

Please help me

**Comment by lailo-ch** [comment]
Same error here, please help use out.

**Comment by loganfsmyth** [comment]
Why are you using `/usr/local/bin/babel`, it should be `babel`. That will use a global Babel version instead of the one in your `package.json`. Also please make sure your `babel-loader` is up to date for version 6.

**Comment by IlyasM** [comment]
+1

**Comment by hzoo** [comment]
If there is an error about presets not being an option then somehow babel 5 is being run somewhere (maybe global)
