### ISSUE TITLE
Can't get gulpfile to run with babel-core/register

### ISSUE THREAD

**Issue by Industrial** [babel/babel#3021]
Hi.

I can't get my [gulpfile.js](https://github.com/Industrial/test-loopback/blob/master/gulpfile.js#L3) working.

It goes on to load [initialize.js](https://github.com/Industrial/test-loopback/blob/master/gulp/initialize.js) which (and the rest) is all in ES2015.

```
$ gulp run
/home/tom/code/test-loopback/gulp/initialize.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at loader (/home/tom/code/test-loopback/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/tom/code/test-loopback/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/tom/code/test-loopback/gulpfile.js:5:1)
    at Module._compile (module.js:435:26)
```

**Comment by hzoo** [comment]
If it's `Unexpected reserved word` it sounds like you didn't specify your presets/plugins http://babeljs.io/blog/2015/10/31/setting-up-babel-6/

**Comment by Industrial** [comment]
I'ts not the gulp setup that is wrong. I have configured my gulp babel compile task correctly.

What is wrong is that the gulpfile.js source code itself is written in ES6. I want to run that directly through babel, so I require `babel-core/register`. This used to work with the 5.x version, but stopped working with 6.x

**Comment by hzoo** [comment]
Oh ok - then you just need to pass the correct options into that `require('babel-core/register')({ preset: [] });`

**Comment by Industrial** [comment]
I did that, and now I get:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/interop-require-wildcard'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/tom/code/test-loopback/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/lib/index.js:5:31)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/tom/code/test-loopback/node_modules/babel-core/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

**Comment by hzoo** [comment]
Sounds something like https://github.com/babel/babel/issues/3012? Since you're original issue is fixed goina close this one.
