### ISSUE TITLE
Cannot read property 'coroutine' of undefined

### ISSUE THREAD

**Issue by magicismight** [babel/babel#3030]
```
async function updateCache() {
    let [system] = await System.findAll();
    cache = system;
    return system;
}
```
this will throw an error 

```
TypeError: Cannot read property 'coroutine' of undefined
    at /www/deyi/server/models/system.js:8:28
    at Object.<anonymous> (system.js:6:27)
    at Module._compile (module.js:435:26)
    at loader (/www/deyi/server/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/www/deyi/server/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/www/deyi/server/core/models.js:12:15)
    at Module._compile (module.js:435:26)
    at loader (/www/deyi/server/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/www/deyi/server/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/www/deyi/server/core/admin.js:41:15)
    at Module._compile (module.js:435:26)
    at loader (/www/deyi/server/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/www/deyi/server/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
```

but this works fine
```
let updateCache = async function () {
    let [system] = await System.findAll();
    cache = system;
    return system;
};
```

there is my .babelrc,and my babel version is `6.1.18`
```JSON
{
    "presets": [
        "es2015",
        "stage-0"
    ],
    "plugins": [
        ["transform-async-to-module-method", {
            "module": "bluebird",
            "method": "coroutine"
        }]
    ]
}
```

**Comment by sebmck** [comment]
Basically #3026.
