### ISSUE TITLE
Syntax bug? Function name and variable name not allowed to be the same

### ISSUE THREAD

**Issue by jonaskello** [babel/babel#3048]
Minimal repro:

.babelrc
```json
{
  "presets": ["es2015", "stage-2"]
}
```

repro.js

```javascript
class Stream {
 timeout(timeLimit, opts) {
    let timeout = null;
  }
}
```

```bash
$ babel --version
6.1.18 (babel-core 6.1.19)

$ babel repro.js 
TypeError: repro.js: Duplicate declaration "timeout"
  1 | class Stream {
  2 |  timeout(timeLimit, opts) {
> 3 |     let timeout = null;
    |         ^
  4 |   }
  5 | }
  6 | 
    at File.buildCodeFrameError (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:408:15)
    at Scope.checkBlockScopedCollisions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/scope/index.js:488:27)
    at Scope.<anonymous> (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/scope/index.js:673:18)
    at Scope.registerBinding (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/scope/index.js:687:8)
    at Scope.registerDeclaration (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/scope/index.js:575:14)
    at Object.BlockScoped (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/scope/index.js:226:28)
    at Object.newFn (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:311:17)
    at NodePath._call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:72:18)
    at NodePath.call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:40:14)
    at NodePath.visit (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:102:12)
```

 According to the author of the original code (which is not me), this should be allowed and it is also working in Chrome Canary.

 > As I understand it, a function has its own LexicalEnvironment and corresponding EnvironmentRecord. Creating a new binding only checks for duplicates in that same EnvironmentRecord - not in any containing LexicalEnvironment / EnvironmentRecord:

> [http://www.ecma-international.org/ecma-262/6.0/#sec-declarative-environment-records-createmutablebinding-n-d]

Also see this original [issue](https://github.com/dart-lang/dev_compiler/issues/385#issuecomment-156451540).

**Comment by hzoo** [comment]
Thanks! This is the same as https://github.com/babel/babel/issues/2684
