### ISSUE TITLE
babel require hook results different than babel cli - export default async functions

### ISSUE THREAD

**Issue by legomind** [babel/babel#3065]
Given the following code:

index.js

``` js
import User from './model/User'
let users = await User.GetAll()
console.log(JSON.Stringify(users))
```

model/User.js

``` js
import sqlConnection from '../sql-connection'

export default class User {
  constructor (data) {
    this.FirstName = data.FirstName
    this.LastName = data.LastName
    this.DOB = data.DOB
    this.DateCreated = data.DateCreated
    this.DateLastModified = data.DateLastModified
  }

  static async GetAll () {
    let r = sqlConnection.request()
    let ds = await r.query('SELECT * FROM dbo.Users')
    return ds.map(x => new User(x))
  }

  static async GetById (id) {
    let r = sqlConnection.request()
    let ds = await r.query(`SELECT * FROM dbo.Users WHERE Id = '${id}'`)
    return new User(ds)
  }
}

```

When running app with: `node -r babel-register src/`:

```
ReferenceError: r is not defined]
Debug: internal, implementation, error
    Error: ReferenceError: r is not defined
    at _callee$ (user.js:14:20)
    at tryCatch (/Users/coryt/projects/my-project/node_modules/babel-polyfill/node_modules/regenerator/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/coryt/projects/my-project/node_modules/babel-polyfill/node_modules/regenerator/runtime.js:338:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/coryt/projects/my-project/node_modules/babel-polyfill/node_modules/regenerator/runtime.js:95:21)
```

When running app with: `babel  --out-dir dist/ src/*.js && node dist/`

```
[{"FirstName":"Austin","LastName":"Atkinson","DOB":"1979-07-05T00:00:00.000Z","DateCreated":"1965-11-19T22:32:13.420Z","DateLastModified":"1965-11-22T01:19:57.920Z"},{"FirstName":"Marc","LastName":"Gross","DOB":"2002-12-02T00:00:00.000Z","DateCreated":"2005-01-26T12:13:41.350Z","DateLastModified":"2005-04-10T09:10:27.940Z"}]
```

Module versions:

``` json
{
    "babel-core": "^6.1.21",
    "babel-polyfill": "^6.1.19",
    "babel-register": "^6.1.18",
    "babel-preset-es2015": "^6.1.4",
    "babel-preset-stage-0": "^6.1.2",
}
```

babel.rc

``` json
{
  "sourceMap": true,
  "presets": [ "es2015", "stage-0" ]
}
```

**Comment by vekexasia** [comment]
I'm suffering something like this.

Can you confirm that changing `export default class Blabla" to `class Balbla` & then `exports = Blabla` works?

**Comment by legomind** [comment]
@vekexasia Yes! The following works!

```js
import sqlConnection from '../sql-connection'

class User {
  constructor (data) {
    this.FirstName = data.FirstName
    this.LastName = data.LastName
    this.DOB = data.DOB
    this.DateCreated = data.DateCreated
    this.DateLastModified = data.DateLastModified
  }

  static async GetAll () {
    let r = sqlConnection.request()
    let ds = await r.query('SELECT * FROM dbo.Users')
    return ds.map(x => new User(x))
  }

  static async GetById (id) {
    let r = sqlConnection.request()
    let ds = await r.query(`SELECT * FROM dbo.Users WHERE Id = '${id}'`)
    return new User(ds)
  }
}

module.exports = User
```

**Comment by legomind** [comment]
Perhaps related to #2718?

**Comment by legomind** [comment]
Removing the `default` keyword works too.

index.js
```js
import { User } from './model/User'
let users = await User.GetAll()
console.log(JSON.Stringify(users))
```
model/User.js
```js
import sqlConnection from '../sql-connection'

export class User {
  constructor (data) {
    this.FirstName = data.FirstName
    this.LastName = data.LastName
    this.DOB = data.DOB
    this.DateCreated = data.DateCreated
    this.DateLastModified = data.DateLastModified
  }

  static async GetAll () {
    let r = sqlConnection.request()
    let ds = await r.query('SELECT * FROM dbo.Users')
    return ds.map(x => new User(x))
  }

  static async GetById (id) {
    let r = sqlConnection.request()
    let ds = await r.query(`SELECT * FROM dbo.Users WHERE Id = '${id}'`)
    return new User(ds)
  }
}
```

**Comment by legomind** [comment]
A separate `export default` statement will work as well
```js
import sqlConnection from '../sql-connection'

export class User {
  constructor (data) {
    this.FirstName = data.FirstName
    this.LastName = data.LastName
    this.DOB = data.DOB
    this.DateCreated = data.DateCreated
    this.DateLastModified = data.DateLastModified
  }

  static async GetAll () {
    let r = sqlConnection.request()
    let ds = await r.query('SELECT * FROM dbo.Users')
    return ds.map(x => new User(x))
  }

  static async GetById (id) {
    let r = sqlConnection.request()
    let ds = await r.query(`SELECT * FROM dbo.Users WHERE Id = '${id}'`)
    return new User(ds)
  }
}

export default User
```

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
