### ISSUE TITLE
6to5/register doesn't work if writing es6 in the file in which 6to5/register is defined.

### ISSUE THREAD

**Issue by chrisabrams** [babel/babel#45]
If I make a file such as:

```
require('6to5/register')
require('6to5/polyfill')

class A {
    constructor() {
        console.log('A')
    }
}

var a = new A()
```

I will get the following error:

```
class A {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

but if I put `class A` in it's own file and require it, everything work as expected.

**Comment by resistdesign** [comment]
@sebmck If it's the first file loaded into node you spin off another process with the same args but target a wrapper that requires the current file and then exit the current process. But that is the only way! :P
