### ISSUE TITLE
TypeError: Can't add property call, object is not extensible

### ISSUE THREAD

**Issue by lucastan** [babel/babel#4569]
No problem  running the js in browser but got this when tried to run the js thru babel . 

```

events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Can't add property call, object is not extensible
    at defProp (/Users/xxx/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/private/private.js:11:15)
    at makeSafeToCall (/Users/xxx/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/private/private.js:24:5)
    at Object.<anonymous> (/Users/xxx/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/private/private.js:35:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xxx/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/meta.js:15:9)
```

**Comment by hzoo** [comment]
We will need more information here - I would fill out the issue template so we can help you. (Code snippet, babelrc, etc)

**Comment by lucastan** [comment]
i have a lot of js code... how do I pinpoint which part caused the problem? any suggestion?

**Comment by hzoo** [comment]
Basically I would comment out/remove code (it's mostly a guess) until the error is gone - then you'll have a better idea of what is causing the problem.

The error is coming from regenerator though so it sounds like you are using either async or a generator (`async function a() {}` or `function *a() {}`)

**Comment by lucastan** [comment]
this is the code

```
haAppConfig = function (app){
    'use strict';


};

//# sourceMappingURL=config.js.map
```

**Comment by loganfsmyth** [comment]
@benjamn Any thoughts on what would cause this exception?

@lucastan What version of Node are you running this on?

**Comment by loganfsmyth** [comment]
@lucastan What other dependencies do you load in your `gulpfile`? If you remove all the require/import except the ones needed for this transform, does this happen? Do you have a `gulpfile.babel.js` or just a normal `gulpfile.js`? If you do `find node_modules -type d -name private` what do you get?

**Comment by lucastan** [comment]
it's just gulpfile.js 

node 4.1.0

imports
```
var gulp = require('gulp');
var gulpCopy = require('gulp-copy');
var babel = require("gulp-babel");
var concat = require('gulp-concat');
var Cache = require('gulp-file-cache');
var minifyCss = require('gulp-minify-css');
var minifyHtml = require('gulp-minify-html');
var ngAnnotate = require('gulp-ng-annotate');
var wrapJS = require("gulp-wrap-js");
var nodemon = require('gulp-nodemon');
var imagemin = require('gulp-imagemin');
var sourcemaps = require('gulp-sourcemaps');
var uglify = require('gulp-uglify');
```

```
node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/private
node_modules/gulp-babel/node_modules/babel-core/node_modules/private
node_modules/jade-babel/node_modules/babel-core/node_modules/private
node_modules/jscs/node_modules/babel-core/node_modules/private
```

**Comment by loganfsmyth** [comment]
I don't have more time at the moment, but some module somewhere in there is probably replacing `Function.prototype.call` and `Function.prototype.apply`. I have no idea what that would be though.

**Comment by loganfsmyth** [comment]
As a bit of a hack, what happens if you add `require('babel-preset-es2015')'` to the very top of your gulpfile above everything else? You don't have to assign it to anything, just load it.

**Comment by lucastan** [comment]
i added `require('babel-preset-es2015')'` above everything else ... no error

**Comment by lucastan** [comment]
@loganfsmyth  any idea

**Comment by hzoo** [comment]
Closing for inactivity, can you update the packages and check again if it still has the error?

**Comment by mladenp** [comment]
Hey @lucastan did you fix this somehow?
I just migrated from webpack 1 to 2 and i am getting this error in browser console.
