### ISSUE TITLE
Regression babel-code-frame@6.16.0: mocks stopped working?

### ISSUE THREAD

**Issue by bestander** [babel/babel#4601]
React Native started failing Jest tests with release of 6.16.0 yesterday

```
Running 44 test suites... FAIL  packager/react-packager/src/JSTransformer/worker/__tests__/constant-folding-test.js
  ● Test suite failed to run
    TypeError: Cannot read property 'bold' of undefined
      
      at Object.<anonymous> (node_modules/babel-code-frame/lib/index.js:77:39)
      at Object.<anonymous> (node_modules/babel-traverse/lib/path/replacement.js:16:23)
      at Object.<anonymous> (node_modules/babel-traverse/lib/path/index.js:184:43)
      at Object.<anonymous> (node_modules/babel-traverse/lib/index.js:10:13)
      at Object.<anonymous> (node_modules/babel-template/lib/index.js:69:22)
      at Object.<anonymous> (node_modules/babel-helpers/lib/helpers.js:5:22)
      at Object.<anonymous> (node_modules/babel-helpers/lib/index.js:12:16)
      at Object.<anonymous> (node_modules/babel-core/lib/transformation/file/index.js:34:21)
      at Object.<anonymous> (node_modules/babel-core/lib/api/node.js:6:13)
      at Object.<anonymous> (node_modules/babel-core/index.js:1:107)
      at Object.<anonymous> (packager/react-packager/src/JSTransformer/worker/__tests__/constant-folding-test.js:12:15)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

The reference to `bold` is probably related to a mock we have for chalk.js https://github.com/facebook/react-native/blob/542ab8643ece6e8e29445cf3584e47cc5d39c0e6/local-cli/__mocks__/chalk.js

A CI run with 6.16.0: https://travis-ci.org/facebook/react-native/jobs/163517412
A working CI run with 6.11.0: https://travis-ci.org/facebook/react-native/jobs/163467411

I'll dig a bit more

**Comment by bestander** [comment]
Nevermind, this is related to the primitive mock of chalk.js we have in the code
