### ISSUE TITLE
Error in babel-register 6.16.0

### ISSUE THREAD

**Issue by ColorfulCow** [babel/babel#4602]
```
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at loader (/data/app/adminservice/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/data/app/adminservice/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/data/app/adminservice/js/shared/components/index.js:592:31)
    at Module._compile (module.js:435:26)
    at loader (/data/app/adminservice/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/data/app/adminservice/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

**Comment by ataube** [comment]
I can confirm to have the same error

```
somefile.js:204
                  return _context4.abrupt('return', (await sut(SOME_ID, {
                                                           ^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at loader (/Users/ataube/dev/workspace/LiquidLabs/squealing-octo-giggle/node_modules/babel-register/lib/node.js:143:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ataube/dev/workspace/LiquidLabs/squealing-octo-giggle/node_modules/babel-register/lib/node.js:153:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/ataube/dev/workspace/LiquidLabs/squealing-octo-giggle/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/ataube/dev/workspace/LiquidLabs/squealing-octo-giggle/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/ataube/dev/workspace/LiquidLabs/squealing-octo-giggle/node_modules/mocha/lib/mocha.js:485:10)
    at Object.<anonymous> (/Users/ataube/dev/workspace/LiquidLabs/squealing-octo-giggle/node_modules/mocha/bin/_mocha:457:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

It seems like the await keyword gets not transformed!

The source file looks something like

```
describe('some context', () => {
        beforeEach(async () =>
          await sut(SOME_ID)
        );

        ....
      });
```

**Comment by danez** [comment]
This might be related to #4599 which is already fixed in master and will be released later.
