### ISSUE TITLE
Syntax error (Unexpected token) for export-extensions

### ISSUE THREAD

**Issue by fanatid** [babel/babel#4644]
`.babelrc`:

```
{
  "plugins": [
    "transform-export-extensions",
    "transform-async-to-generator",
    "transform-es2015-modules-commonjs"
  ]
}
```

`a.js`:

``` js
export default class A {}
```

`b.js`:

``` js
export A from './a'
```

`c.js`:

``` js
import { A } from './b'
```

`d.js`:

``` js
require('babel-register')({ ignore: false })
```

command:

``` bash
$ node -r ./d c.js 
/home/kirill/tmp/babel/node_modules/babel-core/lib/transformation/file/index.js:605
      throw err;
      ^

SyntaxError: /home/kirill/tmp/babel/b.js: Unexpected token (1:7)
> 1 | export A from './a'
    |        ^
  2 | 
    at Parser.pp.raise (/home/kirill/tmp/babel/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/home/kirill/tmp/babel/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.expect (/home/kirill/tmp/babel/node_modules/babylon/lib/parser/util.js:83:33)
    at Parser.pp.parseExportSpecifiers (/home/kirill/tmp/babel/node_modules/babylon/lib/parser/statement.js:1017:8)
    at Parser.pp.parseExport (/home/kirill/tmp/babel/node_modules/babylon/lib/parser/statement.js:887:28)
    at Parser.pp.parseStatement (/home/kirill/tmp/babel/node_modules/babylon/lib/parser/statement.js:133:81)
    at Parser.pp.parseBlockBody (/home/kirill/tmp/babel/node_modules/babylon/lib/parser/statement.js:514:21)
    at Parser.pp.parseTopLevel (/home/kirill/tmp/babel/node_modules/babylon/lib/parser/statement.js:28:8)
    at Parser.parse (/home/kirill/tmp/babel/node_modules/babylon/lib/parser/index.js:96:17)
    at parse (/home/kirill/tmp/babel/node_modules/babylon/lib/index.js:45:47)
```

Environment:

``` bash
$ uname -a
Linux localhost.localdomain 4.6.6-200.fc23.x86_64 #1 SMP Wed Aug 10 23:13:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ node -v
v6.7.0
$ npm -v
3.10.3
$ npm ls | grep babel
/home/kirill/tmp/babel
├─┬ babel-core@6.17.0
│ ├─┬ babel-code-frame@6.16.0
│ ├─┬ babel-generator@6.17.0
│ ├── babel-helpers@6.16.0
│ ├── babel-messages@6.8.0
│ ├─┬ babel-register@6.16.3
│ ├─┬ babel-runtime@6.11.6
│ ├── babel-template@6.16.0
│ ├─┬ babel-traverse@6.16.0
│ ├─┬ babel-types@6.16.0
├─┬ babel-plugin-transform-async-to-generator@6.16.0
│ ├─┬ babel-helper-remap-async-to-generator@6.16.2
│ │ └─┬ babel-helper-function-name@6.8.0
│ │   └── babel-helper-get-function-arity@6.8.0
│ └── babel-plugin-syntax-async-functions@6.13.0
├─┬ babel-plugin-transform-es2015-modules-commonjs@6.16.0
│ └── babel-plugin-transform-strict-mode@6.11.3
└─┬ babel-plugin-transform-export-extensions@6.8.0
  └── babel-plugin-syntax-export-extensions@6.13.0
```

**Comment by danez** [comment]
This form of the export is not yet available in any ES201X syntax, but is a stage 1 proposal.
https://github.com/leebyron/ecmascript-export-default-from

To enable it either add stage-1 preset or add the plugin `babel-plugin-transform-export-extensions`

**Comment by fanatid** [comment]
@danez my `.babelrc` contains `transform-export-extensions`...

**Comment by fanatid** [comment]
The main problem, that if `transform-async-to-generator` will be removed from `.babelrc` all works as expected.

**Comment by danez** [comment]
It's not the transform, but the `syntax-export-extensions` that you need to add.

**Comment by fanatid** [comment]
@danez thank you, I missed it :(
with `syntax-export-extensions` all works, but from babel docs:
```
NOTE: Transform plugins automatically inherit/use the syntax plugins so you don’t need to specify the syntax plugin if the corresponding transform plugin is used already.
```

so, why I need include syntax plugin here if I already include transform?

**Comment by danez** [comment]
Thats a good question

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by slavadevelopers** [comment]
When added this plugin in create-react-app?

**Comment by nicolo-ribaudo** [comment]
You should ask to the [create-react-app repository](https://github.com/facebookincubator/create-react-app).

Anyway, even if they don't add this plugin to the create-react-app babel preset, you can add using a .babelrc file in the root of your project:
```json
{
  "presets": [ "react-app" ],
  "plugins": [ "transform-export-extensions" ]
}
```
