### ISSUE TITLE
Module build failed: Error: Couldn't find preset "stage-0" relative to directory "/Users/olalonde/code/blockai/filepunk-widget/lib/styles"

### ISSUE THREAD

**Issue by olalonde** [babel/babel#4693]
I'm getting this error (using webpack) after `npm link`ing a module (if I `npm install` it, the error goes away):

After `npm link @blockai/filepunk-widget`, I'm getting:

```
[0] Module build failed: Error: Couldn't find preset "stage-0" relative to directory "/Users/olalonde/code/blockai/filepunk-widget/lib/styles"
[0]     at /Users/olalonde/code/blockai/blockai-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:17
[0]     at Array.map (native)
[0]     at OptionManager.resolvePresets (/Users/olalonde/code/blockai/blockai-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
[0]     at OptionManager.mergeOptions (/Users/olalonde/code/blockai/blockai-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:319:29)
```

I have ignore `node_modules` in my webpack config:

``` javascript
//...
   loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: [
          `babel?${JSON.stringify(babelLoaderQuery)}`,
        ],
      },
 // ...
```

**Comment by hzoo** [comment]
sounds like https://github.com/babel/babel/issues/4716? not sure other than issues with npm link
