### ISSUE TITLE
async+destructuring: Cannot read property '0' of null

### ISSUE THREAD

**Issue by hlandau** [babel/babel#4759]
```
$ babel --version
6.16.0 (babel-core 6.17.0)
$ node --version
v6.8.1
$ cat .babelrc
{
  "presets": ["node6"],
  "plugins": ["syntax-async-functions","transform-regenerator"]
}
$ cat x.js
async function g() {
  var {x,y} = f();
}
$ babel x.js
TypeError: x.js: Cannot read property '0' of null
    at isHelper (/usr/lib/node_modules/babel-cli/node_modules/babel-generator/lib/node/whitespace.js:48:48)
    at VariableDeclaration (/usr/lib/node_modules/babel-cli/node_modules/babel-generator/lib/node/whitespace.js:103:21)
    at find (/usr/lib/node_modules/babel-cli/node_modules/babel-generator/lib/node/index.js:93:15)
    at needsWhitespace (/usr/lib/node_modules/babel-cli/node_modules/babel-generator/lib/node/index.js:115:19)
    at needsWhitespaceBefore (/usr/lib/node_modules/babel-cli/node_modules/babel-generator/lib/node/index.js:131:10)
    at Generator._printNewline (/usr/lib/node_modules/babel-cli/node_modules/babel-generator/lib/printer.js:469:11)
    at Generator.printJoin (/usr/lib/node_modules/babel-cli/node_modules/babel-generator/lib/printer.js:366:32)
    at Generator.printSequence (/usr/lib/node_modules/babel-cli/node_modules/babel-generator/lib/printer.js:422:17)
    at Generator.BlockStatement (/usr/lib/node_modules/babel-cli/node_modules/babel-generator/lib/generators/base.js:40:10)
    at /usr/lib/node_modules/babel-cli/node_modules/babel-generator/lib/printer.js:298:23
```

Removing `async` keyword: compiles.
Removing destructuring assignment: compiles.

**Comment by hzoo** [comment]
might be your combination of plugins/presets - it works in the [repl](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2017&code=async%20function%20g()%20%7B%0A%20%20var%20%7Bx%2Cy%7D%20%3D%20f()%3B%0A%7D&experimental=true&loose=false&spec=false&playground=true&stage=0)

**Comment by hlandau** [comment]
It appears to be an issue with transform-regenerator:
```
$ babel --no-babelrc --plugins transform-regenerator x.js
TypeError: x.js: Cannot read property '0' of null
...
```

**Comment by hzoo** [comment]
Ah you're right. Definitely a bug but the workaround your particular case is that you can use the https://babeljs.io/docs/plugins/transform-async-to-generator/ transform since the env is node 6

**Comment by hlandau** [comment]
Yep, that works.

**Comment by luqmaan** [comment]
I'm having the same problem, and working around it by adding `transform-es2015-destructuring`.

```
export function* y(action) {
    const {payload} = action;
    yield payload;
}
```

```
$ babel --no-babelrc --plugins transform-regenerator y.js
TypeError: y.js: Cannot read property '0' of null
    at isHelper (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/node/whitespace.js:48:48)
    at VariableDeclaration (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/node/whitespace.js:103:21)
    at find (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/node/index.js:93:15)
    at needsWhitespace (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/node/index.js:115:19)
    at needsWhitespaceBefore (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/node/index.js:131:10)
    at Generator._printNewline (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/printer.js:469:11)
    at Generator.printJoin (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/printer.js:366:32)
    at Generator.printSequence (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/printer.js:422:17)
    at Generator.BlockStatement (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/generators/base.js:40:10)
    at /Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/printer.js:298:23
22:00:48 0 ~/o/pappy dev ✗ 4M 2A
pappy ❯ babel --no-babelrc --plugins transform-regenerator y.js | pbcopy
TypeError: y.js: Cannot read property '0' of null
    at isHelper (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/node/whitespace.js:48:48)
    at VariableDeclaration (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/node/whitespace.js:103:21)
    at find (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/node/index.js:93:15)
    at needsWhitespace (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/node/index.js:115:19)
    at needsWhitespaceBefore (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/node/index.js:131:10)
    at Generator._printNewline (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/printer.js:469:11)
    at Generator.printJoin (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/printer.js:366:32)
    at Generator.printSequence (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/printer.js:422:17)
    at Generator.BlockStatement (/Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/generators/base.js:40:10)
    at /Users/luqmaan/dev/o/pappy/node_modules/babel-generator/lib/printer.js:298:23
```


```
$ babel --no-babelrc --plugins transform-regenerator --plugins transform-es2015-destructuring y.js
export function* y(action) {
    const payload = action.payload;

    yield 3;
}
```

**Comment by EnoahNetzach** [comment]
A variant of this bug is
```es6
const dispatch = async id => ({ id })

export const getId = async () => {
  const { id } = await dispatch(42)

  return id
}
```
which throws the error `Expected type "Expression" with option {}`.

In this particular case the problem seems to be that it tries to treat an `ObjectPattern` as an `Expression` ([**@see**](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-regenerator/src/emit.js#L1142)) on the lhs of line 4.

**Comment by edmorley** [comment]
Is this a bug with babel/babel-plugin-transform-regenerator's use of [regenerator-transform](https://github.com/facebook/regenerator/tree/master/packages/regenerator-transform), or solely with the latter? Just wondering if this needs to be re-filed over at:
https://github.com/facebook/regenerator/issues

Also, is there an issue filed already for improving the error messages in cases like these? The current `Cannot read property '0' of null` doesn't provide a line number or many other clues, so this took me a while to track down :-)

**Comment by dorianrod** [comment]
Hi, I encountered this bug too. I need to transform generator as my code is going to go on front end clients.
Is there a workaround ?

**Comment by OmgImAlexis** [comment]
Are there any updates to this? I believe I'm running into a similar issue.

```
> Error! TypeError: Cannot read property '0' of null
    at shortFromAlias (/Users/xo/code/unraid/api/node_modules/pkg/lib-es5/walker.js:68:49)
    at Walker._callee5$ (/Users/xo/code/unraid/api/node_modules/pkg/lib-es5/walker.js:891:25)
    at tryCatch (/Users/xo/code/unraid/api/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/xo/code/unraid/api/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/xo/code/unraid/api/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/xo/code/unraid/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/xo/code/unraid/api/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nicolo-ribaudo** [comment]
Closing, since both the examples work now:
https://babeljs.io/repl#?babili=false&browsers=node%206&build=&builtIns=false&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsIwOYAoCUMA3gFAwwBuwATsQB4A0YAvjALzwEDcJzJJAegEwhI4aInipYmZNnS5i4fyiYQyGABNUIAA7BkUABbsYoSLFSb2APhi4iMKzGb5-AUzq701DaojqOO7IAJLWHObQ9oRsdqTk_oGOzqwRAO7AqBraegbGuAAsAExuZDDUwQjUWFa8QA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.5.4&externalPlugins=
