### ISSUE TITLE
TypeError using w/ Webpack or Browserify

### ISSUE THREAD

**Issue by gr4vy** [babel/babel#4847]
I am getting this error when I try using Webpack or when trying to use Browserify to transpile and bundle my code. I'm using babelify when trying Browserify. both using babel presets es2015 and react.

```
/dir/node_modules/babel-traverse/lib/path/index.js:47
var _debug = (0, _debug3.default)("babel");
                                 ^

TypeError: (0 , _debug3.default) is not a function
    at Object.<anonymous> (/dir/node_modules/babel-traverse/lib/path/index.js:47:34)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/dir/node_modules/babel-traverse/lib/index.js:10:13)
    at Module._compile (module.js:573:32)
```
| software         | version
| ---------------- | -------
| Babel            |  6.18.2
| node             | 7.0.0
| npm              | 3.10.8
| Operating System | linux

**Comment by DrewML** [comment]
@gr4vy It's impossible to help you without having example code that triggers this problem. Please provide the input code passed to babel, and a copy of your babel and webpack configuration.
