### ISSUE TITLE
transforming JSX inside of AMD module that uses property spread operator

### ISSUE THREAD

**Issue by pgraham** [babel/babel#4857]
### Input Code
https://gist.github.com/pgraham/51084903667496ffa6e8215e21d463d5

### Babel Configuration (.babelrc, package.json, cli command)
babelify with react preset

### Expected Behavior

Code should run without a ReferenceError. Transform helpers should remain in bundle after deamdify has been applied.

### Current Behavior

executing `npm test` produces the following output:

```
$ npm test

> babel-demo@0.0.1 test /Users/philip.graham/Development/src/mfm/babel-test
> ./run-tests.sh

Started
F

Failures:
1) views/MyComponent renders
  Message:
    ReferenceError: _extends is not defined
  Stack:
    ReferenceError: _extends is not defined
        at module.exports.React.createClass.render (/Users/philip.graham/Development/src/mfm/babel-test/target/test-bundle.js:6:47)
        at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/philip.graham/Development/src/mfm/babel-test/target/test-bundle.js:7221:34)
        at ReactCompositeComponentMixin._renderValidatedComponent (/Users/philip.graham/Development/src/mfm/babel-test/target/test-bundle.js:7248:14)
        at wrapper [as _renderValidatedComponent] (/Users/philip.graham/Development/src/mfm/babel-test/target/test-bundle.js:13724:21)
        at ReactCompositeComponentMixin.mountComponent (/Users/philip.graham/Development/src/mfm/babel-test/target/test-bundle.js:6669:30)
        at wrapper [as mountComponent] (/Users/philip.graham/Development/src/mfm/babel-test/target/test-bundle.js:13724:21)
        at /Users/philip.graham/Development/src/mfm/babel-test/target/test-bundle.js:14688:32
npm ERR! Test failed.  See above for more details.
```

### Possible Solution
Update transform process to detect AMD modules and insert helper functions inside of the define statement.

### Context
I am trying to bundle a legacy app using browserify in a way that allows test specs to leverage npm ecosystem.

### Your Environment

babelify: ^7.3.0
browserify: ^13.0.1
deamdify: github:jaredhanson/deamdify
jasmine: ^2.5.2
react: ^0.13.1

**Comment by DrewML** [comment]
This is a bug with `deamdify`, rather than with `Babel`. The AMD format allows binding identifiers to be declared outside the scope of the callback passed to `define`. Example:

```js
var foo = 'bar';

require([], function() {
    console.log(foo);
    return 'b';
});
```

When run through the `r.js` optimizer:
```js
var foo="bar";require([],function(){return console.log(foo),"b"}),define("MyComponent",function(){});
```

When this same code is run through `deamdify`, it produces:
```js
module.exports = function () {
    console.log(foo);
    return 'b';
}();
```

Note that `deamdify` is only transforming the code inside of the callback, and dropping any other code outside.
