### ISSUE TITLE
Duplicate declaration error with object literal syntax & function keyword

### ISSUE THREAD

**Issue by davewasmer** [babel/babel#4946]
It's possible this behavior is to-spec, but I don't think so. As I understand it, in the example input code below, the object literal creates a block scope but the function itself creates an additional block scope. Thus, the inner `let foo` should shadow, not collide with, the outer `function foo`

### Input Code

```js
let obj = {
  foo: function foo() {
    let foo = true;
    console.log('foo ran');
  }
};

obj.foo();
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{}
```

### Expected Behavior
The code should compile with no errors.

### Current Behavior
```
TypeError: index.js: Duplicate declaration "foo"
  2 | let obj = {
  3 |   foo: function foo() {
> 4 |     let foo = true;
    |         ^
  5 |     console.log('foo ran');
  6 |   }
  7 | };
    at File.buildCodeFrameError (/Users/daw/scratch/babel-duplicate-declaration-reproduction/node_modules/babel-core/lib/transformation/file/index.js:431:15)
    at Scope.checkBlockScopedCollisions (/Users/daw/scratch/babel-duplicate-declaration-reproduction/node_modules/babel-traverse/lib/scope/index.js:403:27)
    at Scope.registerBinding (/Users/daw/scratch/babel-duplicate-declaration-reproduction/node_modules/babel-traverse/lib/scope/index.js:597:16)
    at Scope.registerDeclaration (/Users/daw/scratch/babel-duplicate-declaration-reproduction/node_modules/babel-traverse/lib/scope/index.js:501:14)
    at Object.BlockScoped (/Users/daw/scratch/babel-duplicate-declaration-reproduction/node_modules/babel-traverse/lib/scope/index.js:189:28)
    at Object.newFn (/Users/daw/scratch/babel-duplicate-declaration-reproduction/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/Users/daw/scratch/babel-duplicate-declaration-reproduction/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/daw/scratch/babel-duplicate-declaration-reproduction/node_modules/babel-traverse/lib/path/context.js:44:14)
    at NodePath.visit (/Users/daw/scratch/babel-duplicate-declaration-reproduction/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/daw/scratch/babel-duplicate-declaration-reproduction/node_modules/babel-traverse/lib/context.js:150:16)
```

### Context
I originally encountered this trying to run already-compiled code through babel again (long story). The es2015 class transform outputs code that uses this kind of object literal syntax with methods defined via named `function` expressions. The result is that if you define a variable `foo` inside a method named `foo`, the resulting code will throw the above error if run through the babel compiler again.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.0
| node             |  6.6.0
| yarn             |  0.17.9
| Operating System | OS X 10.11.6

**Comment by MasanoriOyabu** [comment]
@davewasmer 
After all, how did you solve it?

**Comment by davewasmer** [comment]
@MasanoriOyabu I didn't. I had to work around the issue by not running babel on already transpiled code, but as far as I know, this bug is still present.
