### ISSUE TITLE
Issue with for loop in transform-regenerator

### ISSUE THREAD

**Issue by farwayer** [babel/babel#4953]
```js
async function foo() {
  for (let i; i;);
}
```

```js
ERROR in ./src/api/index.js
Module build failed: Error: .../src/api/index.js: You passed `path.replaceWith()` a falsy node, use `path.remove()` instead
at NodePath.replaceWith (.../node_modules/babel-traverse/lib/path/replacement.js:123:11)
at ForStatement (.../node_modules/babel-plugin-transform-regenerator/lib/hoist.js:61:26)
at NodePath._call (.../node_modules/babel-traverse/lib/path/context.js:76:18)
at NodePath.call (.../node_modules/babel-traverse/lib/path/context.js:48:17)
at NodePath.visit (.../node_modules/babel-traverse/lib/path/context.js:105:12)
at TraversalContext.visitQueue (.../node_modules/babel-traverse/lib/context.js:150:16)
at TraversalContext.visitMultiple (.../node_modules/babel-traverse/lib/context.js:103:17)
at TraversalContext.visit (.../node_modules/babel-traverse/lib/context.js:190:19)
at Function.traverse.node (.../node_modules/babel-traverse/lib/index.js:114:17)
at traverse (.../node_modules/babel-traverse/lib/index.js:79:12)
at NodePath.traverse (.../node_modules/babel-traverse/lib/path/index.js:144:25)
at exports.hoist (.../node_modules/babel-plugin-transform-regenerator/lib/hoist.js:44:23)
at PluginPass.exit (.../node_modules/babel-plugin-transform-regenerator/lib/visit.js:77:35)
at newFn (.../node_modules/babel-traverse/lib/visitors.js:276:21)
at NodePath._call (.../node_modules/babel-traverse/lib/path/context.js:76:18)
at NodePath.call (.../node_modules/babel-traverse/lib/path/context.js:48:17)
@ ./src/index.js 19:11-25
@ multi main
```

All ok if variable is initialized:
```js
async function foo() {
  for (let i = 0; i;);
}
```

**Comment by cellog** [comment]
*every(callback, thisArg = undefined) {
    const cb = thisArg ? callback.bind(thisArg) : callback
    for (let i; i < this.arr.length; i++) {

    }
    return true
  }

I have exactly the same issue.

**Comment by hzoo** [comment]
The implementation has been moved to https://github.com/facebook/regenerator/issues so I would check there (search issues first), and it's possible we are on the older version
