### ISSUE TITLE
Using regenerator-transform to implement babel-plugin-transform-regenerator broke all production apps

### ISSUE THREAD

**Issue by jalooc** [babel/babel#4982]
Commit [16c84fb35393157dc94d238b669140d08e8802c6](https://github.com/babel/babel/commit/16c84fb35393157dc94d238b669140d08e8802c6) ruined our `babel-cli` with `NODE_ENV=production` usage and errored builds in all of our applications.

One of the symptoms was getting `TypeError: require(...) is not a function` which looks like a sign of circular dependency ([source](https://github.com/babel/babel/commit/16c84fb35393157dc94d238b669140d08e8802c6#commitcomment-20134981) by [rroslaniec](https://github.com/rroslaniec)).

We managed to revive our apps by adding `"babel-plugin-transform-regenerator": "6.16.1"` as an explicit dependency, maybe that will help in finding a solution for the problem.

**Comment by hzoo** [comment]
Thanks for the issue!

Is the stack trace not any longer? It would be great if you could provide the code/config/stack trace that it's failing at to be able to debug this. Otherwise we'll need to just repro by trying out code + regenerator. cc @benjamn

**Comment by alexduan** [comment]
This completely destroyed our app as well. Looks like our dependency on babel-preset-es2015 caused this latest version to load, and then we started getting a bunch of resolve failed errors. It literally took hours to hunt this down. Shrinkwrapping to 6.16.1 solved our problems.

> resolve failed:  { Error: Cannot find module 'webpack-core'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.requireRelative.resolve (/tmp/scp-web/node_modules/require-relative/index.js:30:17)
    at resolve (/tmp/scp-web/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/tmp/scp-web/node_modules/modify-babel-preset/lib/serialize.js:83:11)
    at /tmp/scp-web/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/tmp/scp-web/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/tmp/scp-web/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/tmp/scp-web/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/tmp/scp-web/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17) code: 'MODULE_NOT_FOUND' } webpack-core

**Comment by loganfsmyth** [comment]
@developit Any thoughts on what would cause an error like this from `modify-babel-preset`?

**Comment by brokenalarms** [comment]
I confirm that `npm install`ing at some point broke all our tests based on `require('babel-core/register')`, and that installing/pinning the `babel-plugin-transform-regenerator@6.16.1` fixes it. Believe I know why in my case, which may help to solve the overriding issue.

Initial error is:

```
ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/regenerator-transform/package.json" at 0, attempted to resolve relative to "/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/regenerator-transform" (While processing preset: "/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-preset-es2015/index.js")
    at /Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/lib/index.js:3:18)
    at Module._compile (module.js:570:32)
    at loader (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-preset-es2015/index.js:23:6)
    at Module._compile (module.js:570:32)
    at loader (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pitchshifter/work/anx-sdk/anx-data-plane/test/index.js:4:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Installing `babel-plugin-transform-runtime` manually at the app level fixes this error but introduces a new one:

```
Error: Options {"loose":true} passed to /Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-preset-es2015/index.js which does not accept options. (While processing preset: "/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-preset-es2015/index.js") (While processing preset: "/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-preset-es2015/index.js")
    at /Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:320:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-plugin-transform-regenerator/lib/index.js:3:18)
    at Module._compile (module.js:570:32)
    at loader (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-preset-es2015/index.js:23:6)
    at Module._compile (module.js:570:32)
    at loader (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pitchshifter/work/anx-sdk/anx-data-plane/test/index.js:4:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/Users/pitchshifter/work/anx-sdk/anx-data-plane/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

From this, I believe that the different version of `transform-regenerator` switched to specifies an out-of-date version of `babel-preset-es2015` (6.9.0) which does not support the `{loose: true}` option (as evidenced [here](https://github.com/jhen0409/babel-preset-es2015-node6/issues/7)) which is then nonetheless passed to it in its `package.json`.

Hope that helps - we have addressed this for the moment by manually installing `transform-runtime` and `babel-plugin-transform-regenerator` locked to 6.16.1, and whilst this only happens to break our tests, it does make me very nervous and we can't push any changes until we know it's resolved. I can understand the emotive language given this does completely break in-production apps. Thank you for your work on this!

**Comment by brokenalarms** [comment]
This issue has a large scope of effect, since following any user's next casual `npm install`, it basically will prevent running of every single piece of code which makes use of `babel-core/register`. For us this fortunately only includes tests, but I can imagine it hitting others a lot harder.

**Comment by melbourne2991** [comment]
Getting the same error as @brokenalarms, also using babel/register for tests (with jasmine). Oddly it only started breaking when I added the "only" option to babel, I also tried the "ignore" option which had the same effect.

```
require('babel-register')({
  only: ['**/*.js'],
  presets: ['es2015']
});

```

package.json
```
  "devDependencies": {
    "angular-mocks": "^1.5.7",
    "babel-core": "^6.17.0",
    "babel-loader": "^6.2.5",
    "babel-preset-es2015": "^6.16.0",
    "babel-register": "^6.16.3",
    "eslint": "^3.7.1",
    "html-loader": "^0.4.4",
    "jasmine": "^2.5.2",
    "jasmine-spec-reporter": "^2.7.0",
    "webpack": "^1.13.2"
  },
```

**Comment by leafi** [comment]
@loganfsmyth You can reproduce the issue on react-infinite-calendar, like so:

```
git clone https://github.com/clauderic/react-infinite-calendar.git
cd react-infinite-calendar
git checkout ddecb1a # just in case react-infinite-calendar changes in the mean time
npm i && npm run build
```

Attached is a shell log of what happens & the log file npm encouraged me to provide.

It has the characteristic resolve failed: Error: Cannot find module 'caniuse-db' and resolve failed: Error: Cannot find module babel-runtime messages.

(We are currently working around this by forcing babel-plugin-transform-regenerator to be exactly 6.16.1 in the package.json file, and recently by fixing babel-preset-es2015 to be exactly 6.16.0, too - as with the most recent release of babel-preset-es2015 npm can't ensure all versions of babel-plugin-transform-regenerator in the entire tree are 6.16.1.)

[shell.txt](https://github.com/babel/babel/files/794230/shell.txt)

[2017-02-22T16_59_23_935Z-debug.log.txt](https://github.com/babel/babel/files/794233/2017-02-22T16_59_23_935Z-debug.log.txt)

**Comment by existentialism** [comment]
@leafi this looks like an issue with an old version of `babel-preset-es2015-rollup`/`babel-modify-preset`... (evidence is the error from relative-require).

If you bump to `babel-preset-es2015-rollup@3.0.0` it builds fine.

**Comment by leafi** [comment]
@existentialism It's that simple? Ah, wonderful! We'll get on that soon then :)

Thanks for debugging it!

**Comment by existentialism** [comment]
@leafi sure! definitely report back if you run into any other issues though.

**Comment by gap777** [comment]
I've followed the suggestions on this thread, but now I get this error:

```
SyntaxError: /myAppPath/node_modules/graceful-fs/graceful-fs.js: Invalid number (80:53)
78 |     switch (req.constructor.name) {
  79 |       case 'OpenReq':
> 80 |         open(req.path, req.flags || "r", req.mode || 0777, req.cb)
     |                                                                                     ^
  81 |         break
  82 |       case 'ReaddirReq':
  83 |         readdir(req.path, req.cb)
```

Any suggestions?

**Comment by loganfsmyth** [comment]
@gap777 Best not to mix questions in with an unrelated issue. We have our recommended support channels documented in our README https://github.com/babel/babel#looking-for-support and we'd be happy to help via one of those channels.

**Comment by gap777** [comment]
@loganfsmyth I was trying to suggest that what I'm seeing is related somehow to the problem talked about here... since I had the same symptoms as @brokenalarms, and tried his fix, and then got this...  if my issue is clearly not related to this thread, my apologies...

**Comment by loganfsmyth** [comment]
Gotcha, sorry. Your issue is that you are running Babel on `graceful-fs` when you should not be. Usually Babel skips files in `node_modules` entirely, so your setup may be overriding that.

**Comment by gap777** [comment]
@loganfsmyth I am indeed overriding that, and I see that I am unintentionally babelizing graceful-fs within my node_modules. Please excuse me.
