### ISSUE TITLE
latest babel-plugin-transform-regenerator causing errors when bundling with rollup

### ISSUE THREAD

**Issue by travi** [babel/babel#4985]
### Input Code

you can find one of the projects impacted by this problem here: https://github.com/travi/hapi-react-router. running the `build` script with the latest dependencies will reproduce the problem

```
$ npm run build
```

### Babel Configuration (.babelrc, package.json, cli command)

```json
{
  "presets": [
    "es2015-node",
    "stage-3",
    "react"
  ]
}
```

### Expected Behavior
if i manually install `v6.16.1` of `babel-plugin-transform-regenerator`, the `rollup` build succeeds.

<details>
  <summary>successful output</summary>

```
> rollup -c

Treating 'react' as external dependency
Treating 'react-dom/server' as external dependency
Treating 'react-router' as external dependency
Treating 'boom' as external dependency
Treating 'react-router' as external dependency
Treating 'redial' as external dependency
```
</details>

### Current Behavior

with the latest (`6.20.0`), i get the following error, along with output that suggests steps that i am surprised to see executing:

<details>
  <summary>error output</summary>

```
> rollup -c
resolve failed:  { Error: Cannot find module '@greenkeeper'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/home/travis/build/travi/hapi-react-router/node_modules/require-relative/index.js:30:17)
    at resolve (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/travis/build/travi/hapi-react-router/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12) code: 'MODULE_NOT_FOUND' } @greenkeeper
resolve failed:  { Error: Cannot find module 'husky'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/home/travis/build/travi/hapi-react-router/node_modules/require-relative/index.js:30:17)
    at resolve (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/travis/build/travi/hapi-react-router/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12) code: 'MODULE_NOT_FOUND' } husky
info postpublish Use @travi/hapi-react-router@0.0.0-semantically-released
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/home/travis/build/travi/hapi-react-router/node_modules/require-relative/index.js:30:17)
    at resolve (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/travis/build/travi/hapi-react-router/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12) code: 'MODULE_NOT_FOUND' } babel-runtime
resolve failed:  { Error: Cannot find module '@travi'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/home/travis/build/travi/hapi-react-router/node_modules/require-relative/index.js:30:17)
    at resolve (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/travis/build/travi/hapi-react-router/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12) code: 'MODULE_NOT_FOUND' } @travi
resolve failed:  { Error: Cannot find module '@semantic-release'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/home/travis/build/travi/hapi-react-router/node_modules/require-relative/index.js:30:17)
    at resolve (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/travis/build/travi/hapi-react-router/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12) code: 'MODULE_NOT_FOUND' } @semantic-release
resolve failed:  { Error: Cannot find module '@bahmutov'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/home/travis/build/travi/hapi-react-router/node_modules/require-relative/index.js:30:17)
    at resolve (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/travis/build/travi/hapi-react-router/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/travis/build/travi/hapi-react-router/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/travis/build/travi/hapi-react-router/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12) code: 'MODULE_NOT_FOUND' } @bahmutov
Treating 'react' as external dependency
Treating 'react-dom/server' as external dependency
Treating 'react-router' as external dependency
Treating 'boom' as external dependency
Treating 'react-router' as external dependency
Treating 'redial' as external dependency
(node:1809) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Aborting commit due to empty commit message.
```
</details>

you can see this output in [this build](https://travis-ci.org/travi/hapi-react-router/builds/182713629) by expanding the `$ npm run semantic-release` block at the end of the output

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  
| node             | v7.2.0
| npm              | v3.10.9
| Operating System | OSX 10.11.6 & Travis-CI

**Comment by Kovensky** [comment]
Hm... the problem seems to be triggered by `babel-modify-preset`?

Try replacing `"babel-preset-es2015-rollup"` with `["babel-preset-es2015", { "modules": false }]`, see if avoiding that module helps.

**Comment by travi** [comment]
making that change does, in fact, enable the build to complete successfully again, but would then require me to include the external-helpers plugin to get back to the same functionality that `babel-preset-es2015-rollup` provides.

are you suggesting this as a work around or a step toward providing better info for fixing the rollup preset? if you could help me understand details so i can file a better issue there, it would be appreciated.

**Comment by travi** [comment]
also, for anyone looking through this thread later, this might be helpful context:

```
$ npm ls babel-plugin-transform-regenerator
@travi/hapi-react-router@0.0.0-semantically-released /Users/admin/development/travi/hapi-react-router
└─┬ babel-preset-es2015-rollup@1.2.0
  └─┬ babel-preset-es2015@6.18.0
    └── babel-plugin-transform-regenerator@6.20.0 
```

**Comment by existentialism** [comment]
@travi it does look like `preset-es2015-rollup` needs to [get updated](https://github.com/rollup/babel-preset-es2015-rollup/issues/18).

As @Kovensky pointed out, you can effectively do the same by changing your babel config to:

```
 {
  "presets": [
    ["es2015", { "modules": false }]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

**Comment by travi** [comment]
thanks for the clarification. i agree that it probably makes the most sense to just update to use `babel-preset-es2015` directly at this point.

**Comment by travi** [comment]
an update was rolled out for the rollup preset that resolved my issue
