### ISSUE TITLE
Couldn't find preset "transform-es2015-classes" relative to directory

### ISSUE THREAD

**Issue by AuthorProxy** [babel/babel#4998]
just begin testing ie8 support and get stucked with this error: 

```
$ babel --plugins transform-es2015-classes home.js
Error: Couldn't find preset "transform-es2015-classes" relative to directory "C:\\Users\\kostyukova\\YandexDisk\\Learning\\NodeWebpack\\webpack-screencast-master\\01-intro"
    at C:\Users\kostyukova\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Users\kostyukova\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:270:20)
    at OptionManager.mergePresets (C:\Users\kostyukova\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:259:10)
    at OptionManager.mergeOptions (C:\Users\kostyukova\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:244:14)
    at OptionManager.init (C:\Users\kostyukova\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at File.initOptions (C:\Users\kostyukova\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\Users\kostyukova\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (C:\Users\kostyukova\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\Users\kostyukova\AppData\Roaming\npm\node_modules\babel-cli\lib\babel\util.js:50:22)
```

.babelrc config:
```
{
  "plugins": ["transform-runtime", "transform-es3-member-expression-literals", "transform-es3-property-literals"],
  "presets": [["transform-es2015-classes", {
    "loose": true
  }], ["env", {
    "targets": {
      "browsers": ["ie >= 8", "> 3%", "last 3 version"]
    },
    "loose": true
  }]]
}
```

using webpack loader and direct call ```babel --plugins transform-es2015-classes home.js``` produce the same error

package.json:
```
{
  "name": "01-intro",
  "version": "1.0.0",
  "description": "",
  "main": "build.js",
  "dependencies": {
    "babel-runtime": "^6.20.0"
  },
  "devDependencies": {
    "babel-core": "^6.20.0",
    "babel-loader": "^6.2.9",
    "babel-plugin-transform-es2015-classes": "^6.18.0",
    "babel-plugin-transform-es3-member-expression-literals": "^6.8.0",
    "babel-plugin-transform-es3-property-literals": "^6.8.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-polyfill": "^6.20.0",
    "babel-preset-env": "^1.1.1",
    "webpack": "^1.14.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

What am I doing wrong?

**Comment by hzoo** [comment]
First thing I can see is that ` "presets": [["transform-es2015-classes", {` isn't a preset, it's a plugin

**Comment by hzoo** [comment]
Also it looks like you are using env which already includes the class plugin?

**Comment by AuthorProxy** [comment]
@hzoo  yes it includes and you are right, I maked mistake, but before I check source code and notice that it includes "transform-es2015-classes", and everything was ok, except that 'default' problem arise whenever I use classes. So the problem is still there 'default' not escaped when I use classes.

**Comment by hzoo** [comment]
Ok that's a different issue, and maybe we can add the es3 transforms for ie in env (separate issue)

**Comment by AuthorProxy** [comment]
Should notice that at other places like ```export default``` it work good with current config, but not at class conversion via ```env```, should I create a new bug for this?

**Comment by hzoo** [comment]
Can you search other issues for "default" or "es3" ie, etc first? You can make another issue to add es3 transforms to env itself if you want so you don't have to do it manually.
