### ISSUE TITLE
Cannot find module 'react/lib/ReactDOMServer

### ISSUE THREAD

**Issue by EasonWang01** [babel/babel#5009]
```

Error: Cannot find module 'react/lib/ReactDOMServer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/etc/nginx/sites-available/React-router-Redux-isomorphic-Boilerplate/node_modules/react-dom/server.js:3:18)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/etc/nginx/sites-available/React-router-Redux-isomorphic-Boilerplate/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/etc/nginx/sites-available/React-router-Redux-isomorphic-Boilerplate/src/server/server.js:47:1)
    at Module._compile (module.js:570:32)
    at loader (/etc/nginx/sites-available/React-router-Redux-isomorphic-Boilerplate/node_modules/babel-register/lib/node.js:144:5)
```

enrty
```
require('babel-register')({
  presets: ['es2015', 'react', 'stage-0']
});
require.extensions['.scss'] = () => {
  return;
};
require.extensions['.css'] = () => {
  return;
};
require('./server');
```

what might cause this problem ?thanks

**Comment by xtuc** [comment]
Could you please provide more information on your version and context.

At first look I think you are searching for `react-dom/server`.

**Comment by EasonWang01** [comment]
{
  "dependencies": {
    "axios": "^0.15.2",
    "babel-core": "^6.4.5",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.2.2",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-react-hmre": "^1.1.0",
    "babel-register": "^6.16.3",
    "body-parser": "^1.15.2",
    "connect-mongo": "^1.3.2",
    "cookie-parser": "^1.4.3",
    "css-loader": "^0.26.0",
    "eslint": "^3.8.1",
    "eslint-config-airbnb": "^12.0.0",
    "eslint-plugin-react": "^6.4.1",
    "express": "^4.13.4",
    "express-session": "^1.14.2",
    "imgur": "^0.2.0",
    "jsonwebtoken": "^7.1.9",
    "material-ui": "^0.16.1",
    "mongodb": "^2.2.11",
    "mongoose": "^4.6.7",
    "mysql": "^2.12.0",
    "nodemailer": "^2.6.4",
    "prore": "^1.0.0",
    "react": "^15.3.2",
    "react-dom": "^0.14.7",
    "react-redux": "^4.4.5",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.2",
    "react-rte": "^0.11.0",
    "react-tap-event-plugin": "^1.0.0",
    "redis": "^2.6.3",
    "redux": "^3.4.0",
    "redux-logger": "^2.6.1",
    "redux-thunk": "^2.0.1",
    "socket.io": "^1.5.1",
    "style-loader": "^0.13.1",
    "webpack": "^1.12.13",
    "webpack-dev-middleware": "^1.5.1",
    "webpack-hot-middleware": "^2.6.4"
  },
  "devDependencies": {
    "babel-preset-stage-0": "^6.5.0"
  }
}

**Comment by EasonWang01** [comment]
about react itself not babel.
https://github.com/facebook/react/issues/8588
