### ISSUE TITLE
babel-register fails on Linux under Node 4.3.2 specifically.

### ISSUE THREAD

**Issue by resistdesign** [babel/babel#5033]
On, my local machine macOS 10.12.1 `babel-register` works fine under Node 4.3.2. On Travis, it works fine under Node versions 6, 6.1 and 5.11, but for some reason, during the Travis build/test under Node 4.3.2, it just can't find `babel-runtime/regenerator`. 

Here is my [package.json](https://github.com/resistdesign/incarnate/blob/master/package.json).

Here is the raw Travis log:

```bash

Worker information
hostname: ip-10-12-9-52:29dd9498-7d66-4d46-baf9-d9cc8e2a9fb4
version: v2.5.0-8-g19ea9c2 https://github.com/travis-ci/worker/tree/19ea9c20425c78100500c7cc935892b47024922c
instance: f986739:travis:node_js
startup: 592.774995ms
Build system information
Build language: node_js
Build group: stable
Build dist: precise
Build id: 186403304
Job id: 186403308
travis-build version: 7cac7d393
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"

$ export DEBIAN_FRONTEND=noninteractive
W: Size of file /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_precise-security_restricted_binary-amd64_Packages.gz is not what the server reported 13782 14904
W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-updates_restricted_binary-amd64_Packages.gz is not what the server reported 19576 20785
W: Size of file /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_precise-security_restricted_binary-i386_Packages.gz is not what the server reported 13751 14885
W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-updates_restricted_binary-i386_Packages.gz is not what the server reported 19521 20707
W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-backports_multiverse_source_Sources.gz is not what the server reported 5886 5888
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_travis-ci_zero-mq_ubuntu_dists_precise_main_binary-amd64_Packages.gz is not what the server reported 832 1195
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-amd64_Packages.gz is not what the server reported 33653 36677
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-i386_Packages.gz is not what the server reported 33699 36733
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libc-bin libc-dev-bin libc6-dev
Suggested packages:
  glibc-doc
The following packages will be upgraded:
  libc-bin libc-dev-bin libc6 libc6-dev
4 upgraded, 0 newly installed, 0 to remove and 250 not upgraded.
Need to get 8,840 kB of archives.
After this operation, 14.3 kB disk space will be freed.
Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6-dev amd64 2.15-0ubuntu10.15 [2,943 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-dev-bin amd64 2.15-0ubuntu10.15 [84.7 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-bin amd64 2.15-0ubuntu10.15 [1,177 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6 amd64 2.15-0ubuntu10.15 [4,636 kB]
Fetched 8,840 kB in 0s (36.2 MB/s)
Preconfiguring packages ...
(Reading database ... 69991 files and directories currently installed.)
Preparing to replace libc6-dev 2.15-0ubuntu10.10 (using .../libc6-dev_2.15-0ubuntu10.15_amd64.deb) ...
Unpacking replacement libc6-dev ...
Preparing to replace libc-dev-bin 2.15-0ubuntu10.10 (using .../libc-dev-bin_2.15-0ubuntu10.15_amd64.deb) ...
Unpacking replacement libc-dev-bin ...
Preparing to replace libc-bin 2.15-0ubuntu10.10 (using .../libc-bin_2.15-0ubuntu10.15_amd64.deb) ...
Unpacking replacement libc-bin ...
Processing triggers for man-db ...
Setting up libc-bin (2.15-0ubuntu10.15) ...
(Reading database ... 69990 files and directories currently installed.)
Preparing to replace libc6 2.15-0ubuntu10.10 (using .../libc6_2.15-0ubuntu10.15_amd64.deb) ...
Unpacking replacement libc6 ...
Setting up libc6 (2.15-0ubuntu10.15) ...
Setting up libc-dev-bin (2.15-0ubuntu10.15) ...
Setting up libc6-dev (2.15-0ubuntu10.15) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
$ git clone --depth=50 --branch=master https://github.com/resistdesign/incarnate.git resistdesign/incarnate
Cloning into 'resistdesign/incarnate'...
remote: Counting objects: 169, done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 169 (delta 83), reused 97 (delta 27), pack-reused 0
Receiving objects: 100% (169/169), 25.71 KiB | 0 bytes/s, done.
Resolving deltas: 100% (83/83), done.
Checking connectivity... done.

$ cd resistdesign/incarnate
$ git checkout -qf a4acffa37fb005d344ae0ad8d56a6aa9213b40a9

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
Updating nvm to v0.32.0
$ nvm install 4.3.2
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v4.3.2 (npm v2.14.12)

Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
$ node --version
v4.3.2
$ npm --version
2.14.12
$ nvm --version
0.32.0
$ npm install 
npm WARN optional dep failed, continuing fsevents@1.0.15
mocha@3.2.0 node_modules/mocha
├── diff@1.4.0
├── browser-stdout@1.3.0
├── escape-string-regexp@1.0.5
├── growl@1.9.2
├── json3@3.3.2
├── supports-color@3.1.2 (has-flag@1.0.0)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@7.0.5 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6, minimatch@3.0.3)
└── lodash.create@3.1.1 (lodash._basecreate@3.0.3, lodash._isiterateecall@3.0.9, lodash._baseassign@3.2.0)

expect@1.20.2 node_modules/expect
├── is-regex@1.0.3
├── object-keys@1.0.11
├── object-inspect@1.2.1
├── tmatch@2.0.1
├── has@1.0.1 (function-bind@1.1.0)
├── define-properties@1.1.2 (foreach@2.0.5)
└── is-equal@1.5.3 (is-arrow-function@2.0.3, is-number-object@1.0.3, is-date-object@1.0.1, is-string@1.0.4, is-callable@1.1.3, is-boolean-object@1.0.0, is-symbol@1.0.1, is-generator-function@1.0.6, object.entries@1.0.4)

npm-watch@0.1.7 node_modules/npm-watch
├── through2@2.0.3 (xtend@4.0.1, readable-stream@2.2.2)
└── nodemon@1.11.0 (ignore-by-default@1.0.1, undefsafe@0.0.3, es6-promise@3.3.1, debug@2.5.1, minimatch@3.0.3, touch@1.0.0, lodash.defaults@3.1.2, ps-tree@1.1.0, update-notifier@0.5.0, chokidar@1.6.1)

event-emitter@0.3.4 node_modules/event-emitter
├── d@0.1.1
└── es5-ext@0.10.12 (es6-symbol@3.1.0, es6-iterator@2.0.0)

babel-register@6.18.0 node_modules/babel-register
├── home-or-tmp@2.0.0 (os-tmpdir@1.0.2, os-homedir@1.0.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── source-map-support@0.4.7 (source-map@0.5.6)
├── babel-core@6.21.0 (babel-template@6.16.0, babel-messages@6.8.0, slash@1.0.0, path-is-absolute@1.0.1, babel-helpers@6.16.0, private@0.1.6, json5@0.5.1, babylon@6.14.1, convert-source-map@1.3.0, source-map@0.5.6, babel-types@6.21.0, debug@2.5.1, minimatch@3.0.3, babel-code-frame@6.20.0, babel-traverse@6.21.0, babel-generator@6.21.0)
├── babel-runtime@6.20.0 (regenerator-runtime@0.10.1)
├── lodash@4.17.2
└── core-js@2.4.1

babel-plugin-transform-object-rest-spread@6.20.2 node_modules/babel-plugin-transform-object-rest-spread
├── babel-plugin-syntax-object-rest-spread@6.13.0
└── babel-runtime@6.20.0 (regenerator-runtime@0.10.1, core-js@2.4.1)

babel-plugin-transform-runtime@6.15.0 node_modules/babel-plugin-transform-runtime
└── babel-runtime@6.20.0 (regenerator-runtime@0.10.1, core-js@2.4.1)

babel-plugin-transform-class-properties@6.19.0 node_modules/babel-plugin-transform-class-properties
├── babel-plugin-syntax-class-properties@6.13.0
├── babel-template@6.16.0 (babylon@6.14.1, babel-types@6.21.0, babel-traverse@6.21.0, lodash@4.17.2)
├── babel-helper-function-name@6.18.0 (babel-helper-get-function-arity@6.18.0, babel-types@6.21.0, babel-traverse@6.21.0)
└── babel-runtime@6.20.0 (regenerator-runtime@0.10.1, core-js@2.4.1)

babel-preset-env@1.1.4 node_modules/babel-preset-env
├── babel-plugin-syntax-trailing-function-commas@6.20.0
├── browserslist@1.5.1 (caniuse-db@1.0.30000602)
├── babel-plugin-transform-es2015-for-of@6.18.0 (babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-literals@6.8.0 (babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-modules-umd@6.18.0 (babel-template@6.16.0, babel-runtime@6.20.0)
├── babel-plugin-check-es2015-constants@6.8.0 (babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-typeof-symbol@6.18.0 (babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-duplicate-keys@6.8.0 (babel-types@6.21.0, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-template-literals@6.8.0 (babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-arrow-functions@6.8.0 (babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-block-scoped-functions@6.8.0 (babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-destructuring@6.19.0 (babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-shorthand-properties@6.18.0 (babel-types@6.21.0, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-modules-amd@6.18.0 (babel-template@6.16.0, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-spread@6.8.0 (babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-function-name@6.9.0 (babel-types@6.21.0, babel-helper-function-name@6.18.0, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-block-scoping@6.21.0 (babel-template@6.16.0, babel-types@6.21.0, babel-traverse@6.21.0, lodash@4.17.2, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-unicode-regex@6.11.0 (regexpu-core@2.0.0, babel-helper-regex@6.18.0, babel-runtime@6.20.0)
├── babel-plugin-transform-exponentiation-operator@6.8.0 (babel-plugin-syntax-exponentiation-operator@6.13.0, babel-helper-builder-binary-assignment-operator-visitor@6.18.0, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-computed-properties@6.8.0 (babel-template@6.16.0, babel-helper-define-map@6.18.0, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-sticky-regex@6.8.0 (babel-helper-regex@6.18.0, babel-types@6.21.0, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-object-super@6.8.0 (babel-helper-replace-supers@6.18.0, babel-runtime@6.20.0)
├── babel-plugin-transform-async-to-generator@6.16.0 (babel-plugin-syntax-async-functions@6.13.0, babel-helper-remap-async-to-generator@6.20.3, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-modules-systemjs@6.19.0 (babel-template@6.16.0, babel-helper-hoist-variables@6.18.0, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-modules-commonjs@6.18.0 (babel-plugin-transform-strict-mode@6.18.0, babel-template@6.16.0, babel-types@6.21.0, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-parameters@6.21.0 (babel-helper-get-function-arity@6.18.0, babel-helper-call-delegate@6.18.0, babel-template@6.16.0, babel-types@6.21.0, babel-traverse@6.21.0, babel-runtime@6.20.0)
├── babel-plugin-transform-es2015-classes@6.18.0 (babel-messages@6.8.0, babel-helper-replace-supers@6.18.0, babel-helper-optimise-call-expression@6.18.0, babel-helper-function-name@6.18.0, babel-template@6.16.0, babel-helper-define-map@6.18.0, babel-types@6.21.0, babel-traverse@6.21.0, babel-runtime@6.20.0)
└── babel-plugin-transform-regenerator@6.21.0 (regenerator-transform@0.9.8)

$ npm test

> @resistdesign/incarnate@0.0.0 test /home/travis/build/resistdesign/incarnate
> mocha -u exports --require babel-register -- '**/*.spec.js'

module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/resistdesign/incarnate/src/Incarnate.spec.js:3:20)
    at Module._compile (module.js:409:26)
    at loader (/home/travis/build/resistdesign/incarnate/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/resistdesign/incarnate/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/travis/build/resistdesign/incarnate/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/resistdesign/incarnate/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/home/travis/build/resistdesign/incarnate/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/home/travis/build/resistdesign/incarnate/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
npm ERR! Test failed.  See above for more details.


The command "npm test" exited with 1.

Done. Your build exited with 1.
```

**Comment by loganfsmyth** [comment]
When you use `babel-plugin-transform-runtime`, you need to have `babel-runtime` in your `package.json` `dependencies` section. It is working on Node 5 and 6 by chance because of `npm@3.x`'s `node_modules` flattening, but will fail if you installed without dev dependencies or install with `npm@2`.

**Comment by resistdesign** [comment]
Ah, makes sense, ty!
