### ISSUE TITLE
Babel Template Yield statement fails

### ISSUE THREAD

**Issue by jtenner** [babel/babel#5055]
```javascript
require('babel-template')(`yield A`)({ A: require('babel-types').identifier('d') })
```
I've had to work around this by using `t.yieldExpression()` manually.

```text
SyntaxError: Unexpected token, expected ; (1:6)
    at Parser.pp$5.raise (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babylon\lib\index.js:4246:13)
    at Parser.pp.unexpected (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babylon\lib\index.js:1627:8)
    at Parser.pp.semicolon (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babylon\lib\index.js:1608:38)
    at Parser.pp$1.parseExpressionStatement (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babylon\lib\index.js:2103:8)
    at Parser.pp$1.parseStatement (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babylon\lib\index.js:1779:17)
    at Parser.pp$1.parseBlockBody (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babylon\lib\index.js:2133:21)
    at Parser.pp$1.parseTopLevel (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babylon\lib\index.js:1645:8)
    at Parser.parse (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babylon\lib\index.js:1537:17)
    at Object.parse$1 [as parse] (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babylon\lib\index.js:6466:37)
    at getAst (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babel-template\lib\index.js:29:21)from
    at exports.default (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\node_modules\babel-template\lib\index.js:12:11)
    at Object.<anonymous> (C:\Users\jtenner\Desktop\projects\babel-plugin-vn\failExample.js:1:88)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)

```
| software         | version
| ---------------- | -------
| Babel            |  ^6.21.0
| node             |  7.3.0
| npm              |  3.10.10
| Operating System |  Windows

**Comment by DrewML** [comment]
We probably need to make a change to `Babylon` to add an `allowYieldOutsideGenerator` option, similar to `allowReturnOutsideFunction` and `allowImportExportEverywhere`, which `babel-template` sets to `true` by default. I'm willing to bet `await` has the same issue with `babel-template` when not in an `async` function.

**Comment by jtenner** [comment]
Thanks for acknowledging this! I'm not sure i can help with the code changes, but I would love to help.

**Comment by jtenner** [comment]
I don't suppose there's anything I can do to help make this happen faster?  I need to get my hands dirty!

**Comment by loganfsmyth** [comment]
I wonder if we could avoid adding this to Babylon by having an option that would wrap and unwrap the content with `function*(){..}` or `async function(){ .. }`. Seems like that would be a simpler way to get this in.

**Comment by DrewML** [comment]
@loganfsmyth 👍 That'd probably be a better long term solution that adding a flag to `Babylon` every time we need to allow referencing a token in a position where it's typically not allowed

**Comment by Brenndoerfer** [comment]
I would also appreciate the possibility to pass a `allowYieldOutsideGenerator` option

**Comment by DrewML** [comment]
Maybe it would make more sense long-term for us to have a `loose` parse mode, similar to `acorn`. I can see this list of exceptions in `Babylon` growing out of hand eventually.
