### ISSUE TITLE
Crash caused by newly released babel-transform@66.23.0

### ISSUE THREAD

**Issue by nickpalmer** [babel/babel#5305]
Version 6.23.0 of babel-transform causes babel-plugin-transform-es2015-destructuring to crash while compiling our app.

Pinning to babel-tranform@6.22.1 removes the crash.

If I console.log(this.hub) in babel-transform I see that this.hub is an empty object. This should be trivial to reproduce in any app that uses destructuring..

TypeError: /Users/nick/git/app/src/server/server.js: this.hub.addHelper is not a function
    at Scope.toArray (/Users/nick/git/app/frontend/node_modules/babel-traverse/lib/scope/index.js:463:38)
    at DestructuringTransformer.toArray (/Users/nick/git/app/frontend/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:122:27)
    at DestructuringTransformer.pushArrayPattern (/Users/nick/git/app/frontend/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:277:26)
    at DestructuringTransformer.push (/Users/nick/git/app/frontend/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:110:14)
    at DestructuringTransformer.init (/Users/nick/git/app/frontend/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:317:12)
    at PluginPass.VariableDeclaration (/Users/nick/git/app/frontend/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:468:27)
    at newFn (/Users/nick/git/app/frontend/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/nick/git/app/frontend/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/nick/git/app/frontend/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/nick/git/app/frontend/node_modules/babel-traverse/lib/path/context.js:105:12)

**Comment by hzoo** [comment]
Thanks for the report, looking into it now

**Comment by rsolomon** [comment]
Same issue with our build. If we can provide any additional information to help debug just let me know.

**Comment by hzoo** [comment]
From https://github.com/babel/babel/pull/5050, need to investigate

**Comment by rsolomon** [comment]
babelrc:

```
{
  "presets": [
    "es2015",
    "es2016",
    "stage-0",
    "react"
  ],
  "plugins": [
    "add-module-exports",
    "react-hot-loader/babel",
    "transform-flow-strip-types",
    "transform-runtime",
    "transform-strict-mode"
  ]
}
```

No specific code triggers it-- it throws on every file when the unit tests are run.

**Comment by loganfsmyth** [comment]
We're reverting now.

**Comment by nickpalmer** [comment]
I think it is a mismatch with our older version of babel-core.

**Comment by loganfsmyth** [comment]
I've reverted the PR and published 6.23.1 of `babel-core` and `babel-traverse`, please install your deps and things should be back.

**Comment by hzoo** [comment]
Thanks everyone for the reports!

We'll setup better infrastructure to prevent this kind of incompatible change in the future (our issue due to being a monorepo)

**Comment by yongxu** [comment]
Sorry for this breaking PR. It passed the test when I finished it, but its been a little while. Will look into it now, really sorry for breaking the repo..

**Comment by existentialism** [comment]
@yongxu you didn't break anything! we just missed categorizing it as a breaking change, so we'll revisit landing it asap.

**Comment by hzoo** [comment]
Closing now since issue has been fixed (wanted to leave it up for a while so no one needed to make a duplicate issue)

**Comment by yongxu** [comment]
thank you for letting me know @existentialism! The `file`   was passed to `PluginPass` and something else changed it(probably assumed it was a changeable state) it somewhere else. I don't think the problem could possibly be my PR. I took a look yesterday but wasn't confident to give the conclusion. It's great to have someone confirm it!

**Comment by yongxu** [comment]
@loganfsmyth @hzoo Is there any plan for merge this back or is there any update I should work on? Please let me know if there is anything I should do :)
