### ISSUE TITLE
Plugins using Flow declarations as bindings

### ISSUE THREAD

**Issue by also** [babel/babel#5395]
Using the `syntax-flow` and `transform-es2015-classes` plugins together with `declare var` breaks a generated class method and triggers a warning (#3414):

```
You or one of the Babel plugins you are using are using Flow declarations as bindings.
```

This occurs when there is a `declare var` for a variable that is referred to in a method with the same name.

### Input Code

```js
declare var global: string;

class What {
  global() {
    return global;
  }
}
```

Full example here: https://gist.github.com/also/5e82e860699091d0df4c36f98cf2f666

### Babel Configuration (.babelrc, package.json, cli command)

```js
{"plugins": ["syntax-flow", "transform-es2015-classes"]}
```

### Expected Behavior

Adding `declare var` shouldn't change the body of the `global()` function or cause a warning.

### Current Behavior

Without a `declare var`, the compiled code works as expected. Adding it causes `global` to be rewritten to `_global`, which doesn't work.

```js
var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

declare var _global: string;

let What = function () {
  function What() {
    _classCallCheck(this, What);
  }

  _createClass(What, [{
    key: "global",
    value: function global() {
      return _global;
    }
  }]);

  return What;
}();
```

`console.trace` on the error message as suggested logs
```
Trace:
        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 6.8. To find out the caller, grep for this
        message and change it to a `console.trace()`.

    at Scope.warnOnFlowBinding (/Users/rberdeen/work/scratch/babel-flow-bug/node_modules/babel-traverse/lib/scope/index.js:1015:15)
    at Scope.getBinding (/Users/rberdeen/work/scratch/babel-flow-bug/node_modules/babel-traverse/lib/scope/index.js:1025:32)
    at Scope.getBindingIdentifier (/Users/rberdeen/work/scratch/babel-flow-bug/node_modules/babel-traverse/lib/scope/index.js:1034:21)
    at Scope.bindingIdentifierEquals (/Users/rberdeen/work/scratch/babel-flow-bug/node_modules/babel-traverse/lib/scope/index.js:1010:17)
    at Renamer.Scope (/Users/rberdeen/work/scratch/babel-flow-bug/node_modules/babel-traverse/lib/scope/lib/renamer.js:30:21)
    at Renamer.newFn (/Users/rberdeen/work/scratch/babel-flow-bug/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/Users/rberdeen/work/scratch/babel-flow-bug/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/rberdeen/work/scratch/babel-flow-bug/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/rberdeen/work/scratch/babel-flow-bug/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/rberdeen/work/scratch/babel-flow-bug/node_modules/babel-traverse/lib/context.js:150:16)
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.23.0
| node             | 6.5.0
| npm              | Yarn v0.21.3
| Operating System | OS X 10.11.6

**Comment by hzoo** [comment]
Can you give more context into why you aren't using the flow preset/strip-types plugin and rather the syntax plugin?

**Comment by also** [comment]
I reduced the example to the simplest form I could figure out.

In my app, I'm am using `transform-flow-strip-types`. I encountered the issue where the reference to the `global` variable is changed to `_global`. While trying to track this down, I discovered that the same problem happens when just using just`syntax-flow`, and it also included the warning which seemed like it was likely related to the incorrect renaming of my `global` variable.

"using Flow declarations as bindings" seemed like it could explain how adding a flow type declaration would cause Babel to rename a variable.

**Comment by loganfsmyth** [comment]
We'll have to investigate the warning message itself, since this seems like probably not what we want.

That said, the transformation itself seems correct. You've declared a variable named `global` but it is scoped inside the module file itself, so it is not a global variable, and since it is scoped that way, Babel deems it safe to rename. I think to declare a real global, you'd need a flow declaration file?

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/blob/2374062bbdfe8815892d64bd797298805db8b150/packages/babel-traverse/src/scope/index.js#L914-L918

Do we want to remove flow bindings in Babel 7?

**Comment by ohtangza** [comment]
Any news for this?
