### ISSUE TITLE
babel-plugin-transform-react-constant-elements -> Cannot read property 'declarations' of null

### ISSUE THREAD

**Issue by olslash** [babel/babel#5552]
Working example showing the bug: https://github.com/olslash/react-transform-constant-elements-bugreport

Using babel-plugin-transform-react-constant-element, when a React component defines a method that returns a function using class property syntax, not referencing the argument to the returned function leads to the build error:

`Cannot read property 'declarations' of null`

### Expected Behavior
should build correctly, as it does without babel-plugin-transform-react-constant-element
### Current Behavior
has the error: 
```
TypeError: src/BugReport.js: Cannot read property 'declarations' of null
    at Scope.push (/Users/mitchrobb/Dev/constant-bugreport/node_modules/babel-traverse/lib/scope/index.js:933:20)
    at Object.emit (/Users/mitchrobb/Dev/constant-bugreport/node_modules/babel-helper-call-delegate/lib/index.js:15:18)
    at Object.VariableDeclaration (/Users/mitchrobb/Dev/constant-bugreport/node_modules/babel-helper-hoist-variables/lib/index.js:59:15)
    at NodePath._call (/Users/mitchrobb/Dev/constant-bugreport/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/mitchrobb/Dev/constant-bugreport/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/mitchrobb/Dev/constant-bugreport/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/mitchrobb/Dev/constant-bugreport/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/mitchrobb/Dev/constant-bugreport/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/mitchrobb/Dev/constant-bugreport/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/mitchrobb/Dev/constant-bugreport/node_modules/babel-traverse/lib/index.js:114:17)
```

### Context
example use (see linked repo for an even more minimal example):

```
import React from 'react';

class BugReport extends React.Component {
    thisWontBuild = ({ color }) => (data) => {
        return <div color={ color }>does not reference data</div>;
    };

    thisBuilds = ({ color }) => (data) => {
        return <div color={ color }>{ data }</div>;
    };

    render() {
        return <SomeComponent someEl={ this.thisWontBuild({ color: 'red'}) } />
    }
}
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  latest (see example project)
| node             |  6.9.5
| npm              | 3.10.10
| Operating System | OSX

**Comment by STRML** [comment]
I can't get this to error against 7.0. Could you please verify?

**Comment by olslash** [comment]
Hi @STRML, 

I updated the package.json in the example repo with the newest v7 alpha:

```javascript
{
  ...
  "devDependencies": {
    "babel-cli": "7.0.0-alpha.9",
    "babel-plugin-transform-react-constant-elements": "7.0.0-alpha.9",
    "babel-preset-es2015": "7.0.0-alpha.9",
    "babel-preset-react": "7.0.0-alpha.9",
    "babel-preset-stage-1": "7.0.0-alpha.9"
  }
}

```

and the error still occurs:

```

> constant-bugreport@1.0.0 build /Users/mitch/Dev/react-transform-constant-elements-bugreport
> babel src -d lib

TypeError: src/BugReport.js: Cannot read property 'declarations' of null
    at Scope.push (/Users/mitch/Dev/react-transform-constant-elements-bugreport/node_modules/babel-traverse/lib/scope/index.js:918:20)
    at Object.emit (/Users/mitch/Dev/react-transform-constant-elements-bugreport/node_modules/babel-helper-call-delegate/lib/index.js:15:18)
    at Object.VariableDeclaration (/Users/mitch/Dev/react-transform-constant-elements-bugreport/node_modules/babel-helper-hoist-variables/lib/index.js:53:15)
    at NodePath._call (/Users/mitch/Dev/react-transform-constant-elements-bugreport/node_modules/babel-traverse/lib/path/context.js:71:18)
    at NodePath.call (/Users/mitch/Dev/react-transform-constant-elements-bugreport/node_modules/babel-traverse/lib/path/context.js:43:17)
    at NodePath.visit (/Users/mitch/Dev/react-transform-constant-elements-bugreport/node_modules/babel-traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/Users/mitch/Dev/react-transform-constant-elements-bugreport/node_modules/babel-traverse/lib/context.js:146:16)
    at TraversalContext.visitMultiple (/Users/mitch/Dev/react-transform-constant-elements-bugreport/node_modules/babel-traverse/lib/context.js:99:17)
    at TraversalContext.visit (/Users/mitch/Dev/react-transform-constant-elements-bugreport/node_modules/babel-traverse/lib/context.js:186:19)
    at Function.traverse.node (/Users/mitch/Dev/react-transform-constant-elements-bugreport/node_modules/babel-traverse/lib/index.js:110:17)
```

**Comment by STRML** [comment]
I can reproduce in the example repo. I'll take a closer look.

**Comment by STRML** [comment]
I cannot, however, reproduce in `7.0` dev. Double-checked it via `npm link`. I've added the above test PR to ensure we don't break it again.
