### ISSUE TITLE
babel-traverse 6.24.1 is broken because ignored directories are needed

### ISSUE THREAD

**Issue by runspired** [babel/babel#5611]
```js
Cannot find module './path'
Error: Cannot find module './path'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/babel-traverse/lib/index.js:10:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by runspired** [comment]
I suspect after further review that `npm publish` was botched and simply did not have all the requisite files included. `babel-traverse` has only added tests since it's previous publish.

**Comment by hzoo** [comment]
Wow that's really bad..

I'm looking at https://unpkg.com/babel-traverse@6.24.1/lib and it seems to be ok though? I see a path folder with an index.js file in it

**Comment by runspired** [comment]
I can confirm that's not what I'm ending up with, I'll keep digging.

**Comment by runspired** [comment]
for reference, this is what was installed:

<img width="254" alt="screen shot 2017-04-07 at 2 36 09 pm" src="https://cloud.githubusercontent.com/assets/650309/24820760/977c0b56-1b9f-11e7-8bf0-4c5f0ba747c4.png">

**Comment by hzoo** [comment]
that's really weird, I just did an `npm install babel-traverse` to 6.24.1

![screen shot 2017-04-07 at 5 37 49 pm](https://cloud.githubusercontent.com/assets/588473/24820806/00f7c732-1bb9-11e7-8bb4-2a04cbe032c5.png)

**Comment by runspired** [comment]
Yeah I've now tried an npm install and a yarn install in an empty directory and both work correctly.  I will keep digging.

**Comment by runspired** [comment]
@hzoo thanks for weighing in and sorry for crashing your friday night. This seems to be on our end. After blowing away `~/.npm` and reinstalling we're hitting this:

```
Cannot find module './whitespace'
Error: Cannot find module './whitespace'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cthoburn/Lnkd/voyager-web_trunk/node_modules/babel-generator/lib/node/index.js:18:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

So it seems we may have imported it poorly and are now bouncing around issues.
