### ISSUE TITLE
Babel not working with NODE_PATH

### ISSUE THREAD

**Issue by ORESoftware** [babel/babel#5618]
This is a bug report - I am getting this error:
```

Module build failed: Error: Couldn't find preset "latest" relative to directory "/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman-browser-polyfills/modules"
    at /Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-loader/lib/index.js:163:20)
 @ ./lib/index.js 136:9-22
 @ multi babel-polyfill ./lib/index.js

ERROR in .-browser-polyfills/modules/assert.js
Module build failed: Error: Couldn't find preset "latest" relative to directory "/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman-browser-polyfills/modules"
    at /Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/babel-loader/lib/index.js:163:20)
 @ ./lib/index.js 131:13-30
 @ multi babel-polyfill ./lib/index.js
```

Webpack should be able to find the babel modules, because I am using NODE_PATH, which allows me to store Babel deps in a particular location, and I run webpack like so:

```bash
#!/usr/bin/env bash
NODE_PATH=${NODE_PATH}:~/.suman/global/node_modules webpack
```

I have this webpack config:

```js
const path = require('path');

module.exports = {

  entry: ['babel-polyfill', './lib/index.js'],

  output: {
    path: path.resolve(__dirname + '/dist'),
    filename: 'suman.js'
  },

  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          presets: ['latest'],
          plugins: ['transform-runtime']
        }
      },
      {
        test: /(\/lib\/init\/|cli.js$)/,
        loader: 'ignore-loader'
      }
    ]
  },

  resolve: {
    alias: {
      fs: require.resolve('suman-browser-polyfills/modules/fs'),
      assert: require.resolve('suman-browser-polyfills/modules/assert')
    },
    extensions: ['.js']
  },

  node: {
    // assert: true,
    buffer: true,
    child_process: 'empty',
    cluster: 'empty',
    console: true,
    constants: true,
    crypto: 'empty',
    dgram: 'empty',
    dns: 'mock',
    domain: true,
    events: true,
    // fs: 'empty',
    http: true,
    https: true,
    module: 'empty',
    net: 'mock',
    os: true,
    path: true,
    process: true,
    punycode: true,
    querystring: true,
    readline: 'empty',
    repl: 'empty',
    stream: true,
    string_decoder: true,
    timers: true,
    tls: 'mock',
    tty: true,
    url: true,
    util: true,
    v8: 'mock',
    vm: true,
    zlib: 'empty',
  }
};
```

as you can see, in `resolve.alias`, we are referencing another project. No Babel dependencies are installed in

But that should not matter, the Babel deps needed are located in the directory referenced in NODE_PATH.

What's probably happening is that Webpack/Babel is doing a relative path lookup check for the needed Babel deps, but it should also check on NODE_PATH, if it needs to do a "pre-check".

This is a bug.

**Comment by ORESoftware** [comment]
Sorry, maybe I should file this with Webpack instead.

**Comment by loganfsmyth** [comment]
This is definitely unrelated to Webpack. Babel performs plugin/preset lookups, not Webpack.

`NODE_PATH` is considered deprecated in Node, and Babel has not historically taken it into account.

Note the [Node documentation](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders):

> These are mostly for historic reasons. You are highly encouraged to place your dependencies locally in node_modules folders. They will be loaded faster, and more reliably.

**Comment by ORESoftware** [comment]
NODE_PATH is the bomb diggity, and I love it, it probably won't be going anywhere for a long time.

But yes I see that this may be a Webpack issue. One stupid trick I used was to just do:

cd $HOME && npm install my-babel-deps

now Webpack/Babel might be able to find them there, and I won't have to install them in projects that don't need Babel. I can explain why I would have projects that don't need Babel installed - Webpack still needs to source code from separate projects. 

When I use NPM link, it will link to projects outside of my project root, then Webpack will start complaining that it can't find Babel deps.

Hence, a need / use case for NODE_PATH, amirite?

**Comment by loganfsmyth** [comment]
> When I use NPM link, it will link to projects outside of my project root, then Webpack will start complaining that it can't find Babel deps.

That's a Babel 6 bug that we couldn't fix without breaking people. In Babel 7, plugins passed to `babel-loader` will resolve relative to the cwd so npm link will no longer break for that case. It will just expect your root repo where the webpack config is to have the `node_modules` installed.

**Comment by ORESoftware** [comment]
ughh, resolving relative to cwd is always a nightmare, absolute paths are so much better.  But I guess Babel 7 might fix my problem, we'll see. So this is actually a Babel issue?

**Comment by loganfsmyth** [comment]
We expose `babel.resolvePlugin('foo', '/my-dir')` if you want to create an absolute path, but Babel has no way to do that automatically if all you tell it is

    loader: 'babel-loader',
    query: {
      presets: ['es2015'],
    },

Currently in Babel 6 that tries to find `es2015` relative to each file that gets compiled, which is why it breaks for npm linked modules. In v7 at the moment the plan is for it to resolve using the cwd.

**Comment by ORESoftware** [comment]
@loganfsmyth ok then, since NODE_PATH doesn't work, what I am planning to do is just symlink babel deps into each project (with some automated tool). Frankly it's pretty crazy to have to do this - many of these projects don't need babel deps at all directly, so it's just a waste of time and (disk) space to have to install them in each project, when only a master project is the one that needs them.

**Comment by ORESoftware** [comment]
yeah symlinks are super broken with Babel, total shame, I am having trouble developing projects side-by-side, because Babel does not work nicely with NPM link.

However, my strategy of installing Babel deps on $HOME (or similar path), works, and is working wonders.

**Comment by ThiefMaster** [comment]
So, I just tried symlinking a babelrc from somewhere else (NODE_PATH) is set as well, and ended up with this issue. FYI, this is even more annoying than https://github.com/babel/babel/issues/4970#issuecomment-370435260 since symlinking the babel config isn't too hard, but I can't do that for `node_modules` since people may have extra dependencies so I'd need to merge the two folders.. which would be a huge mess of course.

**Comment by xtuc** [comment]
@ORESoftware is this still an issue and if yes, would you mind working on it?

**Comment by nicolo-ribaudo** [comment]
I think that we can close this issue, since in `babel.config.js` you can use your own resolution algorithm.

**Comment by strongholdmedia** [comment]
While it is true that in `babel.config.js` one may start juggling with different path crunching ideas..
..this is at times absolutely contraproductive.

**Node.js**, as a concept, uses the host like it was a system service.
I do not really wish to start off if and/or why this is a bad idea. I do not use node.js for serving stuff, and that's fine with me.

However, "recently", front end development and asset management is more and more strongly tied to npm/node as well.

*Thus the need for being able to **build** packages after local changes, but in a way that keeps it upstream compatible, is very real.*

If they want, later the changes may get merged into upstream, but I figure I'd have a hard time why I customized the babel.config.js for everybody. gitignoring it is not always a good idea either.

So **is there anything specific against using NODE_PATH**?

**Comment by strongholdmedia** [comment]
I added a PR that did solve the issue for me.
If it has no probability of getting merged, *no worries*, at least it is here for reference.
I am kinda far from using Flow or anything alike anytime soon; did I miss something, please let me know.

**Again: this is necessary for building npm packages inside the global prefix without tampering with their versioned content.**

**Comment by zetavg** [comment]
Notes for a quick solution: in the meanwhile, we can use `babel.config.js` as something like:

```js
// babel.config.js
module.exports = {
  "presets": [
    require('babel-preset-airbnb')
  ]
}
```

instead of `.babelrc`:

```js
// .babelrc
{
  "presets": [
    "airbnb"
  ]
}
```

because `require` respects `NODE_ENV` while the resolver of Babel didn't.

**Comment by strongholdmedia** [comment]
Sure.. it may do. Depends on "require", I guess.
But the thing is that you'd still have to edit every freaking package to instruct **them** to use a global requirement.
Which is exactly what, for instance, I try to avoid.

**Comment by mnpenner** [comment]
@loganfsmyth Where does it say "deprecated"? On the contrary, it says:

> `NODE_PATH` is **still supported**, but is _less necessary_ now that the Node.js ecosystem has settled on a convention for locating dependent modules.

@zetavg You don't have to require in the whole module, you can just resolve it:

```js
module.exports = {
    "plugins": [
        require.resolve("@babel/plugin-syntax-dynamic-import"),
        require.resolve("@babel/plugin-syntax-bigint"),
        [require.resolve("@babel/plugin-proposal-class-properties"), {"loose": true}],
        [require.resolve("@babel/plugin-proposal-nullish-coalescing-operator"), {"loose": true}],
        [require.resolve("@babel/plugin-proposal-optional-chaining"), {"loose": true}]
    ],
    ...
```

I suspect this will be more efficient if you use `env` to conditionally load some of the plugins.

------

My use case is for docker. I want to install the `node_modules` into my image and then mount my app directory. Since `node_modules` typically resides in the app dir, it gets overridden so I moved it somewhere else:

```
FROM node:lts-alpine

ENV NODE_PATH=/usr/lib/node_modules
COPY --chown=node:node package.json yarn.lock /tmp/build/
RUN cd /tmp/build && yarn install --frozen-lockfile --production=false --check-files --modules-folder "${NODE_PATH}" && rm -r /tmp/build
```

**Comment by bdkjones** [comment]
Was there a problem with the PR that fixed this issue? It's been open for 4+ years, a fix has been supplied, and having Babel respect `NODE_PATH` would help people out. Was there some downside that led to this PR lingering for years?
