### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by zivanovicb1** [babel/babel#5678]
# Bug report

### Input Code

```js
export default registerFormReducer;
```

### Babel Configuration (package.json)

```js
"babel": {
    "presets": [
      "react",
      "stage-0",
      "env"
    ]
  }
```

### Expected Behavior

I just expected to transpile some well known es6 features.

### Current Behavior

```
SyntaxError: Unexpected token export
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (C:\Users\zivan\Desktop\trello-react\server\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\zivan\Desktop\trello-react\server\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

### Context

I have React app which I want to render on server initially. The thing is it uses most of es6 features and I realized I have to use babel to be able to render react app.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24.0
| node             |  6.10.2
| npm              |  4.5.0
| Operating System |  Windows 10

**Comment by xtuc** [comment]
It seems you are missing the [transform-es2015-modules-commonjs](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) plugin.

**Comment by hzoo** [comment]
The commonjs plugin is part of env @xtuc so that's ok. It's probably the way you are calling babel, I see you are using babel-register?

Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
