### ISSUE TITLE
Babel 7-Alpha-x regression (or babel-prest-env@2-alpha) - default async export

### ISSUE THREAD

**Issue by brokentone** [babel/babel#5738]
Bug report

### Input Code

https://github.com/brokentone/babel-7-async-default

```js
export default async function () {
  return 'test';
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["env", {
      "targets": {
        "node": 4
      }   
    }]  
  ]
}
```

### Expected Behavior
Should transpile to something like the following (babel 6 / babel-preset-env@1 version):

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }

exports.default = _asyncToGenerator(regeneratorRuntime.mark(function _callee() {
  return regeneratorRuntime.wrap(function _callee$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
          return _context.abrupt('return', 'test');

        case 1:
        case 'end':
          return _context.stop();
      }
    }
  }, _callee, this);
}));
```

### Current Behavior

```
TypeError: src/test.js: Cannot read property 'name' of null
    at plainFunction (/Users/kjacobse/Projects/example-issues/babel-7-async-default/node_modules/babel-preset-env/node_modules/babel-plugin-transform-async-to-generator/node_modules/babel-helper-remap-async-to-generator/lib/index.js:154:91)
    at exports.default (/Users/kjacobse/Projects/example-issues/babel-7-async-default/node_modules/babel-preset-env/node_modules/babel-plugin-transform-async-to-generator/node_modules/babel-helper-remap-async-to-generator/lib/index.js:18:5)
    at PluginPass.Function (/Users/kjacobse/Projects/example-issues/babel-7-async-default/node_modules/babel-preset-env/node_modules/babel-plugin-transform-async-to-generator/lib/index.js:18:56)
    at newFn (/Users/kjacobse/Projects/example-issues/babel-7-async-default/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:266:21)
    at NodePath._call (/Users/kjacobse/Projects/example-issues/babel-7-async-default/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:71:18)
    at NodePath.call (/Users/kjacobse/Projects/example-issues/babel-7-async-default/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:43:17)
    at NodePath.visit (/Users/kjacobse/Projects/example-issues/babel-7-async-default/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/Users/kjacobse/Projects/example-issues/babel-7-async-default/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:146:16)
    at TraversalContext.visitSingle (/Users/kjacobse/Projects/example-issues/babel-7-async-default/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:104:19)
    at TraversalContext.visit (/Users/kjacobse/Projects/example-issues/babel-7-async-default/node_modules/babel-cli/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:188:19)

```

### Possible Solution

I have no idea, but if I can help in any way, please let me know!

### Context

Attempting to test this alpha version on my app, revealed this issue. It seems we would be unable to use this update until this is corrected.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-alpha.9 (babel-core 7.0.0-alpha.9)
| node             | v6.9.4
| npm              | 3.10.10
| Operating System | OS X 10.10.5

**Comment by hzoo** [comment]
Looks like an issue from https://github.com/babel/babylon/issues/257 which changed the parser since there was a bug to be a FunctionDeclaration from FunctionExpression

https://github.com/babel/babel/blob/ce6f67216e2c90d1ecae758238cde2b4507984fe/packages/babel-helper-remap-async-to-generator/src/index.js#L141-L155

This means the node.id is null now and the code fails

**Comment by brokentone** [comment]
It seems like that was reverted though @hzoo? https://github.com/babel/babylon/issues/257#issuecomment-285288353

Perhaps we babel needs to update babylon?

I just looked with alpha-12, and this issue is still here.

**Comment by jridgewell** [comment]
Fixed with https://github.com/babel/babylon/issues/257#issuecomment-312442827

**Comment by brokentone** [comment]
Confirmed that the new version of babylon make this work again!
