### ISSUE TITLE
Short syntax for plugins and presets doesn't work for scoped packages 

### ISSUE THREAD

**Issue by DanielSWolf** [babel/babel#5894]
When listing plugins and presets in `.babelrc`, I can omit the prefixes `babel-plugin-` and `babel-preset-`, respectively. [According to the documentation](https://babeljs.io/docs/plugins/#plugin-preset-paths-plugin-preset-shorthand), this should work for scoped packages, too. So the following `.babelrc` file:

```json
{
  "presets": ["@mobilex/mip"]
}
```

should find the (privately scoped) package `@mobilex/babel-preset-mip`, provided that the package is installed. Instead, however, I get the following error message:

```
Error: Couldn't find preset "@mobilex/mip" relative to directory "/Users/wolf/dev/cross-mip/task-details"
      at /Users/wolf/dev/cross-mip/task-details/node_modules/babel-core/lib/transformation/file/options/option-manager.js:281:17
      at Array.map (native)
      at OptionManager.resolvePresets (/Users/wolf/dev/cross-mip/task-details/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
      at OptionManager.mergePresets (/Users/wolf/dev/cross-mip/task-details/node_modules/babel-core/lib/transformation/file/options/option-manager.js:254:10)
      at OptionManager.mergeOptions (/Users/wolf/dev/cross-mip/task-details/node_modules/babel-core/lib/transformation/file/options/option-manager.js:239:14)
      at OptionManager.init (/Users/wolf/dev/cross-mip/task-details/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
      at File.initOptions (/Users/wolf/dev/cross-mip/task-details/node_modules/babel-core/lib/transformation/file/index.js:216:65)
      at new File (/Users/wolf/dev/cross-mip/task-details/node_modules/babel-core/lib/transformation/file/index.js:137:24)
      at Pipeline.transform (/Users/wolf/dev/cross-mip/task-details/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
      at transpile (/Users/wolf/dev/cross-mip/task-details/node_modules/babel-loader/index.js:38:20)
      at Object.module.exports (/Users/wolf/dev/cross-mip/task-details/node_modules/babel-loader/index.js:131:12)
  at test/index.test.js:73
```

If I specify the full name (`@mobilex/babel-preset-mip`), it works fine.

### Expected Behavior

Given the preset string `@mobilex/mip`, Babel should try to `require` both `@mobilex/mip` and `@mobilex/babel-preset-mip`. Same goes for plugins.

### Current Behavior

As described above, an exception is thrown.

Looking at [`options-manager.js`](https://github.com/babel/babel/blob/a1dd25104a87f925ebfbf5ebf7c35e00c765bc40/packages/babel-core/src/transformation/file/options/option-manager.js#L228), the relevant code line is this:

```js
let presetLoc = resolve(`babel-preset-${val}`, dirname) || resolve(val, dirname);
```

That is, the code blindly prefixed *the entire string* with `babel-preset-`, effectively looking for `babel-preset-@mobilex/mip`, which doesn't exist. Same goes for plugins.

### Possible Solution

Check whether the string refers to a scoped plugin/preset. If it does, insert the prefix *after* the scope name.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 6.14.0
| node             | 7.10.0
| npm              | 4.2.0
| Operating System | OS X

**Comment by xtuc** [comment]
This has been fixed in Babel [v6.16.0](https://github.com/babel/babel/blob/7.0/CHANGELOG.md#v6160-2016-09-28).

I'm closing this issue for now, feel free to open it if need it.
