### ISSUE TITLE
Spreading args in inner anonymous function causes error "Cannot read property 'file' of undefined"

### ISSUE THREAD

**Issue by Lajnold** [babel/babel#5901]
### Input Code
```js
const singleFunction = (...args) => {
    // Works
    const copy = [...args];
};

const outerFunction = outer => (...args) => {
    // Doesn't work
    const copy = [...args];
};

const outerFunctionAndSlice = outer => (...args) => {
    // Works
    const copy = args.slice();
};

const outerFunctionAndSliceAndCallingOtherFunction = outer => (...args) => {
    // Doesn't work
    const copy = args.slice();
    singleFunction(...args);
};

const outerFunctionAndSliceAndCallingOtherFunctionWithCopy = outer => (...args) => {
    // Passing ...copy instead of ...args doesn't work either
    const copy = args.slice();
    singleFunction(...copy);
};
```

### Current Behavior
The functions that don't work generate this error:
```
Module build failed: TypeError: C:\theproject\js\src\utils\code.js: Cannot read property 'file' of undefined
    at Scope.toArray (C:\theproject\js\node_modules\babel-traverse\lib\scope\index.js:437:24)
    at getSpreadLiteral (C:\theproject\js\node_modules\babel-plugin-transform-es2015-spread\lib\index.js:16:20)
    at build (C:\theproject\js\node_modules\babel-plugin-transform-es2015-spread\lib\index.js:56:20)
    at PluginPass.CallExpression (C:\theproject\js\node_modules\babel-plugin-transform-es2015-spread\lib\index.js:105:19)
    at newFn (C:\theproject\js\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\theproject\js\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\theproject\js\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\theproject\js\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\theproject\js\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\theproject\js\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\theproject\js\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\theproject\js\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (C:\theproject\js\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (C:\theproject\js\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\theproject\js\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\theproject\js\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\theproject\js\node_modules\babel-traverse\lib\index.js:114:17)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| babel-core            |  6.25
| babel-preset-es2015            |  6.24.1
| babel-preset-react            |  6.24.1
| babel-preset-stage0            |  6.24.1
| ... more babel ... |
| node             | 7.7.4
| yarn             | 0.24.6
| Operating System | Windows 10

**Comment by jridgewell** [comment]
This is working fine in the [REPL](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-0&targets=&browsers=last%202%20versions&builtIns=false&debug=false&code_lz=MYewdgzgLgBBCWYDmAbApgMQK5mFe4MAvDABQB0lAhgE5IQCUxAfDAN4BQM3MA9LzADqIGgGsIXHqEixQABwCexGAG1K5WvQC6Abg4BfPR2nQYILFDQ1sufIRLnLNFmXWbGLzjz4CAIiDQIMAByWAB3EVFJbhNZEEVlNWo6CF0DI1izCysbPAIwAEEwABMAZRR4YDRlRysXCmT6JiJWLx5-IUiJb0z5JRJ3cggKqtIGPUMOY3BTWuscPPAispG0ZYBhKhQK5AB5KAALHIW7MBrs5xbXRo8rtu4O_0CQ8MjomF74_phB4cq0MZ6bwIZDoXKnBoaFLjdJTTJzcH5Zblf4bLY7JD7I7zWz5QTwQ7rL7nJz1NzQzzvDoABSoEBBSBg6j6MEQ0DQVGKZgAZkybjBigEgqEYBExDA0ATse9PgkBikhqtAe8GWCTvlIX0YYYgA&experimental=false&loose=false&spec=false&playground=true). We'll need your babelrc configuration.

**Comment by Lajnold** [comment]
It turns out that it's only a problem when **flow-react-proptypes** is included as a plugin in .babelrc. The error happens even if neither flow nor react is used in the code. I don't know whether the bug is in babel or flow-react-proptypes, or even in webpack. I've created a repo showing the error. I can report it elsewhere if the bug isn't in babel.

https://github.com/Lajnold/babel-issue-5901/

**Comment by jridgewell** [comment]
Core issues is https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/src/util.js#L37. Can you open an issue telling them to use `Path#traverse` instead of the `babel-traverse` package?

**Comment by Lajnold** [comment]
Thanks for the feedback. I have reported the problem to them.
