### ISSUE TITLE
transform-react-jsx-source throws error - strongly expects a fileName being passed

### ISSUE THREAD

**Issue by swernerx** [babel/babel#5909]
```
TypeError: unknown: Property value expected type of string but got null
  
  at Object.validate (node_modules/babel-types/lib/definitions/index.js:161:13)
  at validate (node_modules/babel-types/lib/index.js:505:9)
  at Object.builder (node_modules/babel-types/lib/index.js:466:7)
  at PluginPass.JSXOpeningElement (node_modules/babel-plugin-transform-react-jsx-source/lib/index.js:35:68)
  at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
  at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
  at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
  at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
```

This is the test suite of [babel-preset-edge](https://github.com/sebastian-software/babel-preset-edge) when running the "jest" testrunner.

The babel config is dynamically created based on babel-preset-env, fast-async, react, lodash, ...

It seems to throw in this area (from babel-plugin-transform-react-jsx-source/lib/index.js) at version 6.22.0:

```js
if (!state.fileNameIdentifier) {
  var fileName = state.file.log.filename !== "unknown" ? state.file.log.filename : null;

  var fileNameIdentifier = path.scope.generateUidIdentifier(FILE_NAME_VAR);
  path.hub.file.scope.push({ id: fileNameIdentifier, init: t.stringLiteral(fileName) });
  state.fileNameIdentifier = fileNameIdentifier;
}
```

This here is the thing which throws:

```js
t.stringLiteral(fileName)
```

It seems to expect that the `fileName` is always a valid string. Unfortunately as we can see a few lines above `fileName` could be also `null`. Somehow there should be a workaround for this.

In my case the error is gone when changing the first line from above snippet to:

```js
var fileName = state.file.log.filename !== "unknown" ? state.file.log.filename : "";
```

I am just not sure whether this makes any sense.

**Comment by jridgewell** [comment]
Want to submit a PR?

**Comment by swernerx** [comment]
I'll do

**Comment by hzoo** [comment]
Can redo the PR on master still (which is 7.x now)
