### ISSUE TITLE
babel-traverse: Path#getSource() throws "Cannot read property 'file' of undefined"

### ISSUE THREAD

**Issue by motet-a** [babel/babel#5915]
Probably related with #5901 and #5880.

### Input Code

It seems to happen with any input code, so...

### Babel Configuration (.babelrc, package.json, cli command)

I am using babel-traverse@6.25.0 and babel-plugin-minify-simplify@0.1.2 (from Babily) with Webpack.

babel-plugin-minify-simplify does [this](https://github.com/babel/babili/blob/90ee63b/packages/babel-plugin-minify-simplify/src/index.js#L722):

```js
// An approximation of the resultant gzipped code after minification
this.fitsInSlidingWindow = path.getSource().length / 10 < 33000;
```

And `Path#getSource()` is [here](https://github.com/babel/babel/blob/58ec149c522c9b9c7933befbb120e54d3de0c5e0/packages/babel-traverse/src/path/introspection.js#L196):

```js
/**
 * Get the source code associated with this node.
 */

export function getSource() {
  const node = this.node;
  if (node.end) {
    return this.hub.file.code.slice(node.start, node.end);
  } else {
    return "";
  }
}
```

### Expected Behavior
It should not crash.

### Current Behavior
It crashes because `this.hub` is undefined:

```
Module build failed: TypeError: someproject/src/index.js: Cannot read property 'file' of undefined
    at NodePath.getSource (someproject/node_modules/babel-traverse/lib/path/introspection.js:193:20)
    at PluginPass.Program (someproject/node_modules/babel-plugin-minify-simplify/lib/index.js:702:41)
    at newFn (someproject/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (someproject/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (someproject/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (someproject/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (someproject/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (someproject/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (someproject/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (someproject/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (someproject/node_modules/babel-traverse/lib/index.js:79:12)
    at File.transform (someproject/node_modules/babel-core/lib/transformation/file/index.js:548:35)
    at someproject/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (someproject/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (someproject/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at transpile (someproject/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (someproject/node_modules/babel-loader/lib/index.js:171:20)
```

### Possible Solution
Find out why `this.hub` is undefined and fix it.

### Your Environment

| software         | version(s)
| ---------------- | -------
| babel-core    |  6.25.0
| babel-traverse | 6.25.0
| babel-plugin-minify-simplify | 0.1.2
| node             | 8.1.3

**Comment by jridgewell** [comment]
What's the source code you're transforming? Are you using `for await (...)` anywhere?

**Comment by motet-a** [comment]
I’m really sorry, I should have investigate more in order to create a simple repository reproducing the bug. It was probably a strange interaction between webpack, babel and others. Let that be a lesson to me.

I never used `for await (...)` by the way.

**Comment by haf** [comment]
Here's another stack trace, when it's happening to me:

```
TypeError: /app/data/reducers.js: Cannot read property 'file' of undefined
    at Scope.toArray (/app/node_modules/babel-traverse/lib/scope/index.js:437:24)
    at DestructuringTransformer.toArray (/app/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:122:27)
    at DestructuringTransformer.pushArrayPattern (/app/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:277:26)
```

For this code:

```js
  Scope.prototype.toArray = function toArray(node, i) {
    var file = this.hub.file;

    if (t.isIdentifier(node)) {
      var binding = this.getBinding(node.name);
      if (binding && binding.constant && binding.path.isGenericType("Array")) return node;
    }
```

**Comment by haf** [comment]
Here's a minimal repro:

```js

const fn = edit => noop => {
  const a = [ 1, 2 ]
  const [ sid, ignored ] = [ 1, a[0] ];
}

```

**Comment by Nicholi** [comment]
Still crashing

babel-core: 6.26.0
babel-traverse: 6.26.0
babel-plugin-minify-mangle: 0.2.0
babel-plugin-minify-simplify: 0.2.0
node: 8.5.0

No webpack, nothing special, just doesn't work. Only solution is to disable mangle/simplify in minify options.

**Comment by jridgewell** [comment]
This appears to be fixed in http://babeljs.io/repl#?babili=false&browsers=ie%2010&build=&builtIns=true&code_lz=MYewdgzgLgBAZmGBeGBTAJgS1kgfDMEEAB2XwG8AoGGUSWAQ2RgG0YBGAGhgCYYBdarXDRWMCJnTdMAc0IAnDAOZsuMBiwAM_AQG5KAXyA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015-loose%2Creact%2Cstage-3&prettier=false&targets=&version=7.0.0-alpha.19.

**Comment by tomasdev** [comment]
@jridgewell what versions are being used at the REPL? I'm reproducing it on

babel-preset-minify: 0.2.0
babel-cli: 6.26.0

**Comment by haf** [comment]
Yeah, I'm using minification @jridgewell — and the REPL fails on that, so reopen this issue, please.
