### ISSUE TITLE
`6to5-node -e` evaluates in an unsatisfactory context (e.g. no require)

### ISSUE THREAD

**Issue by timoxley** [babel/babel#592]
```
> 6to5-node -e "console.log(require)"

/usr/local/lib/node_modules/6to5/bin/_6to5-node:49
  return vm.runInThisContext(code, filename);
            ^
ReferenceError: require is not defined
    at eval:1:13
    at _eval (/usr/local/lib/node_modules/6to5/bin/_6to5-node:49:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/6to5/bin/_6to5-node:53:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

While in `node`:

```
> node -e "console.log(require)"
{ [Function: require]
  resolve: [Function],
  main: undefined,
  extensions: { '.js': [Function], '.json': [Function], '.node': [Function] },
  registerExtension: [Function],
  cache: {} }
```

**Comment by sebmck** [comment]
Superseded by #883.
