### ISSUE TITLE
Exception "We don't know what to do with this node type." when processed ExportNamedDeclaration

### ISSUE THREAD

**Issue by shcoder-ru** [babel/babel#5926]
Hi there!
The case is when `this.parentPath.isExportNamedDeclaration() && this.key === 'declaration'` is not handled in [/babel-traverse/src/path/modification.js](https://github.com/babel/babel/blob/master/packages/babel-traverse/src/path/modification.js#L33)

### Input Code
I'm trying to make coverage of
``` js
export function SomeFunction() {}
```
then i have a problem, but if i'm trying to make coverage of
``` js
function SomeFunction() {}
export {SomeFunction as SomeFunction};
```
then it's okay.
Specific case:
[export function checkArgumentType(argument, position, type) {](https://github.com/shcoder-ru/guit/blob/v2/src/utils/check-argument.js#L10)
[travis-ci log](https://travis-ci.org/shcoder-ru/guit/jobs/250815273#L222)

### Babel Configuration .babelrc
``` json
{
  "presets": [
    "es2015",
    "es2017"
  ],
  "plugins": [
    "transform-runtime",
    "transform-object-rest-spread"
  ],
  "env": {
    "test": {
      "plugins": [ "transform-coverage" ]
    }
  }
}
```

### Expected Behavior
coverage on the [codecov](https://codecov.io/gh/shcoder-ru/guit/src/v2/src/utils/check-argument.js#L10) must be 100%
[travis](https://travis-ci.org/shcoder-ru/guit/jobs/250815273#L222) shouldn't throw an exception.

### Current Behavior
```
Error: /home/travis/build/shcoder-ru/guit/src/utils/check-argument.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertBefore (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/path/modification.js:61:13)
    at PluginPass.exit (/home/travis/build/shcoder-ru/guit/node_modules/babel-plugin-transform-coverage/lib/transform-coverage.js:34:18)
    at PluginPass.newFn (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/visitors.js:318:17)
    at newFn (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/travis/build/shcoder-ru/guit/node_modules/babel-traverse/lib/context.js:103:17)
```

### Possible Solution
Maybe implement a handling of the case is when `this.parentPath.isExportNamedDeclaration() && this.key === 'declaration'` in [babel-traverse/src/path/modification.js](https://github.com/babel/babel/blob/master/packages/babel-traverse/src/path/modification.js#L16)

### My Environment

| software         | version(s)
| ---------------- | -------
| Babel            | v6.25.0
| node             | v6.10.0
| npm              | v3.10.10
| Operating System | 4.9.34-gentoo x86_64 GNU/Linux

**Comment by loganfsmyth** [comment]
`babel-plugin-transform-coverage` is not a plugin we maintain, so you'd want to file that there.

That said, you probably want to be using https://www.npmjs.com/package/babel-plugin-istanbul since it is maintained.
