### ISSUE TITLE
[bug] babel-preset-typescript with babel-loader

### ISSUE THREAD

**Issue by hlehmann** [babel/babel#6093]
I try to use babel-preset-typescript with the webpack builder but I get the following error.
```
Cannot read property 'referencePaths' of undefined
    at isImportTypeOnly (node_modules/babel-plugin-transform-typescript/lib/index.js:212:34)
    at PluginPass.ImportDeclaration (node_modules/babel-plugin-transform-typescript/lib/index.js:39:15)
    at newFn (node_modules/babel-traverse/lib/visitors.js:234:21)
    at NodePath._call (node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:67:18)
    at NodePath.call (node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:42:17)
    at NodePath.visit (node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:98:12)
    at TraversalContext.visitQueue (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:136:16)
    at TraversalContext.visitMultiple (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:91:17)
    at TraversalContext.visit (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:175:19)
    at Function.traverse.node (node_modules/babel-core/node_modules/babel-traverse/lib/index.js:108:17)
    at NodePath.visit (node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:109:19)
    at TraversalContext.visitQueue (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:136:16)
    at TraversalContext.visitSingle (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:96:19)
    at TraversalContext.visit (node_modules/babel-core/node_modules/babel-traverse/lib/context.js:177:19)
    at Function.traverse.node (node_modules/babel-core/node_modules/babel-traverse/lib/index.js:108:17)
    at traverse (node_modules/babel-core/node_modules/babel-traverse/lib/index.js:75:12)
    at File.transform (node_modules/babel-core/lib/transformation/file/index.js:485:35)
    at node_modules/babel-core/lib/transformation/pipeline.js:52:17
    at File.wrap (node_modules/babel-core/lib/transformation/file/index.js:504:14)
    at Object.transform (node_modules/babel-core/lib/transformation/pipeline.js:49:15)
    at transpile (node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (node_modules/babel-loader/lib/index.js:174:20)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7
| node             |  8.2
| npm              |  5.3
| Operating System | ubuntu 17.4

**Comment by threehams** [comment]
You're going to need to include a sample project or minimal repro steps, a call stack isn't enough to work from. I have Webpack and the Typescript plugin working just fine in a project.

**Comment by hlehmann** [comment]
After more investigation, this error occur when I use babel-plugin-transform-runtime. If I remove it I have no more errors

**Comment by Kovensky** [comment]
`babel-plugin-transform-runtime` writes new imports in a `Program.exit` visitor in a way that triggers a new traversal, but when the new traversal happens, all metadata about the file and the traversal has already been deleted.

This was also a problem I found when trying to improve the commonjs transform -- it was impossible to make it work correctly with `babel-plugin-transform-runtime`, either being forced to leave the extra `import`s as-is, or crashing.

* This is also why I advocate never using `transformruntime` and just either shipping polyfills or requiring that your users provide the needed polyfills. There is nothing bad about polyfills -- you're not "polluting" globals because you are only providing *missing parts of the spec implementation*. If you're adding something to global that is not in any spec, that is not polyfilling.

**Comment by hlehmann** [comment]
I notice we get the same error with babel-plugin-lodash and other library equivalent which are very useful but are modifying the imports.

**Comment by phyllisstein** [comment]
`babel-plugin-transform-promise-to-bluebird` and `babel-plugin-universal-import` also fall victim to this bug when used with the TypeScript preset.

**Comment by hzoo** [comment]
If someone can provide a minimal repo with more information that would helpful for someone to be able to figure this out. We have a fix for the transform-runtime issue but that may not be the issue given that it is an error in other places that modify imports as well.

**Comment by phyllisstein** [comment]
Hi @hzoo , here's a few of the cases I've seen. Hope it helps: <https://github.com/phyllisstein/babel-typescript-imports-mwe>.

**Comment by phyllisstein** [comment]
@hzoo I hate to nag, but has the Babel team had a chance to take a look at this in the past few weeks? Or is there still not enough code in <https://github.com/phyllisstein/babel-typescript-imports-mwe> to be useful? I'm happy to keep working on the repro case if that's helpful, but I'm afraid I still don't know Babel's guts well enough to do more than that.

**Comment by drcmda** [comment]
It seems to happen whenever imports are being changed, transform-runtime is not the culprit, all plugins that do it cause the typescript to fail.

It happens in plugin-transforms-typescript/lib/index.js: 

```js
37 ImportDeclaration: function ImportDeclaration(path, state) {
..
58     var binding = path.scope.getBinding(_specifier.local.name);
59
60     if (isImportTypeOnly(binding, state.programPath)) {
```

_specifier.local.name seems to point to the changed import, which isn't in the scope, hence binding is empty. When it gets passed to `isImportTypeOnly` it crashes.

In our case it happens for [a plugin](https://github.com/ant-design/babel-plugin-import) that transforms import statements for optimization purposes like so:

```js
import { Button } from 'antd';
ReactDOM.render(<Button>xxxx</Button>);

      ↓ ↓ ↓ ↓ ↓ ↓
      
var _button = require('antd/lib/button');
ReactDOM.render(<_button>xxxx</_button>);
```
