### ISSUE TITLE
Transform Generator Plugin Fails

### ISSUE THREAD

**Issue by wdalrymple** [babel/babel#6126]
Transform Generator Plugin Fails

### Input Code

I grab the lastest version of babel:

....
babel-plugin-transform-object-rest-spread@6.26.0 node_modules/babel-plugin-transform-object-rest-spread
├── babel-plugin-syntax-object-rest-spread@6.13.0
└── babel-runtime@6.26.0 (regenerator-runtime@0.11.0, core-js@2.5.0)

babel-preset-es2015@6.6.0 node_modules/babel-preset-es2015
├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-arrow-functions@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-typeof-symbol@6.23.0 (babel-runtime@6.26.0)
├── babel-plugin-check-es2015-constants@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-literals@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-spread@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-template-literals@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-function-name@6.24.1 (babel-types@6.26.0, babel-helper-function-name@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-unicode-regex@6.24.1 (regexpu-core@2.0.0, babel-helper-regex@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-duplicate-keys@6.24.1 (babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-object-super@6.24.1 (babel-helper-replace-supers@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-for-of@6.23.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-sticky-regex@6.24.1 (babel-helper-regex@6.26.0, babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-shorthand-properties@6.24.1 (babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-computed-properties@6.24.1 (babel-template@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-destructuring@6.23.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-parameters@6.24.1 (babel-helper-get-function-arity@6.24.1, babel-helper-call-delegate@6.24.1, babel-types@6.26.0, babel-template@6.26.0, babel-traverse@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-modules-commonjs@6.26.0 (babel-plugin-transform-strict-mode@6.24.1, babel-types@6.26.0, babel-template@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-block-scoping@6.26.0 (babel-types@6.26.0, babel-template@6.26.0, babel-traverse@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-classes@6.24.1 (babel-helper-optimise-call-expression@6.24.1, babel-messages@6.23.0, babel-helper-replace-supers@6.24.1, babel-helper-define-map@6.26.0, babel-helper-function-name@6.24.1, babel-types@6.26.0, babel-template@6.26.0, babel-traverse@6.26.0, babel-runtime@6.26.0)
└── babel-plugin-transform-regenerator@6.26.0 (regenerator-transform@0.10.0)

babel-core@6.7.7 node_modules/babel-core
├── slash@1.0.0
├── shebang-regex@1.0.0
├── path-exists@1.0.0
├── path-is-absolute@1.0.1
├── private@0.1.7
├── convert-source-map@1.5.0
├── babel-code-frame@6.26.0 (js-tokens@3.0.2, esutils@2.0.2)
├── debug@2.6.8 (ms@2.0.0)
├── minimatch@2.0.10 (brace-expansion@1.1.8)
├── babylon@6.18.0
├── json5@0.4.0
├── source-map@0.5.6
├── lodash@3.10.1
├── babel-runtime@5.8.38 (core-js@1.2.7)
├── babel-register@6.26.0 (home-or-tmp@2.0.0, source-map-support@0.4.15, mkdirp@0.5.1, babel-core@6.26.0, babel-runtime@6.26.0, lodash@4.17.4, core-js@2.5.0)
├── babel-messages@6.23.0 (babel-runtime@6.26.0)
├── babel-template@6.26.0 (lodash@4.17.4, babel-runtime@6.26.0)
├── babel-helpers@6.24.1 (babel-runtime@6.26.0)
├── babel-generator@6.26.0 (trim-right@1.0.1, jsesc@1.3.0, detect-indent@4.0.0, lodash@4.17.4, babel-runtime@6.26.0)
├── babel-types@6.26.0 (to-fast-properties@1.0.3, esutils@2.0.2, lodash@4.17.4, babel-runtime@6.26.0)
└── babel-traverse@6.26.0 (globals@9.18.0, invariant@2.2.2, lodash@4.17.4, babel-runtime@6.26.0)

When i try and transpile my code:
Module build failed: Error: Plugin 20 specified in "/my app folder/node_modules/babel-preset-es2015/index.js" provided an invalid property of "name"
    at Plugin.init (/my app folder/node_modules/babel-core/lib/transformation/plugin.js:115:13)
    at Function.normalisePlugin (/my app folder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:149:12)
    at /my app folder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:183:30
    at Array.map (native)
    at Function.normalisePlugins (/my app folder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:155:20)
    at OptionManager.mergeOptions (/my app folder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:277:36)
    at /my app folder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /my app folder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
    at Array.map (native)
    at OptionManager.resolvePresets (/my app folder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/my app folder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/my app folder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.init (/my app folder/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/my app folder/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/my app folder/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/my app folder/node_modules/babel-core/lib/transformation/pipeline.js:45:16)

I assume that plugin 20 is:
babel-plugin-transform-regenerator@6.26.0 (regenerator-transform@0.10.0)

### Babel Configuration (.babelrc, package.json, cli command)

```js
    "babel-core": "~6.7.4",
    "babel-loader": "~6.2.4",
    "babel-plugin-resolver": "^1.0.0",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-preset-es2015": "~6.6.0",
```

### Expected Behavior
It shouldn't barf

### Current Behavior
Barfs

### Context
Can't build

### Your Environment
Nothing special. I have a build server where I am getting the latest version of all my dependencies during each run.

| software         | version(s)
| ---------------- | -------
| Babel            |  babel-core@6.7.7
| node             | v0.10.46
| npm              | 2.12.0
| Operating System | linux

**Comment by jmrapp1** [comment]
I ran into this issue as well today and have been scouring the internet trying to find a fix. I've tried everything from re-installing npm & node, re-cloning the repository from the point that it was working, and countless other small things, but nothing has worked.

**Comment by jgrayauskie** [comment]
Seeing this too.

**Comment by tnm** [comment]
We're hitting this too, and I suspect many others are as well.

```
Module build failed: Error: Plugin 20 specified in "/my app folder/node_modules/babel-preset-es2015/index.js" provided an invalid property of "name"
```

**Comment by Fionoble** [comment]
Same issue here.

**Comment by hzoo** [comment]
Ok thanks for the report but we don't have enough info here. Just the error message but not the babelrc or a minimal reproduction

**Comment by jmrapp1** [comment]
```
{
  "presets": ["es2015", "stage-0"],
  "plugins": ["syntax-class-properties", "add-module-exports", "transform-object-assign"]
}
```

**Comment by wdalrymple** [comment]
Looks like it is https://github.com/babel/babel-preset-env/issues maybe? 

It could be this since that is what is loading the plugin '20' that seems to be failing?

**Comment by jmrapp1** [comment]
My issue was putting out "plugin 19"

**Comment by kylehood** [comment]
I have a hunch that an incompatibility with an updated dependency. Our project was working fine this morning, and everyone is now experiencing the issue after a fresh npm install. I work with @jmrapp1 so the configuration is the same. We noticed this first about 3-4 hours ago, around noon eastern time.

**Comment by existentialism** [comment]
@wdalrymple confused... don't think preset-env is being used?

@jmrapp1 can you try babel-core@6.26.0?

**Comment by hzoo** [comment]
Ok I'm thinking it must be https://github.com/facebook/regenerator/commit/70b1f14896634200b250340ceae54d043688dd0, need to determine why it's failing it because it shouldn't have an issue with name. Either way we can ask @benjamn to do another release

**Comment by wdalrymple** [comment]
Ahh, that would make sense. Seems to line up with the error that I am seeing.

**Comment by jmrapp1** [comment]
@existentialism Change to `babel-core@6.26.0` worked. Built successfully. Everyone else try to update to this version of core as well.

**Comment by hzoo** [comment]
Ok then it sounds like everyone here is actually using an older babel-core verison?

**Comment by jmrapp1** [comment]
Must be the cause, yes.

**Comment by hzoo** [comment]
aside: if you are using npm 2, Babel is going to be really slow to install and isn't really supported (and node 0.10/0.12 is EOL and will be dropped in Babel 7)

**Comment by existentialism** [comment]
@jmrapp1 as @hzoo pointed out, transform-regenerator added a `name` property in preparation for 7.0, but that prop isn't compatible with [<6.14.0](https://github.com/babel/babel/commit/07b3dc18a09f2217b38a3a63c8613add6df1b47d#diff-f1bb17455dbc30ceac2d7136667151d7L18)

**Comment by wdalrymple** [comment]
d

**Comment by wdalrymple** [comment]
What would then be the latest safest version to use then?

**Comment by jmrapp1** [comment]
@wdalrymple Using `babel-core@6.26.0` works for me.

**Comment by nicolo-ribaudo** [comment]
@wdalrymple  You should use the same version for every babel package. So either use always `^version` or always `~version` in your package.json.

**Comment by wdalrymple** [comment]
So use the same version of every package in babel? like say:
    "babel-core": "~6.26.0",
    "babel-loader": "~6.26.0",
    "babel-plugin-resolver": "~6.26.0",
    "babel-plugin-transform-object-rest-spread": "~6.26.0"",
    "babel-preset-es2015": "~6.26.0"",

**Comment by syrnick** [comment]
re npm2, node 4 ships with 2.15.11 and is supported till April 2018.

**Comment by wdalrymple** [comment]
yeah - we definitely need to upgrade the version of node on the build server. it is old

**Comment by syrnick** [comment]
My point is that although node 0.10 isn't supported, npm 2 should be supported until node 4 maintenance ends.

**Comment by nicolo-ribaudo** [comment]
> So use the same version of every package in babel? like say:
"babel-core": "~6.26.0",
"babel-loader": "~6.26.0",
"babel-plugin-resolver": "~6.26.0",
"babel-plugin-transform-object-rest-spread": "~6.26.0"",
"babel-preset-es2015": "~6.26.0"",

Yes

**Comment by loganfsmyth** [comment]
@syrnick npm@2 does work, but for Babel to be fast you need to `npm dedupe`, npm@>=3 do flattening automatically so it is fast automatically.  There's also nothing stopping you from installing more recent versions of npm on Node 4, npm 2 is just the included version.

**Comment by wdalrymple** [comment]
Thanks for the pointers. Much appreciated! Thanks everyone!

**Comment by etzJohn** [comment]
can confirm setting plugins and presets to pre `6.26` works

**Comment by wssgcg1213** [comment]
Same issue here.

**Comment by nicolo-ribaudo** [comment]
@wssgcg1213 Which versions of the babel packages are you using?

**Comment by wdalrymple** [comment]
I am using:
    "babel-core": "~6.23.0",
    "babel-loader": "~6.4.1",
    "babel-plugin-resolver": "~1.0.0",
    "babel-plugin-transform-object-rest-spread": "~6.23.0",
    "babel-preset-es2015": "~6.24.1",

Successfully.
"babel-core": 6.26.0 seems to conflict with some of my other dependencies with the babel-loader.

**Comment by bogo26** [comment]
I keep having this issue, my package.json looks like:

    "babel-cli": "^6.24.1",
    "babel-core": "^6.24.1",
    "babel-eslint": "^6.1.2",
    "babel-loader": "^6.4.1",
    "babel-plugin-istanbul": "^4.1.4",
    "babel-plugin-rewire": "^1.1.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1"

babel-core is 6.26.0
babel-cli is 6.26.0
babel-preset-es2015 is 6.24.1

All the latest but I keep getting this when I try to build:
//I also tried with fix 6.24.1 to match the latest preset-es2015

_Error: Plugin 20 specified in "app\\node_modules\\babel-preset-es2015\\lib\\index.js" provided an invalid property of "name"_

What am I missing?

**Comment by nicolo-ribaudo** [comment]
Can you try to delete node_modules and reinstall it? Maybe you still have an older version of babel-core downloaded. (You can check the installed versions in `node_modules/babel-core/package.json` and `node_modules/babel-preset-es2015/package.json`)

**Comment by bogo26** [comment]
@nicolo-ribaudo I did that like 20 times today :)
I also cleared the cache from AppData, still the same issue
I tried to set some old versions, that used to work, same issue.

**Comment by nicolo-ribaudo** [comment]
Can you `yarn list` or `npm list` and upload the output to gist?

**Comment by bogo26** [comment]
Yes, here it is
https://gist.github.com/bogo26/2c535156663743be7ca745563581f73c

**Comment by nicolo-ribaudo** [comment]
I'm sorry, I can't reproduce this issue with your package versions... Can you upload a small reproduction on github?
Also, in that `npm list` there isn't a top-level babel-core (I _think_ that it should there be, but I'm not sure)

**Comment by loganfsmyth** [comment]
Update on this. I've posted https://github.com/facebook/regenerator/pull/312 which will fix the backward-compatibility issue people are hitting. Hopefully we can get that out sooner rather than later.

**Comment by bogo26** [comment]
@nicolo-ribaudo I will do that tomorrow if I can't find a fix. I will start a new project and take it step by step and check where it brakes then post it if I can't figure it out.

If anyone has a better solution to fix this I'm all ears :)

**Comment by bogo26** [comment]
That fixed it for me. Thanks guys ^^

**Comment by hzoo** [comment]
Thanks everyone!
