### ISSUE TITLE
RangeError: Maximum call stack size exceeded on node 8.3+

### ISSUE THREAD

**Issue by jasperkuperus** [babel/babel#6128]
### Input Code
I have a file that contains a large template string (260 lines, 73017 characters). It's a simple SQL query like this:

```js
{ query: `INSERT INTO slices (id, image_id, created_at ...) VALUES
  ('1', 'image-1', '${date}', ...),
  ('2', 'image-1', '${date}', ...),
  ('3', 'image-1', '${date}', ...),
  ...`
}
```

Babel seems to choke in this file using Node 8.3 and higher:

```
RangeError: /Users/Jasper/.../test/util.js: Maximum call stack size exceeded
    at TraversalContext.create (/Users/Jasper/.../node_modules/babel-traverse/lib/context.js:68:26)
    at TraversalContext.visitSingle (/Users/Jasper/.../node_modules/babel-traverse/lib/context.js:108:36)
    at TraversalContext.visit (/Users/Jasper/.../node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/Jasper/.../node_modules/babel-traverse/lib/index.js:114:17)
...
    at Function.traverse.node (/Users/Jasper/.../node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/Users/Jasper/.../node_modules/babel-traverse/lib/index.js:79:12)
    at File.transform (/Users/Jasper/.../node_modules/babel-core/lib/transformation/file/index.js:548:35)
    at /Users/Jasper/.../node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/Users/Jasper/.../node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/Users/Jasper/.../node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.transformFileSync (/Users/Jasper/.../node_modules/babel-core/lib/api/node.js:152:10)
    at compile (/Users/Jasper/.../node_modules/babel-register/lib/node.js:118:20)
    at loader (/Users/Jasper/.../node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Jasper/.../node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Jasper/.../test/e2e/get-images-spec.js:3:1)
    at Module._compile (module.js:573:30)
    at loader (/Users/Jasper/.../node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Jasper/.../node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /Users/Jasper/.../node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/Jasper/.../node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/Jasper/.../node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/Jasper/.../node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
```

Using 8.2.1 or lower, this file is successfully parsed. If I cut the length of the template string in this file, 8.3+ also parses this file correctly.

### Babel Configuration

```js
{
  "presets": ["env"]
}
```

### Expected Behavior
Babel should process the file with the long template string as any other file, without errors.

### Current Behavior
Babel breaks with a `Maximum call stack size exceeded`, see stack trace above.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | 8.3+
| npm              | 5.3.0
| Operating System | OS X

**Comment by loganfsmyth** [comment]
Seems like that's really pushing up against the boundaries of what our transform can handle. If you can, my recommendation would be to break it into an array of many values, e.g.

```
{
  query: `INSERT INTO slices (id, image_id, created_at ...) VALUES` + [
    `('1', 'image-1', '${date}', ...)`,
    `('2', 'image-2', '${date}', ...)`,
    `('3', 'image-3', '${date}', ...)`,

  ].join(',')
```

**Comment by jasperkuperus** [comment]
Yeah, I agree, it's totally pushing the limits. I would normally not create such big strings, although being some temporary, static test data, I didn't mind. I would understand if this is not worth fixing. This did however work on node 8.2 and lower and the error message did not point me in the right direction.

I did a bit more research, seems the cut off point is a string of 70380 characters in my case.

**Comment by loganfsmyth** [comment]
It seems likely that you were close to the stack size limit, and with the new engine changes in 8.3, some structure on the stack probably changed sizes and pushed you over the limit.

**Comment by loganfsmyth** [comment]
Going to close this since it does not seem actionable for us.
