### ISSUE TITLE
babel-polyfill missing es6.typed.array-buffer

### ISSUE THREAD

**Issue by chrisblossom** [babel/babel#6131]
Choose one: is this a bug report or feature request?

### Input Code

When updating from ``Babel`` ``v6.23.0`` to ``v6.26.0``, ``babel-preset-env`` cannot find ``es6.typed.array-buffer``. I am not sure if this is an issue with ``babel-polyfill`` or ``babel-preset-env``

### Babel Configuration (.babelrc, package.json, cli command)

```js
  "devDependencies": {
...
    "babel-cli": "6.26.0",
    "babel-core": "6.26.0",
    "babel-loader": "7.1.1",
    "babel-plugin-transform-es3-member-expression-literals": "6.22.0",
    "babel-plugin-transform-es3-property-literals": "6.22.0",
    "babel-plugin-transform-jscript": "6.22.0",
    "babel-plugin-transform-object-rest-spread": "6.26.0",
    "babel-preset-env": "1.6.0",
    "babel-preset-flow": "6.23.0",
    "babel-preset-react": "6.24.1",
    "babel-register": "6.26.0",
...
  },
  "dependencies": {
...
    "babel-polyfill": "6.26.0",
...
  },
```

```js
const babelConfig = {
    cacheDirectory: true,

    babelrc: false,
    passPerPreset: false,
    presets: [
        [
            'env',
            {
                targets: {
                    browsers: ['> 0%'],
                },
                exclude: ['transform-regenerator'],
                modules: false,
                useBuiltIns: true,
                debug: false,
            },
        ],
        'react',
    ],
    plugins: [
        'transform-object-rest-spread',
        'transform-jscript',
        'transform-es3-member-expression-literals',
        'transform-es3-property-literals',
    ],
};
```

### Current Behavior

```
app git:(develop) ✗ node build/web/server.js
Error: Cannot find module 'core-js/modules/es6.typed.array-buffer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/chris/github/app/build/web/webpack:/external "core-js/modules/es6.typed.array-buffer":1:1)
    at __webpack_require__ (/Users/chris/github/app/build/web/webpack:/webpack/bootstrap 9accef4ee38dc4d41fc0:19:1)
    at Object.<anonymous> (/Users/chris/github/app/build/web/server.js:11066:97)
    at __webpack_require__ (/Users/chris/github/app/build/web/webpack:/webpack/bootstrap 9accef4ee38dc4d41fc0:19:1)
    at Object.<anonymous> (/Users/chris/github/app/build/web/server.js:26962:18)
    at __webpack_require__ (/Users/chris/github/app/build/web/webpack:/webpack/bootstrap 9accef4ee38dc4d41fc0:19:1)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | 6.11.2
| npm              | 3.10.10
| yarn              | 0.27.5
| Operating System | MacOS 10.12.6

**Comment by chrisblossom** [comment]
I removed ``yarn.lock`` and ``node_modules``. Everything works as expected now.
