### ISSUE TITLE
Error on master: babel-plugin-transform-es2015-block-scoping/general label

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#6171]
Failing test on master after upgrading babylon. I don't know enough to say if it's an error or not.

**bigger question is why wasn't this caught?**

```
1) babel-plugin-transform-es2015-block-scoping/general label:
     SyntaxError: /Users/jridgewell/src/babel/packages/babel-plugin-transform-es2015-block-scoping/test/fixtures/general/label/actual.js: Invalid labeled declaration (3:5)
    1 | let x, y;
    2 | {
  > 3 |   a: let x;
      |      ^
    4 |   let y;
    5 | }
    6 |
      at _class.raise (node_modules/babylon/lib/index.js:812:15)
      at _class.parseLabeledStatement (node_modules/babylon/lib/index.js:4496:12)
      at _class.parseStatementContent (node_modules/babylon/lib/index.js:4111:19)
      at _class.parseStatement (node_modules/babylon/lib/index.js:3996:17)
      at _class.parseBlockOrModuleBlockBody (node_modules/babylon/lib/index.js:4541:23)
      at _class.parseBlockBody (node_modules/babylon/lib/index.js:4527:10)
      at _class.parseBlock (node_modules/babylon/lib/index.js:4516:10)
      at _class.parseStatementContent (node_modules/babylon/lib/index.js:4059:21)
      at _class.parseStatement (node_modules/babylon/lib/index.js:3996:17)
      at _class.parseBlockOrModuleBlockBody (node_modules/babylon/lib/index.js:4541:23)
      at _class.parseBlockBody (node_modules/babylon/lib/index.js:4527:10)
      at _class.parseTopLevel (node_modules/babylon/lib/index.js:3964:10)
      at _class.parse (node_modules/babylon/lib/index.js:5381:17)
      at parse (node_modules/babylon/lib/index.js:9894:36)
      at File.parse (packages/babel-core/lib/transformation/file/index.js:365:17)
      at File.parseCode (packages/babel-core/lib/transformation/file/index.js:472:22)
      at packages/babel-core/lib/transformation/pipeline.js:49:10
      at File.wrap (packages/babel-core/lib/transformation/file/index.js:429:14)
      at Object.transform (packages/babel-core/lib/transformation/pipeline.js:47:15)
      at run (packages/babel-helper-transform-fixture-test-runner/lib/index.js:245:20)
      at runTask (packages/babel-helper-transform-fixture-test-runner/lib/index.js:22:13)
      at Context.<anonymous> (packages/babel-helper-transform-fixture-test-runner/lib/index.js:51:15)
```

**Comment by nicolo-ribaudo** [comment]
Actually I think that test should fail, since after a label there must be a statement but lexical declarations aren't statements.

**Comment by jeysal** [comment]
In case anyone else stumbles upon this and wonders why the ESTree format would allow this even though ECMA-262 does not:
https://github.com/estree/estree/issues/40
