### ISSUE TITLE
env preset breaks on class in v7 alpha 20

### ISSUE THREAD

**Issue by bowdenk7** [babel/babel#6186]
Bug report

Repro: https://github.com/bowdenk7/babel-7-bug-repro

### Input Code
```js
// src/foo.js
class Foo {
    
}
```
### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": [
        "env"
    ]
}
```

### Expected Behavior
Expecting an emitted JS file `out/foo.js`. 
This works in babel 6.

### Current Behavior
Crashes with error message:
```
TypeError: src\foo.js: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (C:\Users\wilkelly\Downloads\babelBug\node_modules\babel-traverse\lib\scope\index.js:974:12)
    at BlockScoping.updateScopeInfo (C:\Users\wilkelly\Downloads\babelBug\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:364:17)
    at BlockScoping.run (C:\Users\wilkelly\Downloads\babelBug\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (C:\Users\wilkelly\Downloads\babelBug\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:70:24)
    at newFn (C:\Users\wilkelly\Downloads\babelBug\node_modules\babel-traverse\lib\visitors.js:236:21)
    at NodePath._call (C:\Users\wilkelly\Downloads\babelBug\node_modules\babel-traverse\lib\path\context.js:68:19)
    at NodePath.call (C:\Users\wilkelly\Downloads\babelBug\node_modules\babel-traverse\lib\path\context.js:42:17)
    at NodePath.visit (C:\Users\wilkelly\Downloads\babelBug\node_modules\babel-traverse\lib\path\context.js:99:12)
    at TraversalContext.visitQueue (C:\Users\wilkelly\Downloads\babelBug\node_modules\babel-traverse\lib\context.js:137:18)
    at TraversalContext.visitSingle (C:\Users\wilkelly\Downloads\babelBug\node_modules\babel-traverse\lib\context.js:96:19)
```
### Possible Solution
No idea, sorry :)

### Context
Came across while trying to test typescript and env presets together.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-alpha.20
| node             |  6.11.1
| npm              |  5.3.0
| Operating System |  Windows 10

**Comment by hzoo** [comment]
Dang 😛 , some basic investigation

https://github.com/babel/babel/blob/44f6ff5e85a5e0a64bcb4ba6f1d0d64ca0eb9723/packages/babel-traverse/src/scope/index.js#L971-L978

From https://github.com/babel/babel/releases/tag/v7.0.0-alpha.20, only 2 PRs to touch scoping pkg is https://github.com/babel/babel/pull/6156, https://github.com/babel/babel/pull/5980

**Comment by existentialism** [comment]
@bowdenk7 you will want to use `babel-preset-env@2.0.0-alpha.20`

**Comment by hzoo** [comment]
Oh duh didn't even see that, `    "babel-preset-env": "^1.6.0"`

Yeah and the exact issue is that we made a breaking change in #5923 so that `getFunctionParent` wouldn't return the top level `Program` node anymore 😄  since that didn't make any sense.

**Comment by bowdenk7** [comment]
Thanks for the lightning response! Sorry, I'm a rookie at testing alpha builds >.<

**Comment by existentialism** [comment]
@bowdenk7 no no, I totally understand, it can be _really_ confusing. We're planning on improving the developer experience around this soon!

**Comment by dijonkitchen** [comment]
For anyone that comes across this in the future, the [docs](https://github.com/babel/babel/tree/master/packages/babel-preset-env) seem to be updated now. Just install `babel-preset-env` like so:
```sh
npm install @babel/preset-env --save-dev
```
and configure your `.babelrc` with:
```sh
{
  "presets": ["@babel/preset-env"]
}
```
