### ISSUE TITLE
Tests failing with error in babel-standalone

### ISSUE THREAD

**Issue by RusinovAnton** [babel/babel#6386]
While working on https://github.com/babel/babel/pull/6381 I've got error after run `make test` locally. 

```
make test
./node_modules/.bin/eslint scripts packages codemods *.js --format=codeframe --rulesdir="./eslint_rules"
./scripts/test.sh
/Users/rusinov/my-projects/babel/packages/babel-standalone/babel.js:80
throw new Error("Module build failed: TypeError: [BABEL] /Users/rusinov/my-projects/babel/packages/babel-standalone/src/index.js: Cannot read property 'loose' of undefined (While processing: \"base$2\")\n    at _default (/Users/rusinov/my-projects/babel/packages/babel-plugin-transform-optional-chaining/lib/index.js:12:31)\n    at /Users/rusinov/my-projects/babel/packages/babel-core/lib/config/option-manager.js:239:12\n    at cachedFunction (/Users/rusinov/my-projects/babel/packages/babel-core/lib/config/caching.js:48:17)\n    at loadPluginDescriptor (/Users/rusinov/my-projects/babel/packages/babel-core/lib/config/option-manager.js:269:28)\n    at /Users/rusinov/my-projects/babel/packages/babel-core/lib/config/option-manager.js:56:14\n    at Array.map (<anonymous>)\n    at OptionManager.mergeOptions (/Users/rusinov/my-projects/babel/packages/babel-core/lib/config/option-manager.js:55:34)\n    at /Users/rusinov/my-projects/babel/packages/b

Error: Module build failed: TypeError: [BABEL] /Users/rusinov/my-projects/babel/packages/babel-standalone/src/index.js: Cannot read property 'loose' of undefined (While processing: "base$2")
    at _default (/Users/rusinov/my-projects/babel/packages/babel-plugin-transform-optional-chaining/lib/index.js:12:31)
    at /Users/rusinov/my-projects/babel/packages/babel-core/lib/config/option-manager.js:239:12
    at cachedFunction (/Users/rusinov/my-projects/babel/packages/babel-core/lib/config/caching.js:48:17)
    at loadPluginDescriptor (/Users/rusinov/my-projects/babel/packages/babel-core/lib/config/option-manager.js:269:28)
    at /Users/rusinov/my-projects/babel/packages/babel-core/lib/config/option-manager.js:56:14
    at Array.map (<anonymous>)
    at OptionManager.mergeOptions (/Users/rusinov/my-projects/babel/packages/babel-core/lib/config/option-manager.js:55:34)
    at /Users/rusinov/my-projects/babel/packages/babel-core/lib/config/option-manager.js:83:15
    at Array.forEach (<anonymous>)
    at OptionManager.mergeOptions (/Users/rusinov/my-projects/babel/packages/babel-core/lib/config/option-manager.js:82:15)
    at Object.<anonymous> (/Users/rusinov/my-projects/babel/packages/babel-standalone/babel.js:80:7)
    at __webpack_require__ (/Users/rusinov/my-projects/babel/packages/babel-standalone/babel.js:30:30)
    at /Users/rusinov/my-projects/babel/packages/babel-standalone/babel.js:73:18
    at /Users/rusinov/my-projects/babel/packages/babel-standalone/babel.js:76:10
    at webpackUniversalModuleDefinition (/Users/rusinov/my-projects/babel/packages/babel-standalone/babel.js:3:20)
    at Object.<anonymous> (/Users/rusinov/my-projects/babel/packages/babel-standalone/babel.js:10:3)
    at Module._compile (module.js:624:30)
    at Module._compile (/Users/rusinov/my-projects/babel/node_modules/pirates/lib/index.js:88:24)
    at Module._extensions..js (module.js:635:10)
    at Object.newLoader [as .js] (/Users/rusinov/my-projects/babel/node_modules/pirates/lib/index.js:93:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rusinov/my-projects/babel/packages/babel-standalone/test/babel.js:2:15)
    at Module._compile (module.js:624:30)
    at Module._compile (/Users/rusinov/my-projects/babel/node_modules/pirates/lib/index.js:88:24)
    at Module._extensions..js (module.js:635:10)
    at Object.newLoader [as .js] (/Users/rusinov/my-projects/babel/node_modules/pirates/lib/index.js:93:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /Users/rusinov/my-projects/babel/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/rusinov/my-projects/babel/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/rusinov/my-projects/babel/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/Users/rusinov/my-projects/babel/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
make: *** [test-only] Error 1
```

| software         | version(s)
| ---------------- | -------
| babel-standalone            |  7.0.0-beta.2
| node             | 8.5.0
| npm              | 5.4.1
| Operating System | macOS Sierra 10.12.6

**Comment by hzoo** [comment]
Ok need to add this line

Modified: packages/babel-core/src/config/option-manager.js

@ option-manager.js:509 @ function normalizePair(
```diff
  value: {} | Function,
  options: ?{},
} {
-  let options;
+  let options = {};
  let value = pair;
  if (Array.isArray(pair)) {
    if (pair.length > 2) {
```

**Comment by RusinovAnton** [comment]
You da real MVP
