### ISSUE TITLE
Couldn't find preset "env" relative to directory

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6406]
---

Migrated from https://github.com/babel/babel-preset-env/issues/186
Originally created by @adlk on *Fri, 03 Mar 2017 14:49:36 GMT*

---
I'm working with the [`electron-forge`](https://github.com/electron-userland/electron-forge) setup and I'm trying to dynamically require an external node_module that is located in `/Users/name/plugin` Unfortunately babel-preset-env is trying to resolve the preset relative to the required module instead of the local module. 

**Console output when trying to require the module**
```
Error: Couldn't find preset "env" relative to directory "/Users/name/plugin/7ada6103-7315-4c24-93f3-4a3a6a0fa7ee"
    at /Users/name/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/name/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/name/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/name/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/name/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/name/project/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/name/project/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/name/project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at BabelCompiler.compileSync (/Users/name/project/node_modules/electron-compilers/lib/js/babel.js:76:26)
```

**contents of .compilerc**
```
{
  "env": {
    "development": {
      "application/javascript": {
        "presets": [
          [
            "env",
            {
              "targets": {
                "electron": "1.4.15"
              }
            }
          ],
          "react"
        ],
        "plugins": [
          "transform-decorators-legacy",
          "transform-flow-strip-types",
          "transform-class-properties",
          "transform-async-to-generator"
        ],
        "sourceMaps": "inline"
      }
    },
    "production": {
      "application/javascript": {
        "presets": [
          [
            "env",
            {
              "targets": {
                "electron": "1.4.15"
              }
            }
          ],
          "react"
        ],
        "plugins": [
          "transform-decorators-legacy",
          "transform-flow-strip-types",
          "transform-class-properties",
          "transform-async-to-generator"
        ],
        "sourceMaps": "none"
      }
    }
  }
}
```

**How to test this issue:**
Use a clean project (`electron-forge init`) and try to import any random module from a folder that is not within `module.paths`

**Comment by katheryqu** [comment]
hey ,when i add the pkg:env,it doesn't work ,also the same mistakes

Module build failed: Error: Couldn't find preset "env" relative to directory

**Comment by nicolo-ribaudo** [comment]
Can you share your package.json and .babelrc? Usually the cause of this problem is that there are incompatible versions of babel used together.
