### ISSUE TITLE
Unable to combine with syntax-dynamic-import, async await, and Node 6.9

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6417]
---

Migrated from https://github.com/babel/babel-preset-env/issues/168
Originally created by @eliperelman on *Thu, 23 Feb 2017 16:34:23 GMT*

---
I'm trying to configure this to support `syntax-dynamic-import` and async await, but have had some troubles getting it to actually work:

config:

```js
{
  plugins: ['babel-plugin-syntax-dynamic-import'],
  presets: [
    ['babel-preset-env', {
      modules: false,
      targets: {
        node: 6.9
      }
    }]
  ]
}
```

The code I am trying to test this on is:

```js
(async () => {
  const { createServer } = await import('http');
  const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
  const port = process.env.PORT || 3000;

  createServer(async (req, res) => {
    await delay(500);
    console.log('Request!');
    res.end('hi!');
  })
  .listen(port, () => console.log(`Server running on port ${port}`));
})();
```

With the above configuration, I get the error (paths changed for brevity):

```
Module parse failed: src/index.js Unexpected token (4:33)
You may need an appropriate loader to handle this file type.
|
| _asyncToGenerator(function* () {
|   const { createServer } = yield import('http');
|   const delay = function (ms) {
|     return new Promise(function (resolve) {
```

If I include `transform-regenerator` (which I'm not even sure why I would since Node 6.9 supports generators), I get:

```
Module build failed: Error: src/index.js: Expected type "Expression" with option {}
    at Object.t.(anonymous function) [as assertExpression] (node_modules/babel-types/lib/index.js:354:13)
    at Emitter.Ep.explodeExpression (node_modules/regenerator-transform/lib/emit.js:768:7)
    at node_modules/regenerator-transform/lib/emit.js:1002:64
    at Emitter.Ep.explodeExpression (node_modules/regenerator-transform/lib/emit.js:1037:4)
    at node_modules/regenerator-transform/lib/emit.js:366:14
    at Emitter.Ep.explodeStatement (node_modules/regenerator-transform/lib/emit.js:659:4)
    at node_modules/regenerator-transform/lib/emit.js:348:12
    at Array.forEach (native)
    at Emitter.Ep.explodeStatement (node_modules/regenerator-transform/lib/emit.js:347:22)
    at Emitter.Ep.explode (node_modules/regenerator-transform/lib/emit.js:302:40)
    at PluginPass.exit (node_modules/regenerator-transform/lib/visit.js:111:15)
    at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
```

If I switch the code to:

```js

import { createServer as cs } from 'http';

(async () => {
  const { createServer } = await Promise.resolve({ createServer: cs });
  const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
  const port = process.env.PORT || 3000;

  createServer(async (req, res) => {
    await delay(500);
    console.log('Request!');
    res.end('hi!');
  })
  .listen(port, () => console.log(`Server running on port ${port}`));
})();
```

It seems to work fine. Any idea why this combination doesn't work properly? Is this an issue in preset-env or syntax-dynamic-import?

**Comment by ch-luke** [comment]
@hzoo , what was the answer ?

**Comment by existentialism** [comment]
@ch-luke from the old repo: https://github.com/babel/babel-preset-env/issues/168#issuecomment-282105553

**Comment by jridgewell** [comment]
Fixed with https://github.com/babel/babylon/pull/383.
