### ISSUE TITLE
Does not accept options

### ISSUE THREAD

**Issue by hzoo** [babel/babel#6434]
---

Migrated from https://github.com/babel/babel-preset-env/issues/10
Originally created by @tinovyatkin on *Fri, 30 Sep 2016 03:53:05 GMT*

---
I've got an error `Options {"targets":{"chrome":51},"modules":false,"loose":false} passed to /Users/tino/Sites/transfers.do/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/Users/tino/Sites/transfers.do/node_modules/babel-preset-env/lib/index.js")` while trying to use this module in following code:

``` javascript
file = babel.transform(file, {
        sourceMap: false,
        babelrc: false,
        plugins: ['transform-strict-mode'],
        parserOpts: {
          sourceType: 'script',
          plugins: ['flow'],
        },
        presets: [
          ['env', {
            targets: {
              chrome: 51,
            },
            modules: false,
            loose: false,
          }],
        ],
        env: {
          production: {
            // presets: ['babili'],
            compact: true,
            minified: true,
            comments: false,
          },
        },
      }).code
```

**Comment by hzoo** [comment]
---

Migrated from https://github.com/babel/babel-preset-env/issues/10#issuecomment-250731029
Originally created by @hzoo on *Fri, 30 Sep 2016 12:22:37 GMT*

---
The first release is out, it should definitely be at least usable. @tinovyatkin are you sure you are on the latest version of babel (babel-core)

**Comment by hzoo** [comment]
---

Migrated from https://github.com/babel/babel-preset-env/issues/10#issuecomment-250859216
Originally created by @hzoo on *Fri, 30 Sep 2016 21:42:08 GMT*

---
Ok it was supposed to be an export default - fixed in https://github.com/babel/babel-preset-env/commit/fa53e8389ee4f5df275b378da6336a28c62e8c40 (0.0.2)

**Comment by hzoo** [comment]
---

Migrated from https://github.com/babel/babel-preset-env/issues/10#issuecomment-250654348
Originally created by @milesj on *Fri, 30 Sep 2016 04:11:21 GMT*

---
I don't believe this package is actually done. Is there a reason you're trying to use it?

**Comment by hzoo** [comment]
---

Migrated from https://github.com/babel/babel-preset-env/issues/10#issuecomment-302934383
Originally created by @pragmader on *Sun, 21 May 2017 12:41:47 GMT*

---
My build started failing today because of the same issue.

```
[2017-05-21T12:01:22.635Z] [ERROR] [catberry:2020] – Error: Options {"targets":{"browsers":["last 2 versions","not ie <= 10"]},"debug":false} passed to a preset which does not accept options. while parsing file: /home/travis/build/catberry/catberry-todomvc/browser.js
    at /home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/travis/build/catberry/catberry-todomvc/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush (/home/travis/build/catberry/catberry-todomvc/node_modules/babelify/index.js:27:24)
```

The code that uses the plugin is here https://github.com/catberry/catberry/blob/9.0.0/lib/builders/BrowserBundleBuilder.js#L367-L396

Was working the day before, I have builds scheduled every 12 hours. Nothing has changed from our side.

**Comment by hzoo** [comment]
---

Migrated from https://github.com/babel/babel-preset-env/issues/10#issuecomment-250847825
Originally created by @hzoo on *Fri, 30 Sep 2016 20:44:52 GMT*

---
Actually this is probably from the regression from 6.16 (it was working fine before). I think https://github.com/babel/babel/pull/4620 should fix it

**Comment by hzoo** [comment]
---

Migrated from https://github.com/babel/babel-preset-env/issues/10#issuecomment-250832125
Originally created by @tinovyatkin on *Fri, 30 Sep 2016 19:29:03 GMT*

---
Yes, babel-core is 6.16
