### ISSUE TITLE
babel-plugin-transform-react-jsx-source passes null to t.stringLiteral

### ISSUE THREAD

**Issue by fmoo** [babel/babel#6523]
> Choose one: is this a bug report or feature request?

Bug Report:

I seem to be tripping the case in babel-plugin-transform-react-jsx-source where `state.file.log.filename !== "unknown"`, which sets filename to null:

```
var fileName = state.file.log.filename !== "unknown" ? state.file.log.filename : null;
...
path.hub.file.scope.push({ id: fileNameIdentifier, init: t.stringLiteral(fileName) });
```

Which triggers a pretty hard failure:
```
TypeError: unknown: Property value expected type of string but got null
  at Object.validate (.../node_modules/babel-types/lib/definitions/index.js:162:13)
  at validate (.../node_modules/babel-types/lib/index.js:505:9)
  at Object.builder (.../node_modules/babel-types/lib/index.js:466:7)
  at PluginPass.JSXOpeningElement (.../node_modules/babel-plugin-transform-react-jsx-source/lib/index.js:36:70)
  at newFn (.../node_modules/babel-traverse/lib/visitors.js:276:21)
  at NodePath._call (.../node_modules/babel-traverse/lib/path/context.js:76:18)
  at NodePath.call (.../node_modules/babel-traverse/lib/path/context.js:48:17)
  at NodePath.visit (.../node_modules/babel-traverse/lib/path/context.js:105:12)
  at TraversalContext.visitQueue (.../node_modules/babel-traverse/lib/context.js:150:16)
  at TraversalContext.visitSingle (.../node_modules/babel-traverse/lib/context.js:108:19)
  at TraversalContext.visit (.../node_modules/babel-traverse/lib/context.js:192:19)
  at Function.traverse.node (.../node_modules/babel-traverse/lib/index.js:114:17)
```

I'm doing this by running a babel transform via the react-native  CLI:

```
yarn react-native bundle --entry-file path/to/index.js --bundle-output _gen/  --transformer ./myTransformer.js
```

### Input Code

```js
const {transform} = require('babel-core');
const platformAssetTransformer = babel => {
  const t = babel.types;
  return {
    visitor: {}
  }
};

module.exports = {
  transform: {file} => {
    return transform(file.src, {
      presets: ['react-native'],
      plugins: [platformAssetTransformer],
    });
  },
};
```

### Expected Behavior

bundler bundles the app successfully.

### Current Behavior
```
TransformError: .../path/to/index.js: unknown: Property value expected type of string but got null
```

### Possible Solution

in babel-plugin-transform-react-jsx-source/lib/index.js, wrap the scope update with a conditional on the string literal.
```
path.hub.file.scope.push({ id: fileNameIdentifier, init: t.stringLiteral(fileName) });
```
like this:
```
if (fileName) {
  path.hub.file.scope.push({ id: fileNameIdentifier, init: t.stringLiteral(fileName) });
}
```

### Context

Just trying to apply a custom transform for some apps that need a slightly different package config for a react-native project.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 6.26.0
| babel-types | 6.26.0
| babel-plugin-transform-react-jsx-source | 6.22.0
| node             | 7.8.0
| npm              | 4.2.0
| Operating System | OSX 10.12.6

**Comment by fmoo** [comment]
Actually, it looks like this was fixed in #6239 about a month ago.  Could we get a new build of babel-plugin-transform-react-jsx-source ?  The latest, 6.22.0, was published 9 months ago.

**Comment by nicolo-ribaudo** [comment]
You can use version 7.0.0-beta.3

**Comment by fmoo** [comment]
It sounds like we're not going to be able to update our whole repository to
the 7 beta any time soon.

Any hope for some sort of backport of the fix to babel-6?  I can probably
manage this on a private fork, but would prefer to have something published

**Comment by xtuc** [comment]
Fixed in 7.
