### ISSUE TITLE
Error: Couldn't find preset "latest" relative to directory

### ISSUE THREAD

**Issue by wzup** [babel/babel#6558]
So you claim that some presets are deprecated and that

> babel-preset-env behaves exactly the same as babel-preset-latest

Then why `babel-preset-env` doesn't work and Webpack can't compile and throws requiring `babel-preset-latest`? 

```
ERROR in ./node_modules/react/index.js
    Module build failed: Error: Couldn't find preset "latest" relative to directory "C:\\Users\\user\\app\\node_modules\\react"
        at C:\Users\user\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
        at Array.map (native)
        at OptionManager.resolvePresets (C:\Users\user\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
        at OptionManager.mergePresets (C:\Users\user\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
        at OptionManager.mergeOptions (C:\Users\user\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
        at OptionManager.init (C:\Users\user\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
        at File.initOptions (C:\Users\user\app\node_modules\babel-core\lib\transformation\file\index.js:212:65)
        at new File (C:\Users\user\app\node_modules\babel-core\lib\transformation\file\index.js:135:24)
        at Pipeline.transform (C:\Users\user\app\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
        at transpile (C:\Users\user\app\node_modules\babel-loader\lib\index.js:50:20)
        at C:\Users\user\app\node_modules\babel-loader\lib\fs-cache.js:118:18
        at ReadFileContext.callback (C:\Users\user\app\node_modules\babel-loader\lib\fs-cache.js:31:21)
        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
     @ multi react react-dom react-bootstrap react-redux react-router redux-thunk redux-logger
```

Is `babel-preset-env` really a substitute to latest and other presets? How to use it? 

Here is my config. What's wrong with it?

```
{
    "presets": [
        // ["latest", {"modules": false}],
        ["env", {"targets": {"node": "current"}}],
        ["stage-0"],
        ["react"],
    ],
    "plugins": ["syntax-dynamic-import"],
    "env": {
        "test": {
            "plugins": ["transform-es2015-modules-commonjs"]
        }
    }
}
```

**Comment by wzup** [comment]
vibrant Slack community? lol
Obviously a bunch of clowns.

![https___slack babeljs io - google chrome 2017-10-26 13 47 19](https://user-images.githubusercontent.com/3880497/32036794-8702a10a-ba54-11e7-82c9-ca42c207d7c8.png)

**Comment by nicolo-ribaudo** [comment]
I would suggest clicking on that blue link

**Comment by wzup** [comment]
So far, `babel-preset-env` doesn't do what Babel docs say. It is not a substitute for other plugins in no way.

I've installed `babel-preset-latest` back and my app works well as before.

**Comment by loganfsmyth** [comment]
> Obviously a bunch of clowns.

Asking for help and also insulting people doesn't exactly motivate me to want to help you?

**Comment by loganfsmyth** [comment]
Sounds like you've left off part of [the config we recommend](https://github.com/babel/babel-loader#usage), specifically

    exclude: /(node_modules|bower_components)/,

**Comment by nicolo-ribaudo** [comment]
`env` only enables the plugins that you need (specified by `"targets"`). `"node": current` means "The node version installed on my computer".
If you are using an up-to-date node version, it supports (almost) every js feature up to es2017, so Babel doesn't need to transpile anything.

**Comment by hzoo** [comment]
@wzup  The error message you posted is about preset-latest but you are saying that the error is having to do with using preset-env?

> babel-preset-env behaves exactly the same as babel-preset-latest
> Then why babel-preset-env doesn't work an..

It behaves the same if the configuration is done correctly? Clearly it wasn't working for you and that's why you can make an issue to ask for help but I would recommend doing so without such negative comments. Don't expect the help then by acting in such a demanding way, no one has to answer so I would urge that you have some courtesy for us next time 👌.

---

Maybe you could use some context on the slack issue? I'm not sure what you were expecting when you wanted to join Slack but the link to signup is in that site? https://github.com/babel/notes/issues/38 - We had a bot trying to spam all our users with messages so we had to take that down. I'm not sure why having that message means that the community is what you say it is?

**Comment by wzup** [comment]
@hzoo exactly. 

Any fix? `babel-preset-env` DOES NOT behaves same as `babel-preset-latest`. Error still exists. It is thrown by several packages:

```
    ERROR in ./node_modules/react-dom/index.js
    ERROR in ./node_modules/react/index.js
    ERROR in ./node_modules/react-redux/es/index.js
    ERROR in ./node_modules/redux-thunk/lib/index.js
    ERROR in ./node_modules/react-router/es/index.js
    ERROR in ./node_modules/redux-logger/dist/redux-logger.js

    Module build failed: Error: Couldn't find preset "latest" relative to directory "C:\\app"
        at C:\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
        at Array.map (native)
        at OptionManager.resolvePresets (C:\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
        at OptionManager.mergePresets (C:\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
        at OptionManager.mergeOptions (C:\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
        at OptionManager.init (C:\app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
        at File.initOptions (C:\app\node_modules\babel-core\lib\transformation\file\index.js:212:65)
        at new File (C:\app\node_modules\babel-core\lib\transformation\file\index.js:135:24)
        at Pipeline.transform (C:\app\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
        at transpile (C:\app\node_modules\babel-loader\lib\index.js:50:20)
        at C:\app\node_modules\babel-loader\lib\fs-cache.js:118:18
        at ReadFileContext.callback (C:\app\node_modules\babel-loader\lib\fs-cache.js:31:21)
        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
     @ multi react react-dom react-redux react-router redux-thunk redux-logger
```

This is my webpack config. 
`env` in `options.presets` throws. If replaced with `latest`, it works ok.
```
{
    resource: {
        test: /\.js$/,
        include: [
            path.join(__dirname, '..', 'node_modules'),
            path.resolve(__dirname, '..', 'src/js')
        ]
    },
    use: [{
        loader: 'babel-loader',
        options: {
            presets: ["env", "stage-0", "react"], // <== "env" throws! Only "latest" works ok.
            code: true,
            comments: true,
            cacheDirectory: true,
        }
    }],
},
```

**Comment by hayesgm** [comment]
I experienced this issue as well (should we open a new issue without all of the non-relevant conversation?). I am using brunch and choose the quick fix, I added:

`"babel-preset-latest": "6.24.1"`

to my `package.json` file. I am sure this is not the best solution, and I would be happy to understand what a better solution would be.

**Comment by existentialism** [comment]
```js
        test: /\.js$/,
        include: [
            path.join(__dirname, '..', 'node_modules'),
            path.resolve(__dirname, '..', 'src/js')
        ]
    },
```
It might be occurring because you're including compiling `node_modules` and trying to compile `preset-env`?

Ref: https://github.com/babel/babel/issues/6130#issuecomment-324495961
