### ISSUE TITLE
TypeError thrown saying result.deopt.isIdentifier is not a function

### ISSUE THREAD

**Issue by futagoza** [babel/babel#6759]
Choose one: is this a bug report or feature request? __a bug report__

It seems like [`result.deopt.isIdentifier()` in babel-preset-env/src/use-built-ins-plugin.js#L201](https://github.com/babel/babel/blob/master/experimental/babel-preset-env/src/use-built-ins-plugin.js#L201) is not a function when transpiling some files, although I'm not sure what the conditions are for this as it's not telling me what source file was being transpiled when this error got thrown.

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```json
{

    "sourceMaps": true,
    "plugins": [
        [ "@babel/transform-runtime" ]
    ],
    "presets": [

        [ "@babel/env", {

            "exclude": [
                "transform-regenerator"
            ],
            "loose": true,
            "targets": {
                "node": 4
            },
            "useBuiltIns": "usage"

        } ],
        "@babel/stage-0"

    ]

}
```

### Expected Behavior

It transpiles, or if my source code has a problem, it shows where this problem is, even if it doesn't know what the problem is.

### Current Behavior

After transpiling 2 files, it chokes and throws the error:
```
TypeError: result.deopt.isIdentifier is not a function
    at PluginPass.enter (...\node_modules\@babel\preset-env\lib\use-built-ins-plugin.js:153:51)
    at newFn (...\node_modules\@babel\traverse\lib\visitors.js:223:21)
    at NodePath._call (...\node_modules\@babel\traverse\lib\path\context.js:64:19)
    at NodePath.call (...\node_modules\@babel\traverse\lib\path\context.js:38:17)
    at NodePath.visit (...\node_modules\@babel\traverse\lib\path\context.js:95:12)
    at TraversalContext.visitQueue (...\node_modules\@babel\traverse\lib\context.js:139:18)
    at TraversalContext.visitSingle (...\node_modules\@babel\traverse\lib\context.js:98:19)
    at TraversalContext.visit (...\node_modules\@babel\traverse\lib\context.js:180:19)
    at Function.traverse.node (...\node_modules\@babel\traverse\lib\index.js:91:17)
    at NodePath.visit (...\node_modules\@babel\traverse\lib\path\context.js:102:18)
```

### Possible Solution

I don't know about a solution, but you could start by looking at [commit/9cf017](https://github.com/babel/babel/commit/9cf017b2ca43f86906595989762346fda2d16075) which added the line [babel-preset-env/src/use-built-ins-plugin.js#L201](https://github.com/babel/babel/blob/master/experimental/babel-preset-env/src/use-built-ins-plugin.js#L201)

### Context

I can't transpile all of the source files in my project :cry:

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.31
| node             | 8.9.0
| npm              | 5.4.2
| Operating System | Windows 10 Home x64

**Comment by existentialism** [comment]
@futagoza see https://github.com/babel/babel/pull/6745

**Comment by futagoza** [comment]
@thanks, closing this in that case 😄
