### ISSUE TITLE
ReferenceError Unknown plugin @babel/transform-runtime in .babelrc

### ISSUE THREAD

**Issue by liuliangsir** [babel/babel#6769]
Choose one: is this a bug report or feature request?

Bug

I've replace `babel-plugin-transform-runtime` with `@babel/plugin-transform-runtime`. Saddly,
i run into the following issue.

Input Code

```
ERROR in ./www/static/src/entry/home/index.js
Module build failed: ReferenceError: Unknown plugin "@babel/transform-runtime" specified in "/Users/liuliang/Desktop/project/w3ctech-birthday-gift/www/static/src/.babelrc" at 1, attempted to resolve relative to "/Users/liuliang/Desktop/project/w3ctech-birthday-gift/www/static/src"
    at /Users/liuliang/Desktop/project/w3ctech-birthday-gift/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/liuliang/Desktop/project/w3ctech-birthday-gift/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/liuliang/Desktop/project/w3ctech-birthday-gift/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/liuliang/Desktop/project/w3ctech-birthday-gift/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/liuliang/Desktop/project/w3ctech-birthday-gift/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/liuliang/Desktop/project/w3ctech-birthday-gift/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/liuliang/Desktop/project/w3ctech-birthday-gift/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/liuliang/Desktop/project/w3ctech-birthday-gift/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/liuliang/Desktop/project/w3ctech-birthday-gift/node_modules/babel-loader/lib/index.js:175:20)
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:3001/ webpack/hot/dev-server ./entry/home
```
Babel/Babylon Configuration (.babelrc, package.json, cli command)

```
{
    "presets": [
        [
            "env",
            {
                "modules": false
            }
        ],
        // "stage-2",
        "react"
    ],
    "plugins": [
        "react-hot-loader/babel",//top level variables are registered
        [
            "@babel/transform-runtime", {
                "helpers": true,
                "polyfill": true,
                "regenerator": true,
                "moduleName": "@babel/runtime",
                "useBuiltIns": false,
                "useESModules": false
            }
        ],
        "transform-decorators-legacy",
        "add-module-exports",
        "transform-object-rest-spread"
    ],
    "comments": false
}
```
Your Environment
```
    "dependencies": {
        "@babel/runtime": "^7.0.0-beta.31",
        "grommet": "^1.3.4",
        "highlight.js": "^8.8.0",
        "marked": "^0.3.5",
        "marked-toc": "^0.3.0",
        "node-crontab": "0.0.8",
        "prop-types": "^15.6.0",
        "react": "^16.0.0",
        "react-dom": "^16.0.0",
        "react-redux": "^5.0.6",
        "redux": "^3.7.2",
        "redux-actions": "^2.2.1",
        "redux-promise": "^0.5.3",
        "redux-saga": "^0.16.0",
        "redux-thunk": "^2.2.0",
        "superagent": "^1.3.0",
        "thinkjs": "2.2.x"
    },
    "devDependencies": {
        "@babel/plugin-transform-runtime": "^7.0.0-beta.31",
        "autoprefixer": "^7.1.5",
        "babel-cli": "^6.26.0",
        "@babel/core": "^7.0.0-beta.31",
        "babel-loader": "^7.1.2",
        "babel-plugin-add-module-exports": "^0.2.1",
        "babel-plugin-transform-decorators-legacy": "^1.3.4",
        "babel-plugin-transform-object-rest-spread": "^6.26.0",
        "babel-preset-env": "^1.6.1",
        "babel-preset-react": "^6.24.1",
        "fecs-loader": "^0.4.0",
        "postcss-sorting": "^3.0.2",
        "react-hot-loader": "^3.0.0",
        "redbox-react": "^1.5.0",
        "redux-devtools": "^3.4.0",
        "redux-devtools-dock-monitor": "^1.1.2",
        "redux-devtools-log-monitor": "^1.3.0",
        "stc": "^2.0.4",
        "stc-cdn": "^1.0.2",
        "stc-css-compress": "^1.0.1",
        "stc-html-compress": "^1.0.1",
        "stc-localstorage": "^1.0.4",
        "stc-localstorage-ejs": "^1.0.3",
        "stc-resource-version": "^1.0.1",
        "stc-uglify": "^1.0.1",
        "webpack": "^3.8.1",
        "webpack-dashboard": "^1.0.0",
        "webpack-dev-server": "^2.9.2"
    }
```

| software         | version(s)
| ---------------- | -------
| node             | 8.6.0
| npm              | 5.5.1
| Operating System | macOS High Sierra(10.13)

**Comment by nicolo-ribaudo** [comment]
You should update all your Babel packages to v7

**Comment by hzoo** [comment]
Yeah sorry about that, but you can't just add `@babel` for 1 of the plugins because that would be using `@babel/core` v7  when everything else expects v6. Anything that is part of babel needs to be beta.31, and babel-loader should be 8.0.0-beta.0
