### ISSUE TITLE
@babel/plugin-proposal-class-properties TypeError

### ISSUE THREAD

**Issue by mgcrea** [babel/babel#6793]
Bug:

Compiling works fine but I can't run tests.

Looks like @babel/plugin-proposal-class-properties does not guard against an empty config and/or jest is not properly providing one.

```
    TypeError: Cannot read property 'loose' of undefined
      
      at _default (node_modules/@babel/plugin-proposal-class-properties/lib/index.js:21:23)
      at Function.memoisePluginContainer (node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
      at Function.normalisePlugin (node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
          at Array.map (<anonymous>)
      at Function.normalisePlugins (node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (node_modules/babel-core/lib/transformation/file/index.js:135:24)
```

### Input Code

```js
npm test
```

```bash
$ cat package.json | jq .scripts.test
"NODE_ENV=test jest"
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "node": "4"
      }
    }]
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
  ]
}
```

### Your Environment

```
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.31",
    "@babel/core": "^7.0.0-beta.31",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.31",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.31",
    "@babel/plugin-transform-classes": "^7.0.0-beta.31",
    "@babel/preset-env": "^7.0.0-beta.31",
    "jest": "^21.2.1",
    "rimraf": "^2.6.2"
  },
```

**Comment by hzoo** [comment]
it's using an older version of babel-core that doesn't provide the 2nd options object https://github.com/facebook/jest/pull/4557 shouldn't be our issue but we are trying to figure out peerDeps

```js
function _default(_ref, options) {
  var t = _ref.types;
  var loose = options.loose;
```
