### ISSUE TITLE
Unknown option: .targets

### ISSUE THREAD

**Issue by cyberalien** [babel/babel#6854]
I've encountered strange bug in 7.0.0-beta.32 when used with web pack when trying to set options for preset-env.

From webpack.config.js

```        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: /(node_modules|bower_components)/,
                    use: {
                        loader: 'babel-loader',
                        options: {
                            presets: ["@babel/preset-env", {
                                "targets": {
                                    "chrome": 52
                                }
                            }],
                        }
                    }
                }
            ]
        }
```

Results in following error:

```Module build failed: ReferenceError: [BABEL] /src/app.js: Unknown option: .targets. Check out http://babeljs.io/docs/usage/options/ for more information about options.
        at buildUnknownError (/node_modules/@babel/core/lib/config/options.js:79:11)
        at /node_modules/@babel/core/lib/config/options.js:65:57
        at Array.forEach (<anonymous>)
        at validate (/node_modules/@babel/core/lib/config/options.js:55:21)
        at /node_modules/@babel/core/lib/config/option-manager.js:259:36
        at cachedFunction (/node_modules/@babel/core/lib/config/caching.js:48:17)
        at loadPresetDescriptor (/node_modules/@babel/core/lib/config/option-manager.js:250:10)
        at /node_modules/@babel/core/lib/config/option-manager.js:52:14
        at Array.map (<anonymous>)
        at OptionManager.mergeOptions (/node_modules/@babel/core/lib/config/option-manager.js:51:34)
        at OptionManager.init (/node_modules/@babel/core/lib/config/option-manager.js:115:14)
        at manageOptions (/node_modules/@babel/core/lib/config/option-manager.js:31:30)
        at loadConfig (/node_modules/@babel/core/lib/config/index.js:15:37)
        at transformSync (/node_modules/@babel/core/lib/transform-sync.js:13:36)
        at Object.transform (/node_modules/@babel/core/lib/transform.js:20:65)
        at transpile (/node_modules/babel-loader/lib/index.js:55:20)
        at Object.module.exports (/node_modules/babel-loader/lib/index.js:179:20)
```

Error is triggered by second entry in "presets" array. Removing that entry results in everything working correctly, but trying to set any options results in errors.

babel/core version: 7.0.0-beta.32
babel/preset-env version: 7.0.0-beta.32
babel-loader version: 8.0.0-beta.0
webpack version: 3.8.1

**Comment by cyberalien** [comment]
Sorry, figured it out. Missed that preset with options should be in nested array.

Correct code:

```                    options: {
                        presets: [
                            ['@babel/preset-env', {
                            targets: {
                                chrome: 52
                            }
                        }]
                        ]
                    }
```
