### ISSUE TITLE
Babylon regression: crash on yield expression surrounded by parens

### ISSUE THREAD

**Issue by alangpierce** [babel/babel#6864]
Choose one: is this a bug report or feature request?
**Bug report**

### Input Code

```js
function *f() {
  (yield a => a);
}
```

### CLI commands

Parses fine on babylon 7.0.0-beta.30
```
> yarn add babylon@7.0.0-beta.30
...
> node -e "require('babylon').parse('function *f() { (yield a => a); }');"
>
```

Fails on babylon 7.0.0-beta.31
```
> yarn add babylon@7.0.0-beta.31
...
> node -e "require('babylon').parse('function *f() { (yield a => a); }');"
/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:830
    throw err;
    ^

SyntaxError: yield is not allowed in the parameters of an arrow function inside a generator (1:17)
    at Parser.raise (/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:822:15)
    at Parser.parseArrowExpression (/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:3873:12)
    at Parser.parseExprAtom (/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:3226:25)
    at Parser.parseExprSubscripts (/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:2961:21)
    at Parser.parseMaybeUnary (/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:2939:21)
    at Parser.parseExprOps (/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:2844:21)
    at Parser.parseMaybeConditional (/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:2814:21)
    at Parser.parseMaybeAssign (/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:2773:21)
    at Parser.parseYield (/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:4107:28)
    at Parser.parseMaybeAssign (/Users/alanpierce/code/babylon_test/node_modules/babylon/lib/index.js:2752:24)
>
```

### Context
This is causing an error in the [decaffeinate test suite](https://github.com/decaffeinate/decaffeinate#status). An intermediate step in decaffeinate is failing when using babylon to parse this line of code (which is in a generator):
```
var joiners = (yield joinerIDs.map(id => User.findById(id))).map(user => _.pick(user.toObject(), ['_id', 'email', 'name', 'firstName', 'lastName']));
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babylon          | 7.0.0-beta.31 (it also fails on master)
| node             | v9.2.0
| Operating System | macOS 10.13.1

**Comment by nicolo-ribaudo** [comment]
As a workaround, you can wrap arrow functions in parentheses
