### ISSUE TITLE
createTypeAnnotationBasedOnTypeof(type) throwing error when not supposed to

### ISSUE THREAD

**Issue by gchamon** [babel/babel#6880]
Ran into an issue using babel with gulp, where the mentioned function was throwing the following error:

```
events.js:160                                   
      throw er; // Unhandled 'error' event      
      ^                                         
Error: /home/gchamon/WayCarbon/projetos/eclimas/src/app/admin/factorBuilder/libs/nerdamer.core.js: Invalid typeof value                                                                                
at Object.createTypeAnnotationBasedOnTypeof (/home/gchamon/WayCarbon/projetos/eclimas/node_modules/babel-types/lib/flow.js:106:11)                                                                 
at inferAnnotationFromBinaryExpression (/home/gchamon/WayCarbon/projetos/eclimas/node_modules/babel-traverse/lib/path/inference/inferer-reference.js:136:12)                                       
at getConditionalAnnotation (/home/gchamon/WayCarbon/projetos/eclimas/node_modules/babel-traverse/lib/path/inference/inferer-reference.js:171:18)                                                 
at getTypeAnnotationBindingConstantViolations (/home/gchamon/WayCarbon/projetos/eclimas/node_modules/babel-traverse/lib/path/inference/inferer-reference.js:45:18)                                
at NodePath.exports.default (/home/gchamon/WayCarbon/projetos/eclimas/node_modules/babel-traverse/lib/path/inference/inferer-reference.js:17:14)                                                   
at NodePath._getTypeAnnotation (/home/gchamon/WayCarbon/projetos/eclimas/node_modules/babel-traverse/lib/path/inference/index.js:64:20)                                                            
at NodePath.getTypeAnnotation (/home/gchamon/WayCarbon/projetos/eclimas/node_modules/babel-traverse/lib/path/inference/index.js:31:19)
at Identifier (/home/gchamon/WayCarbon/projetos/eclimas/node_modules/babel-plugin-minify-simplify/lib/index.js:509:18)
at NodePath._call (/home/gchamon/WayCarbon/projetos/eclimas/node_modules/babel-traverse/lib/path/context.js:76:18)
at NodePath.call (/home/gchamon/WayCarbon/projetos/eclimas/node_modules/babel-traverse/lib/path/context.js:48:17)  
```

upon investigation, I decided to verify what was actually inside `type` by modifying the function `createTypeAnnotationBasedOnTypeof(type)` inside *flow.js*, altering the error throwing line to:
```JavaScript
throw new Error(`Invalid typeof value: '${type}' (${typeof type})`);
```
which now, interestingly, yelds the error:
```
Invalid typeof value: 'undefined ' (string)
```
Notice the blank space after `undefined`. Trying a hack to make it work, replacing `" "` to `""` as in:
```JavaScript
type = type.replace(" ", "");
```
gulp runs fine alright. What is going on?

**Comment by nicolo-ribaudo** [comment]
Which is the code that causes babel to throw? A starting point for a proper fix would be to understand _why_ there is that space.

**Comment by gchamon** [comment]
That goes without saying, but following the traceback we can see that the error is raised in the scope of the babel-traverse -> minify then all the way to babel-type so it is all self contained inside babel-maintained code, which means even if I pinpointed the source of the issue I couldn't correct it myself without diverging from this repo.

Anyway, the provided "hack" works and everything minifies as expected (too well actually, I need to figure out how to make it respect angular names so it doesn't break the framework)

**Comment by nicolo-ribaudo** [comment]
Can you provide an example of code which, when run trought Babel with the `babel-minify` preset, throws that error? `"undefind "` should never be passed to that function, so the bug is somewhere else. Without reproducing the error, it is impossible to know where it exactly is.

**Comment by gchamon** [comment]
I am sorry I did not update you guys on the issue. I believe the issue was with our code, some typo an ex-employee left and nobody knew what was going on. Really sorry to waste your time on it. This should be closed and, hopefully, forgotten.

**Comment by existentialism** [comment]
@gchamon thanks for the update! let us know if you run into it again!
