### ISSUE TITLE
[Bug] Using `super` in `async` method fails in some cases

### ISSUE THREAD

**Issue by firelizzard18** [babel/babel#6883]
I have a class, `BaseClass`, that defines an instance method, `async get()`. I have a class, `DerivedClass`, that is derived from `BaseClass`, that overrides an instance method, `async get()`. When the module including `DerivedClass` and `BaseClass` is transpiled per my settings for `babel-preset-env`, the result is invalid.

This is because the overridden `get()` calls `super.get()`, but the transpilation process converts the method body into an anonymous generator function which is passed to `_asyncToGenerator`. `super` is not valid in the context of the anonymous generator function. Thus, the ECMAScript interpreter fails to parse the file.

### Input Code

```js
class DerivedClass extends BaseClass {
    async get() {
        let r = await super.get()
        return r.Token
    }
}
```

### Output Code

```js
let DerivedClass = class DerivedClass extends BaseClass {
    get() {
        return _asyncToGenerator(function* () {
            let r = yield super.get();
            return r.Token;
        })();
    }
};
```

### Babel/Babylon Configuration (API)
```js
{
    presets: [
      ['env', {
        loose: true,
        modules: 'systemjs',
        targets: {
          browsers: [
            "last 2 Chrome versions",
            // "last 2 Edge versions"
          ]
        }
      }],
      'stage-1'
    ],
}
```

### Expected Behavior
`DerivedClass` transpiles to something that is valid (for the specified browsers).

### Current Behavior
`DerivedClass` transpiles to something that is not valid (for the specified browsers).

### Possible Solution
```js
let DerivedClass = class DerivedClass extends BaseClass {
    get() {
        let _get = () => super.get();
        return _asyncToGenerator(function* () {
            let r = yield _get();
            return r.Token;
        })();
    }
};
```

### Context
I am trying to switch from `babel-preset-es2015` to `babel-preset-env`. I need to support recent versions of Chrome and recent versions of Edge.

### Your Environment

Dependencies:
```json
{
"babel-plugin-syntax-flow": "^6.18.0",
"babel-plugin-transform-async-to-generator": "^6.24.1",
"babel-plugin-transform-class-properties": "^6.24.1",
"babel-plugin-transform-decorators-legacy": "^1.3.4",
"babel-plugin-transform-flow-strip-types": "^6.22.0",
"babel-preset-env": "^1.6.1",
"babel-preset-es2015": "^6.24.1",
"babel-preset-stage-1": "^6.24.1",
"gulp-babel": "^7.0.0"
}
```

**Comment by rohozhnikoff** [comment]
hey @firelizzard18 
you use old version of `babel-plugin-transform-async-to-generator`

current version 7.0.0-beta.32 compile you input to:
```
let DerivedClass = class DerivedClass extends BaseClass {
  get() {
    var _superprop_callGet = (..._args) => super.get(..._args);

    return _asyncToGenerator(function* () {
      let r = yield _superprop_callGet();
      return r.Token;
    })();
  }
};```

**Comment by firelizzard18** [comment]
I don't think my config was actually using that plugin at all. I have `preset-env` configured as above, but the only plugin I was actually using was `transform-decorators-legacy`. I updated to `7.0.0-beta.3` and nothing changed. I added `transform-async-to-generator` to `plugins: [...]` and now I get the following error: `path.get(...).unwrapFunctionEnvironment is not a function`.

Full config (updated, modules = 'systemjs'):
```js
module.exports = function(modules) {
  return {
    filename: '',
    filenameRelative: '',
    sourceMap: true,
    sourceRoot: '',
    moduleRoot: path.resolve('src').replace(/\\/g, '/'),
    moduleIds: false,
    comments: false,
    compact: false,
    code: true,
    presets: [
      ['env', {
        loose: true,
        modules: modules,
        targets: {
          browsers: [
            "last 2 Chrome versions",
            "last 2 Edge versions"
          ]
        }
      }],
      'stage-1'
    ],
    plugins: [
      'transform-decorators-legacy',
      'transform-async-to-generator' // added
    ]
  };
};
```

Gulp task:
```js
var babel = require('gulp-babel');
var babelOptions = require('../babel-options');
gulp.task('compile', function() {
    ...
    .pipe(babel(babelOptions('systemjs')))
    ...
}
```

**Comment by rohozhnikoff** [comment]
you still use old modules
7.0 change packages-names to scoped

try this
```
['env', { >> ['@babel/env', {
'stage-1' >> '@babel/stage-1'
plugins: [
      'transform-decorators-legacy', >>  '@babel/plugin-transform-decorators-legacy'
      'transform-async-to-generator' >> '@babel/transform-async-to-generator'
    ]

**Comment by firelizzard18** [comment]
Now I get the following:

```
events.js:136
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'method' of undefined
    at _default (C:\Users\me\project\node_modules\@babel\plugin-transform-async-to-generator\lib\index.js:15:24)
    at Function.memoisePluginContainer (C:\Users\me\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:113:13)
    at Function.normalisePlugin (C:\Users\me\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:32)
    at C:\Users\me\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\me\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\me\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\me\project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\me\project\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\me\project\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\me\project\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at DestroyableTransform._transform (C:\Users\me\project\node_modules\gulp-babel\index.js:36:22)
    at DestroyableTransform.Transform._read (C:\Users\me\project\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (C:\Users\me\project\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Users\me\project\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\me\project\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (C:\Users\me\project\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at YamlTransform.ondata (C:\Users\me\project\node_modules\readable-stream\lib\_stream_readable.js:612:20)
    at YamlTransform.emit (events.js:159:13)
    at addChunk (C:\Users\me\project\node_modules\readable-stream\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\me\project\node_modules\readable-stream\lib\_stream_readable.js:271:11)
    at YamlTransform.Readable.push (C:\Users\me\project\node_modules\readable-stream\lib\_stream_readable.js:238:10)
    at YamlTransform.Transform.push (C:\Users\me\project\node_modules\readable-stream\lib\_stream_transform.js:146:32)
    at afterTransform (C:\Users\me\project\node_modules\readable-stream\lib\_stream_transform.js:102:51)
    at TransformState.afterTransform (C:\Users\me\project\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at YamlTransform._transform (C:\Users\me\project\build\tools\compile-yaml.js:23:16)
    at YamlTransform.Transform._read (C:\Users\me\project\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at YamlTransform.Transform._write (C:\Users\me\project\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Users\me\project\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\me\project\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at YamlTransform.Writable.write (C:\Users\me\project\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at write (C:\Users\me\project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\me\project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\Users\me\project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
```

Config (`transform-decorators-legacy` has no scoped equivalent):
```js
module.exports = function(modules) {
  return {
    ...
    presets: [
      ['@babel/preset-env', {
        loose: true,
        modules: modules,
        targets: {
          browsers: [
            "last 2 Chrome versions",
            "last 2 Edge versions"
          ]
        }
      }],
      '@babel/preset-stage-1'
    ],
    plugins: [
      'transform-decorators-legacy',
      '@babel/plugin-transform-async-to-generator'
    ]
  };
};
```

Packages:
```json
{
  ...
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.32",
    "@babel/plugin-syntax-flow": "^7.0.0-beta.32",
    "@babel/plugin-transform-async-to-generator": "^7.0.0-beta.32",
    "@babel/plugin-transform-flow-strip-types": "^7.0.0-beta.32",
    "@babel/preset-env": "^7.0.0-beta.32",
    "@babel/preset-stage-1": "^7.0.0-beta.32",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "gulp": "^3.9.1",
    "gulp-babel": "^7.0.0",
    ...
  },
}
```

**Comment by firelizzard18** [comment]
Looks like the issue was `gulp-babel`. I needed to update to `8.0.0-beta.0`.
