### ISSUE TITLE
sourceType: "unambiguous" does not detect modules

### ISSUE THREAD

**Issue by simondel** [babel/babel#6912]
# Bug report

When I try to parse code that is part of a module with options `{ sourceType: 'unambiguous' }` the parsing fails.

### Input Code
[Reproduction repository](https://github.com/simondel/babylon-unambiguous)

```js
var babylon = require('babylon');

var code = `import fs from 'fs'; fs.readFileSync('myfile.js');`;
var options = { sourceType: 'unambiguous' };

console.log(`parsing "${code}" with options ${JSON.stringify(options)}`);
var result = babylon.parse(code, options);
console.log(`parsing succeeded: ${result != null}`);
```

### Expected Behavior
I would expect Babylon to parse the code as a module.

### Current Behavior
Babylon throws the error that the code cannot be parsed as a script:
```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
    at Parser.pp$5.raise (C:\dev\temp\babylon-unambiguous\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp$1.parseStatement (C:\dev\temp\babylon-unambiguous\node_modules\babylon\lib\index.js:1881:16)
    at Parser.pp$1.parseBlockBody (C:\dev\temp\babylon-unambiguous\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseTopLevel (C:\dev\temp\babylon-unambiguous\node_modules\babylon\lib\index.js:1778:8)
    at Parser.parse (C:\dev\temp\babylon-unambiguous\node_modules\babylon\lib\index.js:1673:17)
    at Object.parse (C:\dev\temp\babylon-unambiguous\node_modules\babylon\lib\index.js:7305:37)
    at Object.<anonymous> (C:\dev\temp\babylon-unambiguous\index.js:7:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

### Context
We are parsing JavaScript code with Babylon which could either be a script or a module. We found the sourceType `"unambiguous"` and that should be a great fix for our use case.

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  none
| Babylon          | 6.18.0
| node             |  6.9.5
| npm              |  5.3.0
| Operating System | Windows 10 Enterprise (version 1709)

**Comment by simondel** [comment]
Whoops! Turns out this is a beta feature for v7 that has not yet been released! For now we'll keep the try-catch that we have right now.
