### ISSUE TITLE
TypeError: test.js: Duplicate declaration "tmp" (This is an error on an internal node. Probably an internal error.)

### ISSUE THREAD

**Issue by TimWolla** [babel/babel#6923]
Choose one: bug report

The error message

> TypeError: test.js: Duplicate declaration "tmp" (This is an error on an internal node. Probably an internal error.)

is shown when transpiling the input code. node successfully executes the input code.

### Input Code

```js
async function foo() {
	(async function (number) {
		const tmp = number
	})
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{ "presets": [ [ "@babel/env"
               , { "targets": { "browsers": [ "last 2 chrome versions"
                                            , "last 2 chromeandroid versions"
                                            , "firefox esr"
                                            , "last 2 firefox versions"
                                            , "edge >= 15"
                                            , "safari >= 11"
                                            ]
                              }
                 , "debug": true
                 }
               ]
             ]
}
```

```js
{
  "dependencies": {
    "@babel/cli": "^7.0.0-beta.32",
    "@babel/core": "^7.0.0-beta.32",
    "@babel/preset-env": "^7.0.0-beta.32",
    "regenerator-runtime": "^0.11.0"
  }
}
```

### Expected Behavior

The script is successfully transpiled.

### Current Behavior

The given error message appears:

```
root@3f46f465fd04:/pwd# yarn run babel test.js
yarn run v1.3.2
warning package.json: No license field
$ /pwd/node_modules/.bin/babel test.js
@babel/preset-env: `DEBUG` option

Using targets:
{
  "chrome": "61",
  "edge": "15",
  "firefox": "52",
  "safari": "11"
}

Using modules transform: commonjs

Using plugins:
  transform-destructuring { "edge":"15", "firefox":"52" }
  transform-for-of { "firefox":"52" }
  transform-function-name { "edge":"15", "firefox":"52" }
  transform-literals { "firefox":"52" }
  transform-parameters { "firefox":"52" }
  transform-regenerator { "firefox":"52" }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
TypeError: test.js: Duplicate declaration "tmp" (This is an error on an internal node. Probably an internal error.)
    at File.buildCodeFrameError (/pwd/node_modules/@babel/core/lib/transformation/file/file.js:209:12)
    at Scope.checkBlockScopedCollisions (/pwd/node_modules/@babel/traverse/lib/scope/index.js:295:27)
    at Scope.registerBinding (/pwd/node_modules/@babel/traverse/lib/scope/index.js:477:16)
    at Scope.registerDeclaration (/pwd/node_modules/@babel/traverse/lib/scope/index.js:396:14)
    at Object.Declaration (/pwd/node_modules/@babel/traverse/lib/scope/index.js:89:12)
    at NodePath._call (/pwd/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/pwd/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/pwd/node_modules/@babel/traverse/lib/path/context.js:95:12)
    at TraversalContext.visitQueue (/pwd/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/pwd/node_modules/@babel/traverse/lib/context.js:93:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Context

It worked fine with `babel-preset-env` in version `1.5.2`. It is broken with `@babel/preset-env` in version `7.0.0-beta.32`.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.32 (@babel/core 7.0.0-beta.32)
| Babylon          | 
| node             | v9.2.0
| npm              | 5.5.1
| Operating System | Official node.js Docker container

**Comment by TimWolla** [comment]
Updated initial issue to remove incorrect remark about `transform-arrow-functions`, apparently I had some older version of my testcase in my mind.

**Comment by TimWolla** [comment]
@nicolo-ribaudo According to the commit (https://github.com/babel/babel/commit/4887d81929b7b598abf2e04b77c95586b5230b35) the patch is contained in the v7.0.0-beta.40 tag. I tried again with beta 40, but still encounter this issue:

```
[timwolla@/t/test [1]]cat package.json .babelrc                                                                                                                                                             20:16:57
{
  "dependencies": {
    "@babel/cli": "^7.0.0-beta.40",
    "@babel/core": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "regenerator-runtime": "^0.11.0"
  }
}
{ "presets": [ [ "@babel/env"
               , { "targets": { "browsers": [ "last 2 chrome versions"
                                            , "last 2 chromeandroid versions"
                                            , "firefox esr"
                                            , "last 2 firefox versions"
                                            , "edge >= 15"
                                            , "safari >= 11"
                                            ]
                              }
                 , "debug": true
                 }
               ]
             ]
}
[timwolla@/t/test]docker run -it --rm -v (pwd):(pwd) -v (pwd):/pwd --workdir /pwd -v /scratch/cache/yarn:/usr/local/share/.cache/yarn/v1 timwolla/node yarn install                                         20:17:01
yarn install v1.3.2
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 10.09s.
[timwolla@/t/test]cat test.js                                                                                                                                                                               20:17:16
async function foo() {
	(async function (number) {
		const tmp = number
	})
}
[timwolla@/t/test]docker run -it --rm -v (pwd):(pwd) -v (pwd):/pwd --workdir /pwd -v /scratch/cache/yarn:/usr/local/share/.cache/yarn/v1 timwolla/node yarn run babel test.js                               20:17:22
yarn run v1.3.2
warning package.json: No license field
$ /pwd/node_modules/.bin/babel test.js
@babel/preset-env: `DEBUG` option

Using targets:
{
  "chrome": "63",
  "edge": "15",
  "firefox": "52",
  "safari": "11"
}

Using modules transform: commonjs

Using plugins:
  transform-destructuring { "edge":"15", "firefox":"52" }
  transform-for-of { "firefox":"52" }
  transform-function-name { "edge":"15", "firefox":"52" }
  transform-literals { "firefox":"52" }
  transform-parameters { "firefox":"52" }
  transform-regenerator { "firefox":"52" }
  transform-dotall-regex { "edge":"15", "firefox":"52", "safari":"11" }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
TypeError: test.js: Duplicate declaration "tmp" (This is an error on an internal node. Probably an internal error.)
    at File.buildCodeFrameError (/pwd/node_modules/@babel/core/lib/transformation/file/file.js:207:12)
    at Scope.checkBlockScopedCollisions (/pwd/node_modules/@babel/traverse/lib/scope/index.js:303:27)
    at Scope.registerBinding (/pwd/node_modules/@babel/traverse/lib/scope/index.js:485:16)
    at Scope.registerDeclaration (/pwd/node_modules/@babel/traverse/lib/scope/index.js:404:14)
    at Object.Declaration (/pwd/node_modules/@babel/traverse/lib/scope/index.js:89:12)
    at NodePath._call (/pwd/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/pwd/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/pwd/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/pwd/node_modules/@babel/traverse/lib/context.js:135:18)
    at TraversalContext.visitMultiple (/pwd/node_modules/@babel/traverse/lib/context.js:89:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[timwolla@/t/test [1]]docker run -it --rm -v (pwd):(pwd) -v (pwd):/pwd --workdir /pwd timwolla/node node --version                                                                                          20:17:29
v9.5.0
[timwolla@/t/test]docker run -it --rm -v (pwd):(pwd) -v (pwd):/pwd --workdir /pwd timwolla/node npm --version                                                                                               20:17:49
5.6.0
```

Did I do something wrong?

**Comment by nicolo-ribaudo** [comment]
I will check later

**Comment by retyui** [comment]
@nicolo-ribaudo check please this error!

**Comment by deflock** [comment]
`firefox esr` in `browserslist` somehow affects parsing and causes this error.

ping @nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
Reduced test case:
```js
babel.transformSync(
  `
  async function foo() {
    (async function (number) {
      const tmp = number
    })
  }
`,
  {
    configFile: false,
    plugins: [load("plugin-transform-regenerator")],
  }
).code;
```

**Comment by trusktr** [comment]
I've got the same problem.

## Input code:

```js
import 'element-behaviors'
import Class from 'lowclass'
import {withUpdate} from '@trusktr/skatejs'
import native from 'lowclass/native'
import ForwardProps from './ForwardProps'
import Node from '../../core/Node'

/**
 * Base class for all behaviors
 *
 */
export default
Class( 'Behavior' ).extends( native( withUpdate( ForwardProps ) ), ({ Public, Protected, Private, Super }) => ({
    static: {
        // use a getter because Mesh is undefined at module evaluation time due
        // to a circular dependency.
        get requiredElementType() { return Node },
    },

    constructor(element) {
        let _this = Super(this).constructor()

        _this.element = element

        Private(this).__checkElementIsLibraryElement(element)

        return _this
    },

    // This could be useful, but at the moment we only need this because if it
    // returns falsey (i.e. undefined) then skatejs won't fire `updated` because
    // it returns early if !this.parentNode in triggerUpdate.
    get parentNode() {
        return this.element.parentNode
    },

    // proxy setAttribute to this.element so that SkateJS withUpdate works in certain cases
    setAttribute(name, value) {
        this.element.setAttribute(name, value)
    },

    refreshAllProps() {
        if (!this.constructor.props) return

        for (const prop in this.constructor.props) {
            this._modifiedProps[prop] = true
        }

        this.triggerUpdate()
    },

    connectedCallback() {
        Super( this ).connectedCallback()
        Protected(this)._listenToElement()
    },

    disconnectedCallback() {
        Super( this ).disconnectedCallback()
        Protected(this)._unlistenToElement()
    },

    protected: {
        // used by ForwardProps. See ForwardProps.js
        get _observedObject() {
            return Public( this ).element
        },

        _listenToElement() {
            // subclasses: add event listeners
        },

        _unlistenToElement() {
            // subclasses: remove event listeners
        },
    },

    private: {

        // TODO add a test to make sure this check works
        async __checkElementIsLibraryElement(element) {
            const pub = Public(this)
            const BaseClass = Public(this).constructor.requiredElementType

            if ( element.nodeName.includes('-') ) {
                const whenDefined = customElements.whenDefined(element.nodeName.toLowerCase())
                    .then(() => {
                        if (element instanceof BaseClass) return true
                        else return false
                    })

                const timeout = new Promise(r => setTimeout(r, 10000))

                const isNode = await Promise.race([whenDefined, timeout])

                if (!isNode) throw new Error(`
                    Either the element you're using the behavior on is not an
                    instance of ${BaseClass.name}, or there was a 10-second timeout
                    waiting for the element to be defined.
                `)
            }
            else {
                throw new Error(`
                    The element you're using the mesh behavior on is not an
                    instance of ${BaseClass.name}.
                `)
            }
        },

    },

}))
```

## babelrc:


```js
        {
            presets: [ ['@babel/preset-env', { targets: { node: 9 } }] ],
            plugins: [
                ['transform-builtin-classes', { globals: [ 'HTMLElement', 'Map' ] }],

                '@babel/plugin-proposal-export-namespace-from',
                '@babel/plugin-proposal-export-default-from',
                '@babel/plugin-transform-classes',
                '@babel/plugin-transform-object-super',
                '@babel/plugin-proposal-object-rest-spread',
                'babel-plugin-array-includes',

                ['@babel/plugin-transform-runtime', {
                    helpers: true,
                    polyfill: true,
                    regenerator: false,
                }],

                ['module:fast-async', {
                    compiler: {
                        promises: true,
                        noRuntime: true,
                    },
                }],
            ],
            sourceMap: 'inline',
        }
```

## Error:

```
Uncaught TypeError: /Users/joepea/src/trusktr+infamous/src/html/behaviors/Behavior.js: Duplicate declaration "whenDefined" (This is an error on an internal node. Probably an internal error.)
at /Users/joepea/src/trusktr+infamous/node_modules/@babel/traverse/lib/scope/index.js:343:7

undefined
```

**Comment by trusktr** [comment]
Updated previous comment with a reduced test case.

**Comment by trusktr** [comment]
Taking the above example, I can make the error go away in different ways. For example, if I change the code to one of the following, the error goes away:

```js
const Class = () => {}

Class( 'Behavior', {
    private: {

        async __checkElementIsLibraryElement(element) {
            if ( true ) {
                const timeout = 5
                const isNode = timeout // <-- took away the await keyword
            }
        },

    },

})
```

```js
const Class = () => {}

Class( 'Behavior', {
    private: {

        async __checkElementIsLibraryElement(element) {
            // removed the wrapping if(){} block
            const timeout = 5
            const isNode = await timeout
        },

    },

})
```

But if I change it to the following, then the a slightly different version of the error happens:

```js
const Class = () => {}

Class( 'Behavior', {
    private: {

        async __checkElementIsLibraryElement(element) {
            const timeout = 5
            if ( true ) {
                const isNode = await timeout
            }
        },

    },

})
```

Error:

```
```
Uncaught TypeError: /Users/joepea/src/trusktr+infamous/src/html/behaviors/Behavior.js: Duplicate declaration "isNode" (This is an error on an internal node. Probably an internal error.)
at /Users/joepea/src/trusktr+infamous/node_modules/@babel/traverse/lib/scope/index.js:343:7

undefined
```

Although there is clearly not more than one `isNode`.

**Comment by trusktr** [comment]
As a workaround, I can store stuff on `this.`:

```js
const Class = () => {}

Class( 'Behavior', {
    private: {

        async __checkElementIsLibraryElement(element) {
            if ( true ) {
                this.timeout = 5 // HERE, using `this.` to store variables.
                this.isNode = await this.timeout
            }
        },

    },

})
```
