### ISSUE TITLE
TypeError: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "ArrayPattern"

### ISSUE THREAD

**Issue by hoschi** [babel/babel#6926]
Choose one: bug

### Input Code

```js
import createSelector from 'reselect'
import {wikiCommentsEndpoint, wikiVersionsEndpoint}  from './endpoints'

export let [
    [createCommentDataByIdSelector, createCommentDataIsFetchingByIdSelector],
    [createVersionDataByIdSelector, createVersionDataIsFetchingByIdSelector],
] = [wikiCommentsEndpoint, wikiVersionsEndpoint].map(endpoint => {
    return [endpoint.globalToByIdDataStorageState, endpoint.globalToIsFetchingState].map(
        endpointStateSelector => {
            return () => {
                return createSelector(endpointStateSelector, (data) => !!data);
            };
        }
    );
});

```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
    "env": {
        "test": {
            "presets": [
                [
                    "env",
                    {
                        "targets": {
                            "node": "current"
                        }
                    }
                ]
            ],
        },
    }
}

```

### Expected Behavior
`NODE_ENV=test babel myFile.js` should work

### Current Behavior
`NODE_ENV=test babel myFile.js` gives error:
```
TypeError: src/features/wiki/wikiDataReducer.js: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "ArrayPattern"
    at validate (/home/hoschi/repos/gis/frontend/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/home/hoschi/repos/gis/frontend/node_modules/babel-types/lib/definitions/core.js:412:50)
    at Object.validate (/home/hoschi/repos/gis/frontend/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/home/hoschi/repos/gis/frontend/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/home/hoschi/repos/gis/frontend/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at NodePath.replaceInline (/home/hoschi/repos/gis/frontend/node_modules/babel-traverse/lib/path/replacement.js:266:17)
    at Array.enter (/home/hoschi/repos/gis/frontend/node_modules/babel-template/lib/index.js:134:12)
    at NodePath._call (/home/hoschi/repos/gis/frontend/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/hoschi/repos/gis/frontend/node_modules/babel-traverse/lib/path/context.js:44:14)
    at NodePath.visit (/home/hoschi/repos/gis/frontend/node_modules/babel-traverse/lib/path/context.js:105:12)

```

### Context
I want to switch from node version 6 to 8. With version 6 this works, but fails with version 8. My original source file and `.babelrc` is bigger, but I managed to cut the problem down to what you see above. When I replace `"current"` with `"6"` in `targets.node` it compiles to:
```js
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.createVersionDataIsFetchingByIdSelector = exports.createVersionDataByIdSelector = exports.createCommentDataIsFetchingByIdSelector = exports.createCommentDataByIdSelector = undefined;

var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }();

var _reselect = require('reselect');

var _reselect2 = _interopRequireDefault(_reselect);

var _endpoints = require('./endpoints');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var _map = [_endpoints.wikiCommentsEndpoint, _endpoints.wikiVersionsEndpoint].map(endpoint => {
    return [endpoint.globalToByIdDataStorageState, endpoint.globalToIsFetchingState].map(endpointStateSelector => {
        return () => {
            return (0, _reselect2.default)(endpointStateSelector, data => !!data);
        };
    });
}),
    _map2 = _slicedToArray(_map, 2),
    _map2$ = _slicedToArray(_map2[0], 2);

let createCommentDataByIdSelector = _map2$[0],
    createCommentDataIsFetchingByIdSelector = _map2$[1];

var _map2$2 = _slicedToArray(_map2[1], 2);

let createVersionDataByIdSelector = _map2$2[0],
    createVersionDataIsFetchingByIdSelector = _map2$2[1];
exports.createCommentDataByIdSelector = createCommentDataByIdSelector;
exports.createCommentDataIsFetchingByIdSelector = createCommentDataIsFetchingByIdSelector;
exports.createVersionDataByIdSelector = createVersionDataByIdSelector;
exports.createVersionDataIsFetchingByIdSelector = createVersionDataIsFetchingByIdSelector;

```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 6.18.0 
| babel-preset-env| 1.6.1
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | linux (Arch)

**Comment by nicolo-ribaudo** [comment]
Thank you for the bug report, this works using Babel 7.0.0-beta.32  and preset-env 7.0.0-beta.32
