### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'spec' of undefined 

### ISSUE THREAD

**Issue by changfuguo** [babel/babel#6988]
Choose one: is this a bug report or feature request?

bug report

```
ERROR in ./src/modules/todos/index.js
Module build failed: TypeError: Cannot read property 'spec' of undefined (While processing preset: "/Users/didi/Code/orion_m/risk_manage/node_modules/@babel/preset-env/lib/index.js")
    at _default (/Users/didi/Code/orion_m/risk_manage/node_modules/@babel/plugin-transform-arrow-functions/lib/index.js:7:21)
    at Function.memoisePluginContainer (/Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/didi/Code/orion_m/risk_manage/node_modules/babel-core/lib/transformation/file/index.js:135:24)
 @ multi ./src/modules/todos/index.js webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&reload=true
```
### Input Code

my babelrc config is below:
```js


```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  	"presets": [
	    ["@babel/preset-env", {
	      	"targets": {
	        	"browsers": ["last 2 versions", "safari >= 7"]
	      	},
	      	"modules": false,
     		"loose": true
	    }]
  	]
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 
| node             | 6.4
| npm              | 3.10.3
| Operating System |  macOs

**Comment by nicolo-ribaudo** [comment]
Hi, the problem is that you are using `@babel/preset-env` (which is version 7) with Babel 6. The two versions are not compatible. I'd suggest using `babel-preset-env` (which is version 6) instead.
