### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by julien-f** [babel/babel#7026]
Choose one:

- [x] bug
- [ ] feature

[Repro repository](https://github.com/julien-f/babel-issue).

### Input Code

```js
//
export default async function f () {}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```json
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "node": "6"
        }
      }
    ]
  ]
}
```

### Expected Behavior

It should compile the code.

### Current Behavior

```
TypeError: Cannot read property 'some' of null
    at isPureAnnotated (<dir>/node_modules/@babel/helper-annotate-as-pure/lib/index.js:19:26)
    at annotateAsPure (<dir>/node_modules/@babel/helper-annotate-as-pure/lib/index.js:27:7)
    at _default (<dir>/node_modules/@babel/helper-remap-async-to-generator/lib/index.js:74:39)
    at PluginPass.Function (<dir>/node_modules/@babel/plugin-transform-async-to-generator/lib/index.js:43:50)
    at newFn (<dir>/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (<dir>/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (<dir>/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (<dir>/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (<dir>/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (<dir>/node_modules/@babel/traverse/lib/context.js:98:19)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.34
| Babylon          | 
| node             | 9.3.0
| npm              | 5.5.1
| Operating System | Fedora 27

**Comment by existentialism** [comment]
Looks like we need to change https://github.com/babel/babel/blob/master/packages/babel-helper-annotate-as-pure/src/index.js#L7 to check for null or prevent `node.leadingComments` from being null.

**Comment by julien-f** [comment]
Yep.

I could not reproduce without:
- the comment
- the export
- the function
- the function's name
