### ISSUE TITLE
Incorrect transforms of function custom field assignment in babel 7

### ISSUE THREAD

**Issue by Amareis** [babel/babel#7030]
When you made multiple assignment to function fields, only first transforms to direct assigment. Others are broken.

### Input Code

First example:
```js
function generateAsyncAction(type) {
    type = type.toUpperCase()
    const request = createAction(type+'_REQUEST',
        undefined, requestMetaCreator
    )
    request.request = request // crazy
    request.success = createAction(type+'_SUCCESS', undefined, metaCreator)
    request.error = createAction(type+'_ERROR', undefined, metaCreator)
    request.cancel = createAction(type+'_CANCEL', undefined, metaCreator)
    request.progress = createAction(type+'_PROGRESS', undefined, metaCreator)
    request.process = createAction(type+'_PROCESS', undefined, metaCreator)

    return request
}
```
Second example:
```js
constructor(timestamp) {
    super()
    this.timestamp = timestamp
    this.moment = moment(timestamp)
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["@babel/preset-es2015", "@babel/preset-stage-0", "@babel/preset-react"],
    "plugins": [
        "react-hot-loader/babel",
        ["@babel/transform-runtime", { "polyfill": false }]
    ],
    "env": {
        "test": {
            "retainLines": true
        }
    }
}
```
### Current Behavior

First example:
```js
function generateAsyncAction(type) {
  type = type.toUpperCase();
  var request = (0, _reduxActions.createAction)(type + '_REQUEST', undefined, requestMetaCreator); // if (debug) {
  //     const orig_request = request
  //     request = function() {
  //         debugger
  //         return orig_request(...arguments)
  //     }
  // }

  request.request = request; // crazy

  (0, _initializerDefineProperty2.default)(request, "success", type + '_SUCCESS', undefined);
  (0, _initializerDefineProperty2.default)(request, "error", type + '_ERROR', undefined);
  (0, _initializerDefineProperty2.default)(request, "cancel", type + '_CANCEL', undefined);
  (0, _initializerDefineProperty2.default)(request, "progress", type + '_PROGRESS', undefined);
  (0, _initializerDefineProperty2.default)(request, "process", type + '_PROCESS', undefined);
  return request;
}
```
Note that `_initializerDefineProperty2` strings. First string is transformed right and others are wrong. Why? I dunno, lol.

Second example just don't builds with error which listed below. If you removes `this.moment = moment(timestamp)` or change it to `this['moment'] = moment(timestamp)`, all will works. 
```
Module build failed: TypeError: Cannot read property 'node' of undefined
    at PluginPass.AssignmentExpression (/some_dir/node_modules/@babel/plugin-proposal-decorators/lib/index.js:139:261)
    at newFn (/some_dir/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (/some_dir/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/some_dir/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/some_dir/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/some_dir/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/some_dir/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/some_dir/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/some_dir/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/some_dir/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/some_dir/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/some_dir/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/some_dir/node_modules/@babel/traverse/lib/context.js:178:19)
    at Function.traverse.node (/some_dir/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/some_dir/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/some_dir/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/some_dir/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/some_dir/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/some_dir/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/some_dir/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/some_dir/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/some_dir/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/some_dir/node_modules/@babel/traverse/lib/context.js:178:19)
```
### Possible Solution

As workaround, you can just don't use dot notation. Next example will works as expected:
```js
    request['request'] = request // crazy
    request['success'] = createAction(type+'_SUCCESS', undefined, metaCreator)
    request['error'] = createAction(type+'_ERROR', undefined, metaCreator)
    request['cancel'] = createAction(type+'_CANCEL', undefined, metaCreator)
    request['progress'] = createAction(type+'_PROGRESS', undefined, metaCreator)
    request['process'] = createAction(type+'_PROCESS', undefined, metaCreator)
```
### Your Environment

```js
    "@babel/core": "7.0.0-beta.35",
    "@babel/plugin-transform-runtime": "7.0.0-beta.35",
    "@babel/polyfill": "7.0.0-beta.35",
    "@babel/preset-es2015": "7.0.0-beta.35",
    "@babel/preset-react": "7.0.0-beta.35",
    "@babel/preset-stage-0": "7.0.0-beta.35",
    "@babel/register": "7.0.0-beta.35",
    "@babel/runtime": "7.0.0-beta.35",
```

**Comment by Amareis** [comment]
It's really annoing issue, which brokes tons of code along repo.

**Comment by Amareis** [comment]
As i notice, it's broken only when on right side of assignment there is function call. When assigns just another variable, all is ok.

**Comment by Amareis** [comment]
Oh, thanks you for rapid fix. When it's come to release?

**Comment by joshunger** [comment]
@hzoo @nicolo-ribaudo how do you look up when this will be released?  Thanks.

**Comment by existentialism** [comment]
@joshunger as soon as possible! you can always downgrade to beta 34 for now?

**Comment by joshunger** [comment]
@existentialism That worked out perfect thank you.

**Comment by a-x-** [comment]
I have the same issue on beta 31 and beta 35

**Comment by a-x-** [comment]
<details><summary>Config</summary>

```json5
{
      presets: [
        ['@babel/env', {
          targets: {
            browsers: browsers.production,
          },
          modules: false, // keep es6 exports
          useBuiltIns: false, // Disable polyfill transforms
        }],
        '@babel/react',
        '@babel/stage-1'
      ],
      'plugins': [
        '@babel/syntax-dynamic-import', // import()
        '@babel/plugin-transform-shorthand-properties', // uglify fails
        '@babel/transform-destructuring', // coffeescript2 compiles incorrect es6 ({foo} = bar)
        '@babel/proposal-optional-chaining',
      ],
}
```

</details>

**Comment by a-x-** [comment]
_initializerDefineProperty brokes everything.
how to remove it? :)

code:
```es6
    this.askDadataThrottled = window.askDadataThrottled = throttle(this.askDadata, 200)
    console.log 'wtf', this.askDadataThrottled, 'th', throttle(this.askDadata, 200), 'this', this, 'w', window.askDadataThrottled
```

<details><summary>result:</summary>

```js
/* harmony default export */ __webpack_exports__[\"a\"] = (AddressInput = function () {
  let AddressInput = class AddressInput extends __WEBPACK_IMPORTED_MODULE_0_react___default.a.Component {
    constructor() {
      super(...arguments);
      this.handleSuggestionsUpdateRequested = this.handleSuggestionsUpdateRequested.bind(this);
      this.handleSuggestionSelected = this.handleSuggestionSelected.bind(this);
      this.handleChange = this.handleChange.bind(this);
      this.askDadata = this.askDadata.bind(this);
    }

    componentDidMount() {
      this.setState({
        query: this.props.defaultValue,
        kladr_id: !!this.props.kladr_id
      });
      this.askDadataThrottled = _initializerDefineProperty(window, \"askDadataThrottled\", this.askDadata, 200);
      return console.log(
'wtf', this.askDadataThrottled, /// THIS IS undefined
'th', __WEBPACK_IMPORTED_MODULE_3_lodash_throttle___default()(this.askDadata, 200), /// THIS IS OK
'this', this,
'w', window.askDadataThrottled); /// THIS IS undefined
//    ...
```

</details>

**Comment by joshunger** [comment]
@a-x- did 34 not work for you?

**Comment by a-x-** [comment]
yeah, 34 is ok

**Comment by a-x-** [comment]
let's reopen issue

**Comment by nicolo-ribaudo** [comment]
The issue has been fixed, but we haven't yet released a new version (and probably won't happened soon, because of Christmas).
