### ISSUE TITLE
Regression babel-template with uppercase variables not meant to be replaced

### ISSUE THREAD

**Issue by danez** [babel/babel#7035]
Choose one: is this a bug report or feature request?

bug

### Input Code

```js
const unsafeWrapTemplate = template(`
  if (process.env.NODE_ENV !== "production") {
    NODE;
  }
`);

unsafeWrapTemplate({
  NODE: path.node,
}),
```

### Expected Behavior
returns the template with NODE replaced

### Current Behavior

```
Error: No substitution given for "NODE_ENV"
    at /Users/danieltschinder/Documents/Github/react-fast-highlight/node_modules/@babel/template/lib/populate.js:16:15
    at Array.forEach (<anonymous>)
    at populatePlaceholders (/Users/danieltschinder/Documents/Github/react-fast-highlight/node_modules/@babel/template/lib/populate.js:14:27)
    at /Users/danieltschinder/Documents/Github/react-fast-highlight/node_modules/@babel/template/lib/string.js:20:51
    at /Users/danieltschinder/Documents/Github/react-fast-highlight/node_modules/@babel/template/lib/builder.js:83:14
    at remove (/Users/danieltschinder/Documents/Github/react-fast-highlight/node_modules/babel-plugin-transform-react-remove-prop-types/lib/remove.js:88:28)
```
### Context
Found in `babel-plugin-remove-prop-types`

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  beta 35
| node             | 8.9.3
| npm              |  5.5
| Operating System | mac

**Comment by loganfsmyth** [comment]
Good catch, I'll put together a PR now.

**Comment by loganfsmyth** [comment]
Oh hmmm, so we actually use replacements for things like this in a few places, so we're going to get a breaking change either way. For example https://github.com/babel/babel/blob/ed4d90b33db8ec7c31cb905bffa6780d4810accb/packages/babel-plugin-transform-computed-properties/src/index.js#L11 and new in Babel 7 https://github.com/babel/babel/blob/ed4d90b33db8ec7c31cb905bffa6780d4810accb/packages/babel-helper-module-transforms/src/index.js#L165 (and a few others in that file).

The alternative is that we leave things as-is and users that hit this case would have to do
```
const unsafeWrapTemplate = template(`
  if (process.env.NODE_ENV !== "production") {
    NODE;
  }
`, { placeholderWhitelist: new Set(['NODE']) });
```
or

```
const unsafeWrapTemplate = template(`
  if (process.env.NODE_ENV !== "production") {
    NODE;
  }
`, { placeholderPattern: /^NODE$/ });
```
so that `NODE_ENV` isn't treated as a placeholder identifier.

Thoughts?

**Comment by oliviertassinari** [comment]
I like the `placeholderWhitelist` option 👍

**Comment by loganfsmyth** [comment]
@oliviertassinari Cool! Those options were added in the PR that changed the behavior in v7, so you should be able to start using them. https://github.com/babel/babel/blob/master/packages/babel-template/README.md#options

**Comment by danez** [comment]
@loganfsmyth I just tried placeholderWhitelist but it is not an exclusive whitelist, babel-template still searches for patterns and in the example above picks up NODE_MODULES. So the only way is to use `placeholderPattern`.

I hope though that using a pattern of `^NODE$` does not replace it in `NODE_MODULES`

**Comment by hzoo** [comment]
> Error: No substitution given for "NODE_ENV"

We should at least modify this error message to say you can use those options for ^ if it's intentional?

**Comment by loganfsmyth** [comment]
Oh weird, I swear I wrote up a reply to this way back, but I guess not?

> I just tried placeholderWhitelist but it is not an exclusive whitelist, babel-template still searches for patterns and in the example above still picks up NODE_MODULES too. So the only way is to use placeholderPattern.

@danez You're totally right. So you'd either want

    { placeholderPattern: false, placeholderWhitelist: new Set(['NODE'])  }

or

    { placeholderPattern: /^NODE$/ }

@hzoo Agreed. That would be a great addition.

I'm marking this as good beginner contribution. We can update that error message to throw something like

```
Error: No substitution given for "NODE_ENV". If this is not meant to be a placeholder, you may want to consider passing one of the following possibly options to babel-template:
  - `{ placeholderPattern: false, placeholderWhitelist: new Set(['NODE']) }`
  - `{ placeholderPattern: /^NODE$/ }`
```

Since we have the names, we could generate all of the correct lists based on the placeholders that actually had replacements passed in.

**Comment by hzoo** [comment]
Error message is at https://github.com/babel/babel/blob/c7980b2b90744098ed5d67a105f8f6e7270e7cbe/packages/babel-template/src/populate.js#L18
