### ISSUE TITLE
TypeError: Cannot read property 'node' of undefined | babel 7

### ISSUE THREAD

**Issue by seeden** [babel/babel#7041]
I am not able to compile my source code. The problem is in the @babel/plugin-proposal-decorators. 
 I can see
```
TypeError: Cannot read property 'node' of undefined
    at PluginPass.AssignmentExpression (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/plugin-proposal-decorators/lib/index.js:145:39)
```

It is working if I added into the @babel/plugin-proposal-decorators/lib/index.js line 138
```js
if(!path.get("right.arguments")[1]) {
  return;
}
```

Here is the full stackstrace

```
Module build failed: TypeError: Cannot read property 'node' of undefined
    at PluginPass.AssignmentExpression (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/plugin-proposal-decorators/lib/index.js:145:39)
    at newFn (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:178:19)
    at Function.traverse.node (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:178:19)
    at Function.traverse.node (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/seeden/Documents/git/quizana.com/node_modules/@babel/traverse/lib/path/context.js:106:18)
 @ ./src/index.js 19:46-74
```

My versions
```
    "babel-core": "7.0.0-bridge.0",
    "@babel/core": "^7.0.0-beta.35",
    "@babel/plugin-transform-proto-to-assign": "^7.0.0-beta.35",
    "@babel/plugin-transform-flow-strip-types": "^7.0.0-beta.35",
    "@babel/preset-env": "^7.0.0-beta.35",
    "@babel/preset-react": "^7.0.0-beta.35",
    "@babel/preset-stage-0": "^7.0.0-beta.35",
    "@babel/polyfill": "^7.0.0-beta.35",
    "@babel/register": "^7.0.0-beta.35",
    "babel-loader": "8.0.0-beta.0",
```

**Comment by nicolo-ribaudo** [comment]
Already fixed! :smile:
https://github.com/babel/babel/pull/7032

It will be included in the next release

**Comment by seeden** [comment]
Thanks @nicolo-ribaudo. It was fast 👍

**Comment by nicolo-ribaudo** [comment]
In the meantime, I suggest downgrading to the previous beta version.

**Comment by damianobarbati** [comment]
@nicolo-ribaudo what should I downgrade to skip this for now? 
`"@babel/plugin-proposal-decorators": "^7.0.0-beta.34"`? 
Because I tried with no success, still I have:
```
        ERROR in ./node_modules/lodash/lodash.js
        Module build failed: TypeError: Cannot read property 'node' of undefined
            at PluginPass.AssignmentExpression (/Users/damz/Desktop/react-app/node_modules/@babel/plugin-proposal-decorators/lib/index.js:139:261)
```

Thanks guys for your work!

**Comment by hzoo** [comment]
Released [beta.36](https://github.com/babel/babel/releases/tag/v7.0.0-beta.36) with the fix
