### ISSUE TITLE
Compilation issues with decorators plugin

### ISSUE THREAD

**Issue by julien-f** [babel/babel#7045]
Choose one:

- [x] bug
- [ ] feature

[Repro repository](https://github.com/julien-f/babel-decorators-issue).

### Input Code

```js
global.foo = f()
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```json
{
  "plugins": [
    "@babel/plugin-proposal-decorators"
  ]
}
```

### Expected Behavior

It should compile the code.

### Current Behavior

```
TypeError: Cannot read property 'node' of undefined
    at PluginPass.AssignmentExpression (<dir>/node_modules/@babel/plugin-proposal-decorators/lib/index.js:139:224)
    at newFn (<dir>/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (<dir>/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (<dir>/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (<dir>/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (<dir>/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (<dir>/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (<dir>/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (<dir>/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (<dir>/node_modules/@babel/traverse/lib/path/context.js:106:18)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.35
| Babylon          | 
| node             | 9.3.0
| npm              | 5.5.1
| Operating System | Fedora 27

**Comment by simonjoom** [comment]
this bug was resolved from last code see-> https://github.com/babel/babel/commit/9a146d01b05689d264787c6b694d5515a2fed68d , take manually the source code of plugin-proposal-decorators from this repo and compile it or wait the new release 7.0.0-beta.36

**Comment by julien-f** [comment]
Thank you 😄 

Feel free to close this report if you feel it's not longer relevant.

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/babel/pull/7032

While waiting for the next release, you can downgrade to beta 34

**Comment by hzoo** [comment]
Released [beta.36](https://github.com/babel/babel/releases/tag/v7.0.0-beta.36) with the fix, Merry Christmas y'all!
