### ISSUE TITLE
How to install babel v7?

### ISSUE THREAD

**Issue by hekod777** [babel/babel#7050]
I am trying to use babel-preset-env but getting this error:

```
Module build failed: TypeError: Cannot read property 'loose' of undefined
```

It seems that the answer is to use babel v7.

How am I supposed to install babel v7?

with the following dependencies I am still having thise 'loose' of undefined error

```
    "@babel/core": "^7.0.0-beta.35",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.35",
    "@babel/preset-env": "^7.0.0-beta.35",
    "babel-cli": "^6.26.0",
```

**Comment by hekod777** [comment]
```bash
npm install --save-dev @babel/cli
```

is the trick.

**Comment by qiuyaofan** [comment]
IModule build failed: TypeError: Cannot read property 'loose' of undefined (While processing preset: "/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_@babel_preset-env@7.0.0-beta.37@@babel/preset-env/lib/index.js")
    at _default (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_@babel_plugin-transform-modules-commonjs@7.0.0-beta.37@@babel/plugin-transform-modules-commonjs/lib/index.js:21:23)
    at Function.memoisePluginContainer (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/qiuyaofan/Documents/new-project/manager-project/node_modules/_babel-core@6.26.0@babel-core/lib/transformation/file/index.js:135:24)
I meet the same issue , how to fixed it ,can you help @hekod777

**Comment by TrySound** [comment]
@qiuyaofan Try to remove all babel 6 modules.

**Comment by qiuyaofan** [comment]
`"@babel/core": "^7.0.0-beta.37",
    "@babel/cli": "^7.0.0-beta.37",
    "@babel/preset-env": "^7.0.0-beta.37",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.37",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.4.1",
    "babel-plugin-istanbul": "^3.1.2",
    "babel-plugin-transform-es2015-destructuring": "^6.23.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-babili": "^0.1.4",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-node6": "^11.0.0",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",`

like remove the module beloaw babel-cli module ?

**Comment by qiuyaofan** [comment]
`
"@babel/core": "^7.0.0-beta.37",
    "@babel/cli": "^7.0.0-beta.37",
    "@babel/preset-env": "^7.0.0-beta.37",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.37",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.4.1",
    "babel-plugin-istanbul": "^3.1.2",
    "babel-plugin-transform-es2015-destructuring": "^6.23.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-babili": "^0.1.4",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-node6": "^11.0.0",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
`
like remove the module beloaw babel-cli module ? @TrySound

**Comment by TrySound** [comment]
@qiuyaofan Remove all babel-* packages with 6 version. es20* presets are deprecated in favor of `@babel/preset-env`. babili is called now [minify](https://github.com/babel/minify)

**Comment by qiuyaofan** [comment]
it is ok !! Thank you so much

**Comment by qiuyaofan** [comment]
It is ok .error because I use 
const config={
test,
aaa
};
async can Uglify successfully @TrySound
