### ISSUE TITLE
Typescript `import =` is not supported.

### ISSUE THREAD

**Issue by rosskevin** [babel/babel#7062]
Choose one: is this a bug report or feature request?
Bug (or feature - because typescript support is new)

### Input Code
```js
import debounce = require('lodash/debounce')
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "@babel/preset-typescript",
    "@babel/preset-env",
    "@babel/preset-stage-1",
    "@babel/preset-react"
  ]
} 
```

### Expected Behavior
From https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

> When importing a module using export =, TypeScript-specific import module = require("module") must be used to import the module.

### Current Behavior
```js
SyntaxError: src/transitions/Slide.tsx: `import =` is not supported.

    at File.buildCodeFrameError (/Users/kross/projects/material-ui/node_modules/@babel/core/lib/transformation/file/file.js:209:12)
    at NodePath.buildCodeFrameError (/Users/kross/projects/material-ui/node_modules/@babel/traverse/lib/path/index.js:155:26)
    at PluginPass.TSImportEqualsDeclaration (/Users/kross/projects/material-ui/node_modules/@babel/plugin-transform-typescript/lib/index.js:208:20)
    at newFn (/Users/kross/projects/material-ui/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (/Users/kross/projects/material-ui/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/Users/kross/projects/material-ui/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/Users/kross/projects/material-ui/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/Users/kross/projects/material-ui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/Users/kross/projects/material-ui/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/Users/kross/projects/material-ui/node_modules/@babel/traverse/lib/context.js:178:19)
```

### Possible Solution
One idea would be that since this is a typescript only concept, and babel handles the other syntax well, just convert
```js
import debounce = require('lodash/debounce')
```
to
```js
import debounce from 'lodash/debounce'
```

### Context
Cannot use babel 7 directly without `tsc` preprocessing.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  @babel/core@7.0.0-beta.35
| node             | 9.3.0
| Operating System | OSX

**Comment by hzoo** [comment]
This is already documented as a caveat which is why the error message ``import =` is not supported`

https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-typescript/README.md#babelplugin-transform-typescript

The TS team made the original PR, unless we think it's worth adding this behavior still, someone would need to make a case/PR

**Comment by andy-ms** [comment]
Like you suggested, when using babel it's better to use a default import. This is supported in TypeScript by using the [`--allowSyntheticDefaultImports`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) flag.
(Created Microsoft/TypeScript-Handbook#700)

**Comment by rosskevin** [comment]
Thanks, I used `--allowSyntheticDefaultImports` a bit reluctantly, it has been useful in finding errors but understand that it may be painful to implement here.

**Comment by loganfsmyth** [comment]
Should we expand that error message with a bit more info so users know what to do next?

**Comment by rosskevin** [comment]
I think expanding the message with @andy-ms's link would be a good idea.

**Comment by hzoo** [comment]
Yes, definetely

**Comment by loganfsmyth** [comment]
Filed: https://github.com/babel/babel/issues/7067
