### ISSUE TITLE
Exporting TypeScript enum throws error: "We don't know what to do with this node type."

### ISSUE THREAD

**Issue by phyllisstein** [babel/babel#7122]
### Choose one: is this a bug report or feature request?
Bug report.

### Summary
Starting in v7.0.0-beta.36, exporting a TypeScript enum causes Babel to throw an error during transpilation: "We don't know what to do with this node type. We were previously a Statement but we can't fit in here?"

### Input Code
```ts
export enum A {
  RECEIVE_POSTS = 'RECEIVE_POSTS',
  REQUEST_POST = 'REQUEST_POST',
  REQUEST_POSTS = 'REQUEST_POSTS',
  REQUEST_POSTS_FAILED = 'REQUEST_POSTS_FAILED',
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  presets: [
    ['@babel/env', {
      exclude: [
        'transform-async-to-generator',
        'transform-regenerator',
      ],
      targets: {
        browsers: ['last 2 versions'],
      },
      modules: false,
      loose: true,
      useBuiltIns: 'usage',
    }],
    '@babel/react',
    '@babel/typescript',
    ['@babel/stage-0', {
      loose: true,
    }],
  ],
  plugins: [
    'autobind-class-methods',
    ['module:fast-async', {
      compiler: {
        lazyThenables: true,
        parser: {
          sourceType: 'module',
        },
        promises: true,
        wrapAwait: true,
      },
      useRuntimeModule: false,
    }],
    'graphql-tag',
    'lodash',
    ['styled-components', {
      displayName: true,
      ssr: true,
    }],
    'transform-promise-to-bluebird',
    ['@babel/transform-regenerator', {
      async: false,
      asyncGenerators: true,
      generators: true,
    }],
    '@babel/transform-runtime',
  ],
}
```

### Expected Behavior
Babel should transpile the exported enum.

### Current Behavior
Starting in v7.0.0-beta.36, Babel throws the following error:

```
Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
        at NodePath.insertAfter (/Users/daniel/Repos/Ignota/ordo-frontend/node_modules/@babel/traverse/lib/path/modification.js:126:11)
        at transpileEnum (/Users/daniel/Repos/Ignota/ordo-frontend/node_modules/@babel/plugin-transform-typescript/lib/enum.js:26:14)
        at PluginPass.TSEnumDeclaration (/Users/daniel/Repos/Ignota/ordo-frontend/node_modules/@babel/plugin-transform-typescript/lib/index.js:205:27)
        at newFn (/Users/daniel/Repos/Ignota/ordo-frontend/node_modules/@babel/traverse/lib/visitors.js:223:21)
        at NodePath._call (/Users/daniel/Repos/Ignota/ordo-frontend/node_modules/@babel/traverse/lib/path/context.js:64:19)
        at NodePath.call (/Users/daniel/Repos/Ignota/ordo-frontend/node_modules/@babel/traverse/lib/path/context.js:38:17)
        at NodePath.visit (/Users/daniel/Repos/Ignota/ordo-frontend/node_modules/@babel/traverse/lib/path/context.js:99:12)
        at TraversalContext.visitQueue (/Users/daniel/Repos/Ignota/ordo-frontend/node_modules/@babel/traverse/lib/context.js:139:18)
        at TraversalContext.visitSingle (/Users/daniel/Repos/Ignota/ordo-frontend/node_modules/@babel/traverse/lib/context.js:98:19)
        at TraversalContext.visit (/Users/daniel/Repos/Ignota/ordo-frontend/node_modules/@babel/traverse/lib/context.js:180:19)
```

### Possible Solution
`¯\_(ツ)_/¯`

### Context
I've been using TS enums as Redux action types, and usually export them in the style above.

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  v7.0.0-beta.36
| node             | v9.3.0
| npm              | v5.6.0
| Operating System | macOS 10.13.3 (17D25b)

**Comment by Kovensky** [comment]
Is this maybe fixed by https://github.com/babel/babel/pull/7116? 🤔

**Comment by nicolo-ribaudo** [comment]
I don't think it is, since that PR is only about default exported expressions.

The problem is that transform-typescript conflicts with some other plugin, since it works with only preset-env enabled: https://babeljs.io/repl/build/master#?babili=false&browsers=last%202%20versions&build=&builtIns=false&code_lz=KYDwDg9gTgLgBMAdgVwLZwIJwN4Cg5wBKAogMLECSAasQPoAKA8gMoAqzcAvHAOQnnU6TNsx4AafEWIBFAKrE2DFqy68SchayVtxk9fMXD2qvjINajoiQX2bt7WgDEMFADLEAIiduHlzJy7uHroAvkA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=typescript%2Cenv&prettier=false&targets=&version=7.0.0-beta.36
@phyllisstein Can you try to disable one plugin at time and see which causes the problem?

**Comment by phyllisstein** [comment]
🤕 🌴 Sorry for the bogus issue, it turns out `babel-loader` had installed its own version of Babel that was stuck on beta 35. Purging the ole `node_modules` and truing my monorepo's versions up did the trick. Thanks for jumping in so quickly, and forgive the noise.
