### ISSUE TITLE
Nested async functions transpiled to regenerator broken since v7.0.0-beta.35

### ISSUE THREAD

**Issue by bsuh** [babel/babel#7134]
It started happening after https://github.com/babel/babel/pull/6984

From a cursory glance, my hunch is the pull request didn't introduce this bug but uncovered a bug with transform-regenerator.

I have created a minimal repro https://github.com/bsuh/babel-broken-async

index.js
```
async function hello() {
	async function hello2() {
		return true;
	}
	return hello2();
}

async function main() {
	try {
		await hello();
		console.log('success');
	} catch (e) {
		console.log(e);
	}
}

main();
```

console output
```
~/babel-broken-async % node index.js
success
~/babel-broken-async % npx babel-node index.js
RangeError: Maximum call stack size exceeded
    at _hello2 (/Users/bsuh/babel-broken-async/index.js:1:1)
    at _hello2 (/Users/bsuh/babel-broken-async/index.js:34:30)
    at _hello2 (/Users/bsuh/babel-broken-async/index.js:34:30)
    at _hello2 (/Users/bsuh/babel-broken-async/index.js:34:30)
    at _hello2 (/Users/bsuh/babel-broken-async/index.js:34:30)
    at _hello2 (/Users/bsuh/babel-broken-async/index.js:34:30)
    at _hello2 (/Users/bsuh/babel-broken-async/index.js:34:30)
    at _hello2 (/Users/bsuh/babel-broken-async/index.js:34:30)
    at _hello2 (/Users/bsuh/babel-broken-async/index.js:34:30)
    at _hello2 (/Users/bsuh/babel-broken-async/index.js:34:30)
```

**Comment by bsuh** [comment]
Confirmed to be an issue in regenerator-transform. Will close this.

Issue
https://github.com/facebook/regenerator/issues/225

Pull request
https://github.com/facebook/regenerator/pull/335
