### ISSUE TITLE
Babel 7 + jest - ReferenceError: Unknown helper assertThisInitialized

### ISSUE THREAD

**Issue by darkowic** [babel/babel#7195]
Choose one: is this a bug report or feature request?

A bug

### Input Code

I run  my test and receive following error:
```js
 FAIL  src/tests/app.test.js
  ● Test suite failed to run

    ReferenceError: Unknown helper assertThisInitialized
      
      at loadHelper (node_modules/babel-7-jest/node_modules/@babel/helpers/lib/index.js:239:40)
      at ThisExpression (node_modules/@babel/plugin-transform-classes/lib/vanilla.js:51:60)
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

Babel config:
```js
  "babel": {
    "plugins": [
      "@babel/plugin-syntax-dynamic-import",
      "@babel/plugin-proposal-class-properties"
    ],
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "browsers": [
              "> 2% in DE",
              "safari>=9",
              "ie>=11"
            ]
          },
          "useBuiltIns": "usage",
          "modules": false
        }
      ],
      "@babel/preset-stage-0",
      "@babel/preset-react"
    ],
    "env": {
      "production": {
        "only": [
          "src"
        ],
        "plugins": [
          "babel-plugin-transform-react-remove-prop-types",
          "@babel/plugin-transform-react-constant-elements",
          "@babel/plugin-transform-react-inline-elements"
        ]
      },
      "test": {
        "plugins": [
          "@babel/plugin-transform-modules-commonjs",
          "babel-plugin-dynamic-import-node-babel-7",
          "@babel/syntax-export-extensions"
        ]
      }
    }
  },
```

### Possible Solution

Am I missing some plugin?

### Context

I'm trying to configure jest for babel-7. I use https://github.com/Sneezoo/babel-7-jest library.

Jest config:
```
  "jest": {
    "transform": {
      ".jsx?$": "babel-7-jest"
    },
    "collectCoverageFrom": [
      "app/**/*.{js,jsx}",
      "!app/**/*.test.{js,jsx}"
    ],
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "coverageDirectory": "./reports",
    "coverageReporters": [
      "text-summary"
    ],
    "moduleNameMapper": {
      ".*\\.(css|less|styl|scss|sass)$": "<rootDir>/internals/mocks/cssModule.js",
      ".*\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/internals/mocks/image.js",
      "imports-loader?.*": "<rootDir>/internals/mocks/importsLoader.js"
    },
    "testRegex": "tests/.*\\.test\\.jsx?$",
    "setupFiles": [
      "<rootDir>/internals/testing/setup.js"
    ],
    "testPathIgnorePatterns": [
      "node_modules.*",
      "/containers/"
    ]
  },
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.37
| node             | v6.10.3
| npm              | 5.6.0
| Operating System | Xubuntu 

Related issue https://github.com/Sneezoo/babel-7-jest/issues/2
@Sneezoo

**Comment by darkowic** [comment]
Problem is that Jest itself has old babel dependencies. Do you think it may
couse the problem?

10.01.2018 17:56 "Mateusz Burzyński" <notifications@github.com> napisał(a):

**Comment by Andarist** [comment]
Possibly, not sure though. From what I know the newest release of jest (v22?) should support babel@7, you'd need to install `babel-core@7.0.0-bridge.0` though to make it work.

**Comment by darkowic** [comment]
I have one plugin with version `beta.32` `@babel/plugin-syntax-export-extensions` but there is no newer version for it. And when I removed this plugin nothing changed.

There is a list of my current dev dependencies:
```
 "devDependencies": {
    "@babel/cli": "7.0.0-beta.37",
    "@babel/core": "^7.0.0-beta.37",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.37",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0-beta.37",
    "@babel/plugin-syntax-export-extensions": "^7.0.0-beta.32",
    "@babel/plugin-transform-modules-commonjs": "^7.0.0-beta.37",
    "@babel/plugin-transform-react-constant-elements": "7.0.0-beta.37",
    "@babel/plugin-transform-react-inline-elements": "7.0.0-beta.37",
    "@babel/plugin-transform-react-jsx": "7.0.0-beta.37",
    "@babel/plugin-transform-react-jsx-source": "7.0.0-beta.37",
    "@babel/plugin-transform-runtime": "7.0.0-beta.37",
    "@babel/preset-env": "7.0.0-beta.37",
    "@babel/preset-react": "^7.0.0-beta.37",
    "@babel/preset-stage-0": "^7.0.0-beta.37",
    "@babel/register": "7.0.0-beta.37",
    "babel-7-jest": "^21.3.2",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^8.2.1",
    "babel-jest": "^22.0.4",
    "babel-loader": "^8.0.0-beta.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.12", // used only in prod env
    "canvas": "^1.6.5",
    "canvas-prebuilt": "^1.6.5-prerelease.1",
    "chai": "~3.5.0",
    "chai-enzyme": "~0.6.1",
    "chalk": "~1.1.3",
    "compression": "~1.6.2",
    "cors": "^2.8.3",
    "cross-env": "~4.0.0",
    "css-loader": "~0.28.4",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^1.5.1",
    "eslint": "^4.15.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-import-resolver-webpack": "^0.8.4",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "exports-loader": "^0.6.4",
    "express": "~4.15.2",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "~1.1.6",
    "html-loader": "^0.5.4",
    "html-webpack-plugin": "^2.28.0",
    "husky": "^0.13.3",
    "image-webpack-loader": "^3.3.1",
    "imports-loader": "^0.7.1",
    "ip": "~1.1.5",
    "jasmine-reporters": "^2.2.1",
    "jest": "^22.0.5",
    "jest-junit": "^1.5.1",
    "jest-styled-components": "^3.3.2",
    "jsdom": "^11.5.1",
    "karma": "~1.1.1",
    "karma-chai": "~0.1.0",
    "karma-chrome-launcher": "~0.2.1",
    "karma-coverage": "^1.1.1",
    "karma-firefox-launcher": "~0.1.7",
    "karma-jenkins-reporter": "0.0.2",
    "karma-mocha": "~0.2.1",
    "karma-mocha-reporter": "~1.1.3",
    "karma-sourcemap-loader": "~0.3.7",
    "karma-webpack": "~1.8.0",
    "lint-staged": "^3.4.1",
    "mocha": "~2.3.4",
    "npm-run-all": "^4.0.2",
    "null-loader": "~0.1.1",
    "raw-loader": "^0.5.1",
    "react-addons-test-utils": "^15.6.0",
    "rimraf": "^2.6.1",
    "sinon": "~2.2.0",
    "style-loader": "~0.19.1",
    "transform-loader": "~0.2.4",
    "underscore": "^1.8.3",
    "vinyl-buffer": "~1.0.0",
    "vinyl-fs": "~2.4.4",
    "vinyl-source-stream": "~1.1.0",
    "webpack": "^3.10.0",
    "webpack-bundle-tracker": "~0.2.0",
    "webpack-dev-middleware": "~2.0.4",
    "webpack-hot-middleware": "^2.21.0",
    "xmlserializer": "^0.6.0",
    "xpath": "0.0.24"
  }
```

**Comment by darkowic** [comment]
@Andarist any tips how can I debug the problem?

**Comment by darkowic** [comment]
I found that `babel-7-jest` is still installing old babel beta 31 in its `node_modules`.

**Comment by darkowic** [comment]
This is definietly because of `npm-shrinkwrap.json` file :/

**Comment by Andarist** [comment]
`babel-7-jest` is an unofficial community package. You should just install `babel-jest` + `babel-core@7.0.0-bridge.0` + `@babel/core@7.0.0-beta.37` and you will be good to go (dont forget to remove `babel-7-jest`).

**Comment by darkowic** [comment]
Thank for your time and help @Andarist . I'm closing this issue. I will try your solution too. For more check https://github.com/Sneezoo/babel-7-jest/issues/2
