### ISSUE TITLE
@babel/flow-transform-comments: UnionTypeAnnotation minimal example

### ISSUE THREAD

**Issue by houshuang** [babel/babel#7247]
The following minimal example crashes with flow-transform-comments, but works well with flow-strip-types.

```js
(path: string[]) => {
  const aryPath = true && path;
  return [...aryPath];
};
```

This is a reduced example, where I tried to strip out everything that did not cause the error. It seems like any further reductions makes the error go away, for example this does not crash:

```js
(path: string[]) => {
  const aryPath = path;
  return [...aryPath];
};
```

(The actual code before reduction is here: https://github.com/chili-epfl/FROG/blob/develop/frog-utils/src/generateReactiveFn.js#L79 (keyedObjInsert).

Error:
```js
TypeError: Property types[0] of UnionTypeAnnotation expected node to be of a type ["FlowType"] but instead got "Noop"
    at validate (/Users/stian/src/frog/node_modules/@babel/types/lib/definitions/utils.js:136:13)
    at validator (/Users/stian/src/frog/node_modules/@babel/types/lib/definitions/utils.js:95:7)
    at Object.validate (/Users/stian/src/frog/node_modules/@babel/types/lib/definitions/utils.js:191:10)
    at validate (/Users/stian/src/frog/node_modules/@babel/types/lib/validators/validate.js:15:9)
    at builder (/Users/stian/src/frog/node_modules/@babel/types/lib/builders/builder.js:40:27)
    at UnionTypeAnnotation (/Users/stian/src/frog/node_modules/@babel/types/lib/builders/generated/index.js:1189:27)
    at Object.createUnionTypeAnnotation (/Users/stian/src/frog/node_modules/@babel/types/lib/builders/flow/createUnionTypeAnnotation.js:18:47)
    at NodePath.LogicalExpression (/Users/stian/src/frog/node_modules/@babel/traverse/lib/path/inference/inferers.js:107:12)
    at NodePath._getTypeAnnotation (/Users/stian/src/frog/node_modules/@babel/traverse/lib/path/inference/index.js:53:20)
    at NodePath.getTypeAnnotation (/Users/stian/src/frog/node_modules/@babel/traverse/lib/path/inference/index.js:19:19)
```

Reduced .babelrc:
```js
{
  "plugins": [
    "transform-flow-comments"
  ],
  "presets": [
    "@babel/preset-env"
  ]
}
```

Babel: 7.0.0-beta.38
NPM: 5.6.0
Node: 8.7.0

**Comment by rajzshkr** [comment]
```
{
  "presets": ["@babel/preset-env"],
  "plugins": ["@babel/plugin-transform-flow-comments"]
}
```
Can you try updating the plugin name from `transform-flow-comments => @babel/plugin-transform-flow-comments`

**Comment by houshuang** [comment]
Thanks, this worked!
