### ISSUE TITLE
transform-eval plugin doesn't work anymore

### ISSUE THREAD

**Issue by xtuc** [babel/babel#7250]
Choose one: is this a bug report or feature request?

### Input Code

```js
// ....
return ast.program;
```

Doesn't work in recent Babel version.

### Current Behavior

```
  1) babel-plugin-transform-eval/transform eval transform:
     Error: Unexpected return value from visitor method function newFn(path) {
          return fn.call(state, path, state);
        }
      at NodePath._call (packages/babel-traverse/lib/path/context.js:71:13)
      at NodePath.call (packages/babel-traverse/lib/path/context.js:38:17)
      at NodePath.visit (packages/babel-traverse/lib/path/context.js:99:12)
      at TraversalContext.visitQueue (packages/babel-traverse/lib/context.js:139:18)
      at TraversalContext.visitSingle (packages/babel-traverse/lib/context.js:98:19)
      at TraversalContext.visit (packages/babel-traverse/lib/context.js:180:19)
      at Function.traverse.node (packages/babel-traverse/lib/index.js:76:17)
      at NodePath.visit (packages/babel-traverse/lib/path/context.js:106:18)
      at TraversalContext.visitQueue (packages/babel-traverse/lib/context.js:139:18)
      at TraversalContext.visitMultiple (packages/babel-traverse/lib/context.js:93:17)
      at TraversalContext.visit (packages/babel-traverse/lib/context.js:178:19)
      at Function.traverse.node (packages/babel-traverse/lib/index.js:76:17)
      at NodePath.visit (packages/babel-traverse/lib/path/context.js:106:18)
      at TraversalContext.visitQueue (packages/babel-traverse/lib/context.js:139:18)
      at TraversalContext.visitSingle (packages/babel-traverse/lib/context.js:98:19)
      at TraversalContext.visit (packages/babel-traverse/lib/context.js:180:19)
      at Function.traverse.node (packages/babel-traverse/lib/index.js:76:17)
      at traverse (packages/babel-traverse/lib/index.js:46:12)
      at transformFile (packages/babel-core/lib/transformation/index.js:107:27)
      at runSync (packages/babel-core/lib/transformation/index.js:35:3)
      at transformSync (packages/babel-core/lib/transform-sync.js:15:38)
      at Object.transform (packages/babel-core/lib/transform.js:20:65)
      at run (packages/babel-helper-transform-fixture-test-runner/lib/index.js:173:20)
      at runTask (packages/babel-helper-transform-fixture-test-runner/lib/index.js:229:13)
      at Context.<anonymous> (packages/babel-helper-transform-fixture-test-runner/lib/index.js:257:15)
```

### Possible Solution

Use
```js
path.replaceWith(node)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System | 

See failing tests in https://github.com/babel/babel/pull/7249

**Comment by gastonche** [comment]
Hello @xtuc 
Want to work on this issue, but I'd like some guidance on how to start since this is my first task with babel

**Comment by loganfsmyth** [comment]
I posted about it on Slack once, but I may not have ever filed an issue. The `parse` function it is using doesn't even exist. It's entirely possible this plugin has literally never worked. Personally I'm in favor of just erasing it entirely.

**Comment by xtuc** [comment]
@loganfsmyth see https://github.com/babel/babel/pull/7248

**Comment by hzoo** [comment]
Yeah I don't really see the point of this, and it doesn't have to be an official plugin since it's unrelated to what we do as core, also in favor of removing this.

**Comment by rajzshkr** [comment]
So, are we going to fix this issue or remove this plugin?

**Comment by xtuc** [comment]
We can remove it, it has been broken since 2015, I guess nobody is relying on that.

**Comment by rajzshkr** [comment]
Done!!
