### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by AndrewRayCode** [babel/babel#7282]
This error appears to be intermittent. I'm using `babel-eslint` 8.6.2

```
    Module build failed: TypeError: MyFile.jx: Cannot read property 'type' of undefined
        at Whitespace.getNewlinesAfter (node_modules/babel-generator/lib/whitespace.js:50:20)
        at Generator._printNewline (node_modules/babel-generator/lib/printer.js:459:34)
        at Generator.printJoin (node_modules/babel-generator/lib/printer.js:376:32)
        at Generator.printList (node_modules/babel-generator/lib/printer.js:430:17)
        at Generator.ObjectExpression (node_modules/babel-generator/lib/generators/types.js:57:10)
        at node_modules/babel-generator/lib/printer.js:298:23
        at Buffer.withSource (node_modules/babel-generator/lib/buffer.js:168:5)
        at Generator.withSource (node_modules/babel-generator/lib/printer.js:189:15)
        at Generator.print (node_modules/babel-generator/lib/printer.js:297:10)
        at Generator.ArrayExpression (node_modules/babel-generator/lib/generators/types.js:106:12)
        at node_modules/babel-generator/lib/printer.js:298:23
        at Buffer.withSource (node_modules/babel-generator/lib/buffer.js:168:5)
        at Generator.withSource (node_modules/babel-generator/lib/printer.js:189:15)
        at Generator.print (node_modules/babel-generator/lib/printer.js:297:10)
        at Generator.ObjectProperty (node_modules/babel-generator/lib/generators/types.js:92:8)
        at node_modules/babel-generator/lib/printer.js:298:23
        at Buffer.withSource (node_modules/babel-generator/lib/buffer.js:168:5)
        at Generator.withSource (node_modules/babel-generator/lib/printer.js:189:15)
        at Generator.print (node_modules/babel-generator/lib/printer.js:297:10)
        at Generator.printJoin (node_modules/babel-generator/lib/printer.js:366:12)
        at Generator.printList (node_modules/babel-generator/lib/printer.js:430:17)
        at Generator.ObjectExpression (node_modules/babel-generator/lib/generators/types.js:57:10)
        at node_modules/babel-generator/lib/printer.js:298:23
        at Buffer.withSource (node_modules/babel-generator/lib/buffer.js:168:5)
        at Generator.withSource (node_modules/babel-generator/lib/printer.js:189:15)
        at Generator.print (node_modules/babel-generator/lib/printer.js:297:10)
        at Generator.ObjectProperty (node_modules/babel-generator/lib/generators/types.js:92:8)
        at node_modules/babel-generator/lib/printer.js:298:23
        at Buffer.withSource (node_modules/babel-generator/lib/buffer.js:168:5)
        at Generator.withSource (node_modules/babel-generator/lib/printer.js:189:15)
```

Where I suspect there's a problem:

```
import React, { PureComponent } from 'react';

export class MyComponent extends PureComponent {
  someFn = (someArg, someDefaultArg = {}) => {
    console.log('hi');
  };
  render() {

  }
}
```
When I change `someDefaultArg = {}`, the error goes away (sometimes).

**Comment by Akirus** [comment]
For someone why will come to this page from google like me:
Updating babel-generator to 6.26.1 fixed it for me.

**Comment by xtuc** [comment]
Closing, seems to be resolved by now.
