### ISSUE TITLE
Cannot find module 'babel-preset-es2015' while using '@babel/preset-env' and '@babel/plugin-transform-runtime'

### ISSUE THREAD

**Issue by leiming** [babel/babel#7290]
bug report

I want to run webpack which use 'css-loader' which use [js-base64](https://github.com/dankogai/js-base64):

```js
// https://github.com/dankogai/js-base64/blob/master/package.json
  "devDependencies": {
    "babel-preset-es2015": "^6.24.1",
    "babel-register": "^6.26.0",
    "mocha": "*"
  }
```

### Input Code

> Sample:
> https://github.com/leiming/mini-programs-kit/tree/dev-tmp

run `yarn start` to execute `node_modules/.bin/mini-programs-scripts.js`

```js
// project-a/package.json

  "scripts": {
    "start": "mini-programs-scripts start"
  },
```

### '@babel/register' config

> mini-programs-scripts/bin/mini-programs-scripts.js

```js
#!/usr/bin/env node

const path = require('path')
const projectName = require('../package')['name']
const isProject = (path.dirname('').indexOf(`/node_modules/${projectName}`) !== -1)

require('@babel/register')({
  only: isProject ? /`${projectName}`/ : undefined,
  presets: [
    [require('@babel/preset-env'),
      {
        useBuiltIns: 'usage',
        targets: {
          'node': '6.12',
        },
        // debug: true
      }
    ],
  ],
  plugins: [
    [require('@babel/plugin-transform-runtime'), {
      helpers: true,
      polyfill: false,
      reGenerator: true,
    }],
    require('@babel/plugin-proposal-object-rest-spread'),
    require('@babel/plugin-transform-async-to-generator'),
  ],


  extensions: ['.js', '.mjs'],
  cache: false,
})
```

### Current Behavior

```
ERROR in ../mini-programs-scripts/node_modules/css-loader!./src/pages/demo/demo.css
Module build failed: Error: Cannot find module 'babel-preset-es2015' from '/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/js-base64'
- Did you mean "@babel/es2015"?
    at Function.module.exports [as sync] (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/resolve/lib/sync.js:40:15)
    at resolveStandardizedName (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/files/plugins.js:78:29)
    at resolvePreset (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/files/plugins.js:31:10)
    at loadPreset (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/files/plugins.js:50:18)
    at createDescriptor (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/config-descriptors.js:135:21)
    at /Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/config-descriptors.js:101:12
    at Array.map (<anonymous>)
    at createDescriptors (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/config-descriptors.js:100:27)
    at createPresetDescriptors (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/config-descriptors.js:92:10)
    at /Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/config-descriptors.js:64:19
    at presets (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/config-descriptors.js:54:25)
    at mergeChainOpts (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/config-chain.js:293:68)
    at /Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/config-chain.js:246:7
    at buildRootChain (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/config-chain.js:82:20)
    at loadConfig (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/config/index.js:50:53)
    at loadOptions (/Users/leiming/IdeaProjects/mini-programs-kit/packages/mini-programs-scripts/node_modules/@babel/core/lib/index.js:72:36)
 @ ./src/pages/demo/demo.css 2:14-104
 @ ./src/pages/demo/demo.js
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.38
| node             |  v9.4.0
| npm              | 5.6.0
| css-loader              | 0.28.9
| Operating System | macOS 10.13.3

**Comment by leiming** [comment]
@hzoo thanks, it is.

**Comment by AoDev** [comment]
@leiming Could you share your fixed config? I have this issue when building on a windows OS but not OSX
