### ISSUE TITLE
npm registry return not found 404

### ISSUE THREAD

**Issue by jimblue** [babel/babel#7301]
Hi!

It seems the last release broke something with `npm registry`.

I can't install any `@babel` package neither with `npm` nor `yarn`

**Comment by jimblue** [comment]
Here is the error return in `yarn-error.log`:

```
Trace: 
  Error: https://registry.npmjs.org/@babel%2fcore: User not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:62098:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:123085:22)
      at Request.emit (events.js:160:13)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:124068:10)
      at Request.emit (events.js:160:13)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:123988:12)
      at Object.onceWrapper (events.js:255:19)
      at IncomingMessage.emit (events.js:165:20)
      at endReadableNT (_stream_readable.js:1101:12)
      at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by hzoo** [comment]
hey Jim! I think I would just try it again? Maybe it was weird initally but I even have a PR to update babel itself and it passes CI https://github.com/babel/babel/pull/7302

**Comment by jimblue** [comment]
Hey @hzoo just try again it's not working. All my package but `@babel` install without issue.

**Comment by jimblue** [comment]
<img width="693" alt="screen shot 2018-01-31 at 01 29 41" src="https://user-images.githubusercontent.com/10623367/35598886-4a88f4ea-0626-11e8-9f56-632302895f60.png">
<img width="693" alt="screen shot 2018-01-31 at 01 29 55" src="https://user-images.githubusercontent.com/10623367/35598887-4a9e9a20-0626-11e8-9ef7-da7a7db41b33.png">

**Comment by loganfsmyth** [comment]
Does it work if you open it in a browser? That URL loads fine for me. I don't know what "User not found" means in this case, but maybe your own local user is configured incorrectly in Yarn, assuming you have an account on the npm registry?

**Comment by jimblue** [comment]
Just try to remove all `@babel` related package from my `package.json`.
Both `yarn` and `npm install` are working!

**Comment by jimblue** [comment]
Same problem when trying to install `@babel`
<img width="697" alt="screen shot 2018-01-31 at 01 35 09" src="https://user-images.githubusercontent.com/10623367/35599007-0183cff8-0627-11e8-82d4-efaefd9fd31b.png">

**Comment by loganfsmyth** [comment]
Does the URL `https://registry.npmjs.org/@babel%2fcore` load for you in a browser? The packages are published and do exist. I have no idea what `User not found` means here.

**Comment by jimblue** [comment]
@loganfsmyth I just try in chrome to browse to `https://registry.npmjs.org/@babel%2fcore`
It's working!

**Comment by jimblue** [comment]
<img width="950" alt="screen shot 2018-01-31 at 01 36 49" src="https://user-images.githubusercontent.com/10623367/35599071-3d89e708-0627-11e8-8441-e64a8f4a061e.png">

**Comment by jimblue** [comment]
Ok just found!

I wanted to publish my first npm package this afternoon by following this: `https://docs.npmjs.com/getting-started/publishing-npm-packages`

In my root directory I've found a new `.npmrc` file:
<img width="429" alt="screen shot 2018-01-31 at 01 43 51" src="https://user-images.githubusercontent.com/10623367/35599294-5c4a60f4-0628-11e8-952e-fefac54ed0c3.png">

I just removed it and it's working again.
