### ISSUE TITLE
[preset-env] Duplicate declaration "object"

### ISSUE THREAD

**Issue by julien-f** [babel/babel#7304]
### Is this a bug report or feature request?

Bug

[Repro repo](https://github.com/julien-f/issue-babel-env-duplicate).

### Input Code

```js
export default class {
  method ({ ...object }) {}
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "@babel/env",
      {
        "shippedProposals": true,
        "targets": {
          "node": 8
        },
        "useBuiltIns": "usage"
      }
    ]
  ]
}
```

### Expected Behavior

Should compile.

### Current Behavior

```
TypeError: index.js: Duplicate declaration "object"
  1 | export default class {
> 2 |   method ({ ...object }) {}
    |                ^
  3 | }
  4 |
    at File.buildCodeFrameError (issue-babel-env-duplicate/node_modules/@babel/core/lib/transformation/file/file.js:209:12)
    at Scope.checkBlockScopedCollisions (issue-babel-env-duplicate/node_modules/@babel/traverse/lib/scope/index.js:303:27)
    at Scope.registerBinding (issue-babel-env-duplicate/node_modules/@babel/traverse/lib/scope/index.js:485:16)
    at Scope.registerDeclaration (issue-babel-env-duplicate/node_modules/@babel/traverse/lib/scope/index.js:404:14)
    at Object.BlockScoped (issue-babel-env-duplicate/node_modules/@babel/traverse/lib/scope/index.js:146:28)
    at Object.newFn (issue-babel-env-duplicate/node_modules/@babel/traverse/lib/visitors.js:266:17)
    at NodePath._call (issue-babel-env-duplicate/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (issue-babel-env-duplicate/node_modules/@babel/traverse/lib/path/context.js:34:14)
    at NodePath.visit (issue-babel-env-duplicate/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (issue-babel-env-duplicate/node_modules/@babel/traverse/lib/context.js:139:18)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.39
| Babylon          | 
| node             | 9.4.0
| npm              | 
| Operating System |

**Comment by rajzshkr** [comment]
Can you check the target node version. I think proposal-object-rest-spread is not shipped in node version 8. it works fine if i change to "8.9.1".

**Comment by benjamn** [comment]
I have a reproduction for a similar problem that I'm planning to submit as a PR soon, with a fix if possible.

**Comment by julien-f** [comment]
@rajzshkr I'm using `shippedProposals` so it should compile it if necessary.

It works with `"node": 6` for instance

**Comment by hzoo** [comment]
cc @nicolo-ribaudo if you have an idea

**Comment by nicolo-ribaudo** [comment]
I can investigate :+1:
