### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by bonovski** [babel/babel#7324]
I replaced **babel-preset-es2015** with **babel-preset-env** in my gulp project.

When trying to compile I get the error in the title. 
Now after I install the es2015 preset again alongside the env package everything works as normal despite my gulp file not referencing it at all, it just has to be present in node_modules.

I found a few threads on this but no working solution.
I deleted node_modules and installed everything from scratch but it still isn't working with env only.

`"babel-core": "^6.26.0",
"babel-preset-env": "^1.6.1", 
"babel-preset-es2015": "^6.24.1",
"babelify": "^8.0.0",`

**Comment by xtuc** [comment]
Could you please share your Babel configuration?

**Comment by bonovski** [comment]
My package.json:
```
"devDependencies": {
        "babel-core": "^6.26.0",
        "babel-preset-env": "^1.6.1",
        "babel-preset-es2015": "^6.24.1",
        "babelify": "^8.0.0",
        "browser-sync": "^2.23.5",
        "browserify": "^15.2.0",
        "del": "^3.0.0",
        "eslint": "^4.15.0",
        "foundation-sites": "^6.4.3",
        "gulp": "^3.9.1",
        "gulp-autoprefixer": "^4.1.0",
        "gulp-if": "^2.0.2",
        "gulp-imagemin": "^4.1.0",
        "gulp-notify": "^3.1.0",
        "gulp-options": "^1.1.1",
        "gulp-rename": "^1.2.2",
        "gulp-sass": "^3.1.0",
        "gulp-sourcemaps": "^2.6.3",
        "gulp-strip-debug": "^2.0.0",
        "gulp-uglify": "^3.0.0",
        "jquery": "^3.3.1",
        "motion-ui": "^1.2.3",
        "vinyl-buffer": "^1.0.1",
        "vinyl-source-stream": "^2.0.0"
    },
   "babel": {"presets": [ "env"]}
```
My gulpfile.js:
```
// scripts task
gulp.task( 'scripts', function() {
	return browserify({
		entries: jsMain
	})
		.transform( babelify, { presets: [ 'env' ] } )
		.bundle()
		.pipe( source(jsSRC) )
		.pipe( rename( {
			extname: '.min.js'
		} ) )
		.pipe( buffer() )
		.pipe( gulpif( options.has( 'production' ), stripDebug() ) )
		.pipe( sourcemaps.init({ loadMaps: true }) )
		.pipe( uglify() )
		.pipe( sourcemaps.write( '.' ) )
		.pipe( gulp.dest( jsURL ) )
		.pipe( browserSync.stream() );
});
```

**Comment by bonovski** [comment]
The complete error:

```
> Error: Couldn't find preset "es2015" relative to directory "/Users/peter/Sites/gulp-es6/node_modules/foundation-sites/dist/js" while parsing file: /Users/peter/Sites/gulp-es6/node_modules/foundation-sites/dist/js/npm.js
>     at /Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
>     at Array.map (<anonymous>)
>     at OptionManager.resolvePresets (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
>     at OptionManager.mergePresets (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
>     at OptionManager.mergeOptions (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
>     at OptionManager.init (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
>     at File.initOptions (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/index.js:212:65)
>     at new File (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/file/index.js:135:24)
>     at Pipeline.transform (/Users/peter/Sites/gulp-es6/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
>     at Babelify._flush (/Users/peter/Sites/gulp-es6/node_modules/babelify/index.js:26:24)
```

**Comment by bonovski** [comment]
The issue appears only with foundation, all other imports from node_modules are compiling without errors.
