### ISSUE TITLE
babel-node can't be installed

### ISSUE THREAD

**Issue by fehergeri13** [babel/babel#7397]
BUG:

If I try to install babel-node with: `yarn add babel-node` in an empty directory, I get this:

```
$ yarn add babel-node
yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⡀ babel-node
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
error C:\Users\gergo\Desktop\test\node_modules\babel-node: Command failed.
Exit code: 1
Command: node message.js; sleep 10; exit 1;
Arguments:
Directory: C:\Users\gergo\Desktop\test\node_modules\babel-node
Output:
module.js:557
    throw err;
    ^

Error: Cannot find module 'C:\Users\gergo\Desktop\test\node_modules\babel-node\message.js;'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)

```

`npm i babel-node`

```
npm i babel-node

> babel-node@6.5.3 postinstall C:\Users\gergo\Desktop\test\node_modules\babel-node
> node message.js; sleep 10; exit 1;

module.js:557
    throw err;
    ^

Error: Cannot find module 'C:\Users\gergo\Desktop\test\node_modules\babel-node\message.js;'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\gergo\Desktop\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! babel-node@6.5.3 postinstall: `node message.js; sleep 10; exit 1;`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the babel-node@6.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gergo\AppData\Roaming\npm-cache\_logs\2018-02-19T22_26_13_241Z-debug.log
```

debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\gergo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'babel-node' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose npm-session 788abf0976204661
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/babel-node 256ms (from cache)
8 silly pacote tag manifest for babel-node@latest fetched in 299ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
.
.
.
3490 silly postinstall github-username@1.1.1
3491 info lifecycle github-username@1.1.1~postinstall: github-username@1.1.1
3492 silly postinstall github-current-user@2.5.0
3493 info lifecycle github-current-user@2.5.0~postinstall: github-current-user@2.5.0
3494 silly postinstall babel-node@6.5.3
3495 info lifecycle babel-node@6.5.3~postinstall: babel-node@6.5.3
3496 verbose lifecycle babel-node@6.5.3~postinstall: unsafe-perm in lifecycle true
3497 verbose lifecycle babel-node@6.5.3~postinstall: PATH: C:\Users\gergo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\gergo\Desktop\test\node_modules\babel-node\node_modules\.bin;C:\Users\gergo\Desktop\test\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\sbt\bin;C:\Program Files\PuTTY\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\gergo\Anaconda3;C:\Users\gergo\Anaconda3\Scripts;C:\Users\gergo\Anaconda3\Library\bin;C:\Users\gergo\AppData\Local\Microsoft\WindowsApps;C:\Users\gergo\AppData\Roaming\npm;C:\Users\gergo\AppData\Local\Yarn\.bin;C:\Program Files\Microsoft VS Code\bin;C:\texlive\2017\bin\win32;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs\;C:\Users\gergo\Anaconda3;C:\Users\gergo\Anaconda3\Scripts;C:\Users\gergo\Anaconda3\Library\bin;C:\Users\gergo\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;C:\texlive\2017\bin\win32;C:\Users\gergo\AppData\Local\Yarn\bin;C:\Users\gergo\AppData\Roaming\npm
3498 verbose lifecycle babel-node@6.5.3~postinstall: CWD: C:\Users\gergo\Desktop\test\node_modules\babel-node
3499 silly lifecycle babel-node@6.5.3~postinstall: Args: [ '/d /s /c', 'node message.js; sleep 10; exit 1;' ]
3500 silly lifecycle babel-node@6.5.3~postinstall: Returned: code: 1  signal: null
3501 info lifecycle babel-node@6.5.3~postinstall: Failed to exec postinstall script
3502 verbose unlock done using C:\Users\gergo\AppData\Roaming\npm-cache\_locks\staging-766ca4e48aca1963.lock for C:\Users\gergo\Desktop\test\node_modules\.staging
3503 silly saveTree test
3503 silly saveTree `-- babel-node@6.5.3
3503 silly saveTree   `-- github-current-user@2.5.0
3503 silly saveTree     +-- debug@2.6.9
3503 silly saveTree     | `-- ms@2.0.0
3503 silly saveTree     +-- ghsign@1.3.3
3503 silly saveTree     | +-- request@2.83.0
3503 silly saveTree     | | +-- aws-sign2@0.7.0
3503 silly saveTree     | | +-- aws4@1.6.0
3503 silly saveTree     | | +-- caseless@0.12.0
3503 silly saveTree     | | +-- combined-stream@1.0.6
3503 silly saveTree     | | | `-- delayed-stream@1.0.0
3503 silly saveTree     | | +-- extend@3.0.1
3503 silly saveTree     | | +-- forever-agent@0.6.1
3503 silly saveTree     | | +-- form-data@2.3.2
3503 silly saveTree     | | | +-- asynckit@0.4.0
3503 silly saveTree     | | | `-- mime-types@2.1.18
3503 silly saveTree     | | |   `-- mime-db@1.33.0
3503 silly saveTree     | | +-- har-validator@5.0.3
3503 silly saveTree     | | | +-- ajv@5.5.2
3503 silly saveTree     | | | | +-- co@4.6.0
3503 silly saveTree     | | | | +-- fast-deep-equal@1.0.0
3503 silly saveTree     | | | | +-- fast-json-stable-stringify@2.0.0
3503 silly saveTree     | | | | `-- json-schema-traverse@0.3.1
3503 silly saveTree     | | | `-- har-schema@2.0.0
3503 silly saveTree     | | +-- hawk@6.0.2
3503 silly saveTree     | | | +-- boom@4.3.1
3503 silly saveTree     | | | | `-- hoek@4.2.1
3503 silly saveTree     | | | +-- cryptiles@3.1.2
3503 silly saveTree     | | | | `-- boom@5.2.0
3503 silly saveTree     | | | +-- hoek@4.2.1
3503 silly saveTree     | | | `-- sntp@2.1.0
3503 silly saveTree     | | +-- http-signature@1.2.0
3503 silly saveTree     | | | +-- assert-plus@1.0.0
3503 silly saveTree     | | | +-- jsprim@1.4.1
3503 silly saveTree     | | | | +-- extsprintf@1.3.0
3503 silly saveTree     | | | | +-- json-schema@0.2.3
3503 silly saveTree     | | | | `-- verror@1.10.0
3503 silly saveTree     | | | |   `-- core-util-is@1.0.2
3503 silly saveTree     | | | `-- sshpk@1.13.1
3503 silly saveTree     | | |   +-- asn1@0.2.3
3503 silly saveTree     | | |   +-- bcrypt-pbkdf@1.0.1
3503 silly saveTree     | | |   | `-- tweetnacl@0.14.5
3503 silly saveTree     | | |   +-- dashdash@1.14.1
3503 silly saveTree     | | |   +-- ecc-jsbn@0.1.1
3503 silly saveTree     | | |   | `-- jsbn@0.1.1
3503 silly saveTree     | | |   +-- getpass@0.1.7
3503 silly saveTree     | | |   +-- jsbn@0.1.1
3503 silly saveTree     | | |   `-- tweetnacl@0.14.5
3503 silly saveTree     | | +-- is-typedarray@1.0.0
3503 silly saveTree     | | +-- isstream@0.1.2
3503 silly saveTree     | | +-- json-stringify-safe@5.0.1
3503 silly saveTree     | | +-- mime-types@2.1.18
3503 silly saveTree     | | +-- oauth-sign@0.8.2
3503 silly saveTree     | | +-- performance-now@2.1.0
3503 silly saveTree     | | +-- qs@6.5.1
3503 silly saveTree     | | +-- safe-buffer@5.1.1
3503 silly saveTree     | | +-- stringstream@0.0.5
3503 silly saveTree     | | +-- tough-cookie@2.3.3
3503 silly saveTree     | | | `-- punycode@1.4.1
3503 silly saveTree     | | +-- tunnel-agent@0.6.0
3503 silly saveTree     | | `-- uuid@3.2.1
3503 silly saveTree     | +-- ssh-agent@0.2.4
3503 silly saveTree     | | +-- ctype@0.5.4
3503 silly saveTree     | | `-- posix-getopt@1.1.0
3503 silly saveTree     | +-- ssh-key-to-pem@0.11.1
3503 silly saveTree     | | +-- asn1@0.1.11
3503 silly saveTree     | | `-- ctype@0.5.2
3503 silly saveTree     | `-- thunky@0.1.0
3503 silly saveTree     +-- git-config-path@0.1.0
3503 silly saveTree     +-- github-username@1.1.1
3503 silly saveTree     | +-- get-stdin@1.0.0
3503 silly saveTree     | `-- got@2.9.2
3503 silly saveTree     |   +-- duplexify@3.5.3
3503 silly saveTree     |   | +-- end-of-stream@1.4.1
3503 silly saveTree     |   | | `-- once@1.4.0
3503 silly saveTree     |   | |   `-- wrappy@1.0.2
3503 silly saveTree     |   | +-- inherits@2.0.3
3503 silly saveTree     |   | +-- readable-stream@2.3.4
3503 silly saveTree     |   | | +-- isarray@1.0.0
3503 silly saveTree     |   | | +-- process-nextick-args@2.0.0
3503 silly saveTree     |   | | +-- string_decoder@1.0.3
3503 silly saveTree     |   | | `-- util-deprecate@1.0.2
3503 silly saveTree     |   | `-- stream-shift@1.0.0
3503 silly saveTree     |   +-- infinity-agent@2.0.3
3503 silly saveTree     |   +-- is-stream@1.1.0
3503 silly saveTree     |   +-- lowercase-keys@1.0.0
3503 silly saveTree     |   +-- nested-error-stacks@1.0.2
3503 silly saveTree     |   +-- object-assign@2.1.1
3503 silly saveTree     |   +-- prepend-http@1.0.4
3503 silly saveTree     |   +-- read-all-stream@2.2.0
3503 silly saveTree     |   +-- statuses@1.4.0
3503 silly saveTree     |   `-- timed-out@2.0.0
3503 silly saveTree     +-- parse-git-config@0.3.2
3503 silly saveTree     | `-- ini@1.3.5
3503 silly saveTree     `-- request@2.83.0
3504 warn enoent ENOENT: no such file or directory, open 'C:\Users\gergo\Desktop\test\package.json'
3505 verbose enoent This is related to npm not being able to find a file.
3506 warn test No description
3507 warn test No repository field.
3508 warn test No README data
3509 warn test No license field.
3510 verbose stack Error: babel-node@6.5.3 postinstall: `node message.js; sleep 10; exit 1;`
3510 verbose stack Exit status 1
3510 verbose stack     at EventEmitter.<anonymous> (C:\Users\gergo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
3510 verbose stack     at EventEmitter.emit (events.js:160:13)
3510 verbose stack     at ChildProcess.<anonymous> (C:\Users\gergo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
3510 verbose stack     at ChildProcess.emit (events.js:160:13)
3510 verbose stack     at maybeClose (internal/child_process.js:943:16)
3510 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
3511 verbose pkgid babel-node@6.5.3
3512 verbose cwd C:\Users\gergo\Desktop\test
3513 verbose Windows_NT 10.0.16299
3514 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gergo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "babel-node"
3515 verbose node v9.5.0
3516 verbose npm  v5.6.0
3517 error code ELIFECYCLE
3518 error errno 1
3519 error babel-node@6.5.3 postinstall: `node message.js; sleep 10; exit 1;`
3519 error Exit status 1
3520 error Failed at the babel-node@6.5.3 postinstall script.
3520 error This is probably not a problem with npm. There is likely additional logging output above.
3521 verbose exit [ 1, true ]
```

| software         | version(s)
| ---------------- | -------
| Babel            |  no
| Babylon          | no
| node             | 9.5.0
| npm              | 5.6.0
| Operating System | Windoiw

**Comment by loganfsmyth** [comment]
You're not installing the right package, and it looks like the one you are installing doesn't work right on `yarn`. The `babel-node` command in Babel 6 is part of the `babel-cli` package, but you are attempting to install the package `babel-node`.

That package, on `npm` anyway, prints:

```
$ npm i babel-node

> babel-node@6.5.3 postinstall /private/tmp/node_modules/babel-node
> node message.js; sleep 10; exit 1;

┌─────────────────────────────────────────────────────────────────────────────┐
|                         Hello there loganfsmyth 😛                           │
|          You tried to install babel-node. This is not babel-node 🚫          │
|               You should npm install -g babel-cli instead 💁 .               │
|    I took this module to prevent somebody from pushing malicious code. 🕵    │
|                    Be careful out there, loganfsmyth! 👍                     │
└─────────────────────────────────────────────────────────────────────────────┘
```

but it looks like the logic to print this message fails on Yarn.

**Comment by jh3141** [comment]
The problem isn't yarn specific.  I'm seeing it in npm.  The logic fails under Windows: CMD.EXE doesn't understand semicolons as a command separator, so the command doesn't get split there - resulting in node looking for a file called "message.js;" to execute.  Would suggest including the sleep and error conditions raised as part of message.js rather than including them in the postinstall script.

**Comment by damncabbage** [comment]
I'd recommend reopening this issue, if only so the docs get fixed. https://babeljs.io/docs/usage/cli/#babel-node refers to `npx babel-node`, which points to this package.

**Comment by loganfsmyth** [comment]
Hmm, @existentialism @hzoo any thoughts on documentation for this? `npx` will execute the correct thing if `babel-cli` is already installed I believe, but if it isn't, it'll try to install `babel-node` which one of the reasons I'm not a fan of the auto-install behavior of `npx`.
