### ISSUE TITLE
TypeScript : cannot produce valid commonJS with module declaration file

### ISSUE THREAD

**Issue by jy95** [babel/babel#7398]
Choose one: is this a bug report or feature request?

Bug , reproduced on my repo branch : [mediaScan](https://github.com/jy95/mediaScan/tree/babelV7)

### Minimal Input Code

Whatever module declaration file : 
**src/declaration.d.ts**
```ts
// declaration.d.ts
declare module MediaScan {
      // whatever TypeScript: interface, type , enum | a short example : 
     export interface TPN {
        title: string;
        year?: number;
        resolution?: string;
        extended?: boolean;
        unrated?: boolean;
        proper?: boolean;
        repack?: boolean;
        convert?: boolean;
        hardcoded?: boolean;
        retail?: boolean;
        remastered?: boolean;
        region?: string;
        container?: string;
        source?: string;
        codec?: string;
        audio?: string;
        group?: string;
        season?: number;
        episode?: number;
        language?: string;
    }
}

export default MediaScan;
```
And a file that uses it : 
**src/filters/filterProperties.ts**
```ts
/* eslint-disable no-useless-escape,max-len */
/**
 * Boolean properties filter
 */
import {
    filterDefaultBooleanProperties,
    filterByBoolean,
    excludeDefaultBooleanProperties,
} from './filterBooleanProperty';

/**
 * Number properties filter
 */
import {
    convertToValidExpression,
    excludeDefaultNumberProperties,
    filterDefaultNumberProperties,
    filterByNumber,
} from './filterNumberProperty';

/**
 * String properties filter
 */
import {
    excludeDefaultStringProperties,
    filterDefaultStringProperties,
    filterByString,
} from './filterStringProperty';
import MediaScan from "../declaration";

/**
 * Handle searchParameters provided by user to maps
 * @param {searchParameters} searchParameters - search parameters.
 * an object that contains mapped properties for search
 */
function mapProperties(searchParameters: MediaScan.SearchParameters): {
    booleanFieldsSearchMap: Map<string, boolean>, numberFieldsSearchMap: Map<string, MediaScan.NumberExpressionObject>,
    stringFieldsSearchMap: Map<string, string | string[]> } {

    // organize search based on field type : boolean - string - number
    const booleanFieldsSearchMap = filterDefaultBooleanProperties(searchParameters);
    let leftSearchParameters = excludeDefaultBooleanProperties(searchParameters);

    const numberFieldsSearchMap = filterDefaultNumberProperties(leftSearchParameters);
    leftSearchParameters = excludeDefaultNumberProperties(leftSearchParameters);

    const stringFieldsSearchMap = filterDefaultStringProperties(leftSearchParameters);
    leftSearchParameters = excludeDefaultStringProperties(leftSearchParameters);

    let {additionalProperties} = leftSearchParameters;
    // add the optional new properties , optionally provided by user
    /* istanbul ignore else */
    if (additionalProperties !== undefined) {
        additionalProperties
            .filter(newProperty => newProperty.type === MediaScan.AdditionalPropertiesType.BOOLEAN)
            .forEach((newProperty) => {
                booleanFieldsSearchMap.set(newProperty.name, newProperty.value as boolean);
            });

        additionalProperties
            .filter(newProperty => newProperty.type === MediaScan.AdditionalPropertiesType.NUMBER)
            .forEach((newProperty) => {
                let expression = convertToValidExpression(newProperty.value as string|number);
                /* istanbul ignore else */
                if (expression !== undefined) {
                    numberFieldsSearchMap.set(newProperty.name, expression);
                }
            });

        additionalProperties
            .filter(newProperty => newProperty.type === MediaScan.AdditionalPropertiesType.STRING)
            .forEach((newProperty) => {
                stringFieldsSearchMap.set(newProperty.name, [...newProperty.value]);
            });
    }

    return {
        booleanFieldsSearchMap,
        numberFieldsSearchMap,
        stringFieldsSearchMap,
    };
}

/** Filter the movies based on search parameters */
export function filterMoviesByProperties(searchParameters: MediaScan.SearchParameters, allMovies: Set<MediaScan.TPN>): Set<MediaScan.TPN> {
    const {
        booleanFieldsSearchMap, stringFieldsSearchMap,
        numberFieldsSearchMap,
    } = mapProperties(searchParameters);
    const propertiesWithAllProperties
        = [booleanFieldsSearchMap, stringFieldsSearchMap, numberFieldsSearchMap];
    let result = allMovies;
    [filterByBoolean, filterByString, filterByNumber]
        .forEach((filterFunction : (set: Set<MediaScan.TPN>, propertiesMap: Map<string, any>) => Set<MediaScan.TPN>, index) => {
            result = filterFunction(result, propertiesWithAllProperties[index]);
        });
    return result;
}

/** Filter the tv series based on search parameters */
export function filterTvSeriesByProperties(searchParameters: MediaScan.SearchParameters, allTvSeries: Map<string, Set<MediaScan.TPN>>): Map<string, Set<MediaScan.TPN>> {
    const {
        booleanFieldsSearchMap, stringFieldsSearchMap,
        numberFieldsSearchMap,
    } = mapProperties(searchParameters);
    const propertiesWithAllProperties
        = [booleanFieldsSearchMap, stringFieldsSearchMap, numberFieldsSearchMap];
    let result : Map<string, Set<MediaScan.TPN>> = allTvSeries;
    // filtering stuff
    // it also removes all entries that have an empty Set so that we can clearly see only valid things

    [filterByBoolean, filterByString, filterByNumber]
        .forEach((filterFunction : (set: Set<MediaScan.TPN>, propertiesMap: Map<string, any>) => Set<MediaScan.TPN>, index) => {
            result = new Map(<[string, Set<MediaScan.TPN>][]>
                Array.from(
                    result.entries(),
                    ([showName, showSet]) => [showName, filterFunction(showSet, propertiesWithAllProperties[index])],
                )
                // eslint-disable-next-line no-unused-vars
                .filter(([showName, showSet]) => (showSet as Set<MediaScan.TPN>).size > 0));
        });

    return result;
}
```

### .babelrc.js

```js
var presets = [
    "@babel/env",
    "@babel/typescript"
];
var plugins = [
    "@babel/proposal-class-properties"
];
var ignore = [];
var comments = false;

module.exports = {
    presets: presets,
    plugins: plugins,
    ignore: ignore,
    comments: comments
};
```

### Expected Behavior
It should correctly compile and ignore the TypeScript declaration file

### Current Behavior
The compiled code : 
**lib/declaration.d.js**
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
var _default = MediaScan;
exports.default = _default;
```
(only interesting part of filterProperties.js)
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.filterMoviesByProperties = filterMoviesByProperties;
exports.filterTvSeriesByProperties = filterTvSeriesByProperties;

var _filterBooleanProperty = require("./filterBooleanProperty");

var _filterNumberProperty = require("./filterNumberProperty");

var _filterStringProperty = require("./filterStringProperty");

var _declaration = _interopRequireDefault(require("../declaration"));
```

Result : 
```
 FAIL  __tests__\getters\allFilesWithCategory.ts
  ● Test suite failed to run

    Cannot find module '../declaration' from 'filterProperties.js'

      13 | var _filterStringProperty = require("./filterStringProperty");
      14 | 
    > 15 | var _declaration = _interopRequireDefault(require("../declaration"));
      16 | 
      17 | function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
      18 | 
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:194:17)
      at Object.<anonymous> (lib/filters/filterProperties.js:15:92)
```

### Possible Solution
Only idea : make a thing that distinct regular import from namespace/module import , for example with a option in (like files, declaration , etc)

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.40
| node             | 8.9.3
| npm              | 5.6.0
| Operating System | Windows 10 

#### devDependencies

```js
"devDependencies": {
    "@babel/cli": "^7.0.0-beta.40",
    "@babel/core": "^7.0.0-beta.40",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "@babel/preset-typescript": "^7.0.0-beta.40",
    "@semantic-release/changelog": "^1.1.1",
    "@semantic-release/git": "^3.1.1",
    "@types/jest": "^22.1.3",
    "@types/node": "^9.4.6",
    "conventional-changelog-eslint": "^1.0.2",
    "jest": "^22.3.0",
    "semantic-release": "^14.0.3",
    "typescript": "^2.7.2"
  }
```

**Comment by nicolo-ribaudo** [comment]
The typescript declaration file is now correctly compiled to an empty file ([REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PTAEBMFMGMBsEMBO8AuBLA9gOwHThygM4BQUcSkoAthuAK6yUCyk4a8AytPFqAN7FQQ4SFAB3ABapIAN0iJQAFQCeAB0hdEaVSgBcoNFhTyAZvGiQANKBRrK1yFjpVQAH1DxQhCRkQpQkAAe8FSqjKD6gsIBgaq-_obGiGYWSgAKAHL8UdFC6CiM-oQoWlgA5gDcObnKkEgA_PpOVABG8lW5woiQhBiwdOjYjV4lhpXV0UHGWFDgwy0YfXVYHZ2gdFjIxnP6C0s8q52qiBjqiPOLjAcTXZCq5gDWF_srN0LQ2HJ-z1eva6BSRDgD6zH7LQ65booeBoWBg67_bpUeDFeSseF_NbdMqYLDDYqlcb_D5GGFYeT40blCHRXp0RAWSmEmnCEEwJljFlCeB0NgYDnUt6gMonOiqAVEtaEOq9PFNZxtRBcgKqNC9KDDZqK5UIcp0eBlSASiEAX2IZuIQTifggkDMDH8LDYnG4ryAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.12.12&externalPlugins=)).

In `filterProperties.ts`, you can use `import type MediaScan from "../declaration";` to prevent Babel from injecting a `require()` call.
