### ISSUE TITLE
Error: Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by AnthonyPaulO** [babel/babel#7470]
I've been banging my head against this for a week. I get the following error when running webpack 4 (or 3) for certain bundles:

> ERROR in ./node_modules/cib-bento-ui-sources/bundles/bootstrapper/js/bootstrapper.js
> Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions.
>     at createDescriptor (C:\dev\projects\storm-ui\node_modules\@babel\core\lib\config\config-descriptors.js:158:11)
>     at C:\dev\projects\storm-ui\node_modules\@babel\core\lib\config\config-descriptors.js:101:12
>     at Array.map (<anonymous>)
>     at createDescriptors (C:\dev\projects\storm-ui\node_modules\@babel\core\lib\config\config-descriptors.js:100:27)
>     at createPresetDescriptors (C:\dev\projects\storm-ui\node_modules\@babel\core\lib\config\config-descriptors.js:92:10)
>     at C:\dev\projects\storm-ui\node_modules\@babel\core\lib\config\config-descriptors.js:64:19
>     at presets (C:\dev\projects\storm-ui\node_modules\@babel\core\lib\config\config-descriptors.js:54:25)
>     at mergeChainOpts (C:\dev\projects\storm-ui\node_modules\@babel\core\lib\config\config-chain.js:294:68)
>     at C:\dev\projects\storm-ui\node_modules\@babel\core\lib\config\config-chain.js:247:7
>     at buildRootChain (C:\dev\projects\storm-ui\node_modules\@babel\core\lib\config\config-chain.js:83:20)
>     at loadConfig (C:\dev\projects\storm-ui\node_modules\@babel\core\lib\config\index.js:50:53)
>     at C:\dev\projects\storm-ui\node_modules\@babel\core\lib\transform.js:26:33
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
>  @ ./bundles/storm-settings-widget/ts/storm-settings-widget.ts 17:27-59

package.json
```
{
  "name": "storm",
  "version": "1.6.35",
  "main": "src/js/index.js",
  "private": true,
  "jest": {
    "moduleFileExtensions": [
      "js",
      "ts",
      "tsx"
    ],
    "testMatch": [
      "**/bundles/storm-blotter-widget/ts/**/*.spec.(ts|tsx)"
    ],
    "transform": {
      "^.+\\.(ts|tsx)$": "<rootDir>/preprocessor.ts"
    },
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ],
    "verbose": true
  },
  "scripts": {
    "bundle": "webpack --env development --config webpack.config4.js"
  },
  "dependencies": {
    "cib-bento-ui": "3.15.0",
    "cib-bento-ui-sources": "3.15.0",
    "clipboard": "1.5.8",
    "core-js": "2.5.1",
    "extend-me": "2.4.0",
    "gsap": "1.20.3",
    "immutability-helper": "2.0.0",
    "immutable": "3.8.1",
    "ramda": "0.24.1",
    "react-dnd": "2.5.4",
    "react-dnd-html5-backend": "2.3.0",
    "react-dom-factories": "1.0.1",
    "react-layout-components": "3.0.6"
  },
  "devDependencies": {
    "@babel/cli": "7.0.0-beta.40",
    "@babel/core": "7.0.0-beta.40",
    "@babel/plugin-proposal-class-properties": "7.0.0-beta.40",
    "@babel/plugin-proposal-decorators": "7.0.0-beta.40",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.40",
    "@babel/preset-env": "7.0.0-beta.40",
    "@babel/preset-react": "7.0.0-beta.40",
    "@babel/preset-typescript": "7.0.0-beta.40",
    "@types/bluebird": "3.0.36",
    "@types/classnames": "0.0.30",
    "@types/core-js": "0.9.43",
    "@types/enzyme": "2.8.0",
    "@types/graphlib": "^2.1.3",
    "@types/history": "2.0.41",
    "@types/jasmine": "2.2.34",
    "@types/jquery": "2.0.34",
    "@types/jqueryui": "1.11.31",
    "@types/lodash": "4.14.55",
    "@types/node": "8.0.26",
    "@types/protobufjs": "5.0.31",
    "@types/react": "16.0.5",
    "@types/react-addons-test-utils": "0.14.19",
    "@types/react-dom": "15.5.1",
    "@types/react-redux": "5.0.10",
    "@types/react-router": "4.0.15",
    "@types/recompose": "0.23.3",
    "@types/redux": "3.5.30",
    "@types/redux-logger": "2.6.32",
    "@types/redux-thunk": "2.1.32",
    "@types/sinon": "2.3.7",
    "@types/uuid-js": "0.7.0",
    "@types/webpack-env": "1.13.0",
    "awesome-typescript-loader": "3.0.8",
    "babel-loader": "^8.0.0-beta.0",
    "enzyme": "2.7.1",
    "enzyme-to-json": "2.0.0",
    "exports-loader": "0.6.4",
    "imports-loader": "0.6.5",
    "jest": "21.1.0",
    "json-loader": "0.5.7",
    "less": "^2.3.1",
    "less-loader": "^4.0.6",
    "moment-timezone": "0.5.14",
    "react-addons-test-utils": "15.4.2",
    "react-contextmenu": "2.7.0",
    "redux-devtools-extension": "2.13.2",
    "redux-mock-store": "1.2.2",
    "redux-observable": "0.12.2",
    "sinon": "4.1.2",
    "tslint": "4.5.1",
    "tslint-eslint-rules": "3.4.0",
    "tslint-loader": "3.4.3",
    "typescript": "2.4.1",
    "webpack": "3.11.0",
    "webpack-dev-server": "2.11.1",
    "whatwg-fetch": "2.0.3"
  }
}

```
webpack.config.js

```
const path = require('path');
const webpack = require('webpack');
const LessHintPlugin = require(path.join(__dirname,'node_modules/cib-bento-ui-sources/tools/webpack/lesshint-plugin/webpack-lesshint.js'));
const merge = require('webpack-merge');
const babelLoader = require('./babelLoader');

module.exports = function(env) {
    const isDevelopment = env === 'development';
    // console.log(`This is a ${isDevelopment ? "development" : "production"} build`);
    
    const baseConfig = {
        entry: {
            'storm-settings-widget': './bundles/storm-settings-widget/ts/storm-settings-widget.ts'
        },
        output: {
            path: path.resolve(__dirname, 'dist'),
            publicPath: "/dist/",
            filename: "[name].bundle.js",
            sourceMapFilename: "[name].bundle.map",
            chunkFilename: "[id].[name].bundle.js",
            library: ["JPMMMacro", "[name]"],
            libraryTarget: "assign"
        },
        externals: {
            "coreservices":"(opener || window).top.MM_MESSAGING",
            "bluebird":"Promise",
            "eventEmitter":"EventEmitter",
            "jquery":"jQuery",
            "lodash":"_",
            "moment":"moment",
            "numeral":"numeral",
            "object-assign":"objectAssign",
            "react":"React",
            "react-dom":"ReactDOM",
            "redux":"Redux",
            "react-redux":"ReactRedux",
            "redux-logger":"reduxLogger",
            "redux-thunk":"ReduxThunk",
            "scriptjs":"$script",
            "uuid-js":"UUIDjs",
            "long":"dcodeIO['Long']",
            "bytebuffer":"dcodeIO['ByteBuffer']",
            "protobufjs":"dcodeIO['ProtoBuf']",
            "rxjs":"Rx"
        },
        resolve: {
            extensions: ['.ts', '.tsx', '.js', '.json'],
        },
        plugins: [
            new webpack.DefinePlugin({
                                     ENV_IS_DEVELOPMENT: isDevelopment,
                                     ENV_IS: JSON.stringify(env)
                                     }),
            new webpack.DefinePlugin({
                                     'process.env.NODE_ENV': JSON.stringify('development')
                                     })
        ],
        module: {
            rules: [{
                include: /(bundles)/,
                test: /\.(css|less)$/,
                use: [
                    { loader: 'style-loader' },
                    { loader: 'css-loader' },
                    { loader: 'less-loader' }
                ]
            }, {
                include: /(bundles)/,
                test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
                use: {
                    loader: 'file-loader',
                    options: {
                        name: 'assets/fonts/[name].[ext]'
                    }
                }
            }, {
                include: /(bundles)/,
                test: /\.(png|jpg|gif)?$/,
                use: {
                    loader: 'file-loader',
                    options: {
                        name: 'assets/[name].[ext]'
                    }
                }
            }]
        }
    };
    
    if (isDevelopment) {
        return merge(baseConfig, babelLoader, {
            devServer: {
                contentBase: [
                    path.resolve(__dirname, 'dist'),
                    path.resolve(__dirname, 'config'),
                    path.resolve(__dirname, 'node_modules/some-ui/development')
                ],
                watchContentBase: false,
                hotOnly: true,
                overlay: true,

                host: '0.0.0.0',
                port: 9000,
                proxy: {
                    "/Execution/Storm": {
                        target: 'http://localhost:9000',
                        pathRewrite: { '^/Execution/Storm' : '' }
                    }
                }
            },
            plugins: [
                new webpack.NamedModulesPlugin(),
                new webpack.HotModuleReplacementPlugin()
            ]
        });
    }

return merge(baseConfig, babelLoader);
}

```

.babelrc
```
{
    "presets": [
        "@babel/env",
        "@babel/react",
        "@babel/typescript"
    ],
    "plugins": [
        "@babel/proposal-class-properties",
        "@babel/proposal-object-rest-spread",
        "@babel/plugin-proposal-decorators"
    ]
}

```

babelLoader
```
module.exports = {
   module: {
      rules: [{
        test: /\.(tsx?)|(js)$/,
        include: /(bundles)/,
        use: {
           loader: 'babel-loader',
           options: {
              babelrc: true
           }
        }
     }]
   },
};

```

**Comment by nicolo-ribaudo** [comment]
Is there any other `.babelrc` file in the parent folders of your project?

**Comment by ahromyak** [comment]
same here. just trying to get all packages up to date  and somehow always got some mysterious errors.
anyway can someone help what is cousin  this error? i mean what conditions should be for this error to appear? i saw a lot of links in google people asking about this errors. and mostly fix is to get old version of packages. please help someone?

**Comment by nicolo-ribaudo** [comment]
This error happens when you use a plugin developed for Babel 6 with Babel 7. I suggest disabling your third-party plugins one-by-one to find which one isn't working and either update it to the latest version or open a PR/issue adding Babel 7 support.
