### ISSUE TITLE
traverse: Crash when a function expression contains a class declaration of the same name

### ISSUE THREAD

**Issue by rictic** [babel/babel#7483]
### Input Code

```js
const code = `
    (function Foo() {
      class Foo {};
    })
`;
const ast = babylon.parse(code);
babelTraverse(ast, {});
```

### Expected Behavior
This is legal JS. Inside the function expression, `Foo` should resolve to the class.

### Current Behavior

I get a crash with the following stacktrace:

<details><summary>Click to expand</summary>

```
     TypeError: Cannot read property 'file' of undefined
      at Scope.checkBlockScopedCollisions (node_modules/babel-traverse/lib/scope/index.js:398:22)
      at Scope.registerBinding (node_modules/babel-traverse/lib/scope/index.js:592:16)
      at Scope.registerDeclaration (node_modules/babel-traverse/lib/scope/index.js:499:12)
      at Object.BlockScoped (node_modules/babel-traverse/lib/scope/index.js:244:28)
      at Object.newFn (node_modules/babel-traverse/lib/visitors.js:318:17)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:44:14)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:103:17)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:190:19)
      at Function.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:115:19)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitSingle (node_modules/babel-traverse/lib/context.js:108:19)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:192:19)
      at Function.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:115:19)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitSingle (node_modules/babel-traverse/lib/context.js:108:19)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:192:19)
      at Function.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:115:19)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:103:17)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:190:19)
      at Function.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
      at traverse (node_modules/babel-traverse/lib/index.js:79:12)
      at NodePath.traverse (node_modules/babel-traverse/lib/path/index.js:144:25)
      at Scope._crawl (node_modules/babel-traverse/lib/scope/index.js:828:10)
      at Scope.crawl (node_modules/babel-traverse/lib/scope/index.js:749:10)
      at Scope.init (node_modules/babel-traverse/lib/scope/index.js:744:32)
      at NodePath.setScope (node_modules/babel-traverse/lib/path/context.js:151:30)
      at NodePath.setContext (node_modules/babel-traverse/lib/path/context.js:166:8)
      at NodePath.pushContext (node_modules/babel-traverse/lib/path/context.js:229:8)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:138:14)
      at TraversalContext.visitSingle (node_modules/babel-traverse/lib/context.js:108:19)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:192:19)
      at Function.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
      at Object.traverse [as default] (node_modules/babel-traverse/lib/index.js:79:12)
      at Object.<anonymous> (src/test/polymer/polymer2-mixin-scanner_test.ts:261:18)
      at Generator.next (<anonymous>)
      at lib/test/polymer/polymer2-mixin-scanner_test.js:20:71
      at new Promise (<anonymous>)
      at __awaiter (lib/test/polymer/polymer2-mixin-scanner_test.js:16:12)
      at Context.test.only (src/test/polymer/polymer2-mixin-scanner_test.ts:256:54)
```

</details>

### Possible Solution

The error appears to be in scope building. Doing `babelTraverse(ast, {noScope: true});` does not crash. Changing `Foo` in either location to something else also works.

It's specific to the combination of function expression and class declaration. None of the other combinations crash (function declaration + class declaration; function expression + class expression; function expression + class expression):

### Context

We're building a [static analyzer](https://github.com/Polymer/polymer-analyzer) and experimenting with using babel-traverse's scopes for dereferencing. It's a common pattern when writing an [ES6 class mixin](http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/) to name the inner class the same thing as the mixin function. e.g. this is what some of our real world code looks like:

```js
const MyMixin = mixinWrapper(function MyMixin(baseClass) {
  class MyMixin extends baseClass {
    myMixinMethod() { /* ... */ }
  };
  return MyMixin;
});

```

### Environment

| software         | version(s)
| ---------------- | -------
| Babylon          | 6.18.0
| babel-traverse          | 6.26.0
| node             | v9.2.1
| npm              |  5.6.0
| Operating System | MacOS 10.12.6

**Comment by nicolo-ribaudo** [comment]
Thank you for te bug report. It has been fixed in Babel 7: https://babeljs.io/repl/build/master#?babili=false&browsers=last%202%20chrome%20versions%2C%20last%202%20chromeandroid%20versions%2C%20firefox%20esr%2C%20last%202%20firefox%20versions%2C%20edge%20%3E%3D%2015%2C%20safari%20%3E%3D%2011&build=&builtIns=false&code_lz=BQMwrgdgxgLglgewgAgGIIcAlMg3gKGWSgBsBDAZwrQzwF8BufOrIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=&prettier=false&targets=&version=7.0.0-beta.40&envVersion=7.0.0-beta.40%2Bpr.7388

**Comment by rictic** [comment]
Oh great! I can confirm that it's fixed!
