### ISSUE TITLE
[7.0.0-beta.41] Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by sanex3339** [babel/babel#7572]
This is a bug report

After updating from `beta.40` on `beta.41` i got an error
```Module build failed: TypeError: [BABEL] /foobar/javascript-obfuscator/index.ts: Cannot read property 'slice' of undefined (While processing: "/foobar/node_modules/@babel/plugin-transform-runtime/lib/index.js")```

With `beta.40` everything is ok.

Full error log:
```
TypeError: [BABEL] test-tmp/index.js: Cannot read property 'slice' of undefined (While processing: "/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/@babel/plugin-transform-runtime/lib/index.js")
    at throwVersionError (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/@babel/helper-plugin-utils/lib/index.js:41:15)
    at Object.assertVersion (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/@babel/helper-plugin-utils/lib/index.js:11:11)
    at /Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/@babel/plugin-transform-runtime/lib/index.js:19:7
    at /Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/@babel/helper-plugin-utils/lib/index.js:16:12
    at /Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-core/lib/config/option-manager.js:238:14
    at cachedFunction (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-core/lib/config/caching.js:48:17)
    at loadPluginDescriptor (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-core/lib/config/option-manager.js:272:28)
    at /Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-core/lib/config/option-manager.js:56:14
    at Array.map (<anonymous>)
    at OptionManager.mergeOptions (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-core/lib/config/option-manager.js:55:34)
    at OptionManager.init (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-core/lib/config/option-manager.js:114:14)
    at manageOptions (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-core/lib/config/option-manager.js:40:30)
    at loadConfig (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-core/lib/config/index.js:17:37)
    at Object.transformFileSync (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-core/lib/transform-file-sync.js:20:36)
    at Object.compile (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-cli/lib/babel/util.js:71:18)
    at write (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-cli/lib/babel/dir.js:30:21)
    at handleFile (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-cli/lib/babel/dir.js:54:20)
    at /Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-cli/lib/babel/dir.js:78:9
    at Array.forEach (<anonymous>)
    at handle (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-cli/lib/babel/dir.js:75:56)
    at Array.forEach (<anonymous>)
    at _default (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-cli/lib/babel/dir.js:86:15)
    at Object.<anonymous> (/Users/sanex/PhpstormProjects/javascript-obfuscator/node_modules/babel-cli/lib/babel/index.js:185:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
```

### Input Code
Huge project, can't extract place that triggering this error

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "generatorOpts": {
    "retainFunctionParens": true
  },
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "node": "4.8"
      },
      "forceAllTransforms": true
    }]
  ],
  "plugins": [
    "@babel/transform-runtime"
  ]
}
```

### Expected Behavior
No error

### Current Behavior
Error described above

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.41
| node             | 9.1.0
| Operating System | MacOs

**Comment by kuby** [comment]
Are you able to install all the subdependencies? I am having trouble with that, it looks like the submodules for this version `beta.41` are not published. I have the registry set to the `https://registry.npmjs.org/` so that cannot be the problem.

If I do for example this: `npm install babel-traverse@7.0.0-beta.41` it fails to install it with error: 
`No matching version found for babel-traverse@7.0.0-beta.41`.

All these packages are failing:
```
"@babel/code-frame": "7.0.0-beta.41",
"@babel/generator": "7.0.0-beta.41",
"@babel/helpers": "7.0.0-beta.41",
"@babel/template": "7.0.0-beta.41",
"@babel/traverse": "7.0.0-beta.41",
"@babel/types": "7.0.0-beta.41",
"babylon": "7.0.0-beta.41",
```

**Comment by existentialism** [comment]
@sanex3339 can you verify all your @babel-related deps are on the same version? beta.41 introduced a way for plugins to check/assert the version of babel they're being used with, and this error you're seeing may mean your @babel/core version is mismatched since `helper-plugin-utils` is [erroring while trying to check the version](https://github.com/babel/babel/blob/master/packages/babel-helper-plugin-utils/src/index.js#L37).

**Comment by hzoo** [comment]
Also would be helpful to have a repo/reproduction step, otherwise need to figure it out from the stack trace.

**Comment by loganfsmyth** [comment]
If you can just push a branch with the broken setup and tell me what command to run, I'd be happy to look into this more.

**Comment by sanex3339** [comment]
thank you. Now it conflicting with `awesome-typescript-loader` (which trying to load 6.26.0 version) but this is not related with this.

**Comment by oliviertassinari** [comment]
@loganfsmyth I'm [trying to upgrade](https://github.com/mui-org/material-ui/pull/10964) to Babel 7 on Material-UI.
I'm facing the same error:

> Error: TypeError: Cannot read property 'slice' of undefined
    at /Users/oliviertassinari/material-ui-next/node_modules/@babel/cli/lib/babel/dir.js:146:15

The error is coming from this line.

https://github.com/babel/babel/blob/d260bfaec47f1c34933ff2abdf1fd4ffded4875d/packages/babel-helper-plugin-utils/src/index.js#L64

For some reason `api.version` is undefined.
https://github.com/babel/babel/blob/d260bfaec47f1c34933ff2abdf1fd4ffded4875d/packages/babel-helper-plugin-utils/src/index.js#L8
I'm digging more

**Comment by loganfsmyth** [comment]
@oliviertassinari Alright, let us know how it does. As far as I know, the fix I landed should be all set in https://github.com/babel/babel/pull/7580 should have addressed this. If you're still seeing it, definitely look closely at what object is passed where and what the prototype object is.
