### ISSUE TITLE
@babel/core can't be installed 

### ISSUE THREAD

**Issue by ychow** [babel/babel#7594]
Bug
i used ` npm install --save-dev  @babel/core`

but get this: 
```
npm WARN babel-jest@22.4.1 requires a peer of babel-core@^6.0.0 || ^7.0.0-0 but none was installed.
npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react@>15 <16 but none was installed.
npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react-dom@>15 <16 but none was installed.
npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react-addons-transition-group@^15.0.0 but none was installed.
npm WARN @antv/g2-plugin-slider@2.0.1 requires a peer of @antv/g2@>=3.0.0 but none was installed.
npm WARN react-router-redux@5.0.0-alpha.6 requires a peer of react@^15 but none was installed.
npm WARN react-fittext@1.0.0 requires a peer of react@^15.0.0 but none was installed.
npm WARN react-fittext@1.0.0 requires a peer of react-dom@^15.0.0 but none was installed.
npm WARN @babel/plugin-proposal-export-default@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32 but none was installed.
npm WARN @babel/plugin-proposal-export-namespace@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32 but none was installed.
npm WARN @babel/plugin-syntax-export-extensions@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32 but none was installed.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
npm WARN eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 but none was installed.
npm WARN ts-jest-babel-7@22.0.7 requires a peer of typescript@2.x but none was installed.
npm WARN ts-jest-babel-7@22.0.7 requires a peer of babel-core@^6.0.0 || ^7.0.0-0 but none was installed.

npm ERR! Cannot read property '0' of undefined

┌─────────────────────────────────────────────────────────────────┐
│                     npm update check failed                     │
│               Try running with sudo or get access               │
│              to the local update config store via               │
│ sudo chown -R $USER:$(id -gn $USER) /Users/xiaoyuanzhou/.config │
└─────────────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiaoyuanzhou/.npm/_logs/2018-03-19T02_06_57_598Z-debug.log
```

debug.log: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/bin/node',
1 verbose cli   '/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   '@babel/core' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose npm-session 3fbb9bd9e1b8d519
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@babel%2fcore 1060ms (from cache)
8 silly pacote range manifest for @babel/core@^7.0.0-beta.40 fetched in 1206ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @babel/core@7.0.0-beta.42 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/convert-source-map 609ms (from cache)
15 http fetch GET 304 https://registry.npmjs.org/json5 608ms (from cache)
16 http fetch GET 304 https://registry.npmjs.org/debug 611ms (from cache)
17 http fetch GET 304 https://registry.npmjs.org/babylon 613ms (from cache)
18 silly pacote range manifest for convert-source-map@^1.1.0 fetched in 616ms
19 silly resolveWithNewModule convert-source-map@1.5.1 checking installable status
20 silly pacote range manifest for json5@^0.5.0 fetched in 616ms
21 silly resolveWithNewModule json5@0.5.1 checking installable status
22 silly pacote range manifest for debug@^3.1.0 fetched in 618ms
23 silly resolveWithNewModule debug@3.1.0 checking installable status
24 silly pacote version manifest for babylon@7.0.0-beta.42 fetched in 622ms
25 silly resolveWithNewModule babylon@7.0.0-beta.42 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/@babel%2ftypes 749ms (from cache)
```

**Comment by loganfsmyth** [comment]
Maybe try with `npm install --save-dev @babel/core --verbose`? Unfortunately the error isn't specific enough to narrow anything down.

**Comment by ychow** [comment]
@loganfsmyth  i try with `npm install --save-dev @babel/core --verbose` . Unfortunately still the error.

get this: 
```
npm info it worked if it ends with ok
npm verb cli [ '/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/bin/node',
npm verb cli   '/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/bin/npm',
npm verb cli   'install',
npm verb cli   '--save-dev',
npm verb cli   '@babel/core',
npm verb cli   '--verbose' ]
npm info using npm@5.3.0
npm info using node@v8.6.0
npm verb npm-session 5965d9cc2a19abec
npm http fetch GET 304 https://registry.npmjs.org/@babel%2fcore 1573ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/convert-source-map 602ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/babylon 604ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/debug 630ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/json5 633ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2fcode-frame 731ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2fgenerator 792ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/micromatch 202ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/resolve 209ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 208ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/source-map 207ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2ftypes 1189ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2fhelpers 1221ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2ftraverse 1222ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2ftemplate 1225ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2fhighlight 788ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/esutils 191ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chalk 195ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-styles 184ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 198ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/supports-color 203ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-convert 188ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/color-name 195ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-flag 190ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/trim-right 198ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/jsesc 200ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/to-fast-properties 188ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/invariant 196ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/globals 200ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2fhelper-function-name 720ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@babel%2fhelper-get-function-arity 758ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ms 188ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/arr-diff 225ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/filename-regex 229ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-brackets 240ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/extglob 240ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/braces 245ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/array-unique 246ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-glob 254ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-extglob 256ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/kind-of 258ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/normalize-path 268ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/object.omit 204ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/regex-cache 193ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/parse-glob 206ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/arr-flatten 313ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/preserve 205ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/expand-range 207ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/repeat-element 207ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fill-range 201ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/randomatic 190ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isobject 204ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-number 206ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/repeat-string 207ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-buffer 188ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 189ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-posix-bracket 189ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/remove-trailing-separator 190ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-extendable 193ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/for-own 197ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/for-in 191ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/glob-base 188ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-dotfile 191ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/glob-parent 189ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-equal-shallow 200ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-primitive 192ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/path-parse 193ms (from cache)
npm verb correctMkdir /Users/xiaoyuanzhou/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/xiaoyuanzhou/.npm/_locks/staging-e79e651e5cb63b4f.lock for /Users/xiaoyuanzhou/Desktop/muyuanTest/my-frontend-ant/node_modules/.staging
npm info lifecycle undefined~preuninstall: undefined
npm info lifecycle undefined~uninstall: undefined
npm verb unlock done using /Users/xiaoyuanzhou/.npm/_locks/staging-e79e651e5cb63b4f.lock for /Users/xiaoyuanzhou/Desktop/muyuanTest/my-frontend-ant/node_modules/.staging
npm WARN babel-jest@22.4.1 requires a peer of babel-core@^6.0.0 || ^7.0.0-0 but none was installed.
npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react@>15 <16 but none was installed.
npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react-dom@>15 <16 but none was installed.
npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react-addons-transition-group@^15.0.0 but none was installed.
npm WARN @antv/g2-plugin-slider@2.0.1 requires a peer of @antv/g2@>=3.0.0 but none was installed.
npm WARN react-router-redux@5.0.0-alpha.6 requires a peer of react@^15 but none was installed.
npm WARN react-fittext@1.0.0 requires a peer of react@^15.0.0 but none was installed.
npm WARN react-fittext@1.0.0 requires a peer of react-dom@^15.0.0 but none was installed.
npm WARN @babel/plugin-proposal-export-default@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32 but none was installed.
npm WARN @babel/plugin-proposal-export-namespace@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32 but none was installed.
npm WARN @babel/plugin-syntax-export-extensions@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32 but none was installed.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
npm WARN eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 but none was installed.
npm WARN ts-jest-babel-7@22.0.7 requires a peer of typescript@2.x but none was installed.
npm WARN ts-jest-babel-7@22.0.7 requires a peer of babel-core@^6.0.0 || ^7.0.0-0 but none was installed.

npm verb stack TypeError: Cannot read property '0' of undefined
npm verb stack     at rmStuff (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/unbuild.js:61:24)
npm verb stack     at tryCatcher (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at ret (eval at makeNodePromisifiedEval (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
npm verb stack     at lifecycle.then.then (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
npm verb stack     at tryCatcher (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:781:20)
npm verb stack     at tryOnImmediate (timers.js:743:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
npm verb cwd /Users/xiaoyuanzhou/Desktop/muyuanTest/my-frontend-ant
npm verb Darwin 16.6.0
npm verb argv "/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/bin/node" "/Users/xiaoyuanzhou/.nvm/versions/node/v8.6.0/bin/npm" "install" "--save-dev" "@babel/core" "--verbose"
npm verb node v8.6.0
npm verb npm  v5.3.0
npm ERR! Cannot read property '0' of undefined
npm verb exit [ 1, true ]

┌─────────────────────────────────────────────────────────────────┐
│                     npm update check failed                     │
│               Try running with sudo or get access               │
│              to the local update config store via               │
│ sudo chown -R $USER:$(id -gn $USER) /Users/xiaoyuanzhou/.config │
└─────────────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiaoyuanzhou/.npm/_logs/2018-03-19T03_53_26_126Z-debug.log
```

**Comment by loganfsmyth** [comment]
This appears to be an `npm` issue that was fixed in later versions: https://github.com/npm/npm/issues/17858#issuecomment-350189251
