### ISSUE TITLE
Error: Cannot find module './undefined.js'

### ISSUE THREAD

**Issue by SiwakornS** [babel/babel#7603]
### Error
```
<img width="1424" alt="screen shot 2561-03-21 at 00 10 39" src="https://user-images.githubusercontent.com/37061959/37670986-4751534c-2c9d-11e8-852e-27b749e8f082.png">

Error: Cannot find module './undefined.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/siwakornsittilerdpaisal/Desktop/Project/ZeeZcore-backend/config/environment/index.js:58:74)
    at Module._compile (module.js:635:30)
    at Module._compile (/Users/siwakornsittilerdpaisal/Desktop/Project/ZeeZcore-backend/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:646:10)
    at Object.newLoader [as .js] (/Users/siwakornsittilerdpaisal/Desktop/Project/ZeeZcore-backend/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```
### Input Code

```
"use strict";

const env = process.env.NODE_ENV || "development";

if (env === "development" || env === "test") {
  // Register the Babel require hook
  require("@babel/register");
}

```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "debug": true,
                "targets": {
                    "node": "8.9.0"
                }
            }
        ]
    ]
}
```

### package.json
    "@babel/core": "^7.0.0-beta.42",
    "@babel/preset-env": "^7.0.0-beta.42",
    "@babel/register": "^7.0.0-beta.42",
    

<img width="1424" alt="screen shot 2561-03-21 at 00 10 39" src="https://user-images.githubusercontent.com/37061959/37671026-59813bfe-2c9d-11e8-880a-0beb15e8f044.png">

**Comment by loganfsmyth** [comment]
This doesn't seem babel-related to me. That says the `environment/index.js` file is importing `./undefined.js` and it doesn't exist.
