### ISSUE TITLE
Browserlist 3.2.2 breaks master

### ISSUE THREAD

**Issue by jridgewell** [babel/babel#7624]
```
  ● babel-preset-env/preset options › browserslist package

    BrowserslistError: [BABEL] /Users/jridgewell/src/babel/packages/babel-preset-env/test/fixtures/preset-options/browserslist-package/input.mjs: Browserslist config should contain array of strings with browser queries (While processing: "/Users/jridgewell/src/babel/packages/babel-preset-env/lib/index.js")

      112 |   if (queryIsValid || !options.ignoreBrowserslistConfig) {
      113 |     _browserslist.default.defaults = (0, _normalizeOptions.objectToBrowserslist)(targets);
    > 114 |     const browsers = (0, _browserslist.default)(browsersquery, {
      115 |       path: options.configPath
      116 |     });
      117 |     const queryBrowsers = getLowestVersions(browsers);

      at check (packages/babel-preset-env/node_modules/browserslist/node.js:54:11)
      at parsePackage (packages/babel-preset-env/node_modules/browserslist/node.js:92:5)
      at packages/babel-preset-env/node_modules/browserslist/node.js:226:29
      at eachParent (packages/babel-preset-env/node_modules/browserslist/node.js:46:18)
      at Object.findConfig (packages/babel-preset-env/node_modules/browserslist/node.js:218:20)
      at Function.loadConfig (packages/babel-preset-env/node_modules/browserslist/node.js:149:37)
      at browserslist (packages/babel-preset-env/node_modules/browserslist/index.js:187:31)
      at getTargets (packages/babel-preset-env/lib/targets-parser.js:114:48)
      at Object.<anonymous>._default (packages/babel-preset-env/lib/index.js:167:46)
      at packages/babel-helper-plugin-utils/lib/index.js:19:12
```

**Comment by jridgewell** [comment]
It's a breaking change in browserslist, opened https://github.com/browserslist/browserslist/issues/240.

**Comment by ai** [comment]
To fix it fast replace string to the array. Unfortunately, I am walking at Long Island City and will be able to release a fix only after a few hours.

**Comment by loganfsmyth** [comment]
Thanks!
