### ISSUE TITLE
@babel/traverse/lib/path/evaluation.js shipped with `**` use causing test fails in Node 6

### ISSUE THREAD

**Issue by jdalton** [babel/babel#7654]
It looks like the line [here](https://github.com/babel/babel/blob/v7.0.0-beta.43/packages/babel-traverse/src/path/evaluation.js#L309) is tripping up Node 6 because it failed to translate its use of `**` to something Node 6 can understand.

In [`@babel/traverse@7.0.0-beta.42`](https://unpkg.com/@babel/traverse@7.0.0-beta.42/lib/path/evaluation.js) it was
```js
return Math.pow(_left, _right);
```
In [`@babel/traverse@7.0.0-beta.43`](https://unpkg.com/@babel/traverse@7.0.0-beta.43/lib/path/evaluation.js) it is
```js
return left ** right;
```

**Comment by jdalton** [comment]
You can see it in the raw source [here](https://unpkg.com/@babel/traverse@7.0.0-beta.43/lib/path/evaluation.js). Search for `left ** right`

**Comment by jdalton** [comment]
In [`@babel/traverse@7.0.0-beta.42`](https://unpkg.com/@babel/traverse@7.0.0-beta.42/lib/path/evaluation.js) it was
```js
return Math.pow(_left, _right);
```
In [`@babel/traverse@7.0.0-beta.42`](https://unpkg.com/@babel/traverse@7.0.0-beta.43/lib/path/evaluation.js) it is
```js
return left ** right;
```

**Comment by jcomplex** [comment]
Is there a workaround in the meantime or ETA on a fix?  I am also running into this issue.

**Comment by jdalton** [comment]
Hi @jcomplex!

> Is there a workaround in the meantime or ETA on a fix? I am also running into this issue.

You may be able to workaround the issue by pinning your Babel deps to 7.0.0-beta.42 until the issue is resolved.

**Comment by hzoo** [comment]
Yeah we recommend you don't use `^` with Babel 7 (mostly because of breaking changes until RC but also since there could be a regression).

**Comment by aswinramakrish** [comment]
I get this when I create a new `react-native` application. `react-native-cli` basically fails because of this issue.

Here is what I get -

    /node_modules/@babel/traverse/lib/path/evaluation.js:299`
             return left ** right;
     
     SyntaxError: Unexpected token *
       at Object.exports.runInThisContext (vm.js:76:16)
       at Module._compile (module.js:542:28)
       at Module._extensions..js (module.js:579:10)
       at Object.require.extensions.(anonymous function) [as .js] 
     (/node_modules/babel-register/lib/node.js:152:7)
       at Module.load (module.js:487:32)
       at tryModuleLoad (module.js:446:12)
       at Function.Module._load (module.js:438:3)
       at Module.require (module.js:497:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (/node_modules/@babel/traverse/lib/path/index.js:62:51)

**Comment by jdalton** [comment]
Thanks @existentialism, @hzoo, and @loganfsmyth!

**Comment by loganfsmyth** [comment]
@aswinramakrish I'll be pushing out a fix soon, but I'll also repeat what @hzoo said. Using `^` or `~` on Babel's beta is a bad idea, so anything that breaks due to this bad publish should taking it as a reminder that this is very much still beta, and you should be locking down your versions.

**Comment by aswinramakrish** [comment]
It looks like it's a dependency of `metro` bundler, which explains why every `react-native-cli` command fails. 

![screen shot 2018-04-02 at 3 43 00 pm](https://user-images.githubusercontent.com/1799620/38217846-fd0c0f9e-368c-11e8-8931-9c54b997cdbe.png)

For time being, I had to downgrade the `react-native` version from `0.54.4` to `0.52.2`

Had to do something like - `react-native init HelloWorld --version react-native@0.52.2`. Hope this helps someone.

**Comment by hzoo** [comment]
When did metro start using v7? Also we are trying to do a new publish now.

**Comment by brokentone** [comment]
We just hit this issue and started rabbit holeing today. Might I ask that this issue stay open until the regression fix is published?

**Comment by loganfsmyth** [comment]
@brokentone Yup! Just got auto-closed because it was linked in the related fix, sorry.

**Comment by brokentone** [comment]
@loganfsmyth Thanks for the reopen and the fix/republish @hzoo etc
