### ISSUE TITLE
TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by YaStasya** [babel/babel#7664]
Hello. I have here such an error. How can it be solved and what is it related to?
> C:\Users\Пользователь\WebstormProjects\untitled>babel-node server/app.js
> C:\Users\Пользователь\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transformation\file\options\option-mana
> ger.js:126
>       if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
>                             ^
> 
> TypeError: Cannot read property 'error' of undefined
>     at OptionManager.mergeOptions (C:\Users\Пользователь\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\tran
> sformation\file\options\option-manager.js:126:29)
>     at OptionManager.addConfig (C:\Users\Пользователь\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transfo
> rmation\file\options\option-manager.js:107:10)
>     at OptionManager.findConfigs (C:\Users\Пользователь\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\trans
> formation\file\options\option-manager.js:168:35)
>     at OptionManager.init (C:\Users\Пользователь\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transformati
> on\file\options\option-manager.js:229:12)
>     at compile (C:\Users\Пользователь\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\api\register\node.js:11
> 7:22)
>     at normalLoader (C:\Users\Пользователь\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\api\register\node.
> js:199:14)
>     at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Пользователь\AppData\Roaming\npm\node_modules\babel\nod
> e_modules\babel-core\lib\api\register\node.js:216:7)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)

My .babelrc

> {
>   "presets": ["react", "es2015"]
> }

 and package.json

> "dependencies": {
>     "axios": "^0.18.0",
>     "babel": "^6.23.0",
>     "babel-core": "^6.26.0",
>     "babel-plugin-transform-class-properties": "^6.24.1",
>     "babel-preset-env": "^1.6.1",
>     "babel-preset-flow": "^6.23.0",
>     "babel-preset-react": "^6.24.1",
>     "body-parser": "^1.18.2",
>     "create-react-class": "^15.6.3",
>     "events": "^2.0.0",
>     "file-loader": "^1.1.11",
>     "flux": "^3.1.3",
>     "fly-babel": "^2.1.1",
>     "json-loader": "^0.5.7",
>     "keymirror": "^0.1.1",
>     "mongodb": "^3.0.5",
>     "mongoose": "^5.0.12",
>     "react": "^16.3.0",
>     "react-dom": "^16.3.0",
>     "react-hot-loader": "^4.0.1",
>     "react-transform": "0.0.3",
>     "url-loader": "^1.0.1",
>     "webpack-cli": "^2.0.13"
>   },
>   "devDependencies": {
>     "babel-cli": "^6.26.0",
>     "babel-loader": "^7.1.4",
>     "babel-preset-es2015": "^6.24.1",
>     "css-loader": "^0.22.0",
>     "express": "^4.14.0",
>     "webpack": "^4.4.1",
>     "webpack-dev-server": "^3.1.1"
>   }
>

**Comment by YaStasya** [comment]
The issue is solved by deleting / installing / resetting the babel
