### ISSUE TITLE
babel-node error

### ISSUE THREAD

**Issue by AK-Bharath** [babel/babel#7695]
Hi All,

I get the following error when I run babel-node node/react-render.jsx

[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
[object Object]
    at Object.isSpreadProperty (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/generated/index.js:1271:11)
    at hasSpread (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:185:19)
/usr/local/lib/node_modules/@babel/core/node_modules/@babel/template/lib/builder.js:88
      throw err;
      ^

Error: Unknown substitution "BODY" given
    at /usr/local/lib/node_modules/@babel/core/node_modules/@babel/template/lib/populate.js:32:15
    at Array.forEach (<anonymous>)
    at populatePlaceholders (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/template/lib/populate.js:30:31)
    at /usr/local/lib/node_modules/@babel/core/node_modules/@babel/template/lib/string.js:22:51
    at /usr/local/lib/node_modules/@babel/core/node_modules/@babel/template/lib/builder.js:85:14
    at spec (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-es2015-for-of/lib/index.js:159:20)
    at PluginPass.ForOfStatement (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-es2015-for-of/lib/index.js:72:21)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    =============
    at exports.default (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-es2015-for-of/lib/index.js:11:20)
    at /usr/local/lib/node_modules/@babel/core/lib/config/full.js:172:14
    at cachedFunction (/usr/local/lib/node_modules/@babel/core/lib/config/caching.js:42:17)
    at loadPluginDescriptor (/usr/local/lib/node_modules/@babel/core/lib/config/full.js:207:28)
    at /usr/local/lib/node_modules/@babel/core/lib/config/full.js:64:16
    at Array.map (<anonymous>)
    at recurseDescriptors (/usr/local/lib/node_modules/@babel/core/lib/config/full.js:63:36)
    at recurseDescriptors (/usr/local/lib/node_modules/@babel/core/lib/config/full.js:97:26)

I don't know whether it is babel issue or it is an issue with our code.  Please help me.

babelrc file contents

{
  "presets": [
    "react",
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "ie >= 11"],
        "node": "current"
      }
    }]
  ],

  "plugins": [
    "transform-decorators-legacy",
    "transform-optional-chaining",
    "transform-object-rest-spread"
  ]
}

package.json contents

"devDependencies": {
    "@babel/cli": "^7.0.0-beta.44",
    "@babel/core": "^7.0.0-beta.44",
    "@babel/node": "^7.0.0-beta.44",
    "@babel/register": "^7.0.0-beta.44",
    "babel-cli": "^7.0.0-beta.3",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^6.1.2",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-optional-chaining": "^7.0.0-beta.3",
    "babel-preset-env": "^2.0.0-beta.2",
    "babel-preset-react": "^7.0.0-beta.3",
    "babel-preset-stage-3": "^6.24.1",
    "babel-register": "^7.0.0-beta.3",
    "cssmin": "^0.4.3",
    "eslint": "^3.11.1",
    "eslint-plugin-react": "^6.8.0",
    "uglify": "^0.1.5"
  },
  "scripts": {
    "start": "concurrently --no-color \"npm run pack\" \"npm run django\" \"npm run render\"",
    "partial-start": "concurrently --no-color \"npm run pack\" \"npm run render\"",
    "start-prod": "concurrently --no-color \"uwsgi --ini /home/ntdl/code/uwsgi.ini\" \"nginx\" \"npm run render-prod\"",
    "pack": "webpack --watch --config node/webpack/webpack.config.js",
    "pack-prod": "webpack --config node/webpack/webpack.production.config.js",
    "django": "python manage.py runserver",
    "render": "babel-node node/react-render.jsx --watch",
    "render-prod": "babel-node node/react-render.jsx",
    "pylint": "pylint ntdl cms search",
    "eslint": "eslint static/style/style.js && eslint --ext .jsx search",
    "lint": "npm run pylint && npm run eslint",
    "es-index": "babel-node elasticsearch/index/create.js",
    "migratedb": "python manage.py migrate"
  },
  "dependencies": {
    "autobind-decorator": "^2.1.0",
    "babel-eslint": "^6.1.2",
    "babel-polyfill": "^6.23.0",
    "body-parser": "^1.17.2",
    "coffeescript": "^2.2.4",
    "concurrently": "^3.5.0",
    "elasticsearch": "^12.1.3",
    "express": "^4.15.4",
    "graceful-fs": "^4.1.11",
    "history": "^4.7.2",
    "material-ui": "^0.16.7",
    "minimatch": "^3.0.4",
    "node-sass": "^3.13.0",
    "openseadragon": "^2.3.0",
    "pdfjs-dist": "^1.8.492",
    "query-string": "^5.0.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.6",
    "react-render": "^1.2.1",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.6",
    "react-tap-event-plugin": "^2.0.1",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "request": "2.79.0",
    "webpack": "^3.5.5",
    "webpack-bundle-tracker": "0.1.0",
    "yargs": "^6.6.0"
  }
enviroment 

Linux ubuntu on aws.

With Many thanks,
Bharath AK

Choose one: is this a bug report or feature request?

### Input Code

```js
var your => (code) => here;
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by loganfsmyth** [comment]
```
"babel-plugin-transform-object-rest-spread": "^6.26.0",
```
should match the over 7.x versions, e.g.
```
"babel-plugin-transform-object-rest-spread": "^7.0.0-beta.44",
```

**Comment by AK-Bharath** [comment]
Hi Logan,

I had updated to version 7.0.0-beta.3

"babel-plugin-transform-object-rest-spread":7.0.0-beta.3
currently my package.json is 
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.3",
    "@babel/core": "^7.0.0-beta.3",
    "@babel/node": "^7.0.0-beta.3",
    "@babel/register": "^7.0.0-beta.3",
    "babel-cli": "^7.0.0-beta.3",
    "babel-core": "^7.0.0-beta.3",
    "babel-eslint": "^6.1.2",
    "babel-loader": "^7.0.0-beta.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-rest-spread": "^7.0.0-beta.3",
    "babel-plugin-transform-optional-chaining": "^7.0.0-beta.3",
    "babel-preset-env": "^2.0.0-beta.2",
    "babel-preset-react": "^7.0.0-beta.3",
    "babel-preset-stage-3": "^7.0.0-beta.3",
    "babel-register": "^7.0.0-beta.3",
    "cssmin": "^0.4.3",
    "eslint": "^3.11.1",
    "eslint-plugin-react": "^6.8.0",
    "uglify": "^0.1.5"
  },
  "scripts": {
    "start": "concurrently --no-color \"npm run pack\" \"npm run django\" \"npm run render\"",
    "partial-start": "concurrently --no-color \"npm run pack\" \"npm run render\"",
    "start-prod": "concurrently --no-color \"uwsgi --ini /home/ntdl/code/uwsgi.ini\" \"nginx\" \"npm run render-prod\"",
    "pack": "webpack --watch --config node/webpack/webpack.config.js",
    "pack-prod": "webpack --config node/webpack/webpack.production.config.js",
    "django": "python manage.py runserver",
    "render": "babel-node node/react-render.jsx --watch",
    "render-prod": "babel-node node/react-render.jsx",
    "pylint": "pylint ntdl cms search",
    "eslint": "eslint static/style/style.js && eslint --ext .jsx search",
    "lint": "npm run pylint && npm run eslint",
    "es-index": "babel-node elasticsearch/index/create.js",
    "migratedb": "python manage.py migrate"
  },
  "dependencies": {
    "autobind-decorator": "^2.1.0",
    "babel-eslint": "^6.1.2",
    "babel-polyfill": "^6.23.0",
    "body-parser": "^1.17.2",
    "coffeescript": "^2.2.4",
    "concurrently": "^3.5.0",
    "elasticsearch": "^12.1.3",
    "express": "^4.15.4",
    "graceful-fs": "^4.1.11",
    "history": "^4.7.2",
    "material-ui": "^0.16.7",
    "minimatch": "^3.0.4",
    "node-sass": "^3.13.0",
    "openseadragon": "^2.3.0",
    "pdfjs-dist": "^1.8.492",
    "query-string": "^5.0.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.6",
    "react-render": "^1.2.1",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.6",
    "react-tap-event-plugin": "^2.0.1",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "request": "2.79.0",
    "webpack": "^3.5.5",
    "webpack-bundle-tracker": "0.1.0",
    "yargs": "^6.6.0"
  }


Please find the errors below

/usr/local/lib/node_modules/@babel/core/node_modules/@babel/template/lib/builder.js:88
      throw err;
      ^

Error: Unknown substitution "BODY" given
    at /usr/local/lib/node_modules/@babel/core/node_modules/@babel/template/lib/populate.js:32:15
    at Array.forEach (<anonymous>)
    at populatePlaceholders (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/template/lib/populate.js:30:31)
    at /usr/local/lib/node_modules/@babel/core/node_modules/@babel/template/lib/string.js:22:51
    at /usr/local/lib/node_modules/@babel/core/node_modules/@babel/template/lib/builder.js:85:14
    at spec (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-es2015-for-of/lib/index.js:159:20)
    at PluginPass.ForOfStatement (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-es2015-for-of/lib/index.js:72:21)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    =============
    at exports.default (/home/ubuntu/workarea/sourcecode/ntdl/node_modules/babel-plugin-transform-es2015-for-of/lib/index.js:11:20)
    at /usr/local/lib/node_modules/@babel/core/lib/config/full.js:172:14
    at cachedFunction (/usr/local/lib/node_modules/@babel/core/lib/config/caching.js:42:17)
    at loadPluginDescriptor (/usr/local/lib/node_modules/@babel/core/lib/config/full.js:207:28)
    at /usr/local/lib/node_modules/@babel/core/lib/config/full.js:64:16
    at Array.map (<anonymous>)
    at recurseDescriptors (/usr/local/lib/node_modules/@babel/core/lib/config/full.js:63:36)
    at recurseDescriptors (/usr/local/lib/node_modules/@babel/core/lib/config/full.js:97:26)

still I get the same error.  I don't know whether it is due to my code?

correct me if I am wrong.

With Many thanks,
Bharath AK

**Comment by AK-Bharath** [comment]
I had tried cleaning the npm cache, removed node_modules folder then npm install, still I face the issue.  Please help me what would be the problem. 
With Many Thanks,
Bharath AK

**Comment by AK-Bharath** [comment]
Hi logan,
I had installed @babel/plugin-proposal-object-rest-spread,  But after installation of that package it say babel-plugin-transform-object-rest-spread not found error.  Please suggest what needs to be done.

With Many thanks,
Bharath AK

**Comment by drjayvee** [comment]
@AK-Bharath I ran into the same error. My project now works with these dependencies:
```
    "@babel/core": "^7.0.0-beta.44",
    "@babel/cli": "^7.0.0-beta.44",
    "@babel/polyfill": "^7.0.0-beta.44",
    "@babel/preset-env": "^7.0.0-beta.44",
    "babel-loader": "^8.0.0-beta.2",
    "babel-minify-webpack-plugin": "^0.3.1",
    "grunt": "^1.0.0",
    "grunt-babel": "^8.0.0-beta.0",
```
Since I'm using babel-preset-env, I also had to change `.babelrc.js`:
```
--- a/.babelrc.js
+++ b/.babelrc.js
@@ -2,7 +2,7 @@

 module.exports = {
    "presets": [
-       ["env", {
+       ["@babel/env", {
            "debug": true,
            "modules": false,
            "targets": {
```
Hope that helps!

**Comment by loganfsmyth** [comment]
@AK-Bharath You also need to adjust your babelrc to account for the new name.

**Comment by AK-Bharath** [comment]
Hi Logan,

      Thanks for your help.   The problem is now resolved.  

Regards,
Bharath AK
