### ISSUE TITLE
Object's destructuring assignment crashes babel on assertion if there is a nested Rest Element

### ISSUE THREAD

**Issue by awto** [babel/babel#7710]
If object destructing assignment contains some nested object or array with rest element babel crashes somewhere in `@babel/plugin-proposal-object-rest-spread`. 

For variable declarations and parameters works fine, only crashes on assignment expression.

Here are the minimal examples: 

```js
({i: {...j}} = k);
```

or 

```js
({i: [...j]} = k);
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

package.json:
```js
{
  "dependencies": {
    "@babel/cli": "^7.0.0-beta.44",
    "@babel/core": "^7.0.0-beta.44",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.44"
  }
}
```

Running with "@babel/cli":
```
$ babel --plugins=@babel/plugin-proposal-object-rest-spread index.js
```

No .babelrc

### Expected Behavior

Transpiled source or at least a meaningful error report.

### Current Behavior

Crash on assert.

```
Error: Expected type "RestElement" with option {}, but instead got "ObjectProperty".
    at assert (/private/var/tmp/node_modules/@babel/types/lib/asserts/generated/index.js:265:11)
    at Object.assertRestElement (/private/var/tmp/node_modules/@babel/types/lib/asserts/generated/index.js:554:3)
    at createObjectSpread (/private/var/tmp/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js:170:19)
    at PluginPass.AssignmentExpression (/private/var/tmp/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js:319:38)
    at newFn (/private/var/tmp/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/private/var/tmp/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/private/var/tmp/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/private/var/tmp/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/private/var/tmp/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/private/var/tmp/node_modules/@babel/traverse/lib/context.js:104:19)
```

**Comment by JLHwung** [comment]
This issue could not be reproduced at [REPL](https://babeljs.io/repl#?babili=false&browsers=ie%20<%3D%2011%2C%0Anot%20op_mini%20all&build=&builtIns=false&spec=false&loose=false&code_lz=BQbwlgXABCB08CsC-SoF4oGsCUBuAUKJFANrywIC6qGOuQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.6.0&externalPlugins=%40babel%2Fplugin-proposal-export-default-from%407.5.2) and according to [Babel AST Explorer](https://lihautan.com/babel-ast-explorer/#?eyJiYWJlbFNldHRpbmdzIjp7InZlcnNpb24iOiI3LjIuMCJ9LCJ0cmVlU2V0dGluZ3MiOnsiaGlkZUVtcHR5Ijp0cnVlLCJoaWRlTG9jYXRpb24iOnRydWUsImhpZGVUeXBlIjp0cnVlfSwiY29kZSI6Iih7aTogey4uLmp9fSA9IGspO1xuKHtpOiBbLi4ual19ID0gayk7In0=), it has been fixed since version 7.2.0.
