### ISSUE TITLE
Issues with the new Reflect-based inherit

### ISSUE THREAD

**Issue by xtuc** [babel/babel#7744]
Choose one: is this a bug report or feature request?
bug

### Input Code

```js
class T extends Error {}

console.log(1, new T("test").message);
console.log(2, new Error("test").message);
```

Generated code:
<detail>

```js
"use strict";

function _typeof(obj) { if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (call && (_typeof(call) === "object" || typeof call === "function")) { return call; } return _assertThisInitialized(self); }

function _assertThisInitialized(self) { if (self === void 0) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function"); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

function _gPO(o) { _gPO = Object.getPrototypeOf || function _gPO(o) { return o.__proto__; }; return _gPO(o); }

function _sPO(o, p) { _sPO = Object.setPrototypeOf || function _sPO(o, p) { o.__proto__ = p; return o; }; return _sPO(o, p); }

function _construct(Parent, args, Class) { _construct = (typeof Reflect === "undefined" ? "undefined" : _typeof(Reflect)) === "object" && Reflect.construct || function _construct(Parent, args, Class) { var Constructor, a = [null]; a.push.apply(a, args); Constructor = Parent.bind.apply(Parent, a); return _sPO(new Constructor(), Class.prototype); }; return _construct(Parent, args, Class); }

function _wrapNativeSuper(Class) { var _cache = typeof Map === "function" ? new Map() : undefined; _wrapNativeSuper = function _wrapNativeSuper(Class) { if (typeof Class !== "function") { throw new TypeError("Super expression must either be null or a function"); } if (typeof _cache !== "undefined") { if (_cache.has(Class)) return _cache.get(Class); _cache.set(Class, Wrapper); } function Wrapper() {} Wrapper.prototype = Object.create(Class.prototype, { constructor: { value: Wrapper, enumerable: false, writable: true, configurable: true } }); return _sPO(Wrapper, _sPO(function Super() { return _construct(Class, arguments, _gPO(this).constructor); }, Class)); }; return _wrapNativeSuper(Class); }

var T =
/*#__PURE__*/
function (_Error) {
  _inherits(T, _Error);

  function T() {
    _classCallCheck(this, T);

    return _possibleConstructorReturn(this, (T.__proto__ || Object.getPrototypeOf(T)).apply(this, arguments));
  }

  return T;
}(_wrapNativeSuper(Error));

console.log(1, new T("test"));
console.log(2, new Error("test"));
```

</detail>

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["@babel/preset-env"]
}
```

### Expected Behavior

```
1 'test'
2 'test'
```

Observable on `7.0.0-beta.35` (before Reflect-based extend #7020 ).

### Current Behavior

```
1 ''
2 'test'
```

Also logging the entire object shows significantly something else:

```
1 [Error]
2 Error: test
    at [stdin]:36:16
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:152:38)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:660:30)
    at evalScript (bootstrap_node.js:475:27)
    at Socket.<anonymous> (bootstrap_node.js:240:15)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.44
| Babylon          | 
| node             | v6.11.4
| npm              | 
| Operating System |

**Comment by nicolo-ribaudo** [comment]
This might be fixed by https://github.com/babel/babel/pull/7533. I'll see what still needs to be done in that PR.

**Comment by loganfsmyth** [comment]
Looks like this works on master now.
