### ISSUE TITLE
Error with babel-plugin-transform-es2015-modules-amd with Mozilla pdf.js

### ISSUE THREAD

**Issue by csetera** [babel/babel#7759]
This is a bug report.  As part of an upgrade from Ember 2.12 to Ember 2.18, the build is crashing when Babel attempts to transpile the Mozilla pdf.js project that we depend on.  The Mozilla code is pulled in by bower as a dependency of this Ember plugin:

```"ember-pdfjs": "^0.4.11"```

### Input Code
Executing babel under debugger control, I used the following:
```
node --inspect --debug-brk ./node_modules/.bin/babel  --plugins transform-es2015-modules-amd bower_components/pdfjs-dist/build/pdf.js -d ~/temp
```

This is with the following bower.json configuration for retrieving Mozilla's PDF.js:
```    "pdfjs-dist": "1.7.331"  ```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
No configuration specified... other than what was on the command line shown above.

### Expected Behavior
I would expect the plugin to complete without error.  Likely would not need any actual file changes, but even with changes it should complete successfully.

### Current Behavior
Failure with the following error:
```
TypeError: bower_components/pdfjs-dist/build/pdf.js: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/Users/setera/temp/bv-fund-mgr-218/node_modules/babel-types/lib/definitions/index.js:110:13)
    at Object.validate (/Users/setera/temp/bv-fund-mgr-218/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/Users/setera/temp/bv-fund-mgr-218/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath._remove (/Users/setera/temp/bv-fund-mgr-218/node_modules/babel-traverse/lib/path/removal.js:58:10)
    at NodePath.remove (/Users/setera/temp/bv-fund-mgr-218/node_modules/babel-traverse/lib/path/removal.js:30:8)
    at PluginPass.CallExpression (/Users/setera/temp/bv-fund-mgr-218/node_modules/babel-plugin-transform-es2015-modules-amd/lib/index.js:42:12)
    at NodePath._call (/Users/setera/temp/bv-fund-mgr-218/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/setera/temp/bv-fund-mgr-218/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/setera/temp/bv-fund-mgr-218/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/setera/temp/bv-fund-mgr-218/node_modules/babel-traverse/lib/context.js:150:16)
```

I added a debugger statement just before the error line shown above and connected with the Chrome debugger.  The debugger shows that the AST node in question has a starting source location of line 2423/column 3 and an ending position of line 2423/column 42.  The source of the pdf.js code for that line is:
```js
   require.ensure = require('node-ensure');
```

That line with a bit more context looks like this:
```js
if (typeof __pdfjsdev_webpack__ === 'undefined') {
 if (typeof window === 'undefined') {
  isWorkerDisabled = true;
  if (typeof require.ensure === 'undefined') {
   require.ensure = require('node-ensure');
  }
  useRequireEnsure = true;
 } else if (typeof require !== 'undefined' && typeof require.ensure === 'function') {
  useRequireEnsure = true;
 }
 if (typeof requirejs !== 'undefined' && requirejs.toUrl) {
  workerSrc = requirejs.toUrl('pdfjs-dist/build/pdf.worker.js');
 }
```
Clearly, there is a lot of module handling going on inside this code and it appears that that is confusing the parsing or Babel and this plugin in some way.

### Possible Solution
I honestly don't know, which is why I reached out! :-)

### Context
Attempting to upgrade to a newer version of Ember CLI.  Moving from 2.12 to 2.18 which also means moving from Babel 5 to Babel 6.  I suspect it is due to the Babel upgrade that this is occurring.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Ember CLI    | 2.18.2
| Babel            |  (core) 6.26
| node             | v6.9.4
| npm              | 3.10.10
| Operating System | Darwin localhost 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Comment by loganfsmyth** [comment]
`transform-es2015-modules-amd` is meant to compile ES6 modules to AMD. If your file isn't an ES6 module, enabling can cause issues like the one you are seeing.
