### ISSUE TITLE
7.0.0-beta.46 has issues with jsx

### ISSUE THREAD

**Issue by mikevaleriano** [babel/babel#7788]
Choose one: is this a bug report or feature request?
Bug report.

### Input Code

```js
import React from "react";
import { render } from "react-dom";

// some other code, not related to jsx or this issue

const Comp = () => <div>content</div>;
render(<Comp/>, document.querySelector("#root"));
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": [
    ["@babel/preset-env", { "modules": false, "shippedProposals": true }],
    "@babel/preset-react"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

### Expected Behavior
Webpack should compile the code successfully, as it did with version 7.0.0-beta.45

### Current Behavior
Webpack compilation halts with an error at the first JSX appearance in code. Nothing else was updated, only babel from beta.45 to beta.46
```
ERROR in d:/Code/dist/melhoria-beta/src/index.js
Module build failed: SyntaxError: d:\Code\dist\melhoria-beta\src\index.js: Unexpected token (24:19)

  22 | };
  23 |
> 24 | const Comp = () => <div>content</div>;
     |                    ^
  25 | render(<Comp/>, document.querySelector("#root"));
  26 | 
    at Parser.raise (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:779:15)
    at Parser.unexpected (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:2082:16)
    at Parser.parseExprAtom (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:3158:20)
    at Parser.parseExprSubscripts (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:2758:21)
    at Parser.parseMaybeUnary (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:2737:21)
    at Parser.parseExprOps (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:2646:21)
    at Parser.parseMaybeConditional (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:2618:21)
    at Parser.parseMaybeAssign (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:2565:21)
    at Parser.parseFunctionBody (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:3747:24)
    at Parser.parseArrowExpression (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:3707:10)
    at Parser.parseParenAndDistinguishExpression (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:3323:12)
    at Parser.parseExprAtom (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:3114:21)
    at Parser.parseExprSubscripts (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:2758:21)
    at Parser.parseMaybeUnary (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:2737:21)
    at Parser.parseExprOps (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:2646:21)
    at Parser.parseMaybeConditional (d:\Code\dist\melhoria-beta\node_modules\@babel\core\node_modules\babylon\lib\index.js:2618:21)
i ｢wdm｣: Failed to compile.
```

### Your Environment

Plugins and presets were also updated to beta.46.
Reverting my dependencies to beta.45 doesn't solve the issue, since they depend on other packages that were updated to beta.46 themselves.

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.46
| Babylon          | 
| node             | 9.11.1
| npm              | 5.8.0
| Operating System | Windows 10 64-bit

**Comment by loganfsmyth** [comment]
Is there a reproduction repository somewhere that we could look at?

**Comment by loganfsmyth** [comment]
FYI, you should fall back to `beta.44`, rather than `45`. Both `45` and `46` were published last night.

**Comment by hzoo** [comment]
I can't reproduce with 

<img width="548" alt="screen shot 2018-04-23 at 12 06 17 pm" src="https://user-images.githubusercontent.com/588473/39139062-0235bff2-46ef-11e8-8eb5-5532422f253d.png">

```json
{
  "presets": ["@babel/preset-react"]
}
```

**Comment by lorenzomigliorero** [comment]
If you import another module in a.js, the issue appear.

**Comment by xtuc** [comment]
@lorenzomigliorero do you mean creating a repo with your repro? So we can use it for debug.

**Comment by mikevaleriano** [comment]
> Is there a reproduction repository somewhere that we could look at?

This is a [not so small repository](https://github.com/mikevaleriano/babeltest) because I really don't use the CLI, but the webpack loader (a beta version of it, which works fine with 44).  As it is, the error is reproduced, since it's using 46. If you revert to beta.44, it compiles without problems, both in the devServer and in the production builds of webpack.

> FYI, you should fall back to beta.44, rather than 45. Both 45 and 46 were published last night.

You are absolutely right: the issue happens with 45 as well.

**Comment by iantanwx** [comment]
The work around seems to be to pass the entire `babelrc` config to `babel-loader`. I think this must be related to https://github.com/babel/babel/pull/7358, since `babel-loader` seems to be unable to pick up the `babelrc` as it normally would.

**Comment by mikevaleriano** [comment]
Following instructions in #7358 and creating a `babel.config.js` file exporting my configuration as it was in `.babelrc` solved the issue. Closing.

**Comment by loganfsmyth** [comment]
FYI, for anyone coming across this bug and wondering about config files, our new docs at http://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading may help explain why we've things a bit in Babel 7 and how you might approach getting things to work again.
