### ISSUE TITLE
transform-es2015-modules-commonjs throws without plugin-object-rest-spread

### ISSUE THREAD

**Issue by davidaurelio** [babel/babel#7796]
Choose one: bug

When using `transform-es2015-modules-commonjs` without `plugin-object-rest-spread`, it throws when traversing object rest spreads.

### Input Code

```js
({...a} = b);
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```sh
echo '({...a} = b);' | npx babel --plugins syntax-object-rest-spread,transform-es2015-modules-commonjs
```

### Expected Behavior
Output equivalent to input.

### Current Behavior
```
TypeError: unknown: Cannot read property 'name' of undefined
    at Object.AssignmentExpression (.../node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:92:38)
    at NodePath._call (.../node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (.../node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (.../node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (.../node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (.../node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (.../node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (.../node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (.../node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (.../node_modules/babel-traverse/lib/context.js:150:16)
```

### Context
Trying to compile code for node 8, containing imports/exports

### Your Environment

babel-core@6.26.0
babel-plugin-syntax-object-rest-spread@6.13.0
babel-plugin-transform-es2015-modules-commonjs@6.26.0

**Comment by nicolo-ribaudo** [comment]
This works in Babel 7: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=BQbwdBCGC-AEC8sBGBKA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.5.5&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.5.0
