### ISSUE TITLE
Invalid code generated when using for-of loops and/or throws exception

### ISSUE THREAD

**Issue by swernerx** [babel/babel#7801]
Bug Report

I am currently trying out the plugin async-to-promises from this PR https://github.com/babel/babel/pull/7076. While doing this I discovered a small issue with how for-of loops are being transpiled. The `_iterator` is declared two times. This produces a warning with nodent-transform.

See also: https://github.com/MatAtBread/fast-async/issues/55#issuecomment-383991686

### Input Code

```js
for (const taskName of tasks) {
  try {
    executeCommands()
  } catch (error) {
    console.error("Error")
  }
}
```

When used in my current preset it is transpiled to:

```js
import "core-js/modules/es7.symbol.async-iterator";
import "core-js/modules/es6.symbol";
import "core-js/modules/web.dom.iterable";

for (var _iterator = tasks, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
  var _ref;

  if (_isArray) {
    if (_i >= _iterator.length) break;
    _ref = _iterator[_i++];
  } else {
    _i = _iterator.next();
    if (_i.done) break;
    _ref = _i.value;
  }

  try {
    executeCommands();
  } catch (error) {
    console.error("Error");
  }
}
```

Line 5 shows the error described. Babel v6 produces a totally different code with no such issue.

I tried isolating this further by just using `@babel/cli`:

```
node_modules/.bin/babel --presets=env --no-babelrc __tests__/__fixtures__/es2015_for_off.js
```

The code tested is the same but magically results into an exception being thrown:

```
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/traverse/lib/scope/index.js:970:13)
    at BlockScoping.updateScopeInfo (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:342:10)
    at PluginPass.Loop (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:57:36)
    at newFn (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitMultiple (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/traverse/lib/context.js:99:17)
```

I figure this is related to usage of `const` so I wrapped the whole code into a function:

```js
function test() {
  for (const taskName of tasks) {
    try {
      executeCommands()
    } catch (error) {
      console.error("Error")
    }
  }
}
```

Unfortunately this now throws with another error:

```
Error: Unknown substitution "BODY" given
    at /Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/template/lib/populate.js:32:15
    at Array.forEach (<anonymous>)
    at populatePlaceholders (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/template/lib/populate.js:30:31)
    at /Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/template/lib/string.js:22:51
    at /Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/template/lib/builder.js:85:14
    at spec (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/babel-plugin-transform-es2015-for-of/lib/index.js:171:20)
    at PluginPass.ForOfStatement (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/babel-plugin-transform-es2015-for-of/lib/index.js:76:21)
    at newFn (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/traverse/lib/path/context.js:40:17)
    =============
    at exports.default (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/babel-plugin-transform-es2015-for-of/lib/index.js:14:20)
    at /Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/core/lib/config/full.js:172:14
    at cachedFunction (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/core/lib/config/caching.js:42:17)
    at loadPluginDescriptor (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/core/lib/config/full.js:207:28)
    at /Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/core/lib/config/full.js:64:16
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/core/lib/config/full.js:63:36)
    at recurseDescriptors (/Users/swerner/Workspace/open-source/babel-preset-edge/node_modules/@babel/core/lib/config/full.js:97:26)
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

I am just using the env preset which is enough to see the issue.

```js
{
  "presets": [ "env" ]
}
```

### Expected Behavior

`for...of` transpiles should work correctly and produce valid code.

### Context

I am currently working on migration of my preset `babel-preset-edge` to Babel v7.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.46 
| node             | 9.11.1
| npm              | 5.8.0
| Operating System | macOS 10.13.4

**Comment by swernerx** [comment]
Seems like the issue was to use "env" instead of "@babel/env". I would wish Babel would somehow check whether the plugin version is compatible with the Babel version.

**Comment by hzoo** [comment]
We actually do now, it's just that it was added in v7 https://github.com/babel/babel/pull/7450

**Comment by dany-fu** [comment]
@swernerx can you elaborate on how you solved this? I'm running into the same error
