### ISSUE TITLE
Allow parsing of HTML-like Comments

### ISSUE THREAD

**Issue by xtuc** [babel/babel#7802]
Choose one: is this a bug report or feature request?
Bug I guess

### Input Code

```js
<!-- test --->
```

### Expected Behavior

`undefined`

### Current Behavior

```
{ SyntaxError: res/ex-html-comment.js: Unexpected token (1:0)

> 1 | <!-- console.log("foo") -->
    | ^
  2 | 
    at Parser.raise (/home/sven/Documents/xtuc/talks/understanding-the-differences-is-accepting/node_modules/babylon/lib/index.js:779:15)
    at Parser.unexpected (/home/sven/Documents/xtuc/talks/understanding-the-differences-is-accepting/node_modules/babylon/lib/index.js:2082:16)
    at Parser.parseExprAtom (/home/sven/Documents/xtuc/talks/understanding-the-differences-is-accepting/node_modules/babylon/lib/index.js:3158:20)
    at Parser.parseExprSubscripts (/home/sven/Documents/xtuc/talks/understanding-the-differences-is-accepting/node_modules/babylon/lib/index.js:2758:21)
    at Parser.parseMaybeUnary (/home/sven/Documents/xtuc/talks/understanding-the-differences-is-accepting/node_modules/babylon/lib/index.js:2737:21)
    at Parser.parseExprOps (/home/sven/Documents/xtuc/talks/understanding-the-differences-is-accepting/node_modules/babylon/lib/index.js:2646:21)
    at Parser.parseMaybeConditional (/home/sven/Documents/xtuc/talks/understanding-the-differences-is-accepting/node_modules/babylon/lib/index.js:2618:21)
    at Parser.parseMaybeAssign (/home/sven/Documents/xtuc/talks/understanding-the-differences-is-accepting/node_modules/babylon/lib/index.js:2565:21)
    at Parser.parseExpression (/home/sven/Documents/xtuc/talks/understanding-the-differences-is-accepting/node_modules/babylon/lib/index.js:2518:21)
    at Parser.parseStatementContent (/home/sven/Documents/xtuc/talks/understanding-the-differences-is-accepting/node_modules/babylon/lib/index.js:4077:21)
  pos: 0,
  loc: Position { line: 1, column: 0 },
  code: 'BABEL_PARSE_ERROR' }

```

### Possible Solution

Ignore it or update Babylon (it could be a good first issue?).

### Context

Maybe some peoples are still using it?

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7
| Babylon          | 
| node             | v6.11.4
| npm              | 
| Operating System | 

See spec: [B.1.3 HTML-like Comments](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-html-like-comments)

```
Comment::
  SingleLineHTMLOpenComment
  ...

SingleLineHTMLOpenComment::
  <!--SingleLineCommentChars
  ...
```

**Comment by KFlash** [comment]
You did not mentionif this was in sloppy mode or module code, but note that <!--` in module code is not considered a comment start , but allowed in sloppy mode. 
However. This is an common issue among the majority of other JS parsers.  E.g. Esprima got this right in sloppy mode, but doesn't throw in module code. Shift got it right both in sloppy and module code.

**Comment by loganfsmyth** [comment]
I'm not strictly this, but I don't know that I'd call it a spec violation because it's part of Annex B, and Babel has generally not handled that stuff. For instance, we definitely don't handle all of the old non-standard block-level function hoisting defined in annex B. I did file #5266 last year to track the possibility though.

**Comment by hzoo** [comment]
Personally, I'd I don't think we support support this or anything in Annex B - we never have and there's already enough issues that are way higher priority. We don't have to (not a browser) so we actually have the option not to (this is true for anything really). Basically I think we need to think about priority (code that is normally written/used), and there's plenty of that such that I don't see this happening unless this is a really good use case - if it's just a curiosity/completionist kind of view then I would ask that we not try to pursue this kind of thing?

**Comment by KFlash** [comment]
I noticed this has never been supported in acorn either. Off topic. I Looked at the lexer and noticed it possible to gain 3% perf boost. Move WS skipping to top of the switch and all other rare WS only validate them if hit max ascii chars - 128 and above.  And only break the loop in the default clause. No ws skipping. 
It's also possible to gain perf if rewrite `fromCidePoint`. It's too bloated.

**Comment by xtuc** [comment]
Ok, I haven't realized that Babel doesn't support the Annex B (I don't think it's documented somewhere neither).

First, I don't particularly care about allows HTML comments in Babel, it seems like a very uncommon use-case. Unlike the non-standard block-level function hoisting we can just parse it (and emit it again if needed).

On the other hand, I think that it could be a good first issue for someone wanting to contribute to our parser/babel.

**Comment by danez** [comment]
We do support html comments in script mode. Till recently we did not allow them on the first line though: #9760
