### ISSUE TITLE
Assertion failure - expected a single output file when running ts-jest tests

### ISSUE THREAD

**Issue by apieceofbart** [babel/babel#7826]
Choose one: is this a bug report or feature request?
Bug. Regresion after installing babel-core 6.26.2

### Input Code

I apologize but I don't currently have time to create a reproducible repo but I will try to describe issue the best I can. 
We're using `ts-jest` which is using `babel-core` as dependency. When running test we observe issue for files that don't emit any javascript (they only contain typescript type annotations). We observe error thrown: `Assertion failure - expected a single output file` 
This comes from: https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/merge-map.js#L15

However, I cannot even debug that because the `if` statement is never true, yet somehow error is thrown. 

```js
// I will provide repo later...
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

I am not using babel directly. 

```js
{
  "your": { "config": "here" }
}
```

### Expected Behavior

There should be no error thrown.

### Current Behavior

Error is thrown

### Possible Solution

Downgrading to 6.26.0 of babel-core fixes the issue

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

**Comment by loganfsmyth** [comment]
Sorry about that. I know what I've broken, I'll get it fixed up.

**Comment by apieceofbart** [comment]
@loganfsmyth no problem, thank you! The easiest workaround we found is to add some dummy export to the file, e.g. `export const __something = null;`

**Comment by loganfsmyth** [comment]
Can you give 6.26.3 a shot?

**Comment by tsirlucas** [comment]
Hey @loganfsmyth, I'm using babel-core@6.26.3 and ts-jest@22.4.4 and still getting the same error when importing files with only types to use inside a test file. The error occurs when trying to collect coverage from those files.

Downgrading to babel-core@6.26.0 didn't resolve the issue for me.

I've ignored the models dir and it solved the issue for now, but I think it's just a workaround.

Workaround in my case:
```json
 "collectCoverageFrom":  [
    "src/**/*.{ts,tsx}",
    "!src/**/index.ts",
    "!src/models/*.ts" // here, models is the dir where my types are.
  ],
```

Error message:
```
STACK: Error: /Users/lucascorreia/Documents/workspace/college/PayIt/src/models/Bill.ts: Assertion failure - expected a single output file
    at mergeSourceMap (/Users/lucascorreia/Documents/workspace/college/PayIt/node_modules/ts-jest/node_modules/babel-core/lib/transformation/file/merge-map.js:38:11)
    at File.mergeSourceMap (/Users/lucascorreia/Documents/workspace/college/PayIt/node_modules/ts-jest/node_modules/babel-core/lib/transformation/file/index.js:450:37)
    at File.generate (/Users/lucascorreia/Documents/workspace/college/PayIt/node_modules/ts-jest/node_modules/babel-core/lib/transformation/file/index.js:687:25)
    at File.transform (/Users/lucascorreia/Documents/workspace/college/PayIt/node_modules/ts-jest/node_modules/babel-core/lib/transformation/file/index.js:522:17)
    at /Users/lucascorreia/Documents/workspace/college/PayIt/node_modules/ts-jest/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/Users/lucascorreia/Documents/workspace/college/PayIt/node_modules/ts-jest/node_modules/babel-core/lib/transformation/file/index.js:532:16)
    at Pipeline.transform (/Users/lucascorreia/Documents/workspace/college/PayIt/node_modules/ts-jest/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at /Users/lucascorreia/Documents/workspace/college/PayIt/node_modules/ts-jest/dist/postprocess.js:33:22
    at Object.process (/Users/lucascorreia/Documents/workspace/college/PayIt/node_modules/ts-jest/dist/preprocessor.js:39:22)
    at ScriptTransformer.transformSource (/Users/lucascorreia/Documents/workspace/college/PayIt/node_modules/jest-runtime/build/script_transformer.js:247:35)
```

**Comment by tsirlucas** [comment]
@loganfsmyth Yup, thats the case. Thanks for the help!
