### ISSUE TITLE
Module build failed: Error: Cannot find module 'babel-preset-env' from '../src' - Did you mean "@babel/env"?

### ISSUE THREAD

**Issue by Kunya** [babel/babel#7903]
Hi All,

Looking for support as I coudn't google or find the root cause of the issue.
I don't seem to find any reference to 'babel-preset-env' in my files, but somehow webpack is told to load it and fails. Not sure if this is babel or webpack issue or something else.

**Here is full error mesage:**
```
ERROR in ./src/main.js
Module build failed: Error: Cannot find module 'babel-preset-env' from '/root/text2data/text2data/src'.
Did you mean "@babel/env"?
    at Function.module.exports [as sync] (/root/text2data/text2data/node_modules/resolve/lib/sync.js:42:15)
    at resolveStandardizedName (/root/text2data/text2data/node_modules/@babel/core/lib/config/files/plugins.js:104:31)
    at resolvePreset (/root/text2data/text2data/node_modules/@babel/core/lib/config/files/plugins.js:57:10)
    at loadPreset (/root/text2data/text2data/node_modules/@babel/core/lib/config/files/plugins.js:76:18)
    at createDescriptor (/root/text2data/text2data/node_modules/@babel/core/lib/config/config-descriptors.js:154:21)
    at /root/text2data/text2data/node_modules/@babel/core/lib/config/config-descriptors.js:106:12
    at Array.map (<anonymous>)
    at createDescriptors (/root/text2data/text2data/node_modules/@babel/core/lib/config/config-descriptors.js:105:27)
    at createPresetDescriptors (/root/text2data/text2data/node_modules/@babel/core/lib/config/config-descriptors.js:97:10)
    at /root/text2data/text2data/node_modules/@babel/core/lib/config/config-descriptors.js:69:19
    at presets (/root/text2data/text2data/node_modules/@babel/core/lib/config/config-descriptors.js:59:25)
    at mergeChainOpts (/root/text2data/text2data/node_modules/@babel/core/lib/config/config-chain.js:371:68)
    at /root/text2data/text2data/node_modules/@babel/core/lib/config/config-chain.js:324:7
    at buildRootChain (/root/text2data/text2data/node_modules/@babel/core/lib/config/config-chain.js:136:21)
    at loadPrivatePartialConfig (/root/text2data/text2data/node_modules/@babel/core/lib/config/partial.js:51:53)
    at loadFullConfig (/root/text2data/text2data/node_modules/@babel/core/lib/config/full.js:43:37)
    at /root/text2data/text2data/node_modules/@babel/core/lib/transform.js:28:33
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
**package.json**
```
{
  "name": "text2data",
  "description": "NLP factory",
  "version": "1.0.0",
  "author": "Rudolp The Wild",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "dependencies": {
    "bulma": "^0.5.3",
    "cross-env": "^3.0.0",
    "socket.io": "^2.1.0",
    "vue": "^2.5.16",
    "vue-resource": "^1.5.0",
    "vue-router": "^2.8.1",
    "vuex": "^2.5.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.46",
    "@babel/core": "^7.0.0-beta.46",
    "@babel/preset-env": "^7.0.0-beta.46",
    "babel-loader": "^8.0.0-beta.2",
    "css-loader": "^0.25.0",
    "file-loader": "^0.9.0",
    "vue-loader": "^12.2.2",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.8.1",
    "webpack-cli": "^2.1.3"
  }
}
```

**.babelrc**
```
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false ,
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      }
    }]
  ]
}
```

**webpack.config.js**
```
const path = require('path')
const webpack = require('webpack')
const { VueLoaderPlugin } = require('vue-loader')

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/',
    filename: 'build.js'
  },
  target: "web",
  mode: 'development',
  module: {
    rules: [{
        test: /\.css$/,
        use: [
          'vue-style-loader',
          'css-loader'
        ],
      }, {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {}
          // other vue-loader options go here
        }
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      }
    ]
  },
  devServer: {
    historyApiFallback: true,
    noInfo: true,
    overlay: true
  },
  performance: {
    hints: false
  },
  devtool: '#eval-source-map'
}
```
I've tried to install 'babel-preset-env', but then it throws an error:
`"Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /root/text2data/text2data/node_modules/babel-preset-stage-2/lib/index.js"`.
Guess it's a conflict in Babel versions, so not a way forward.

Any idea where to look to find and remove 'babel-preset-env'? Or any other thought is very welcome, I've spent like a full day in circles ;(

**Comment by loganfsmyth** [comment]
What folder is your `.babelrc` file in? `/root/text2data/text2data/src` implies that you have either `/root/text2data/text2data/src/.babelrc` that references the `env` preset, or possibly a `/root/text2data/text2data/src/package.json` or something.

**Comment by Kunya** [comment]
@loganfsmyth OMG so logical and easy to troubleshoot if only I would use my brain!
HUGE thanks, indeed there was another .babelrc file with reference
