### ISSUE TITLE
strictMode option should be documented by @babel/plugin-transform-modules-commonjs

### ISSUE THREAD

**Issue by zavr-1** [babel/babel#7910]
## Bug Report

**Current Behavior**
There's no documentation for `strictMode` and only for `strict` which doesn't help remove "use strict". 

**Expected behavior/code**
This should be properly documented.

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
    "plugins": [
      "@babel/plugin-syntax-object-rest-spread",
      ["@babel/plugin-transform-modules-commonjs", {
        "strictMode": false
      }]
    ]
  }

```

**Environment**
- Babel version(s): 7.0.0-beta.46
- Node/npm version: Node 8/npm 5
- OS: OSX 10.13.1
- Monorepo no
- How you are using Babel: cli, register

**Possible Solution**

Update Readme file

**Additional context/Screenshots**

**Comment by loganfsmyth** [comment]
@zavr-1 Out of curiosity, what do you want to use the option for? As far as I'm concerned, people shouldn't use it, so I'm not sure I actually want to document it.

**Comment by zavr-1** [comment]
@loganfsmyth I used it in my package https://github.com/artdecocode/erotic without it it's impossible to compile because what I'll get errors in my test suite.

```
test/spec > lib.js > default > getCallerFromArguments > returns caller function from arguments
  TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
      at getCallerFromArguments (/Users/zavr/adc/erotic/src/lib.js:60:11)
      at test (/Users/zavr/adc/erotic/test/spec/lib.js:64:18)
      at caller (/Users/zavr/adc/erotic/test/spec/lib.js:66:16)
      at returns caller function from arguments (/Users/zavr/adc/erotic/test/spec/lib.js:68:19)
```

By the way, checkout `erotic` -- it's very useful, maybe you want to start using it 👍

**Comment by loganfsmyth** [comment]
Alright, just beware that by setting that option, you're making your code non-standard, and it won't actually work if you tried to run it as a real ES6 module.

Since you rely on non-strict functionality, you'd be better off to write your module as CommonJS, instead of pretending that it is a valid ES-module. Your call though.

**Comment by zavr-1** [comment]
To be honest it doesn't work for me in `.mjs` regardless of `strictMode`

```js
// erotic.mjs
import erotic from '..'
console.log(erotic)
```
without `{ "strictMode": true }` (when build is)
```js
"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.default = erotic; // etc
```
and with `{ "strictMode": true }` (when build is)
```js
Object.defineProperty(exports, "__esModule", { value: true });exports.default = erotic;
```

**Comment by loganfsmyth** [comment]
I'm not sure I understand your example. You're saying _with_ `true` it omits the `use strict`?

`{ default: [Function: erotic] }` in `.mjs` is strange though. That could be a separate issue?

**Comment by zavr-1** [comment]
It has `use strict` but it still doesn't work with `mjs`, I thought you said it would make a difference. it's just removing strict so wtf is strict anyway who needs it now

**Comment by zavr-1** [comment]
ok so you mean i should use `require` instead of `import` because `use strict` should always be used in es modules?

**Comment by loganfsmyth** [comment]
Because ES module syntax automatically means that a file is strict, and you rely on non-strict features, it would make sense for you to write your module using standard CommonJS, with `module.exports` and `require` and such, in my opinion.

If you do that, you can just set `sourceType: "script"` in your Babel options, and it will skip adding the `use strict`. Of course, since you're manually enabling the module transform, you can also just leave that out of your config and you'd be fine too.

**Comment by aminya** [comment]
This should be documented. For example, when writing the tests, sometimes we want to set `process.platform` to some other value than its real value to test the code with different operating systems. 

But without this option, this is not possible. Saying use CommonJS is not a solution.

**Comment by dezman** [comment]
I think perhaps strict mode could be disabled in development, as I'd like to access `arguments.callee` ~> `Uncaught TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode` in the console. Is there another way to do this?
