### ISSUE TITLE
"We don't know what to do with this node type" error using @babel/plugin-proposal-class-properties

### ISSUE THREAD

**Issue by xcrzx** [babel/babel#7951]
## Bug Report

**Current Behavior**
Error using `@babel/plugin-proposal-class-properties`:

```
Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertBefore (/node_modules/@babel/traverse/lib/path/modification.js:55:11)
    at PluginPass.Class (/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:257:14)
    at newFn (/node_modules/@babel/traverse/lib/visitors.js:237:21)
    at NodePath._call (/node_modules/@babel/traverse/lib/path/context.js:65:20)
    at NodePath.call (/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/node_modules/@babel/traverse/lib/context.js:142:16)
    at TraversalContext.visitSingle (/node_modules/@babel/traverse/lib/context.js:102:19)
    at TraversalContext.visit (/node_modules/@babel/traverse/lib/context.js:182:19)
    at Function.traverse.node (/node_modules/@babel/traverse/lib/index.js:106:17)
```

**Input Code**

Repo: https://github.com/xcrzx/babel-class-properties

```js
export default class Foo extends Bar {
    static foo = {};

    test = (...args) => {
        console.log(...args);
    };
}
```
The error appears only if I have `static foo = {};`, `export default`, `extends Bar` and `(...args)` all together.

**Babel Configuration (.babelrc, package.json, cli command)**

babel.config.js:
```js
module.exports = {
  plugins: ['@babel/plugin-proposal-class-properties'],
};
```

**Environment**
- Babel version(s): [v7.0.0-beta.47]
- Node/npm version: [Node 9.11.1/npm 6.0.0]
- OS: [OSX 10.13.4]
- Monorepo [no]
- How you are using Babel: [`cli`, `loader`]

**Additional context/Screenshots**
The error appeared when I upgraded babel packages from v7.0.0-beta.44 to v7.0.0-beta.47.

**Comment by xcrzx** [comment]
Just checked, the error introduced in v7.0.0-beta.45

**Comment by xcrzx** [comment]
Added repo: https://github.com/xcrzx/babel-class-properties

**Comment by remcohaszing** [comment]
Some additional info:

- The export doesn’t have to be `default`.
- The test method must be a class property defining a function. I.e., it’s fine if it’s a regular method.
- The problem is only triggered for a variable named `args`.
- The variable `args` doesn’t have to be defined.
- The variable `args` may be used in other ways as well.

Another example triggering the error:

```js
export class Foo extends Bar {
  static foo = {};

  test = function () {
      args;
  };
}
```

**Comment by loganfsmyth** [comment]
Deduping against #7177 since it appears to be the same issue and was filed earlier.
