### ISSUE TITLE
Error while parsing JSON

### ISSUE THREAD

**Issue by Legends** [babel/babel#7991]
When compiling webpack I get the following error:

> ERROR in (webpack)/buildin/global.js
>     Module build failed: SyntaxError: C:\Users\Admin\Downloads\css-test\.babelrc:
> Error while parsing JSON - Unexpected '�' at line 1 column 2 of the JSON5
> data. Still to read: "��{\u0000\"\u0000p\u0

**.babelrc**
`{"presets": ["env"]}`

**webpack.config**
```
"devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2017": "^6.24.1",
```

**Comment by Legends** [comment]
Here is my entry-point file and the stacktrace is below.
If you need anything else, just let me know..
Thanks.

**Entry.js**
```
import "../static/scss/test.scss"

let a = require("./a");
let b = require("./b");

a();
b();
```


**StackTrace:**

ERROR in ./src/entry.js
Module build failed: SyntaxError: C:\Users\Admin\Downloads\css-test\.babelrc: Error while parsing JSON - Unexpected '�' at line 1 column 2 of the JSON5 data. Still to read: "��{\u0000\r\u0000\n\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000"
    at error (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:56:25)
    at word (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:393:13)
    at value (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:493:56)
    at Object.parse (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:508:18)
    at ConfigChainBuilder.addConfig (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:150:65)    at ConfigChainBuilder.findConfigs (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:96:16)
    at buildConfigChain (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:61:13)
    at OptionManager.init (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\option-manager.js:354:58)
    at File.initOptions (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Admin\Downloads\css-test\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\Admin\Downloads\css-test\node_modules\babel-loader\lib\index.js:173:20)

ERROR in   Error: Child compilation failed:
  Module build failed: SyntaxError: C:\Users\Admin\Downloads\css-test\.babelrc: Error while parsing JSON - Unexpected '�' at line 1 column 2 of the JSON5 da  ta. Still to read: "��{\u0000\r\u0000\n\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000"

  - json5.js:56 error
    [css-test]/[json5]/lib/json5.js:56:25

  - json5.js:393 word
    [css-test]/[json5]/lib/json5.js:393:13

  - json5.js:493 value
    [css-test]/[json5]/lib/json5.js:493:56

  - json5.js:508 Object.parse
    [css-test]/[json5]/lib/json5.js:508:18

  - build-config-chain.js:150 ConfigChainBuilder.addConfig
    [css-test]/[babel-core]/lib/transformation/file/options/build-config-chain.js:150:65

  - build-config-chain.js:96 ConfigChainBuilder.findConfigs
    [css-test]/[babel-core]/lib/transformation/file/options/build-config-chain.js:96:16

  - build-config-chain.js:61 buildConfigChain
    [css-test]/[babel-core]/lib/transformation/file/options/build-config-chain.js:61:13

  - option-manager.js:354 OptionManager.init
    [css-test]/[babel-core]/lib/transformation/file/options/option-manager.js:354:58

  - index.js:212 File.initOptions
    [css-test]/[babel-core]/lib/transformation/file/index.js:212:65

  - index.js:135 new File
    [css-test]/[babel-core]/lib/transformation/file/index.js:135:24

  - pipeline.js:46 Pipeline.transform
    [css-test]/[babel-core]/lib/transformation/pipeline.js:46:16

  - index.js:50 transpile
    [css-test]/[babel-loader]/lib/index.js:50:20


  - SyntaxError: C:\Users\Admin\Downloads\css-test\.babelrc: Error while parsing JSON - Unexpected '�' at line 1 column 2 of the JSON5 data. Still to read:
    "��{\u0000\r\u0000\n\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000"

  - Module build failed: SyntaxError: C:\Users\Admin\Downloads\css-test\.babelrc: Error while parsing JSON - Unexpected '�' at line 1 column 2 of the JSON5
    data. Still to read: "��{\u0000\r\u0000\n\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000"

  - json5.js:56 error
    [css-test]/[json5]/lib/json5.js:56:25

  - json5.js:393 word
    [css-test]/[json5]/lib/json5.js:393:13

  - json5.js:493 value
    [css-test]/[json5]/lib/json5.js:493:56

  - json5.js:508 Object.parse
    [css-test]/[json5]/lib/json5.js:508:18

  - build-config-chain.js:150 ConfigChainBuilder.addConfig
    [css-test]/[babel-core]/lib/transformation/file/options/build-config-chain.js:150:65

  - build-config-chain.js:96 ConfigChainBuilder.findConfigs
    [css-test]/[babel-core]/lib/transformation/file/options/build-config-chain.js:96:16

  - build-config-chain.js:61 buildConfigChain
    [css-test]/[babel-core]/lib/transformation/file/options/build-config-chain.js:61:13

  - option-manager.js:354 OptionManager.init
    [css-test]/[babel-core]/lib/transformation/file/options/option-manager.js:354:58

  - index.js:212 File.initOptions
    [css-test]/[babel-core]/lib/transformation/file/index.js:212:65

  - index.js:135 new File
    [css-test]/[babel-core]/lib/transformation/file/index.js:135:24

  - pipeline.js:46 Pipeline.transform
    [css-test]/[babel-core]/lib/transformation/pipeline.js:46:16

  - index.js:50 transpile
    [css-test]/[babel-loader]/lib/index.js:50:20


  - SyntaxError: C:\Users\Admin\Downloads\css-test\.babelrc: Error while parsing JSON - Unexpected '�' at line 1 column 2 of the JSON5 data. Still to read:
    "��{\u0000\r\u0000\n\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000"

  - compiler.js:79 childCompiler.runAsChild
    [css-test]/[html-webpack-plugin]/lib/compiler.js:79:16

  - Compiler.js:242 compile
    [css-test]/[webpack]/lib/Compiler.js:242:11

  - Compiler.js:487 hooks.afterCompile.callAsync.err
    [css-test]/[webpack]/lib/Compiler.js:487:14


  - Hook.js:35 AsyncSeriesHook.lazyCompileHook [as _callAsync]
    [css-test]/[tapable]/lib/Hook.js:35:21

  - Compiler.js:484 compilation.seal.err
    [css-test]/[webpack]/lib/Compiler.js:484:30


  - Hook.js:35 AsyncSeriesHook.lazyCompileHook [as _callAsync]
    [css-test]/[tapable]/lib/Hook.js:35:21

  - Compilation.js:966 hooks.optimizeAssets.callAsync.err
    [css-test]/[webpack]/lib/Compilation.js:966:35


  - Hook.js:35 AsyncSeriesHook.lazyCompileHook [as _callAsync]
    [css-test]/[tapable]/lib/Hook.js:35:21

  - Compilation.js:957 hooks.optimizeChunkAssets.callAsync.err
    [css-test]/[webpack]/lib/Compilation.js:957:32


  - Hook.js:35 AsyncSeriesHook.lazyCompileHook [as _callAsync]
    [css-test]/[tapable]/lib/Hook.js:35:21

  - Compilation.js:952 hooks.additionalAssets.callAsync.err
    [css-test]/[webpack]/lib/Compilation.js:952:36


  - Hook.js:35 AsyncSeriesHook.lazyCompileHook [as _callAsync]
    [css-test]/[tapable]/lib/Hook.js:35:21

  - Compilation.js:948 hooks.optimizeTree.callAsync.err
    [css-test]/[webpack]/lib/Compilation.js:948:32


  - Hook.js:35 AsyncSeriesHook.lazyCompileHook [as _callAsync]
    [css-test]/[tapable]/lib/Hook.js:35:21

  - Compilation.js:890 Compilation.seal
    [css-test]/[webpack]/lib/Compilation.js:890:27

  - Compiler.js:481 hooks.make.callAsync.err
    [css-test]/[webpack]/lib/Compiler.js:481:17


Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 1.9 KiB {0} [built] [failed] [1 error]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 1.9 KiB {0} [built] [failed] [1 error]
        + 2 hidden modules

    ERROR in (webpack)/buildin/global.js
    Module build failed: SyntaxError: C:\Users\Admin\Downloads\css-test\.babelrc: Error while parsing JSON - Unexpected '�' at line 1 column 2 of the JSON5
data. Still to read: "��{\u0000\r\u0000\n\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000"
        at error (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:56:25)
        at word (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:393:13)
        at value (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:493:56)
        at Object.parse (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:508:18)
        at ConfigChainBuilder.addConfig (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:150:65)
        at ConfigChainBuilder.findConfigs (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:96:16)
        at buildConfigChain (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:61:13)
        at OptionManager.init (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\option-manager.js:354:58)
        at File.initOptions (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\index.js:212:65)
        at new File (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\index.js:135:24)
        at Pipeline.transform (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
        at transpile (C:\Users\Admin\Downloads\css-test\node_modules\babel-loader\lib\index.js:50:20)
        at Object.module.exports (C:\Users\Admin\Downloads\css-test\node_modules\babel-loader\lib\index.js:173:20)
     @ ./node_modules/lodash/lodash.js 1:0-41
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs

    ERROR in (webpack)/buildin/module.js
    Module build failed: SyntaxError: C:\Users\Admin\Downloads\css-test\.babelrc: Error while parsing JSON - Unexpected '�' at line 1 column 2 of the JSON5
data. Still to read: "��{\u0000\r\u0000\n\u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000"
        at error (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:56:25)
        at word (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:393:13)
        at value (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:493:56)
        at Object.parse (C:\Users\Admin\Downloads\css-test\node_modules\json5\lib\json5.js:508:18)
        at ConfigChainBuilder.addConfig (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:150:65)
        at ConfigChainBuilder.findConfigs (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:96:16)
        at buildConfigChain (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:61:13)
        at OptionManager.init (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\options\option-manager.js:354:58)
        at File.initOptions (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\index.js:212:65)
        at new File (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\file\index.js:135:24)
        at Pipeline.transform (C:\Users\Admin\Downloads\css-test\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
        at transpile (C:\Users\Admin\Downloads\css-test\node_modules\babel-loader\lib\index.js:50:20)
        at Object.module.exports (C:\Users\Admin\Downloads\css-test\node_modules\babel-loader\lib\index.js:173:20)
     @ ./node_modules/lodash/lodash.js 1:0-41
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs

**Comment by xtuc** [comment]
Could you please share your `.babelrc` file?

**Comment by loganfsmyth** [comment]
Is your `.babelrc` maybe being saved as UTF16 or some other encoding that isn't UTF8? That's what the error message seems like it is saying.

**Comment by Legends** [comment]
@xtuc I have posted my .babelrc in my question above, but here again:

**.babelrc**
`{"presets": ["env"]}`

@loganfsmyth hmmm, I have now set the encoding to utf-8 explicitly, don't know what the previous setting was. The error is gone now. Thanks!

**Comment by loganfsmyth** [comment]
Cool!
