### ISSUE TITLE
having issue with dynamic import in nodemon with babel-node

### ISSUE THREAD

**Issue by rizwan92** [babel/babel#8013]
having issue with dynamic import in nodemon with babel-node
here is my package.json file
[my package.json](https://gist.github.com/rizwan92/8041b8c1831c22bb7064fefe0f2bbab2
)
- `nodemon -1.17.2`:
- `node -v8.11.2`:
- Operating system/terminal environment: 
- Command you ran:
     nodemon --exec babel-node server/server.js --ignore public/

### Actual behaviour:- but throwing an error that is Unexpected token import
here is problem :- [error screen short](https://files.slack.com/files-pri/T062L95S6-FAU6WCEGH/screenshot_from_2018-05-23_17-59-44.png)

i ran my server/server.js file with command babel server/server.js 
it is working fine
pic:-  [pic link with bable](https://files.slack.com/files-pri/T062L95S6-FAUNYVD8A/screenshot_from_2018-05-23_18-08-04.png)

**Comment by rizwan92** [comment]
i asked in the slack sir but no one knows why babel-node is giving this error in stage-3

**Comment by xtuc** [comment]
My guess is that the Babel configuration isn't reachable using nodemon, but I have no experience with it.

**Comment by rizwan92** [comment]
hello sir,
i  have created very small and super minimal project that uses dynamic imports in gihub., you can run and checkout the issue i am getting here. 

link is :- https://github.com/rizwan92/dynamic-import

run project with two commands:- 
npm run webpack
npm start

localhost://8000

**Comment by rizwan92** [comment]
@xtuc  no it not like that , it reaches the babel configuration. i checked it

**Comment by rizwan92** [comment]
@loganfsmyth  i deleted the `node_modules ` folder, run npm install still the same problem, 
i have one doubt i switched off my wifi and tun npm install to my project folder , from where  it is still installing the dependency without internet connection.

**Comment by rizwan92** [comment]
@loganfsmyth  no sir i let other people check this repo every one has the same problem 
`/home/rizwan/Desktop/web/asc-backend/src/App.js:151
        return import('./pages/DashboardPage');
               ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at loader (/home/rizwan/Desktop/web/asc-backend/node_modules/babel-register/lib/node.js:144:5)

    at Object.require.extensions.(anonymous function) [as .js] (/home/rizwan/Desktop/web/asc-backend/node_modules/babel-register
/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/rizwan/Desktop/web/asc-backend/server/server.js:12:1)
    at Module._compile (module.js:652:30)
    at loader (/home/rizwan/Desktop/web/asc-backend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/rizwan/Desktop/web/asc-backend/node_modules/babel-register
/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)`

**Comment by loganfsmyth** [comment]
Oh I'm sorry, it looks like you'd need to enable https://www.npmjs.com/package/babel-plugin-dynamic-import-node

The `syntax-dynamic-import` is just so Babel doesn't throw a parse error, if you want to transform it into something that works on Node, you need a transform to do that.

**Comment by rizwan92** [comment]
it works thanks @loganfsmyth . so here is some information about dynamic import in server side rendering with react and express.
dynamic import already supports by webpack which bundles up the all the react application.
but if you are using server side rendering which means compile the whole react application in server side and then send html string to the client , then babel wont understand the syntax import ('./yourFile.js'). 
to make it work you need to use this  https://www.npmjs.com/package/babel-plugin-dynamic-import-node plugin for node support.
and you must use stage-3 preset. 
my babelrc  config
{
   "presets": ["es2015","stage-2","stage-3","react"],
   "plugins": ["dynamic-import-node"]
}
```
```
