### ISSUE TITLE
@babel/register does not run on ES Module (.mjs) files

### ISSUE THREAD

**Issue by feross** [babel/babel#8085]
## Bug Report

**Current Behavior**

`@babel/register` should run on `.mjs` files now that `.mjs` is a supported file extension.

The @babel/register README states the following:

> All subsequent files required by node with the extensions .es6, .es, .jsx, **.mjs**, and .js will be transformed by Babel. ([link to quote](https://github.com/babel/babel/tree/master/packages/babel-register#usage))

**Input Code**

index.mjs:

```js
import '@babel/register'
import './file-with-jsx'
```

file-with-jsx.mjs:
```js
function func () {
  return <div>hi</div>
}
```

Then, run `index.mjs` with the `--experimental-modules` flag:

```bash
node --experimental-modules index.mjs
```

This prints an error:

```
{ SyntaxError: /Users/feross/code/test/file-with-jsx.js: Unexpected token (1:9)

> 1 | function () {
    |          ^
  2 |   return <div>hi</div>
  3 | }
  4 | 
    at _class.raise (/Users/feross/code/test/node_modules/@babel/parser/lib/index.js:3861:15)
    at _class.unexpected (/Users/feross/code/test/node_modules/@babel/parser/lib/index.js:5190:16)
    at _class.parseFunction (/Users/feross/code/test/node_modules/@babel/parser/lib/index.js:7746:12)
    at _class.parseFunctionStatement (/Users/feross/code/test/node_modules/@babel/parser/lib/index.js:7412:17)
    at _class.parseStatementContent (/Users/feross/code/test/node_modules/@babel/parser/lib/index.js:7109:21)
    at _class.parseStatement (/Users/feross/code/test/node_modules/@babel/parser/lib/index.js:7085:17)
    at _class.parseBlockOrModuleBlockBody (/Users/feross/code/test/node_modules/@babel/parser/lib/index.js:7632:23)
    at _class.parseBlockBody (/Users/feross/code/test/node_modules/@babel/parser/lib/index.js:7619:10)
    at _class.parseTopLevel (/Users/feross/code/test/node_modules/@babel/parser/lib/index.js:7050:10)
    at _class.parse (/Users/feross/code/test/node_modules/@babel/parser/lib/index.js:8432:17)
  pos: 9,
  loc: Position { line: 1, column: 9 },
  code: 'BABEL_PARSE_ERROR' }
```

**Expected behavior/code**

If you change the file extension of `file-with-jsx.mjs` to `.js`, then it works.

```bash
mv file-with-jsx.mjs file-with-jsx.js
node --experimental-modules index.mjs
```

This runs successfully, without errors.

***This would seem to indicate that babel is not running on the `.mjs` file.***

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    [
      "@babel/plugin-transform-react-jsx",
      {
        "pragma": "h",
        "useBuiltIns": true
      }
    ]
  ]
}
```

**Environment**
- Babel version(s): v7.0.0-beta.49
- Node/npm version: node v10.3.0, npm 6.1.0
- OS: macOS 10.13.4
- Monorepo: no
- How you are using Babel: @babel/register 7.0.0-beta.49

**Comment by jimniels** [comment]
I'm seeing something similar.

When I have the JSX as an `.mjs` file, I get this error:

```
❯ node --experimental-modules index.mjs
(node:89056) ExperimentalWarning: The ESM module loader is experimental.
file-with-jsx.mjs:4
  return <div>hi</div>;
         ^
SyntaxError: Unexpected token <
    at translators.set (internal/modules/esm/translators.js:33:13)
```

When I change the JSX to a `.js` file, I get a different error:

```
❯ node --experimental-modules index.mjs
(node:89133) ExperimentalWarning: The ESM module loader is experimental.
file-with-jsx.js:1
(function (exports, require, module, __filename, __dirname) { import React from "react";
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Proxy.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._compile (/Users/jim.nielsen/Sites/iosicongallery.com/shared/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/Users/jim.nielsen/Sites/iosicongallery.com/shared/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

"@babel/core": "^7.2.2",
"@babel/preset-react": "^7.0.0",
"@babel/register": "^7.0.0",

**Comment by jimniels** [comment]
I have this same issue (won't import `.mjs` but will import `.js`), but with a slightly different `.babelrc` file:

```
{
  "presets": [
    ["@babel/preset-env"],
    "@babel/preset-react"
  ]
}
```

**Comment by feross** [comment]
I think `--experimental-modules` has changed quite a bit since I opened this issue, so I'm going to just close this issue. I also just solved this problem by using `.mjs`, using the `@babel/plugin-transform-modules-commonjs` plugin, and removing the `--experimental-modules` flag.
