### ISSUE TITLE
[plugin-proposal-class-properties]: error on certain calling of private property

### ISSUE THREAD

**Issue by Lodin** [babel/babel#8090]
## Bug Report

**Current Behavior**
Trying to compile code below I've got the following error:
```
Property id of PrivateName expected node to be of a type ["Identifier"] but instead got "SequenceExpression"
```
This error appeared again when I tried to use babel REPL. I reduced example code to the minimal reproducable size, and there was the new strange thing: when I change the name of the variable that contains whole decorator function (`const b` in the REPL example) to a name equal to the private variable, code compiles as expected.

Removing dynamic variable name from field declaration allows code to compile as well. Static class declaration compiles properly too.

**Input Code**
- REPL or Repo link if applicable:
[Link](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZmGBeGUCGAnA5gU1kgPgCgYZgAbNCCGHADyhzABMb1s8YBvE0mAYjTIYAbQC6AbiK9SETiIgBPALZiAFADcAlNxl8AlnBhqoAC30QAdIJ1cAvnoek7EoA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&sourceType=module&lineWrap=false&presets=stage-2%2Cstage-3&prettier=false&targets=&version=7.0.0-beta.48&envVersion=7.0.0-beta.48)

```js
const fn = target =>
  class extends target {
    #a = [];

    set [sym](v) {
      if (this.#a) {}
    }
  };
```

**Expected behavior/code**
No error, compiled code.

**Babel Configuration (.babelrc, package.json, cli command)**
```js
{
  plugins: [
    ['@babel/plugin-proposal-class-properties', {loose: true }],
  ],
}
```

**Environment**
- Babel version(s): v7.0.0-beta.49
- Node/npm version: v10.3.0/v6.0.1
- OS: Windows 10
- Monorepo: Lerna
- How you are using Babel: `babel-loader@8.0.0-beta.3`

**Possible Solution**

**Additional context/Screenshots**
Error stacktrace:
```
Module build failed: TypeError: Property id of PrivateName expected node to be of a type ["Identifier"] but instead got "SequenceExpression"
    at Object.validate (<Project>\node_modules\@babel\core\node_modules\@babel\types\lib\definitions\utils.js:128:13)
    at Object.validate (<Project>\node_modules\@babel\core\node_modules\@babel\types\lib\validators\validate.js:17:9)
    at NodePath._replaceWith (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\replacement.js:194:9)
    at NodePath.replaceWith (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\replacement.js:178:8)
    at Object.ReferencedIdentifier (<Project>\node_modules\@babel\plugin-proposal-class-properties\lib\index.js:123:14)
    at Object.newFn (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:230:17)
    at NodePath._call (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (<Project>\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:90:19)
```

**Comment by TrejGun** [comment]
nice example!

**Comment by Lodin** [comment]
After some investigation I've got following data.

1) Error happens when program tries to replace `a` in `this.#a` to TDZ error and fails because `PrivateName` expects only `Identifier` (which is listed in error).
2) Error happens only with computed `sym` (if it is not computed), program does not enter [computedPaths](https://github.com/babel/babel/blob/master/packages/babel-plugin-proposal-class-properties/src/index.js#L321) cycle and does not trigger checking for TDZ error. 
3) Error happens only with private name, so [ReferencedIdentifier](https://github.com/babel/babel/blob/master/packages/babel-plugin-proposal-class-properties/src/index.js#L41) consumes it for some reason. If I add `console.log` on the [42 line](https://github.com/babel/babel/blob/master/packages/babel-plugin-proposal-class-properties/src/index.js#L42) like in code below, I'll get two logs: `sym` and `a`, while replacing private property with public gives only `sym` log. 
```javascript
ReferencedIdentifier(path) {
    console.log(path.node.name); // <-- here

    if (this.classRef === path.scope.getBinding(path.node.name)) {
        const classNameTDZError = this.file.addHelper("classNameTDZError");
        const throwNode = t.callExpression(classNameTDZError, [
            t.stringLiteral(path.node.name),
        ]);

        path.replaceWith(t.sequenceExpression([throwNode, path.node]));
        path.skip();
    }
},
```

I suppose error might be something here. No idea why `ReferencedIdentifier` decides to consume private property while public property is ignored by it.

**Comment by Lodin** [comment]
Looks like it is not an issue anymore since Babel 7 release. 

In accordance with [repl Link](https://babeljs.io/en/repl.html#?babili=false&browsers=chrome%20>%2065&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZmGBeGUCGAnA5gU1kgPgCgYZgAbNCCGHADyhzABMb1s8YBvE0mAYjTIYAbQC6AbiK9SETiIgBPALZiAFADcAlNxl8AlnBhqoAC30QAdIJ1cAvnoek7EoA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.0.0&envVersion=7.0.0) (necessary to add `@babel/plugin-proposal-class-fields` to make it work) and my own explorations, Babel 7 handles this issue pretty well. If I will have any further issues, I'll reopen this issue or create a new one.

Thanks for your work.
