### ISSUE TITLE
Babel 7.0.0-beta.49 (--experimental-modules)

### ISSUE THREAD

**Issue by cavaller** [babel/babel#8148]
I am using **Node v10.4.0**

```json
{
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.49",
    "@babel/core": "^7.0.0-beta.49",
    "@babel/node": "^7.0.0-beta.49",
    "@babel/preset-flow": "^7.0.0-beta.49",
    "flow-bin": "^0.74.0"
  }
}
```

## 1. This does not work because I am using the Flow (It is 👌)
node --experimental-modules ./packages/services/src/server.mjs

# This both should work but It does not (2, 3)

## 2. This does not work (ignoring everything probably)
./node_modules/.bin/babel-node --presets "@babel/preset-flow" ./packages/services/src/server.mjs --experimental-modules

```
/Users/m/Desktop/k/packages/services/src/server.mjs:1
(function (exports, require, module, __filename, __dirname) { import http from 'http';
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Module._compile (/Users/m/Desktop/k/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.newLoader [as .mjs] (/Users/m/Desktop/k/node_modules/pirates/lib/index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

## 3. This does not work (ignoring flow preset)
NODE_OPTIONS=--experimental-modules ./node_modules/.bin/babel-node --presets "@babel/preset-flow" ./packages/services/src/server.mjs

```
(node:3332) ExperimentalWarning: The ESM module loader is experimental.
(node:3333) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/m/Desktop/k/packages/services/src/Client/server.mjs:10
export const context = (context: Context) => {
                               ^
SyntaxError: Unexpected token :
    at translators.set (internal/modules/esm/translators.js:31:13)
```

**Comment by xtuc** [comment]
All the Babel version are affected since it's a new flag. 

We need to add this flag into https://github.com/babel/babel/blob/master/packages/babel-node/src/babel-node.js. Would you mind sending a PR?

**Comment by dnalborczyk** [comment]
@cavaller  I think it's currently not possible to use the `--experimental-modules` flag with babel.

you could check out [esm](https://github.com/standard-things/esm). it's awesome! it works great together with babel.

```
node -r esm -r @babel/register index.js
```

it runs with every node version, you can keep the `js` file extension, supports dynamic imports, and much more...

**Comment by dnalborczyk** [comment]
@xtuc could you elaborate on your :thumbsdown:

whitelisting the flag wouldn't do anything, as far as I know.

**Comment by xtuc** [comment]
@dnalborczyk: according to the description of the issue @cavaller is looking specially for the `--experimental-modules` flag on Node v10.4.0. I doubt that an alternative will actually help him.

> whitelisting the flag wouldn't do anything, as far as I know.

It will pass it to Node

**Comment by dnalborczyk** [comment]
> It will pass it to Node

I know https://github.com/babel/babel/issues/6285

>  I doubt that an alternative will actually help him.

[esm](https://github.com/standard-things/esm) is a module, and does the same thing as `--experimental modules` but on steroids. I **highly** recommend it. The maintainer of the module also joined the node modules working group recently.

as you see, I found myself with the same problem some time ago, and found [esm](https://github.com/standard-things/esm) as a great alternative.

**Comment by demurgos** [comment]
`esm` is a fine workaround but you shouldn't have to use it. I prefer a simple native solution rather than "modules on steroids". For example it needs configuration to run in strict mode. I use `esm` when I have no other choice (with `mocha` for example) but I highly prefer to use Node's native implementation.

**Comment by tbremer** [comment]
Not sure if this has been addressed, but adding a +1 to the request.

With ESM support in Node barreling towards us it'd be _really_ helpful to be able to use `.mjs` modules and Flow at the same time.
