### ISSUE TITLE
Invalid Option: 'true' is not a valid value for 'targets.forceAllTransforms'

### ISSUE THREAD

**Issue by srghma** [babel/babel#8164]
## Bug Report

**Current Behavior**
```
root@7244a1f05246:/usr/src/app# npm run build

> my-create-react-app@0.0.1 build /usr/src/app
> node scripts/build

/usr/src/app/node_modules/webpack-cli/bin/cli.js:244
                                throw err;
                                ^

Error: [BABEL] /usr/src/app/webpack-config/webpack.config.babel.js: Invalid Option: 'true' is not a valid value for 'targets.forceAllTransforms'. (While processing: "/usr/src/app/node_modules/@babel/preset-env/lib/index.js")
    at semverifyTarget (/usr/src/app/node_modules/@babel/preset-env/lib/targets-parser.js:148:11)
    at __default (/usr/src/app/node_modules/@babel/preset-env/lib/targets-parser.js:154:92)
    at Object.keys.filter.sort.reduce (/usr/src/app/node_modules/@babel/preset-env/lib/targets-parser.js:195:43)
    at Array.reduce (<anonymous>)
    at getTargets (/usr/src/app/node_modules/@babel/preset-env/lib/targets-parser.js:183:104)
    at _default (/usr/src/app/node_modules/@babel/preset-env/lib/index.js:183:46)
    at /usr/src/app/node_modules/@babel/preset-env/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/usr/src/app/node_modules/@babel/core/lib/config/full.js:157:14)
    at cachedFunction (/usr/src/app/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPresetDescriptor (/usr/src/app/node_modules/@babel/core/lib/config/full.js:227:63)
    at config.presets.map.descriptor (/usr/src/app/node_modules/@babel/core/lib/config/full.js:72:19)
    at Array.map (<anonymous>)
    at recurseDescriptors (/usr/src/app/node_modules/@babel/core/lib/config/full.js:70:38)
    at loadFullConfig (/usr/src/app/node_modules/@babel/core/lib/config/full.js:100:6)
    at loadOptions (/usr/src/app/node_modules/@babel/core/lib/config/index.js:27:36)
    at OptionManager.init (/usr/src/app/node_modules/@babel/core/lib/index.js:215:36)
    at compile (/usr/src/app/node_modules/@babel/register/lib/node.js:61:42)
    at compileHook (/usr/src/app/node_modules/@babel/register/lib/node.js:102:12)
    at Module._compile (/usr/src/app/node_modules/pirates/lib/index.js:86:27)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/usr/src/app/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/usr/src/app/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/usr/src/app/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/usr/src/app/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /usr/src/app/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
exec: /usr/src/app/node_modules/webpack-cli/bin/cli.js:244
                                throw err;
                                ^

Error: [BABEL] /usr/src/app/webpack-config/webpack.config.babel.js: Invalid Option: 'true' is not a valid value for 'targets.forceAllTransforms'. (While processing: "/usr/src/app/node_modules/@babel/preset-env/lib/index.js")
    at semverifyTarget (/usr/src/app/node_modules/@babel/preset-env/lib/targets-parser.js:148:11)
    at __default (/usr/src/app/node_modules/@babel/preset-env/lib/targets-parser.js:154:92)
    at Object.keys.filter.sort.reduce (/usr/src/app/node_modules/@babel/preset-env/lib/targets-parser.js:195:43)
    at Array.reduce (<anonymous>)
    at getTargets (/usr/src/app/node_modules/@babel/preset-env/lib/targets-parser.js:183:104)
    at _default (/usr/src/app/node_modules/@babel/preset-env/lib/index.js:183:46)
    at /usr/src/app/node_modules/@babel/preset-env/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/usr/src/app/node_modules/@babel/core/lib/config/full.js:157:14)
    at cachedFunction (/usr/src/app/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPresetDescriptor (/usr/src/app/node_modules/@babel/core/lib/config/full.js:227:63)
    at config.presets.map.descriptor (/usr/src/app/node_modules/@babel/core/lib/config/full.js:72:19)
    at Array.map (<anonymous>)
    at recurseDescriptors (/usr/src/app/node_modules/@babel/core/lib/config/full.js:70:38)
    at loadFullConfig (/usr/src/app/node_modules/@babel/core/lib/config/full.js:100:6)
    at loadOptions (/usr/src/app/node_modules/@babel/core/lib/config/index.js:27:36)
    at OptionManager.init (/usr/src/app/node_modules/@babel/core/lib/index.js:215:36)
    at compile (/usr/src/app/node_modules/@babel/register/lib/node.js:61:42)
    at compileHook (/usr/src/app/node_modules/@babel/register/lib/node.js:102:12)
    at Module._compile (/usr/src/app/node_modules/pirates/lib/index.js:86:27)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/usr/src/app/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/usr/src/app/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/usr/src/app/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/usr/src/app/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /usr/src/app/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)

root@7244a1f05246:/usr/src/app#
```

[.babelrc](https://github.com/srghma/my-create-react-app/blob/4501c8e6b36bf9be2c3966d82769ae15e085462d/.babelrc#L40)

```
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "browsers": "last 2 Chrome versions"
      }
    }],
    "@babel/react"
  ],
  "plugins": [
    "@babel/plugin-external-helpers",
    "css-to-js",
    "@babel/transform-runtime",
    ["@babel/plugin-proposal-object-rest-spread"],
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "webpack-config": "./webpack-config"
      }
    }],
    ["lodash", {
      "id": ["ramda", "ramda-adjunct", "recompose", "srghma-react-helpers"]
    }],
    ["direct-import", { "modules": ["material-ui"] }]
  ],
  "env": {
    "development": {
      "presets": [
        ["@babel/react", {
          "development": true
        }],
      ],
      "plugins": [ "react-hot-loader/babel" ]
    },
    "production": {
      "presets": [
        ["@babel/env", {
          "targets": {
            "browsers": "last 2 Chrome versions",
            "forceAllTransforms": true # line that causing the issue
          }
        }],
      ],
      "plugins": [
        "@babel/plugin-transform-react-constant-elements",
        "@babel/plugin-transform-react-inline-elements"
      ]
    }
  }
}
```

How to reproduce:

```
git clone https://github.com/srghma/my-create-react-app
git checkout 4501c8e6b36bf9be2c3966d82769ae15e085462d
  docker run \
    -it \
    --rm \
    --name "$(basename $PWD)-ruby" \
    -v `pwd`:/usr/src/app \
    -w /usr/src/app \
    starefossen/ruby-node:latest \
    "$@"
npm install
npm run build
```

**Possible Solution**
change `"forceAllTransforms": true` to `"uglify": true`

**Comment by hzoo** [comment]
`forceAllTransforms` doesn't go under `targets` unlike `uglify` so you need to specify it at a higher level in the config.

**Comment by srghma** [comment]
@hzoo, tnx, it works

```
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "browsers": "last 2 Chrome versions"
      }
    }],
    "@babel/react"
  ],
  "plugins": [
    "@babel/plugin-external-helpers",
    "css-to-js",
    "@babel/transform-runtime",
    ["@babel/plugin-proposal-object-rest-spread"],
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "webpack-config": "./webpack-config"
      }
    }],
    ["lodash", {
      "id": ["ramda", "ramda-adjunct", "recompose", "srghma-react-helpers"]
    }],
    ["direct-import", { "modules": ["material-ui"] }]
  ],
  "env": {
    "development": {
      "presets": [
        ["@babel/react", {
          "development": true
        }],
      ],
      "plugins": [ "react-hot-loader/babel" ]
    },
    "production": {
      "presets": [
        ["@babel/env", {
          "targets": {
            "browsers": "last 2 Chrome versions",
          },
          "forceAllTransforms": true
        }],
      ],
      "plugins": [
        // TODO: fix babel-preset-react-optimize to support babel 7
        "@babel/plugin-transform-react-constant-elements",
        "@babel/plugin-transform-react-inline-elements"
      ]
    }
  }
}

```
