### ISSUE TITLE
Error: Plugin 0 specified in "/<somePath>/.babelrc" provided an invalid property of "Instrumenter"

### ISSUE THREAD

**Issue by xploreraj** [babel/babel#8173]
Getting no issue in stage or localhost, but **only while deploying to our prod environment (starting up the app)**, getting below error:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Plugin 0 specified in "/<somePath>/.babelrc" provided an invalid property of "Instrumenter"
    at Plugin.init (/<somePath>/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/<somePath>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /<somePath>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/<somePath>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/<somePath>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/<somePath>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/<somePath>/node_modules/babel-register/lib/node.js:103:45)
    at loader (/<somePath>/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/<somePath>/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at handler (/<somePath>/node_modules/express-enrouten/lib/directory.js:79:20)
```

Here is my `.babelrc`
```
{
    "presets": [ "react", "es2015", "stage-3" ],
    "env": {
        "test": {
          "plugins": [ "istanbul" ]
        }
    },
    "plugins": ["istanbul"]
}
```

The dependencies: `node v8.11.2`

```
"dependencies": {
    "babel-core": "^6.24.1",
    "babel-loader": "^7.0.0",
    "babel-preset-env": "latest",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-3": "6.24.1",
    "babel-register": "^6.26.0",
    ...

"devDependencies": {
    "@istanbuljs/nyc-config-babel": "^1.2.3",
    "babel-cli": "^6.24.1",
    "babel-jest": "^23.0.0-alpha.0",
    "babel-plugin-istanbul": "^4.1.6",
    ...
```

Please explain the error and any solution/suggestion.

Thank you

**Comment by xploreraj** [comment]
Got resolved by removing `"plugins": ["istanbul"]` from `.babelrc`.
