### ISSUE TITLE
Symlinked module cannot find Babel plugin, property of 'useBuiltIns' undefined

### ISSUE THREAD

**Issue by karbica** [babel/babel#8209]
## Bug Report

**Current Behavior**
An npm linked module exposes a `bin`. That `bin` runs the build using the Webpack module provided the `webpack.config.js`. It works normally when called from `npm run build` but throws an error in the output of the file when called using the `bin`. I linked it so I can work on it without having to publish to the registry. This module will be used as a dependency of another project and is supposed to run Webpack internally to produce a new file which would be picked up by the parent project.

The error in the output file (`main.css`) is..
`ModuleBuildError: Module build failed: TypeError: Cannot read property 'useBuiltIns' of undefined
    at _default (/Users/kevinarbi/dev/component-lib/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js:13:32)`

**Input Code**
This is the module rule. I left out the other rules which are just for CSS.
```javascript
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: path.join(__dirname, 'src', 'components', 'index.js'),
  output: {
    libraryTarget: 'commonjs',
    library: '',
    path: path.resolve(__dirname, 'dist/themes'),
    filename: '[name].css',
  },
  resolve: {
    symlinks: false
  },
  module: {
    rules: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader',
        options: {
          babelrc: false,
          presets: ['@babel/preset-env', '@babel/preset-react'],
          plugins: [require('@babel/plugin-proposal-object-rest-spread')],
        },
      },
    }, ],
  },
  plugins: [new ExtractTextPlugin({
    filename: '[name].css'
  })],
};
```

This is the `bin` file. The error case does not happen so Webpack didn't see an error but Babel did and left it in the output of the file. The stats also show the error.
```javascript
#! /usr/bin/env node
const webpack = require('webpack');
const config = require('../webpack.config.themes');

webpack(config, (err, stats) => {
    if (err) {
        console.log(err);
        return;
    }

    console.log(stats);
});
```

**Expected behavior/code**
I expected to receive the output file as I would from running the build from the CLI which would be a single CSS file but from the call of an executable exposed by the project. Basically, the `bin` would build Webpack to generate some CSS for a the parent project.

**Babel Configuration (.babelrc, package.json, cli command)**
The working CLI command.
`"build": "webpack --config webpack.config.themes.js"`

This is the `.babelrc`.
```js
{
    "env": {
        "test": {
            "presets": [
                "@babel/preset-env"
            ]
        }
    },
    "plugins": [
        "@babel/plugin-proposal-object-rest-spread"
    ],
    "presets": [
        [ "@babel/preset-env", { "modules": false } ],
        "@babel/preset-react"
    ]
}
```

**Environment**
- Webpack version: `3.10.0`
- Babel version(s): `"@babel/core": "7.0.0-beta.39",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.39",
    "@babel/preset-env": "7.0.0-beta.39",
    "@babel/preset-react": "7.0.0-beta.39",
    "babel-core": "7.0.0-bridge.0",
    "babel-loader": "8.0.0-beta.0"`
- Node/npm version: `8.11.2`/`5.6.0`
- OS: `macOS 10.13.5`
- Monorepo: **no**
- How you are using Babel: `loader`

**Possible Solution**
I've read that resolving modules may be the case. I've done that with the presets and the plugins to no avail. I've also read that downgrading back down to Babel v6.x has solved the issue but I have to yet try that since I would like to stay on the new version. Seeing that it works normally from the CLI, I was hoping the same would be true when calling it from the outside through the `bin` file.

**Additional context/Screenshots**
Here is the stack trace..
```
[ ModuleBuildError: Module build failed: TypeError: Cannot read property 'useBuiltIns' of undefined
    at _default (/Users/kevinarbi/dev/component-lib/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js:13:32)
    at Function.memoisePluginContainer (/Users/kevinarbi/dev/cloud-console/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/kevinarbi/dev/cloud-console/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/kevinarbi/dev/cloud-console/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/kevinarbi/dev/cloud-console/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/kevinarbi/dev/cloud-console/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/kevinarbi/dev/cloud-console/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/kevinarbi/dev/cloud-console/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/kevinarbi/dev/cloud-console/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at runLoaders (/Users/kevinarbi/dev/component-lib/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/kevinarbi/dev/component-lib/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/kevinarbi/dev/component-lib/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/Users/kevinarbi/dev/component-lib/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/kevinarbi/dev/component-lib/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/kevinarbi/dev/component-lib/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/kevinarbi/dev/component-lib/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at /Users/kevinarbi/dev/component-lib/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at /Users/kevinarbi/dev/component-lib/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3) ],
```

**Comment by loganfsmyth** [comment]
That error really doesn't seem to correspond to your `package.json`. Please reinstall and make sure that the versions in `package.json` are really the versions that are installed in `node_modules`.
