### ISSUE TITLE
Babel 7 crashes Jest tests

### ISSUE THREAD

**Issue by budarin** [babel/babel#8213]
## 🐛 Bug Report

I have worked my project with Babel 6.
Then I moved it to Babel7 and got the error:
```
    D:\Projects\react-bootstrap-project\src\App.tsx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                                    ^^^^^

    SyntaxError: Unexpected identifier

      1 | import React from 'react';
      2 | import renderer from 'react-test-renderer';
    > 3 | import App from './App';
        | ^
      4 |
      5 | test('renders correctly', () => {
      6 |     const tree = renderer.create(<App />).toJSON();

      at ScriptTransformer._transformAndBuildScript (../node_modules/jest-runtime/build/script_transformer.js:402:17)
      at Object.<anonymous> (App.test.js:3:1)
```
jest.config.js

```js
const config = {
    rootDir: 'src',
    preset: 'jest-puppeteer',
    cacheDirectory: '../.tmp/jest',
    coverageDirectory: '../.tmp/jest/coverage',
    transform: {
        '^.+\\.js$': '../config/jest/transformer.js',
    },
    testMatch: [
        '**/__tests__/**/*.js?(x)',
        '**/__tests__/**/*.ts?(x)',
        '**/?(*.)+(spec|test).js?(x)',
        '**/?(*.)+(spec|test).ts?(x)',
    ],
    moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
    moduleNameMapper: {
        '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
            '../config/jest/mocks/fileMock.js',
        '\\.(css)$': '../config/jest/mocks/styleMock.js',
    },
    testPathIgnorePatterns: ['/node_modules/'],
    globals: {},
    notify: false,
    notifyMode: 'failure',
};

module.exports = config;
```
/config/jest/transformer.js

```js
const browserList = require('../browserList');

const config = {
    babelrc: false,
    presets: [
        [
            '@babel/preset-env',
            {
                loose: true,
                debug: true,
                modules: 'commonjs',
                targets: {
                    browsers: browserList,
                },
            },
        ],
        '@babel/preset-typescript',
        '@babel/preset-react',
    ],
    plugins: [
        '@babel/plugin-syntax-dynamic-import',
        ['babel-plugin-lodash', { id: ['lodash', 'recompose'] }],
        '@babel/plugin-transform-react-jsx-self',
        '@babel/plugin-transform-react-jsx-source',
        '@babel/plugin-proposal-class-properties',
        '@babel/plugin-proposal-object-rest-spread',
    ],
};

module.exports = require('babel-jest').createTransformer(config);
```

## To Reproduce

run tests

## Expected behavior

successful tests

## Link to repl or repo (highly encouraged)

Link to my [repository](https://github.com/budarin/react-bootstrap-project)

## Run `npx envinfo --preset jest`

**Environment**
- Babel version(s): 7.0.0-beta.51"
- Node/npm version: Node 10/npm 6
- OS: OSX 10.13.5, Windows 7
- Monorepo yes
- How you are using Babel: `loader`, jest transform

**Comment by budarin** [comment]
as I can see in .tmp/jest-transform-cache the module code is not transpiled yest - there is the original source of the .tsx module

**Comment by loganfsmyth** [comment]
Since you've got 
```
'^.+\\.js$': '../config/jest/transformer.js',
```
You'll only be transforming `.js` files.

**Comment by budarin** [comment]
@loganfsmyth 
Thanks alot!!!
I think that it automatically transform with config, but it's not true
