### ISSUE TITLE
babel doesn't transpile typescript even having @babel/preset-typescript in config

### ISSUE THREAD

**Issue by budarin** [babel/babel#8218]
## Bug Report

**Current Behavior**
I want to run webpack with ```webpack.config.babel.ts```
Wen I run webpack
```node
webpack-dev-server --mode development --config ./webpack.config.babel.ts
```
it fails with error:
```
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';
                                                                     ^^
SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```
**Expected behavior/code**
expexted to run webpack.config.ts

**Babel Configuration (.babelrc, package.json, cli command)**

```js{
    "presets": [
        [
            "@babel/preset-env",
            {
                "loose": true,
                "debug": true,
                "targets": { "node": "current" }
            }
        ],
        "@babel/preset-typescript"
    ],
    "plugins": [
        [
            "module-resolver",
            {
                "extensions": [".js", ".jsx", ".ts", ".tsx"],
                "root": ["./"]
            }
        ],
        "@babel/plugin-syntax-dynamic-import",
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-object-rest-spread"
    ]
}
```

**Environment**
- Babel version(s):  [v7.0.0-beta.51]
- Node/npm version: [Node 10/npm 6]
- OS:  [Windows 7]
- Monorepo [yes]
- How you are using Babel: [...]

**Comment by TomLingham** [comment]
I'd give `webpack -r @babel/register` in your script, this will register babel before loading your config files. I'm fairly confident that `webpack.config.babel.js` is hardcoded with the `js` extension.
This is how I do it, except I register babel in a separate file and run `webpack -r ./path/to/register-ts.js`

**Comment by budarin** [comment]
@TomLingham 
thanks for the idea, but I am confusing!
every tool has a config to configure it, but babel need to have another config to configure config for doin it's job !
It's little bit strange!
Why it should not be in config as an option???
why I should like a sorcerer gather different peaces of knowledge how with many hacks to force babel work as expected???
Sorry for my emotions but I spend a lot of time to configure webpack, babel, jest and etc because of its unusual and unkown hacks :(

**Comment by budarin** [comment]
@TomLingham 
I create register-ts.js
```js
require('@babel/register', {
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
});
```
And try to run webpack
```bash
webpack-dev-server --r registerTS.js --config ./webpack.config.babel.ts
```
but it fails with
```
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';
                                                                     ^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.newLoader [as .js] (\node_modules\pirates\lib\index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
```

**Comment by TomLingham** [comment]
Make sure you have the command written correctly:
`webpack-dev-server -r ./register-ts.js --config ./webpack.config.babel.ts`
-r will load the module from the node_modules folder unless it is a relative import just like when using node.

**Comment by budarin** [comment]
@TomLingham 
something stange is happend - I place ```register-ts.js``` at the root of the project and when I call
```js
webpack-dev-server -r ./register-ts.js
```
I get the error:
```
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module './registerTS.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at argv.configRegister.forEach.dep (\node_modules\webpack-cli\bin\convert-argv.js:130:7)
    at Array.forEach (<anonymous>)
    at WEBPACK_OPTIONS (\node_modules\webpack-cli\bin\convert-argv.js:128:26)
    at requireConfig (\node_modules\webpack-cli\bin\convert-argv.js:136:6)
    at \node_modules\webpack-cli\bin\convert-argv.js:143:17
    at Array.forEach (<anonymous>)
```
only calling like this
```js
webpack-dev-server -r register-ts.js
```
helps

**Comment by TomLingham** [comment]
Is the file called `register-ts.js` or `registerTS.js`? Just make sure you are typing that correctly first.

**Comment by budarin** [comment]
of course my version is called ```registerTS.js``` (I 'have tryied to use your name) and there is no typos when calling webpack

**Comment by TomLingham** [comment]
Alright, try prefix the file as if webpack is loading it relative to the `./node_modules/webpack-cli/bin/` directory. I've noticed this also happens sometimes with webpack-dev-server.
for example `webpack-dev-server -r ../../../registerTS.js`

**Comment by budarin** [comment]
@TomLingham 
It helped to run ```registerTS.js``` run (I placed console log to check if it 's runnig) but did not help to transpile ```webpack.config.babel.ts```:
```bash
Starting script: start-client
.ts & .tsx are registered
D:\Projects\react-ssr-bootstrap-project\config\webpack\client\webpack.config.babel.ts:1
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';
                                                                     ^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.newLoader [as .js] (D:\Projects\react-ssr-bootstrap-project\node_modules\pirates\lib\index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
```

**Comment by TomLingham** [comment]
This repo has a setup that works https://github.com/TomLingham/typescript-webpack
`npm install` and then `npm run dev` to get it running. See if you can use that as a reference.
I would need to see more of your code / setup to be able to troubleshoot further I think.

**Comment by budarin** [comment]
@TomLingham 
Here is the [repo](https://github.com/budarin/react-ssr-bootstrap-project) - try to play with it, please

**Comment by budarin** [comment]
@TomLingham 
I didn't manage to win it :(
Error:
```bash
@HSRV /d/Projects/react-ssr-bootstrap-project (master)
$ npm run build-temp

> minimal-react-webpack-babel-setup@1.0.0 build-temp D:\Projects\react-ssr-bootstrap-project
> webpack-dev-server -r ../../../config/webpack/client/register-ts.js --config config/webpack/client/webpack.config.babel.ts

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '../../../config/webpack/client/register-ts.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at argv.configRegister.forEach.dep (D:\Projects\react-ssr-bootstrap-project\node_modules\webpack-cli\bin\convert-argv.js:129:7)
    at Array.forEach (<anonymous>)
    at WEBPACK_OPTIONS (D:\Projects\react-ssr-bootstrap-project\node_modules\webpack-cli\bin\convert-argv.js:128:26)
    at requireConfig (D:\Projects\react-ssr-bootstrap-project\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at D:\Projects\react-ssr-bootstrap-project\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! minimal-react-webpack-babel-setup@1.0.0 build-temp: `webpack-dev-server -r ../../../config/webpack/client/register-ts.js --config config/webpack/client/webpack.config.babel.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minimal-react-webpack-babel-setup@1.0.0 build-temp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\AppData\Roaming\npm-cache\_logs\2018-06-24T12_44_40_661Z-debug.log
```

**Comment by TomLingham** [comment]
The path to `register-ts.js` is incorrect. Put `register-ts.js` inside `config/webpack/client/` and try that.

**Comment by budarin** [comment]
@TomLingham 
Thanks a lot for your help and patience!

I'm tired of the struggle and the thousands of little things you need to keep in mind to customize all the tools :)
