### ISSUE TITLE
babel-traverse throws on collisions in different typescript ambient module declarations

### ISSUE THREAD

**Issue by LeanidShutau** [babel/babel#8262]
## Bug Report

**Current Behavior**
`@babel/traverse` tries to throw a `Duplicate declaration` error for key duplicates in different ambient module declarations in one file. `@babel/parser` with `typescript` plugin is used to build an AST.
https://github.com/babel/babel/issues/4640 explains why `Cannot read property 'file' of undefined` is thrown.

**Input Code**
```js
const parse = require('@babel/parser').parse;
const traverse = require('@babel/traverse').default;

const code = `
declare module 'module1' {
  export const variable: string;
}

declare module 'module2' {
  export const variable: number;
}
`;

const ast = parse(code, {
  sourceType: 'module',
  plugins: ['typescript']
});

traverse(ast, {
  enter(path) {
    // smth
  }
});
```
**Output**

```
...\node_modules\@babel\traverse\lib\scope\index.js:347
      throw this.hub.file.buildCodeFrameError(id, `Duplicate declaration "${name}"`, TypeError);
                     ^

TypeError: Cannot read property 'file' of undefined
    at Scope.checkBlockScopedCollisions (...\node_modules\@babel\traverse\lib\scope\index.js:347:22)
    at Scope.registerBinding (...\node_modules\@babel\traverse\lib\scope\index.js:506:16)
    at Scope.registerDeclaration (...\node_modules\@babel\traverse\lib\scope\index.js:454:14)
    at Object.Declaration (...\node_modules\@babel\traverse\lib\scope\index.js:125:12)
    at NodePath._call (...\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (...\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (...\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (...\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (...\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (...\node_modules\@babel\traverse\lib\context.js:144:19)
```

**Expected behavior**
Each module declaration has its own block scope, so the `Duplicate declaration` error shouldn't be thrown. 

**Environment**
- Babel version: v7.0.0-beta.51
- Node/npm version: node 8.11.3 / npm 5.6.0
- OS: Windows 10

**Comment by nicolo-ribaudo** [comment]
@gucong3000 `let a; let a;` should throw. This issue is about declarations inside TS modules.

**Comment by gucong3000** [comment]
@nicolo-ribaudo  But I got the unintended error message: `Cannot read property 'file' of undefined`

**Comment by gucong3000** [comment]
@LeanidShutau I find that this is going to work:
```js
const {
	parse,
	traverse,
} = require("@babel/core");  // 7.0.0-rc.1
const ast = parse("let a;let a", {});
traverse(ast, {});
```

**Comment by liuxingbaoyu** [comment]
has been fixed.
