### ISSUE TITLE
@babel/plugin-proposal-pipeline-operator version upgrade produce problem  - 'proposal' must be one of: minimal While processing

### ISSUE THREAD

**Issue by mengli404** [babel/babel#8277]
before upgrade to **_@babel_plugin-proposal-pipeline-operator@7.0.0-beta.52@@babel**, everything is well , after upgrade version, produce one problem:
```
/.webpackrc.js: 'proposal' must be one of: minimal (While processing: "/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_plugin-proposal-pipeline-operator@7.0.0-beta.52@@babel/plugin-proposal-pipeline-operator/lib/index.js$inherits")
Error: [BABEL] /Users/mengliding/Documents/front_end_repo/network-map/.webpackrc.js: 'proposal' must be one of: minimal (While processing: "/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_plugin-proposal-pipeline-operator@7.0.0-beta.52@@babel/plugin-proposal-pipeline-operator/lib/index.js$inherits")
    at _default (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_plugin-syntax-pipeline-operator@7.0.0-beta.52@@babel/plugin-syntax-pipeline-operator/lib/index.js:26:11)
    at /Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_helper-plugin-utils@7.0.0-beta.52@@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:157:14)
    at cachedFunction (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/caching.js:32:19)
    at loadPluginDescriptor (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:192:28)
    at cache.invalidate.data (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:216:47)
    at CacheConfigurator.invalidate (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/caching.js:149:17)
    at instantiatePlugin (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:216:28)
    at cachedFunction (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/caching.js:32:19)
    at loadPluginDescriptor (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:192:10)
    at config.plugins.map.descriptor (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:68:16)
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:67:38)
    at recurseDescriptors (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:86:27)
    at recurseDescriptors (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:86:27)
    at loadFullConfig (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:100:6)
```

**Comment by mengli404** [comment]
@nicolo-ribaudo I have added these  `["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal" }]`  in `babelrc.js`, but it still can not work

**Comment by nicolo-ribaudo** [comment]
What error do you get now? Can you show your configuration?

**Comment by mengli404** [comment]
@nicolo-ribaudo  my configuration in webpackrc.js:
```
const path = require('path');

export default {
  entry: 'src/index.js',
  outputPath: './build/',
  extraBabelPlugins: [
    ['@babel/plugin-proposal-pipeline-operator', { 'proposal': 'minimal' }],
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
  ],
  env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
    },
  },
  alias: {
    'components': path.resolve(__dirname, 'src/components/'),
    'utils': path.resolve(__dirname, 'src/utils/'),
    'services': path.resolve(__dirname, 'src/services/'),
    'common': path.resolve(__dirname, 'src/common/'),
  },
  ignoreMomentLocale: true,
  theme: './src/theme.js',
  html: {
    template: './src/index.ejs',
  },
  disableDynamicImport: true,
  publicPath: '/',
};
```

the error is still exist:
```
Build failed: [BABEL] /Users/mengliding/Documents/front_end_repo/network-map/.webpackrc.js: 'proposal' must be one of: minimal (While processing: "/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_plugin-proposal-pipeline-operator@7.0.0-beta.52@@babel/plugin-proposal-pipeline-operator/lib/index.js$inherits")
Error: [BABEL] /Users/mengliding/Documents/front_end_repo/network-map/.webpackrc.js: 'proposal' must be one of: minimal (While processing: "/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_plugin-proposal-pipeline-operator@7.0.0-beta.52@@babel/plugin-proposal-pipeline-operator/lib/index.js$inherits")
    at _default (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_plugin-syntax-pipeline-operator@7.0.0-beta.52@@babel/plugin-syntax-pipeline-operator/lib/index.js:26:11)
    at /Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_helper-plugin-utils@7.0.0-beta.52@@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:157:14)
    at cachedFunction (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/caching.js:32:19)
    at loadPluginDescriptor (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:192:28)
    at cache.invalidate.data (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:216:47)
    at CacheConfigurator.invalidate (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/caching.js:149:17)
    at instantiatePlugin (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:216:28)
    at cachedFunction (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/caching.js:32:19)
    at loadPluginDescriptor (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:192:10)
    at config.plugins.map.descriptor (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:68:16)
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:67:38)
    at recurseDescriptors (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:86:27)
    at recurseDescriptors (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:86:27)
    at loadFullConfig (/Users/mengliding/Documents/front_end_repo/network-map/node_modules/_@babel_core@7.0.0-beta.52@@babel/core/lib/config/full.js:100:6)
```

**Comment by nicolo-ribaudo** [comment]
The configuration looks correct. Which software are you using to run it? Maybe it adds another instance of the pipeline proposal plugin.

**Comment by mengli404** [comment]
@nicolo-ribaudo my env as below:
IDE: Vistual Studio Code
Terminal: iTerm2

still the same error msg before

**Comment by destinatis** [comment]
I have this error too. 

`['@babel/preset-stage-0', { decoratorsLegacy: true, pipelineProposal: 'minimal' }]`

This don't work. >:(

**Comment by hzoo** [comment]
Weird

```js
{
  "presets": [
    ["@babel/preset-stage-0", {
    	"decoratorsLegacy": true,
    	"pipelineProposal": "minimal"
    }]
  ]
}
```

either with the preset or the plugin should work. I would make sure everything is the same version (beta.52) and clear cache if necessary (`node_modules/.cache`, or `BABEL_DISABLE_CACHE=true` with `@babel/register`).

**Comment by mengli404** [comment]
Still got the same error, how can I contact you @hzoo , can you help me to debug the problem?

**Comment by nicolo-ribaudo** [comment]
Can you create a repository which reproduces the problem?

**Comment by mAAdhaTTah** [comment]
If the latest version isn't published yet, you'd still be getting the same error, no?

**Comment by mengli404** [comment]
If I changed the version from beta52 to _@babel_plugin-proposal-pipeline-operator@7.0.0-beta.46@@babel, everything is fine, once version update, even add 
```
['@babel/plugin-proposal-pipeline-operator', { 'proposal': 'minimal' }],
```
that's didn't work, sorry, I can not push my code repo to public repo for some security issue problem, @destinatis can you help to share your code to reproduce the problem? 

Finally, I degrade version to beta.46 to solve this problem.

**Comment by nicolo-ribaudo** [comment]
@mengli404 You could create a reduced test case (config + command to run + small sample file).

**Comment by bradennapier** [comment]
this should definitely not be required to use stage-0 if you dont plan to use this at all... i am not using pipeline anywhere and now i am running into a random blocker for no reason

**Comment by mAAdhaTTah** [comment]
Babel is still in beta, so you should expect breaking changes. You can lock your version to avoid problems like this.

Stage 0 proposals are inherently unstable, so should be used with caution. This is part of why they're being removed, because it's too easy to opt into proposals you're not using. If you're going to use unstable proposals, it makes more sense to force you to pick and choose the ones you want and understand the stability choices you're making in doing so.

For the pipeline operator specifically, we added the option to the babel pipeline plugin because there are currently [3 proposals](https://github.com/tc39/proposal-pipeline-operator/) under consideration for the behavior of the operator. We're implementing all three of them in babel so people can try them out and give feedback, allowing us to get a sample of real-world code using the pipeline operator. Users need to be able to toggle between them to be able to choose which one they're using.

I knew this would be breaking when it was introduced, and might be a little annoying, but we really need to be able to get this in the hands of users, and that means landing all the breaking changes before RC, including requiring a new configuration option.

It isn't permanent; once we pick which of the 3 proposals advancing, we deprecate the configuration option and default to the accepted one. Everyone's build continues to work until they can migrate to the accepted version.

**Comment by nicolo-ribaudo** [comment]
What is your configuration?

**Comment by lvsewuyou** [comment]
I  used roadhog，so I uninstall roadhog and then install roadhog by npm uninstall roadhog and npm install roadhog .It works.

**Comment by xyths** [comment]
thanks to **lvsewuyou** 

> I used roadhog，so I uninstall roadhog and then install roadhog by npm uninstall roadhog and npm install roadhog .It works.

it works for me!

**Comment by StrongerSY** [comment]
> I used roadhog，so I uninstall roadhog and then install roadhog by npm uninstall roadhog and npm install roadhog .It works.

Works for me too ~ thx !

**Comment by qiansimin88** [comment]
> I used roadhog，so I uninstall roadhog and then install roadhog by npm uninstall roadhog and npm install roadhog .It works.

nice ~

**Comment by jedwards1211** [comment]
@nicolo-ribaudo based on the errors I saw, it looked like the options validation was happening in `@babel/core`, which was too old in my project and only knew about the `minimal` proposal.  Once I upgraded all babel deps the error went away.  The options validation should happen in `@babel/plugin-proposal-pipeline-operator`

**Comment by mAAdhaTTah** [comment]
@jedwards1211 It does, via the syntax plugin: https://github.com/babel/babel/blob/master/packages/babel-plugin-syntax-pipeline-operator/src/index.js

**Comment by jedwards1211** [comment]
Ah right.  Back in the day I had assumed even the grammar and parsing logic was pluggable, but it's not, right?  All of the parsing lives in core and plugins just turn things on or off?

Maybe there could have been a peerDependency in the plugin to warn about this?

**Comment by jedwards1211** [comment]
Also tbf the error messages hardly made it clear that the parser is what needs to be updated...took me like 30 minutes to guess that was what the problem was

**Comment by mAAdhaTTah** [comment]
Maybe worth updating the error message to say something like "If you expect this proposal to be valid, you may need to update `@babel/core`" or something like that. @nicolo-ribaudo thoughts?

**Comment by jedwards1211** [comment]
Yeah, esp considering that as far as I can tell from this thread no one realized a version mismatch was causing the OP's problem
