### ISSUE TITLE
Babel 7 ignores files outside of project directory

### ISSUE THREAD

**Issue by petrdanecek** [babel/babel#8309]
I think I'm missing something. I recently upgraded up to latest Babel 7 and got lot of issues related to my webpack configuration. I was able to solve all of them expect that I'm not able to import webpack.parts once they are outside of my project directory. I think my problem is related to below symptoms:

this doesn't work, babel ignores the content and nothing is "transpiled"
`./node_modules/.bin/babel ../webpack.snippets.js `

this works fine - the file is transpiled properly
`./node_modules/.bin/babel ./webpack.snippets.js `

The file content is very same. The babel ignores the files outside of my project dir.

ENVs:
node modules installed to my project dir
`PATH_NODE=./node_modules`

```
cat .babelrc
{
  "presets": [
    ["@babel/preset-env", {"debug": true}]
  ]
}
```

The above results in below webpack problems. The main webpack.babel.js is in current project directory and imports ../webpack.snippets.js from outside "shared" directory.
The webpack process all imports properly from local webpack.babel.js which imports the outside located ../webpack.snippets.js . This results in failure:

```
webpack.snippets.js:18

import path from 'path';
^^^^^^

SyntaxError: Unexpected token import
```

The workaround is to copy the webpack.snippets.js to project folder locally, but I would like to share the webpack.snippets across more projects. The babel6 was working fine.

I think I'm missing something in my babelrc file, but not sure.. any thoughts?

**Comment by loganfsmyth** [comment]
What is your project structure, and where are your `.babelrc, `package.json` and `webpack.snippets.js` relative to eachother. We've made changes to restrict the scope of where `.babelrc` files are loaded and depend on that.

**Comment by oliviertassinari** [comment]
Sorry for the noise, I'm dropping it here. I have noticed a similar behavior where this works
```
node_modules/.bin/babel-node ./packages/material-ui-icons/scripts/download.js
```
but this doesn't:
```
cd packages/material-ui-icons
../../node_modules/.bin/babel-node ./scripts/download.js
```

**Comment by loganfsmyth** [comment]
@oliviertassinari That is expected in 7.x, because the working directory is used to decide what packages to consider compilable by default, among other things.

**Comment by loganfsmyth** [comment]
There are kind of two related pieces here.

1. `babel-node` only attempts to compile files that are:
  * Rooted at the current working directory
  * Not inside `node_modules` in the current working directory
2. Assuming a file passes those rules and will be compiled, the logic for how Babel decides what configuration to use also depends on the working directory because the working directory is used to search for `babel.config.js` files, which you may or may not care about.

For 1) you can always override by passing `--ignore ../../**/node_modules` to disable the auto-ignore behavior and say to only ignore `node_modules` or something.
For 2) there is various options you can pass but it's not clear if that matters for you.

It all really depends on your directory structure and how you're actually running Babel in general.

**Comment by oliviertassinari** [comment]
@loganfsmyth Thanks you. It seems my issue is with 1. and only 1. I'm using the following workaround:
```diff
-"download": "../../node_modules/.bin/babel-node ./scripts/download.js",
+"download": "cd ../../ && node_modules/.bin/babel-node packages/material-ui-icons/scripts/download.js",
```

**Comment by petrdanecek** [comment]
In my case all .babelrc, package.json, node_modules are in very same projectDir whilst webpack.snippets.js is outside shared between many projects. Something like:
```
/
|-projectA/
              |-node_modules/
              |-.babel.rc
              |-package.json
              |-webpack.config.js (importing somesthing from shared ../webpack.sneppets.js)
|-projectB/
              |-node_modules/
              |-.babel.rc
              |-package.json
              |-webpack.config.js (importing somesthing from shared ../webpack.sneppets.js)
|-webpack.snippets.js
```

**Comment by petrdanecek** [comment]
just adding to above post, the projectA and projectB are standalone and they are bundled individually. The goal is to share the webpack configuration only...

Is there any way how to achieve above?

**Comment by loganfsmyth** [comment]
@petrdanecek What specifically are your expectations? What should be compiled with what settings?

**Comment by petrdanecek** [comment]
@loganfsmyth 
Well I think that the import from outside of project root directory (with .babel.rc) should work.
Example:
```
/
|-projectA/
              |-node_modules/
              |-.babel.rc
              |-package.json
              |-webpack.babel.js (importing somesthing from shared ../webpack.sneppets.js)
|-webpack.snippets.js
```

Current behavior:
```
cd projectA
NODE_PATH=./node_modules node_modules/.bin/webpack --config webpack.babel.js
> webpack.snippets.js:18
> import path from 'path';
> ^^^^^^
> SyntaxError: Unexpected token import
```

Expected behavior:
webpack.snippets.js imported by webpack.babel.js is processed by babel as well so the import works fine.

as I said the workaround is to make local copy of webpack.snippets.js to project root so webpack.babel.js imports it from the same folder, but I want to share the snippets across many projects. Is there any way how to achieve it?

**Comment by petrdanecek** [comment]
[I think this is the similar issue having same root cause](https://stackoverflow.com/questions/49033126/external-imports-in-babel-7-do-not-get-transpiled)

**Comment by PinkaminaDianePie** [comment]
I have exactly the same issue, monorepo with some shared files between the projects. I can't find a proper workaround for that, for now I forced to have one huge package.json in the root folder and share same babel config for all of the projects inside, but it's a really ugly workaround. Are there any better ways?

**Comment by ivosabev** [comment]
What would the proper solution be for a lerna monorepo? I have a Node server code that includes untranspiled ES6 code helpers and I get "Unexpected import" error, since the code in helpers is not transpiled. CRA@next works just fine with the ES6 code in the helpers folder.

Example:
```
packages
  client (CRA@next)
  server
  helpers
lerna.json
package.json
babel.config.js
```

babel.config.js
```
module.exports = {
  "presets": ["@babel/env", "react-app"],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": false,
        "helpers": true,
        "regenerator": true,
        "useESModules": false
      }
    ]
  ]
}
```

package.json
```
"@babel/core": "7.0.0-rc.3",
"@babel/node": "7.0.0-rc.3",
"@babel/plugin-transform-runtime": "7.0.0-rc.3",
"@babel/preset-env": "7.0.0-rc.3",
"@babel/runtime": "7.0.0-rc.3",
"babel-preset-react-app": "next"
```

Since helpers comes from node_modules it is not transpiled. If I do `import helpers from '../../helpers'` in `server/src/index.js` it works.

**Comment by euvl** [comment]
Same question as above tbh. We are using monorepo for our web projects and I am having difficulty with importing shared utilities.

**Comment by loganfsmyth** [comment]
Using the `babel.config.js` file like in the example is likely the best way, but depending on how you run Babel, you may still need to pass it the path of the config file. It will find the `babel.config.js` if the working directory of the build is the root of the monorepo, but if the working directory of your builds is elsewhere, you'll need to set the [`"configFile"`](http://babeljs.io/docs/en/options#configfile) option so it knows about it.

**Comment by loganfsmyth** [comment]
Also for those coming across this, please read through http://babeljs.io/docs/en/config-files if you haven't already.

**Comment by petrdanecek** [comment]
the babel.config.js is probably solution for the monorepo, but how to use it with .babelrc - the webpack configuration load? I read the http://babeljs.io/docs/en/config-files without any luck..
The "configFile" is not recommended to be used with .babelrc...

**Comment by sibelius** [comment]
@adityak74 we have this playground boilerplate for monorepo https://github.com/entria/entria-fullstack

can you try adding a common package and consume in another of the packages?

**Comment by adityak74** [comment]
Sure, I will go ahead and give this a try and get back on this thread here.

**Comment by adityak74** [comment]
@sibelius I did try consuming one of my utility functions. I am having no luck in getting it transpiled. Thanks for the boilerplate 👍 . Do you know any other repos consuming functions from their other repos? I don't see the `entria-fullstack` doing something like that and have been trying to find an example repos to follow through.

**Comment by sibelius** [comment]
can you open an issue about it? or send a PR to add it? we gonna add a shared package soon, to reproduce all the issues

you can try this one https://github.com/slanatech/vue-monorepo-boilerplate, but there is no babel at all

**Comment by adityak74** [comment]
@sibelius 
I have a repo that reproduces this issue, if you want to try taking a look at. I hope my configuration looks correct. https://github.com/adityak74/babel7-import-example

**Comment by sibelius** [comment]
I think in your case you need to have a babel.config.js and use babelrcRoots to indicate which packages babel should transpile

**Comment by adityak74** [comment]
Thanks for the help! I was little confused on how to use babelrcRoots maybe that should solve the issue. I will keep this thread posted.

**Comment by adityak74** [comment]
Okay, I moved the config from `.babelrc` to `babel.config.js` for the `babel7/main` repo. The external remains unchanged. I am still hitting `import undefined`. Did I do it right maybe? Sorry, if am kind of bugging here but I am just trying to create a working example so that it helps everyone. 

https://github.com/adityak74/babel7-import-example/blob/master/babel7/main/babel.config.js

**Comment by adityak74** [comment]
Okay I figured it out. It was basically `babel-node` ignoring the files outside the project itself. So you can set `--ignore='node_modules'` when you compile using `babel-node ` to get the modules outside of your project to transpile.

**Comment by sibelius** [comment]
doing `--ignore='node_modules'`, babel-node will not ignore  `node_modules`? or it will ignore node_modules and transpile the rest of the packages?

how this affects the transpiled version of code?

**Comment by adityak74** [comment]
> doing --ignore='node_modules', babel-node will not ignore node_modules? or it will ignore node_modules and transpile the rest of the packages?

Yes, that would only ignore `node_modules` and not the other (outside of cwd()) which is set in by default.

> how this affects the transpiled version of code?

I haven't gotten to test a code which is already transpiled but certainly `ignore` flag should take care of those files.

Also, as a fact, even this `--ignore=' '` works. With babel 7 processing only from the root which is os.cwd() which would be my current package but my imported code from another monorepo doesn't get transpiled without having `ignore` flag. So, I think just overriding the default `ignore` will make sure that files imported from outside of the current packages are transpiled correctly. 

The issue I see here is with the new Babel 7 only with respect to a monorepo setup:

1. `babel.config.js` - should be on the root.
2. Since, the monorepo setup, the `babelrc` file searching is restricted to the first occurrence of package.json which stop babel to get to the root config.
3. When in a monorepo setup, packages importing other monorepo  sources are not being compiled due to babel search being restricted, and the workaround would be to override the `--ignore`. Until I go from being dumb to sensible and configure my `babel.config.js` settings properly.

**Comment by adityak74** [comment]
I went ahead and made an npm library that actually tranverses and executes webpack commands as babel searching is restricted to os.cwr() being trated as root especially for lerna monorepo or monorepo structures applications. https://github.com/adityak74/lerna-babel7-webpack-exec 

Also, this library is not restricted to lerna as such. It basically traverses to root and executes scripts which makes sure that babel traverses to the actuall root of the application to grab `babel.config.js` setup at the root.

**Comment by nicolo-ribaudo** [comment]
Isn't it the same as using Babel's `--root-mode upward` option?

**Comment by Izhaki** [comment]
# Working Example

As I've struggled with this myself, here's a [working mono-repo](https://github.com/Izhaki/codinsky/tree/e0de8fa9fef562f10493378fd649fdf4aeb34293) that involves:

- Babel 7
- Lerna
- Yarn workspaces
- Webpack
- Rollup
- Bundler-free transpilation (for tests)

I hope this will help some.

Only the important bits:

[/package.json](https://github.com/Izhaki/codinsky/blob/e0de8fa9fef562f10493378fd649fdf4aeb34293/package.json):

```json
  "workspaces": [
    "packages/*",
    "website"
  ],
```

[/babel.config.js](https://github.com/Izhaki/codinsky/blob/e0de8fa9fef562f10493378fd649fdf4aeb34293/babel.config.js):

```js
const aliases = require('./aliases.config');

module.exports = {
  presets: ['@babel/preset-env'],
  plugins: [
    [
      'module-resolver',
      {
        // https://github.com/tleunen/babel-plugin-module-resolver/issues/338
        // There seem to be a bug with module-resolver with a mono-repo setup:
        // It doesn't resolve paths correctly when using root/alias combo, so we
        // use this function instead.
        resolvePath(sourcePath) {
          // This will return undefined if aliases has no key for the sourcePath,
          // in which case module-resolver will fallback on its default behaviour.
          return aliases[sourcePath];
        },
      },
    ],
  ],
};
```

[/packages/parse/rollup.config.js](https://github.com/Izhaki/codinsky/blob/e0de8fa9fef562f10493378fd649fdf4aeb34293/packages/parse/rollup.config.js):

```js
const esm = [
  {
    input,
    output: { file: 'dist/esm/index.js', format: 'esm' },
    plugins: [
      // Note: rollup-plugin-babel automatically set modules:false with babel 7
      babel({
        // Pick up our root babel.config.js
        rootMode: 'upward',
        exclude: /node_modules/,
      }),
    ],
  },
];
```

[/website/webpack.config.js](https://github.com/Izhaki/codinsky/blob/e0de8fa9fef562f10493378fd649fdf4aeb34293/website/webpack.config.js):

```js
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          // Pick up our root babel.config.js
          rootMode: 'upward',
          presets: [
            [
              '@babel/preset-env',
              {
                // Do not transform ES6 modules to another format.
                // Webpack will take care of that.
                modules: false,
              },
            ],
          ],
        },
      },
```

[/packages/curate/cucumber.config.js](https://github.com/Izhaki/codinsky/blob/e0de8fa9fef562f10493378fd649fdf4aeb34293/packages/curate/cucumber.config.js):

```js
require('@babel/register')({
  // Find babel.config.js up the folder structure.
  rootMode: 'upward',

  // Since babel ignores all files outside the cwd, it does not compile sibling packages
  // So rewrite the ignore list to only include node_modules
  ignore: ['node_modules'],
});
```

(Thanks @adityak74 for the last one.)

---

Anyhow, I believe this issue has diverged from the original post. Close?

**Comment by FeklistovGleb** [comment]
--ignore ../../**/node_modules - why this works only from console, maybe add this section in babel.config.js?

**Comment by PinkaminaDianePie** [comment]
Does anybody really know how to solve this issue? I still forced to use some ugly workarounds like one `.babelrc` per whole project, and run babel not from different folders inside, but from the root.
Is there  any clear way how to ask babel to also include some directory outside of current root? 
 @loganfsmyth

**Comment by scythargon** [comment]
I'm confused that there is no any (hopefully - positive) feedback to @Izhaki 's post above https://github.com/babel/babel/issues/8309#issuecomment-449515834

**Comment by scythargon** [comment]
I've tried to follow @Izhaki 's recommendations and got my project building (no need to publish it since it is a private one) but now the React component I'm importing from a sibling package does not get access to the `state` even though it is wrapped with `Provider`. :( But if I just manually copy this component into that package which I'm trying to build - it works.
![image](https://user-images.githubusercontent.com/1755870/52277658-10ba4280-2977-11e9-95b6-8b75ab17ead9.png)

**Comment by PavelKastornyy** [comment]
I am surprised that Babel developers haven't clarified this issue yet although half year has passed. It is hard to believe that they didn't foresee such problem when they decided to implement such restriction. How to explain their silence?

**Comment by PavelKastornyy** [comment]
I solved this problem. My project [script4j](https://github.com/PavelKastornyy/script4j) has the following structure:

```
script4j
|
|-modules
|   |-script4j.base
|   |      |-node_modules
|   |      |-package.json
|   |      |-gulpfile.js
|   |      |-tasks.js
|   |-script4jfx.base
|   |      |-node_modules
|   |      |-package.json
|   |      |-gulpfile.js
|   |      |-tasks.js
|   |-script4jfx.graphics
|   |      |-node_modules
|   |      |-package.json
|   |      |-gulpfile.js
|   |      |-tasks.js
|-scripts
|    |-gulptasks.js
|    |-babelregister.js
|-babel.config.js
|-package.json
```
As you see I have three modules. Module `script4jfx.base` depends on `script4j.base`. Module `script4jfx.graphics` depends on `script4j.base` and `script4jfx.base`. 

In my project I use babel for gulp and mocha tests. I will explain how I use it for gulp, for mocha it is used the same way - you can see `scripts/gulptasks.js` file for details.
So,
1) All babel dependencies are only in `script4j/package.json`. No one module `package.json` has babel dependencies.
2) The entry point of module gulp tasks is `script4j/modules/moduleName/gulpfile.js`:
```
require('./../../scripts/babelregister');
require('./tasks');
```
3) `script4j/scripts/babelregister.js` sets `@babel/register` and makes babel find `babel.config.js`:
```
require('@babel/register')({
    rootMode: "upward",
    ignore: [/node_modules/]
});
```
4) `babel.config.js` has all the settings for babel. No one module has .babelrc file. Babel.config:

```
module.exports = function (api) {
    api.cache(true);
    return {
        babelrcRoots: [
            '.',
            './modules/*'
        ],
	ignore: [/node_modules/],
        presets: ["@babel/preset-env"]
    };
}
```

**Comment by nmccready** [comment]
@Izhaki  you are a blessing. Wow this got me 99% of the way. The last bit (was clutch) was removing all dependencies which had `"somemodule": file:/...SOME_PATH/TO_YOUR_PACKAGE_OR _MODULE` in the `package.json`.

Without doing the above webpack could not compile react code via babel for some unknown reason.

**Comment by steve-taylor** [comment]
The old Babel 6 behaviour was perfectly fine. I'm trying to understand why it was changed in version 7 and how to get the version 6 behaviour to work in version 7, but after reading about it several times I still can't make sense of any of it.

The great thing about version 6 was that it encouraged libraries to be distributed as source, so that when a project and all its dependencies are transpiled together, each dependency's `.babelrc` file is used when transpiling it. That doesn't seem to be the case anymore. Babel 7 is encouraging library authors to transpile to ES5, although even that's deprecated now, so the workaround is to target ancient browsers via `@babel/preset-env`'s `targets`.

**Comment by esr360** [comment]
What do I need to add to my `babel.config.js` file in order to be able to transpile files outside of my project directory? The question is simple. Adding `ignore: [/node_modules/],` doesn't work.

**Comment by jjeeknowre** [comment]
I had this same issue. I'm working in a monorepo, and the file structure is as follows: 

```
monorepo
|-packages
|   |-package1
|   |   |-node_modules
|   |   |-src
|   |   |-package.json
|   |   |-.babelrc
|   |   |-webpack.config.js
|   |-package2
|   |   |-node_modules
|   |   |-src
|   |   |-package.json
|   |   |-.babelrc
|   |   |-webpack.config.js
|-package.json
```

where `package1` was using `package2` in its build.

This was my solution:
`package1/webpack.config.js`:
```
module.exports = {
   ...
   module: {
       rules: [
            ...
            {
                test: /\.(js)$/,
                loader: 'babel-loader',
                options: {
                rootMode: 'upward'
                }
           }
        ]
    },
   ...
}
```

And then I added `babel.config.js` in `monorepo`
```
module.exports = (api) => {
	api.cache(false); // set cache as true/false
  
	return {
		presets: [ ... ],
		plugins: [ ... ],
		// optional if you want to use local .babelrc files
	 	babelrcRoots: [".", "packages/*"]
	};
};
```

Since my `.babelrc` files were the same, I removed them, which left me with the following:
```
monorepo
|-packages
|   |-package1
|   |   |-node_modules
|   |   |-src
|   |   |-package.json
|   |   |-webpack.config.js
|   |-package2
|   |   |-node_modules
|   |   |-src
|   |   |-package.json
|   |   |-webpack.config.js
|-package.json
|-babel.config.js
```

I hope this helps. I wonder if there's an easier way to do this instead of having to create a `babel.config.js` file in the root directory.

**Comment by vlad0337187** [comment]
The only working approach for me was adding `--ignore=' '` to cli command.
So command looks like:
`babel-node --ignore=' ' --root-mode upward --extensions '.ts' ./src/index.ts\"`

(versions:
    "@babel/cli": "^7.6.4",
    "@babel/core": "^7.6.4",
    "@babel/node": "^7.6.3",
)

But it's just a workaround, not a solution for this issue.

**Comment by iampava** [comment]
Hey!

Just ran across the same issue. We kinda have a monorepo structure - although we're not using Lerna atm - and wanted to import a file from outside the current project root. Specifically, we wanted to import `realtime.js` inside `/client` app.


```
/monorepo
  /client
    .babelrc
    package.json
    webpack.config.js
  /common
    realtime.js
```

However, `realtime.js` was using [Nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) operator and thus `/client` build was failing with the error below: 

```
ERROR in ../common/dist/realtime.js 8:56
Module parse failed: Unexpected token (8:56)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
...
...
...
i ｢wdm｣: Failed to compile.
```

However, if we moved the file inside `/client`, everything was ok since we are using `@babel/plugin-proposal-optional-chaining`.

The solution we found was to use `configFile` parameter to `babel-loader`:

```
{
  test: /\.(tsx?|js)$/,
  // use: 'babel-loader',
  exclude: /node_modules/,
  use: {
    loader: 'babel-loader',
    options: {
      configFile: resolve(__dirname, '.babelrc'),
    },
  },
},
```

**Comment by kentandersen** [comment]
@iampava We had the exact same issue. Solved it by using the following babel-loader config. 

```
{
  test: /\.js$/,
  exclude: /node_modules/,
  use: {
    loader: 'babel-loader',
    options: {
      configFile: path.resolve(__dirname, '.babelrc'),
      babelrcRoots: ['../*'],
     },
  },
}
```

**Comment by rijnhard** [comment]
same issue but different use case:
Intellij has scratch file functionality where it will create a temporary file to test something in.
It does so in a very different directory to the project, but allows me to run the file using project configuration.

The run command then looks like this
```
/Data/Projects/test-scratch/node_modules/.bin/babel-node /home/rijnhard/.config/JetBrains/PhpStorm2020.3/scratches/scratch_1.es

(node:348289) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/rijnhard/.config/JetBrains/PhpStorm2020.3/scratches/scratch_1.es:1
import { database } from '../../../../../../Data/Projects/test-scratch/src/db';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module._compile (/Data/Projects/test-scratch/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .es] (/Data/Projects/test-scratch/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at Object.<anonymous> (/Data/Projects/test-scratch/node_modules/@babel/node/lib/_babel-node.js:170:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

Process finished with exit code 1
```

using the `--ignore=' '` trick just breaks it in a different way
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Data/Projects/test-scratch/''
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at Object.<anonymous> (/Data/Projects/test-scratch/node_modules/@babel/node/lib/_babel-node.js:170:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Process finished with exit code 1
```

**Comment by armordog** [comment]
Since this is still a problem, can we have a babelrc option that re-enables the original babel 6 behaviour?

**Comment by oshihirii** [comment]
is there any official documentation that explains how to do the following:
  
- transpile all direct and descendant imported files within your project, 
- regardless of the folder they are in, 
- except for `/node_modules`

example project structure - all imported files should be transpiled:
```
- node_modules
- app.js               <---------------------- imports the file '01_01.js'  
- package.json
- folder_01
-- 01_01.js            <---------------------- imports the file '02_02.js'  
-- 01_02.js 
- folder_02
-- 02_01.js
-- 02_02.js            <---------------------- imports the file '03b_01.js'
- folder_03
-- folder_03b
--- 03b_01.js
```

**Comment by nicolo-ribaudo** [comment]
@oshihirii You can use a top-level `babel.config.json` file and add [`"ignore": "**/node_modules/**"`](https://babeljs.io/docs/en/options#ignore).

**Comment by oshihirii** [comment]
**Short Version:**

Imported files are not being transpiled after creating `babel.config.json` file in project root directory with these contents:
```js
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "node": "current"
                }
            }
        ]
    ],
    "ignore": ["**/node_modules/**"]
}
```  
And then running `npm run build-server-file` which is:
```  
babel app_before_babel.js --out-file app.js  
```

**Long Version:**

I looked at these links:  

 - https://babeljs.io/docs/en/options#ignore  
 - https://babeljs.io/docs/en/configuration#babelconfigjson *
 - https://babeljs.io/docs/en/config-files#root-babelconfigjson-file ** 

I took these steps:  

**01)** Create a file in the root directory of the project named `babel.config.json`:  
```js
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "node": "current"
                }
            }
        ]
    ],
    "ignore": ["**/node_modules/**"]
}
```  
**02)**  Run the `npm script` which is:      
```
babel app_before_babel.js --out-file app.js
```
**03)**   The build completes, but I get this error when trying to run the app:
```
SyntaxError: Unexpected token 'export'   
```
**04)**   My understanding is that means the file was not transpiled.    

*** note:  I do not understand why there is JSON *and* JavaScript displayed at the [babel.config.json](https://babeljs.io/docs/en/configuration#babelconfigjson) link, ie:
```js
// json  
{
  "presets": [...],
  "plugins": [...]
}
```
*and:*  
```js
// JavaScript
module.exports = function (api) {
  api.cache(true);

  const presets = [ ... ];
  const plugins = [ ... ];

  return {
    presets,
    plugins
  };
}
```  
** note: i also don't understand how you can put a `console.log()` statement in a `.json` file, per the instructions at the [Root babel.config.json file](https://babeljs.io/docs/en/config-files#root-babelconfigjson-file) link, ie:  

>  One helpful way to test if your config is being detected is to place a `console.log()` call inside of it if it is a `babel.config.json` JavaScript file: the log will execute the first time Babel loads it.

**Comment by nicolo-ribaudo** [comment]
It's because you are only passing the `app_before_babel.js` file to the Babe cli. You probably want to compile the full directory:
```
babel app_directory --out-dir compiled_app_directory
```
https://babeljs.io/docs/en/babel-cli#compile-directories

---

You can have both JS and JSON config file (as explained in the [previous docs section](https://babeljs.io/docs/en/config-files#supported-file-extensions)); we should reword the `console.log` suggestion because it doesn't apply to `.json` files but onl to JavaScript files.

**Comment by mrShturman** [comment]
Is this bug not solved yet?

I just got the same issue in monorepo like this
```
monorepo
|- common/
|   |- .babelrc.js
|- packageA/
|   |- .babelrc.js
|- packageB/
|   |- .babelrc.js
|- .babel.config.json
|- package.json
```

I try to import something from common.

Result:
```
import path from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by aaronamm** [comment]
@joshjee your solution is helpful. Thank you so much.
