### ISSUE TITLE
[Babel 7][plugin-proposal-object-rest-spread] TypeError: Property value of ObjectProperty expected node to be of a type

### ISSUE THREAD

**Issue by dr-js** [babel/babel#8323]
## Bug Report

**Current Behavior**
With `7.0.0-beta.53`, setting `loose: true` for `@babel/plugin-proposal-object-rest-spread` and compiling some ES2018 Rest Properties code will produce error: 

`TypeError: Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got null`

This does not happen with `7.0.0-beta.51`.

**Input Code**

```js
// test-babel.js

const f = ({ a, b = 0, ...z }) => {} // will produce error
// const f = ({ a, ...z }) => {} // will pass
```
**Babel Configuration**

```js
// babel.config.js

module.exports = {
  presets: [ [ '@babel/env', { targets: { node: '8' } } ] ],
  plugins: [ [ '@babel/plugin-proposal-object-rest-spread', { loose: true } ] ]
}
```

```json
// package.json

{
  "dependencies": {
    "@babel/cli": "7.0.0-beta.53",
    "@babel/core": "7.0.0-beta.53",
    "@babel/preset-env": "7.0.0-beta.53"
  }
}
```

**The Error**

```
> npx babel test-babel.js -o test-babel-o.js
TypeError: Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got null
    at Object.validate (PATH\node_modules\@babel\types\lib\definitions\utils.js:128:13)
    at Object.validate (PATH\node_modules\@babel\types\lib\validators\validate.js:17:9)
    at NodePath._replaceWith (PATH\node_modules\@babel\traverse\lib\path\replacement.js:194:9)
    at NodePath._remove (PATH\node_modules\@babel\traverse\lib\path\removal.js:51:10)
    at NodePath.remove (PATH\node_modules\@babel\traverse\lib\path\removal.js:30:8)
    at Object.keys.forEach.bindingName (PATH\node_modules\@babel\plugin-proposal-object-rest-spread\lib\index.js:136:40)
    at Array.forEach (<anonymous>)
    at removeUnusedExcludedKeys (PATH\node_modules\@babel\plugin-proposal-object-rest-spread\lib\index.js:131:27)
    at VariableDeclarator.path (PATH\node_modules\@babel\plugin-proposal-object-rest-spread\lib\index.js:247:13)
    at NodePath._call (PATH\node_modules\@babel\traverse\lib\path\context.js:53:20)
```

**Environment**
- Babel version(s): 7.0.0-beta.53
- Node/npm version: Node 10.5/npm 6.1
- OS: Windows 10
- How you are using Babel: `cli`

**Comment by milesj** [comment]
Has this been looked into yet?
