### ISSUE TITLE
SyntaxError: Unexpected token import on webpack dynamic import with server side rendering

### ISSUE THREAD

**Issue by againksy** [babel/babel#8384]
i have server side rendering and using webpack dynamic imports
on server package.json
```
    "@babel/core": "^7.0.0-beta.54",
    "@babel/preset-env": "^7.0.0-beta.54",
    "@babel/register": "^7.0.0-beta.54",
    "babel-plugin-dynamic-import-node": "^2.0.0",
    "babel-plugin-dynamic-import-node-babel-7": "^2.0.7"

```
on client package.json:
```
    "@babel/core": "^7.0.0-beta.54",
    "@babel/plugin-proposal-decorators": "^7.0.0-beta.54",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0-beta.54",
    "@babel/preset-env": "^7.0.0-beta.54",
    "@babel/preset-react": "^7.0.0-beta.54",
    "@babel/preset-stage-0": "^7.0.0-beta.54",
    "babel-loader": "^8.0.0-beta.4",
    "babel-plugin-dynamic-import-node": "^2.0.0",
    "babel-plugin-dynamic-import-node-babel-7": "^2.0.7",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-runtime": "^6.26.0",

```
server index.js
```
require("@babel/register")({
  "plugins": ["dynamic-import-node"],
  presets: [ '@babel/preset-react', '@babel/preset-env', '@babel/preset-stage-0', ],
});
```
webpack on client side
```
		rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          "plugins": ["@babel/plugin-syntax-dynamic-import"],
          presets: [ '@babel/preset-react',
            '@babel/preset-env',
            '@babel/preset-stage-0', ]
        }
      },
```

client starts okey.
but when starting server i got:
```
node server.js 
/Users/z/project//src/containers/List.js:1
(function (exports, require, module, __filename, __dirname) { import React, { Component, } from 'react';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (/Users/z/project/src/_server/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/Users/z/project/src/_server/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

```
as you can see i tried both the  "babel-plugin-dynamic-import-node": "^2.0.0", and "babel-plugin-dynamic-import-node-babel-7": "^2.0.7"

**Comment by ccinelli** [comment]
Similar problem with babel@7

**Comment by nicolo-ribaudo** [comment]
What is your directory structure?

**Comment by nicolo-ribaudo** [comment]
Closing as I didn't receive any response for 6 months. Please follow up at #8249.
