### ISSUE TITLE
Error "corejs is not a valid Plugin property"

### ISSUE THREAD

**Issue by chawax** [babel/babel#8451]
I am upgrading a React Native app from 0.55.3 to 0.56.0 and so to Babel 7.
To solve an Android release build problem I try to add corejs to my project.

My `babel.config.js` file (I had to replace `.babelrc` file so Babel 7 could work with Jest) :

```
module.exports = function (api) {
  api.cache(true)
  const presets = ['react-native']
  const plugins = [
    '@babel/plugin-transform-runtime',
    {
      corejs: 2,
    },
  ]

  return {
    presets,
    plugins,
  }
}
```

And my Babel dependencies in `package.json` :

```
{
  ...
  "dependencies": {
    "@babel/runtime-corejs2": "7.0.0-rc.1",
    "react": "16.4.1",
    "react-native": "0.56.0",
    ...
  },
  "devDependencies": {
    "@babel/core": "7.0.0-rc.1",
    "@babel/plugin-transform-runtime": "7.0.0-rc.1",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "7.1.1",
    "babel-jest": "23.4.2",
    "babel-plugin-ignite-ignore-reactotron": "0.3.0",
    "babel-plugin-transform-react-remove-prop-types": "0.4.13",
    "babel-preset-react-native": "5.0.2",
    ...
  },
 ...
}
```

But when I start my app or try to bundle it I have this error :

```
/Users/administrateur/***-app/node_modules/@babel/core/lib/config/full.js:127
    throw e;
    ^

Error: [BABEL] /Users/administrateur/***-app/node_modules/react-native/local-cli/cliEntry.js: .corejs is not a valid Plugin property
    at Object.keys.forEach.key (/Users/administrateur/***-app/node_modules/@babel/core/lib/config/validation/plugins.js:52:56)
    at Array.forEach (<anonymous>)
    at validatePluginObject (/Users/administrateur/***-app/node_modules/@babel/core/lib/config/validation/plugins.js:50:20)
    at instantiatePlugin (/Users/administrateur/***-app/node_modules/@babel/core/lib/config/full.js:201:55)
    at cachedFunction (/Users/administrateur/***-app/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPluginDescriptor (/Users/administrateur/***-app/node_modules/@babel/core/lib/config/full.js:192:10)
    at config.plugins.map.descriptor (/Users/administrateur/***-app/node_modules/@babel/core/lib/config/full.js:68:16)
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/administrateur/***-app/node_modules/@babel/core/lib/config/full.js:67:38)
    at loadFullConfig (/Users/administrateur/***-app/node_modules/@babel/core/lib/config/full.js:100:6)
```

I looked into `plugin-transform-runtime` source code and `corejs` is the right name for the property.

Any idea what my problem is ?

**Comment by existentialism** [comment]
@chawax you must use the same version of `@babel/*` deps as the react-native preset, which as of [5.0.2](https://unpkg.com/babel-preset-react-native@5.0.2/package.json) is beta.47

**Comment by loganfsmyth** [comment]
When passing options, each item in `plugins` needs to be an array of its own, so
```
  const plugins = [
    '@babel/plugin-transform-runtime',
    {
      corejs: 2,
    },
  ]
```
should actually be
```
  const plugins = [
    ['@babel/plugin-transform-runtime', {
      corejs: 2,
    }],
  ]
```

**Comment by chawax** [comment]
Thanks @loganfsmyth , I had not seen that ! It solved my problem.

**Comment by hzoo** [comment]
Closing then, not sure if we can really provide a better message here really (suggest that you are probably passing the option to the plugin array instead of the plugin option)
