### ISSUE TITLE
TypeError in @babel/plugin-transform-runtime

### ISSUE THREAD

**Issue by pronebird** [babel/babel#8457]
Transform runtime plugin does not work anymore 😢 

```
$ babel --version
7.0.0-rc.1 (@babel/core 7.0.0-rc.1)

$ cat package.json | grep @babel
    "@babel/cli": "^7.0.0-rc.1",
    "@babel/core": "^7.0.0-rc.1",
    "@babel/plugin-proposal-class-properties": "^7.0.0-rc.1",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-rc.1",
    "@babel/plugin-transform-runtime": "^7.0.0-rc.1",
    "@babel/preset-env": "^7.0.0-rc.1",
    "@babel/preset-flow": "^7.0.0-rc.1",
    "@babel/preset-react": "^7.0.0-rc.1",
    "@babel/runtime": "^7.0.0-rc.1"

$ babel src/ --copy-files --out-dir build
TypeError: helpers(...).minVersion is not a function
    at File.availableHelper (~/project/app/node_modules/@babel/core/lib/transformation/file/file.js:178:30)
    at file.set.name (~/project/app/node_modules/@babel/plugin-transform-runtime/lib/index.js:100:45)
    at File.addHelper (~/project/app/node_modules/@babel/core/lib/transformation/file/file.js:193:19)
    at PluginPass.addHelper (~/project/app/node_modules/@babel/core/lib/transformation/plugin-pass.js:31:22)
    at buildClassPropertySpec (~/project/app/packages/components/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:245:81)
    at PluginPass.Class (~/project/app/packages/components/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:424:30)
    at newFn (~/project/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (~/project/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (~/project/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (~/project/app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:88:12)
error Command failed with exit code 1.
```

`.babelrc`:

```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": { 
        "node": "8.9" 
      }
    }],
    "@babel/preset-react",
    "@babel/preset-flow"
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

**Comment by pronebird** [comment]
Whoa. Aligned the versions across packages. Seems to work now! Thanks!
