### ISSUE TITLE
babel-register does not seem to load plugins

### ISSUE THREAD

**Issue by pronebird** [babel/babel#8458]
## Bug Report

**Current Behavior**

I am running mocha (v5.2.0) with `@babel/register` and it does not seem to strip flow types which makes me think that it does not read `.babelrc`.

`babel src/ --copy-files --out-dir build` works fine on the other side.

```
yarn test
yarn run v1.9.4
$ mocha -R spec --compilers js:@babel/register --require "test/setup.js" "test/**/*.spec.js"
~/project/app/node_modules/@babel/register/node_modules/@babel/core/lib/transformation/normalize-file.js:174
    throw err;
    ^

SyntaxError:~/project/app/packages/components/test/AccountInput.spec.js: Unexpected token, expected "," (13:28)

  11 |   };
  12 | 
> 13 |   const render = (mergeProps: $Shape<React.ElementProps<typeof AccountInput>>) => {
     |                             ^
  14 |     const defaultProps: React.ElementProps<typeof AccountInput> = {
  15 |       value: '',
  16 |       onEnter: null,
    at _class.raise (~/project/app/node_modules/babylon/lib/index.js:776:15)
    at _class.unexpected (~/project/app/node_modules/babylon/lib/index.js:2079:16)
    at _class.expect (~/project/app/node_modules/babylon/lib/index.js:2067:28)
    at _class.parseParenAndDistinguishExpression (~/project/app/node_modules/babylon/lib/index.js:3283:14)
    at _class.parseExprAtom (~/project/app/node_modules/babylon/lib/index.js:3113:21)
    at _class.parseExprAtom (~/project/app/node_modules/babylon/lib/index.js:8185:52)
    at _class.parseExprSubscripts (~/project/app/node_modules/babylon/lib/index.js:2757:21)
    at _class.parseMaybeUnary (~/project/app/node_modules/babylon/lib/index.js:2736:21)
    at _class.parseExprOps (~/project/app/node_modules/babylon/lib/index.js:2643:21)
    at _class.parseMaybeConditional (~/project/app/node_modules/babylon/lib/index.js:2615:21)
    at _class.parseMaybeAssign (~/project/app/node_modules/babylon/lib/index.js:2562:21)
    at _class.parseVar (~/project/app/node_modules/babylon/lib/index.js:4582:26)
    at _class.parseVarStatement (~/project/app/node_modules/babylon/lib/index.js:4412:10)
    at _class.parseStatementContent (~/project/app/node_modules/babylon/lib/index.js:4012:21)
    at _class.parseStatement (~/project/app/node_modules/babylon/lib/index.js:3962:17)
    at _class.parseBlockOrModuleBlockBody (~/project/app/node_modules/babylon/lib/index.js:4513:23)
    at _class.parseBlockBody (~/project/app/node_modules/babylon/lib/index.js:4500:10)
    at _class.parseBlock (~/project/app/node_modules/babylon/lib/index.js:4489:10)
    at _class.parseFunctionBody (~/project/app/node_modules/babylon/lib/index.js:3754:24)
    at _class.parseArrowExpression (~/project/app/node_modules/babylon/lib/index.js:3706:10)
    at _class.parseParenAndDistinguishExpression (~/project/app/node_modules/babylon/lib/index.js:3322:12)
    at _class.parseExprAtom (~/project/app/node_modules/babylon/lib/index.js:3113:21)
    at _class.parseExprAtom (~/project/app/node_modules/babylon/lib/index.js:8185:52)
    at _class.parseExprSubscripts (~/project/app/node_modules/babylon/lib/index.js:2757:21)
    at _class.parseMaybeUnary (~/project/app/node_modules/babylon/lib/index.js:2736:21)
    at _class.parseExprOps (~/project/app/node_modules/babylon/lib/index.js:2643:21)
    at _class.parseMaybeConditional (~/project/app/node_modules/babylon/lib/index.js:2615:21)
    at _class.parseMaybeAssign (~/project/app/node_modules/babylon/lib/index.js:2562:21)
    at _class.parseExprListItem (~/project/app/node_modules/babylon/lib/index.js:3824:18)
    at _class.parseCallExpressionArguments (~/project/app/node_modules/babylon/lib/index.js:2953:22)
    at _class.parseSubscript (~/project/app/node_modules/babylon/lib/index.js:2862:32)
    at _class.parseSubscripts (~/project/app/node_modules/babylon/lib/index.js:2777:19)
    at _class.parseExprSubscripts (~/project/app/node_modules/babylon/lib/index.js:2767:17)
    at _class.parseMaybeUnary (~/project/app/node_modules/babylon/lib/index.js:2736:21)
    at _class.parseExprOps (~/project/app/node_modules/babylon/lib/index.js:2643:21)
    at _class.parseMaybeConditional (~/project/app/node_modules/babylon/lib/index.js:2615:21)
    at _class.parseMaybeAssign (~/project/app/node_modules/babylon/lib/index.js:2562:21)
    at _class.parseExpression (~/project/app/node_modules/babylon/lib/index.js:2515:21)
    at _class.parseStatementContent (~/project/app/node_modules/babylon/lib/index.js:4076:21)
    at _class.parseStatement (~/project/app/node_modules/babylon/lib/index.js:3962:17)
    at _class.parseBlockOrModuleBlockBody (~/project/app/node_modules/babylon/lib/index.js:4513:23)
    at _class.parseBlockBody (~/project/app/node_modules/babylon/lib/index.js:4500:10)
    at _class.parseTopLevel (~/project/app/node_modules/babylon/lib/index.js:3938:10)
    at _class.parse (~/project/app/node_modules/babylon/lib/index.js:5304:17)
    at parse (~/project/app/node_modules/babylon/lib/index.js:10095:38)
    at parser (~/project/app/node_modules/@babel/register/node_modules/@babel/core/lib/transformation/normalize-file.js:139:35)
    at normalizeFile (~/project/app/node_modules/@babel/register/node_modules/@babel/core/lib/transformation/normalize-file.js:87:11)
    at runSync (~/project/app/node_modules/@babel/register/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at transformSync (~/project/app/node_modules/@babel/register/node_modules/@babel/core/lib/transform-sync.js:17:38)
    at Object.transform (~/project/app/node_modules/@babel/register/node_modules/@babel/core/lib/transform.js:22:65)
    at compile (~/project/app/node_modules/@babel/register/lib/node.js:73:20)
    at compileHook (~/project/app/node_modules/@babel/register/lib/node.js:102:12)
    at Module._compile (~/project/app/node_modules/pirates/lib/index.js:86:27)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (~/project/app/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at ~/project/app/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (~/project/app/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (~/project/app/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (~/project/app/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
```

This may be related to https://github.com/babel/babel/issues/7701 but I was trying to run mocha directly without yarn workspaces and it has the same effect.

The weird thing, running with `DEBUG=*` shows that babel finds the right config:

```
  babel:config:loading:files:configuration Found configuration '~/project/app/packages/components/.babelrc' from '~/project/app/packages/components/test'. +1s
```

**Expected behavior/code**
Should run tests.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["@babel/preset-env", {
      "targets": { 
        "node": "8.9" 
      }
    }],
    "@babel/preset-react",
    "@babel/preset-flow"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

**Environment**
- Babel version(s): 7.0.0-rc.1
- Node/npm version: yarn 1.9.4, node v8.11.2
- OS: macOS
- Monorepo: yes
- How you are using Babel: CLI

**Possible Solution**
Not sure

**Additional context/Screenshots**
None

**Comment by pvdlg** [comment]
I have a similar issue with a slightly different use case. I'm using `@babel/register` to compile my code and I also want to compile a couple dependencies that require a node version higher than mine.

My `.babelrc` at the root of my repo is:
```json
{
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "current"
          }
        }
      ]
    ],
    "plugins": [
      "@babel/plugin-proposal-object-rest-spread"
    ]
}
```

I I call `@babel/register` like this:
```js
require('@babel/register')({
  only: ['lib', 'node_modules/got', 'node_modules/cacheable-request'],
});
```

I want to compile all the files in the `lib` directory at the root of my project and all the files in `got` and `cacheable-request` because they require Node 8 and I need to support Node 6.

I get the following error because my `.babelrc` config is ignore for the files in `node_modules/got`.
```
SyntaxError: <PATH_TO_MY_PROJECT>/node_modules/got/source/create.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled
```

**Comment by loganfsmyth** [comment]
@pvdlg I've added some new documentation in http://babeljs.io/docs/en/next/config-files#file-relative-configuration which may help explain why this isn't working.

In your case specifically, `.babelrc` files have no effect on package in `node_modules`. It probably makes the most sense for you to rename your `.babelrc` to `babel.config.js`.

**Comment by pvdlg** [comment]
Thanks for the clarification. It seems in my case the problem is that the config loader stops when a `package.json` is found. As there is one in `node_modules/got` my `.babelrc` is ignored for those files.

May I ask the reason for stopping the lookup when a `package.json` exists? Is there some documentation/PR/issue explaining that?

Shouldn't the lookup stops only when a `.babelrc` or a `package.json` with a `babel` property?
This way the Babel config of the package would be used when there is one, and if not, the upper one would be used.

**Comment by haggholm** [comment]
It looks like (maybe?) Babel loads twice or something, and ends up running tests with no plugins at all. I’ll append a stack trace below, but this excerpt seems key:
```
  babel:config:loading:files:plugins Loaded plugin '@babel/plugin-proposal-class-properties' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +3ms

...<snip>...

/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/@babel/core/lib/transformation/normalize-file.js:174
    throw err;
    ^

SyntaxError: /mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal/node_modules/@client/test-utils/test-utils.js: Support for the experimental syntax 'classProperties' isn't currently enabled (32:21):

  30 | 
  31 | class Provider extends React.PureComponent {
> 32 | 	static displayName = 'Provider';
     | 	                   ^
  33 | 
  34 | 	constructor() {
  35 | 		super(...arguments);

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
```

But of course it *is* enabled; we see it being loaded earlier!

I added some temporary logging to `babylon`’s `Parser.expectPlugin()`, which checks `!!this.plugins[name]`, and found that it actually had *no* plugins loaded.

```
/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/.bin/mocha --require /mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/lib/mocha-babel-hook.js --max-old-space-size=4096
  mocha:suite bail undefined +0ms
  mocha:suite enableTimeouts true +3ms
  mocha:suite bail undefined +5ms
  babel:config:config-chain Ignored '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/lib/babel-ignore.js' because it failed to match one of [ /^\/mnt\/scratch\/shared\/petter\/witkit-devenv\/client-react-native-navigation\/modal/i ] from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal' +0ms
  babel:config:config-chain Ignored '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/mocha/lib/interfaces/common.js' because it matched one of [ [Function] ] from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal' +5ms
  babel:config:loading:files:configuration Found configuration '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal/.babelrc' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal/test'. +0ms
  babel:config:loading:files:plugins Loaded preset 'babel-preset-witkit-client' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +0ms
  babel:config:loading:files:plugins Loaded plugin '@babel/plugin-syntax-dynamic-import' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +114ms
  babel:config:loading:files:plugins Loaded plugin '@babel/plugin-proposal-decorators' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +63ms
  babel:config:loading:files:plugins Loaded plugin '@babel/plugin-proposal-class-properties' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +3ms
  babel:config:loading:files:plugins Loaded plugin '@babel/plugin-transform-flow-comments' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +1ms
  babel:config:loading:files:plugins Loaded plugin '@babel/plugin-transform-react-jsx' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +1ms
  babel:config:loading:files:plugins Loaded plugin '@babel/plugin-proposal-object-rest-spread' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +3ms
  babel:config:loading:files:plugins Loaded plugin '@babel/plugin-proposal-optional-chaining' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +1ms
  babel:config:loading:files:plugins Loaded plugin 'babel-plugin-dynamic-import-node-babel-7' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +1ms
  babel:config:loading:files:plugins Loaded preset '@babel/preset-env' from '/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal'. +197ms
/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/@babel/core/lib/transformation/normalize-file.js:174
    throw err;
    ^

SyntaxError: /mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal/node_modules/@client/test-utils/test-utils.js: Support for the experimental syntax 'classProperties' isn't currently enabled (32:21):

  30 | 
  31 | class Provider extends React.PureComponent {
> 32 | 	static displayName = 'Provider';
     | 	                   ^
  33 | 
  34 | 	constructor() {
  35 | 		super(...arguments);

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
    at Parser.raise (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:776:15)
    at Parser.expectPlugin (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:2084:18)
    at Parser.parseClassProperty (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:4920:12)
    at Parser.pushClassProperty (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:4884:30)
    at Parser.parseClassMemberWithIsStatic (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:4817:14)
    at Parser.parseClassMember (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:4754:10)
    at Parser.parseClassBody (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:4709:12)
    at Parser.parseClass (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:4659:10)
    at Parser.parseStatementContent (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:3990:21)
    at Parser.parseStatement (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:3962:17)
    at Parser.parseBlockOrModuleBlockBody (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:4513:23)
    at Parser.parseBlockBody (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:4500:10)
    at Parser.parseTopLevel (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:3938:10)
    at Parser.parse (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:5304:17)
    at parse (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/babylon/lib/index.js:10095:38)
    at parser (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/@babel/core/lib/transformation/normalize-file.js:139:35)
    at normalizeFile (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/@babel/core/lib/transformation/normalize-file.js:87:11)
    at runSync (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at transformSync (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/@babel/core/lib/transform-sync.js:17:38)
    at Object.transform (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/@babel/core/lib/transform.js:22:65)
    at compile (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/@babel/register/lib/node.js:73:20)
    at compileHook (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/@babel/register/lib/node.js:102:12)
    at Module._compile (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/pirates/lib/index.js:86:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.newLoader [as .js] (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/pirates/lib/index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/modal/test/test-modal.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module._compile (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.newLoader [as .js] (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/pirates/lib/index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/mnt/scratch/shared/petter/witkit-devenv/client-react-native-navigation/devtools/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

**Comment by loganfsmyth** [comment]
@haggholm Take a look at http://babeljs.io/docs/en/next/config-files#file-relative-configuration

A `.babelrc` in `modal` will not apply have any effect on modules inside `modal/node_modules`. You would need to use a project-wide config file for that.

**Comment by pvdlg** [comment]
Is there a way to declare the `babel` config in `package.json` as project-wide? Or is the only way is to have a `babel.config.js`?

I would prefer to use the config in `package.json` rather than adding yet another config file at the root of my project....

Was it discussed to identify project-wide config based on a property (like `global`) rather than the filename containing the config?

Even if it's clearly documented it's quite unintuitive to have `babel.config.js` behaving differently than `.babelrc` and `package.json#babel`... For most tools out there a `rc` file, an entry in `package.json`, a `rc.json` file, a `rc.yml` and a `.config.js` are strictly equivalent.

**Comment by haggholm** [comment]
@loganfsmyth

> A .babelrc in modal will not apply have any effect on modules inside modal/node_modules. You would need to use a project-wide config file for that.

Normally true, but I don’t know if it applies here, because

1. The package in `node_modules` has its own `.babelrc` (or it might be `package.json`) with the exact same settings, and
2. The hook loaded by `--require` specifies an `ignore` function that excludes our scoped packages (e.g. `@client`). (Excludes? Includes? Does not ignore, at any rate.)

**Comment by loganfsmyth** [comment]
> Is there a way to declare the babel config in package.json as project-wide? Or is the only way is to have a babel.config.js? I would prefer to use the config in package.json rather than adding yet another config file at the root of my project....

Not presently.

> Was it discussed to identify project-wide config based on a property in the file (like global) or another mean, rather than the filename containing the config?

Assuming I understand you right, we have #7961 to track the possibility, but it's not clear that it's worth doing since we're then mixing two currently-independent config formats.

> Even if it's clearly documented it's quite unintuitive to have babel.config.js behaving differently than .babelrc and package.json#babel... For most tools out there a rc file, an entry in package.json, a rc.json file, a rc.yml and a .config.js are strictly equivalent.

I respect that, but at the end of the day it is what it is now. The only way to keep it as one format would have been to drop the file-relative resolution entirely, and then people would be just as frustrated, if not more so.

**Comment by loganfsmyth** [comment]
@haggholm 

> The package in node_modules has its own .babelrc (or it might be package.json) with the exact same settings, and

Again, see http://babeljs.io/docs/en/next/config-files#file-relative-configuration. 

> The "filename" being compiled must be inside of "babelrcRoots" packages, or else searching will be skipped entirely.

`modal/node_modules/@client/test-utils/test-utils.js` is not inside of one of the root packages, so it will be ignored, even if it has its own `.babelrc`. You'd have to opt into compilation of it by configuring it as a `babelrcRoots` package.

> The hook loaded by --require specifies an ignore function that excludes our scoped packages (e.g. @client). (Excludes? Includes? Does not ignore, at any rate.)

I don't follow what you mean here, sorry.

**Comment by haggholm** [comment]
@loganfsmyth By the include/exclude stuff I mean that I provided a custom `ignore` function for http://babeljs.io/docs/en/next/babel-register#specifying-options; I thought that would take effect here.

**Comment by loganfsmyth** [comment]
@haggholm Gotcha. Those affect what files are processed by `@babel/register` and passed to Babel, but if a given file has no configuration that applies to it because it is in `node_modules`, it is just going to pass through `babel/register` with no transformations being applied to it.

**Comment by pronebird** [comment]
@loganfsmyth I don't use project-wide configuration, .babelrc is located within `packages/{package}/.babelrc`. We have different for each package.

**Comment by loganfsmyth** [comment]
@pronebird Creating a `babel.config.js` in the root that does 

```
module.exports = { 
  babelrcRoots: [
    ".",
    "./packages/*",
  ]
};
```
should be enough to make Babel process package-level `.babelrc` files.

**Comment by pronebird** [comment]
Still not able to make @babel/register work:

```
$ electron-mocha --renderer -R spec --require @babel/register --require-main "test/setup/main.js" --preload "test/setup/renderer.js" "test/*.spec.js" "test/*.spec.ts" "test/**/*.spec.js"
Unexpected identifier
~/gui/packages/desktop/test/keyframe-animation.spec.ts:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import KeyframeAnimation from '../src/main/keyframe-animation';
                                                                                                                                                                  ^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
```

Compilation actually works 

```
yarn workspace desktop private:compile
yarn workspace v1.10.1
yarn run v1.10.1
$ babel src/ --copy-files --out-dir build --extensions ".ts,.tsx,.js"
Successfully compiled 79 files with Babel.
```

**Comment by pronebird** [comment]
Seems to work fine.
