### ISSUE TITLE
Mocha/Babel/Typescript issues

### ISSUE THREAD

**Issue by srepollock** [babel/babel#8466]
Hi there, 

I have made this an issue as there is a bit of explanation to my problem that I don't want to get lost in a Slack chat. I also hoped to use it as a reference in the chat as well. Onto the question!

I am having some issues running my Mocha test suite written in ESNext TypeScript. Let me explain: I am working on a new game engine library that is written in TypeScript that I would like to deploy to NPM for downloads. As I want this project to use the latest ECMA scripts as well, I want to use Babel to help transpile both the source code for the project and the testing suite from TypeScript to JavaScript for running.

I got my project working in earlier stages, however I believe it was using the wrong version of TypeScript, the wrong module generation and other issues I believe to have now addressed.

Currently, when I run my scripts after making the changes is that I get:

```
> divine-engine@0.0.1 test /Users/Spencer/Documents/git/divine-engine
> mocha --opts mocha.opts

/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: /Users/Spencer/Documents/git/divine-engine/test/components/flagcomponent.spec.ts: Unexpected token, expected ; (6:10)
  4 |
  5 | describe("Flag component unit testing", () => {
> 6 |     var fc: FlagComponent = new FlagComponent(new Transform(0, 0));
    |           ^
  7 |     it("fc should have a location", () => {
  8 |         expect(fc).to.have.property("location");
  9 |     });
    at Parser.pp$5.raise (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.semicolon (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:1742:38)
    at Parser.pp$1.parseVarStatement (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:2170:8)
    at Parser.pp$1.parseStatement (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:1861:19)
    at Parser.pp$1.parseBlockBody (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:4235:22)
    at Parser.pp$3.parseArrowExpression (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:4190:8)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3855:17)
    at Parser.pp$3.parseExprAtom (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3709:19)
    at Parser.pp$3.parseExprSubscripts (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:1906:19)
    at Parser.pp$1.parseBlockBody (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:1673:17)
    at parse (/Users/Spencer/Documents/git/divine-engine/node_modules/babylon/lib/index.js:7305:37)
    at File.parse (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/file/index.js:485:15)
    at File.parseCode (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/file/index.js:570:20)
    at /Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/file/index.js:532:16)
    at Pipeline.transform (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.transformFileSync (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-core/lib/api/node.js:152:10)
    at compile (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-register/lib/node.js:118:20)
    at loader (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Spencer/Documents/git/divine-engine/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/Spencer/Documents/git/divine-engine/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! Test failed.  See above for more details.
```
Unexpected token error occurring.

I have had multiple issues continuously arising when using Mocha/Chai and Babel for unit tests; it’s really starting to bother me. Could someone maybe help me in understanding how TS/Babel/Mocha/Chai all fit together?

## Technical stuff
I’m running on macOS 10.13.5, npm 6.3.0, node 10.0.0, typescript 3.0.1, mocha 5.2.0, chai 4.1.2, babel 6.23.0, babel-preset-env 1.7.0, babel-register 6.26.0

tsconfig.json
```
{
  "compilerOptions": {
    "target": "ESNEXT",
    "module": "ESNEXT",
    "declaration": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "noImplicitAny": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "types": [
      "node",
      "electron"
    ],
    "esModuleInterop": true
  },
  "include": [
    "src/**/*"
  ],
  "exclue": [
    "node_modules"
  ]
}
```
.babelrc
```
{
    "presets": ["env"]
}
```
mocha.opts
```
--require babel-register
./test/**/*.spec.ts
```
`npm test` command
```
"test": "./node_modules/.bin/mocha --opts mocha.opts"
```

Any help or guidance is much appreciated. I have been stuck on this for quite some time.

**Comment by loganfsmyth** [comment]
I'm actually confused about why Babel is even trying to process that file.

**Comment by srepollock** [comment]
@nicolo-ribaudo when you say run `tsc` are you talking the Mocha test files written in TypeScript?
