### ISSUE TITLE
Unexpected token while using mocha + @babel/register

### ISSUE THREAD

**Issue by ganapativs** [babel/babel#8477]
**Issue**
Unable to run test files containing ECMAScript 6 modules using mocha + @babel/register.
```
❯ yarn test
yarn run v1.7.0
warning package.json: No license field
$ mocha --require @babel/register
/Users/<username>/mocha-reproduce/test/reproduce.js:1
(function (exports, require, module, __filename, __dirname) { import { expect } from "chai";
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._compile (/Users/<username>/mocha-reproduce/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/Users/<username>/mocha-reproduce/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/<username>/mocha-reproduce/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/<username>/mocha-reproduce/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/<username>/mocha-reproduce/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/<username>/mocha-reproduce/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not really sure if its babel issue or mocha issue!

**Reproduce Repo**
https://github.com/ganapativs/mocha-babel-register-bug-reproduce

**Babel Configuration (.babelrc, package.json, cli command)**

```js
# .babelrc
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "modules": false
            }
        ]
    ],
    "plugins": [
        "@babel/plugin-proposal-class-properties"
    ]
}

# Package.json scripts
"scripts": {
   "test": "mocha --require @babel/register"
},
```

**Expected behavior/code**
Should run test files containing ECMAScript 6 modules using mocha + @babel/register.

**Environment**
- Babel version(s): v7.0.0-beta.54
- Node/npm version: npm 6.1.0, yarn 1.7.0
- OS: OSX 10.14 Beta
- Monorepo no
- How you are using Babel: `register`

**Comment by loganfsmyth** [comment]
You've set `"modules": false`, which specifically instructs Babel not to compile ES module syntax.

**Comment by ganapativs** [comment]
Oops! Silly bug! That fixed it! Thank you very much @loganfsmyth!
