### ISSUE TITLE
babel-node not using babel.config.js

### ISSUE THREAD

**Issue by tracker1** [babel/babel#8519]
## Bug Report

When I'm using `babel-node foo.js` it doesn't appear to be loading `babel.config.js` for configuration options.

**Input Code**

```js
// foo.js
import shell from 'shelljs';
...
```

**Expected behavior/code**

I would expect the code in `foo.js` to execute without errors on the import

**Babel Configuration (.babelrc, package.json, cli command)**

```js
// babel.config.js
const plugins = require('./babel-plugins');

console.log('LOADING CONFIG!!!');

module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        loose: true,
        targets: {
          node: '10.5',
        },
        exclude: ['transform-async-to-generator', 'transform-regenerator'],
      },
    ],
    '@babel/preset-flow',
    '@babel/preset-react',
  ],
  plugins: [
    [
      '@babel/plugin-transform-modules-commonjs',
      {
        allowTopLevelThis: true,
      },
    ],
    ...plugins,
  ],
  env: {
    test: {
      plugins: [],
    },
  },
};
```

```js
// babel-plugins.js
module.exports = [
  // stage 1
  ['@babel/plugin-proposal-do-expressions', { loose: true }],
  ['@babel/plugin-proposal-export-default-from', { loose: true }],
  ['@babel/plugin-proposal-logical-assignment-operators', { loose: true }],
  ['@babel/plugin-proposal-nullish-coalescing-operator', { loose: true }],
  ['@babel/plugin-proposal-optional-chaining', { loose: true }],
  ['@babel/plugin-proposal-pipeline-operator', { loose: true, proposal: 'minimal' }],

  // stage 2
  ['@babel/plugin-proposal-decorators', { loose: true, legacy: true }],
  ['@babel/plugin-proposal-export-namespace-from', { loose: true }],
  ['@babel/plugin-proposal-function-sent', { loose: true }],
  ['@babel/plugin-proposal-numeric-separator', { loose: true }],
  ['@babel/plugin-proposal-throw-expressions', { loose: true }],

  // stage 3
  ['@babel/plugin-proposal-async-generator-functions', { loose: true }],
  ['@babel/plugin-proposal-class-properties', { loose: true }],
  ['@babel/plugin-proposal-json-strings', { loose: true }],
  ['@babel/plugin-proposal-object-rest-spread', { loose: true }],
  ['@babel/plugin-proposal-optional-catch-binding', { loose: true }],
  ['@babel/plugin-proposal-unicode-property-regex', { loose: true }],
  ['@babel/plugin-syntax-dynamic-import', { loose: true }],
  ['@babel/plugin-syntax-import-meta', { loose: true }],
];
```

**Environment**
- Babel version(s): 7.0.0-rc.1
- Node/npm version: 10.9
- OS: Windows 10
- Monorepo: no
- How you are using Babel: `babel-node`

**Possible Solution**

No ideas on this, not familiar with internals.

**Additional context/Screenshots**

```
(function (exports, require, module, __filename, __dirname) { import shell from 'shelljs';
                                                                     ^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at loader (C:\Users\mryan\src\runbeck.visualstudio.com\vocem\rb-vocem-ui\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\mryan\src\runbeck.visualstudio.com\vocem\rb-vocem-ui\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

**Comment by hzoo** [comment]
Noticed your error message has a `babel-register` in the call stack? So it's running v6 somewhere

**Comment by tracker1** [comment]
@hzoo not sure, just updated all the `^7.0.0-rc.1` to `^7.0.0-rc.2` then `npm i` and seems to be working now...  gotta love running pre-release. :-)
