### ISSUE TITLE
Plugin/Preset files are not allowed to export objects, only functions

### ISSUE THREAD

**Issue by Lory1990** [babel/babel#8522]
Hi guys,
I am going crazy for this error:
`Plugin/Preset files are not allowed to export objects, only functions`

I googled evervwhere but cannot find a solution.... may you help me?

Here is my package.json:
```
....
"scripts": {
        "start": "cross-env NODE_PATH=src webpack-dev-server --config=webpack.dev.js --open --progress --colors --display-error-details --quiet",
        "build": "cross-env NODE_PATH=src && npm run clean:html && npm run clean:dist && webpack --config=webpack.prod.js --progress --colors --display-error-details",
  },
"devDependencies": {
        "@babel/core": "^7.0.0-rc.1",        
        "@babel/plugin-transform-react-constant-elements": "^7.0.0-rc.1",
        "@babel/plugin-transform-react-inline-elements": "^7.0.0-rc.1",
        "@babel/preset-env": "^7.0.0-rc.1",
        "@babel/preset-react": "^7.0.0-rc.1",
        "@babel/plugin-transform-runtime":"^7.0.0-rc.1",
        "@babel/cli": "^7.0.0-rc.1",
        "babel-plugin-lodash": "^3.3.2",
        "babel-plugin-react-transform": "^3.0.0",
        "babel-preset-react-optimize": "^1.0.1",
        "autoprefixer": "9.1.0",
        "babel-loader": "^8.0.0-beta",
        "babel-plugin-transform-react-pure-class-to-function": "^1.0.1",
        "babel-plugin-transform-react-remove-prop-types": "^0.4.15",
        "cross-env": "5.2.0",
        "css-loader": "^1.0.0",
        "html-webpack-plugin": "^3.2.0",
        "js-beautify": "1.7.5",
        "marked": "0.4.0",
        "postcss-cli": "6.0.0",
        "react-hot-loader": "^4.3.4",
        "style-loader": "^0.22.1",
        "tailwindcss": "0.6.4",
        "webpack": "^4.16.5",
        "webpack-cli": "^3.1.0",
        "webpack-dev-server": "^3.1.5"
    }
....
```

this is my `.babelrc`

```
{
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react",
      "react-optimize",
    ],
    "plugins": [
      "@babel/transform-react-constant-elements",
      "@babel/transform-react-inline-elements",
      "transform-react-remove-prop-types",
      "transform-react-pure-class-to-function",
      "react-hot-loader/babel",
    ],
    "compact": true
}
```

and here you have my webpack configuration https://pastebin.com/qLWmVjeV

Could you help me?

**Comment by loganfsmyth** [comment]
The `babel-preset-react-optimize` preset that you are using is not compatible with Babel 7 at the moment. Since you've already got
```
      "@babel/transform-react-constant-elements",
      "@babel/transform-react-inline-elements",
      "transform-react-remove-prop-types",
      "transform-react-pure-class-to-function",
```
in your Babel config, which is the entire content of the preset, but updated for Babel 7, you should just remove the preset itself from your config.

**Comment by Lory1990** [comment]
Now it gives thi error on the console

```
 17% building modules 64/94 modules 30 active …ace-roboto\files\roboto-latin-100.woff2D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\loader-runner\lib\loadLoader.js:35
                        throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
                        ^

Error: Module 'D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\url\url.js' is not a loader (must have normal or pitch function)
    at loadLoader (D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\loader-runner\lib\loadLoader.js:35:10)
    at iteratePitchingLoaders (D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\webpack\lib\NormalModule.js:265:3)
    at NormalModule.build (D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\webpack\lib\NormalModule.js:412:15)
    at Compilation.buildModule (D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\webpack\lib\Compilation.js:616:10)
    at factory.create (D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\webpack\lib\Compilation.js:857:14)
    at factory (D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\webpack\lib\NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\webpack\lib\NormalModuleFactory.js:155:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (D:\CodingProjects\Cryptoforecast\Fujiko_fuse\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fuse-react-app@1.1.6 start: `cross-env NODE_PATH=src webpack-dev-server --config=webpack.dev.js --open --progress --colors --display-error-details --quiet`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fuse-react-app@1.1.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\loren\AppData\Roaming\npm-cache\_logs\2018-08-24T05_54_46_558Z-debug.log
```

**Comment by loganfsmyth** [comment]
That looks like an unrelated error in your Webpack config in the loader/rules list. Looks like you're passing the `url` module as if it were a loader? Maybe you write `loader: "url"` instead of "loader: "url-loader"`?

**Comment by Lory1990** [comment]
fantastic, you are a wizard ;) 

but now...
```
SyntaxError: D:\CodingProjects\Cryptoforecast\Fujiko_fuse\src\@fuse\components\FuseCountdown\FuseCountdown.js: Support for the experimental syntax 'classProperties' isn't currently enabled (21:11):

  19 |
  20 | class FuseCountdown extends Component {
> 21 |     state = {
     |           ^
  22 |         endDate  : moment.isMoment(this.props.endDate) ? this.props.endDate : moment(this.props.endDate),
  23 |         countdown: {
  24 |             days   : '',

```
