### ISSUE TITLE
the option "highlightCode" should default to true

### ISSUE THREAD

**Issue by andy0130tw** [babel/babel#8543]
## Bug Report

**Current Behavior**
When compiling a JS file with syntax error, the error reporting has no color output.

**Input Code**
- REPL or Repo link if applicable:

For example the following nonsense in `error.js`:

```js
alert(,);
```

Transpiling with command `npx babel error.js`, emits a SyntaxError,

```
{ SyntaxError: /home/qbane/Desktop/cms-survey/my-browserify-boilerplate/src/js/error.js: Unexpected token (1:6)

> 1 | alert(,);
    |       ^
  2 | 
    at Parser.raise (/home/xxx/.config/yarn/global/node_modules/@babel/parser/lib/index.js:3913:15)

(... stacktrace omitted ...)

    at Parser.parseCallExpressionArguments (/home/xxx/.config/yarn/global/node_modules/@babel/parser/lib/index.js:6118:22)
  pos: 6,
  loc: Position { line: 1, column: 6 },
  code: 'BABEL_PARSE_ERROR' }
```

But the code is printed with no color.

![2018-08-26 17-32-10](https://user-images.githubusercontent.com/5269414/44626831-3d911500-a956-11e8-9b05-b9b6f50313f6.png)

**Expected behavior/code**

As per [Babel core option](https://babeljs.io/docs/en/babel-core#options) or CLI help, the code *should be highlighted* by default. The CLI does have an option to control the color output, but since the option `no-highlight-code` only has the effect to turn off the color, it is impossible to turn it on AFAIK.

(from `babel --help`)

```
    --no-highlight-code                         enable/disable ANSI syntax highlighting of code frames (on by default)
```

By setting it in `.babelrc` (see below), however, the output is with color, which is the expected behavior.

**Babel Configuration (.babelrc, package.json, cli command)**

The `.babelrc` is a working one.

```js
{
  presets: ['@babel/preset-env'],
  highlightCode: true
}
```

**Environment**
- Babel version(s): 7.0.0-rc.3 (@babel/core 7.0.0-rc.3)
- Node/npm version: Node 8
- OS: Ubuntu 17.10
- Monorepo yes
- How you are using Babel: cli

**Possible Solution**
Likely, `highlightCode` is `false` as opposed to the documentation. It should be `true` by default.

**Comment by loganfsmyth** [comment]
Good catch. Posted: https://github.com/babel/babel/pull/8546
