### ISSUE TITLE
Plugin/Preset files are not allowed to export objects, only functions

### ISSUE THREAD

**Issue by JackyChar** [babel/babel#8560]
I execute command "react-native run-ios".

but build is fail . Please help me . thank you.

Metro Bundler - lanuchPackager.command
```
Loading dependency graph, done.
error: bundling failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/myname/Desktop/myapp/node_modules/babel-preset-react-native-stage-0/index.js
    at createDescriptor (/Users/myname/Desktop/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:162:11)
    at items.map (/Users/myname/Desktop/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:87:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/myname/Desktop/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:87:29)
    at createPresetDescriptors (/Users/myname/Desktop/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:79:10)
    at presets (/Users/myname/Desktop/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:61:19)
    at presets (/Users/myname/Desktop/myapp/node_modules/@babel/core/lib/config/config-descriptors.js:51:25)
    at mergeChainOpts (/Users/myname/Desktop/myapp/node_modules/@babel/core/lib/config/config-chain.js:308:26)
    at /Users/myname/Desktop/myapp/node_modules/@babel/core/lib/config/config-chain.js:271:7
```

package.json :

```
{
  "name": "projactname",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "crypto-js": "^3.1.9-1",
    "immutable": "^3.8.2",
    "key-mirror": "^1.0.1",
    "moment": "^2.22.0",
    "native-base": "^2.7.2",
    "npm": "^5.8.0",
    "pretty-format": "^22.4.3",
    "react": "^16.3.1",
    "react-native": "^0.56.0",
    "react-native-ble-manager": "^6.3.1",
    "react-native-calendars": "^1.18.2",
    "react-native-camera": "^1.1.4",
    "react-native-carousel-pager": "^1.4.2",
    "react-native-datepicker": "^1.7.2",
    "react-native-i18n": "^2.0.12",
    "react-native-image-gallery": "^2.1.5",
    "react-native-indicators": "^0.12.0",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
    "react-native-payments": "^0.4.0",
    "react-native-phone-call": "^1.0.4",
    "react-native-qrcode-scanner": "^1.0.1",
    "react-native-qrcode-svg": "^5.0.6",
    "react-native-simple-dialogs": "^0.3.1",
    "react-native-sqlite-storage": "^3.3.6",
    "react-native-status-bar-height": "^2.0.0",
    "react-native-svg": "^6.3.1",
    "react-native-unique-id": "^1.0.4",
    "react-navigation": "^1.5.11",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-axios-middleware": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-observable": "^0.18.0",
    "redux-promise-middleware": "^5.1.1",
    "rn-splash-screen": "^5.2.0",
    "rxjs": "^5.5.10"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-react-native": "^4.0.0",
    "eslint": "^4.19.1",
    "flow-bin": "^0.71.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1",
    "redux-devtools": "^3.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by JackyChar** [comment]
The issue be solved.

I change to .babelrc.

{
  "presets": ["react-native-stage-0"]
}

to 
{
  "presets": ["react-native"]
}
