### ISSUE TITLE
update project got error

### ISSUE THREAD

**Issue by cattei** [babel/babel#8586]
## Bug Report
I have update the babel as : 

```
$ babel-upgrade --write

:raised_hands:  Thanks for trying out https://github.com/babel/babel-upgrade!

Updating closest package.json dependencies
Index: D:\mycloud\Everest\package.json
===================================================================
--- D:\mycloud\Everest\package.json     Before Upgrade
+++ D:\mycloud\Everest\package.json     After Upgrade
@@ -22,9 +22,8 @@
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-es2015": "^7.0.0-beta.53",
    "@babel/preset-react": "^7.0.0",
-    "@babel/preset-stage-0": "^7.0.0",
    "ajax": "^0.0.4",
    "ali-oss": "^4.7.3",
    "aliyun-sdk": "^1.9.2",
    "antd": "^2.12.7",
```

babel/babel-upgrade

```
got this error:ERROR in ./app/websites/teacher.js
Module build failed: Error: [BABEL] D:\mycloud\Everest\app\websites\teacher.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
 long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
 "plugins": [
   // Stage 0
   "@babel/plugin-proposal-function-bind",

   // Stage 1
   "@babel/plugin-proposal-export-default-from",
   "@babel/plugin-proposal-logical-assignment-operators",
   ["@babel/plugin-proposal-optional-chaining", { "loose": false }],
   ["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal" }],
   ["@babel/plugin-proposal-nullish-coalescing-operator", { "loose": false }],
   "@babel/plugin-proposal-do-expressions",

   // Stage 2
   ["@babel/plugin-proposal-decorators", { "legacy": true }],
   "@babel/plugin-proposal-function-sent",
   "@babel/plugin-proposal-export-namespace-from",
   "@babel/plugin-proposal-numeric-separator",
   "@babel/plugin-proposal-throw-expressions",

   // Stage 3
   "@babel/plugin-syntax-dynamic-import",
   "@babel/plugin-syntax-import-meta",
   ["@babel/plugin-proposal-class-properties", { "loose": false }],
   "@babel/plugin-proposal-json-strings"
 ]
}

If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
 return {
   plugins: [
     require("@babel/plugin-syntax-dynamic-import"),
     [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
     [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
   ],
   presets: [
     // ...
   ],
 };
};
  (While processing: "D:\\mycloud\\Everest\\node_modules\\@babel\\preset-stage-0\\lib\\index.js")
   at _default (D:\mycloud\Everest\node_modules\_@babel_preset-stage-0@7.0.0@@babel\preset-stage-0\lib\index.js:9:9)
   at loadDescriptor (D:\mycloud\Everest\node_modules\_@babel_core@7.0.0@@babel\core\lib\config\full.js:165:14)
   at cachedFunction (D:\mycloud\Everest\node_modules\_@babel_core@7.0.0@@babel\core\lib\config\caching.js:33:19)
   at loadPresetDescriptor (D:\mycloud\Everest\node_modules\_@babel_core@7.0.0@@babel\core\lib\config\full.js:235:63)
   at config.presets.reduce (D:\mycloud\Everest\node_modules\_@babel_core@7.0.0@@babel\core\lib\config\full.js:77:21)
   at Array.reduce (<anonymous>)
   at recurseDescriptors (D:\mycloud\Everest\node_modules\_@babel_core@7.0.0@@babel\core\lib\config\full.js:74:38)
   at loadFullConfig (D:\mycloud\Everest\node_modules\_@babel_core@7.0.0@@babel\core\lib\config\full.js:108:6)
   at process.nextTick (D:\mycloud\Everest\node_modules\_@babel_core@7.0.0@@babel\core\lib\transform.js:28:33)
   at process._tickCallback (internal/process/next_tick.js:61:11)
```

.babelrc file:

```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    ["@babel/preset-stage-0",{"decoratorsLegacy": true}]
  ],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "style": false
      }
    ]
  ]
}
```
package.json
```json
{
  "name": "webs",
  "version": "2.1.0",
  "main": "dist/index.html",
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.46",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-do-expressions": "^7.0.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-function-bind": "^7.0.0",
    "@babel/plugin-proposal-function-sent": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.0.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0",
    "@babel/plugin-proposal-pipeline-operator": "^7.0.0",
    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-es2015": "^7.0.0-beta.53",
    "@babel/preset-react": "^7.0.0",
    "ajax": "^0.0.4",
    "ali-oss": "^4.7.3",
    "aliyun-sdk": "^1.9.2",
    "antd": "^2.12.7",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^8.0.0",
    "babel-plugin-import": "^1.8.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "cheerio": "^0.20.0",
    "ckeditor": "4.5.11",
    "classnames": "^2.2.5",
    "co": "^4.6.0",
    "copyfiles": "^0.2.1",
    "core-decorators": "^0.19.0",
    "core-js": "^2.0.0",
    "create-react-class": "^15.6.0",
    "cross-env": "^5.0.5",
    "css-loader": "^0.23.0",
    "es6-promise": "^3.1.2",
    "eslint": "^1.2.1",
    "eslint-loader": "^1.0.0",
    "eslint-plugin-react": "^3.3.0",
    "event-stream": "^3.3.2",
    "exports-loader": "^0.6.3",
    "express": "^4.15.3",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.8.4",
    "g2": "^2.3.9",
    "glob": "^6.0.0",
    "gulp": "^3.9.1",
    "gulp-connect": "^4.0.0",
    "history": "^2.1.2",
    "hotkeys-js": "^1.0.4",
    "html-webpack-plugin": "^2.9.0",
    "http-proxy-middleware": "^0.17.0",
    "image-webpack-loader": "^1.7.0",
    "imports-loader": "^0.6.5",
    "isparta-instrumenter-loader": "^1.0.0",
    "jquery": "^2.2.3",
    "json-loader": "^0.5.4",
    "less": "^2.5.3",
    "less-loader": "^2.0.0",
    "lodash": "^4.16.5",
    "moment": "^2.17.0",
    "node-notifier": "^5.1.2",
    "node-sass": "^4.5.3",
    "normalize.css": "^3.0.3",
    "null-loader": "^0.1.1",
    "pdfobject": "^2.0.201604172",
    "plyr": "^2.0.11",
    "postcss": "^5.0.11",
    "postcss-loader": "^0.8.0",
    "prop-types": "^15.5.10",
    "qrcode.react": "^0.6.1",
    "querystring": "^0.2.0",
    "rc-util": "^4.0.4",
    "react": "^15.6.1",
    "react-avatar-editor": "^4.1.3",
    "react-contextmenu": "^2.6.5",
    "react-cookie": "^0.4.7",
    "react-dom": "^15.6.1",
    "react-hot-api": "^0.5.0",
    "react-hot-loader": "^2.0.0-alpha-4",
    "react-html5video": "^2.3.0",
    "react-imageloader": "^2.1.0",
    "react-joyride": "^1.10.1",
    "react-lazyload": "^2.2.7",
    "react-redux": "^4.4.5",
    "react-router": "^3.0.0",
    "react-router-redux": "^4.0.7",
    "react-swf": "^1.0.6",
    "redux": "^3.5.2",
    "redux-logger": "^2.7.4",
    "redux-thunk": "^2.1.0",
    "rimraf": "^2.5.4",
    "sass-loader": "^6.0.6",
    "scriptjs": "^2.5.8",
    "scrollyo": "^1.0.2",
    "style-loader": "^0.13.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^2.3.1",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "url-loader": "^0.5.7",
    "vtt.js": "^0.13.0",
    "webpack": "^3.11.0",
    "webpack-dev-middleware": "^1.11.0",
    "webpack-dev-server": "^2.6.1",
    "webpack-hot-middleware": "^2.18.2",
    "webpack-visualizer-plugin": "^0.1.11",
    "whatwg-fetch": "^1.1.1"
  },
  "engines": {
    "node": ">=4.0.0"
  },
  "scripts": {
    "start": "gulp dllBuild && node --max_old_space_size=4096 ./node_modules/gulp/bin/gulp",
    "prod": "cross-env NODE_ENV=dist npm run compile-dist; wait $!;cross-env NODE_ENV=dist npm run cdn; wait $!;",
    "test": "cross-env NODE_ENV=test npm run compile-test; wait $!;cross-env NODE_ENV=test npm run cdn; wait $!;",
    "prod-all": "cross-env NODE_ENV=dist gulp packAll",
    "test-all": "cross-env NODE_ENV=test gulp packAll",
    "compile-dist": "webpack --env=dist",
    "compile-test": "webpack --env=test",
    "desk": "./app/library/nwjs-sdk-v0.13.3-osx-x64/nwjs.app/Contents/MacOS/nwjs .",
    "cdn": "gulp fileupload",
    "prod-cdn": "cross-env NODE_ENV=dist gulp fileupload",
    "test-cdn": "cross-env NODE_ENV=test gulp fileupload",
    "clean": "rimraf publish/*",
    "publish": "gulp publish",
    "deploy": "npm run dist; wait $!; npm run cdn & npm run publish; wait $!;"
  },
  "license": "BSD",
  "dependencies": {
    "@babel/polyfill": "^7.0.0-beta.46",
    "g2-react": "^1.3.0"
  }
}
```

**Comment by nicolo-ribaudo** [comment]
It looks like `babel-upgrade` didn't correctly update your `.babelrc`. Can you remove the stage-0 preset and add the plugins that you need? You can find the complete list in the error message.
