### ISSUE TITLE
@babel/preset to add while setting up with webpack v4

### ISSUE THREAD

**Issue by Tapudp** [babel/babel#8594]
I have been trying to configure babel7 with webpack for my react-redux app and I got the following error which basically says that it can't find the babel, or babel-preset-env or babel-preset-react

```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-preset-env' from 'B:\Shall\Practice\mystarter'
- Did you mean "@babel/env"?
    at Function.module.exports [as sync] (B:\Shall\Practice\mystarter\node_modules\resolve\lib\sync.js:43:15)
    at resolveStandardizedName (B:\Shall\Practice\mystarter\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
    at resolvePreset (B:\Shall\Practice\mystarter\node_modules\@babel\core\lib\config\files\plugins.js:58:10)
    at loadPreset (B:\Shall\Practice\mystarter\node_modules\@babel\core\lib\config\files\plugins.js:77:20)
    at createDescriptor (B:\Shall\Practice\mystarter\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
    at items.map (B:\Shall\Practice\mystarter\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (B:\Shall\Practice\mystarter\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (B:\Shall\Practice\mystarter\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (B:\Shall\Practice\mystarter\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/index.js main[2]
```

Even the documentation setup here http://babeljs.io/en/setup#installation

Says to install `babel-preset-env` and set it up in `.babelrc` as 

```
"preset": ["env", "react"]
```
Which is what gave me error, so it should be 
```
"preset": ["@babel/env", "@babel/react"]
```

Maybe it's just naming convention.

I have wrote an article about the same [here on Medium on how to use babel7 with webpackv4 for react-redux application](https://medium.com/@pbdivyesh/i-learned-how-to-setup-babel7-with-webpack-in-react-redux-projects-b24dafc8cfb)

**Comment by Sibiraj-S** [comment]
Instead of `babel-preset-env` use `@babel/preset-env'

use `@babel/preset-env` instead of `env or @babel/env`

**Comment by Sibiraj-S** [comment]
Try

    "preset": ["@babel/preset-env", "@babel/preset-react"]

https://babeljs.io/docs/en/next/babel-preset-env.html

**Comment by nicolo-ribaudo** [comment]
Do you want to open a PR to https://github.com/babel/website to update it?

**Comment by Tapudp** [comment]
@nicolo-ribaudo yes, that's what I would like to do. This page on babeljs.io do not have it set up with webpack configuration the @babel/preset-react and stuff.

So how do I open a PR there?

**Comment by existentialism** [comment]
@Tapudp you'll find the setup docs here: https://github.com/babel/website/tree/master/docs/tools

**Comment by existentialism** [comment]
@babel-bot move to babel/website

**Comment by Tapudp** [comment]
@existentialism so do I need to clone the whole repo and then modify that particular file and try to push it?

**Comment by existentialism** [comment]
@Tapudp yep!
