### ISSUE TITLE
Error: Cannot find module '@babel/runtime-corejs2/helpers/interopRequireWildcard'

### ISSUE THREAD

**Issue by catamphetamine** [babel/babel#8603]
I tried upgrading my library (which is using `babel-runtime`) to Babel 7 today and I get this error when running it.

```
Error: Cannot find module '@babel/runtime-corejs2/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (c:\dev\serverless-functions-test\node_modules\serverless-functions\commonjs\aws-lambda\api.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

The config is the same as in the Upgrade manual:

```
{
	"presets": ["@babel/preset-env"],

	"plugins":
	[
		["@babel/plugin-transform-runtime", { corejs: 2 }],
		...
	]
}
```

**Comment by catamphetamine** [comment]
Ok, it needed:

```
 npm install @babel/runtime-corejs2 --save
```

**Comment by loganfsmyth** [comment]
Yup! Glad you got it working. Can we improve the documentation around this?

**Comment by catamphetamine** [comment]
@loganfsmyth Not much I guess, it's just a bit overwhelming for anyone to migrate infrastructure to a new major version, so many things get overlooked due to how human perception/consciousness work.
I mean it is written there to install the package, but I decided to just overlook it.
