### ISSUE TITLE
using babel-helper-transform-fixture-test-runner getting "expect" is undefined

### ISSUE THREAD

**Issue by gajus** [babel/babel#8612]
## Bug Report

https://github.com/babel/babel/blob/fc9becfdf2a3dc212cf28a57071f33cdf2442698/packages/babel-helper-transform-fixture-test-runner/src/index.js#L28

**Current Behavior**

```bash
$ node test/index.js
/Users/gajus/Documents/dev/gajus/babel-plugin-react-css-modules/node_modules/@babel/helper-transform-fixture-test-runner/lib/index.js:172
  expect
  ^

ReferenceError: expect is not defined
    at Object.<anonymous> (/Users/gajus/Documents/dev/gajus/babel-plugin-react-css-modules/node_modules/@babel/helper-transform-fixture-test-runner/lib/index.js:172:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at _helperTransformFixtureTestRunner (/Users/gajus/Documents/dev/gajus/babel-plugin-react-css-modules/node_modules/@babel/helper-plugin-test-runner/lib/index.js:9:39)
    at Object._default [as default] (/Users/gajus/Documents/dev/gajus/babel-plugin-react-css-modules/node_modules/@babel/helper-plugin-test-runner/lib/index.js:33:7)

```

**Input Code**

```js
// eslint-disable-next-line import/no-commonjs
require('@babel/helper-plugin-test-runner').default(__dirname);

```

**Expected behavior/code**

Expecting test runner to run.

**Babel Configuration (.babelrc, package.json, cli command)**

N/A

**Environment**

> "@babel/cli": "^7.0.0",
> "@babel/core": "^7.0.0",
> "@babel/helper-plugin-test-runner": "^7.0.0",
> "@babel/plugin-transform-flow-strip-types": "^7.0.0",
> "@babel/preset-env": "^7.0.0",
> "@babel/register": "^7.0.0",

**Comment by nicolo-ribaudo** [comment]
It is meant to be run using jest. Sorry if we haven't documented it anywhere, but `babel-helper-*` packages are meant to be "internal":

**Comment by gajus** [comment]
> It must be run using jest. Sorry if we haven't documented it anywhere, but babel-helper-* packages are meant to be "internal":

Can you provide minimal instructions here?

It used to be run using Mocha.

**Comment by gajus** [comment]
Needed to add:

```json
"jest": {
  "modulePathIgnorePatterns": [
    "/test/fixtures/"
  ],
  "testEnvironment": "node",
  "testRegex": "./test/.+\\.js$"
},

```

to package.json and:

```bash
$ npm install babel-core@7.0.0-bridge.0 --save-dev

```

due to https://github.com/facebook/jest/issues/6913

6a78e70a3049dcb1030ea1b49612440ff4b4c8f2

**Comment by arizonatribe** [comment]
> It must be run using jest. Sorry if we haven't documented it anywhere, but babel-helper-* packages are meant to be "internal":

That's just sloppy, and there it shouldn't be dismissed so easily. You shouldn't be depending on a global like that and _especially_ trying to solve it by suggesting an entire test runner package should be added to any project using this Babel plugin when all you need to do is directly require the separate [expect](https://www.npmjs.com/package/expect) package.
