### ISSUE TITLE
`path.buildCodeFrameError('Error')` throws

### ISSUE THREAD

**Issue by pasaran** [babel/babel#8617]
## Bug Report

**Current Behavior**
`path.buildCodeFrameError( 'Some error' )` throws error:

```
/Users/nop/tmp/node_modules/@babel/traverse/lib/path/index.js:157
    return this.hub.buildError(this.node, msg, Error);
                    ^

TypeError: Cannot read property 'buildError' of undefined
    at NodePath.buildCodeFrameError (/Users/nop/tmp/node_modules/@babel/traverse/lib/path/index.js:157:21)
    at Program (/Users/nop/tmp/test.js:9:20)
    at NodePath._call (/Users/nop/tmp/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/nop/tmp/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/nop/tmp/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/nop/tmp/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/nop/tmp/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/nop/tmp/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/nop/tmp/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/Users/nop/tmp/node_modules/@babel/traverse/lib/index.js:76:12)
```

**Input Code**
```js
const parser = require( '@babel/parser' );
const traverse = require( '@babel/traverse' ).default;
const { codeFrameColumns } = require( '@babel/code-frame' );

const CODE = 'var a = 1;';
const ERROR = 'Number is too small';

const ast = parser.parse( CODE );

traverse( ast, {
    NumericLiteral: function( path ) {
        throw path.buildCodeFrameError( 'Some error' );
        //  throw codeFrameColumns( CODE, path.node.loc, ERROR );
    },
} );
```

**Expected behavior/code**
`throw path.buildCodeFrameError( ERROR )` should do the same as `throw codeFrameColumns( CODE, path.node.loc, ERROR );` (I guess).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
//  package.json:

  "devDependencies": {
    "@babel/parser": "^7.0.0",
    "@babel/traverse": "^7.0.0"
  }
```

**Environment**
- Babel version(s): 7.0.0
- Node/npm version: v9.0.0
- OS: OSX 10.12.6 (16G1408)
- How you are using Babel: `cli`

**Comment by monokrome** [comment]
@loganfsmyth It doesn't have that, because `hub` is the value that is **undefined**. Since `hub` is **undefined**, `buildError` can not be referenced. `undefined.buildError` throws this error.

**Comment by monokrome** [comment]
@loganfsmyth I'm running into this right now - where were you intending to link to?

**Comment by loganfsmyth** [comment]
I honestly think at the moment we just don't ever set a default `hub`, and there is no way to set it via `traverse` without doing the same stuff that Babel itself does to set up the initial traversal.

Depending on your usecase for `buildCodeFrameError`, it might make more sense to use `@babel/core` to trigger the traversal. Otherwise, I'd avoid using `buildCodeFrameError` in your code. If you're seeing it error in code other that your own, then it's still an indication of an error, it's just failing to throw a nice error for you.

**Comment by monokrome** [comment]
When I `import { generate } from  '@babel/core'`, it doesn't actually exist. Is there a way to get a reference to and pass the hub manually?

**Comment by loganfsmyth** [comment]
Sorry, I don't quite follow what you're using `generate` for in this context. Would you be up for joining our Slack to continue this discussion? I think it's hard to have back-and-forth like this on Github.

**Comment by lcoder** [comment]
[Hub. buildError](https://github.com/babel/babel/blob/4e774b726475aff9a6a1d2111afec21158979566/packages/babel-traverse/src/hub.js#L19)
It seems that the features have not been implemented

**Comment by motiz88** [comment]
Some version of this issue seems to have been reintroduced by https://github.com/babel/babel/pull/10914 in 7.8.0.

Before 7.8.0, `@babel/core`'s `parseSync` would call `normalizeFile` which in turn would initialise `hub`, so `traverse`ing and calling `path.buildCodeFrameError` worked.

Since 7.8.0, `@babel/core`'s `parseSync` does not call `normalizeFile`, so `hub` isn't initialised and calling `path.buildCodeFrameError` within a traversal fails again.

**Comment by skipjack** [comment]
Yeah I'm still seeing this error when using `parcel` but only when building for production (i.e. `parcel serve` works fine but `parcel build` fails). Reverting babel to an older version based on @motiz88's comment above to see if that addresses the issue (doesn't feel like a great fix though, would love to help find a cleaner solution).
