### ISSUE TITLE
[typescript] does not handle type casting properly

### ISSUE THREAD

**Issue by sibelius** [babel/babel#8664]
## Bug Report

**Current Behavior**
It should handle type casting using `<>` and `as` syntax

**Input Code**

```js
const edgeType = new GraphQLObjectType({
    name: `${name}Edge`,
    description: 'An edge in a connection.',
    fields: () => ({
      node: {
        type: nodeType,
        resolve: resolveNode,
        description: 'The item at the end of the edge',
      },
      cursor: {
        type: GraphQLNonNull(GraphQLString),
        resolve: resolveCursor,
        description: 'A cursor for use in pagination',
      },
      // as any
      ...(resolveMaybeThunk(edgeFields) as any)
    }),
  });
```

**Expected behavior/code**
It should parse properly typecast 

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  presets: [
    '@babel/preset-flow',
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
  ],
  plugins: [
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-transform-async-to-generator',
    '@babel/plugin-syntax-async-generators',
  ],
  overrides: [
    {
      test: ['/src/**/*.ts'],
      presets: [
        '@babel/preset-typescript',
        [
          '@babel/preset-env',
          {
            targets: {
              node: 'current',
            },
          },
        ],
      ],
    },
  ],
};
```

**Environment**
- Babel version(s): 7
- Node/npm version: node 8 lts, yarn
- OS: OSX
- Monorepo: no
- How you are using Babel: clil

**Possible Solution**

**Additional context/Screenshots**

You can add `( as any)` here https://github.com/entria/graphql-dataloader-boilerplate/pull/97/files#diff-deb8df1d7fac1f963f3c5a75bc21843dR84 to reproduce the parser bug

{ SyntaxError: /graphql-dataloader-boilerplate/src/core/connection/CustomConnectionType.ts: Unexpected token, expected "," (84:40)

  82 |       },
  83 |       // as any
> 84 |       ...(resolveMaybeThunk(edgeFields) as any)
     |                                         ^
  85 |     }),
  86 |   });
  87 | 
    at _class.raise (/Users/sibelius/Dev/entria/feedback/graphql-dataloader-boilerplate/node_modules/@babel/parser/lib/index.js:3938:15)
    at _class.unexpected (/Users/sibelius/Dev/entria/feedback/graphql-dataloader-boilerplate/node_modules/@babel/parser/lib/index.js:5247:16)
    at _class.expect (/Users/sibelius/Dev/entria/feedback/graphql-dataloader-boilerplate/node_modules/@babel/parser/lib/index.js:5235:28)
    at _class.parseParenAndDistinguishExpression (/Users/sibelius/Dev/entria/feedback/graphql-dataloader-boilerplate/node_modules/@babel/parser/lib/index.js:6453:14)
    at _class.parseParenAndDistinguishExpression (/Users/sibelius/Dev/entria/feedback/graphql-dataloader-boilerplate/node_modules/@babel/parser/lib/index.js:2638:71)
    at _class.parseExprAtom (/Users/sibelius/Dev/entria/feedback/graphql-dataloader-boilerplate/node_modules/@babel/parser/lib/index.js:6283:21)
    at _class.parseExprSubscripts (/Users/sibelius/Dev/entria/feedback/graphql-dataloader-boilerplate/node_modules/@babel/parser/lib/index.js:5923:21)
    at _class.parseMaybeUnary (/Users/sibelius/Dev/entria/feedback/graphql-dataloader-boilerplate/node_modules/@babel/parser/lib/index.js:5902:21)
    at _class.parseExprOps (/Users/sibelius/Dev/entria/feedback/graphql-dataloader-boilerplate/node_modules/@babel/parser/lib/index.js:5811:21)
    at _class.parseMaybeConditional (/Users/sibelius/Dev/entria/feedback/graphql-dataloader-boilerplate/node_modules/@babel/parser/lib/index.js:5783:21)
  pos: 2309,
  loc: Position { line: 84, column: 40 },
  code: 'BABEL_PARSE_ERROR' }

**Comment by nicolo-ribaudo** [comment]
> `test: ['/src/**/*.ts'],`

`/src` is an absolute path, you should use `./src/**/*.ts`.

**Comment by sibelius** [comment]
the overrides is working well

**Comment by sibelius** [comment]
wrong override config

test: ['/src/**/*.ts'],

test: ['./src/**/*.ts'],
