### ISSUE TITLE
Plugin/Preset files are not allowed to export objects, only functions

### ISSUE THREAD

**Issue by michnath** [babel/babel#8688]
## Bug Report

**Current Behavior**
I got some exception raised here:
```
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/babel.js
    at createDescriptor (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/config-chain.js:315:26)
    at /Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/config-chain.js:278:7
    at buildRootChain (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/config-chain.js:118:22)
    at loadPrivatePartialConfig (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/partial.js:57:55)
    at loadFullConfig (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/full.js:43:39)
    at loadOptions (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/config/index.js:27:36)
    at OptionManager.init (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/core/lib/index.js:215:36)
    at getPlugins (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/eslint-import-resolver-babel-module/lib/index.js:14:28)
    at Object.exports.resolve (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/eslint-import-resolver-babel-module/lib/index.js:69:23)
    at v2 (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/eslint-module-utils/resolve.js:94:23)
```

**Input Code**
- REPL : https://github.com/michnath/rnw-ssr-multiplatforms/tree/broken-label

**Expected behavior/code**
No exception raised

**Babel Configuration (.babelrc, package.json, cli command)**
package.json
```
  "dependencies": {
    "cross-fetch": "^2.2.1",
    "expo": "^27.0.0",
    "express": "^4.15.2",
    "morgan": "^1.9.0",
    "prop-types": "^15.6.1",
    "qs": "^6.5.2",
    "react": "^16.0.0",
    "react-css-modules": "^4.7.3",
    "react-dom": "^16.0.0",
    "react-loadable": "^5.4.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
    "react-native-web": "^0.6.1",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.3.1",
    "react-router-redux": "^4.0.8",
    "recompose": "^0.27.1",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "reselect": "^3.0.1",
    "serialize-javascript": "^1.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-do-expressions": "^7.0.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-function-bind": "^7.0.0",
    "@babel/plugin-proposal-function-sent": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.0.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0",
    "@babel/plugin-proposal-pipeline-operator": "^7.0.0",
    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "autoprefixer": "^8.6.2",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^8.0.2",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-react-native-web": "^0.6.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-expo": "^4.0.0",
    "babel-preset-react-native": "5.0.2",
    "concurrently": "^3.5.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-import-resolver-babel-module": "^4.0.0",
    "eslint-plugin-flowtype": "^2.46.3",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.7.0",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "husky": "^0.14.3",
    "jest-expo": "^27.0.0",
    "lint-staged": "^7.1.0",
    "lodash-webpack-plugin": "^0.11.5",
    "node-sass": "^4.9.0",
    "onchange": "^4.0.0",
    "optimize-css-assets-webpack-plugin": "^4.0.2",
    "postcss-flexbugs-fixes": "^3.3.1",
    "prettier-eslint": "^8.8.1",
    "prettier-eslint-cli": "^4.7.1",
    "razzle": "^2.4.0",
    "react-native-scripts": "^1.13.1",
    "rimraf": "^2.6.2",
    "sass-loader": "^7.0.3",
    "webpack-bundle-analyzer": "^2.13.1"
  },
```
.babelrc
```
{
  "presets": [
    "razzle/babel",
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": 6
        }
      }
    ],
    "@babel/preset-env",
    "babel-preset-expo",
    "@babel/preset-env",
    "@babel/preset-env",
    "react-native"
  ],
  "env": {
    "development": {
      "plugins": [
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-transform-react-jsx-source"
      ]
    }
  },
  "plugins": [
    "react-native-web",
    "react-loadable/babel",
    [
      "module-resolver",
      {
        "root": [
          "./src"
        ],
        "alias": {
          "build": "./build/",
          "app": "./src/app",
          "config": "./src/config",
          "actions": "./src/app/actions",
          "components": "./src/app/components",
          "constants": "./src/app/constants",
          "containers": "./src/app/containers",
          "helpers": "./src/app/helpers",
          "reducers": "./src/app/reducers",
          "selectors": "./src/app/selectors",
          "store": "./src/app/store",
          "api": "./src/server/api",
          "react-native": "react-native-web"
        }
      }
    ],
    "transform-decorators-legacy",
    [
      "lodash",
      {
        "id": [
          "lodash",
          "recompose"
        ]
      }
    ],
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-json-strings",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-logical-assignment-operators",
    "@babel/plugin-proposal-optional-chaining",
    [
      "@babel/plugin-proposal-pipeline-operator",
      {
        "proposal": "minimal"
      }
    ],
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-do-expressions",
    "@babel/plugin-proposal-function-bind"
  ]
}
```

**Environment**
- Babel version(s): [v7.0.0]
- Node/npm version: [Node v8.10.0/npm 6.4.0]
- OS: MacOS Sierra 10.12.6

**Additional context/Screenshots**
There is another exception raised:
```
Requires Babel "^7.0.0-0", but was loaded with "6.25.0". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at api (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js:19:7)
    at /Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/Nia/Projects/razzle-rnw-redux-loadable/node_modules/razzle/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
    at eval (webpack-internal:///./src/index.js:1:7)
    at Object../src/index.js (/Users/Nia/Projects/razzle-rnw-redux-loadable/build/server.js:796:1)
    at __webpack_require__ (/Users/Nia/Projects/razzle-rnw-redux-loadable/build/server.js:684:30)
    at fn (/Users/Nia/Projects/razzle-rnw-redux-loadable/build/server.js:61:20)
    at Object.0 (/Users/Nia/Projects/razzle-rnw-redux-loadable/build/server.js:809:18)
    at __webpack_require__ (/Users/Nia/Projects/razzle-rnw-redux-loadable/build/server.js:684:30)
    at /Users/Nia/Projects/razzle-rnw-redux-loadable/build/server.js:751:37
    at Object.<anonymous> (/Users/Nia/Projects/razzle-rnw-redux-loadable/build/server.js:754:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by loganfsmyth** [comment]
Looks like your `razzle/babel` preset will only work with Babel 6. You'd have to drop it, or they'd need to release a compatible version.

**Comment by loganfsmyth** [comment]
Also, sorry this error isn't very helpful. We've got an issue filed in #8523 to make it tell you what is actually causing the problem.

**Comment by loganfsmyth** [comment]
I should add, it doesn't look like it does much of anything that you can't do yourself by loading the Babel plugins that it loads, and using the Babel 7.x versions where applicable. You've already got a bunch of them in your new config anyway.
