### ISSUE TITLE
Inheritance from Set fails

### ISSUE THREAD

**Issue by chevdor** [babel/babel#8705]
## Bug Report

**Current Behavior**
Inheriting from `Set` fails while the same test from `String` does work.

**Input Code**
- REPL or Repo link if applicable:

xset.js
```js
export default class XSet extends Set {
   // this is empty and enough to test
}
```

demo.js
```js
import XSet from './xset'
const n = new XSet([1, 2, 3])
console.log('YOU WON', n)
```

**Expected behavior/code**
The code should run and not throw errors.
The code DOES run from a node console.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
    "presets": ["env"]
}

```

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: 7.10,10.8,10.10
- OS: OSX
- How you are using Babel: `babel-node demo.js`

**Possible Solution**
No solution

**Additional context/Screenshots**

Error:
```
$ babel-node demo.js 
/Users/.../src/xset2.js:19
    return _possibleConstructorReturn(this, (XSet.__proto__ || Object.getPrototypeOf(XSet)).apply(this, arguments));
                                                                                            ^

TypeError: Constructor Set requires 'new'
    at XSet.Set (native)
    at new XSet (/Users/.../src/xset2.js:19:93)
    at Object.<anonymous> (/Users/...src/demo.js:3:11)
    at Module._compile (module.js:571:32)
    at loader (/Users/will/.nvm/versions/node/v7.10.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/.../node/v7.10.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
```

**Comment by nicolo-ribaudo** [comment]
This bug has been fixed in Babel 7 (https://github.com/babel/babel/pull/7020)
