### ISSUE TITLE
[typescript] Non-null assertion operator not being properly compiled

### ISSUE THREAD

**Issue by jgfidelis** [babel/babel#8706]
## Bug Report

**Current Behavior**

The non-null assertion operator is not being compiled properly. Description here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

The code snippet does not run:
```
const result = await graphql(schema, query, rootValue, context, variables);
expect(result.data!.MyResult.error).toBe(null);
```

Error:
`SyntaxError: /.../graphql/mutation/Test/__tests__/Test.spec.ts: Unexpected token, expected "," (76:20)`

More logs:
```
      at _class.raise (node_modules/@babel/parser/lib/index.js:3938:15)
      at _class.unexpected (node_modules/@babel/parser/lib/index.js:5247:16)
      at _class.expect (node_modules/@babel/parser/lib/index.js:5235:28)
      at _class.parseCallExpressionArguments (node_modules/@babel/parser/lib/index.js:6115:14)
      at _class.parseSubscript (node_modules/@babel/parser/lib/index.js:6028:32)
      at _class.parseSubscript (node_modules/@babel/parser/lib/index.js:2716:51)
      at _class.parseSubscripts (node_modules/@babel/parser/lib/index.js:5943:19)
      at _class.parseSubscripts (node_modules/@babel/parser/lib/index.js:2669:52)
      at _class.parseExprSubscripts (node_modules/@babel/parser/lib/index.js:5933:17)
      at _class.parseMaybeUnary (node_modules/@babel/parser/lib/index.js:5902:21)
```

**Expected behavior/code**
I should be able to use the operator.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  presets: [
    '@babel/preset-flow',
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
  ],
  plugins: [
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-transform-async-to-generator',
    '@babel/plugin-syntax-async-generators',
  ],
  overrides: [
    {
      test: ['/src/**/*.ts'],
      presets: [
        '@babel/preset-typescript',
        [
          '@babel/preset-env',
          {
            targets: {
              node: 'current',
            },
          },
        ],
      ],
    },
  ],
};
```

**Environment**
- Babel version(s): 7
- Node/npm version: node 8 lts, yarn
- OS: OSX
- Monorepo: no
- How you are using Babel: clil

**Comment by nicolo-ribaudo** [comment]
Does it work if you add `declare var Foo: string` at the start of the file? Just to ensure that the typescript plugin is loaded.
