### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by tbhaxor** [babel/babel#8774]
## Bug Report

**Current Behavior**
After creating a vue.js app i have added [vuetify](https://vuetifyjs.com/en/) and added pre installed templates to `App.vue` and `HelloWorld.vue` components. Then as per instructions i have started my app to view the changes with `$ npm run serve` command. And i got this error

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
BrowserslistError: [BABEL] /mnt/LESSONS/firestore-and-vuejs/app/src/main.js: /mnt/LESSONS/firestore-and-vuejs/app contains both .browserslistrc and package.json with browsers (While processing: "/mnt/LESSONS/firestore-and-vuejs/app/node_modules/@vue/babel-preset-app/index.js$0")
    at /mnt/LESSONS/firestore-and-vuejs/app/node_modules/browserslist/node.js:239:15
    at eachParent (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/browserslist/node.js:46:18)
    at Object.findConfig (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/browserslist/node.js:219:20)
    at Function.loadConfig (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/browserslist/node.js:150:37)
    at browserslist (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/browserslist/index.js:187:31)
    at getTargets (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/@vue/babel-preset-app/node_modules/@babel/preset-env/lib/targets-parser.js:133:50)
    at _default (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/@vue/babel-preset-app/node_modules/@babel/preset-env/lib/index.js:184:46)
    at /mnt/LESSONS/firestore-and-vuejs/app/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/@babel/core/lib/config/full.js:74:38)
    at recurseDescriptors (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/@babel/core/lib/config/full.js:94:27)
    at loadFullConfig (/mnt/LESSONS/firestore-and-vuejs/app/node_modules/@babel/core/lib/config/full.js:108:6)

 @ multi (webpack)-dev-server/client?http://192.168.43.121:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

List of my package hierarchy are [here](https://hastebin.com/omemorudoy.pl)

**Input Code**
- REPL or Repo link if applicable:

_entry file of vue app_
```js
import '@babel/polyfill'
import Vue from 'vue'
import './plugins/vuetify'
import App from './App.vue'

Vue.config.productionTip = false

new Vue({
  render: h => h(App)
}).$mount('#app')

```

**Expected behavior/code**
It must compile w/o any error

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  "presets": [
    [
      "@vue/app",
      {
        "useBuiltIns": "entry"
      }
    ]
  ]
}
```

**Environment**
- Babel version(s): 6.23.0
- Node/npm version: v8.12.0
- OS:Arch Linux 4.18.8-arch1-1-ARCH
- Monorepo: no
- How you are using Babel: loader

**Possible Solution**

**Additional context/Screenshots**
Vue CLI Version : 3.x
This is how i create app
```
$ vue create <app-name>
```
not
```
$ vue init webpack <app-name>
```

**Comment by mydansun** [comment]
Hi @tbhaxor , you should delete .browserslistr.

**Comment by tbhaxor** [comment]
@mydansun but earlier i have used it with `.browserslistr` and it was working fine.

**Comment by loganfsmyth** [comment]
The error says what the issue is. You can't have _both_ a `.browserlistrc` and also configure browserlist info in `package.json`.
