### ISSUE TITLE
async static methods

### ISSUE THREAD

**Issue by andrewmiller1** [babel/babel#8803]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

```
{ SyntaxError: /home/andrew/projects/connector-api/FileSystem.js: Unexpected token, expected "(" (2:15)

  1 | export default class myClass {
> 2 |   async static myMethod() {
    |                ^
  3 |   }
  4 |   constructor() {}
  5 | };
    at Parser.raise (/home/andrew/projects/connector-api/node_modules/@babel/parser/lib/index.js:3939:15)
    at Parser.unexpected (/home/andrew/projects/connector-api/node_modules/@babel/parser/lib/index.js:5248:16)
    at Parser.expect (/home/andrew/projects/connector-api/node_modules/@babel/parser/lib/index.js:5236:28)
    at Parser.parseFunctionParams (/home/andrew/projects/connector-api/node_modules/@babel/parser/lib/index.js:7832:10)
    at Parser.parseMethod (/home/andrew/projects/connector-api/node_modules/@babel/parser/lib/index.js:6856:10)
    at Parser.pushClassMethod (/home/andrew/projects/connector-api/node_modules/@babel/parser/lib/index.js:8076:30)
    at Parser.parseClassMemberWithIsStatic (/home/andrew/projects/connector-api/node_modules/@babel/parser/lib/index.js:8020:14)
    at Parser.parseClassMember (/home/andrew/projects/connector-api/node_modules/@babel/parser/lib/index.js:7937:10)
    at Parser.parseClassBody (/home/andrew/projects/connector-api/node_modules/@babel/parser/lib/index.js:7892:12)
    at Parser.parseClass (/home/andrew/projects/connector-api/node_modules/@babel/parser/lib/index.js:7842:10)
  pos: 46,
  loc: Position { line: 2, column: 15 },
  code: 'BABEL_PARSE_ERROR' }
```

**Input Code**
- REPL or Repo link if applicable:

```js
class myClass {
  async static myMethod() {
}
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

Babel recognize it's an async static method

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = function (api) {
  const plugins = [
    "@babel/proposal-class-properties",
    ["@babel/proposal-decorators", {
      "decoratorsBeforeExport": true
    }],
    "@babel/proposal-do-expressions",
    "@babel/proposal-export-default-from",
    "@babel/proposal-export-namespace-from",
    "@babel/proposal-function-bind",
    "@babel/proposal-function-sent",
    "@babel/proposal-json-strings",
    "@babel/proposal-logical-assignment-operators",
    "@babel/proposal-nullish-coalescing-operator",
    "@babel/proposal-numeric-separator",
    "@babel/proposal-optional-chaining",
    ["@babel/proposal-pipeline-operator", {
      "proposal": "minimal"
    }],
    "@babel/proposal-throw-expressions",
    "@babel/syntax-dynamic-import",
    "@babel/syntax-import-meta"
  ];
  const presets = [
    [
      "@babel/env",
      {
        spec: true,
        forceAllTransforms: true
      }
    ]
  ];
  const parserOpts = {
    plugins: [
      "classPrivateMethods"
    ]
  };


  api.cache(true);


  return {
    plugins,
    parserOpts,
    presets
  };
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34] 7.1.2 (@babel/core 7.1.2)
- Node/npm version: [e.g. Node 8/npm 5] node v10.11.0 npm 6.4.1
- OS: [e.g. OSX 10.13.4, Windows 10] Linux pop-os 4.19.0-041900rc2-generic
- Monorepo [e.g. yes/no/Lerna] n/a
- How you are using Babel: [e.g. `cli`, `register`, `loader`] cli

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

https://github.com/tc39/proposal-static-class-features#use-case

Let me know if you need anything

**Comment by nicolo-ribaudo** [comment]
It should be `static async`

**Comment by andrewmiller1** [comment]
You're right
