### ISSUE TITLE
Babel, CreateReactApp, Jest - Unknown options: base.configFile

### ISSUE THREAD

**Issue by JeffBaumgardt** [babel/babel#8814]
## Bug Report

**Current Behavior**
I really don't know where this issue should start but since it's a babel error I figured I would start here.

When running jest tests in a create-react-app I get the following error:

```cli
 FAIL  src/Components/MetaDataSelection/_tests_/MetaDataWrapper.test.js
  ● Test suite failed to run

    ReferenceError: [BABEL] C:\Node\Investigations\src\Components\MetaDataSelection\_tests_\MetaDataWrapper.test.js: Unknown option: base.configFile. Check out http://babeljs.io/docs/usage/options/ for more information about options.

    A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

    Invalid:
      `{ presets: [{option: value}] }`
    Valid:
      `{ presets: [['presetName', {option: value}]] }`

    For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options.

      at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
      at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (node_modules/babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)
```

I have no babel files in my code the only ones I find are based in other node_modules (ie. react-scripts)

It would be nice to get more of the stack trace to figure out which config file was being used as to fine which node_module was at fault, otherwise I'm stuck reviewing a dozen + packages source files to see if any configs look off to me

**Expected behavior/code**
Be it a little strange I would expect jest tests to execute.

**Babel Configuration (.babelrc, package.json, cli command)**

I do not have a babel config to my project.

**Environment**
- Babel version(s): none
- Node/npm version: Node 10.10.0 / NPM 6.0.0
- OS: Windows 10
- Monorepo: no
- How you are using Babel: [e.g. `cli`, `register`, `loader`]: I presume it would be a loader but I'm not sure what jest uses TBH

**Additional context/Screenshots**
I cannot get this to reproduce with a clean install of CRA. However, I do not have anything strange about my project that I can see. This started happening after the upgrade to CRA 2.0.2 from 1.1.5 in which they upgraded to babel 7. I have reviewed CRA's issues and have not found any issues, nor have I found any issues anywhere.

At this point I would just love a longer stack trace, longer than 6 to trace where the config is being called from to better track who to pass this issue to.

**Comment by JeffBaumgardt** [comment]
I take that back there is a closed issue with CRA - https://github.com/facebook/create-react-app/issues/5259 which describes this issue. At this point since others have seen the error I don't need this to fix a problem. Can I ask for an option to expand the stack limit?
