### ISSUE TITLE
@babel/register SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by nachocab** [babel/babel#8818]
I'm trying to use mocha with "@babel/register" but I'm getting this error:

```
(function (exports, require, module, __filename, __dirname) { import "core-js/modules/es6.array.iterator";
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected string
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
```

This is my current configuration (babel/core and babel/register have the same version, so I don't understand what I'm doing wrong):

```
├─ @babel/code-frame@7.0.0-beta.44
├─ @babel/core@7.0.0-beta.47
├─ @babel/generator@7.0.0-beta.47
├─ @babel/helper-annotate-as-pure@7.0.0-beta.47
├─ @babel/helper-builder-binary-assignment-operator-visitor@7.0.0-beta.47
├─ @babel/helper-call-delegate@7.0.0-beta.47
├─ @babel/helper-define-map@7.0.0-beta.47
├─ @babel/helper-explode-assignable-expression@7.0.0-beta.47
├─ @babel/helper-function-name@7.0.0-beta.47
├─ @babel/helper-get-function-arity@7.0.0-beta.47
├─ @babel/helper-hoist-variables@7.0.0-beta.47
├─ @babel/helper-member-expression-to-functions@7.0.0-beta.47
├─ @babel/helper-module-imports@7.0.0-beta.47
├─ @babel/helper-module-transforms@7.0.0-beta.47
├─ @babel/helper-optimise-call-expression@7.0.0-beta.47
├─ @babel/helper-plugin-utils@7.0.0-beta.47
├─ @babel/helper-regex@7.0.0-beta.47
├─ @babel/helper-remap-async-to-generator@7.0.0-beta.47
├─ @babel/helper-replace-supers@7.0.0-beta.47
├─ @babel/helper-simple-access@7.0.0-beta.47
├─ @babel/helper-split-export-declaration@7.0.0-beta.47
├─ @babel/helper-wrap-function@7.0.0-beta.47
├─ @babel/helpers@7.0.0-beta.47
├─ @babel/highlight@7.0.0-beta.44
├─ @babel/plugin-proposal-async-generator-functions@7.0.0-beta.47
├─ @babel/plugin-proposal-class-properties@7.0.0-beta.47
├─ @babel/plugin-proposal-decorators@7.0.0-beta.47
├─ @babel/plugin-proposal-object-rest-spread@7.0.0-beta.47
├─ @babel/plugin-proposal-optional-catch-binding@7.0.0-beta.47
├─ @babel/plugin-proposal-unicode-property-regex@7.0.0-beta.47
├─ @babel/plugin-syntax-async-generators@7.0.0-beta.47
├─ @babel/plugin-syntax-class-properties@7.0.0-beta.47
├─ @babel/plugin-syntax-decorators@7.0.0-beta.47
├─ @babel/plugin-syntax-dynamic-import@7.0.0-beta.47
├─ @babel/plugin-syntax-jsx@7.0.0-beta.47
├─ @babel/plugin-syntax-object-rest-spread@7.0.0-beta.47
├─ @babel/plugin-syntax-optional-catch-binding@7.0.0-beta.47
├─ @babel/plugin-transform-arrow-functions@7.0.0-beta.47
├─ @babel/plugin-transform-async-to-generator@7.0.0-beta.47
├─ @babel/plugin-transform-block-scoped-functions@7.0.0-beta.47
├─ @babel/plugin-transform-block-scoping@7.0.0-beta.47
├─ @babel/plugin-transform-classes@7.0.0-beta.47
├─ @babel/plugin-transform-computed-properties@7.0.0-beta.47
├─ @babel/plugin-transform-destructuring@7.0.0-beta.47
├─ @babel/plugin-transform-dotall-regex@7.0.0-beta.47
├─ @babel/plugin-transform-duplicate-keys@7.0.0-beta.47
├─ @babel/plugin-transform-exponentiation-operator@7.0.0-beta.47
├─ @babel/plugin-transform-for-of@7.0.0-beta.47
├─ @babel/plugin-transform-function-name@7.0.0-beta.47
├─ @babel/plugin-transform-literals@7.0.0-beta.47
├─ @babel/plugin-transform-modules-amd@7.0.0-beta.47
├─ @babel/plugin-transform-modules-commonjs@7.0.0-beta.47
├─ @babel/plugin-transform-modules-systemjs@7.0.0-beta.47
├─ @babel/plugin-transform-modules-umd@7.0.0-beta.47
├─ @babel/plugin-transform-new-target@7.0.0-beta.47
├─ @babel/plugin-transform-object-super@7.0.0-beta.47
├─ @babel/plugin-transform-parameters@7.0.0-beta.47
├─ @babel/plugin-transform-regenerator@7.0.0-beta.47
├─ @babel/plugin-transform-runtime@7.0.0-beta.47
├─ @babel/plugin-transform-shorthand-properties@7.0.0-beta.47
├─ @babel/plugin-transform-spread@7.0.0-beta.47
├─ @babel/plugin-transform-sticky-regex@7.0.0-beta.47
├─ @babel/plugin-transform-template-literals@7.0.0-beta.47
├─ @babel/plugin-transform-typeof-symbol@7.0.0-beta.47
├─ @babel/plugin-transform-unicode-regex@7.0.0-beta.47
├─ @babel/preset-env@7.0.0-beta.47
├─ @babel/register@7.0.0-beta.47
├─ @babel/runtime-corejs2@7.0.0
├─ @babel/runtime@7.0.0
├─ @babel/template@7.0.0-beta.47
├─ @babel/traverse@7.0.0-beta.47
├─ @babel/types@7.0.0-beta.47
```

**Comment by nicolo-ribaudo** [comment]
What is your Babel config?

**Comment by nachocab** [comment]
It turned out to be an issue due to having the wrong babel config. I changed it to `@babel/preset-env` and now it works. Thanks, Nicolò.
