### ISSUE TITLE
Error Module build failed (from ./node_modules/babel-loader/lib/index.js): in React

### ISSUE THREAD

**Issue by ayoush-edy** [babel/babel#8935]
```
ERROR in ./main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In D:\React Projects\ReactSetup\node_modules\babel-preset-es2015\lib\index.js
    at createDescriptor (D:\React Projects\ReactSetup\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at items.map (D:\React Projects\ReactSetup\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (D:\React Projects\ReactSetup\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (D:\React Projects\ReactSetup\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at passPerPreset (D:\React Projects\ReactSetup\node_modules\@babel\core\lib\config\config-descriptors.js:58:96)
    at cachedFunction (D:\React Projects\ReactSetup\node_modules\@babel\core\lib\config\caching.js:33:19)
    at presets.presets (D:\React Projects\ReactSetup\node_modules\@babel\core\lib\config\config-descriptors.js:29:84)
    at mergeChainOpts (D:\React Projects\ReactSetup\node_modules\@babel\core\lib\config\config-chain.js:315:26)
    at D:\React Projects\ReactSetup\node_modules\@babel\core\lib\config\config-chain.js:278:7
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./main.js main[2]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 448 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
i ｢wdm｣: Failed to compile.
```
Package.json
```
{
  "name": "reactsetup",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server --mode development --open --hot",
    "build": "webpack --mode production"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  },
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "@babel/preset-env": "^7.1.0",
    "babel-loader": "^8.0.4",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-es2015": "^1.3.0",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.23.1"
  }
}
```

webpack.config.js
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
   entry: './main.js',
   output: {
      path: path.join(__dirname, '/bundle'),
      filename: 'index_bundle.js'
   },
   devServer: {
      inline: true,
      port: 8080
   },
   module: {
      rules: [
         {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
               presets: ['es2015', 'react']
            }
         }
      ]
   },
   plugins:[
      new HtmlWebpackPlugin({
         template: './index.html'
      })
   ]
}
```

**Comment by loganfsmyth** [comment]
```
['es2015', 'react']
```
is Babel 6. If you're using Babel 7, you want
```
['@babel/preset-env', '@babel/preset-react']
```

**Comment by loganfsmyth** [comment]
Do you have a `.babelrc` that might also be loading these presets?

**Comment by Punit-white** [comment]
`ERROR in ./client/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-react' from 'C:\xampp\htdocs\graphix\admin'
    at Function.module.exports [as sync] (C:\xampp\htdocs\graphix\admin\node_modules\resolve\lib\sync.js:58:15)
    at resolveStandardizedName (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
    at resolvePreset (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\files\plugins.js:58:10)
    at loadPreset (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\files\plugins.js:77:20)
    at createDescriptor (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
    at items.map (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\config-chain.js:320:26)
    at C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\config-chain.js:283:7
    at buildRootChain (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\config-chain.js:120:22)
    at loadPrivatePartialConfig (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\partial.js:85:55)
    at Object.loadPartialConfig (C:\xampp\htdocs\graphix\admin\node_modules\@babel\core\lib\config\partial.js:110:18)
    at Object.<anonymous> (C:\xampp\htdocs\graphix\admin\node_modules\babel-loader\lib\index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\xampp\htdocs\graphix\admin\node_modules\babel-loader\lib\index.js:3:103)
    at _next (C:\xampp\htdocs\graphix\admin\node_modules\babel-loader\lib\index.js:5:194)
    at C:\xampp\htdocs\graphix\admin\node_modules\babel-loader\lib\index.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\xampp\htdocs\graphix\admin\node_modules\babel-loader\lib\index.js:5:97)
    at Object._loader (C:\xampp\htdocs\graphix\admin\node_modules\babel-loader\lib\index.js:220:18)
    at Object.loader (C:\xampp\htdocs\graphix\admin\node_modules\babel-loader\lib\index.js:56:18)
    at Object.<anonymous> (C:\xampp\htdocs\graphix\admin\node_modules\babel-loader\lib\index.js:51:12)
 @ multi ./client/index.js main[0]`

Can you guide what I m doing?

**Comment by nahomypuente** [comment]
@Punit-white npm i @babel/preset-react
