### ISSUE TITLE
Object rest parameters in arrows throws during transpilation

### ISSUE THREAD

**Issue by yuchi** [babel/babel#897]
```
$ node --version
v0.10.33
$ babel-node --version
4.5.1
$ babel-node --experimental
> (({ o, ...x }) => {})
TypeError: repl: Cannot read property 'start' of undefined
    at toAssignable (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2299:53)
    at toAssignableList (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2346:11)
    at parseArrowExpression (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3573:19)
    at parseParenAndDistinguishExpression (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3345:16)
    at parseExprAtom (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3236:14)
    at parseExprSubscripts (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3108:16)
    at parseMaybeUnary (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3090:16)
    at parseExprOps (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3044:16)
    at parseMaybeConditional (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:3020:16)
    at parseMaybeAssign (/usr/local/lib/node_modules/babel/node_modules/acorn-babel/acorn_csp.js:2999:16)
```

yet this works:

```
$ babel-node --experimental
> function s({ o, ...x }) { return x }
undefined
> s({ o: 0, a: 42 })
{ a: 42 }
```

**Comment by yuchi** [comment]
Surrounding lines:

```js
/*    */        case "ObjectExpression":
/*    */          node.type = "ObjectPattern";
/*    */          for (var i = 0; i < node.properties.length; i++) {
/*    */            var prop = node.properties[i];
/*2299*/            if (prop.kind !== "init") raise(prop.key.start, "Object pattern can't contain getter or setter");
/*    */            toAssignable(prop.value, isBinding);
/*    */          }
/*    */          break;
```

And `prop` has the following values:

```json
{
  "type": "SpreadProperty",
  "start": 7,
  "end": 11,
  "loc": {
    "start": {
      "line": 1,
      "column": 7
    },
    "end": {
      "line": 1,
      "column": 11
    }
  },
  "range": [ 7, 11 ],
  "argument": {
    "type": "Identifier",
    "start": 10,
    "end": 11,
    "loc": {
      "start": {
        "line": 1,
        "column": 10
      },
      "end": {
        "line": 1,
        "column": 11
      }
    },
    "range": [ 10, 11 ],
    "name": "x"
  }
}
```

**Comment by yuchi** [comment]
Probably this should go in `acorn-babel`. Tell me so, and I’ll move it.

**Comment by yuchi** [comment]
Fantastic. As always.
