### ISSUE TITLE
babel 7.1.5 won't compile with retainLines: true and plugin-proposal-object-rest-spread

### ISSUE THREAD

**Issue by hibikiledo** [babel/babel#8992]
## Bug Report

**Current Behavior**
```
TypeError: Cannot read property 'start' of undefined
    at Generator.ArrowFunctionExpression (/Users/hibikiledo/Desktop/babel-generator-7.1.5-bug/node_modules/@babel/generator/lib/generators/methods.js:136:72)
    at withSource (/Users/hibikiledo/Desktop/babel-generator-7.1.5-bug/node_modules/@babel/generator/lib/printer.js:299:22)
    at Buffer.withSource (/Users/hibikiledo/Desktop/babel-generator-7.1.5-bug/node_modules/@babel/generator/lib/buffer.js:185:28)
    at Generator.withSource (/Users/hibikiledo/Desktop/babel-generator-7.1.5-bug/node_modules/@babel/generator/lib/printer.js:178:15)
    at Generator.print (/Users/hibikiledo/Desktop/babel-generator-7.1.5-bug/node_modules/@babel/generator/lib/printer.js:298:10)
    at Generator.printJoin (/Users/hibikiledo/Desktop/babel-generator-7.1.5-bug/node_modules/@babel/generator/lib/printer.js:362:12)
    at Generator.printList (/Users/hibikiledo/Desktop/babel-generator-7.1.5-bug/node_modules/@babel/generator/lib/printer.js:422:17)
    at Generator.CallExpression (/Users/hibikiledo/Desktop/babel-generator-7.1.5-bug/node_modules/@babel/generator/lib/generators/expressions.js:181:8)
    at withSource (/Users/hibikiledo/Desktop/babel-generator-7.1.5-bug/node_modules/@babel/generator/lib/printer.js:299:22)
    at Buffer.withSource (/Users/hibikiledo/Desktop/babel-generator-7.1.5-bug/node_modules/@babel/generator/lib/buffer.js:185:28)
```

**Input Code**
Please see https://github.com/hibikiledo/babel-generator-7.1.5-bug

**Expected behavior/code**
Babel should compile input code without throwing an error.

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
  "env": {
    "development": {
      "retainLines": true,
      "plugins": [
        "@babel/plugin-proposal-object-rest-spread"
      ]
    }
  }
}
```

**Environment**
- Babel version(s): 7.1.5
- Node/npm version: Node 8.12.0
- OS: OSX 10.13.6
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**
Remove `retainLines` seems to fix the problem.

**Additional context/Screenshots**
none

**Comment by loganfsmyth** [comment]
Thanks, I posted a fix: https://github.com/babel/babel/pull/9003

Do you mind if I ask why you're using `retainLines`? We've often considered removing it.

**Comment by hibikiledo** [comment]
I don't know why it is there in the first place.  I checked the commit message and still had no clues.

I ended up removing it permanently since I already had source maps enabled.
