### ISSUE TITLE
Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by lidaof** [babel/babel#8999]
## Bug Report

**Current Behavior**
```
> rm -rf dist && cross-env NODE_ENV=production babel src/ --out-dir dist --extensions ".ts,.tsx,.js,.css,.json,.jsx" --copy-files --ignore __tests__,spec.js,test.js,__snapshots__,umd,build,public,node_modules

Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/dli/eg-react/frontend/node_modules/babel-preset-react-app/index.js
    at createDescriptor (/Users/dli/eg-react/frontend/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/dli/eg-react/frontend/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/dli/eg-react/frontend/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/dli/eg-react/frontend/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/dli/eg-react/frontend/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/dli/eg-react/frontend/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/dli/eg-react/frontend/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/dli/eg-react/frontend/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/dli/eg-react/frontend/node_modules/@babel/core/lib/config/partial.js:85:55)
```

```js
{
    "presets": [
        "react-app",
        "@babel/preset-typescript",
        "@babel/preset-env",
        "@babel/preset-react"
    ]
}
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
"devDependencies": {
    "@babel/cli": "^7.1.5",
    "@babel/core": "^7.1.5",
    "@babel/preset-env": "^7.1.5",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.1.0",
}
```

**Environment**
- Babel version(s): [7.1.5]
- Node/npm version: [ Node v10.13.0]
- OS: [OSX 10.13.4,]
- Monorepo [no]
- How you are using Babel: [`cli`]

**Comment by nicolo-ribaudo** [comment]
What version of `babel-preset-react-app` are you using?

**Comment by lidaof** [comment]
Hi @nicolo-ribaudo , thanks for replying.
I removed `"react-app",` from the presents and it's working now, you can close this if you want.
