### ISSUE TITLE
SyntaxErrors ignore startLine option

### ISSUE THREAD

**Issue by tolmasky** [babel/babel#9015]
## Bug Report

**Current Behavior**
If a SyntaxError is thrown from @babel/parse, `startLine` is ignored (it uses the "real" start line).

**Input Code**

https://runkit.com/tolmasky/babel-issue-9015---syntaxerrors-ignore-startline-option

```js
const { parse } = require("@babel/parser");

parse("5+", { startLine: 10 });
```

**Expected behavior/code**
It should take into account `startLine`.

**Environment**
- Babel version(s): 7.1.5

**Comment by nicolo-ribaudo** [comment]
This seems to be fixed now. That code throws
```
SyntaxError: Unexpected token (10:2)
    at Parser.raise (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/location.js:27:17)
    at Parser.unexpected (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/util.js:99:16)
    at Parser.parseExprAtom (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/expression.js:766:20)
    at Parser.parseExprSubscripts (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/expression.js:337:23)
    at Parser.parseMaybeUnary (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/expression.js:317:21)
    at Parser.parseExprOpBaseRightExpr (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/expression.js:277:34)
    at Parser.parseExprOpRightExpr (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/expression.js:270:21)
    at Parser.parseExprOp (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/expression.js:242:27)
    at Parser.parseExprOps (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/expression.js:202:17)
    at Parser.parseMaybeConditional (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/expression.js:165:23)

```
