### ISSUE TITLE
Babel @babel/register not view @babel/env in presets

### ISSUE THREAD

**Issue by FeklistovGleb** [babel/babel#9090]
## Bug Report

**Current Behavior**
Babel @babel/register not view @babel/env in presets

```js
require('@babel/register')({
    babelrc: false,
    presets: ['@babel/env', '@babel/react'],
});
require('@babel/polyfill');
require('./src/server');
```

**Expected behavior/code**
(function (exports, require, module, __filename, __dirname) { import http from "http";
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Module._compile (F:\self-mono-repo\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (F:\self-mono-repo\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by muneebejazz** [comment]
Its
@babel/preset-env


Not @babel/env

**Comment by FeklistovGleb** [comment]
https://babeljs.io/docs/en/v7-migration#use-in-the-config

How about this?

module.exports = {
  presets: ["@babel/env"], // "@babel/preset-env"
  plugins: ["@babel/transform-arrow-functions"], // same as "@babel/plugin-transform-arrow-functions"
};

**Comment by FeklistovGleb** [comment]
"@babel/env" = "@babel/preset-env" or NOT ?

**Comment by FeklistovGleb** [comment]
Ok, lets try:

Code:
```
require('@babel/register')({
    babelrc: false,
    presets: ['@babel/preset-env'],
});
require('@babel/polyfill');
require('./src/server');
```

Result: 
```
"C:\Program Files\JetBrains\WebStorm 2018.2.6\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run super --scripts-prepend-node-path=auto

> @mono/site@1.0.0 super F:\self-mono-repo\packages\site
> supervisor index.js


Running node-supervisor with
  program 'index.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node index.js'
Watching directory 'F:\self-mono-repo\packages\site' for changes.
Press rs for restarting the process.
F:\self-mono-repo\packages\express\index.js:1
(function (exports, require, module, __filename, __dirname) { import http from "http";
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Module._compile (F:\self-mono-repo\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (F:\self-mono-repo\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
Program node index.js exited with code 1

Starting child process with 'node index.js'
Received SIGINT, killing child process...
Parent process exiting, terminating child...

Process finished with exit code 1
```

Code:
```
require('@babel/register')({
    babelrc: false,
    presets: ['@babel/env'],
});
require('@babel/polyfill');
require('./src/server');
```

Result: 
```
"C:\Program Files\JetBrains\WebStorm 2018.2.6\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run super --scripts-prepend-node-path=auto

> @mono/site@1.0.0 super F:\self-mono-repo\packages\site
> supervisor index.js


Running node-supervisor with
  program 'index.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node index.js'
Watching directory 'F:\self-mono-repo\packages\site' for changes.
Press rs for restarting the process.
F:\self-mono-repo\packages\express\index.js:1
(function (exports, require, module, __filename, __dirname) { import http from "http";
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Module._compile (F:\self-mono-repo\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (F:\self-mono-repo\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
Program node index.js exited with code 1

Starting child process with 'node index.js'
Received SIGINT, killing child process...
Parent process exiting, terminating child...

Process finished with exit code 1
```

**Comment by loganfsmyth** [comment]
`@babel/register` only compiles files inside the working directory by default. Since you're running it inside `packages/site/`, it will not compile `packages/express/`. If you want that, you'd want to opt in to compiling your whole monorepo with something like

```
require('@babel/register')({
    babelrc: false,
    presets: ['@babel/env'],
    only: [__dirname + "/../../"],
    ignore: ["**/node_modules"],
});
```

**Comment by FeklistovGleb** [comment]
```
"C:\Program Files\JetBrains\WebStorm 2018.2.6\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" F:\self-mono-repo\packages\site\index_old.js
F:\self-mono-repo\node_modules\convert-source-map\index.js:61
  return SafeBuffer.Buffer.from(json, 'utf8').toString('base64');
                           ^

TypeError: Cannot read property 'from' of undefined
    at Converter.toBase64 (F:\self-mono-repo\node_modules\convert-source-map\index.js:61:28)
    at Converter.toComment (F:\self-mono-repo\node_modules\convert-source-map\index.js:65:21)
    at generateCode (F:\self-mono-repo\node_modules\@babel\core\lib\transformation\file\generate.js:78:76)
    at runSync (F:\self-mono-repo\node_modules\@babel\core\lib\transformation\index.js:50:51)
    at transformSync (F:\self-mono-repo\node_modules\@babel\core\lib\transform.js:43:38)
    at Object.transform (F:\self-mono-repo\node_modules\@babel\core\lib\transform.js:22:38)
    at compile (F:\self-mono-repo\node_modules\@babel\register\lib\node.js:73:20)
    at compileHook (F:\self-mono-repo\node_modules\@babel\register\lib\node.js:102:12)
    at Module._compile (F:\self-mono-repo\node_modules\pirates\lib\index.js:77:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)

Process finished with exit code 1
```

**Comment by FeklistovGleb** [comment]
Code:
https://github.com/FeklistovGleb/self-mono-repo/blob/master/packages/site/index_old.js

**Comment by FeklistovGleb** [comment]
Fine works over webpack
https://github.com/FeklistovGleb/self-mono-repo/blob/master/packages/site/webpack.config.js

**Comment by FeklistovGleb** [comment]
Without webpack works only babel 6.. version

**Comment by loganfsmyth** [comment]
What version of Node are you running?

**Comment by FeklistovGleb** [comment]
v10.13.0

**Comment by loganfsmyth** [comment]
Oh I think I had a mistake in my example. Can you try
```
require('@babel/register')({
    babelrc: false,
    presets: ['@babel/env'],
    only: [__dirname + "/../../"],
    ignore: [__dirname + "/../../**/node_modules"],
});
```

**Comment by muneebejazz** [comment]
what are you trying to do?

**Comment by FeklistovGleb** [comment]
> what are you trying to do?

This is big secret

**Comment by muneebejazz** [comment]
for babel version 7 
presets;['@babel/preset-env'] works

**Comment by FeklistovGleb** [comment]
Final worked code 
```
require('@babel/register')({
    babelrc: false,
    presets: ['@babel/env', '@babel/react'],
    ignore: [/node_modules/],
});
require('@babel/polyfill');
require('./src/server');
```

**Comment by FeklistovGleb** [comment]
Simple ignore: [/node_modules/],

**Comment by FeklistovGleb** [comment]
Works from everywere

**Comment by FeklistovGleb** [comment]
Thanks to all

**Comment by FeklistovGleb** [comment]
> Oh I think I had a mistake in my example. Can you try
> 
> ```
> require('@babel/register')({
>     babelrc: false,
>     presets: ['@babel/env'],
>     only: [__dirname + "/../../"],
>     ignore: [__dirname + "/../../**/node_modules"],
> });
> ```

Big thanks
