### ISSUE TITLE
helper-create-class-features-plugin path.isClassPrivateMethod is not a function

### ISSUE THREAD

**Issue by TheAifam5** [babel/babel#9120]
I dont have time to fill everything here but:
TypeError: path.isClassPrivateMethod is not a function

**Comment by nicolo-ribaudo** [comment]
Could you try to delete and reinstall your node_modules? I think that for some reason  a new plugin is trying to load an old version of something.

**Comment by neet** [comment]
I also got this error when upgrading to `7.2.0` but once removed `node_modules` then codes generated successfully 🙆‍♂️

**Comment by TheAifam5** [comment]
yup that fixed the problem

**Comment by dlebedynskyi** [comment]
still getting this after `rm -rf node-modules` and upding all `@babel/*` to 7.2.0

**Comment by james-chertkov** [comment]
Same as dlebedynskyi. Also getting this error after updating babel deps. 
```
ERROR in ./src/quality-app/tictactoe.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: path.isClassPrivateMethod is not a function
        at verifyUsedFeatures (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/helper-create-class-features-plugin/lib/features.js:46:12)
        at PluginPass.Class (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/helper-create-class-features-plugin/lib/index.js:69:42)
        at newFn (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/visitors.js:193:21)
        at NodePath._call (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/path/context.js:53:20)
        at NodePath.call (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/path/context.js:40:17)
        at NodePath.visit (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/path/context.js:88:12)
        at TraversalContext.visitQueue (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/context.js:118:16)
        at TraversalContext.visitQueue (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/context.js:124:21)
        at TraversalContext.visitMultiple (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/context.js:85:17)
        at TraversalContext.visit (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/context.js:144:19)
        at Function.traverse.node (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/index.js:94:17)
        at NodePath.visit (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/path/context.js:95:18)
        at TraversalContext.visitQueue (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/context.js:118:16)
        at TraversalContext.visitSingle (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/context.js:90:19)
        at TraversalContext.visit (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/context.js:146:19)
        at Function.traverse.node (/Users/jchert/clones/nde-quality-exp/node_modules/@babel/traverse/lib/index.js:94:17)
     @ ./src/quality-app/app.js 3:0-31 5:38-42
     @ ./src/client.js
     @ multi (webpack)-dev-server/client?http://localhost:3001 ./src/client.js
```

**Comment by inv8der** [comment]
I use yarn as my package manager. I noticed that after updating babel + plugins to 7.2.0, `@babel/helper-create-class-features-plugin` doesn't have a hard dependency on `@babel/traverse`, which is where this error seems to originate from. As result, it will use whatever version installed, which in my case is either 7.0.0 or 7.1.6

```
"@babel/helper-create-class-features-plugin@^7.2.0":
  version "7.2.0"
  resolved "https://registry.yarnpkg.com/@babel/helper-create-class-features-plugin/-/helper-create-class-features-plugin-7.2.0.tgz#8d52930558897042444e670f26ae6581ec9a4a4a"
  integrity sha512-INigeagreiKKZ4Ouo8Wun2y+XT4KxAdNztesU3C/AynDsdtIu00qjgw6QXSM3hVzQ7FvAL4sFmoEpFPuXkeHiw==
  dependencies:
    "@babel/helper-function-name" "^7.1.0"
    "@babel/helper-member-expression-to-functions" "^7.0.0"
    "@babel/helper-optimise-call-expression" "^7.0.0"
    "@babel/helper-plugin-utils" "^7.0.0"
    "@babel/helper-replace-supers" "^7.1.0"

"@babel/traverse@^7.0.0":
  version "7.0.0"
  resolved "https://registry.yarnpkg.com/@babel/traverse/-/traverse-7.0.0.tgz#b1fe9b6567fdf3ab542cfad6f3b31f854d799a61"
  dependencies:
    "@babel/code-frame" "^7.0.0"
    "@babel/generator" "^7.0.0"
    "@babel/helper-function-name" "^7.0.0"
    "@babel/helper-split-export-declaration" "^7.0.0"
    "@babel/parser" "^7.0.0"
    "@babel/types" "^7.0.0"
    debug "^3.1.0"
    globals "^11.1.0"
    lodash "^4.17.10"

"@babel/traverse@^7.1.0", "@babel/traverse@^7.1.5", "@babel/traverse@^7.1.6":
  version "7.1.6"
  resolved "https://registry.yarnpkg.com/@babel/traverse/-/traverse-7.1.6.tgz#c8db9963ab4ce5b894222435482bd8ea854b7b5c"
  integrity sha512-CXedit6GpISz3sC2k2FsGCUpOhUqKdyL0lqNrImQojagnUMXf8hex4AxYFRuMkNGcvJX5QAFGzB5WJQmSv8SiQ==
  dependencies:
    "@babel/code-frame" "^7.0.0"
    "@babel/generator" "^7.1.6"
    "@babel/helper-function-name" "^7.1.0"
    "@babel/helper-split-export-declaration" "^7.0.0"
    "@babel/parser" "^7.1.6"
    "@babel/types" "^7.1.6"
    debug "^4.1.0"
    globals "^11.1.0"
    lodash "^4.17.10"
```

After removing and regenerating my yarn.lock file, all is well... expect for updates to other dependencies that broke things.

**Comment by nicolo-ribaudo** [comment]
The fix will be released soon.

**Comment by TheAifam5** [comment]
That was fast :D
