### ISSUE TITLE
Error: Cannot find module 'core-js/modules/es6.array.sort'

### ISSUE THREAD

**Issue by MrEfrem** [babel/babel#9134]
## Bug Report

**Current Behavior**

I get an error:
```
Error: Cannot find module 'core-js/modules/es6.array.sort'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.../WebProjects/myproject/src/utils/content.js:14:1)
    at Module._compile (module.js:653:30)
    at Module._compile (.../WebProjects/myproject/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (.../WebProjects/myproject/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:566:32)
```
I'm sure broken latest release and this issue can be related: https://github.com/babel/babel/issues/8253

**Environment**
- Babel version(s): v7.2.0
- Node/npm version: Node 8/npm 6.4.1
- OS: OSX 10.14.1
- Monorepo no
- How you are using Babel: [`register`, `loader`]

**Possible Solution**
```
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "node": 8
        },
        "useBuiltIns": "usage"
      }
    ],
    "@babel/flow"
  ]
}
```
If I change "useBuiltIns" from "usage" to "entry" then all works.

**Comment by loganfsmyth** [comment]
If you're using `usage` you need to have `core-js` in your dependencies.

**Comment by MrEfrem** [comment]
oh, ok. Thanks.
