### ISSUE TITLE
preset-env's `useBuiltIns: usage` doesn't work properly with current `regenerator-runtime` version

### ISSUE THREAD

**Issue by Hypnosphi** [babel/babel#9205]
## Bug Report

**Current Behavior**
`useBuiltIns: usage` output throws an error when using latest `regenerator-runtime` release.

```
$ yarn start
yarn run v1.12.3
$ babel index.js -d dist && node dist/index.js
Successfully compiled 1 file with Babel.
~/usebuiltins-usage-repro/dist/index.js:7
regeneratorRuntime.mark(foo);
^

ReferenceError: regeneratorRuntime is not defined
    at Object.<anonymous> (~/usebuiltins-usage-repro/dist/index.js:7:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
error Command failed with exit code 1.

```

**Input Code**
https://github.com/Hypnosphi/usebuiltins-usage-repro

**Expected behavior/code**
No errors

**Babel Configuration (.babelrc, package.json, cli command)**

https://github.com/Hypnosphi/usebuiltins-usage-repro/blob/master/package.json

**Possible Solution**

https://github.com/babel/babel/issues/9044#issuecomment-444143528

**Comment by Hypnosphi** [comment]
Does not reproduce with 7.4
