### ISSUE TITLE
babel-node throws exception TypeError: Cannot read property 'canCompile' of undefined

### ISSUE THREAD

**Issue by philmetzger** [babel/babel#9252]
When I perform the following, there is an exception thrown as can be seen below:

```
$ npm run dev

> maketube@1.0.0 dev C:\Projects\maketube\frontend
> babel-node server.js --presets env,stage-2

C:\Projects\maketube\frontend\node_modules\babel-register\lib\node.js:177
hookExtensions(_babelCore.util.canCompile.EXTENSIONS);
                               ^

TypeError: Cannot read property 'canCompile' of undefined
    at Object.<anonymous> (C:\Projects\maketube\frontend\node_modules\babel-register\lib\node.js:177:32)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Projects\maketube\frontend\node_modules\babel-cli\lib\_babel-node.js:35:22)
    at Module._compile (module.js:635:30)
```

Not sure why, and I have tried removing node modules, etc. I use node version 8.9.1 but I have also tried with node 11.

here is my package.json:

```
{
  "name": "maketube",
  "version": "1.0.0",
  "scripts": {
    "dev": "babel-node server.js --presets env,stage-2",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
  "author": "phil",
  "license": "MIT",
  "dependencies": {
    "autoprefixer": "7.1.5",
    "aws-sdk": "^2.213.1",
    "axios": "0.15.3",
    "babel-cli": "^6.26.0",
    "babel-plugin-inline-react-svg": "^0.4.0",
    "babel-plugin-module-resolver": "^2.7.1",
    "babel-plugin-wrap-in-js": "^1.1.0",
    "body-parser": "^1.18.2",
    "classnames": "^2.2.5",
    "cookie-parser": "^1.4.3",
    "express": "^4.16.3",
    "faker": "^4.1.0",
    "glob": "^7.1.2",
    "http-proxy-middleware": "^0.17.4",
    "jsonwebtoken": "^8.2.0",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.11",
    "moment": "^2.21.0",
    "net": "^1.0.2",
    "next": "latest",
    "njwt": "^0.4.0",
    "node-sass": "^4.4.0",
    "normalize.css": "^7.0.0",
    "postcss-easy-import": "^3.0.0",
    "postcss-loader": "^2.0.7",
    "prop-types": "^15.6.1",
    "raw-loader": "^0.5.1",
    "react": "^16.0.0",
    "react-datepicker": "^0.64.0",
    "react-dom": "^16.0.0",
    "react-expand-collapse": "^0.2.0",
    "react-horizontal-timeline": "^1.4.0",
    "sass-loader": "^6.0.6",
    "semantic-ui-icon": "^2.2.12",
    "semantic-ui-react": "^0.73.0",
    "sqlite": "^2.9.0",
    "sqlite3": "^3.1.13",
    "superagent": "^3.4.0",
    "tls": "0.0.1",
    "universal-cookie": "^2.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "babel-core": "^7.0.0-bridge",
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.24.1",
    "now": "^8.3.10"
  }
}
```

also provided is my babelrc file:

```
{
  "plugins": [
    ["inline-react-svg"],
    [
      "module-resolver", {
        "root": ["."],
        "alias": {
          "styles": "./styles"
        },
        "cwd": "babelrc"
    }],
    [
      "wrap-in-js",
      {
        "extensions": ["css$", "scss$"]
      }
    ]
  ],
  "presets": [
    "next/babel"
  ],
  "ignore": []
}
```

Can someone help me figure out what to do next to debug this? Or what the issue is?

Thanks

**Comment by nicolo-ribaudo** [comment]
You are using Babel/core v7 with Babel 6 packages. You should update everything (except bridge) to v7, or downgrade core to v6 and remove bridge.

**Comment by philmetzger** [comment]
@nicolo-ribaudo thanks! I think thats fixed the problem but I ran into another related one:

```
$ npm run dev

> maketube@1.0.0 dev C:\Projects\maketube\frontend
> babel-node server.js --presets @babel/env

C:\Projects\maketube\frontend\node_modules\babel-plugin-module-resolver\lib\index.js:88
      })[1];
        ^

TypeError: Cannot read property '1' of undefined
    at Plugin.manipulateOptions (C:\Projects\maketube\frontend\node_modules\babel-plugin-module-resolver\lib\index.js:88:9)
    at normalizeOptions (C:\Projects\maketube\frontend\node_modules\@babel\core\lib\transformation\normalize-opts.js:59:16)
    at runSync (C:\Projects\maketube\frontend\node_modules\@babel\core\lib\transformation\index.js:44:86)
    at transformSync (C:\Projects\maketube\frontend\node_modules\@babel\core\lib\transform.js:43:38)
    at Object.transform (C:\Projects\maketube\frontend\node_modules\@babel\core\lib\transform.js:22:38)
    at compile (C:\Projects\maketube\frontend\node_modules\@babel\register\lib\node.js:73:20)
    at compileHook (C:\Projects\maketube\frontend\node_modules\@babel\register\lib\node.js:102:12)
    at Module._compile (C:\Projects\maketube\frontend\node_modules\pirates\lib\index.js:77:29)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (C:\Projects\maketube\frontend\node_modules\pirates\lib\index.js:88:7)
```

And I tried updating babel-plugin-module-resolver. Can you see anything that looks wrong? My babelrc remains as above in my first post.

Updated package.json:

```
{
  "name": "maketube",
  "version": "1.0.0",
  "scripts": {
    "dev": "babel-node server.js --presets @babel/env",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
  "author": "phil",
  "license": "MIT",
  "dependencies": {
    "autoprefixer": "7.1.5",
    "aws-sdk": "^2.213.1",
    "axios": "0.15.3",
    "babel-plugin-wrap-in-js": "^1.1.1",
    "babel-plugin-module-resolver": "^2.7.1",
    "body-parser": "^1.18.2",
    "classnames": "^2.2.5",
    "cookie-parser": "^1.4.3",
    "express": "^4.16.3",
    "faker": "^4.1.0",
    "glob": "^7.1.2",
    "http-proxy-middleware": "^0.17.4",
    "jsonwebtoken": "^8.2.0",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.11",
    "moment": "^2.21.0",
    "net": "^1.0.2",
    "next": "latest",
    "njwt": "^0.4.0",
    "node-sass": "^4.4.0",
    "normalize.css": "^7.0.0",
    "postcss-easy-import": "^3.0.0",
    "postcss-loader": "^2.0.7",
    "prop-types": "^15.6.1",
    "raw-loader": "^0.5.1",
    "react": "^16.0.0",
    "react-datepicker": "^0.64.0",
    "react-dom": "^16.0.0",
    "react-expand-collapse": "^0.2.0",
    "react-horizontal-timeline": "^1.4.0",
    "sass-loader": "^6.0.6",
    "semantic-ui-icon": "^2.2.12",
    "semantic-ui-react": "^0.73.0",
    "sqlite": "^2.9.0",
    "sqlite3": "^3.1.13",
    "superagent": "^3.4.0",
    "tls": "0.0.1",
    "universal-cookie": "^2.1.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/node": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "babel-core": "^7.0.0-bridge",
    "babel-plugin-inline-react-svg": "^0.4.0",
    "babel-plugin-module-resolver": "^2.7.1",
    "now": "^8.3.10"
  }
}
```

**Comment by philmetzger** [comment]
ah the module resolver needs version 3.1.1
