### ISSUE TITLE
@babel/plugin-register error with @babel/plugin-syntax-import-meta

### ISSUE THREAD

**Issue by BananaAcid** [babel/babel#9299]
## Bug Report

**Current Behavior**
Getting an error, register alone did work, but adding @babel/plugin-syntax-import-meta, it triggers an error about "'@babel/plugin-register'" even thought the modules name is "@babel/register".

reference [@babel/register](https://babeljs.io/docs/en/babel-register)

**Input Code**
index.js
version 1
```js
require('@babel/register');
require("@babel/core").transform("code", {
  plugins: ["@babel/plugin-syntax-import-meta"]
});
```
index.js version 2
```js
//require('@babel/register');
require("@babel/core").transform("code", {
  plugins: ["@babel/plugin-syntax-import-meta", "@babel/register"]
});

require('./app.mjs');
```

app.mjs
```
if (!__dirname) var __dirname = path.resolve(path.dirname(decodeURI(url.parse(import.meta.url).pathname))); // fix node module -- fucks up babel
console.log(__dirname);
```

**Expected behavior/code**
parsing the target file with `import.meta.url`

**Babel Configuration (.babelrc)**

tried this as an alternative as well: 

```js
{
  "plugins": [
    "@babel/register",
    "@babel/plugin-syntax-import-meta"
  ]
}
```

**Environment**
    "@babel/core": "^7.2.2",
    "@babel/plugin-syntax-import-meta": "^7.2.0",
    "@babel/register": "^7.0.0"

- Node/npm version: Node v11.6.0, npm 6.5.0-next.0
- OS: Windows 10, Ubuntu
- Monorepo: ??
- How you are using Babel: register

**Additional context/Screenshots**
```
/mnt/___long-path___/mjs-babel-test/node_modules/@babel/core/lib/config/files/plugins.js:152
    throw e;
    ^

Error: Cannot find module '@babel/plugin-register' from '/mnt/___long-path___/mjs-babel-test'
- If you want to resolve "@babel/register", use "module:@babel/register"
    at Function.module.exports [as sync] (/mnt/___long-path___/mjs-babel-test/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/mnt/___long-path___/mjs-babel-test/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/mnt/___long-path___/mjs-babel-test/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/mnt/___long-path___/mjs-babel-test/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/mnt/___long-path___/mjs-babel-test/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/mnt/___long-path___/mjs-babel-test/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/mnt/___long-path___/mjs-babel-test/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/mnt/___long-path___/mjs-babel-test/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/mnt/___long-path___/mjs-babel-test/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
```

**Comment by nicolo-ribaudo** [comment]
`@babel/register` isn't a babel plugin. You should use it like this:

```js
require("@babel/register")({
  plugins: ["@babel/plugin-syntax-import-meta"]
});
```

**Comment by BananaAcid** [comment]
So to get the app.mjs file working with imports, I found "transform-es2015-modules-commonjs". 
This gets me a step further, but @babel/plugin-syntax-import-meta does still not work.

index.js
```
require('@babel/register')({
  plugins: ['@babel/plugin-syntax-import-meta', 'transform-es2015-modules-commonjs']
});
require('./app'); //app.mjs
```

app.mjs
```
if (!__dirname) {
    const im = import.meta.url;
    var __dirname = path.resolve(path.dirname(decodeURI(url.parse(im.url).pathname))); // fix node module -- fucks up babel
}
```

But this added, will result in:
```
/mnt/__long-path__/server.mjs:51
  const im = import.meta.url;
                    ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Module._compile (/mnt/__long-path__/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.newLoader [as .mjs] (/mnt/__long-path__/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Comment by BananaAcid** [comment]
Resolved using the node module `esm` which does work flawlessly, as well as  `node --experimental-modules`. So code is proven to be correct and it is a miss behavior of the babel modules.

**Comment by nicolo-ribaudo** [comment]
The `syntax` plugin allows Babel to parse `import.meta`, but it is left as-is: it's up to node to understand it. If you want to transform it, you'll need another plugin (that we don't offically provide because the spec doesn't say what should there be inside that object).
