### ISSUE TITLE
Latest version of @babel/parser fails on typescript async syntax

### ISSUE THREAD

**Issue by ifiokjr** [babel/babel#9455]
## Bug Report

**Current Behavior**

When running the build with `@babel/parser@7.3.2` the following error is received.

```bash
{ SyntaxError: /path/to/project/code/src/utils.ts: Unexpected token, expected ";" (143:36)

  141 |  * @param coll
  142 |  */
> 143 | export const getDocument = async <T extends {}>(
      |                                     ^
  144 |   documentId: string,
  145 |   coll: string,
  146 | ): Promise<FirestoreRecord<T>> => {
    at Object.raise (/path/to/project/node_modules/@babel/parser/lib/index.js:3831:17)
    at Object.unexpected (/path/to/project/node_modules/@babel/parser/lib/index.js:5143:16)
    at Object.semicolon (/path/to/project/node_modules/@babel/parser/lib/index.js:5131:40)
    at Object.parseVarStatement (/path/to/project/node_modules/@babel/parser/lib/index.js:7712:10)
    at Object.parseStatementContent (/path/to/project/node_modules/@babel/parser/lib/index.js:7307:21)
    at Object.parseStatementContent (/path/to/project/node_modules/@babel/parser/lib/index.js:10113:18)
    at Object.parseStatement (/path/to/project/node_modules/@babel/parser/lib/index.js:7248:17)
    at Object.parseExportDeclaration (/path/to/project/node_modules/@babel/parser/lib/index.js:8414:17)
    at Object.parseExportDeclaration (/path/to/project/node_modules/@babel/parser/lib/index.js:10232:27)
    at Object.maybeParseExportDeclaration (/path/to/project/node_modules/@babel/parser/lib/index.js:8363:31)
  pos: 4169,
  loc: Position { line: 143, column: 36 },
  code: 'BABEL_PARSE_ERROR' }
error Command failed with exit code 1.
ERROR: "build:babel" exited with 1.
error Command failed with exit code 1.
```

Once I downgrade using yarn resolutions in my top level package.json things work well.

```json5
{
  //...
  "resolutions": {
    //...
    "@babel/parser": "7.3.1"
  }
}
```

**Input Code**

```ts
/**
 * Retrieve any document from any firestore collection.
 *
 * @param documentId
 * @param coll
 */
export const getDocument = async <T extends {}>(
  documentId: string,
  coll: string,
): Promise<FirestoreRecord<T>> => {
  const doc = admin
    .firestore()
    .collection(coll)
    .doc(documentId);
  const snap = await doc.get();
  const data = snap.exists ? (snap.data() as T) : undefined;
  return { doc, snap, data };
};
```

**Expected behavior/code**

It should compile correcly. When using `v7.3.1` this works great.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: '8',
        },
      },
    ],
  ],
  plugins: [
    '@babel/plugin-transform-typescript', // Needed instead of preset otherwise abstract classes don't compile correctly
    'lodash',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-transform-arrow-functions',
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
  ],
};
```

**Environment**
- Babel version(s): `@babel/parser@7.3.2`

```json5
{
    //...
    "@babel/plugin-proposal-class-properties": "7.3.0",
    "@babel/plugin-proposal-decorators": "7.3.0",
    "@babel/plugin-proposal-object-rest-spread": "7.3.1",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/plugin-transform-runtime": "7.2.0",
    "@babel/preset-env": "7.3.1",
    "@babel/preset-typescript": "7.1.0",
    "@babel/plugin-syntax-jsx": "7.2.0"
}
```

- Node/npm version: Node 8 - 11
- OS: macOS 10.14.2
- Monorepo: Lerna and Workspaces
- How you are using Babel: `cli`

**Comment by danez** [comment]
Thank you for reporting this. 
Unfortunately we are not able to reproduce your problem with the provided information. It might be that the code snippet is not enough to reproduce this problem.

Would you be able to share the whole file? Or create repository where we can reproduce the problem?

**Comment by ifiokjr** [comment]
@danez Thanks for getting back so quick.  

I'll put something together soon. Maybe it's just the set of plugins I'm using.

**Comment by ifiokjr** [comment]
@danez it seems it's a bug that's pretty much fixed itself. I must have been updating the `@babel/parser@7.3.2` really soon after it's release when the complementary (and required) `@babel/plugin-syntax-typescript@7.3.2` hadn't fully propagated. 

However, I do have an example of what caused the error, in case you're curious. 

If you checkout this commit https://github.com/ifiokjr/schemafire/tree/5d79b3e61a76459d83be22361bad0c159b2d50a2 it fails with the error I describe above. 

After checking out the repo run

```bash
yarn --frozen-lockfile
yarn build
```

This will fail. 

Then run

```bash
rm yarn.lock # delete the lockfile
yarn
```

Now everything should work. I'm assuming that not all the updated babel plugins had been picked up by yarn at the time I made the initial commit. 

Lesson learned. 

Some things just need time.
