### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by hadnet** [babel/babel#9476]
## Bug Report

**Current Behavior**
```js
 var origFn = descriptor.value.bind(target);
                          ^

TypeError: Cannot read property 'value' of undefined
    at time (/Users/oigoinc/Desktop/NewFoxBitApp/dist/index.js:397:27)
    at Object.decorateElement (/Users/oigoinc/Desktop/NewFoxBitApp/dist/index.js:47:2835)
    at Object.<anonymous> (/Users/oigoinc/Desktop/NewFoxBitApp/dist/index.js:47:1691)
    at Array.forEach (<anonymous>)
    at Object.decorateClass (/Users/oigoinc/Desktop/NewFoxBitApp/dist/index.js:47:1564)
    at _decorate (/Users/oigoinc/Desktop/NewFoxBitApp/dist/index.js:45:308)
    at Object.<anonymous> (/Users/oigoinc/Desktop/NewFoxBitApp/dist/index.js:412:11)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
```

**Code**

```js
function time (target, key, descriptor) {
    const origFn = target::descriptor.value;
    
    descriptor.value = function (...args) {
      
      console.log('args: ', args);
        console.time(key);
      let value = origFn(...args);
      console.timeEnd(key);
        return value;
    } 
  }
  
  class Fns {
    constructor(){
      var data = {name: ''}
    }
    
    @time
    squareAll(arry){
      return arry.map(x => x**x);
    }
    get name(){
      return this.data.name;
    }
    set myData(name) {
      this.data.name = name; 
    }
  }
  
  let fns = new Fns();
  console.log(fns.squareAll(Array(10).fill(3)));

```

**Note**
If I use the legacy option:

["@babel/plugin-proposal-decorators", { "legacy": true }],
["@babel/plugin-proposal-private-methods", { "loose" : true }],
["@babel/plugin-proposal-class-properties", { "loose" : true }],

works perfectly.

**Babel Configuration: .babelrc**

```js
{
    "presets": [
        ["@babel/preset-env", { "useBuiltIns": "usage" }]
    ],
    "plugins": [
        "@babel/plugin-proposal-decorators",
        ["@babel/plugin-proposal-private-methods",
        ["@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-function-bind",
        "@babel/plugin-proposal-async-generator-functions",
        "@babel/plugin-transform-async-to-generator"
    ]
}
```

**Environment**
- Babel version(s): v7.2.3
- Node/npm version: Node 11.8.0/npm 6.5.0
- OS: OSX 10.13.6
- How you are using Babel: `cli`

**Comment by nicolo-ribaudo** [comment]
If you wan't to use modern (non-legacy) decorators, you have to rewrite the `time` function.
You can read about some changes at https://babeljs.io/blog/2018/09/17/decorators, but I suggest taking a look at the decorators proposal.
