### ISSUE TITLE
Compile out   webpack v4.29.3  cli v3.2.0

### ISSUE THREAD

**Issue by Dusty-88** [babel/babel#9484]
PS F:\项目库\dome> yarn run dev
yarn run v1.9.4
$ webpack --config webpack.config.js
F:\项目库\dome\node_modules\webpack-cli\bin\cli.js:231
                                throw err;
                                ^

Error: custom keyword definition is invalid: data/errors should be boolean
    at Ajv.addKeyword (F:\项目库\dome\node_modules\ajv\lib\keyword.js:65:13)
    at module.exports (F:\项目库\dome\node_modules\ajv-errors\index.js:10:7)
    at Object.<anonymous> (F:\项目库\dome\node_modules\schema-utils\src\validateOptions.js:22:1)
    at Module._compile (F:\项目库\dome\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (F:\项目库\dome\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (F:\项目库\dome\node_modules\schema-utils\src\index.js:7:25)
    at Module._compile (F:\项目库\dome\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (F:\项目库\dome\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (F:\项目库\dome\node_modules\webpack\lib\SourceMapDevToolPlugin.js:13:25)
    at Module._compile (F:\项目库\dome\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (F:\项目库\dome\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (F:\项目库\dome\node_modules\webpack\lib\WebpackOptionsApply.js:16:32)
    at Module._compile (F:\项目库\dome\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by existentialism** [comment]
@Dusty-88 thanks for the issue report, but this is due to: https://github.com/webpack/webpack/issues/8768, and not Babel-related!
