### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined (While processing preset ...)

### ISSUE THREAD

**Issue by PavelKastornyy** [babel/babel#9495]
This is my project structure:

```
script4j
|
|-modules
|   |-script4j.base  
|   |-script4jfx.base	
|   |-script4jfx.graphics
```
Module `script4jfx.base` depends on one module - `script4j.base` and here everything is OK. Module `script4jfx.graphics` depends on two modules - `script4j.base` and `script4jfx.base` and here I have a problem, at the same time if I leave only one module dependency everything is OK.

This is a piece of `script4jfx.graphics` [package.json](https://github.com/PavelKastornyy/script4j/blob/master/modules/script4jfx.graphics/package.json)

```
    "devDependencies": {
        "gulp": "4.0.0",
        "gulp-mocha": "6.0.0",
        "babel-core": "6.26.3",
        "babel-register": "6.26.0",
        "babel-preset-env": "1.7.0",
        "babel-preset-stage-0": "6.24.1",
        "chai": "4.2.0",
        "mocha": "5.2.0",
        "script4j.base": "file:./../script4j.base",
        "script4jfx.base": "file:./../script4jfx.base"
    },
    "dependencies": {
        "script4j.base": "file:./../script4j.base",
        "script4jfx.base": "file:./../script4jfx.base"
   }
```
And here is what I get when try to run tests of `script4jfx.graphics`:

```
[18:31:10] Requiring external module babel-register
[18:31:10] Failed to load external module @babel/register
[18:31:11] Using gulpfile ~/script4j/modules/script4jfx.graphics/gulpfile.babel.js
[18:31:11] Starting 'test-module'...
/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^
TypeError: Cannot read property 'filter' of undefined (While processing preset: "/home/Pavel/script4j/modules/script4jfx.base/node_modules/babel-preset-env/lib/index.js")
    at normalize (/home/Pavel/script4j/modules/script4jfx.base/node_modules/browserslist/index.js:12:19)
    at /home/Pavel/script4j/modules/script4jfx.base/node_modules/browserslist/index.js:737:17
    at Object.<anonymous> (/home/Pavel/script4j/modules/script4jfx.base/node_modules/browserslist/index.js:756:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/Pavel/script4j/modules/script4jfx.base/node_modules/babel-preset-env/lib/targets-parser.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/Pavel/script4j/modules/script4jfx.base/node_modules/babel-preset-env/lib/index.js:33:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:296:17
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-register/lib/node.js:103:45)
    at loader (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/Pavel/script4j/modules/script4jfx.graphics/tmp/script4jfx.graphics.spec.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/Pavel/script4j/modules/script4jfx.graphics/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/Pavel/script4j/modules/script4jfx.graphics/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
[18:31:23] 'test-module' errored after 12 s
[18:31:23] Error in plugin "gulp-mocha"
Message:
    There were test failures
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

Please, any ideas what it is and  how to fix it.

**Comment by nicolo-ribaudo** [comment]
With #9518 I get the following output, please check if it works when that PR will be released:

```js
script4j/modules/script4jfx.graphics on  master [!?] is 📦 v0.1.0 via ⬢ v10.14.2 
➜ npm run test-module

> script4jfx.graphics@0.1.0 test-module /home/nicolo/Documenti/dev/script4j/modules/script4jfx.graphics
> gulp test-module --experimental-modules

Point XXX
[16:53:10] Using gulpfile ~/Documenti/dev/script4j/modules/script4jfx.graphics/gulpfile.js
[16:53:10] Starting 'test-module'...
Point XXX


  NodeTest
ArrayList { ArrayListIterator: [Function: _class], array: [] }
test
    ✓ test


  1 passing (9ms)

[16:53:14] Finished 'test-module' after 3.92 s

```

**Comment by PavelKastornyy** [comment]
@nicolo-ribaudo Do you mean when next babel 6 is released? I thought that babel 6 is not supported any more.

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/9518
