### ISSUE TITLE
Cannot find @babel/highlight in docker container.

### ISSUE THREAD

**Issue by schade-l** [babel/babel#9507]
## Bug Report
I'm trying to deploy a React SPA within a docker container, served through a python Flask app.

I'm starting here by asking people on Babel, because I think it might be something to do with the way I've set up babel, but I guess it could just as easily be an issue with Parcel or something else.

**Current Behavior**
When using `parcel build` to bundle an app, I get the following error:
```
🚨  Cannot find module '@babel/highlight'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _highlight (/node_modules/@babel/code-frame/lib/index.js:10:40)
    at codeFrameColumns (/node_modules/@babel/code-frame/lib/index.js:98:21)
    at JSAsset.generateErrorMessage (/node_modules/parcel-bundler/src/assets/JSAsset.js:277:23)
    at Bundler.throwDepError (/node_modules/parcel-bundler/src/Bundler.js:521:19)
error Command failed with exit code 1.
```

**Input Code**
The relevant parts of my dockerfile are as follows:

```docker
FROM python:3.6.8

RUN apt-get update
RUN apt-get install -y apt-transport-https apt-utils

RUN alias node=nodejs \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee \
    /etc/apt/sources.list.d/yarn.list \
    && curl -sL https://deb.nodesource.com/setup_11.x | bash - \
    && apt-get update \
    && apt-get install -y  nodejs yarn

RUN yarn global add parcel-bundler

COPY requirements.txt /
RUN pip install -r requirements.txt

COPY .babelrc /
COPY package.json /
COPY yarn.lock /


COPY test/ /test/
COPY app/ /app/

COPY client/ /client/

RUN yarn install && yarn list | grep @babel && yarn run parcel build client/*.html

EXPOSE 5000:5000

CMD ["python", "-um", "app.main"]
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
  "name": "app",
  "version": "1.0.0",
  "main": "client/index.js",
  "dependencies": {
    "adal-angular": "^1.0.17",
    "axios": "^0.18.0",
    "azure-storage": "^2.10.2",
    "bloomer": "^0.6.5",
    "eslint-config-google": "^0.11.0",
    "global": "^4.3.2",
    "lodash": "^4.17.11",
    "node": "^11.6.0",
    "node-sass": "^4.10.0",
    "parcel-bundler": "^1.10.3",
    "prop-types": "^15.6.2",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-table": "^6.8.6",
    "reactjs-popup": "^1.3.2",
    "request": "^2.34",
    "request-promise-native": "^1.0.5",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@babel/highlight": "^7.0.0",
    "babel-code-frame": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "bulma": "^0.7.2",
    "eslint": "^5.12.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.12.3",
    "prettier": "^1.15.3",
    "sass": "^1.15.3"
  },
  "scripts": {
    "start": "parcel client/*.html -p 3000",
    "build": "parcel build client/*.html"
  }
}

```

**Environment**
- Babel version(s):
- Node/npm version: Node 11.9 (same issue on node 10.11)/Yarn 1.13
- OS: Running in a docker container in Ubuntu
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Comment by nicolo-ribaudo** [comment]
What does that `yarn list | grep @babel` print? And `ls /node_modules/@babel`?

**Comment by schade-l** [comment]
**`yarn list | grep @babel`**:
```
├─ @babel/code-frame@7.0.0
│  └─ @babel/highlight@^7.0.0
├─ @babel/core@7.2.2
│  ├─ @babel/code-frame@^7.0.0
│  ├─ @babel/generator@^7.2.2
│  ├─ @babel/helpers@^7.2.0
│  ├─ @babel/parser@^7.2.2
│  ├─ @babel/template@^7.2.2
│  ├─ @babel/traverse@^7.2.2
│  ├─ @babel/types@^7.2.2
├─ @babel/generator@7.3.2
│  ├─ @babel/types@^7.3.2
├─ @babel/helper-annotate-as-pure@7.0.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-builder-binary-assignment-operator-visitor@7.1.0
│  ├─ @babel/helper-explode-assignable-expression@^7.1.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-builder-react-jsx@7.3.0
│  ├─ @babel/types@^7.3.0
├─ @babel/helper-call-delegate@7.1.0
│  ├─ @babel/helper-hoist-variables@^7.0.0
│  ├─ @babel/traverse@^7.1.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-define-map@7.1.0
│  ├─ @babel/helper-function-name@^7.1.0
│  ├─ @babel/types@^7.0.0
├─ @babel/helper-explode-assignable-expression@7.1.0
│  ├─ @babel/traverse@^7.1.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-function-name@7.1.0
│  ├─ @babel/helper-get-function-arity@^7.0.0
│  ├─ @babel/template@^7.1.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-get-function-arity@7.0.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-hoist-variables@7.0.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-member-expression-to-functions@7.0.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-module-imports@7.0.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-module-transforms@7.2.2
│  ├─ @babel/helper-module-imports@^7.0.0
│  ├─ @babel/helper-simple-access@^7.1.0
│  ├─ @babel/helper-split-export-declaration@^7.0.0
│  ├─ @babel/template@^7.2.2
│  ├─ @babel/types@^7.2.2
├─ @babel/helper-optimise-call-expression@7.0.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-plugin-utils@7.0.0
├─ @babel/helper-regex@7.0.0
├─ @babel/helper-remap-async-to-generator@7.1.0
│  ├─ @babel/helper-annotate-as-pure@^7.0.0
│  ├─ @babel/helper-wrap-function@^7.1.0
│  ├─ @babel/template@^7.1.0
│  ├─ @babel/traverse@^7.1.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-replace-supers@7.2.3
│  ├─ @babel/helper-member-expression-to-functions@^7.0.0
│  ├─ @babel/helper-optimise-call-expression@^7.0.0
│  ├─ @babel/traverse@^7.2.3
│  └─ @babel/types@^7.0.0
├─ @babel/helper-simple-access@7.1.0
│  ├─ @babel/template@^7.1.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-split-export-declaration@7.0.0
│  └─ @babel/types@^7.0.0
├─ @babel/helper-wrap-function@7.2.0
│  ├─ @babel/helper-function-name@^7.1.0
│  ├─ @babel/template@^7.1.0
│  ├─ @babel/traverse@^7.1.0
│  └─ @babel/types@^7.2.0
├─ @babel/helpers@7.3.1
│  ├─ @babel/template@^7.1.2
│  ├─ @babel/traverse@^7.1.5
│  └─ @babel/types@^7.3.0
├─ @babel/highlight@7.0.0
├─ @babel/parser@7.3.2
├─ @babel/plugin-proposal-async-generator-functions@7.2.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  ├─ @babel/helper-remap-async-to-generator@^7.1.0
│  └─ @babel/plugin-syntax-async-generators@^7.2.0
├─ @babel/plugin-proposal-json-strings@7.2.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  └─ @babel/plugin-syntax-json-strings@^7.2.0
├─ @babel/plugin-proposal-object-rest-spread@7.3.2
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  └─ @babel/plugin-syntax-object-rest-spread@^7.2.0
├─ @babel/plugin-proposal-optional-catch-binding@7.2.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  └─ @babel/plugin-syntax-optional-catch-binding@^7.2.0
├─ @babel/plugin-proposal-unicode-property-regex@7.2.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  ├─ @babel/helper-regex@^7.0.0
├─ @babel/plugin-syntax-async-generators@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-syntax-flow@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-syntax-json-strings@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-syntax-jsx@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-syntax-object-rest-spread@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-syntax-optional-catch-binding@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-arrow-functions@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-async-to-generator@7.2.0
│  ├─ @babel/helper-module-imports@^7.0.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  └─ @babel/helper-remap-async-to-generator@^7.1.0
├─ @babel/plugin-transform-block-scoped-functions@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-block-scoping@7.2.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-classes@7.2.2
│  ├─ @babel/helper-annotate-as-pure@^7.0.0
│  ├─ @babel/helper-define-map@^7.1.0
│  ├─ @babel/helper-function-name@^7.1.0
│  ├─ @babel/helper-optimise-call-expression@^7.0.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  ├─ @babel/helper-replace-supers@^7.1.0
│  ├─ @babel/helper-split-export-declaration@^7.0.0
├─ @babel/plugin-transform-computed-properties@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-destructuring@7.3.2
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-dotall-regex@7.2.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  ├─ @babel/helper-regex@^7.0.0
├─ @babel/plugin-transform-duplicate-keys@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-exponentiation-operator@7.2.0
│  ├─ @babel/helper-builder-binary-assignment-operator-visitor@^7.1.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-flow-strip-types@7.2.3
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  └─ @babel/plugin-syntax-flow@^7.2.0
├─ @babel/plugin-transform-for-of@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-function-name@7.2.0
│  ├─ @babel/helper-function-name@^7.1.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-literals@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-modules-amd@7.2.0
│  ├─ @babel/helper-module-transforms@^7.1.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-modules-commonjs@7.2.0
│  ├─ @babel/helper-module-transforms@^7.1.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  └─ @babel/helper-simple-access@^7.1.0
├─ @babel/plugin-transform-modules-systemjs@7.2.0
│  ├─ @babel/helper-hoist-variables@^7.0.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-modules-umd@7.2.0
│  ├─ @babel/helper-module-transforms@^7.1.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-named-capturing-groups-regex@7.3.0
├─ @babel/plugin-transform-new-target@7.0.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-object-super@7.2.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  └─ @babel/helper-replace-supers@^7.1.0
├─ @babel/plugin-transform-parameters@7.2.0
│  ├─ @babel/helper-call-delegate@^7.1.0
│  ├─ @babel/helper-get-function-arity@^7.0.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-react-jsx@7.3.0
│  ├─ @babel/helper-builder-react-jsx@^7.3.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  └─ @babel/plugin-syntax-jsx@^7.2.0
├─ @babel/plugin-transform-regenerator@7.0.0
├─ @babel/plugin-transform-shorthand-properties@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-spread@7.2.2
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-sticky-regex@7.2.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  └─ @babel/helper-regex@^7.0.0
├─ @babel/plugin-transform-template-literals@7.2.0
│  ├─ @babel/helper-annotate-as-pure@^7.0.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-typeof-symbol@7.2.0
│  └─ @babel/helper-plugin-utils@^7.0.0
├─ @babel/plugin-transform-unicode-regex@7.2.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  ├─ @babel/helper-regex@^7.0.0
├─ @babel/preset-env@7.3.1
│  ├─ @babel/helper-module-imports@^7.0.0
│  ├─ @babel/helper-plugin-utils@^7.0.0
│  ├─ @babel/plugin-proposal-async-generator-functions@^7.2.0
│  ├─ @babel/plugin-proposal-json-strings@^7.2.0
│  ├─ @babel/plugin-proposal-object-rest-spread@^7.3.1
│  ├─ @babel/plugin-proposal-optional-catch-binding@^7.2.0
│  ├─ @babel/plugin-proposal-unicode-property-regex@^7.2.0
│  ├─ @babel/plugin-syntax-async-generators@^7.2.0
│  ├─ @babel/plugin-syntax-json-strings@^7.2.0
│  ├─ @babel/plugin-syntax-object-rest-spread@^7.2.0
│  ├─ @babel/plugin-syntax-optional-catch-binding@^7.2.0
│  ├─ @babel/plugin-transform-arrow-functions@^7.2.0
│  ├─ @babel/plugin-transform-async-to-generator@^7.2.0
│  ├─ @babel/plugin-transform-block-scoped-functions@^7.2.0
│  ├─ @babel/plugin-transform-block-scoping@^7.2.0
│  ├─ @babel/plugin-transform-classes@^7.2.0
│  ├─ @babel/plugin-transform-computed-properties@^7.2.0
│  ├─ @babel/plugin-transform-destructuring@^7.2.0
│  ├─ @babel/plugin-transform-dotall-regex@^7.2.0
│  ├─ @babel/plugin-transform-duplicate-keys@^7.2.0
│  ├─ @babel/plugin-transform-exponentiation-operator@^7.2.0
│  ├─ @babel/plugin-transform-for-of@^7.2.0
│  ├─ @babel/plugin-transform-function-name@^7.2.0
│  ├─ @babel/plugin-transform-literals@^7.2.0
│  ├─ @babel/plugin-transform-modules-amd@^7.2.0
│  ├─ @babel/plugin-transform-modules-commonjs@^7.2.0
│  ├─ @babel/plugin-transform-modules-systemjs@^7.2.0
│  ├─ @babel/plugin-transform-modules-umd@^7.2.0
│  ├─ @babel/plugin-transform-named-capturing-groups-regex@^7.3.0
│  ├─ @babel/plugin-transform-new-target@^7.0.0
│  ├─ @babel/plugin-transform-object-super@^7.2.0
│  ├─ @babel/plugin-transform-parameters@^7.2.0
│  ├─ @babel/plugin-transform-regenerator@^7.0.0
│  ├─ @babel/plugin-transform-shorthand-properties@^7.2.0
│  ├─ @babel/plugin-transform-spread@^7.2.0
│  ├─ @babel/plugin-transform-sticky-regex@^7.2.0
│  ├─ @babel/plugin-transform-template-literals@^7.2.0
│  ├─ @babel/plugin-transform-typeof-symbol@^7.2.0
│  ├─ @babel/plugin-transform-unicode-regex@^7.2.0
├─ @babel/runtime@7.3.1
├─ @babel/template@7.2.2
│  ├─ @babel/code-frame@^7.0.0
│  ├─ @babel/parser@^7.2.2
│  └─ @babel/types@^7.2.2
├─ @babel/traverse@7.2.3
│  ├─ @babel/code-frame@^7.0.0
│  ├─ @babel/generator@^7.2.2
│  ├─ @babel/helper-function-name@^7.1.0
│  ├─ @babel/helper-split-export-declaration@^7.0.0
│  ├─ @babel/parser@^7.2.3
│  ├─ @babel/types@^7.2.2
├─ @babel/types@7.3.2
│  ├─ @babel/code-frame@^7.0.0
│  ├─ @babel/parser@^7.0.0
│  ├─ @babel/traverse@^7.0.0
│  ├─ @babel/types@^7.0.0
│  ├─ @babel/code-frame@^7.0.0
│  ├─ @babel/code-frame@^7.0.0
│  ├─ @babel/core@^7.0.0
│  ├─ @babel/generator@^7.0.0
│  ├─ @babel/parser@^7.0.0
│  ├─ @babel/plugin-transform-flow-strip-types@^7.0.0
│  ├─ @babel/plugin-transform-modules-commonjs@^7.0.0
│  ├─ @babel/plugin-transform-react-jsx@^7.0.0
│  ├─ @babel/preset-env@^7.0.0
│  ├─ @babel/runtime@^7.0.0
│  ├─ @babel/template@^7.0.0
│  ├─ @babel/traverse@^7.0.0
│  ├─ @babel/types@^7.0.0
```

**`ls /node_modules/@babel`**:

```
code-frame
core
generator
helper-annotate-as-pure
helper-builder-binary-assignment-operator-visitor
helper-builder-react-jsx
helper-call-delegate
helper-define-map
helper-explode-assignable-expression
helper-function-name
helper-get-function-arity
helper-hoist-variables
helper-member-expression-to-functions
helper-module-imports
helper-module-transforms
helper-optimise-call-expression
helper-plugin-utils
helper-regex
helper-remap-async-to-generator
helper-replace-supers
helper-simple-access
helper-split-export-declaration
helper-wrap-function
helpers
highlight
parser
plugin-proposal-async-generator-functions
plugin-proposal-json-strings
plugin-proposal-object-rest-spread
plugin-proposal-optional-catch-binding
plugin-proposal-unicode-property-regex
plugin-syntax-async-generators
plugin-syntax-flow
plugin-syntax-json-strings
plugin-syntax-jsx
plugin-syntax-object-rest-spread
plugin-syntax-optional-catch-binding
plugin-transform-arrow-functions
plugin-transform-async-to-generator
plugin-transform-block-scoped-functions
plugin-transform-block-scoping
plugin-transform-classes
plugin-transform-computed-properties
plugin-transform-destructuring
plugin-transform-dotall-regex
plugin-transform-duplicate-keys
plugin-transform-exponentiation-operator
plugin-transform-flow-strip-types
plugin-transform-for-of
plugin-transform-function-name
plugin-transform-literals
plugin-transform-modules-amd
plugin-transform-modules-commonjs
plugin-transform-modules-systemjs
plugin-transform-modules-umd
plugin-transform-named-capturing-groups-regex
plugin-transform-new-target
plugin-transform-object-super
plugin-transform-parameters
plugin-transform-react-jsx
plugin-transform-regenerator
plugin-transform-shorthand-properties
plugin-transform-spread
plugin-transform-sticky-regex
plugin-transform-template-literals
plugin-transform-typeof-symbol
plugin-transform-unicode-regex
preset-env
runtime
template
traverse
types
```

**Comment by nicolo-ribaudo** [comment]
Ok, `@babel/highlight` is there. It might be a bug with the `v8-compile-cache` (which is a dependency of Parcel) or with Parcel itself.

**Comment by schade-l** [comment]
Do you think I should try downgrading parcel? If so is there a version you recommend?

**Comment by schade-l** [comment]
The solution to this was really odd, but I had to change the directory the commands were working to not be root. This made `node_modules` `/app_dir/node_modules` and then resolved the issues.
