### ISSUE TITLE
@babel/register version bump not released to npm

### ISSUE THREAD

**Issue by jaylaw81** [babel/babel#9512]
## Bug Report

**Current Behavior**
babel-core dependencies are not loading 7.0.0-0

**Input Code**
https://github.com/babel/babel/tree/master/packages/babel-register

Error:

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

-- Call Stack

error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users//Sites/emblemhealth-fe/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/Sites/-fe/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/Sites/emblemhealth-fe/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:29:7)
    at /Users/Sites/emblemhealth-fe/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/Sites/emblemhealth-fe/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/Sites/emblemhealth-fe/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/Sites/emblemhealth-fe/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/Sites/emblemhealth-fe/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/Sites/emblemhealth-fe/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/Sites/emblemhealth-fe/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/Sites/emblemhealth-fe/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/Sites/emblemhealth-fe/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Sites/emblemhealth-fe/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /Users/Sites/emblemhealth-fe/node_modules/jasmine/lib/jasmine.js:93:5
    at Array.forEach (<anonymous>)
    at Jasmine.loadSpecs (/Users/Sites/emblemhealth-fe/node_modules/jasmine/lib/jasmine.js:92:18)
    at Jasmine.execute (/Users/Sites/emblemhealth-fe/node_modules/jasmine/lib/jasmine.js:197:8)
    at runJasmine (/Users/Sites/emblemhealth-fe/node_modules/jasmine/lib/command.js:125:11)
    at Command.run (/Users/Sites/emblemhealth-fe/node_modules/jasmine/lib/command.js:55:9)

**Environment**

- Node/npm version: [e.g. Node 8/npm 6]
- OS: [e.g. OSX]
- How you are using Babel: [`register`]

**Possible Solution**
Publish latest repo to NPM

**Comment by loganfsmyth** [comment]
Your stack trace shows that you are using `babel-register` which is the Babel 6 package, hence the error. The Babel 7 package is called `@babel/register`.
