### ISSUE TITLE
@babel/plugin-transform-runtime get @babel/runtime module path error when set webpack context

### ISSUE THREAD

**Issue by LoeiFy** [babel/babel#9526]
## Bug Report

**Current Behavior**

when set webpack `context` not `process.cwd()`, it throw error:

```bash
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/defineProperty' in 
'/private/var/folders/7t/f477lrkn39lbh_f0ks4w6ghw0000gn/T/FALCO' 
/private/var/folders/7t/f477lrkn39lbh_f0ks4w6ghw0000gn/T/FALCO/js0.js
```

**Input Code**

webpack config:

```js
{
  // ...
  context: resolve(__dirname, '../../'),
  module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: [
                [require.resolve('@babel/preset-env'), { modules: false, useBuiltIns: 'usage' }],
                require.resolve('@babel/preset-react'),
              ],
              plugins: [
                [require.resolve('@babel/plugin-proposal-decorators'), { legacy: true }],
                require.resolve('@babel/plugin-proposal-class-properties'),
                [require.resolve('@babel/plugin-transform-runtime'), {
                  regenerator: false,
                  useESModules: true,
                }],
              ],
            },
          },
        }
     ],
  },
}
```

**Environment**
- Babel: 7.2.0
- webpack: 4.28.4

**Possible Solution**

i find this can fix the error

```js
// ...
              plugins: [
                [require.resolve('@babel/plugin-proposal-decorators'), { legacy: true }],
                require.resolve('@babel/plugin-proposal-class-properties'),
                [require.resolve('@babel/plugin-transform-runtime'), {
                  regenerator: false,
                  useESModules: true,
                  
                  // Add this line
                  absoluteRuntime: resolve(__dirname, '../../node_modules/@babel/runtime'),
                }],
              ],
// ...
```

and i think the error cause by this
https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js#L123-L135

**Comment by nicolo-ribaudo** [comment]
1. What is the full stack trace of that error?
2. What is your package.json?
1. If you disable the `transform-runtime` plugin and manually add `import defineProperty from "@babel/runtime/helpers/esm/defineProperty"` in your code, does it throw the same error?

**Comment by LoeiFy** [comment]
@nicolo-ribaudo 

1. full error:

```bash
ERROR /private/var/folders/7t/f477lrkn39lbh_f0ks4w6ghw0000gn/T/FALCO/js0.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/defineProperty' in '/private/var/folders/7t/f477lrkn39lbh_f0ks4w6ghw0000gn/T/FALCO' /private/var/folders/7t/f477lrkn39lbh_f0ks4w6ghw0000gn/T/FALCO/js0.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/objectWithoutProperties' in '/private/var/folders/7t/f477lrkn39lbh_f0ks4w6ghw0000gn/T/FALCO'
Error: webpack build error
    at watcher (/Users/am0200/Documents/github/falco/lib/compiler/webpack.js:34:14)
    at finalCallback (/Users/am0200/Documents/github/falco/node_modules/webpack/lib/Compiler.js:214:39)
    at hooks.done.callAsync.err (/Users/am0200/Documents/github/falco/node_modules/webpack/lib/Compiler.js:230:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/am0200/Documents/github/falco/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/am0200/Documents/github/falco/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/am0200/Documents/github/falco/node_modules/webpack/lib/Compiler.js:228:21)
    at hooks.afterCompile.callAsync.err (/Users/am0200/Documents/github/falco/node_modules/webpack/lib/Compiler.js:556:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/am0200/Documents/github/falco/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/am0200/Documents/github/falco/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/am0200/Documents/github/falco/node_modules/webpack/lib/Compiler.js:553:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/am0200/Documents/github/falco/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/am0200/Documents/github/falco/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/am0200/Documents/github/falco/node_modules/webpack/lib/Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/am0200/Documents/github/falco/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/am0200/Documents/github/falco/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/am0200/Documents/github/falco/node_modules/webpack/lib/Compilation.js:1314:32)
```

2. package.json:

```json
{
  "dependencies": {
    "@acyort/logger": "^1.1.1",
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/plugin-proposal-decorators": "^7.3.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.3.3",
    "@babel/runtime": "^7.3.1",
    "@vue/babel-helper-vue-jsx-merge-props": "^1.0.0-beta.2",
    "@vue/babel-preset-jsx": "^1.0.0-beta.2",
    "babel-loader": "^8.0.5",
    "css-loader": "^2.1.0",
    "directory-tree": "^2.2.1",
    "fs-extra": "^7.0.1",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "minimist": "^1.2.0",
    "style-loader": "^0.23.1",
    "terser-webpack-plugin": "^1.2.2",
    "vue-loader": "^15.6.2",
    "vue-template-compiler": "^2.6.4",
    "webpack": "^4.28.4",
    "webpack-dev-server": "^3.1.14"
  }
}
```

3. > If you disable the `transform-runtime` plugin and manually add `import defineProperty from "@babel/runtime/helpers/esm/defineProperty"` in your code, does it throw the same error?

it works, no errors

**Comment by nicolo-ribaudo** [comment]
Looking at your stack traces I don't understand how your project is structured.
Are you running webpack from `/Users/am0200/Documents/github/falco/lib/compiler/` but compiling files from `/private/var/folders/7t/f477lrkn39lbh_f0ks4w6ghw0000gn/T/FALCO`? In which of those two folders is `@babel/runtime` installed?

**Comment by LoeiFy** [comment]
@nicolo-ribaudo i use webpack and webpack-dev-server as a node module for `JavaScript Transcoder`

you can see this [repo](https://github.com/fratercula/falco)

**Comment by nicolo-ribaudo** [comment]
What command do I have to run to reproduce the bug?

**Comment by LoeiFy** [comment]
delete this line: https://github.com/fratercula/falco/blob/master/lib/compiler/config.js#L81

then run `npm t`, and you can see the errors

**Comment by nicolo-ribaudo** [comment]
You need to install `@babel/runtime` in the `example` "package": when it is copied to the temp folder, it doesn't have access to the build tool's `node_modules` folder anymore. `@babel/runtime` is a dependency of the built package, not of the build tool.

I see that you have some logic to install used dependencies. You must either collect used dependencies _after_ running Babel (but before running webpack; you'd need to use two separate steps), or hardcode dependencies that will be inserted by a Babel plugin.

**Comment by LoeiFy** [comment]
@nicolo-ribaudo as i said before, i use webpack as a node module for "JavaScript Transcoder", and user can use webpack widthout configuration or install package like `@babel/xxxx` etc.

all the required packages are installed in `resolve(__dirname, '../../node_modules')`, includes `@babel/runtime`. 

besause of has change webpack `context`, the `babel-loader`'s ` presets` and `plugins` modules all be required  in specific ways `require.resolve('@babel/xxxx')`, and working, except `@babel/plugin-transform-runtime`.

i think the errors cause by this https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js#L123-L135, `@babel/plugin-transform-runtime` get the error path of `@babel/runtime` besause the it not check the current context path

**Comment by LoeiFy** [comment]
@nicolo-ribaudo 

Pull requests [#32](https://github.com/babel/website/pull/1912/files) solved my problem, thanks
