### ISSUE TITLE
transform-spread + typescript builds Flow annotation instead of TypeScript

### ISSUE THREAD

**Issue by azz** [babel/babel#9530]
## Bug Report

**Current Behavior**

```
TypeError: Property types[0] of UnionTypeAnnotation expected node to be of a type ["FlowType"] but instead got "TSTypeAnnotation"
    at validate (/work/node_modules/@babel/types/lib/definitions/utils.js:128:13)
    at validator (/work/node_modules/@babel/types/lib/definitions/utils.js:97:7)
    at Object.validate (/work/node_modules/@babel/types/lib/definitions/utils.js:172:7)
    at validate (/work/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/work/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at UnionTypeAnnotation (/work/node_modules/@babel/types/lib/builders/generated/index.js:733:31)
    at Object.createUnionTypeAnnotation (/work/node_modules/@babel/types/lib/builders/flow/createUnionTypeAnnotation.js:20:47)
    at NodePath.ConditionalExpression (/work/node_modules/@babel/traverse/lib/path/inference/inferers.js:124:14)
    at NodePath._getTypeAnnotation (/work/node_modules/@babel/traverse/lib/path/inference/index.js:63:20)
    at NodePath.getTypeAnnotation (/work/node_modules/@babel/traverse/lib/path/inference/index.js:29:19)
```

**Input Code**

https://github.com/azz/babel-typescript-union-bug

```ts
function bug() {
  const x = 1 ? a() : b();

  return [...x];
}

function a(): number[] {
  return [];
}

function b(): number[] {
  return [];
}
```

**Expected behavior/code**

_Not like this_

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": ["@babel/plugin-transform-spread"],
  "presets": ["@babel/preset-typescript"]
}
```

**Environment**
- Babel version(s): 7.3.3
- Node/npm version: 6.5.0
- OS: macOS 10.14.2
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

The builder code for `plugin-transform-spread` is expecting a `UnionTypeAnnotation` instead of a `TSUnionType` in order to determine the type of `x` above, specifically in `scope.toArray`:

https://github.com/babel/babel/blob/5bb1bb080f2cb1ff942c940bdb9595a70e6f4706/packages/babel-traverse/src/scope/index.js#L408-L413

`isGenericType` ends up calling `createUnionTypeAnnotation`:

https://github.com/babel/babel/blob/5bb1bb080f2cb1ff942c940bdb9595a70e6f4706/packages/babel-traverse/src/path/inference/inferers.js#L92-L97

Which creates a `UnionTypeAnnotation`, which works for Flow, but not TypeScript.

**Comment by bentekkie** [comment]
Is there a work around for this?

**Comment by azz** [comment]
The workaround is a bit hacky but change this:
```js
function bug() {
  const x = 1 ? a() : b();
  return [...x];
}
```

into this:

```js
function bug() {
  let x;
  x = 1 ? a() : b();

  return [...x];
}
```

**Comment by sebastiandedeyne** [comment]
I temporarily solved this by using a `concat` call instead of the spread operator.

From:

```js
return [...listItems, ...newListItems];
```

To:

```js
return listItems.concat(newListItems);
```

**Comment by SaeedZhiany** [comment]
Hey @sebastiandedeyne @azz, I need a real quick assistance please,
What is the error message says? I don't understand it at all. I change one of my files and suddenly got this error, even I revert all the changes but still get the error
If it's important, I upgrade npm version from 6.9.2 to 6.10.2 too.

![Screenshot_1565169101](https://user-images.githubusercontent.com/13766432/62610536-1f2eea00-b919-11e9-8e80-60f747381b76.png)

my file **before changes**

```
import { StyleProp, StyleSheet, TextStyle, ViewStyle } from 'react-native';

enum ButtonColor {
  BLUE = 'BLUE',
  RED = 'RED',
  GREEN = 'GREEN',
  GRAY = 'GRAY',
  MORE_TABS = 'MORE_TABS',
  LIGHTGRAY = 'LIGHTGRAY',
  WHITE = 'WHITE',
}

export default ButtonColor;

const styles = StyleSheet.create({
  disabled: {
    backgroundColor: '#E7E7E7',
  },
  disabledGray: {
    backgroundColor: '#e2e6e9',
    borderWidth: 1,
    borderColor: '#b3b3b3',
  },
  disabledGrayText: {
    color: '#999999',
  },
  disabledLightGray: {
    backgroundColor: '#fcfcfc',
  },
  disabledWhite: {
    borderWidth: 1,
    borderColor: '#b3b3b3',
  },
  disabledWhiteText: {
    color: '#000000',
  },
  notDisabled: {
    backgroundColor: '#ffffff',
  },
  red: {
    backgroundColor: '#f74949',
  },
  blue: {
    backgroundColor: '#2f71dc',
  },
  green: {
    backgroundColor: '#43c08f',
    borderWidth: 1,
    borderColor: '#18a16a',
  },
  moreTabs: {
    backgroundColor: '#ececec',
  },
  lightGray: {
    backgroundColor: '#ededed',
  },
  gray: {
    backgroundColor: '#f8f8f8',
    borderWidth: 1,
    borderColor: '#c7c7c7',
  },
  grayText: {
    color: '#000000',
  },
  white: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#c3c3c3',
  },
  whiteText: {
    color: '#000000',
  },
  font: {
    fontSize: 15,
    color: '#ffffff',
  },
});

export function buttonStyle(style: StyleProp<ViewStyle>,
                            disabled: boolean,
                            buttonColor: ButtonColor): StyleProp<ViewStyle>[] {
  let curStyle;
  if (disabled) {
    switch (buttonColor) {
      case ButtonColor.GRAY:
        curStyle = styles.disabledGray;
        break;
      case ButtonColor.LIGHTGRAY:
        curStyle = styles.disabledLightGray;
        break;
      case ButtonColor.WHITE:
        curStyle = styles.disabledWhite;
        break;
      case ButtonColor.RED:
      case ButtonColor.BLUE:
      case ButtonColor.GREEN:
      case ButtonColor.MORE_TABS:
        break;
      default:
        break;
    }
    return [style, styles.disabled, curStyle];
  } else {
    switch (buttonColor) {
      case ButtonColor.RED:
        curStyle = styles.red;
        break;
      case ButtonColor.BLUE:
        curStyle = styles.blue;
        break;
      case ButtonColor.GREEN:
        curStyle = styles.green;
        break;
      case ButtonColor.MORE_TABS:
        curStyle = styles.moreTabs;
        break;
      case ButtonColor.LIGHTGRAY:
        curStyle = styles.lightGray;
        break;
      case ButtonColor.GRAY:
        curStyle = styles.gray;
        break;
      case ButtonColor.WHITE:
        curStyle = styles.white;
        break;
      default:
        break;
    }
    return [style, styles.notDisabled, curStyle];
  }
}

export function textStyle(disabled: boolean, buttonColor: ButtonColor): StyleProp<TextStyle> {
  let curStyle;
  if (disabled) {
    switch (buttonColor) {
      case ButtonColor.GRAY:
        curStyle = styles.disabledGrayText;
        break;
      case ButtonColor.WHITE:
        curStyle = styles.disabledWhiteText;
        break;
      case ButtonColor.LIGHTGRAY:
      case ButtonColor.RED:
      case ButtonColor.BLUE:
      case ButtonColor.GREEN:
      case ButtonColor.MORE_TABS:
        break;
      default:
        break;
    }
    return [styles.font, curStyle];
  } else {
    switch (buttonColor) {
      case ButtonColor.GRAY:
        curStyle = styles.grayText;
        break;
      case ButtonColor.WHITE:
        curStyle = styles.whiteText;
        break;
      case ButtonColor.RED:
      case ButtonColor.BLUE:
      case ButtonColor.GREEN:
      case ButtonColor.MORE_TABS:
      case ButtonColor.LIGHTGRAY:
        break;
      default:
        break;
    }
    return [styles.font, curStyle];
  }
}
```

my file **after changes**

```
import { StyleProp, StyleSheet, TextStyle, ViewStyle } from 'react-native';

enum ButtonColor {
  BLUE = 'BLUE',
  RED = 'RED',
  GREEN = 'GREEN',
  GRAY = 'GRAY',
  LIGHTGRAY = 'LIGHTGRAY',
  WHITE = 'WHITE',
  ORANGE = 'ORANGE',
  WHITE_GREEN = 'WHITE_GREEN',
}

export default ButtonColor;

const styles = StyleSheet.create({
  disabled: {
    backgroundColor: '#E7E7E7',
  },
  enabled: {
    backgroundColor: '#ffffff',
  },
  disabledBLUE: {},
  disabledRED: {},
  disabledGREEN: {},
  disabledGRAY: {
    backgroundColor: '#e2e6e9',
    borderWidth: 1,
    borderColor: '#b3b3b3',
  },
  disabledLIGHTGRAY: {
    backgroundColor: '#fcfcfc',
  },
  disabledWHITE: {
    borderWidth: 1,
    borderColor: '#b3b3b3',
  },
  disabledORANGE: {},
  disabledWHITE_GREEN: {},
  BLUE: {
    backgroundColor: '#2f71dc',
  },
  RED: {
    backgroundColor: '#f74949',
  },
  GREEN: {
    backgroundColor: '#43c08f',
    borderWidth: 1,
    borderColor: '#18a16a',
  },
  GRAY: {
    backgroundColor: '#f8f8f8',
    borderWidth: 1,
    borderColor: '#c7c7c7',
  },
  LIGHTGRAY: {
    backgroundColor: '#ededed',
  },
  WHITE: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#c3c3c3',
  },
  ORANGE: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#c3c3c3',
  },
  WHITE_GREEN: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#c3c3c3',
  },
  disabledBLUEText: {},
  disabledREDText: {},
  disabledGREENText: {},
  disabledGRAYText: {
    color: '#999999',
  },
  disabledLIGHTGRAYText: {},
  disabledWHITEText: {
    color: '#000000',
  },
  disabledORANGEText: {},
  disabledWHITE_GREENText: {},
  BLUEText: {},
  REDText: {},
  GREENText: {},
  GRAYText: {
    color: '#000000',
  },
  LIGHTGRAYText: {},
  WHITEText: {
    color: '#000000',
  },
  ORANGEText: {},
  WHITE_GREENText: {},
  font: {
    fontFamily: 'moein',
    fontSize: 15,
    color: '#ffffff',
  },
});

export function buttonStyle(style: StyleProp<ViewStyle>,
                            disabled: boolean,
                            buttonColor: ButtonColor): StyleProp<ViewStyle>[] {
  let curStyle;
  curStyle = disabled ? disabledButtonStyle(buttonColor) : enabledButtonStyle(buttonColor);
  return [style, ...curStyle];
}

function disabledButtonStyle(buttonColor: ButtonColor): StyleProp<ViewStyle>[] {
  const styleKey = `disabled${buttonColor}`;
  let curStyle;
  curStyle = styles[styleKey] ? styles[styleKey] : {};
  return [styles.disabled, curStyle];
}

function enabledButtonStyle(buttonColor: ButtonColor): StyleProp<ViewStyle>[] {
  let curStyle;
  curStyle = styles[buttonColor] ? styles[buttonColor] : {};
  return [styles.enabled, curStyle];
}

export function textStyle(disabled: boolean, buttonColor: ButtonColor): StyleProp<TextStyle> {
  return disabled ? disabledTextStyle(buttonColor) : enabledTextStyle(buttonColor);
}

function disabledTextStyle(buttonColor: ButtonColor): StyleProp<TextStyle> {
  const styleKey = `disabled${buttonColor}Text`;
  let curStyle;
  curStyle = styles[styleKey] ? styles[styleKey] : {};
  return [styles.font, curStyle];
}

function enabledTextStyle(buttonColor: ButtonColor): StyleProp<TextStyle> {
  const styleKey = `${buttonColor}Text`;
  let curStyle;
  curStyle = styles[styleKey] ? styles[styleKey] : {};
  return [styles.font, curStyle];
}
```

**Comment by JLHwung** [comment]
Thank you @azz for offering a solution. I will add some detailed descriptions about the solution.

Background: In `plugin-transform-spread` we will check if an AST node is an array expression and applied array-type helper transforms. To determine if a node is an array expression, we will infer its type annotation in various ways according to different AST node types. This function is an inferrer of ConditionExpression node.

https://github.com/babel/babel/blob/5bb1bb080f2cb1ff942c940bdb9595a70e6f4706/packages/babel-traverse/src/path/inference/inferers.js#L92-L97

The problems is that `t.createUnionTypeAnnotation` accepts only `FlowType`, but in the example above, it can also be a TSTypeAnnotation. You can check whether a type annotation is of `TSTypeAnnotation` by `t.isTSTypeAnnotation(node)`.

When a type annotation is `TSTypeAnnotation`, we should not use `t.createUnionTypeAnnotation` anymore. Instead we can create a TypeScript alternative of `createUnionTypeAnnotation` in `babel-types/src/builders/typescript/createTSUnionType.js`. Similar to `createUnionTypeAnnotation`
https://github.com/babel/babel/blob/5bb1bb080f2cb1ff942c940bdb9595a70e6f4706/packages/babel-types/src/builders/flow/createUnionTypeAnnotation.js#L9-L19

`createTSUnionType` should check duplicate types and return a `TSUnionType` node on multiple types.

It will be even greater if you can check the other inferrers in this file to see if they need similar treatments.

### contribution guide

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js` and `options.json`; `output.js` will be automatically generated) in 
`packages/babel-traverse/test/fixtures/type-reference`
and
`packages/babel-types/test/builders/typescript`
1. Update the code!
1. `yarn jest babel-traverse` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

**Comment by liamfd** [comment]
If this is available, I'm happy to take a look at it.

**Comment by JLHwung** [comment]
@liamfd Just assigned this issue to you. Feel free to ask on slack #development channel should you have any questions.

**Comment by Beraliv** [comment]
@JLHwung @liamfd if this is NOT in progress, could I have a chance to do it?

**Comment by kaicataldo** [comment]
As long as there isn't an open PR for it, I think it's been long enough that it's fair game.

**Comment by liamfd** [comment]
@Beraliv hey, please go for it if you would like to. Sorry, it fell off of my radar.
