### ISSUE TITLE
__objectWithoutPropertiesLoose problem with jest

### ISSUE THREAD

**Issue by WebDeg-Brian** [babel/babel#9543]
## Bug Report

**Current Behavior**
When using a babel-transpiled module with Jest, this error comes up:
```
D:\Study Documents\Computer Science\cky-website\node_modules\react-spring\renderprops.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _objectWithoutPropertiesLoose from '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      3 | import styled from 'styled-components';
      4 | import { InputBase } from '@material-ui/core';
    > 5 | import { Spring, animated } from 'react-spring/renderprops';
        | ^
      6 | import { createSlideAndFadeAnim } from '@cky-website/animation-helpers';
      7 | 
      8 | const AnimatedSearchWrapper = animated(styled.div`

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)
      at Object.<anonymous> (packages/client/src/components/Header/SearchInput.js:5:1)
      at Object.<anonymous> (packages/client/src/components/Header/Header.js:13:1)
```
The code works fine on the browser, no errors are to be found

**Input Code**
The code file where Jest points to:
```
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';
import { InputBase } from '@material-ui/core';
import { Spring, animated } from 'react-spring/renderprops';
import { createSlideAndFadeAnim } from '@cky-website/animation-helpers';

const AnimatedSearchWrapper = animated(styled.div`
  position: absolute;
  z-index: 0;
  left: 0;
  width: 100%;
  height: 100%;
`);

const StyledSearchInput = styled(({ open, ...others }) => <InputBase {...others} />)`
  width: 100%;
  height: 100%;
  && {
    color: inherit;
  }
`;

const searchInputAnimationBase = createSlideAndFadeAnim('x', 'in', false);

const Search = ({ onChange, open, value }) => (
  <Spring
    native
    from={searchInputAnimationBase.from}
    to={open ? searchInputAnimationBase.to : searchInputAnimationBase.from}
  >
    {style => (
      <AnimatedSearchWrapper>
        <StyledSearchInput
          placeholder="Search CKY - eSports..."
          onChange={onChange}
          value={value}
          open={open}
          style={style}
        />
      </AnimatedSearchWrapper>
    )}
  </Spring>
);

Search.propTypes = {
  // The function that gets invoked when the search input value is changed
  onChange: PropTypes.func.isRequired,

  // The prop that tells whether the search is opened
  open: PropTypes.bool.isRequired,

  // The value of the search input
  value: PropTypes.string.isRequired,
};

export default Search;
```
However, I don't think this piece of code matters too much.

**Expected behavior/code**
Jest shouldn't prompt the issue and continue to execute the tests.

**Babel Configuration (.babelrc, package.json, cli command)**
```
module.exports = {
  presets: ['@babel/preset-env', '@babel/preset-react'],
  plugins: [
    '@babel/plugin-transform-runtime',
    '@babel/plugin-proposal-class-properties',
    [
      'babel-plugin-styled-components',
      {
        displayName: true,
      },
    ],
  ],
  babelrcRoots: ['.', './packages/*'],
};
```

**Environment**
- Tech stack: Lerna with yarn workspace, babel, webpack and plain react (no Next.js/Gatsby or CRA)
- Babel version(s): core 7.2.2, preset-env 7.3.1, preset-react 7.0.0, runtime 7.3.1
- Node/npm version: Node 8.11.3, npm 5.6.0
- OS: Windows 10
- Monorepo: yes (Lerna and Yarn workspace)
- How you are using Babel: loader with webpack

**Possible Solution**
No idea 😕

**Comment by nicolo-ribaudo** [comment]
You need to tell jest not to exclude that node module: https://jestjs.io/docs/en/configuration#transformignorepatterns-array-string

**Comment by WebDeg-Brian** [comment]
@nicolo-ribaudo Okay, I will give it a try 👍

**Comment by WebDeg-Brian** [comment]
@nicolo-ribaudo I added this to my jest config:

`transformIgnorePatterns: ['<rootDir>/node_modules/(?!(react-spring)/)'],`

and now this happens:

```
D:\Study Documents\Computer Science\cky-website\node_modules\@babel\runtime\helpers\esm\objectWithoutPropertiesLoose.js:1    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export default function _objectWithoutPropertiesLoose(source, excluded) {
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      3 | import styled from 'styled-components';
      4 | import { InputBase } from '@material-ui/core';
    > 5 | import { Spring, animated } from 'react-spring/renderprops';
        | ^
      6 | import { createSlideAndFadeAnim } from '@cky-website/animation-helpers';
      7 | 
      8 | const AnimatedSearchWrapper = animated(styled.div`

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)
      at Object.<anonymous> (node_modules/react-spring/renderprops.js:1:1)
      at Object.<anonymous> (packages/client/src/components/Header/SearchInput.js:5:1)
```

**Comment by nicolo-ribaudo** [comment]
Could you try using `renderprops.cjs.js` instead of `renderprops.js`? That libraries depends on the es-modules version of `@babel/runtime`, which needs to be used with webpack or rollup.

**Comment by WebDeg-Brian** [comment]
@nicolo-ribaudo Sorry for the late reply. Yes that was the culprit. I figured out that I need to map the CJS file instead of the ESM one. Thank you and closing the issue now
