### ISSUE TITLE
Reentrant plugin detected

### ISSUE THREAD

**Issue by gergelyke** [babel/babel#9548]
## Bug Report

**Current Behavior**

After updating to jest@24, I get the following error from babel/core:

```
Error: Reentrant plugin detected trying to load "/Users/gnemeth/Development/baseui/babel/cup.js". This module is not ignored and is trying to load itself while compiling itself, leading to a dependency cycle. We recommend adding it to your "ignore" list in your babelrc, or to a .babelignore.
    at requireModule (/Users/gnemeth/Development/baseui/node_modules/@babel/core/lib/config/files/plugins.js:160:11)
    at loadPlugin (/Users/gnemeth/Development/baseui/node_modules/@babel/core/lib/config/files/plugins.js:68:17)
    at createDescriptor (/Users/gnemeth/Development/baseui/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Users/gnemeth/Development/baseui/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/gnemeth/Development/baseui/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/gnemeth/Development/baseui/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/Users/gnemeth/Development/baseui/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
    at mergeChainOpts (/Users/gnemeth/Development/baseui/node_modules/@babel/core/lib/config/config-chain.js:314:26)
    at /Users/gnemeth/Development/baseui/node_modules/@babel/core/lib/config/config-chain.js:278:7
```

**Input Code**

A link to the PR can be found here: 

https://github.com/uber-web/baseui/pull/792

**Environment**
- Babel version(s): 7
- Node/npm version: Node 8 and yarn 1.12.3
- OS: OSX

**Comment by loganfsmyth** [comment]
The error message tries to explain, but it could probably be clearer.

> We recommend adding it to your "ignore" list in your babelrc, or to a .babelignore.

So you should add

```
ignore: [
  './babel/cup.js'
]
```
in your Babel config so that Babel knows not to compile your own plugin with itself.

**Comment by gergelyke** [comment]
thanks! that plus adding the regenarator transform solved the issue
