### ISSUE TITLE
ReferenceError with `for..of`

### ISSUE THREAD

**Issue by aeosynth** [babel/babel#955]
```js
if (true)
  true
else
  for (let x of y);
```

```
$ babel cardgen.js 
/usr/local/lib/node_modules/babel/lib/babel/helpers/parse.js:54
    throw err;
          ^
ReferenceError: cardgen.js: unknown node of type undefined with constructor "Array"
    at CodeGenerator.print (/usr/local/lib/node_modules/babel/lib/babel/generation/index.js:221:13)
    at print (/usr/local/lib/node_modules/babel/lib/babel/generation/index.js:113:20)
    at CodeGenerator.printAndIndentOnComments (/usr/local/lib/node_modules/babel/lib/babel/generation/index.js:260:5)
    at Function.print.indentOnComments (/usr/local/lib/node_modules/babel/lib/babel/generation/index.js:140:20)
    at CodeGenerator.IfStatement (/usr/local/lib/node_modules/babel/lib/babel/generation/generators/statements.js:45:11)
    at CodeGenerator.print (/usr/local/lib/node_modules/babel/lib/babel/generation/index.js:206:22)
    at print (/usr/local/lib/node_modules/babel/lib/babel/generation/index.js:113:20)
    at /usr/local/lib/node_modules/babel/lib/babel/generation/index.js:239:7
    at arrayEach (/usr/local/lib/node_modules/babel/node_modules/lodash/internal/arrayEach.js:15:9)
    at forEach (/usr/local/lib/node_modules/babel/node_modules/lodash/collection/forEach.js:38:7)
```

works fine if the `for` 'loop' is in the `if` branch, if braces are added, or if the `else` branch is a standard `for` loop: `for (let i;;);`

edit: also works in loose mode

**Comment by sebmck** [comment]
Fixed as of 4.7.0, thanks!
