### ISSUE TITLE
Clean install gives error: "Error: Cannot find module 'babel-plugin-transform-runtime'"

### ISSUE THREAD

**Issue by TheDutchCoder** [babel/babel#9555]
## Bug Report

**Current Behavior**
When installing `npm install -D babel-loader @babel/core @babel/preset-env webpack` and adjusting the webpack config as described:

```
const path = require('path')

module.exports = {
  entry: './src/js-framework/src/cart/cart.js',
  output: {
    path: path.resolve(__dirname, './public/static/bundles')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      }
    ]
  },
  resolve: {
    alias: {
      '@js-framework': path.resolve(__dirname, './src/js-framework/src')
    }
  }
}

```

The following error is outputted when running webpack:
```
ERROR in ./src/js-framework/src/cart/cart.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-transform-runtime' from '/var/projects/canvaspop'
- Did you mean "@babel/transform-runtime"?
    at Function.module.exports [as sync] (/var/projects/canvaspop/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/var/projects/canvaspop/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/var/projects/canvaspop/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/var/projects/canvaspop/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/var/projects/canvaspop/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/var/projects/canvaspop/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/var/projects/canvaspop/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/var/projects/canvaspop/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/var/projects/canvaspop/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
    at mergeChainOpts (/var/projects/canvaspop/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /var/projects/canvaspop/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/var/projects/canvaspop/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/var/projects/canvaspop/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/var/projects/canvaspop/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/var/projects/canvaspop/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/projects/canvaspop/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/var/projects/canvaspop/node_modules/babel-loader/lib/index.js:5:194)
    at /var/projects/canvaspop/node_modules/babel-loader/lib/index.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/var/projects/canvaspop/node_modules/babel-loader/lib/index.js:5:97)
    at Object._loader (/var/projects/canvaspop/node_modules/babel-loader/lib/index.js:220:18)
    at Object.loader (/var/projects/canvaspop/node_modules/babel-loader/lib/index.js:56:18)
    at Object.<anonymous> (/var/projects/canvaspop/node_modules/babel-loader/lib/index.js:51:12)
```

```js
/**
 * cart.js
 *
 * Cart specific functionality.
 * Allows the user to change the quantity of line items or remove them.
 */
'use strict'

import { matches } from '@js-framework/utils'



/**
 * Handles changes in the quantity selector.
 *
 * @param {Object} event
 */
const handleQuantityChange = (event) => {
  const target = matches(event.target, '[name=qty]')

  if (target) {
    const form = matches(target, '.form')
    const id = form.querySelector('[name=id]').value

    // If the item is supposed to be removed, change the form's submission
    // target.
    if (target.value === 'remove' || parseInt(target.value, 10) === 0) {
      form.setAttribute('action', `/cart/remove/id/${id}`)
    }

    // Show the loader and submit the form.
    form.querySelector('.loader').classList.add('is-visible')
    form.submit()
  }
}



/**
 * Handles removing the product directly.
 *
 * @param {Object} event
 */
const handleRemoveProduct = (event) => {
  const target = matches(event.target, '.js-remove-product')

  if (target) {
    const form = matches(target, '.form')
    const id = form.querySelector('[name=id]').value

    form.setAttribute('action', `/cart/remove/id/${id}`)

    // Show the loader and submit the form.
    form.querySelector('.loader').classList.add('is-visible')
    form.submit()
  }
}



// Attach event listeners.
document.addEventListener('change', handleQuantityChange)
document.addEventListener('click', handleRemoveProduct)
```

**Expected behavior/code**
I expected the build to pass and my code to be transpiled by Babel.

**Babel Configuration (.babelrc, package.json, cli command)**
See above (webpack.config.js)

**Environment**
- Babel version(s): 7.3.3
- Node/npm version: 8.9.3
- OS: OSX 10.13.6
- Monorepo: no idea
- How you are using Babel: `loader`

**Comment by nicolo-ribaudo** [comment]
Is there any other babel config in your repo?

**Comment by TheDutchCoder** [comment]
Yup, that was it, thanks!

**Comment by hallieliu123** [comment]
I'm struggling with the same problem here. Can you explain how to resolve this ? Tks.

**Comment by hallieliu123** [comment]
I'm struggling with the same problem here. Can you explain how to solve this ? Tks.

**Comment by n00el** [comment]
Hello, I had the same issue!
I just deleted my **node_modules folder**, and the **package-lock.json**, then run **npm install**, and it solved my issue,

Hope it's working for you too!

**Comment by mcpengelly** [comment]
@n00el i dont think thats a solution, typically you wouldnt delete your lockfile and reinstall deps because then youre dependencies/subdeps are no longer "locked down". The fact that it works thought points to a version problem.
