### ISSUE TITLE
@babel/parser does not parse non-null members named 'readonly' in TypeScript

### ISSUE THREAD

**Issue by elevatebart** [babel/babel#9571]
## Bug Report

**Current Behavior**
When I use `@pabel/parser` with the following code:

```ts
class MyComp {
          readonly!: boolean;
}
```
I get `SyntaxError: Unexpected Token`

**Expected behavior/code**
I expect `readonly` to be the name of my property

**Babel Configuration (.babelrc, package.json, cli command)**

```js
import { parse } from '@babel/parser'
const src = 'code above'

parse(src, {
  sourceType: 'module',
  strictMode: false,
  tokens: true,
  plugins:['typescript', 'classProperties']
})
```

**Environment**
- Babel version(s): v7.3.3
- Node/npm version: Node 10/npm 6
- OS: OSX 10.13.4
- Monorepo: no
- How you are using Babel: none, I am using only the parser

**Additional context/Screenshots**
This was found investgating this bug.
https://github.com/vue-styleguidist/vue-styleguidist/issues/281

**Comment by elevatebart** [comment]
I forgot to add the call stack
```
at Object.raise (node_modules/@babel/parser/lib/index.js:3831:17)
      at Object.unexpected (node_modules/@babel/parser/lib/index.js:5143:16)
      at Object.parseIdentifierName (node_modules/@babel/parser/lib/index.js:6970:18)
      at Object.parseIdentifier (node_modules/@babel/parser/lib/index.js:6948:23)
      at Object.parseMaybePrivateName (node_modules/@babel/parser/lib/index.js:6312:19)
      at Object.parsePropertyName (node_modules/@babel/parser/lib/index.js:6768:98)
      at Object.parseClassPropertyName (node_modules/@babel/parser/lib/index.js:8173:22)
      at Object.parseClassMemberWithIsStatic (node_modules/@babel/parser/lib/index.js:10175:12)
      at Object.parseClassMember (node_modules/@babel/parser/lib/index.js:8067:10)
      at Object.parseClassMember (node_modules/@babel/parser/lib/index.js:10138:11)
      at withTopicForbiddingContext (node_modules/@babel/parser/lib/index.js:8022:14)
      at Object.withTopicForbiddingContext (node_modules/@babel/parser/lib/index.js:7150:14)
      at Object.parseClassBody (node_modules/@babel/parser/lib/index.js:7999:10)
      at Object.parseClass (node_modules/@babel/parser/lib/index.js:7973:10)
      at Object.parseExportDefaultExpression (node_modules/@babel/parser/lib/index.js:8394:19)
      at Object.parseExportDefaultExpression (node_modules/@babel/parser/lib/index.js:10113:18)
      at Object.parseExport (node_modules/@babel/parser/lib/index.js:8299:31)
      at Object.parseExport (node_modules/@babel/parser/lib/index.js:10091:20)
      at Object.parseStatementContent (node_modules/@babel/parser/lib/index.js:7347:27)
      at Object.parseStatementContent (node_modules/@babel/parser/lib/index.js:10128:18)
      at Object.parseStatement (node_modules/@babel/parser/lib/index.js:7243:17)
      at Object.parseBlockOrModuleBlockBody (node_modules/@babel/parser/lib/index.js:7810:25)
      at Object.parseBlockBody (node_modules/@babel/parser/lib/index.js:7797:10)
      at Object.parseTopLevel (node_modules/@babel/parser/lib/index.js:7181:10)
      at Object.parse (node_modules/@babel/parser/lib/index.js:8658:17)
      at Object.parse (node_modules/@babel/parser/lib/index.js:10658:38)
``` 
I hope it helps

**Comment by elevatebart** [comment]
I managed to track the bug back to this function `parseClassMemberWithIsStatic`
https://github.com/babel/babel/blob/2817844e895b8999b71ec89ba008180c07b2f66d/packages/babel-parser/src/plugins/typescript.js#L1730 
It parses out the modifier before having a token to modify.
Should I try preventing this in a PR ?

**Comment by elevatebart** [comment]
Actually, I would say that the bang should be added to this list
https://github.com/babel/babel/blob/2817844e895b8999b71ec89ba008180c07b2f66d/packages/babel-parser/src/plugins/typescript.js#L77-L91
