### ISSUE TITLE
Shadow parameter with lexical declaration

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel#9606]
## Bug Report

**Input Code**

```js
(sloppy mode)

function f(a) {
  let a;
}
```

**Current Behavior**
```
SyntaxError: unknown: Identifier 'a' has already been declared (3:6)

  1 | 
  2 | function f(a) {
> 3 |   let a;
    |       ^
  4 | }
  5 | 
    at Parser.raise (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/location.js:21:17)
    at ScopeHandler.declareName (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/util/scope.js:116:12)
    at Parser.checkLVal (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/lval.js:267:22)
    at Parser.parseVarId (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/statement.js:788:10)
    at Parser.parseVar (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/statement.js:759:12)
    at Parser.parseVarStatement (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/statement.js:584:10)
    at Parser.parseStatementContent (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/statement.js:180:21)
    at Parser.parseStatement (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/statement.js:113:17)
    at Parser.parseBlockOrModuleBlockBody (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/statement.js:690:25)
    at Parser.parseBlockBody (/home/nicolo/Documenti/dev/babel/babel/packages/babel-parser/lib/parser/statement.js:677:10)
```

**Expected behavior/code**
It is valid code.

**Environment**
- Babel version(s): master (9aec606c69b04a4617eb85242b9ffb7229d7379a)

**Comment by nicolo-ribaudo** [comment]
Also, chrome accepts this code but I'm not 100% sure about it. I think that the var is collapsed with the parameter and thus `let` is in an inner scope?

```js
function f(a) {
  var a;
  let a;
}
```

**Comment by nicolo-ribaudo** [comment]
It's a V8 bug. See https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-early-errors, 4th point.
