### ISSUE TITLE
SyntaxError: Missing initializer in const declaration (nodejs+typescript+babel)

### ISSUE THREAD

**Issue by jony89** [babel/babel#9608]
## Bug Report

**Current Behavior**

I am trying to use babel with typescript in nodejs environment with `.js` files.

I was following https://babeljs.io/docs/en/babel-preset-typescript

I am getting the following  `SyntaxError`  : 

> SyntaxError: Missing initializer in const declaration
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Input Code**
```js
require("@babel/core").transform("code", {
  presets: ["@babel/preset-typescript"],
});

const x: number = 0;
console.log(x);
```

**Expected behavior/code**

The code should be compiled by babel.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
require("@babel/core").transform("code", {
  presets: ["@babel/preset-typescript"],
});
```

**Environment**
- Babel version(s): 7
- Node/npm version: 8.15.0
- OS: Windows 7
- Monorepo: lerna
- How you are using Babel: `register`

**Comment by nicolo-ribaudo** [comment]
Are you actually transpiling `"code"`? What is the output?

**Comment by jony89** [comment]
I am expecting babel to transpile it during runtime, the same as I am doing with async class properties and regenerator.. 

working example

```js
require('core-js');
require('regenerator-runtime/runtime');
require('@babel/register')({
    presets: ['@babel/env', '@babel/react'],
    plugins: [
        '@babel/proposal-class-properties',
        '@babel/transform-async-to-generator',
        '@babel/proposal-object-rest-spread',
        'dynamic-import-node',
    ],
});
```

**Comment by nicolo-ribaudo** [comment]
Oh ok. Babel/core Is compile-time only; as you said you need to use `@babel/register`. And you need to place your typescript code not in the same file where you load Babel, but in a file that you can require after loading Babel.

**Comment by jony89** [comment]
Yup, I've tried that as well but still getting SyntaxError

file1: `serverInit.js`

```js
require('@babel/register')({
    presets: [
        '@babel/preset-typescript',
    ],
});

require('./server');
```

file2: `server.js` : 
```js
const x: number = 0;
console.log(x);
```

Getting : 

> SyntaxError: MY_PATH/server.js: Unexpected token (29:7)

←[0m ←[90m 27 | ←[39m}))←[33m;←[39m←[0m
←[0m ←[90m 28 | ←[39m←[0m
←[0m←[31m←[1m>←[22m←[39m←[90m 29 | ←[39m←[36mconst←[39m x←[33m:←[39m number ←[33m=←[39m ←[35m0←[39m←[33m;←[39m←[0m
←[0m ←[90m    | ←[39m       ←[31m←[1m^←[22m←[39m←[0m
←[0m ←[90m 30 | ←[39m←[0m
    at Parser.raise (MY_PATH/node_modules\@babel\parser\lib\index.js:3831:17)
    at Parser.unexpected (MY_PATH/node_modules\@babel\parser\lib\index.js:5143:16)
    at Parser.parseVar (MY_PATH/node_modules\@babel\parser\lib\index.js:7884:18)
    at Parser.parseVarStatement (MY_PATH/node_modules\@babel\parser\lib\index.js:7714:10)
    at Parser.parseStatementContent (MY_PATH/node_modules\@babel\parser\lib\index.js:7310:21)
    at Parser.parseStatement (MY_PATH/node_modules\@babel\parser\lib\index.js:7243:17)
    at Parser.parseBlockOrModuleBlockBody (MY_PATH/node_modules\@babel\parser\lib\index.js:7810:25)
    at Parser.parseBlockBody (MY_PATH/node_modules\@babel\parser\lib\index.js:7797:10)
    at Parser.parseTopLevel (MY_PATH/node_modules\@babel\parser\lib\index.js:7181:10)
    at Parser.parse (MY_PATH/node_modules\@babel\parser\lib\index.js:8660:17)

**Comment by nicolo-ribaudo** [comment]
It should be `server.ts`: the TypeScript preset only runs on typescript files.

**Comment by jony89** [comment]
same issue with `.ts`.

> const x: number = 0;
>       ^
> 
> SyntaxError: Missing initializer in const declaration
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:617:28)
>     at Module._extensions..js (module.js:664:10)
>     at Object.newLoader [as .js] (d:\mploy\app\chikichak-server\packages\billing\node_modules\pirates\lib\index.js:104:7)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)

but using `@babel/plugin-transform-typescript` with `.js` files actually works.

Thanks A lot !
