### ISSUE TITLE
Duplicate declaration

### ISSUE THREAD

**Issue by subhero24** [babel/babel#9611]
## 🐛 Bug Report

When running babel with preset-env on this code

```javascript
import x from './x';

export default function(x) {}
```

It errors with 'Duplicate declaration "x"'

I think this is valid code however, as node has no problem executing the file (with esm)

**Comment by mischnic** [comment]
Stack trace:
```
  1 | import x from './x';
  2 |
> 3 | export default function(x) {}
    |                         ^
    at File.buildCodeFrameError (.../@babel/core/lib/transformation/file/file.js:261:12)
    at Scope.checkBlockScopedCollisions (.../@babel/traverse/lib/scope/index.js:348:22)
    at Scope.registerBinding (.../@babel/traverse/lib/scope/index.js:505:16)
    at splitExportDeclaration (.../@babel/helper-split-export-declaration/lib/index.js:50:13)
    at programPath.get.forEach.child (.../@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:332:49)
    at Array.forEach (<anonymous>)
    at nameAnonymousExports (.../@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:330:27)
    at normalizeModuleAndLoadMetadata (.../@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:56:3)
    at rewriteModuleStatementsAndPrepareHeader (.../@babel/helper-module-transforms/lib/index.js:101:54)
    at PluginPass.exit (.../@babel/plugin-transform-modules-commonjs/lib/index.js:155:85)
```

**Comment by subhero24** [comment]
Thank you!
