### ISSUE TITLE
Error: EPERM: operation not permitted, mkdir

### ISSUE THREAD

**Issue by nmodi** [babel/babel#9630]
## Bug Report

**Current Behavior**
I get the following error when I run this npm script:    "build": "npm run clean && babel src --copy-files --out-dir dist"

```
{ Error: EPERM: operation not permitted, mkdir 'C:\Users\ME\codebase\myproject\myproject-project-rs\dist'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (C:\Users\ME\codebase\myproject\myproject-project-rs\node_modules\mkdirp\index.js:71:13)
    at C:\Users\ME\codebase\myproject\myproject-project-rs\node_modules\@babel\cli\lib\babel\dir.js:203:26
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\ME\codebase\myproject\myproject-project-rs\node_modules\@babel\cli\lib\babel\dir.js:74:103)
    at _next (C:\Users\ME\codebase\myproject\myproject-project-rs\node_modules\@babel\cli\lib\babel\dir.js:76:194)
    at C:\Users\ME\codebase\myproject\myproject-project-rs\node_modules\@babel\cli\lib\babel\dir.js:76:364
```

What's weird is that it runs correctly the first time after I start my IDE (vscode), but fails every subsequent time after I stop the server with ctrl+c in the terminal. 

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry"
      }
    ]
  ],
  "plugins": [
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "src": "./src"
      }
    }]
  ]
}
```

**Environment**
- Babel version(s): 
```
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-polyfill": "^6.26.0",
```
- Node/npm version: Node 8.11/npm 5.6
- OS: Windows 10
- Using babel-cli

**Comment by nmodi** [comment]
I believe this was an issue with VSCode actually. Closing this issue.
