### ISSUE TITLE
plugin syntax-jsx cannot parse arrow function to JSXIdentifier inside function

### ISSUE THREAD

**Issue by huozhi** [babel/babel#9638]
## Bug Report

**Current Behavior**
use babel  with `@babel/plugin-syntax-jsx` plugin to parse the following code snippet will lead to errors.

```
TypeError: Property name of JSXOpeningElement expected node to be of a type ["JSXIdentifier","JSXMemberExpression"] but instead got "ArrowFunctionExpression"
```

**Input Code**

snippet.js

```js
it("should support nested Profilers", () => {
  const FunctionComponent = ({ label }) => <div>{label}</div>;
  return <FunctionComponent label="outer function component" />
});
```

but if you remove the top `it` function it will be parsed.

**Expected behavior/code**
parse successfully without errors

**Babel Configuration (.babelrc, package.json, cli command)**

```js
./node_modules/.bin/babel --plugins @babel/plugin-syntax-jsx snippet.js
```

**Environment**
- Babel version(s): v7.3.4
- Node/npm version: [Node 11/npm 6]
- OS: [OSX 10.13.6]
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by danez** [comment]
Can you please post your complete babel config? 
This seems unrelated to the parser. The error is coming from `@babel/types` so I guess some of the react/jsx optimization plugins goes wild.

**Comment by huozhi** [comment]
here is my config
```js
module.exports = {
  plugins: [
    '@babel/plugin-syntax-jsx',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-transform-flow-strip-types',
    '@babel/plugin-syntax-class-properties',
    'babel-plugin-minify-dead-code-elimination',
  ]  
}
```

@danez looks like the error is caused by babel-plugin-minify-dead-code-elimination. if I removed it the error disappeared

```
TypeError: Property name of JSXOpeningElement expected node to be of a type ["JSXIdentifier","JSXMemberExpression"] but instead got "ArrowFunctionExpression"
    at Object.validate (node_modules/@babel/types/lib/definitions/utils.js:128:13)
    at Object.validate (node_modules/@babel/types/lib/validators/validate.js:17:9)
    at NodePath._replaceWith (node_modules/@babel/traverse/lib/path/replacement.js:194:9)
    at NodePath.replaceWith (node_modules/@babel/traverse/lib/path/replacement.js:178:8)
    at replace (node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:1200:10)
    at Object.enter (node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:499:32)
    at Object.newFn (node_modules/@babel/traverse/lib/visitors.js:230:17)
    at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
```

should I move the issue to babel/minify or I just leave it here?
