### ISSUE TITLE
Installing from git vs installing from local repo installs wrong Babel Version.

### ISSUE THREAD

**Issue by karltaylor** [babel/babel#9643]
## Bug Report

Apologies if this is wrong place. I am completely baffled as to why this is not working.

Basically: 
```bash
$ npm install path/to/ui-package
# post-install runs. Babel compiles
# If I add ui-package to package.json and install from gitlab
$ npm install
# Babel fails stating wrong babel version loaded.
# But it the exact same as the git repo as it is local.
```

**Current Behavior**

I have a main app, and `ui-package` app I am developing locally, but want to install from gitlab.

```bash
$ npm i --save /path/to/local/ui-package
# Works fine. Babel runs and compiles.
```

If i add the package to my `package.json` and reference it using gitlab:

```
ui-package: git@gitlab.com:project/ui-package.git
```

```
$ npm install
// Babel will fail
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/karl/code/workshop/backend/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/karl/code/workshop/backend/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/karl/code/workshop/backend/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:29:7)
    at /Users/karl/code/workshop/backend/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/karl/code/workshop/backend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/karl/code/workshop/backend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/karl/code/workshop/backend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/karl/code/workshop/backend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/karl/code/workshop/backend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/karl/code/workshop/backend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/karl/code/workshop/backend/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/karl/code/workshop/backend/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/karl/code/workshop/backend/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/Users/karl/code/workshop/backend/node_modules/babel-cli/lib/babel/util.js:50:22)
    at Object.compile (/Users/karl/code/workshop/backend/node_modules/babel-cli/lib/babel/util.js:59:12)
    at write (/Users/karl/code/workshop/backend/node_modules/babel-cli/lib/babel/dir.js:21:21)
    at handleFile (/Users/karl/code/workshop/backend/node_modules/babel-cli/lib/babel/dir.js:43:7)
    at /Users/karl/code/workshop/backend/node_modules/babel-cli/lib/babel/dir.js:61:9
    at Array.forEach (<anonymous>)
    at handle (/Users/karl/code/workshop/backend/node_modules/babel-cli/lib/babel/dir.js:59:29)
    at Array.forEach (<anonymous>)
    at module.exports (/Users/karl/code/workshop/backend/node_modules/babel-cli/lib/babel/dir.js:69:15)
    at Object.<anonymous> (/Users/karl/code/workshop/backend/node_modules/babel-cli/lib/babel/index.js:129:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

**Expected behavior/code**

Install locally and installing from gitlab to install the same.

**Babel Configuration (.babelrc, package.json, cli command)**

`ui-package/.babelrc`

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}

```

**Environment**
- Babel version(s): See `package.json` below.
- Node/npm version: Node v0.15.2 / npm 6.4.1]
- OS: 10.14.3
- Monorepo: no
- How you are using Babel: `loader`

**Additional context/Screenshots**

Main app `package.json`

```
  "resolutions": {
    "styled-components": "^4.1.3"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "babel-cli": "^6.26.0",
    "css-modulesify": "^0.28.0",
    "hls.js": "^0.8.9",
    "moment": "^2.20.1",
    "moment-duration-format": "^2.2.1",
    "prop-types": "^15.6.1",
    "qs": "^6.5.1",
    "react": "^16.8.3",
    "react-collapsible": "^2.6.0",
    "react-dom": "^16.8.3",
    "react-fontawesome": "^1.6.1",
    "react-loadable": "^5.3.1",
    "react-scrollspy": "^3.3.5",
    "react-select": "^1.2.1",
    "react-share": "^2.2.0",
    "react-sticky": "^6.0.1",
    "react-stripe-checkout": "^2.6.3",
    "react-stripe-elements": "^2.0.1",
    "react-transition-group": "^2.3.1",
    "redux": "^3.7.2",
    "smooth-scroll": "^12.1.5",
    "styled-components": "^4.1.3",
    "video-react": "^0.9.4",
    "workshop-ui": "file:../workshop-ui"
  },
  "devDependencies": {
    "@babel/core": "^7.3.4",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-syntax-throw-expressions": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.1.2",
    "babel-eslint": "^8.2.1",
    "babel-loader": "^8.0.5",
    "browser-sync": "^2.23.6",
    "browser-sync-webpack-plugin": "^2.0.7",
    "css-loader": "^0.28.10",
    "eslint": "^4.17.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-flowtype": "^2.44.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.6.1",
    "flow-bin": "^0.68.0",
    "lodash.assign": "^4.2.0",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.7",
    "style-loader": "^0.20.3",
    "stylus": "^0.54.5",
    "uglifyjs-webpack-plugin": "^1.2.2",
    "webpack": "^4.1.1",
    "webpack-bundle-analyzer": "^2.11.1",
    "webpack-cli": "^3.1.2"
  },
```

`ui-package/package.json`

```
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.4",
    "@babel/preset-env": "^7.3.4",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.3.4",
    "@storybook/addon-info": "^4.1.11",
    "@storybook/addon-knobs": "^4.1.6",
    "@storybook/addon-notes": "^4.1.6",
    "@storybook/react": "^4.1.6",
    "babel-eslint": "^10.0.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.12.4",
    "metro-react-native-babel-preset": "^0.52.0",
    "react": "^16.8.3",
    "react-dom": "^16.8.3",
    "styled-components": "^4.1.3",
    "eslint": "^5.14.1"
  }
```

**Comment by nicolo-ribaudo** [comment]
What does `npx nls why babel-core` print? For some reason there are conflicting Babel versions installed.

**Comment by danez** [comment]
you still have babel-cli in your dependencies. It should be `@babel/cli`

**Comment by karltaylor** [comment]
@danez thank you. Should of spotted this
