### ISSUE TITLE
when i created a project and then load sass ,then npm run serve ,it is error .

### ISSUE THREAD

**Issue by Ariaal** [babel/babel#9658]
## Bug Report
 ERROR  Failed to compile with 1 errors                                                                                                               10:26:53
 error  in ./src/main.js

Module build failed (from ./node_modules/_babel-loader@8.0.5@babel-loader/lib/index.js):
ReferenceError: Unknown option: .module. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
    at throwUnknownError (C:\Users\春夏\Desktop\sss\node_modules\_@babel_core@7.3.4@@babel\core\lib\config\validation\options.js:123:11)
    at Object.keys.forEach.key (C:\Users\春夏\Desktop\sss\node_modules\_@babel_core@7.3.4@@babel\core\lib\config\validation\options.js:107:5)
    at Array.forEach (<anonymous>)
    at validateNested (C:\Users\春夏\Desktop\sss\node_modules\_@babel_core@7.3.4@@babel\core\lib\config\validation\options.js:83:21)
    at validate (C:\Users\春夏\Desktop\sss\node_modules\_@babel_core@7.3.4@@babel\core\lib\config\validation\options.js:74:10)
    at file (C:\Users\春夏\Desktop\sss\node_modules\_@babel_core@7.3.4@@babel\core\lib\config\config-chain.js:169:34)
    at cachedFunction (C:\Users\春夏\Desktop\sss\node_modules\_@babel_core@7.3.4@@babel\core\lib\config\caching.js:33:19)
    at buildRootChain (C:\Users\春夏\Desktop\sss\node_modules\_@babel_core@7.3.4@@babel\core\lib\config\config-chain.js:89:27)
    at loadPrivatePartialConfig (C:\Users\春夏\Desktop\sss\node_modules\_@babel_core@7.3.4@@babel\core\lib\config\partial.js:85:55)
    at Object.loadPartialConfig (C:\Users\春夏\Desktop\sss\node_modules\_@babel_core@7.3.4@@babel\core\lib\config\partial.js:110:18)
    at Object.<anonymous> (C:\Users\春夏\Desktop\sss\node_modules\_babel-loader@8.0.5@babel-loader\lib\index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\春夏\Desktop\sss\node_modules\_babel-loader@8.0.5@babel-loader\lib\index.js:3:103)
    at _next (C:\Users\春夏\Desktop\sss\node_modules\_babel-loader@8.0.5@babel-loader\lib\index.js:5:194)
    at C:\Users\春夏\Desktop\sss\node_modules\_babel-loader@8.0.5@babel-loader\lib\index.js:5:364
    at new Promise (<anonymous>)

 @ multi ./node_modules/webpack-dev-server/client?http://172.20.10.3:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by loganfsmyth** [comment]
Please post your Babel configuration.

**Comment by danez** [comment]
Seems your configuration is wrong. Please reopen and fill out the issue template for bugs.
