### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by Y-k-Y** [babel/babel#9694]
## Bug Report

**Current Behavior**
Recently I'm trying to setup babel with webpack. and I'm getting an error.

**Input Code**
```
ERROR in (webpack)-dev-server/client?http://0.0.0.0:3000
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\webpack-dev-server\client\index.js: .definitions is not a valid Plugin property
    at Object.keys.forEach.key (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\validation\plugins.js:52:56)
    at Array.forEach (<anonymous>)
    at validatePluginObject (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\validation\plugins.js:50:20)
    at instantiatePlugin (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\full.js:209:55)
    at cachedFunction (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\caching.js:33:19)
    at loadPluginDescriptor (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\full.js:200:10)
    at config.plugins.reduce (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\full.js:69:20)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\full.js:67:38)
    at loadFullConfig (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\full.js:108:6)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 ./src/main/resources/static/js/app/main.js bundle[0]

ERROR in ./src/main/resources/static/js/app/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\Users\Y2K\IdeaProjects\spring-webservice\src\main\resources\static\js\app\main.js: .definitions is not a valid Plugin property
    at Object.keys.forEach.key (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\validation\plugins.js:52:56)
    at Array.forEach (<anonymous>)
    at validatePluginObject (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\validation\plugins.js:50:20)
    at instantiatePlugin (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\full.js:209:55)
    at cachedFunction (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\caching.js:33:19)
    at loadPluginDescriptor (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\full.js:200:10)
    at config.plugins.reduce (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\full.js:69:20)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\full.js:67:38)
    at loadFullConfig (C:\Users\Y2K\IdeaProjects\spring-webservice\node_modules\@babel\core\lib\config\full.js:108:6)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 ./src/main/resources/static/js/app/main.js bundle[1]
```

**package.json**
```
{
  "name": "spring-webservice",
  "version": "1.0.0",
  "description": "spring-webservice",
  "scripts": {
    "dev": "webpack-dev-server --config ./configs/webpack.config.dev.js"
  },
  "private": true,
  "main": "index.js",
  "repository": "https://github.com/Y-k-Y/spring-webservice.git",
  "author": "Y_K_Y <Zzzzz.co.kr@gmail.com>",
  "license": "MIT",
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.7.2",
    "bootstrap": "^4.3.1",
    "bulma": "^0.7.4",
    "jquery": "^3.3.1",
    "lodash": "^4.17.11",
    "popper.js": "^1.14.7"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.4",
    "@babel/plugin-transform-runtime": "^7.3.4",
    "@babel/preset-env": "^7.3.4",
    "@babel/runtime": "^7.3.4",
    "babel-loader": "^8.0.5",
    "css-loader": "^2.1.1",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.2.3",
    "webpack-dev-server": "^3.2.1",
    "webpack-merge": "^4.2.1"
  }
}
```

**config.common.js for both development and production**
```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
	entry: {
		/*vendors: [
			path.resolve(__dirname, '../node_modules/jquery/dist/jquery.min.js'),
			path.resolve(__dirname, '../node_modules/popper.js/dist/popper.min.js')
			path.resolve(__dirname, '../node_modules/bootstrap/dist/js/bootstrap.min.js')
			path.resolve(__dirname, '../node_modules/bootstrap/dist/css/bootstrap.min.css')
		],*/
		bundle: [
			path.resolve(__dirname, '../src/main/resources/static/js/app/main.js')
		],
		/*styles: [
			path.resolve(__dirname, '../src/main/resources/static/css/app/main.css')
		]*/
	},
	module: {
		rules: [
			{
				test: /\.js$/,
				use: {
					loader: 'babel-loader',
					options: {
						presets: ['@babel/preset-env'],
						plugins: [
							'@babel/plugin-transform-runtime',
							new webpack.ProvidePlugin({
							  $: 'jquery',
							  jQuery: 'jquery',
							  'window.jQuery': 'jquery',
							  Popper: 'popper.js'
							})
						]
					}
				}
			}
		]
	},
	resolve: {
		modules: [ 'node_modules' ],
		extensions: ['.js', '.json', '.jsx', '.css']
	}
};
```

**config.dev.js**
```js
const path = require('path');
const merge = require('webpack-merge');

const webpackConfigDev = {
	mode: 'development',
	
	output: {
		path: path.resolve(__dirname, '../src/'),
		filename: '[name].js',
		publicPath: '/webpack'
	},
	
	module: {
		rules: [{
			test: /\.(css)$/,
			use: [
				'style-loader',
				'css-loader',
			]
		}]
	},
		
	devServer: {
        hot: false,
        host: '0.0.0.0',
        disableHostCheck: true,
        port: 3000,
        contentBase: path.resolve(__dirname, '../src/main/resources/templates'),
        watchOptions: {
            aggregateTimeout: 300,
            poll: 1000
        },
        historyApiFallback: {
            rewrites: [
                { from: /.*/g, to: '/main2.html' }
            ]
        }
    },
	
	devtool: '#eval-source-map'
};

module.exports = merge(require('./webpack.config.common'), webpackConfigDev);
```
**Environment**
- Babel version(s): 
-  Node/npm version: v10.15.0/6.4.1
- OS: Windows 10

Except new webpack.ProvidePlugin, it successfully compile but on the console of web browser(chrome) another error pop up

```
typeof.js?7037:17 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.eval (typeof.js?7037:17)
    at eval (typeof.js:35)
    at Module../node_modules/@babel/runtime/helpers/typeof.js (bundle.js:97)
    at __webpack_require__ (bundle.js:20)
    at Module.eval (encode.js?e099:1)
    at eval (encode.js:93)
    at Module../node_modules/querystring-es3/encode.js (bundle.js:294)
    at __webpack_require__ (bundle.js:20)
    at eval (index.js?b383:4)
    at Object../node_modules/querystring-es3/index.js (bundle.js:306)
```

**Comment by danez** [comment]
Your configuration is wrong. You cannot supply webpack plugins to babel.

It should be:

```js
module.exports = {
	...
	module: {
		rules: [
			{
				test: /\.js$/,
				use: {
					loader: 'babel-loader',
					options: {
						presets: ['@babel/preset-env'],
						plugins: [
							'@babel/plugin-transform-runtime',
						]
					}
				}
			}
		]
	},
        plugins: [
          new webpack.ProvidePlugin({
							  $: 'jquery',
							  jQuery: 'jquery',
							  'window.jQuery': 'jquery',
							  Popper: 'popper.js'
							})
        ]
...
};
```

**Comment by Y-k-Y** [comment]
@danez 

Thank you so much!! you save me🙇🏻

now compiled successfully but i still have no idea why the chrome still throws that error and the CSS code isn't working. i know it's not babel problem now just i thought you might know that problem too
