### ISSUE TITLE
Module build failed ERROR in ./src/index.js Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by sumitkp** [babel/babel#9701]
I am starting a new project in webpack and I am getting the following error, Please help-:
```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/sumit.kapoor/Desktop/goibibo/gocars_ops/src/index.js: Unexpected token (10:12)

  8 |  render(){
  9 |         return(
> 10 |             <BrowserRouter>
    |             ^
 11 |                 <App />
 12 |             </BrowserRouter>
 13 |         )
   at Parser.raise (/Users/sumit.kapoor/Desktop/goibibo/gocars_ops/node_modules/@babel/parser/lib/index.js:3831:17)
   at Parser.unexpected (/Users/sumit.kapoor/Desktop/goibibo/gocars_ops/node_modules/@babel/parser/lib/index.js:5143:16)
   at Parser.parseExprAtom (/Users/sumit.kapoor/Desktop/goibibo/gocars_ops/node_modules/@babel/parser/lib/index.js:6283:20)
   at Parser.parseExprSubscripts (/Users/sumit.kapoor/Desktop/goibibo/gocars_ops/node_modules/@babel/parser/lib/index.js:5862:23)
   at Parser.parseMaybeUnary (/Users/sumit.kapoor/Desktop/goibibo/gocars_ops/node_modules/@babel/parser/lib/index.js:5842:21)
   at Parser.parseExprOps (/Users/sumit.kapoor/Desktop/goibibo/gocars_ops/node_modules/@babel/parser/lib/index.js:5729:23)
   at Parser.parseMaybeConditional (/Users/sumit.kapoor/Desktop/goibibo/gocars_ops/node_modules/@babel/parser/lib/index.js:5702:23)
   at Parser.parseMaybeAssign (/Users/sumit.kapoor/Desktop/goibibo/gocars_ops/node_modules/@babel/parser/lib/index.js:5647:21)
   at Parser.parseParenAndDistinguishExpression (/Users/sumit.kapoor/Desktop/goibibo/gocars_ops/node_modules/@babel/parser/lib/index.js:6435:28)
   at Parser.parseExprAtom (/Users/sumit.kapoor/Desktop/goibibo/gocars_ops/node_modules/@babel/parser/lib/index.js:6215:21)
@ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js main[1]
:information_source: ｢wdm｣: Failed to compile.
```

Here are my webpack.config.js & package.json files given below-:
webpack.config.js
```
var webpack = require('webpack');
module.exports = {
	entry :[
		'./src/index.js'
	],
	output: {
		filename: '../build/bundle.js',
		
	},
	module:{
		rules: [{
			exclude:'/node_modules/',
            loader:'babel-loader',
            test: /\.js$/
		}]
	}
};
```

.babelrc
```
{
    "presets": ["env"]
}
```

package.json

```
{
  "name": "gocars_ops",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --history-api-fallback",
    "build": "webpack"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/goibibo/gocars_ops.git"
  },
  "author": "Sumit Kapoor",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/goibibo/gocars_ops/issues"
  },
  "homepage": "https://github.com/goibibo/gocars_ops#readme",
  "dependencies": {
    "babel-loader": "^8.0.5",
    "express": "^4.16.4",
    "webpack-dev-server": "^3.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.3.4",
    "babel-preset-env": "^1.7.0",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0"
  }
}
```

**Comment by nicolo-ribaudo** [comment]
1) You should update preset-env to v7 (`@babel/preset-env`)
2) JSX is handled by the `@babel/plugin-transform-jsx` plugin (or `@babel/preset-react`)
