### ISSUE TITLE
Template literal parsing with the typescript preset not working as expected.

### ISSUE THREAD

**Issue by bopfer** [babel/babel#9706]
## Bug Report

**Current Behavior**
`@babel/preset-typescript` parsing of template literals in TypeScript types is not working as expected.

My team is trying to standardize on always using template literals (backticks) for all strings.  For the most part it is going well.  Except for this one case. In the code below, it will error with an `Unexpected token (6:11)`.  See the AST link for details.

**Input Code**
```javascript
const foo = `bar`;

const baz = `Hello, ${foo}`;

type Props = {
  variant: `lightBg` | `darkBg`;
};
```

AST Explorer link: https://astexplorer.net/#/gist/8dfe77749cb537070c7bef1da6cf7d06/275d39c3682ffe282175fdc85704060e7295f95a

**Expected behavior/code**
The template literals should be treated like single and double quoted strings.

Side note: The `typescript` and `@typescript-eslint/parser` do parse properly.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [
    `@babel/env`,
    `@babel/react`,
    `@babel/typescript`
  ],
  plugins: [ ]
}
```

**Environment**
- Babel version(s): 7.3.4
- Node/npm version: Node 11/yarn 1.15.2
- OS: OSX 10.14.3
- Monorepo:  yes
- How you are using Babel: cli

**Additional context/Screenshots**
This is the error when I run babel from the cli:
```
yarn run v1.15.2
$ babel src --out-dir dist --extensions ".tsx"
{ SyntaxError: src/Message.tsx: Unexpected token (6:11)

  4 |
  5 | type Props = {
> 6 |   variant: `lightBg` | `darkBg`;
    |           ^
  7 | };
  8 |
  9 | const Message: React.FC<IProps> = (props) => (
    at Object.raise (node_modules/@babel/parser/lib/index.js:3831:17)
    at Object.unexpected (node_modules/@babel/parser/lib/index.js:5143:16)
    at Object.tsParseNonArrayType (node_modules/@babel/parser/lib/index.js:9269:16)
    at Object.tsParseArrayTypeOrHigher (node_modules/@babel/parser/lib/index.js:9273:21)
    at Object.tsParseTypeOperatorOrHigher (node_modules/@babel/parser/lib/index.js:9312:120)
    at Object.tsParseUnionOrIntersectionType (node_modules/@babel/parser/lib/index.js:9317:16)
    at Object.tsParseIntersectionTypeOrHigher (node_modules/@babel/parser/lib/index.js:9335:17)
    at Object.tsParseUnionOrIntersectionType (node_modules/@babel/parser/lib/index.js:9317:16)
    at Object.tsParseUnionTypeOrHigher (node_modules/@babel/parser/lib/index.js:9339:17)
    at Object.tsParseNonConditionalType (node_modules/@babel/parser/lib/index.js:9492:17)
  pos: 104,
  loc: Position { line: 6, column: 11 },
  code: 'BABEL_PARSE_ERROR' }
```

**Comment by tanhauhau** [comment]
Let me look into this
