### ISSUE TITLE
Object rest parameters throw exceptions on parsing (related to upgrade to `core-js@3`)

### ISSUE THREAD

**Issue by ehmicky** [babel/babel#9713]
## Bug Report

**Current Behavior**
I've just upgraded to `core-js@3` and Babel `7.4.0`. Object rest parameters are throwing errors when being parsed.

**Input Code**

`test.js`:

```js
function test({ ...others }) {}
```

In a terminal:

```bash
$ babel test.js
TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at resolveKey (/home/ether/Desktop/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:74:9)
    at PluginPass.ObjectPattern (/home/ether/Desktop/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:204:21)
    at newFn (/home/ether/Desktop/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/home/ether/Desktop/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/ether/Desktop/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/home/ether/Desktop/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/home/ether/Desktop/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/home/ether/Desktop/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/home/ether/Desktop/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/ether/Desktop/node_modules/@babel/traverse/lib/index.js:94:17)
```

**Expected behavior/code**
No exception should be thrown.

**Babel Configuration (.babelrc)**

```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: { node: '8.10.0' },
        useBuiltIns: 'usage',
        corejs: 3,
      },
    ],
  ],
  plugins: ['@babel/plugin-transform-runtime'],
}
```

**Environment**

```
$ npm ls @babel/cli @babel/core @babel/plugin-transform-runtime @babel/preset-env @babel/runtime core-js
desktop@1.0.0 /home/ether/Desktop
├── @babel/cli@7.2.3 
├── @babel/core@7.4.0 
├── @babel/plugin-transform-runtime@7.4.0 
├─┬ @babel/preset-env@7.4.1 
│ └─┬ core-js-compat@3.0.0
│   └── core-js@3.0.0  deduped
├── @babel/runtime@7.4.0 
└── core-js@3.0.0 
```

- Node/npm version: node `v11.12.0`, npm `6.9.0`
- OS: Ubuntu 18.10
- Monorepo: no
- How you are using Babel: `cli`

**Comment by nicolo-ribaudo** [comment]
As a side note, you need to use `corejs: 3` instead of `corejs: 'core-js@3'`.

**Comment by ehmicky** [comment]
@nicolo-ribaudo thanks for the tip, I was actually a little confused about this. I got the wrong option from this [StackOverflow question](https://stackoverflow.com/questions/55251983/what-does-this-error-mean-with-usebuiltins-option-required-direct-setting-of).

However setting it to `3` still reproduces the issue.

**Comment by zloirock** [comment]
I'll try to fix it after some hours.

**Comment by zloirock** [comment]
Fixed.

**Comment by ehmicky** [comment]
This works! Thanks!
