### ISSUE TITLE
Upgrading to version 7.4.2 yields in an exception 

### ISSUE THREAD

**Issue by amir20** [babel/babel#9759]
## Bug Report

**Current Behavior**
Trying to upgrade from 7.3.4 to 7.4.2.
 I get the following error: 

```
ERROR in ./js/player-page.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: [BABEL] /Users/amirraminfar/Workspace/clashstats/assets/js/player-page.js: (0 , _semver(...).coerce) is not a function (While processing: "/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js")
    at normalizeCoreJSOption (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:173:53)
    at normalizeOptions (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:192:18)
    at _default (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js:109:37)
    at /Users/amirraminfar/Workspace/clashstats/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:108:6)
    at process.nextTick (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/transform.js:28:33)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
```

<details>

<summary>Full output</summary>

```
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Hash: 54d4758c294e3508b4d4
Version: webpack 4.29.6
Time: 3699ms
Built at: 03/24/2019 11:29:55 AM
 530 assets
Entrypoint clan-page = js/clan-page.9b28a3645c9f3a972281.js js/clan-page.9b28a3645c9f3a972281.js.map
Entrypoint player-page = js/player-page.4eb087b6569947f95432.js js/player-page.4eb087b6569947f95432.js.map
Entrypoint troop-page = js/troop-page.b3a9d83178b8e44d599b.js js/troop-page.b3a9d83178b8e44d599b.js.map
Entrypoint index = js/index.67b04bc7ef150fb2291d.js js/index.67b04bc7ef150fb2291d.js.map
Entrypoint common = js/common.cb5a7ef50c06709f1460.js js/common.cb5a7ef50c06709f1460.js.map
Entrypoint styles = css/styles-compiled.43c97e42da9603ed8d7e.css js/styles-compiled.43c97e42da9603ed8d7e.js js/styles-compiled.43c97e42da9603ed8d7e.js.map js/styles.a675fc9b378185abf964.js js/styles.a675fc9b378185abf964.js.map
[0] ./js/clan-page.js 1.71 KiB {0} [built] [failed] [1 error]
[1] ./js/player-page.js 1.71 KiB {3} [built] [failed] [1 error]
[2] ./js/troop-page.js 1.71 KiB {6} [built] [failed] [1 error]
[3] ./js/index.js 1.71 KiB {2} [built] [failed] [1 error]
[4] ./js/common.js 1.71 KiB {1} [built] [failed] [1 error]
[5] ./css/styles.scss 39 bytes {4} [built]
    + 1 hidden module

ERROR in ./js/clan-page.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: [BABEL] /Users/amirraminfar/Workspace/clashstats/assets/js/clan-page.js: (0 , _semver(...).coerce) is not a function (While processing: "/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js")
    at normalizeCoreJSOption (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:173:53)
    at normalizeOptions (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:192:18)
    at _default (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js:109:37)
    at /Users/amirraminfar/Workspace/clashstats/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:108:6)
    at process.nextTick (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/transform.js:28:33)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)

ERROR in ./js/common.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: [BABEL] /Users/amirraminfar/Workspace/clashstats/assets/js/common.js: (0 , _semver(...).coerce) is not a function (While processing: "/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js")
    at normalizeCoreJSOption (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:173:53)
    at normalizeOptions (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:192:18)
    at _default (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js:109:37)
    at /Users/amirraminfar/Workspace/clashstats/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:108:6)
    at process.nextTick (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/transform.js:28:33)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)

ERROR in ./js/index.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: [BABEL] /Users/amirraminfar/Workspace/clashstats/assets/js/index.js: (0 , _semver(...).coerce) is not a function (While processing: "/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js")
    at normalizeCoreJSOption (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:173:53)
    at normalizeOptions (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:192:18)
    at _default (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js:109:37)
    at /Users/amirraminfar/Workspace/clashstats/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:108:6)
    at process.nextTick (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/transform.js:28:33)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)

ERROR in ./js/player-page.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: [BABEL] /Users/amirraminfar/Workspace/clashstats/assets/js/player-page.js: (0 , _semver(...).coerce) is not a function (While processing: "/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js")
    at normalizeCoreJSOption (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:173:53)
    at normalizeOptions (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:192:18)
    at _default (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js:109:37)
    at /Users/amirraminfar/Workspace/clashstats/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:108:6)
    at process.nextTick (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/transform.js:28:33)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)

ERROR in ./js/troop-page.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: [BABEL] /Users/amirraminfar/Workspace/clashstats/assets/js/troop-page.js: (0 , _semver(...).coerce) is not a function (While processing: "/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js")
    at normalizeCoreJSOption (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:173:53)
    at normalizeOptions (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/normalize-options.js:192:18)
    at _default (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/preset-env/lib/index.js:109:37)
    at /Users/amirraminfar/Workspace/clashstats/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/config/full.js:108:6)
    at process.nextTick (/Users/amirraminfar/Workspace/clashstats/node_modules/@babel/core/lib/transform.js:28:33)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js??ref--5-1!../node_modules/postcss-loader/src/index.js??postcss!../node_modules/sass-loader/lib/loader.js!css/styles.scss:
    Entrypoint mini-css-extract-plugin = *
      [0] ../node_modules/css-loader/dist/cjs.js??ref--5-1!../node_modules/postcss-loader/src??postcss!../node_modules/sass-loader/lib/loader.js!./css/styles.scss 461 KiB {0} [built]
    [517] ./images/coc-sprite.png 91 bytes {0} [built]
    [518] ./images/logo.svg 12.5 KiB {0} [built]
    [519] ./images/DO_Powered_by_Badge_blue.svg 6.26 KiB {0} [built]
        + 516 hidden modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! clashleaders@2.6.0 build: `webpack --config webpack.prod.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the clashleaders@2.6.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/amirraminfar/.npm/_logs/2019-03-24T18_29_55_936Z-debug.log
⨉⪧ ~/W/clashstats on corejs3 ⟩                                                                                                                                  4s 971ms
```
</details>

**Input Code**

See https://gist.github.com/amir20/96ce4d442e725dc1cd9bfa1750949954 for the diff 

**Expected behavior/code**
For the code to compile using webpack.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false,
        "useBuiltIns": "usage",
        "corejs": 3,
        "targets": {
          "browsers": ["> 0.25%", "last 2 versions", "not ie <= 9"]
        }
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-object-rest-spread",
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": true,
        "corejs": 3,
      }
    ]
  ]
}

```

**Environment**

- Babel version(s): 7.4.2
- Node/npm version: 11.12.0
- OS: [e.g. OSX 10.13.4, Windows 10]: OSX
- Monorepo: [e.g. yes/no/Lerna] no
- How you are using Babel: [e.g. `cli`, `register`, `loader`]: Webpack

**Possible Solution**

**Additional context/Screenshots**

**Comment by amir20** [comment]
I imagine the error is coming from https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/normalize-options.js#L226 but I don't know what I did to make `coerce` not be a function.

**Comment by zloirock** [comment]
Most likely it's an issue with `semver` version, see https://github.com/babel/babel/pull/9738. Could you try to update `semver` dependency manually?

**Comment by amir20** [comment]
`npm i semver` fixes the problem. But I have other problems now like 

```
Module not found: Error: Can't resolve '@babel/runtime-corejs3/helpers/taggedTemplateLiteral' in '/Users/amirraminfar/Workspace/clashstats/assets/js'
```

However, I'll treat as a different issue. I'll keep updating and post back when I have found a solution.

**Comment by amir20** [comment]
Sounds like I missed a step in upgrading. I also needed to `npm install --save @babel/runtime-corejs3`. 

Everything works now. Thanks @zloirock. Should i close this or leave open?

**Comment by zloirock** [comment]
Since it's already fixed on the `master` branch, it would be better to close it.

**Comment by rpearce** [comment]
Until `7.4.3` comes out, here's what needs to be done in `package.json` if you have more than 1 version of `semver` in your dependencies and you can't get this to work:
```
  "resolutions": {
    "semver": "^5.5.0"
  }
```
