### ISSUE TITLE
ERROR in ./src/index.js Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by itzik415** [babel/babel#9776]
I deconstructed my Create-React-App with Webpack 4 & Babel 7. The first time I ran the command "npm run build" it worked and created a new build folder. Now after the first time I am trying to run the command again and I am getting the error blow.

**ERROR in ./src/index.js 
Module build failed (from ./node_modules/babel-loader/lib/index.js):**

I searched for the solution but all I could find was babel versions discrepancy in Package.json file, something that I don't seem to have.

**Package.json**
```
{
  "name": "hamilton-beach",
  "version": "0.1.0",
  "license": "MIT",
  "main": "src/index.js",
  "scripts": {
    "start": "webpack-dev-server --open --port 3000 --compress --mode development",
    "dev": "webpack --mode development --progress",
    "build": "webpack --mode production --progress",
    "build-css": "node-sass --include-path scss src/main.scss   src/App.css",
    "watch-css": "nodemon -e scss -x \"npm run build-css\""
  },
  "private": true,
  "dependencies": {
    "@babel/polyfill": "^7.4.0",
    "axios": "^0.18.0",
    "core-js": "^3.0.0",
    "css-loader": "^2.1.1",
    "file-loader": "^3.0.1",
    "jsonwebtoken": "^8.5.0",
    "lodash": "^4.17.11",
    "node-sass": "^4.11.0",
    "nodemailer-sendgrid-transport": "^0.2.0",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-redux": "^6.0.0",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "proxy": "http://localhost:5000",
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.5",
    "html-webpack-plugin": "^4.0.0-beta.5",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.2.1"
  }
}
```
**webpack.config.js**

```
const HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
    devtool: 'cheap-module-source-map',
    module: {
        rules: [
            { 
                test: /\.jsx?$/, 
                exclude: /node_modules/, 
                loader: 'babel-loader'
            },
            {
                test: /\.scss$/,
                use: [
                  {
                    loader: "style-loader" // creates style nodes from JS strings
                  },
                  {
                    loader: "css-loader" // translates CSS into CommonJS
                  },
                  {
                    loader: "sass-loader" // compiles Sass to CSS
                  }
                ]
            },
            {
                test: /\.(ttf|eot|svg|gif|png|jpg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                use: [{
                    loader: 'file-loader'
                }]
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: 'index.html'
        })
    ]
}
```

**.babelrc**

```
{
    "presets": [
        [
            "@babel/env", 
            {
                "useBuiltIns": "entry",
                "targets": {
                    "browsers": [
                        "last 2 versions"
                    ]
                }
            },
            "@babel/react"
        ]
    ],
    "plugins": [
        "@babel/proposal-class-properties",
        ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": true }],
    ]
}
```

**Comment by nicolo-ribaudo** [comment]
What is the full error and stacktrace?

**Comment by itzik415** [comment]
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/src/index.js: Unexpected token (19:4)

  17 | 
  18 | ReactDOM.render(
> 19 |     <Provider store={store}>
     |     ^
  20 |         <Main />
  21 |     </Provider>, document.getElementById('root')
  22 | );
    at Parser.raise (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:3851:17)
    at Parser.unexpected (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5165:16)
    at Parser.parseExprAtom (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:6330:20)
    at Parser.parseExprSubscripts (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5916:23)
    at Parser.parseMaybeUnary (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseExprListItem (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:6979:18)
    at Parser.parseCallExpressionArguments (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:6123:22)
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src main[1]

**Comment by itzik415** [comment]
**ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/src/index.js: Unexpected token (19:4)**

    17 | 
    18 | ReactDOM.render(
> 19 |     <Provider store={store}>
         |     ^
   20 |         <Main />
    21 |     </Provider>, document.getElementById('root')
  22 | );
    at Parser.raise (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:3851:17)
    at Parser.unexpected (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5165:16)
    at Parser.parseExprAtom (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:6330:20)
    at Parser.parseExprSubscripts (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5916:23)
    at Parser.parseMaybeUnary (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseExprListItem (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:6979:18)
    at Parser.parseCallExpressionArguments (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:6123:22)
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src main[1]

**Comment by nicolo-ribaudo** [comment]
If you write random things in your `.babelrc`, does it throw a SyntaxError? Maybe your config isn't picked up.

**Comment by itzik415** [comment]
**ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/src/index.js: Unexpected token (19:4)**
```

  17 | 
  18 | ReactDOM.render(
> 19 |     <Provider store={store}>
     |     ^
  20 |         <Main />
  21 |     </Provider>, document.getElementById('root')
  22 | );
    at Parser.raise (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:3851:17)
    at Parser.unexpected (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5165:16)
    at Parser.parseExprAtom (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:6330:20)
    at Parser.parseExprSubscripts (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5916:23)
    at Parser.parseMaybeUnary (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseExprListItem (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:6979:18)
    at Parser.parseCallExpressionArguments (/Users/itzikshaoulian/Desktop/Projects/hamilton-beach/frontend/node_modules/@babel/parser/lib/index.js:6123:22)
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src main[1]
```

**Comment by itzik415** [comment]
Yes @nicolo-ribaudo 
It is throwing an error.

**Comment by nicolo-ribaudo** [comment]
Is there any `package.json` file in `src/`? If so, renaming your config to `babel.config.js` will probably fix the problem.
If it doesn't, could you create a repository which shows the issue I could look at?

**Comment by itzik415** [comment]
I did what you said and I got this:

```
ERROR in ./src/index.js 19:4
Module parse failed: Unexpected token (19:4)
You may need an appropriate loader to handle this file type.
| 
| ReactDOM.render(
>     <Provider store={store}>
|         <Main />
|     </Provider>, document.getElementById('root')
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src main[1]
ℹ ｢wdm｣: Failed to compile.
```

**Comment by itzik415** [comment]
@nicolo-ribaudo https://github.com/itzik415/hamilton-beach

**Comment by nicolo-ribaudo** [comment]
Hi @itzik415, sorry for the long delay.
I cloned your repo and tried to build it: it seems that you figured out how to fix this problem?
