### ISSUE TITLE
Babel 7 produces invalid code when decorating async methods

### ISSUE THREAD

**Issue by matthewadams** [babel/babel#9805]
## Bug Report

**Current Behavior**
Babel 7 `plugin-proposal-decorators` with `legacy: true` & `@babel/plugin-proposal-class-properties` with `loose: true` produces invalid code when decorating `async` methods, causing a syntax error at runtime:
```
$ npm run unit
npm WARN lifecycle The node binary used for scripts is /Users/matthewadams/.asdf/shims/node but npm is using /Users/matthewadams/.asdf/installs/nodejs/10.14.2/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @scispike/aspectify@0.1.0-pre.1 unit /Users/matthewadams/dev/scispike/aspectify
> nyc --check-coverage -x 'lib/test' --exclude-after-remap false mocha --opts mocha.opts 'lib/test/unit/**/*.spec.js'

/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/core/lib/transformation/normalize-file.js:209
    throw err;
    ^

SyntaxError: /Users/matthewadams/dev/scispike/aspectify/lib/test/unit/async/before.spec.js: Can not use keyword 'await' outside an async function (51:10)

  49 |         async
  50 |         go(delayMillis, value) {
> 51 |           await pause(delayMillis);
     |           ^
  52 |           return value;
  53 |         }}, (_applyDecoratedDescriptor(_class.prototype, "go", [ParameterlessBeforeCount], Object.getOwnPropertyDescriptor(_class.prototype, "go"), _class.prototype)), _class);
  54 |
    at Parser.raise (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:3851:17)
    at Parser.checkReservedWord (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7041:14)
    at Parser.parseIdentifierName (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7013:12)
    at Parser.parseIdentifier (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6987:23)
    at Parser.parseExprAtom (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6201:27)
    at Parser.parseExprSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5916:23)
    at Parser.parseMaybeUnary (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseExpression (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5651:23)
    at Parser.parseStatementContent (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7422:23)
    at Parser.parseStatement (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7293:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7879:25)
    at Parser.parseBlockBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7866:10)
    at Parser.parseBlock (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7850:10)
    at Parser.parseFunctionBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6911:24)
    at Parser.parseFunctionBodyAndFinish (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6881:10)
    at Parser.parseMethod (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6837:10)
    at Parser.pushClassMethod (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8272:30)
    at Parser.parseClassMemberWithIsStatic (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8197:12)
    at Parser.parseClassMember (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8136:10)
    at withTopicForbiddingContext (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8091:14)
    at Parser.withTopicForbiddingContext (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7187:14)
    at Parser.parseClassBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8068:10)
    at Parser.parseClass (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8042:22)
    at Parser.parseExprAtom (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6287:21)
    at Parser.parseExprSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5916:23)
    at Parser.parseMaybeUnary (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseMaybeAssign (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5742:25)
    at Parser.parseParenAndDistinguishExpression (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6468:28)
    at Parser.parseExprAtom (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6262:21)
    at Parser.parseExprSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5916:23)
    at Parser.parseMaybeUnary (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseVar (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7951:26)
    at Parser.parseVarStatement (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7773:10)
    at Parser.parseStatementContent (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7360:21)
    at Parser.parseStatement (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7293:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7879:25)
    at Parser.parseBlockBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7866:10)
    at Parser.parseBlock (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7850:10)
    at Parser.parseFunctionBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6911:24)
    at Parser.parseFunctionBodyAndFinish (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6881:10)
    at withTopicForbiddingContext (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8014:12)
    at Parser.withTopicForbiddingContext (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7187:14)
    at Parser.parseFunction (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8013:10)
    at Parser.parseExprAtom (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6205:25)
    at Parser.parseExprSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5916:23)
    at Parser.parseMaybeUnary (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseExprListItem (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6979:18)
    at Parser.parseCallExpressionArguments (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6123:22)
    at Parser.parseSubscript (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6018:29)
    at Parser.parseSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5937:19)
    at Parser.parseExprSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5926:17)
    at Parser.parseMaybeUnary (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseExpression (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5651:23)
    at Parser.parseStatementContent (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7422:23)
    at Parser.parseStatement (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7293:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7879:25)
    at Parser.parseBlockBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7866:10)
    at Parser.parseBlock (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7850:10)
    at Parser.parseFunctionBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6911:24)
    at Parser.parseFunctionBodyAndFinish (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6881:10)
    at withTopicForbiddingContext (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8014:12)
    at Parser.withTopicForbiddingContext (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7187:14)
    at Parser.parseFunction (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8013:10)
    at Parser.parseFunctionExpression (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6366:17)
    at Parser.parseExprAtom (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6279:21)
    at Parser.parseExprSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5916:23)
    at Parser.parseMaybeUnary (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseExprListItem (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6979:18)
    at Parser.parseCallExpressionArguments (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6123:22)
    at Parser.parseSubscript (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6018:29)
    at Parser.parseSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5937:19)
    at Parser.parseExprSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5926:17)
    at Parser.parseMaybeUnary (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseExpression (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5651:23)
    at Parser.parseStatementContent (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7422:23)
    at Parser.parseStatement (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7293:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7879:25)
    at Parser.parseBlockBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7866:10)
    at Parser.parseBlock (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7850:10)
    at Parser.parseFunctionBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6911:24)
    at Parser.parseFunctionBodyAndFinish (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6881:10)
    at withTopicForbiddingContext (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8014:12)
    at Parser.withTopicForbiddingContext (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7187:14)
    at Parser.parseFunction (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8013:10)
    at Parser.parseFunctionExpression (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6366:17)
    at Parser.parseExprAtom (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6279:21)
    at Parser.parseExprSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5916:23)
    at Parser.parseMaybeUnary (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseExprListItem (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6979:18)
    at Parser.parseCallExpressionArguments (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6123:22)
    at Parser.parseSubscript (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:6018:29)
    at Parser.parseSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5937:19)
    at Parser.parseExprSubscripts (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5926:17)
    at Parser.parseMaybeUnary (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5896:21)
    at Parser.parseExprOps (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5783:23)
    at Parser.parseMaybeConditional (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5756:23)
    at Parser.parseMaybeAssign (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5703:21)
    at Parser.parseExpression (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:5651:23)
    at Parser.parseStatementContent (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7422:23)
    at Parser.parseStatement (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7293:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7879:25)
    at Parser.parseBlockBody (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7866:10)
    at Parser.parseTopLevel (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:7222:10)
    at Parser.parse (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:8871:17)
    at parse (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/parser/lib/index.js:11133:38)
    at parser (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at transformSync (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/core/lib/transform.js:43:38)
    at Object.transform (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/core/lib/transform.js:22:38)
    at compile (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/register/lib/node.js:73:20)
    at compileHook (/Users/matthewadams/dev/scispike/aspectify/node_modules/@babel/register/lib/node.js:102:12)
    at Module._compile (/Users/matthewadams/dev/scispike/aspectify/node_modules/pirates/lib/index.js:93:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at /Users/matthewadams/dev/scispike/aspectify/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at newLoader (/Users/matthewadams/dev/scispike/aspectify/node_modules/pirates/lib/index.js:104:7)
    at Object.<anonymous> (/Users/matthewadams/dev/scispike/aspectify/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/matthewadams/dev/scispike/aspectify/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/matthewadams/dev/scispike/aspectify/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/matthewadams/dev/scispike/aspectify/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/matthewadams/dev/scispike/aspectify/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.replacementCompile (/Users/matthewadams/dev/scispike/aspectify/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.<anonymous> (/Users/matthewadams/dev/scispike/aspectify/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at runMain (/Users/matthewadams/.node-spawn-wrap-37238-ffc691b9876d/node:68:10)
    at Function.<anonymous> (/Users/matthewadams/.node-spawn-wrap-37238-ffc691b9876d/node:171:5)
    at Object.<anonymous> (/Users/matthewadams/dev/scispike/aspectify/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at /Users/matthewadams/.node-spawn-wrap-37238-ffc691b9876d/node:178:8
    at Object.<anonymous> (/Users/matthewadams/.node-spawn-wrap-37238-ffc691b9876d/node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @scispike/aspectify@0.1.0-pre.1 unit: `nyc --check-coverage -x 'lib/test' --exclude-after-remap false mocha --opts mocha.opts 'lib/test/unit/**/*.spec.js'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @scispike/aspectify@0.1.0-pre.1 unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matthewadams/.npm/_logs/2019-04-01T21_40_35_691Z-debug.log
$
```

**Input Code**
See tests in https://github.com/SciSpike/aspectify/blob/async/src/test/unit/async/before.spec.js.

Specific lines would be near
* https://github.com/SciSpike/aspectify/blob/async/src/test/unit/async/before.spec.js#L51
* https://github.com/SciSpike/aspectify/blob/async/src/test/unit/async/before.spec.js#L79

Steps to reproduce:
* `cd /tmp # or wherever`
* `git clone https://github.com/SciSpike/aspectify`
* `git checkout async`
* `npm install`
* `npm run unit`

**Expected behavior/code**
You should be able to decorate `async` methods, including the possible replacement of the decorated method with a new `async` method.

**Babel Configuration (.babelrc, package.json, cli command)**
`package.json`:

```json
{
  "name": "@scispike/aspectify",
  "version": "0.1.0-pre.1",
  "description": "Decorator-driven, aspect-oriented programming (AOP) for Node.js",
  "engines": {
    "node": ">=10.12.0"
  },
  "scripts": {
    "build": "run-s test",
    "transpile": "run-s transpile-main transpile-test",
    "transpile-main": "babel --delete-dir-on-start --verbose --out-dir lib/main --copy-files src/main",
    "transpile-test": "babel --delete-dir-on-start --verbose --out-dir lib/test --copy-files src/test",
    "unit-integration": "nyc --check-coverage --statements 94 --branches 89 --functions 90 --lines 95 -x 'lib/test' --exclude-after-remap false mocha --opts mocha.opts 'lib/test/unit/**/*.spec.js' 'lib/test/integration/**/*.spec.js'",
    "postunit-integration": "run-s report",
    "integration": "nyc --check-coverage -x 'lib/test' --exclude-after-remap false mocha --opts mocha.opts 'lib/test/integration/**/*.spec.js'",
    "postintegration": "run-s report",
    "i": "mocha --opts mocha.opts 'src/test/integration/**/*.spec.js' | npx bunyan",
    "unit": "nyc --check-coverage -x 'lib/test' --exclude-after-remap false mocha --opts mocha.opts 'lib/test/unit/**/*.spec.js'",
    "postunit": "run-s report",
    "u": "mocha --opts mocha.opts 'src/test/unit/**/*.spec.js' | npx bunyan",
    "test": "run-s transpile unit-integration lint",
    "report": "nyc report --reporter=html",
    "cov": "open coverage/index.html",
    "lint": "standard --verbose 'src/**/*.js'",
    "format": "standard --fix 'src/**/*.js'",
    "make-distribution": "run-s transpile finalize-distribution",
    "finalize-distribution": "copyfiles --verbose package.json package-lock.json README.md lib/main"
  },
  "publishConfig": {
    "access": "public"
  },
  "dependencies": {
    "@babel/polyfill": "7.2.5"
  },
  "devDependencies": {
    "@babel/cli": "7.2.3",
    "@babel/core": "7.2.2",
    "@babel/plugin-proposal-class-properties": "7.2.3",
    "@babel/plugin-proposal-decorators": "7.2.3",
    "@babel/plugin-proposal-optional-chaining": "7.2.0",
    "@babel/preset-env": "7.2.3",
    "@babel/register": "7.0.0",
    "acorn": "6.0.4",
    "babel-eslint": "10.0.1",
    "chai": "4.2.0",
    "copyfiles": "2.1.0",
    "dirty-chai": "2.0.1",
    "fs-extra": "7.0.1",
    "intercept-stdout": "0.1.2",
    "mocha": "5.2.0",
    "npm-run-all": "4.1.5",
    "nyc": "13.1.0",
    "standard": "12.0.1"
  },
  "babel": {
    "sourceMaps": "inline",
    "retainLines": true,
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": true
          }
        }
      ]
    ],
    "plugins": [
      [
        "@babel/plugin-proposal-optional-chaining",
        {
          "loose": false
        }
      ],
      [
        "@babel/plugin-proposal-decorators",
        {
          "legacy": true
        }
      ],
      [
        "@babel/plugin-proposal-class-properties",
        {
          "loose": true
        }
      ]
    ]
  },
  "standard": {
    "parser": "babel-eslint"
  }
}
```

**Environment**
- Babel version(s): 7.2.2
- Node/npm version: v10.14.1/6.4.1
- OS: macOS 10.14.3 (18D109)
- Monorepo: no
- How you are using Babel: `register`?

**Possible Solution**

**Additional context/Screenshots**
See `async` branch of https://github.com/SciSpike/aspectify.  `master` branch, containing synchronous code, works beautifully.  See tests at `src/test/unit/sync` for synchronous usage.

**Comment by matthewadams** [comment]
Might be similar to https://github.com/babel/babel/issues/8650, since we also have `retainLines` set to `true`.

**Comment by matthewadams** [comment]
Just confirmed that I get the same behavior with `retainLines: false` and without any `retainLines` setting at all.

**Comment by matthewadams** [comment]
Reran with `retailLines` removed from my Babel configuration, and now, legal JavaScript is produced.  However, there is _still_ a bug.

It appears that, even if the decorated method carries the `async` modifier and its property descriptor's method is replaced with another `async` function, that function is not being invoked with a preceding `await`.  The unit test currently (as of this writing) in the `async` branch appears to confirm this theory.

Still investigating, though...

**Comment by matthewadams** [comment]
Ok.  Fixed.  Problem was that my generalized advice was not distinguishing between sync & `async` flavors.  Added that & all is fixed.  Now just polishing...
