### ISSUE TITLE
Mocha, Babel, and Windows symlinks

### ISSUE THREAD

**Issue by ricick** [babel/babel#9824]
## Bug Report

**Current Behavior**
Mocha is not running Babel beforehand when the project is behind a symlink on windows.

I have a small SSD and a larger HDD so to make my life easier I have a hard symlink to D:/projects in C:/Users/MyUser home directory, so can access via ~/projects.

When running `mocha --require @babel/register `I'm getting the Unexpected identifier import problem. I even re-installed windows thinking it might be an environment problem before figuring out that this was the problem

**Input Code**
Create a simple mocha es6 project in realfoldercontainer/myproject, to be run via npm test with `mocha -r @babel/register` in package.json

Create a hard symlink with `mklink /j linkname realfoldercontainer`

Navigate to linkname/myproject

Run npm test

**Expected behavior/code**
```
npm test

> mochatest@1.0.0 test D:\projects\mochatest
> mocha -r @babel/register

  index test
    sayHello function
      √ should say Hello guys!


  1 passing (44ms)
```

Actual behavior
```
npm test

> mochatest@1.0.0 test D:\testlink\mochatest
> mocha -r @babel/register

D:\projects\mochatest\test\index.test.js:3
import sayHello from "../src/index"
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:749:23)
    at Module._compile (D:\projects\mochatest\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Object.newLoader [as .js] (D:\projects\mochatest\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at D:\projects\mochatest\node_modules\mocha\lib\mocha.js:327:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (D:\projects\mochatest\node_modules\mocha\lib\mocha.js:324:14)
    at Mocha.run (D:\projects\mochatest\node_modules\mocha\lib\mocha.js:801:10)
    at Object.exports.singleRun (D:\projects\mochatest\node_modules\mocha\lib\cli\run-helpers.js:207:16)
    at exports.runMocha (D:\projects\mochatest\node_modules\mocha\lib\cli\run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (D:\projects\mochatest\node_modules\mocha\lib\cli\run.js:296:3)
    at Object.runCommand (D:\projects\mochatest\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (D:\projects\mochatest\node_modules\yargs\yargs.js:1089:24)
    at Object.parse (D:\projects\mochatest\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (D:\projects\mochatest\node_modules\mocha\lib\cli\cli.js:62:6)
    at Object.<anonymous> (D:\projects\mochatest\node_modules\mocha\bin\_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
npm ERR! Test failed.  See above for more details.
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
node v11.13.0

"@babel/cli": "^7.4.3",
"@babel/core": "^7.4.3",
"@babel/node": "^7.2.2",
"@babel/preset-env": "^7.4.3",
"@babel/register": "^7.4.0",
"chai": "^4.2.0",
"jest": "^24.7.1",
"mocha": "^6.0.2"

**Additional context/Screenshots**
I can now corretctly run the tests by going directly to the folder, but it took a long time to figure this out, including a system rebuild to try and fix the problem.

I'm unsure as to whether this is a babel or mocha issue, so will be posting in both github issues pages.

**Comment by jgroman** [comment]
Thank you @ricick for finding the source of the problem I was troubleshooting for some hours already.

Definitely a Babel issue as I am experiencing the same problem with gulpfile.babel.js in symlinked Windows directory without using Mocha whatsoever. Running gulp in original directory works fine.

**Versions:**
    "@babel/core": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "@babel/register": "^7.4.4",'''

Everything works fine even in symlinked directory using previous major Babel version installed with:
`$ npm install --save-dev gulp-babel@7 babel-core babel-preset-env`

**Comment by loganfsmyth** [comment]
The issue here is that `@babel/register`, by default, only runs Babel on files inside the working directory and not inside a `node_modules` folder. If you want a broader scope, you'll need to configure it. For example you can do `--require ./babel-register.js` and make that file:

```
// babel-register.js

require("@babel/register")({
  ignore: [/node_modules/]
});
```
to compile _all_ non-`node_modules` files, even those outside the working directory.

**Comment by jgroman** [comment]
Hi @loganfsmyth thanks for more insight! Does that mean that Babel considers symlinked win10 directory different from the original source directory and thus being "outside" working directory?

I created very simple repo with steps to reproduce the problem here: https://github.com/jgroman/babel_win10_dir_symlink

## Steps to reproduce problem

1. Clone repo
1. `npm i`
1. Run `gulp`

## Results

**Standard Win10 directory**

    c:\Users\jgroman\Documents\Project\test>gulp
    [09:36:51] Requiring external module @babel/register
    [09:36:52] Using gulpfile c:\Users\jgroman\Documents\Project\test\gulpfile.babel.js
    [09:36:52] Task never defined: default
    [09:36:52] To list available tasks, try running: gulp --tasks

**Symlinked Win10 directory**  
Created either using `mklink /D` or `mklink /J`

    c:\junctest>gulp
    [09:39:37] Requiring external module @babel/register
    c:\users\jgroman\documents\junctest\gulpfile.babel.js:1
    (function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                                         ^^^^
    
    SyntaxError: Unexpected identifier
        at new Script (vm.js:80:7)
        at createScript (vm.js:274:10)
        at Object.runInThisContext (vm.js:326:10)
        at Module._compile (internal/modules/cjs/loader.js:664:28)
        at Module._compile (c:\users\jgroman\documents\junctest\node_modules\pirates\lib\index.js:99:24)
        at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
        at Object.newLoader [as .js] (c:\users\jgroman\documents\junctest\node_modules\pirates\lib\index.js:104:7)
        at Module.load (internal/modules/cjs/loader.js:600:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
        at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by jgroman** [comment]
@loganfsmyth Unfortunately I was not able to get it working using your suggested fix. Maybe there's some other problem in play?

    c:\project\test>gulp --require ./babel-register.js
    [10:27:28] Requiring external module ./babel-register.js
    [10:27:28] Requiring external module @babel/register
    C:\Users\jgroman\Documents\Project\test\gulpfile.babel.js:1
    (function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                                         ^^^^
    
    SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    ...

**Comment by loganfsmyth** [comment]
> Does that mean that Babel considers symlinked win10 directory different from the original source directory and thus being "outside" working directory?

Yes exactly. 

> Maybe there's some other problem in play?

Yes I realize that I should have mentioned one other thing. .babelrc config files a) only apply to files in child directories b) need to be in a folder Babel expects .babelrc configs to be in. 

Like the other case, since Babel sees the file as outside of your project, there is no way for a .babelrc to apply to it. This is why Babel 7 added support for project-wide/file-path-independent configuration that can be loaded from a babel.config.js. you can read more at https://babeljs.io/docs/en/config-files#project-wide-configuration
