### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by clsferguson** [babel/babel#9862]
## Bug Report

**Current Behavior**
Trying to run a npm server that uses babel-cli and it crashes

**Input Code**
https://github.com/Michaelvilleneuve/lg-netcast-control

```$ npm start

> lg-control@1.0.0 start C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control
> nodemon app.js --exec ./node_modules/babel-cli/bin/babel-node.js --presets node6

[nodemon] 1.18.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `./node_modules/babel-cli/bin/babel-node.js app.js --presets node6`
[nodemon] app crashed - waiting for file changes before starting...
```

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: npm 6.7.0
- OS: Docker toolkit on windows 10
- How you are using Babel: CLI

![error](https://user-images.githubusercontent.com/48876201/56237237-b6a9bd80-6048-11e9-8ccf-567c6cdb8c52.jpg)

**Comment by nicolo-ribaudo** [comment]
This is the file which crashes:

https://unpkg.com/babel-cli@6.26.0/bin/babel-node.js
```js
#!/usr/bin/env node

require("../lib/babel-node");
```

Doesn't node support `#!` syntax on windows?
Maybe your file isn't run throught node, try using this instead:
```
nodemon app.js --exec node ./node_modules/babel-cli/bin/babel-node.js --presets node6
```

**Comment by clsferguson** [comment]
I am running it in a docker terminal.

so i tried the command line you posted and this is what is logged.


$ nodemon app.js --exec node ./node_modules/babel-cli/bin/babel-node.js --presets node6
[nodemon] 1.18.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting node app.js ./node_modules/babel-cli/bin/babel-node.js --presets node6
C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\app.js:1
import express from 'express';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
[nodemon] app crashed - waiting for file changes before starting...

**Comment by nicolo-ribaudo** [comment]
That error means that Babel is now working correctly, but it isn't configured to transpile that file. I'm not sure about how nodemon works but looking at some examples online it looks like `app.js` should be the last argument:

```
nodemon --exec node ./node_modules/babel-cli/bin/babel-node.js --presets node6 ./app.js
```

**Comment by clsferguson** [comment]
ok, so i modified package.json in the lg-control folder to the line you posted. i no longer get a run time error. but this pops up in the log

$ npm start

> lg-control@1.0.0 start C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control
> nodemon --exec node ./node_modules/babel-cli/bin/babel-node.js --presets node6 ./app.js

[nodemon] 1.18.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./node_modules/babel-cli/bin/babel-node.js --presets node6 ./app.js`
C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "stage-3" relative to directory "C:\\Users\\cferg\\AppData\\Roaming\\npm\\node_modules\\lg-control"
    at C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\cferg\AppData\Roaming\npm\node_modules\lg-control\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:666:32)
[nodemon] app crashed - waiting for file changes before starting...
